### ISSUE TITLE
crate error-chain is no longer maintained

### ISSUE THREAD

**Issue by jiangliu** [kata-containers/kata-containers#100]
**Which feature do you think can be improved?**
According to the discussion,  Error-chain is no longer maintained(https://users.rust-lang.org/t/error-chain-is-no-longer-maintained/27561).  This may cause trouble to project maintenance. Should we switch to other error handling crates such as failure?

**How can it be improved?**

Find a new error handling crate.

**Comment by jodh-intel** [comment]
Good catch @jiangliu. I took a look at https://crates.io/crates/failure a while back. It looked interesting but has usability issues fwics.

I haven't looked at them yet, but apparently these two crates are worth considering:

- https://crates.io/crates/thiserror
- https://crates.io/crates/anyhow

**Comment by jiangliu** [comment]
> Good catch @jiangliu. I took a look at https://crates.io/crates/failure a while back. It looked interesting but has usability issues fwics.
> 
> I haven't looked at them yet, but apparently these two crates are worth considering:
> 
> * https://crates.io/crates/thiserror
> * https://crates.io/crates/anyhow

How about hand-writing error codes? error-chain is some kind of magic, and not so easy when navigating the source code.

**Comment by liubin** [comment]
Now anyhow  has been adopted by https://github.com/kata-containers/kata-containers/pull/642 , close this issue.
