### ISSUE TITLE
tests: tdx: Get authenticated image pull tests working for TDX

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#10011]
In initial testing of the authenticated image pull https://github.com/kata-containers/kata-containers/pull/9904
The positive test for TDX works, but the negative tests are both failing with:
```
assert_logs_contain "${node}" kata "${node_start_time}" "failed to pull manifest Not authorize"' failed
```
,but I can see in the log that the message is there:
```
# Jul 15 08:45:14 [984fee00bd70.jf.intel.com](http://984fee00bd70.jf.intel.com/) kata[3896558]: time="2024-07-15T08:45:14.391889998-07:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = failed to pull manifest Not authorized:
```
I'm not sure if there could be an issue related to the `node`, or `node_start_time` being missing or something else, but it's difficult to check this without having access to the system.

**Comment by ChengyuZhu6** [comment]
https://github.com/kata-containers/kata-containers/pull/10031

**Comment by ChengyuZhu6** [comment]
This issue not only occurred in the authenticated image pull tests but was also found in the trusted storage tests.

**Comment by BbolroC** [comment]
The same failure is happening for IBM SE: https://github.com/kata-containers/kata-containers/actions/runs/10017693261/job/27692208889 The test passes when I run the test while staying in a ssh session, but no success in a scheduled cron job. I am expecting the PR by @ChengyuZhu6 will fix the issue on SE as well. 😉

**Comment by BbolroC** [comment]
It seems #10031 cannot solve the issue on IBM SE. Interestingly, it failed for the first run, but second run. This kind of behaviour has been observed for the past 3 days. I was told by @ryansavino that SEV is also struggling with a similar issue. I will reopen this issue and look into the machine.

**Comment by BbolroC** [comment]
Update: the nightly test passed if the journal was reset at the start of the job. I don't know why yet, but it explains that the 1st run always fails (almost 23h have passed since the last run) while the 2nd run (manually triggered) passes. I will figure out a root cause today. Thanks.
