### ISSUE TITLE
Remove unused variables from runtime's Makefile

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1003]
**Which feature do you think can be improved?**

There's at least a few cases of variables set on Makefile that are never used, such as "SHIMPATH" (and, consequently, "SHIMCMD").

**How can it be improved?**

One could do a fine check on which are the non-used variables and remove them entirely.

**Additional Information**

This is a good first issue for a newcomer, and that's the reason I'm opening this.
Please, consider leaving this one for newcomers to the project.

**Comment by jodh-intel** [comment]
@fidencio - This sounds like a good idea. I wonder in fact whether we can take this further and add a static check for Makefiles to:

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh
- https://github.com/kata-containers/tests/blob/2.0-dev/.ci/static-checks.sh

We could set `MAKEFLAGS=--warn-undefined-variables` in the CI scripts but that will simply emit a warning message which can't be "caught" unless we ran the CI using `script(1)`, say.

We could also look at https://github.com/mrtazz/checkmake and alternatives.

**Comment by littlejawa** [comment]
I have made a PR for that.
@jodh-intel - I also made a script to identify the variables that are initialized but not used, but I guess we need an issue on the "test" repository to add it as part of the static-checks.sh ?
