### ISSUE TITLE
kata-monitor needs version option

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#1004]
[`kata-monitor`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/kata-monitor/main.go) is missing a `--version` option, which all components need.

The PR that fixes this needs to also update https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/data/kata-collect-data.sh.in to include the output of `kata-monitor --version`, and maybe `kata-runtime kata-env` should include it too?

**Comment by liubin** [comment]
I think add `--version` for `kata-monitor` is better.

`kata-runtime` dose't depend on `kata-monitor`, and `kata-monitor` may be moved out from `src/runtime` as a separated tools as it's growthing.

`kata-runtime kata-env` should only show things it depends on.

**Comment by jodh-intel** [comment]
> kata-runtime kata-env should only show things it depends on.

@liubin - agreed - let's just update `kata-monitor` and `kata-collect-data.sh`.
