### ISSUE TITLE
Move gh/zvonkok/container-device-interface-rs to gh/kata-containers/container-device-interface

### ISSUE THREAD

**Issue by zvonkok** [kata-containers/kata-containers#10059]
We recently added initial support for CDI in Rust with https://github.com/zvonkok/container-device-interface-rs. Now that the initial version works with the kata-agent we want to donate cdi-rs to the Kata community and have it hosted under the kata-containers umbrella in github. 

This would be part of the first phase in rolling out better supporting CDI with Rust. After a grace period and thorough testing and running in production workloads a second phase may involve  donating the CDI Rust implementation to the official CNCF  CDI project at: https://github.com/cncf-tags/container-device-interface

We haven't added any copyright statement to each of the files, but we're planning to add the Apache License to this project, which most of the open-source projects have, including https://github.com/cncf-tags/container-device-interface. 

We need to ensure that we can use the software as is in Kata and keep open the possibility of easily donating the project to the CNCF CDI project. 

Having said that, the highest priority for now is to ensure that it is adequately supported in Kata and Confidential Containers.

**Comment by elezar** [comment]
Thanks @zvonkok. I think if you're willing to sheppard the CDI-rs repository in `tags.cncf.io`, then we could raise the issue of moving the repo sooner rather than later. As you say, the appropriate licence (Apache) would be a prerequisite.

**Comment by zvonkok** [comment]
This is done we're now hosted at https://github.com/cncf-tags/container-device-interface-rs
