### ISSUE TITLE
`src/libs/protocols` does not compile natively on darwin

### ISSUE THREAD

**Issue by burgerdev** [kata-containers/kata-containers#10071]
# Description of problem

I'm trying to get the `genpolicy` tool to build with target platform darwin. As far as I can tell, there's no inherent reason for this not to work - it's a dev tool that's not necessarily run in a cluster. However, one of the internal deps does not compile:

```sh
git checkout 162a6b44f67e1fc381db5144e93aba53bc951a6f   # <-- somewhat recent HEAD of main
cd src/libs/procotols
cargo build
```

# Expected result

Successful compilation.

# Actual result

```data
[...]
error[E0308]: mismatched types
   --> protocols/src/trans.rs:316:52
    |
316 |             FileMode: from.file_mode.map_or(0, |v| v),
    |                                                    ^ expected `u32`, found `u16`
    |
help: you can convert a `u16` to a `u32`
    |
316 |             FileMode: from.file_mode.map_or(0, |v| v.into()),
    |                                                     +++++++

error[E0308]: mismatched types
   --> protocols/src/trans.rs:726:29
    |
726 |             file_mode: Some(from.FileMode()),
    |                        ---- ^^^^^^^^^^^^^^^ expected `u16`, found `u32`
    |                        |
    |                        arguments to this enum variant are incorrect
    |
help: the type constructed contains `u32` due to the type of the argument passed
   --> protocols/src/trans.rs:726:24
    |
726 |             file_mode: Some(from.FileMode()),
    |                        ^^^^^---------------^
    |                             |
    |                             this argument influences the type of `Some`
[...]
```

# Further information

Reason for this is that one of the OCI structs uses `libc::mode_t` as type of `fileMode`. However, `libc` contains definitions for the target platform, while the OCI struct in question is always Linux-specific (and [specified to be u32](https://github.com/opencontainers/runtime-spec/blob/v1.2.0/config-linux.md?plain=1#L138)).

This can be fixed by replacing the `libc` references with hard-coded values (`EPERM == 1` and `mode_t == u32`). 

@Apokleos: do I assume correctly that this is fixed by #9944?

**Comment by Apokleos** [comment]
Hi, @burgerdev Yeah, I updated the PR to fix this issue.

**Comment by Apokleos** [comment]
Hi @burgerdev As #9944 has been merged, and fixed this issue. 
it should be closed now.
