### ISSUE TITLE
genpolicy: Add state to policy

### ISSUE THREAD

**Issue by Redent0r** [kata-containers/kata-containers#10087]
Currently policy code is stateless. It would be helpful to add state to it. Having state would allow us to validate things like:
1. Pod sanbox name. See https://github.com/kata-containers/kata-containers/pull/9957#issuecomment-2204925209
2. Device mount locations.

Possible implementation:
1. Levarege regorus::Engine::add_data (save) and rego data namespace (load). See https://docs.rs/crate/regorus/latest
2. Let rego policy evaluation return a struct (eg https://github.com/microsoft/regorus/blob/regorus-v0.1.4/tests/aci/framework.rego#L103) that may instruct a state operation, rather than just returning a boolean. Eg: 
```
{
  allowed: boolean, 
  metadata: {
    [stateActionKey]: {
      name: String,
      key: String,
      action: String,
      value: Object
    }
  }
}
```

The metadata field could indicate state operations (add/update/remove). Which could then be executed by the agent. And then referenced later using data namespace.

Example of metadata actions and resulting state:

![image](https://github.com/user-attachments/assets/ea8df5f3-e12e-4fbb-b1d5-e270c255b10a)

Then you'd be able to retrieve the data from rego like so:
```
data.metadata.devices[target] 
data.metadata.matches[input.containerID]
```

**Comment by burgerdev** [comment]
Thanks for writing this up! I'm overall in favour of this approach, just one remark:

The `stateAction` looks a bit like a JSON Patch. Could we go all the way and return a list of patches, to make the mechanism more flexible? There's even a robust-looking crate for this: [json-patch](https://crates.io/crates/json-patch)). 

Using JSON Patch might also help reduce the things that the agent needs to know about the state, which is desirable imho, and would allow managing sub-resources (without replacing unrelated fields). 

An example for the rule that all init containers have to be created before a main container can run (overly simplified).

`StartContainer` returns a patch:

```json
[
  { "op": "test", "path": "/containers/a/phase", "value": "created" },
  { "op": "replace", "path": "/containers/a/phase", "value": "started" }
]
```

And then, in the CreateContainerRequest, we check

```rego
CreateContainerRequest {
  every c_name in p_container.prereqs {
    data.metadata.containers[c_name].phase == "started"
  }
}
```

**Comment by c3d** [comment]
I believe that this is a nice generalization of the problems outlined in #9957.

I'm a bit concerned about possible abuses. Consider the example of a pod name. Can someone use it to inject bogus pod names with an attempt to escape filesystem boundaries (e.g. craft a pod name like `../../../bogus-name-used-for-malicious-purpose`)?

It's not very clear to me how complicated it becomes to express constraints in Rego that block nonsensical names with your scheme. Do you expect the users to explicitly insert `regex.match` statements themselves to restrict pod names, or is it something that would be there by default? In other words, would you expect the policy to define name filtering, or the agent?

**Comment by burgerdev** [comment]
> I believe that this is a nice generalization of the problems outlined in #9957.
> 
> I'm a bit concerned about possible abuses. Consider the example of a pod name. Can someone use it to inject bogus pod names with an attempt to escape filesystem boundaries (e.g. craft a pod name like `../../../bogus-name-used-for-malicious-purpose`)?

We already have such checks throughout `genpolicy`, but they are admittedly a bit hard to find.

* https://github.com/kata-containers/kata-containers/blob/528745fc88152e69e14b564b1a48ecb7a5835a82/src/tools/genpolicy/genpolicy-settings.json#L207
* https://github.com/kata-containers/kata-containers/blob/528745fc88152e69e14b564b1a48ecb7a5835a82/src/tools/genpolicy/genpolicy-settings.json#L132
* ... and more to come: #10050 

One of the reasons why we wanted stateful policy is because it allows us to make these checks even tighter. @danmihai1 gives an example in https://github.com/kata-containers/kata-containers/pull/9957#issuecomment-2204925209.

> It's not very clear to me how complicated it becomes to express constraints in Rego that block nonsensical names with your scheme. Do you expect the users to explicitly insert `regex.match` statements themselves to restrict pod names, or is it something that would be there by default? In other words, would you expect the policy to define name filtering, or the agent?

Preventing path traversal and bogus names should be fully automated by the genpolicy tool, so part of the policy. Afaiu the agent's role here is only to pass state from one query to the next, without interpreting it. On the other hand, I would see value in reducing the attack surface in the agent as well, for example by explicitly filtering fields that should not be interpreted before processing requests (`OCI.Annotations` comes to mind).

**Comment by inatatsu** [comment]
@Redent0r Do you think this feature can be extended to store status other than validated inputs, such as a process exit code? A use case I imagine is enforcing that an application container is started after successful completion of init containers. For example, a service mesh such as [Istio](https://istio.io/) may want to ensure that an `istio-init` container has deployed iptables chains to redirect traffics to an `istio-proxy` container to enforce TLS. To validate whether the `istio-init` container has completed, it is convenient if we can store a [WaitProcessResponse](https://github.com/kata-containers/kata-containers/blob/9ef59488d9d7424a9dd6ac44de348e445c7f9944/src/libs/protocols/protos/agent.proto#L151-L153) into regorus.

**Comment by c3d** [comment]
> We already have such checks throughout `genpolicy`, but they are admittedly a bit hard to find.
> 
> * https://github.com/kata-containers/kata-containers/blob/528745fc88152e69e14b564b1a48ecb7a5835a82/src/tools/genpolicy/genpolicy-settings.json#L207
> * https://github.com/kata-containers/kata-containers/blob/528745fc88152e69e14b564b1a48ecb7a5835a82/src/tools/genpolicy/genpolicy-settings.json#L132
> * ... and more to come: [genpolicy: hardening some agent requests #10050](https://github.com/kata-containers/kata-containers/pull/10050)

Thanks. That seems like a reasonable choice. This lends substance to the claim that there may be some value in having an incremental value to policies (JSON patch or something similar), to split policies that are "distro", "company" or "workload" level (hoping that the meaning of such levels is clear).

> 
> One of the reasons why we wanted stateful policy is because it allows us to make these checks even tighter. @danmihai1 gives an example in [#9957 (comment)](https://github.com/kata-containers/kata-containers/pull/9957#issuecomment-2204925209).

Ah, makes sense. Thanks!

> Preventing path traversal and bogus names should be fully automated by the genpolicy tool, so part of the policy. Afaiu the agent's role here is only to pass state from one query to the next, without interpreting it. On the other hand, I would see value in reducing the attack surface in the agent as well, for example by explicitly filtering fields that should not be interpreted before processing requests (`OCI.Annotations` comes to mind).

Now I understand the value of `genpolicy` a bit better. It's not just a matter of ease of use, there is some upcoming automation that this makes possible as well.

**Comment by c3d** [comment]
> @Redent0r Do you think this feature can be extended to store status other than validated inputs, such as a process exit code?

The idea sounds interesting, but I wonder when the agent is supposed to evaluate policy files. I was not under the impression that this would happen on process exit. If this does not happen, then how to we record the exit status?

> A use case I imagine is enforcing that an application container is started after successful completion of init containers. For example, a service mesh such as [Istio](https://istio.io/) may want to ensure that an `istio-init` container has deployed iptables chains to redirect traffics to an `istio-proxy` container to enforce TLS. To validate whether the `istio-init` container has completed, it is convenient if we can store a [WaitProcessResponse](https://github.com/kata-containers/kata-containers/blob/9ef59488d9d7424a9dd6ac44de348e445c7f9944/src/libs/protocols/protos/agent.proto#L151-L153) into regorus.

That made my mind go off-tangent. Where can the data come from and how do we collect it.

Here are a few random ideas that are deliberately a bit far-fetched, just to get the thinking going:

* Can we collect metrics data, e.g. to set a resource limit based on the initial data set size? Something like: if a container uses 1G after boot, then it should never use more than 2G?
* RBAC or other user information, something like: "allow `kubectl exec` Iff the user role has this or that attribute"
* Time-based / event-based, something like: "every 5 minutes, check this or that condition"

**Comment by danmihai1** [comment]
> @Redent0r Do you think this feature can be extended to store status other than validated inputs, such as a process exit code? A use case I imagine is enforcing that an application container is started after successful completion of init containers. For example, a service mesh such as [Istio](https://istio.io/) may want to ensure that an `istio-init` container has deployed iptables chains to redirect traffics to an `istio-proxy` container to enforce TLS. To validate whether the `istio-init` container has completed, it is convenient if we can store a [WaitProcessResponse](https://github.com/kata-containers/kata-containers/blob/9ef59488d9d7424a9dd6ac44de348e445c7f9944/src/libs/protocols/protos/agent.proto#L151-L153) into regorus.

I agree that we might want Policy to have access to the WaitProcessResponse information - and maybe to information from other Responses too. I look at this an additional/future improvement, after we add basic policy state support.

The init containers example makes sense to me. Another example would be to deny the execution of more than one instance of a single container in a pod.

**Comment by inatatsu** [comment]
@c3d Thank you for your comments. I think the stateful policy targets to validate an entire pod rather than each agent API call. If a policy can validate that a preceding init container successfuly completed when starting an application container, it can ensure that some security setup by the init container is done.

As you point out, a process exit status is currently not available at policy evaluation time. But a kubelet watches the status of an init container and eventually it will kick `WaitProcess()` Kata agent API call. By storing the returned `WaitProcessResponse` into regolus [after validating a `WaitProcessRequest`](https://github.com/kata-containers/kata-containers/blob/230aefc0dac59c1c0ae23633f942355a2cec1a32/src/agent/src/rpc.rs#L757-L758), I think a policy can refer the exit code of a preceding init container when starting an application container.

**Comment by danmihai1** [comment]
> > @Redent0r Do you think this feature can be extended to store status other than validated inputs, such as a process exit code?
> 
> The idea sounds interesting, but I wonder when the agent is supposed to evaluate policy files. I was not under the impression that this would happen on process exit. If this does not happen, then how to we record the exit status?

I agree this is not possible with today's Kata Agent. But theoretically, the Kata Agent could call into the Policy rules pretty much whenever it wants. 

As usual, when adding such features we have to balance:
1. Possibly intrusive changes to the Agent.
2. Run time performance.
3. Policy base64 format text being limited by the maximum size of k8s annotations.
4. Etc.

Tracking the state of a container seems useful enough to investigate the possibility of adding this feature in future versions of the Agent.

**Comment by Redent0r** [comment]
> Thanks for writing this up! I'm overall in favour of this approach, just one remark:
> 
> The `stateAction` looks a bit like a JSON Patch. Could we go all the way and return a list of patches, to make the mechanism more flexible? There's even a robust-looking crate for this: [json-patch](https://crates.io/crates/json-patch)).
> 
> Using JSON Patch might also help reduce the things that the agent needs to know about the state, which is desirable imho, and would allow managing sub-resources (without replacing unrelated fields).
> 
> An example for the rule that all init containers have to be created before a main container can run (overly simplified).
> 
> `StartContainer` returns a patch:
> 
> ```json
> [
>   { "op": "test", "path": "/containers/a/phase", "value": "created" },
>   { "op": "replace", "path": "/containers/a/phase", "value": "started" }
> ]
> ```
> 
> And then, in the CreateContainerRequest, we check
> 
> ```rego
> CreateContainerRequest {
>   every c_name in p_container.prereqs {
>     data.metadata.containers[c_name].phase == "started"
>   }
> }
> ```

Sorry for the delay here... Thanks for the suggestion @burgerdev ! we did end up adopting json-patch in the end. I just created a new draft PR in https://github.com/kata-containers/kata-containers/pull/10431 , if you get a chance :)
