### ISSUE TITLE
tests: k8s: exec_host() doesn't work sometimes

### ISSUE THREAD

**Issue by danmihai1** [kata-containers/kata-containers#10081]
I have seen two recent examples - both on ppc64le for some reason that I don't understand:

https://github.com/kata-containers/kata-containers/actions/runs/10103276831/job/27940923619?pr=10075

2024-07-26T00:37:42.2314124Z not ok 3 Liveness tcp probe
2024-07-26T00:37:42.2332744Z # (from function `setup_common' in file tests_common.sh, line 50,
2024-07-26T00:37:42.2340589Z #  from function `setup' in test file k8s-liveness-probes.bats, line 17)
2024-07-26T00:37:42.2347320Z #   `setup_common' failed with status 2
2024-07-26T00:37:42.2356374Z # warning: couldn't attach to pod/node-debugger-ltc22u23-25dbd, falling back to streaming logs:
2024-07-26T00:37:42.2364462Z # pod "node-debugger-ltc22u23-25dbd" deleted
2024-07-26T00:37:42.2376675Z # /home/ubuntu/runner/_layout/_work/kata-containers/kata-containers/tests/integration/kubernetes/tests_common.sh: line 126: **return: 2024-07-26**: numeric argument required
2024-07-26T00:37:42.2390978Z # error: arguments in resource/name form must have a single resource and name
2024-07-26T00:37:42.2397614Z # error: resource name may not be empty

https://github.com/kata-containers/kata-containers/actions/runs/10081452068/job/27875337788?pr=10051

2024-07-24T18:36:36.0167779Z not ok 1 Test readonly volume for pods
2024-07-24T18:36:36.0194687Z # (from function `setup' in test file k8s-file-volume.bats, line 19)
2024-07-24T18:36:36.0205229Z #   `tmp_file=$(exec_host "$node" mktemp /tmp/file-volume-test-foo.XXXXX)' failed with status 2
2024-07-24T18:36:36.0216252Z # warning: couldn't attach to pod/node-debugger-ltc22u23-b7nxv, falling back to streaming logs:
2024-07-24T18:36:36.0224729Z # pod "node-debugger-ltc22u23-b7nxv" deleted
2024-07-24T18:36:36.0239534Z # /home/ubuntu/runner/_layout/_work/kata-containers/kata-containers/tests/integration/kubernetes/tests_common.sh: line 126: **return: /tmp/file-volume-test-foo.7BDfg**: numeric argument required

It looks like sometimes exec_host() tries to return a string that was part of the output of the command that was executed, instead of the exit code that exec_host() wanted to echo.

**Comment by ChengyuZhu6** [comment]
Hey @danmihai1 . I encountered the similar issue on TDX CI, which might be helpful for you: https://github.com/kata-containers/kata-containers/pull/10031

**Comment by GabyCT** [comment]
when the test fails we can not see anything in the output, when the test pass we can see 0

**Comment by GabyCT** [comment]
@danmihai1 so I reproduce this locally and what I notice is that for example
```
command="mktemp /tmp/file-volume-test-foo.XXX$RANDOM"
kubectl debug -qi "node/${node}" --image=ghcr.io/linuxcontainers/alpine:latest -- chroot /host bash -c "${command}" | tr -d '\r'
```
sometimes it works and sometimes it does not, I took this example from the https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-file-volume.bats#L19 which is failing randomly. I took a look for example to the `node` and seems that is there:
```
$ kubectl get node
NAME        STATUS   ROLES                  AGE   VERSION
testdebug   Ready    control-plane,master   28h   v1.29.6+k3s2
```
I also took a look to the existing `debugger pods` with
```
NAMESPACE                   NAME                                     READY   STATUS      RESTARTS        AGE
coco-tenant                 kbs-6dd449bf96-5t86n                     1/1     Running     1 (3h14m ago)   28h
kata-containers-k8s-tests   node-debugger-testdebug-6p5fx            0/1     Completed   0               27m
```
*** This existing debugger pods can change its status to Running when the command above (the `kubectl debug ...)` exits 0 to Error when it does not give an output, here it is an example of the `kubectl describe pod` when an error happened
```
Containers:
  debugger:
    Container ID:  containerd://e7b0d6b54518b9c5e2ce887c36a6845ca10eb7b4ff0bd00b3c1296d0b5ab87e9
    Image:         ghcr.io/linuxcontainers/alpine:latest
    Image ID:      ghcr.io/linuxcontainers/alpine@sha256:3a2408bd8927ead9a414fa20e05bb5d13cd9329d6fcfa2ade9a26cce1e79ba4a
    Port:          <none>
    Host Port:     <none>
    Command:
      chroot
      /host
      bash
      -c
      /tmp/file-volume-test-foo.NQzEr
    State:          Terminated
      Reason:       Error
      Exit Code:    126
      Started:      Fri, 02 Aug 2024 20:38:28 +0000
      Finished:     Fri, 02 Aug 2024 20:38:28 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host from host-root (rw)
```
https://github.com/kata-containers/kata-containers/blob/aadde2c25be116d865d6102abbeec1b731b4b2b2/tests/integration/kubernetes/tests_common.sh#L96

Not sure if we need for example to do retries until we have an output or a pod in Completed status will help this situation, wdyt @danmihai1

**Comment by danmihai1** [comment]
Great investigation, thanks @GabyCT !

My guess is that it would be helpful to avoid terminating the debug container prematurely. So I would try:

1. Start the debug pod using:

 kubectl debug -iq node/aks-nodepool1-20465909-vmss000000 --image=ghcr.io/linuxcontainers/alpine:latest -- /bin/sh -c **"sleep 5m" &**

2. Get the pod name from "kubectl get pods" - exec_host() already does that, but it should retry if we'll use this model.

3. **Execute the desired command with "kubectl exec" in the new debug pod** - and capture the exit code from the kubectl exec output.

4. Kill the debug pod - as exec_host() already does.

I am cautiously optimistic about these steps because we are successfully using the same "start container + kubectl exec + kill container" pattern in several tests already.

Cc: @sprt in case he has better ideas.

**Comment by GabyCT** [comment]
@danmihai1 yes I can try on monday to have this...I will put the test in a for loop so we can exercise this and see no failures

**Comment by GabyCT** [comment]
@danmihai1 so I try to do your suggestion, however, seems like it is not that easy. For example I modified the https://github.com/kata-containers/kata-containers/blob/aadde2c25be116d865d6102abbeec1b731b4b2b2/tests/integration/kubernetes/tests_common.sh#L96 to the following
```
exec_host() {
        node="$1"
        # `kubectl debug` always returns 0, so we hack it to return the right exit code.
        command="${@:2}"

        # Get the already existing debugger pods.
        declare -a old_debugger_pods=( $(kubectl get pods -o name | grep node-debugger) )

        # We're trailing the `\r` here due to: https://github.com/kata-containers/kata-containers/issues/8051
        # tl;dr: When testing with CRI-O we're facing the following error:
        # ```
        # (from function `exec_host' in file tests_common.sh, line 51,
        # in test file k8s-file-volume.bats, line 25)
        # `exec_host "echo "$file_body" > $tmp_file"' failed with status 127
        # [bats-exec-test:38] INFO: k8s configured to use runtimeclass
        # bash: line 1: $'\r': command not found
        # ```
 
       # 1 Ran the debug pods
        kubectl debug -qi "node/${node}" --image=quay.io/bedrock/ubuntu:latest -- chroot /host bash -c "sleep 5m" &
        sleep 5

       # 2 Get the running pod name
        running_pod_name=$(kubectl get pods -o name | grep node-debugger)
        kubectl wait --timeout="30s" --for=condition=ready "${running_pod_name}"

       # 3 execute the command desired
        kubectl exec -q "${running_pod_name}" -- ${command}
        exit_code=$(echo $?)

        # Get the updated list of debugger pods.
        declare -a new_debugger_pods=( $(kubectl get pods -o name | grep node-debugger) )

       for new_pod in "${new_debugger_pods[@]}"; do
               delete_pod_if_new "${new_pod}" "${old_debugger_pods[@]}"
       done

        return ${exit_code}
}
```
The main problem with that is for example the https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-file-volume.bats. For example while executing https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-file-volume.bats#L19 it will create a `pod-debugger`. Now will performing the `kubectl exec` is an issue in that example one of the steps is to create a `tmp file`, if we keep the code that I paste at the beggining, the output of the `tmp file` will change to
```
pod/node-debugger-testdebug-pdq76 condition met
```
In general the whole logic will change and that will impact all the tests that have this .

**Comment by danmihai1** [comment]
Thanks for looking into this, @GabyCT !

I agree that polluting the output that way is problematic. Is it realistic to filter out that additional text?

Otherwise, maybe someday we'll find a way to pick up the output of debug pods being terminated. I don't have any good ideas here.

**Comment by sprt** [comment]
@GabyCT IIRC why not do this in your updated function>

```shell
kubectl wait --timeout="30s" --for=condition=ready "${running_pod_name}" > /dev/null
```

**Comment by GabyCT** [comment]
> @GabyCT IIRC why not do this in your updated function?
> 
> ```shell
> kubectl wait --timeout="30s" --for=condition=ready "${running_pod_name}" > /dev/null 2>&1
> ```

yes we can do that thanks

**Comment by GabyCT** [comment]
@sprt @danmihai1 the issue gets more complicated, we can filter out the output of the function, however, when we ran
```
kubectl debug -qi "node/${node}" --image=quay.io/bedrock/ubuntu:latest -- chroot /host bash -c "sleep 5m" &
``` 
We got a pod running were we are doing some `exec` but if you look out the tests you were using the `exec_host` function to perform functions inside one pod in particular, with the current steps above we are creating `pods` with different names and when you are for example to try to find a `tmp` file inside the first pod where you create it ...well you will not find out as that pod is not longer existing

**Comment by sprt** [comment]
@GabyCT Hmm not sure I understand the issue. In the code below we're creating the temp file on the host, so any pod should be able to see it.

https://github.com/kata-containers/kata-containers/blob/99730256a2899c82d111400024621519d17ea15d/tests/integration/kubernetes/k8s-file-volume.bats#L19

Can you show an output of what you mean?

**Comment by BbolroC** [comment]
This happens frequently on s390x as well: https://github.com/kata-containers/kata-containers/issues/10155

**Comment by BbolroC** [comment]
FYI: I didn't run into any problem to get a expected result with the following:

```bash
#!/bin/bash -ex

delete_pod_if_new() {
    declare -r new_pod="$1"
    shift
    declare -r old_pods=("$@")

    for old_pod in "${old_pods[@]}"; do
        [ "${old_pod}" == "${new_pod}" ] && return 0
    done

    kubectl delete "${new_pod}" >&2
}

get_one_kata_node() {
    local resource_name
    resource_name="$(kubectl get node -o name | head -1)"
    # Remove leading "/node"
    echo "${resource_name/"node/"}"
}

exec_host() {
        node="$1"
        command="${@:2}"

        declare -a old_debugger_pods=( $(kubectl get pods -o name | grep node-debugger) )

       # 1 Ran the debug pods
        kubectl debug -q "node/${node}" --image=quay.io/bedrock/ubuntu:latest -- chroot /host bash -c "sleep 5m"

       # 2 Get the running pod name
        running_pod_name=$(kubectl get pods -o name | grep node-debugger)
        kubectl wait --timeout="30s" --for=condition=ready "${running_pod_name}" > /dev/null 2>&1

       # 3 execute the command desired
        kubectl exec -q "${running_pod_name}" -- ${command}
        exit_code=$(echo $?)

        # Get the updated list of debugger pods.
        declare -a new_debugger_pods=( $(kubectl get pods -o name | grep node-debugger) )

       for new_pod in "${new_debugger_pods[@]}"; do
               delete_pod_if_new "${new_pod}" "${old_debugger_pods[@]}"
       done

        return ${exit_code}
}

node="$(get_one_kata_node)"
tmp_file=$(exec_host "$node" mktemp /tmp/file-volume-test-foo.XXXXX)
```

Here is log for it:

```
++ get_one_kata_node
++ local resource_name
+++ kubectl get node -o name
+++ head -1
++ resource_name=node/kind-control-plane
++ echo kind-control-plane
+ node=kind-control-plane
++ exec_host kind-control-plane mktemp /tmp/file-volume-test-foo.XXXXX
++ node=kind-control-plane
++ command='mktemp /tmp/file-volume-test-foo.XXXXX'
+++ kubectl get pods -o name
+++ grep node-debugger
++ old_debugger_pods=()
++ declare -a old_debugger_pods
++ kubectl debug -q node/kind-control-plane --image=quay.io/bedrock/ubuntu:latest -- chroot /host bash -c 'sleep 5m'
+++ kubectl get pods -o name
+++ grep node-debugger
++ running_pod_name=pod/node-debugger-kind-control-plane-4qtr7
++ kubectl wait --timeout=30s --for=condition=ready pod/node-debugger-kind-control-plane-4qtr7
++ kubectl exec -q pod/node-debugger-kind-control-plane-4qtr7 -- mktemp /tmp/file-volume-test-foo.XXXXX
+++ echo 0
++ exit_code=0
+++ kubectl get pods -o name
+++ grep node-debugger
++ new_debugger_pods=('pod/node-debugger-kind-control-plane-4qtr7')
++ declare -a new_debugger_pods
++ for new_pod in "${new_debugger_pods[@]}"
++ delete_pod_if_new pod/node-debugger-kind-control-plane-4qtr7
++ declare -r new_pod=pod/node-debugger-kind-control-plane-4qtr7
++ shift
++ old_pods=()
++ declare -r old_pods
++ kubectl delete pod/node-debugger-kind-control-plane-4qtr7
pod "node-debugger-kind-control-plane-4qtr7" deleted
++ return 0
+ tmp_file=/tmp/file-volume-test-foo.D1zfd
```
