### ISSUE TITLE
Hitting Rate-Limit while pulling images from Docker on CI nodes

### ISSUE THREAD

**Issue by AdithyaKrishnan** [kata-containers/kata-containers#10100]
During days of debugging with multiple retries or days wherein multiple PRs are created, the AMD CI nodes are hitting rate limit errors causing tests to fail thereby preventing PRs from getting merged.

Example: https://github.com/kata-containers/kata-containers/actions/runs/10171601017/job/28133291133#step:7:6542

Error: Failed to pull image "busybox": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/busybox/manifests/sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Solution is to migrate away from docker or perform some sort of load balancing.

**Comment by ChengyuZhu6** [comment]
We might need to switch the image to `quay.io/prometheus/busybox:latest` to resolve the issue.

**Comment by AdithyaKrishnan** [comment]
@ChengyuZhu6 
That's what we did and just opened a PR for it : https://github.com/kata-containers/kata-containers/pull/10101
Requesting you to please review
