### ISSUE TITLE
Can't set up loop device with `exec_host`

### ISSUE THREAD

**Issue by ChengyuZhu6** [kata-containers/kata-containers#10133]
# Description of problem

I can't use `exec_host $node "losetup -fP $loop_file" to create a loop device for testing. Error log in CI:
- https://github.com/kata-containers/kata-containers/actions/runs/10267144487/job/28408713802?pr=9999#:~:text=not%20ok%203,1490
- https://github.com/kata-containers/kata-containers/actions/runs/10267144487/job/28408715000?pr=9999#:~:text=not%20ok%203,1480

 I have reproduced it and debugged and found the error: 
```
$  loop_file="/tmp/trusted-image-storage.img"
$ exec_host $node "dd if=/dev/zero of=$loop_file bs=1M count=2500"
2500+0 records in
2500+0 records out
2621440000 bytes (2.6 GB, 2.4 GiB) copied, 2.60192 s, 1.0 GB/s
$ exec_host() {
        node="$1"
        # kubectl debug always returns 0, so we hack it to return the right exit code.
        command="${@:2}"
        command+='; echo -en \\n$?'

        # Get the already existing debugger pods.
        declare -a old_debugger_pods=( $(kubectl get pods -o name | grep node-debugger) )

        # We're trailing the \r here due to: https://github.com/kata-containers/kata-containers/issues/8051
        # tl;dr: When testing with CRI-O we're facing the following error:
        # 
# (from function `exec_host' in file tests_common.sh, line 51,
        # in test file k8s-file-volume.bats, line 25)
        # `exec_host "echo "$file_body" > $tmp_file"' failed with status 127
        # [bats-exec-test:38] INFO: k8s configured to use runtimeclass
        # bash: line 1: $'\r': command not found
        #

        output="$(kubectl debug -qit "node/${node}" --image=ghcr.io/linuxcontainers/alpine:latest -- chroot /host bash -c "${command}" | tr -d '\r')"

        # Get the updated list of debugger pods.
        declare -a new_debugger_pods=( $(kubectl get pods -o name | grep node-debugger) )

        exit_code="$(echo "${output}" | tail -1)"
        echo "$(echo "${output}" | head -n -1)"
        return ${exit_code}
}
$ exec_host $node "losetup -fP $loop_file"
losetup: /tmp/trusted-image-storage.img: failed to set up loop device: Operation not permitted`
```

I don't know how to set up loop device using `exec_host`, I would greatly appreciate any guidance you could provide. @sprt @wainersm @stevenhorsman @fidencio

**Comment by sprt** [comment]
Argh, I've seen this before with other commands. We'd need to SSH into the host, the chroot environment isn't enough. So I'd create a function `exec_host_ssh()` that executes a command through SSH using `exec_host()`.

**Comment by BbolroC** [comment]
Yeah, it seems there a security restriction on `kubectl debug` for running `losetup`.

Here is my workaround:

- `node-debugger.yaml` for mimicking a node debugger, but get it escalated to root:

```
apiVersion: v1
kind: Pod
metadata:
  name: node-debugger-custom
spec:
  containers:
  - name: node-debugger-container
    image: quay.io/bedrock/ubuntu:latest
    command: ["/bin/sh"]
    stdin: true
    tty: true
    securityContext:
      privileged: true
      runAsUser: 0
      allowPrivilegeEscalation: true
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
```

- `test.sh` which copies most of `exec_host()`, but uses `kubectl apply -f node-debugger.yaml` instead of `kubectl debug`

```
#!/bin/bash -ex

get_new_debugger_pod() {
    local old_pods=("$@")
    local new_pod_list=($(kubectl get pods -o name | grep node-debugger))

    for new_pod in "${new_pod_list[@]}"; do
        if [[ ! " ${old_pods[*]} " =~ " ${new_pod} " ]]; then
            echo "${new_pod}"
            return
        fi
    done
}

get_one_kata_node() {
    local resource_name
    resource_name="$(kubectl get node -o name | head -1)"
    # Remove leading "/node"
    echo "${resource_name/"node/"}"
}

exec_host() {
    local node="$1"
    local command="${@:2}"
    command+='; echo -en \\n$?'

    # Capture the list of existing debugger pods
    local old_debugger_pods=($(kubectl get pods -o name | grep node-debugger))

    # Run the debug pod
    kubectl apply -f node-debugger.yaml

    # Identify the new debugger pod
    local new_debugger_pod=$(get_new_debugger_pod "${old_debugger_pods[@]}")

    # Wait for the newly created pod to be ready
    kubectl wait --timeout="30s" --for=condition=ready "${new_debugger_pod}" > /dev/null

    # Execute the command and capture the output
    local output="$(kubectl exec -qi "${new_debugger_pod}" -- chroot /host bash -c "${command}" | tr -d '\r')"

    # Delete the newly created pod
    kubectl delete "${new_debugger_pod}" >&2

    # Output the command result
    local exit_code="$(echo "${output}" | tail -1)"
    echo "$(echo "${output}" | head -n -1)"
    return ${exit_code}
}

node="$(get_one_kata_node)"
loop_file="/tmp/trusted-image-storage.img"
exec_host $node "dd if=/dev/zero of=$loop_file bs=1M count=2500"
exec_host $node "losetup -fP $loop_file"
```

- Got the following result:

```
$ losetup -l
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                             DIO LOG-SEC
/dev/loop1         0      0         1  1 /var/lib/snapd/snaps/core20_2319.snap   0     512
/dev/loop6         0      0         0  0 /tmp/trusted-image-storage.img          0     512
/dev/loop4         0      0         1  1 /var/lib/snapd/snaps/snapd_19995.snap   0     512
/dev/loop2         0      0         1  1 /var/lib/snapd/snaps/lxd_24325.snap     0     512
/dev/loop0         0      0         1  1 /var/lib/snapd/snaps/core20_2017.snap   0     512
/dev/loop5         0      0         1  1 /var/lib/snapd/snaps/snapd_21760.snap   0     512
/dev/loop3         0      0         1  1 /var/lib/snapd/snaps/lxd_29381.snap     0     512
```

@ChengyuZhu6 @wainersm @stevenhorsman Is this something you guys are expecting? Thanks!

**Comment by sprt** [comment]
@BbolroC This sounds great to me if that solves this issue! Anything that we'd lose by going with this route?

Also maybe we could have this as a long running pod instead, to save the overhead of creating it every time. But only consider this a nice to have.

**Comment by BbolroC** [comment]
> Anything that we'd lose by going with this route?

I suggest going with this approach only for dealing with a loop device. Otherwise, I prefer to keep using `kubectl debug`. I’m not sure how this mimicking behavior will work in a negative way, so I would like to hear your opinion on this @wainersm @fidencio @stevenhorsman Thanks!

**Comment by BbolroC** [comment]
> Also maybe we could have this as a long running pod instead, to save the overhead of creating it every time. But only consider this a nice to have.

Thanks for the suggestion. It sounds great. Yes, we can consider this further within a resolution PR.

**Comment by ChengyuZhu6** [comment]
Thanks @BbolroC ! That’s an impressive attempt!
 
>I suggest going with this approach only for dealing with a loop device. Otherwise, I prefer to keep using kubectl debug. I’m not sure how this mimicking behavior will work in a negative way

I think we could use this approach to address specific needs that might not be easily achievable with `kubectl debug`, such as loop device management.  However, it requires careful consideration of the security implications, especially when mounting the entire host filesystem into the debug container. Since I’m not an expert on this, I agree that it would be valuable to hear from those with more experience.

**Comment by sprt** [comment]
@ChengyuZhu6 The current approach already mounts the host filesystem into the container, that's how we achieve running commands on the host easily. 🙂

@BbolroC I actually suggest using your approach instead of all invocations of `kubectl debug`. When developing, I usually SSH into the host from inside the debug container to workaround such situations, but your approach is much easier to set up in CI!

**Comment by ChengyuZhu6** [comment]
> @ChengyuZhu6 The current approach already mounts the host filesystem into the container, that's how we achieve running commands on the host easily. 🙂
> 
> @BbolroC I actually suggest using your approach instead of all invocations of `kubectl debug`. When developing, I usually SSH into the host from inside the debug container to workaround such situations, but your approach is much easier to set up in CI!

Got it, thanks for clarifying. If the code can be merged, I'll enable the trusted image storage in coco-dev job.

**Comment by stevenhorsman** [comment]
Sorry I'm late to this. Nothing much to add from me as people with more experience in this seem happy with this approach, so I am happy to see a PR with it and try it out. Thanks @BbolroC!
