### ISSUE TITLE
QEMU Version Adaptation

### ISSUE THREAD

**Issue by ccxiaop** [kata-containers/kata-containers#10150]
Can the CC-0.8.0 version be loaded with the qemu8.2 branch version? What is the main work of kata to adapt to different qemu versions? What needs to be done?

**Comment by fidencio** [comment]
> Can the CC-0.8.0 version be loaded with the qemu8.2 branch version? What is the main work of kata to adapt to different qemu versions? What needs to be done?

Do not use CC-* branches, those are unmaintaned and not supported anymore.
Refer to using our main branch, where we ship a built QEMU for SEV / SNP, and we rely on distro packages for Ubuntu / CentOS for TDX.

I'm closing the issue for now, but feel free to open a new one if you feel the need.
