### ISSUE TITLE
Default Qemu parameters incompatible with Qemu v9.0.2

### ISSUE THREAD

**Issue by Friz-zy** [kata-containers/kata-containers#10184]
# Description of problem

Kata runtime v1.11.5 configure Qemu parameters as `-machine pc,accel=kvm,kernel_irqchip` which incompatible with Qemu v9.0.2 (openSUSE Tumbleweed)

# Expected result

Working qemu vm

# Actual result

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: failed to launch qemu: exit status 1,
error messages from qemu log: qemu-system-x86_64: -machine pc,accel=kvm,kernel_irqchip: Expected '=' after parameter 'kernel_irqchip': unknown.
```

# Further information

Default Machine options located [there](https://github.com/kata-containers/kata-containers/blob/e0ae398a2eb8ea3391145d5904dc37db91ea8351/src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs#L393). I haven't found in the documentation or code a way to override it.

Potentially enabling [IOMMU or ConfidentialGuest](https://github.com/kata-containers/kata-containers/blob/e0ae398a2eb8ea3391145d5904dc37db91ea8351/src/runtime/virtcontainers/qemu_amd64.go#L106) will solve the problem, but I haven't tested it yet.

**Comment by fidencio** [comment]
@Friz-zy, kata runtime 1.x and 2.x are not supported anymore.
Please, give it a try with our latest release.

Also, we do ship our own version of QEMU as part of the tarball released as part of our release process.

I'm closing the issue for now, but feel free to open a new one in case you feel the need.

**Comment by Friz-zy** [comment]
My bad, didn't notice the opensuse repository was using an older version
