### ISSUE TITLE
Allow protobuf crate to be updated to support newer features

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#1019]
# Summary

It is too difficult to update the `protobuf` crate currently.

# Future plans

I'd like to make use of the `serde` derive support in the [`protobuf` crate](https://github.com/stepancheg/rust-protobuf#serde_derive-support).

# (Some) Details

We've pinned the `protobuf` crate to version `2.14.0` (mostly):

```sh
$ grep protobuf Cargo.toml */Cargo.toml
Cargo.toml:protobuf = "=2.14.0"
netlink/Cargo.toml:protobuf = { version = "=2.14.0", optional = true }
netlink/Cargo.toml:with-agent-handler = ["protobuf", "protocols"]
protocols/Cargo.toml:protobuf = "=2.14.0"
rustjail/Cargo.toml:protobuf = "2.8.1"
```

Currently it is very difficult to update to a newer version of this crate, due to the various components that all need to be updated together:

- `protoc`
- `protoc-gen-rust`
- `ttrpc_rust_plugin`

Attempting to upgrade everything to the latest versions currently fails for me with the following error (repeated for every `.proto` file):

```bash
   Compiling protocols v0.1.0 (/home/james/go/src/github.com/kata-containers/kata-containers/src/agent/protocols)
error: use of deprecated struct `protobuf::lazy::Lazy`: Please regenerate .rs files from .proto files to use newer APIs
   --> protocols/src/empty.rs:114:32
    |
114 |         static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D deprecated` implied by `-D warnings`
```

I *think* this might be due to https://github.com/containerd/ttrpc-rust not generating the correct code, but haven't actually looked closely at that yet. We are using a fixed release of ttrpc-rust, but even `master` fails fwics:

```bash
$ grep ttrpc protocols/Cargo.toml
ttrpc = { git = "https://github.com/containerd/ttrpc-rust.git", branch="0.3.0" }
```

/cc @lifupan, @liubin, @teawater, @Tim-Zhang.

**Comment by lifupan** [comment]
@Tim-Zhang  Please take a look and make the  protocol  files created dynamically   thus we can upgrade protobuf easily.

**Comment by Tim-Zhang** [comment]
@lifupan ok
