### ISSUE TITLE
Handle QEMU events in sandbox

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1026]
In #1013 , we can get guest panic event from QEMU, now this event is only used to dump guest memory.

It can be used further more, for example publish events to outside like `/tasks/create`/`/tasks/start`/`...`

**Comment by ariel-adam** [comment]
@liubin can you clarify this issue? what is the problem and what would you like to add?

**Comment by liubin** [comment]
No exciting usage of the events yet, close it.
