### ISSUE TITLE
kernel 5.10 kata 3.8.0 occur a error 'assignment to entry in nil map'

### ISSUE THREAD

**Issue by linjianshu** [kata-containers/kata-containers#10266]
[root@ccseagent-gpu ~]# uname -r 
5.10.0-136.12.0.88.2.ctl3.x86_64
[root@ccseagent-gpu ~]# uname -a
Linux ccseagent-gpu 5.10.0-136.12.0.88.2.ctl3.x86_64 #1 SMP Mon Jun 24 07:40:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
[root@ccseagent-gpu ~]# cat /etc/os-release 
NAME="CTyunOS"
VERSION="2"
ID="ctyunos"
VERSION_ID="2"
PRETTY_NAME="CTyunOS 2"
ANSI_COLOR="0;31"

Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.754311575+08:00" level=error msg="Failed to connect to QEMU instance" error="dial unix /run/vc/vm/te>
Sep 04 17:17:45 ccseagent-gpu kata[1043945]: time="2024-09-04T17:17:45.754311575+08:00" level=error msg="Failed to connect to QEMU instance" error="dial unix /run/vc/vm/test-kat>
Sep 04 17:17:45 ccseagent-gpu kata[1043945]: time="2024-09-04T17:17:45.754416713+08:00" level=warning msg="failed to resolve vm path" dir=/run/vc/vm/test-kata11 error="lstat /ru>
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.754416713+08:00" level=warning msg="failed to resolve vm path" dir=/run/vc/vm/test-kata11 error="lst>
Sep 04 17:17:45 ccseagent-gpu kata[1043945]: time="2024-09-04T17:17:45.756533701+08:00" level=error msg="failed to cleanup the &{%!s(*cgroups.cgroup=&{0x564a58f34f40 [0xc00007e8>
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.756533701+08:00" level=error msg="failed to cleanup the &{%!s(*cgroups.cgroup=&{0x564a58f34f40 [0xc0>
Sep 04 17:17:45 ccseagent-gpu kata[1043945]: time="2024-09-04T17:17:45.756832967+08:00" level=warning msg="failed to cleanup network" error="failed to get netns /var/run/netns/c>
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.756832967+08:00" level=warning msg="failed to cleanup network" error="failed to get netns /var/run/n>
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.759748099+08:00" level=info msg="shim disconnected" id=test-kata11
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.759802154+08:00" level=warning msg="cleaning up after shim disconnected" id=test-kata11 namespace=de>
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.759811584+08:00" level=info msg="cleaning up dead shim"
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.772365787+08:00" level=error msg="failed to delete" cmd="/usr/bin/containerd-shim-kata-v2 -namespace>
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.772443019+08:00" level=warning msg="failed to clean up after shim disconnected" error="time=\"2024-0>
Sep 04 17:17:45 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:45.772516564+08:00" level=error msg="copy shim log" error="read /proc/self/fd/17: file already closed"
Sep 04 17:17:52 ccseagent-gpu kata[1044007]: time="2024-09-04T17:17:52.807570417+08:00" level=warning msg="failed to resolve SNP certificates path: /opt/snp/cert_chain.cert" nam>
Sep 04 17:17:52 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:52.807570417+08:00" level=warning msg="failed to resolve SNP certificates path: /opt/snp/cert_chain.cer>
Sep 04 17:17:52 ccseagent-gpu kata[1044007]: time="2024-09-04T17:17:52.827587931+08:00" level=warning msg="Could not add /dev/mshv to the devices cgroup" name=containerd-shim-v2>
Sep 04 17:17:52 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:52.827587931+08:00" level=warning msg="Could not add /dev/mshv to the devices cgroup" name=containerd-s>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: panic: assignment to entry in nil map
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: goroutine 13 [running]:
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).siblingAnnotation(0xc0002211e0, {0xc00030bf>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1013 +0x1ab
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).annotateContainerWithVFIOMetadata(0xc000221>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:994 +0x6f4
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).create(0xc0002211e0, {0x55946e6286f0, 0xc00>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1045 +0x48b
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).createContainers(0xc00049d040, {0x55946e6286f>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:1899 +0x3d0
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.createSandboxFromConfig({_, _}, {0xc000120480, {0x0, 0x0>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/api.go:110 +0x41b
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.CreateSandbox({_, _}, {0xc000120480, {0x0, 0x0}, {0x5594>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/api.go:51 +0x13a
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*VCImpl).CreateSandbox(_, {_, _}, {0xc000120480, {0x0, >
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/implementation.go:35 +0x5d
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/pkg/katautils.CreateSandbox({_, _}, {_, _}, {{0xc00030b607, 0x9}, 0xc00>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/katautils/create.go:170 +0x7eb
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.create({0x55946e6286f0, 0xc00014b7d0}, 0xc000176>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/create.go:194 +0xda5
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.(*service).Create.func2()
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/service.go:428 +0x2c
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: created by github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.(*service).Create in goroutine 12
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/service.go:427 +0x47c
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:54.392433091+08:00" level=info msg="shim disconnected" id=test-kata11
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:54.392483122+08:00" level=warning msg="cleaning up after shim disconnected" id=test-kata11 namespace=de>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:54.392511218+08:00" level=info msg="cleaning up dead shim"
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:54.406214968+08:00" level=error msg="failed to delete" cmd="/usr/bin/containerd-shim-kata-v2 -namespace>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:54.406336173+08:00" level=warning msg="failed to clean up after shim disconnected" error="time=\"2024-0>
Sep 04 17:17:54 ccseagent-gpu containerd[1041962]: time="2024-09-04T17:17:54.406494726+08:00" level=error msg="copy shim log" error="read /proc/self/fd/17: file already closed"

it can fix by add check non-nil logic in kata-containers/src/runtime/virtcontainers/container.go

func (c *Container) siblingAnnotation(devPath string, siblings []DeviceRelation) {
            // Check if Annotations map is nil, and initialize it if necessary
    if c.config.CustomSpec.Annotations == nil {
        c.config.CustomSpec.Annotations = make(map[string]string)
    }
        for _, sibling := range siblings {
                if sibling.Path == devPath {
                        vfioNum := filepath.Base(devPath)
                        annoKey := fmt.Sprintf("cdi.k8s.io/vfio%s", vfioNum)
                        annoValue := fmt.Sprintf("nvidia.com/gpu=%d", sibling.Index)
                        c.config.CustomSpec.Annotations[annoKey] = annoValue
                        c.Logger().Infof("annotated container with %s: %s", annoKey, annoValue)
                }
        }
}

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Apokleos** [comment]
Hi @linjianshu Sorry for the trouble. I plan to fix this bug today. I will keep you in the loop.

**Comment by Apokleos** [comment]
Yeah, I think you have caught it. Could you please  make a PR to fix it ?

**Comment by linjianshu** [comment]
thanks very much!!!
