### ISSUE TITLE
tests: CoCo: Support s390x in the signed image tests

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#10302]
As part of https://github.com/kata-containers/kata-containers/pull/10009 signed image verification support was added to image pull and tests added. However I think only an amd64 test image is being used. IIRC the different arch images have different digests, so we can't create a multi-arch container image for this, but instead I think it would be ideal if we created new versions of:
```
UNSIGNED_PROTECTED_REGISTRY_IMAGE="ghcr.io/confidential-containers/test-container-image-rs:unsigned"
COSIGN_SIGNED_PROTECTED_REGISTRY_IMAGE="ghcr.io/confidential-containers/test-container-image-rs:cosign-signed"
COSIGNED_SIGNED_PROTECTED_REGISTRY_WRONG_KEY_IMAGE="ghcr.io/confidential-containers/test-container-image-rs:cosign-signed-key2"
```
With an s390x suffix to the tag. Then we can use the logic from `CCv0` in tests to append the arch it's not x86: 
```
tag_suffix=""
if [ "$(uname -m)" != "x86_64" ]; then
	tag_suffix="-$(uname -m)"
fi
```

This would probably work best if we could have the same private and public key for all the images, so I think @Xynnn007 would need to be involved in helping with this.

**Comment by stevenhorsman** [comment]
cc @Xynnn007 & @BbolroC

**Comment by Xynnn007** [comment]
Finished pushing images.

ghcr.io/confidential-containers/test-container-image-rs:unsigned-s390x
ghcr.io/confidential-containers/test-container-image-rs:cosign-signed-s390x  (same key with x86-64)
ghcr.io/confidential-containers/test-container-image-rs:cosign-signed-key2-s390x (also same key2 with x86-64)

**Comment by BbolroC** [comment]
@Xynnn007 @stevenhorsman Thanks for taking care of this. I much appreciate it.
