### ISSUE TITLE
"hostname" / "uname -n" is not set in 3.8.0 -- works correctly in 3.7.0

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#10325]
With 3.8.0 when I call `hostname` from a shell I get an empty string. I can see that `/proc/sys/kernel/hostname` is empty although `/etc/hostname` is set.

With 3.7.0 `/proc/sys/kernel/hostname` is set correctly and returns the pod name.

**Comment by volfco** [comment]
This also seems to happen with v3.9.0

**Comment by skaegi** [comment]
To be clear here... the Guest VM is getting a hostname... and I can use a `hostname=customname` kernel-param to set the VM name and validate that with the debug_console. What is not happening is that the "pod" hostname  is not getting propagated down to the pod containers.

This unfortunately is definitely a regression and breaking a number of our workloads as Java programs like Gradle and thinks the github actions runner call `gethostname` and break/panic when it is set to nothing. In addition there is no particularly good workaround as trying to manually set it calling... `hostname -F /etc/hostname` can only be done in a privileged container which is not the norm for our customers workloads.

**Comment by fidencio** [comment]
@skaegi, @volfco, my blind guess is that this is a regression introduced by #9944

That's the only commit I can remember of that touched something on those lines.

@Apokleos, @zvonkok, mind to take a look at this one?

**Comment by Apokleos** [comment]
> @skaegi, @volfco, my blind guess is that this is a regression introduced by #9944
> 
> That's the only commit I can remember of that touched something on those lines.
> 
> @Apokleos, @zvonkok, mind to take a look at this one?
>
I will check this issue.

**Comment by Apokleos** [comment]
Hi @skaegi I create a PR to try to fix this issue, could you please validate the patch within your environment ? Thx
