### ISSUE TITLE
SEV-SNP: Several build failures have occured when I tried the procedures in Kata Containers with AMD SEV-SNP VMs.

### ISSUE THREAD

**Issue by kimullaa** [kata-containers/kata-containers#10378]
# Description of problem

Several build failures have occured when I tried the procedures in [Kata Containers with AMD SEV-SNP VMs](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md).

I was informed in [this issue](https://github.com/kata-containers/kata-containers/issues/10355#issuecomment-2379526520) that the SNP host patches just went upstream in 6.11. So I think this SNP-specific build method may no longer be necessary in the near future, but if required, I would like to submit a Pull Request.

#  Problem1

## Expected result

https://github.com/kata-containers/kata-containers/blob/8412c0914326f48b4069784aa09eeca73d91b963/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md?plain=1#L31-L35

## Actual result

```bash
$ pushd kata-containers/tools/packaging/
$ ./kernel/build-kernel.sh -a x86_64 -x snp setup
...
Options:
...
        -x              : All the confidential guest protection type for a specific architecture.
```

## Further information 

 `-x` option no longer accepts the argument.  https://github.com/kata-containers/kata-containers/commit/6c3338271bd376207df7013076796f089e8423e7

#  Problem2

## Expected result

https://github.com/kata-containers/kata-containers/blob/8412c0914326f48b4069784aa09eeca73d91b963/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md?plain=1#L38-L42

## Actual result

Same as expected. However, this is not the OVMF for AMDSEV.

## Further information 

Maybe we should use `ovmf_build=sev ./build.sh`. https://github.com/kata-containers/kata-containers/commit/638c2c41649a48ec8fb44450993b39cee70752bf

**Comment by stevenhorsman** [comment]
@ryansavino - are you able to help, or link someone in to help here?
