### ISSUE TITLE
[RFE] Switch to Q35 as the default machine type for QEMU for 2.1.0

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1038]
First of all, this switch should not cause any negative impact as we do **not** support migration between Kata Containers, which is one of the yet hard to solve issues when migrating from the PC-I440FX to the Q35 machine time.

Secondly, some of the Kata Containers consumers (such as Red Hat) have already been using Q35 for some time, both on their virtualization Stack, and also together with Kata Containers themselves.

I'd like to recommend people to take a look at https://wiki.qemu.org/images/archive/4/4e/20160904170105!Q35.pdf, from @marcel-apf, and explicitly mention the fact that one of the most interesting selling points for the switch is that "DPDK on guest requires emulated IOMMU to protect the Guest OS from the users space accessing physical addresses", as mentioned by @marcel-apf.

I do remember people mentioned some issues faced with Q35 in the past, and I'd like to know whether those issues still exist or if there are some pointer to them, so they can help to evaluate this RFE.

I'd like to also have an idea about what would be the impact on the CI to do such switch. I know we currently have one job specifically testing Q35 on RHEL and in a conversation with @devimc, on #kata-dev, it was mentioned that:
```
17:33 <  fidencio> devimc: we have a CI job specifically testing q35, right? what's the focus / rationale of that test?
17:35 <    devimc> fidencio, we run all the tests
17:35 <    devimc> k8s, crio, docker ...
17:35 <  fidencio> devimc: we already run all the tests with q35 then
17:35 <    devimc> ahh and vfio
17:35 <    devimc> yes
17:36 <  fidencio> I'll quote you on that :-)
```

My, maybe broken, understanding is that we wouldn't face issues with older distros as we're building our own version of QEMU there and we're not using legacy virtio devices anyways. In the very worst case, we'd require consumers of Kata Containers that, for some reason or the other, decide to still use PC-I440FX as the machine type to explicitly set it.

Obviously, we'd have to choose one distro (ubuntu?) and keep at least one job running using "PC-I440FX", at least for some time.

Ideas? Comments?
@kata-containers/architecture-committee, @kata-containers/runtime, @kata-containers/tests, @kata-containers/ci

**Comment by devimc** [comment]
@fidencio thanks for raising this, I like your proposal, but before switch to Q35 I think we should consider the following points:

1. Performance - what's the impact of this change for "small workloads" and/or "serverless" applications? we need metrics
2. VFIO hotplug is a *little bit* broken in Q35, @dgibson is doing a great job fixing these issues in kata 1.x (see https://github.com/kata-containers/agent/pull/850 , https://github.com/kata-containers/agent/pull/845 , https://github.com/kata-containers/runtime/pull/3003 , https://github.com/kata-containers/runtime/pull/2963) -  but since you are proposing this for 2.x I think this may require more work in the kata rust agent

**Comment by fidencio** [comment]
@devimc, lovely!
Yes, we should keep track of those before doing the switch, thanks for bringing this up.

One question, do you think the switch would be reasonable for 1.x as well? Not knowing for how long the 1.x branch will still be alive (please, see: http://lists.katacontainers.io/pipermail/kata-dev/2020-October/001559.html) I'm not sure whether it's worth the effort there.

**Comment by devimc** [comment]
> One question, do you think the switch would be reasonable for 1.x as well? Not knowing for how long the 1.x branch will still be alive (please, see: http://lists.katacontainers.io/pipermail/kata-dev/2020-October/001559.html) I'm not sure whether it's worth the effort there.

I wouldn't switch to Q35 in 1.x since I think we should keep it as stable as possible and don't include new features, just fixes, 
but this my opinion, @kata-containers/architecture-committee members may think different

**Comment by fidencio** [comment]
@fidencio, while going through the "needs- review" issues I've faced this one.
We still want to do the switch ASAP, but we depend on work being done on different areas before we actually are able to switch.

For now, I'm removing the "needs-review" label.

**Comment by fidencio** [comment]
Closing this one as https://github.com/kata-containers/kata-containers/pull/1954 got merged.
