### ISSUE TITLE
improve sandbox cleanup logic

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#1039]
When reading the cleanup code path, we have several problems:
1. containerd container cleanup order is adhoc and we should handle the case that a sandbox container is cleaned up before other containers in the same pod sandbox
2. cgroups cleanup should ignore non-existing directories
3. sandbox delete should always succeeds after verifying sandbox states. otherwise we end up leaving orphan containers and inconsistent container states

**Comment by fidencio** [comment]
@bergwolf, I've faced this one while going through the issues with "needs-review" label.

Is this still a problem? If so, wouldn't this be a good firt issue for a new community member to work on? If not, could we close this one referencing the PR that solved the issue?

Anyways, for now, I'm removing the "needs-review" label.
