### ISSUE TITLE
Clean up handling of PCI paths

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#1040]
Forward port to Kata 2 https://github.com/kata-containers/runtime/issues/3002 and https://github.com/kata-containers/agent/issues/854

**Comment by fidencio** [comment]
@dgibson, as I'm going through the issues with "needs-review" label, I ended up on this one.

This one looks a lot like a supersed of https://github.com/kata-containers/kata-containers/issues/683.  Is this the case? If so, could we close #683?

**Comment by fidencio** [comment]
Anyways, I've removed the "needs-review" label, as @dgibson has been working on this one.

**Comment by dgibson** [comment]
@fidencio, this does not supersede #683.  It's a preliminary towards #683, but actually removing the rescan involves further work.
