### ISSUE TITLE
how to build qemu-vanilla-system-x86_64 

### ISSUE THREAD

**Issue by lovebaby979** [kata-containers/kata-containers#1041]
how to qemu-vanilla-system-x86_64 
from qemu, how to build qemu-vanilla-system-x86_64 ?

**Comment by devimc** [comment]
you can use https://github.com/kata-containers/kata-containers/blob/2.0-dev/tools/packaging/static-build/qemu/build-static-qemu.sh or manually using https://github.com/kata-containers/kata-containers/blob/2.0-dev/tools/packaging/scripts/configure-hypervisor.sh and then `make && make install`

**Comment by devimc** [comment]
@lovebaby979 can we close this?
