### ISSUE TITLE
genpolicy: darwin builds

### ISSUE THREAD

**Issue by burgerdev** [kata-containers/kata-containers#10424]
**Which feature do you think can be improved?**

The `genpolicy` binary.

**How can it be improved?**

`genpolicy` is a developer tool that does not necessarily run on the same system that Kata is deployed on, and there is no inherent limitation that would prevent compiling it for common developer systems. Concretely, I'd like to be able to compile and run the tool on an Apple M2.

Once `genpolicy` compiles on darwin, I would like to include it in the CI build so that we notice when it breaks.

**Additional Information**

The tool does not compile today because of these issues:

1. `protocols` has a dependency on `kata-sys-util`, which is Linux-only. This is trivial to solve by moving a function around.
2. We're generating conversion traits between ttRPC and OCI representations. However, some of the nested structs in oci-spec are conditionally compiled by compilation target platform.  I believe this to be a mistake (https://github.com/containers/oci-spec-rs/issues/243), but until this is resolved we could add a compilation condition to the conversions, too.

**Before raising this enhancement request**

✔️  Have you looked at the [limitations document](https://github.com/kata-containers/kata-containers/blob/main/docs/Limitations.md)?

**Kata Containers survey**

✔️  Please consider taking the survey to help us help you: https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey

cc @Apokleos @Redent0r @danmihai1

**Comment by fidencio** [comment]
I'm closing this one. @burgerdev, please, let's track the Darwin CI addition in a different issue.
