### ISSUE TITLE
Add annotation validation for entropy_source

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#1043]
**Which feature do you think can be improved?**

While some paths are protected from modification using annotations, `entropy_source` currently is not.

See comment https://github.com/kata-containers/documentation/pull/755#discussion_r512783241

**How can it be improved?**

Add annotation validation in the vein of what was done in #902 .

**Comment by fidencio** [comment]
@c3d, I'm commenting here as I'm going through the issues with "needs-review"  label.  Right now I'm removing the label from this one as we already have a PR opened for this issue.  I'd like to ask you, though, whether you could rebase your PR as it conflicts with `main`.
