### ISSUE TITLE
guest_hook_path not triggered

### ISSUE THREAD

**Issue by junqiang0718** [kata-containers/kata-containers#10458]
The guest_hook_path is triggered by using the docker.io/nvidia/cuda:12.4.0-base-ubuntu20.04 container image. The nvidia-container-toolkit.log log is found inside the virtual machine.
`root@node1:/opt/kata# ctr --debug run --rm --runtime "io.containerd.kata.v2" --device /dev/vfio/222 -t "docker.io/nvidia/cuda:12.4.0-base-ubuntu20.04" demo bash
DEBU[0000] remote introspection plugin filters           filters="[type==io.containerd.snapshotter.v1, id==overlayfs]"
root@:/# find / -name "*nvidia*"
/usr/lib/firmware/nvidia
/usr/local/cuda-12.4/compat/libnvidia-ptxjitcompiler.so.550.54.15
/usr/local/cuda-12.4/compat/libnvidia-pkcs11-openssl3.so.550.54.15
/usr/local/cuda-12.4/compat/libnvidia-nvvm.so
/usr/local/cuda-12.4/compat/libnvidia-ptxjitcompiler.so.1
/usr/local/cuda-12.4/compat/libnvidia-nvvm.so.4
/usr/local/cuda-12.4/compat/libnvidia-nvvm.so.550.54.15
/usr/local/cuda-12.4/compat/libnvidia-pkcs11.so.550.54.15
/etc/ld.so.conf.d/nvidia.conf
/sys/kernel/slab/nvidia_pte_cache
/sys/kernel/slab/nvidia_stack_cache
/sys/kernel/slab/nvidia_p2p_page_cache
/sys/bus/pci/drivers/nvidia
/sys/bus/pci/drivers/nvidia-nvswitch
/sys/module/nvidia_uvm
/sys/module/nvidia
/sys/module/nvidia/holders/nvidia_uvm
/sys/module/nvidia/holders/nvidia_modeset
/sys/module/nvidia/drivers/pci:nvidia-nvswitch
/sys/module/nvidia/drivers/pci:nvidia
/sys/module/nvidia_modeset
/proc/driver/nvidia
/proc/driver/nvidia-uvm
/proc/driver/nvidia-caps
/proc/driver/nvidia-nvlink
/proc/driver/nvidia-nvswitch`

The guest_hook_path is not triggered when using the docker.io/library/ubuntu:20.04 container image, and there is no nvidia-container-toolkit.log log inside the virtual machine
`root@node1:/opt/kata# ctr --debug run --rm --runtime "io.containerd.kata.v2"  --device /dev/vfio/222  -t "docker.io/library/ubuntu:20.04" demo bash
DEBU[0000] remote introspection plugin filters           filters="[type==io.containerd.snapshotter.v1, id==overlayfs]"
root@:/# find / -name "*nvidia*"
root@:/# `

**Comment by junqiang0718** [comment]
The kata.log log is as follows：
[Uploading kata.log…]()

**Comment by junqiang0718** [comment]
Found the reason. ctr did not configure the NVIDIA_VISIBLE_DEVICES environment variable for the container.

**Comment by Apokleos** [comment]
Thx @junqiang0718 reports this problem though it's not the issue of kata runtime, but it will help other users.
The issue will be closed.

/close
