### ISSUE TITLE
agent: Exception starting agent with GuestComponentsProcs=none

### ISSUE THREAD

**Issue by squarti** [kata-containers/kata-containers#10568]
# Description of problem

The kata agent fails to start up if `guest_components_procs` is set to `none` with following error:

```
root@podvm-nginx-abe882f9:~# journalctl -u kata-agent
-- Logs begin at Tue 2024-11-12 19:14:44 UTC, end at Tue 2024-11-12 19:15:07 UTC. --
Nov 12 19:15:02 podvm-nginx-abe882f9 systemd[1]: Starting Kata Agent...
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[976]: umount: /sys/fs/cgroup/misc: no mount point specified.
Nov 12 19:15:02 podvm-nginx-abe882f9 systemd[1]: Started Kata Agent.
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]: {"msg":"announce","level":"INFO","ts":"2024-11-12T19:15:02.451349856Z","subsystem":"root","pid":"977","source":"agent","version":"0.1.0","name":"kata-agent","co>
...
12T19:15:02.520494955Z","pid":"977","name":"kata-agent","source":"agent","subsystem":"uevent","version">
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]: Error: No such file or directory (os error 2)
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]: Stack backtrace:
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    1: kata_agent::start_sandbox::{{closure}}::{{closure}}.17073
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    2: kata_agent::real_main::{{closure}}
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    3: kata_agent::main
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    4: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    5: std::rt::lang_start
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    6: __libc_start_main
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[977]:    7: _start
Nov 12 19:15:02 podvm-nginx-abe882f9 systemd[1]: kata-agent.service: Main process exited, code=exited, status=1/FAILURE
Nov 12 19:15:02 podvm-nginx-abe882f9 kata-agent[1051]: Can't remove  as it doesn't exist
```

# Expected result

kata-agent starts up successfully in PodVM.

# Actual result

kata-agent fails to start up.

# Further information

Only broken in kata 3.11.0 release.  Related to this change

https://github.com/kata-containers/kata-containers/commit/bf769851f81a399c6e526814479738040c6b4b6f#diff-ed2edc9fa74154f8f6bbe195c07e456a861f1c9e20e0b07a1c66d2aed49a3f0cL411-R429

`init_attestation_components` is called because `attestation_binaries_available` returns `true`

# Kata Containers survey

Please consider taking the survey to help us help you: https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey

**Comment by fidencio** [comment]
cc @mkulke

**Comment by mkulke** [comment]
@squarti can you elaborate on the behaviour you expect?

you want to
- set `guest_components_procs = none`
- have attestation binaries present on the rootfs
- do not have the agent perform `init_attestation_components()` (connect to CDH, etc)

if that's the case, I don't think it's supported.

because the semantics at the moment are:

If attestation binaries are present on the rootfs, `init_attestation_components()` is performed
If `guest_components_procs == none` kata-agent doesn't launch any guest-component processes itself.

If we want to disable `init_attestation_components()`, even when attestation binaries are present on the rootfs, we need another toggle.

3.11 is [used](https://github.com/confidential-containers/cloud-api-adaptor/blob/56fba7010cb1facf42d6390b3e1306ecc017ca18/src/cloud-api-adaptor/versions.yaml#L52) in peerpods w/ `guest_component_procs=none` in e2e-tests (see (https://github.com/mkulke/cloud-api-adaptor/blob/b58e8972959ea91051ece34a897e0f577d17ee51/src/cloud-api-adaptor/pkg/agent/config.go#L10). it works, because a CDH socket is available, I suspect that's what the error is about.

**Comment by squarti** [comment]
>set guest_components_procs = none

yes

> have attestation binaries present on the rootfs

no, we do not have the attestation binaries installed in our podvm

> do not have the agent perform init_attestation_components() (connect to CDH, etc)

yes

I think the problem is that `attestation_binaries_available` returns true because the binaries list is empty https://github.com/kata-containers/kata-containers/blob/3.11.0/src/agent/src/main.rs#L448

**Comment by mkulke** [comment]
thanks for the clarification. that looks indeed a bit nonsensical. there is no reason why attestation_binaries_available() should return true if no guest_components_procs == none. I think the intention was to short-fuse the binary-file-present heuristic and perform the initialization anyway. But that doesn't make sense if there's no CDH socket available.

I guess the implicit assumption was/is that noone would set `guest_component_procs = none` if there are no guest_components on the rootfs.

I'm not entirely sure what we want as a desired behaviour. there is a heuristic we use to find out that we are in a confidential vm and a then there i config flag to define whether we want to launch child processes, both have to be reconciled somehow.

To understand the use case a bit better: is there a reason why there you set `guest_component_procs = none`? if there are no attestation binaries available it would just skip the init (and log a warning, which is the case for non-confidential kata-vms now).

**Comment by squarti** [comment]
> To understand the use case a bit better: is there a reason why there you set guest_component_procs = none?

No reason other than it is the default value and it used to work.

What would I set to?  `None` seems to be the only possible value for my case and it seems to imply "no processes".   

```
pub enum GuestComponentsProcs {
    None,
    /// ApiServerRest implies ConfidentialDataHub and AttestationAgent
    #[default]
    ApiServerRest,
    AttestationAgent,
    /// ConfidentialDataHub implies AttestationAgent
    ConfidentialDataHub,
}
```

**Comment by mkulke** [comment]
> > To understand the use case a bit better: is there a reason why there you set guest_component_procs = none?
> 
> No reason other than it is the default value and it used to work.
> 
> What would I set to? `None` seems to be the only possible value for my case and it seems to imply "no processes".
> 
> ```
> pub enum GuestComponentsProcs {
>     None,
>     /// ApiServerRest implies ConfidentialDataHub and AttestationAgent
>     #[default]
>     ApiServerRest,
>     AttestationAgent,
>     /// ConfidentialDataHub implies AttestationAgent
>     ConfidentialDataHub,
> }
> ```

Where would `guest_component_procs = None` be a default value? In the snippet above, for kata-agent, it should be `ApiServerRest`, if you don't specify anything, no? `GuestComponentProcs::None` was introduced for peerpods to avoid spawning duplicate processes, as peerpods is using systemd to manage those processes. This might change sometime in the future, depending on a related initdata discussion.

The last kata release introduced a dependency on a CDH socket (for confidential containers), that's why you are seeing the error. with the change you are suggesting, kata wouldn't connect to the CDH socket if `guest_component_procs = none`, which would break peerpods.

so, the scenario that we have to cover:
- the agent should init attestation components (set OCICRYPT env, connect to CDH socket)
- the agent should not spawn processes

**Comment by squarti** [comment]
I think `none` is coming from https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/pkg/agent/config.go#L10.  I would need to confirmed.

> the agent should init attestation components (set OCICRYPT env, connect to CDH socket)

I see the reason for your change now.   

I believe `init_attestation_components` is erroring out in this [line](https://github.com/kata-containers/kata-containers/blob/3.11.0/src/agent/src/main.rs#L522) because the the directory `/run/confidential-container` does not exists (need to confirm).  Maybe we could create the dir if necessary ensuring that `init_attestation_components` does not fail?

**Comment by mkulke** [comment]
right, that's true. CAA will always set this to None, we could make this configurable. but indeed, like you pointed out, the problem doesn't seem to be the socket. it should actually tolerate the socket not being available. however, the ocicrypt file needs /run/confidential-container to be present. If we don't have this, it's probably not worth bothering. If CDH is not running, encrypted images probably would not work anyway. So we can just make a successful cdh client init a requirement for the ocicrypt config. wdyt?

```rust
async fn init_attestation_components(logger: &Logger, config: &AgentConfig) -> Result<()> {
    launch_guest_component_procs(logger, config).await?;

    // If a CDH socket exists, initialize the CDH client and enable ocicrypt
    match tokio::fs::metadata(CDH_SOCKET).await {
        Ok(md) => {
            if md.file_type().is_socket() {
                cdh::init_cdh_client(CDH_SOCKET_URI).await?;
                fs::write(OCICRYPT_CONFIG_PATH, OCICRYPT_CONFIG.as_bytes())?;
                env::set_var("OCICRYPT_KEYPROVIDER_CONFIG", OCICRYPT_CONFIG_PATH);                
            } else {
                debug!(logger, "File {} is not a socket", CDH_SOCKET);
            }
        }
        Err(err) => warn!(
            logger,
            "Failed to probe CDH socket file {}: {:?}", CDH_SOCKET, err
        ),
    }

    Ok(())
}
```

**Comment by squarti** [comment]
I performed some testing and confirmed this approach works:

changes: https://github.com/kata-containers/kata-containers/compare/main...squarti:kata-containers:fork-3.11.0

We get a warning about the missing CDH socket, but the agent starts up successfully. 

```
root@podvm-nginx-24edc949:~# journalctl -u kata-agent
-- Logs begin at Mon 2024-11-25 19:21:00 UTC, end at Mon 2024-11-25 19:23:11 UTC. --
Nov 25 19:21:17 podvm-nginx-24edc949 systemd[1]: Starting Kata Agent...
Nov 25 19:21:17 podvm-nginx-24edc949 kata-agent[980]: umount: /sys/fs/cgroup/misc: no mount point specified.
Nov 25 19:21:17 podvm-nginx-24edc949 systemd[1]: Started Kata Agent.
Nov 25 19:21:18 podvm-nginx-24edc949 kata-agent[981]: {"msg":"announce","level":"INFO","ts":"2024-11-25T19:21:18.110428872Z","version":"0.1.0","source":"agent","name":"kata-agent","pid":"981","subsystem":"root","agent-version":"3.11.0","extra-features":">
Nov 25 19:21:18 podvm-nginx-24edc949 kata-agent[981]: {"msg":"https_proxy is not set (environment variable not found)","level":"INFO","ts":"2024-11-25T19:21:18.139401805Z","pid":"981","name":"kata-agent","source":"agent","version":"0.1.0","subsystem":"im>
Nov 25 19:21:18 podvm-nginx-24edc949 kata-agent[981]: {"msg":"no_proxy is not set (environment variable not found)","level":"INFO","ts":"2024-11-25T19:21:18.139440992Z","source":"agent","pid":"981","name":"kata-agent","subsystem":"image","version":"0.1.0>
Nov 25 19:21:18 podvm-nginx-24edc949 kata-agent[981]: {"msg":"starting uevents handler","level":"INFO","ts":"2024-11-25T19:21:18.143990193Z","subsystem":"uevent","source":"agent","pid":"981","name":"kata-agent","version":"0.1.0"}
Nov 25 19:21:18 podvm-nginx-24edc949 kata-agent[981]: {"msg":"Failed to probe CDH socket file /run/confidential-containers/cdh.sock: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }","level":"WARN","ts":"2024-11-25T19:21:18.14531521>

````

**Comment by mkulke** [comment]
great. thanks for testing. can you open a PR?
