### ISSUE TITLE
take too long to start kata with cloud hypervisor 

### ISSUE THREAD

**Issue by magnate3** [kata-containers/kata-containers#1058]
firstly, I use cloud hypervisor to start kata
root@cloud:~/hyper/cloud-hypervisor# time docker run --rm -itd --name=kata-test --runtime kata-runtime busybox
22b0251b91ccfb98c6bc5a48a9e4f618ae8b7a232d6c26b77515755b956f0745

real 0m12.488s
user 0m0.049s
sys 0m0.067s

secondly , I use qemu to start kata
root@ubuntu:~/docker/container# time docker run --rm -itd --name=kata-test --runtime kata-runtime busybox
9a14122665eb57641a9f307a7cc823526c6a559055d2f37e1ec0fdcc260513fa

real 0m1.837s
user 0m0.025s
sys 0m0.084s
root@ubuntu:~/docker/container#

perf with cloudhypervisor

root@cloud:~/hyper/cloud-hypervisor# strace -c -f -S name docker run --rm -itd --name=kata-test --runtime kata-runtime busybox
strace: Process 21490 attached
strace: Process 21491 attached
strace: Process 21492 attached
strace: Process 21493 attached
strace: Process 21494 attached
strace: Process 21495 attached
strace: Process 21496 attached
strace: Process 21497 attached
strace: Process 21498 attached
strace: Process 21499 attached
strace: Process 21500 attached
strace: Process 21501 attached
strace: Process 21502 attached
strace: Process 21503 attached
strace: Process 21504 attached
strace: Process 21505 attached
strace: Process 21506 attached
strace: Process 21507 attached
87130c9c40a85446fb67d21a2704be785f284e8e53eb0cffa051f38a862e97b9
strace: Process 21513 attached
% time seconds usecs/call calls errors syscall

0.00 0.000014 5 3 brk
0.00 0.000000 0 1 capget
6.12 0.019506 24 810 clock_gettime
0.08 0.000263 14 19 clone
0.03 0.000094 5 19 close
0.02 0.000052 13 4 2 connect
0.00 0.000013 13 1 epoll_create1
0.01 0.000016 2 8 epoll_ctl
3.44 0.010972 229 48 epoll_pwait
0.00 0.000000 0 1 execve
0.01 0.000042 5 9 9 faccessat
0.01 0.000034 4 9 fcntl
0.02 0.000057 5 12 fstat
80.76 0.257279 220 1172 109 futex
0.00 0.000000 0 2 getpeername
0.01 0.000019 10 2 getpid
0.00 0.000000 0 1 getrandom
0.00 0.000000 0 2 getsockname
0.04 0.000112 6 20 gettid
0.00 0.000000 0 1 gettimeofday
0.00 0.000011 11 1 getuid
0.00 0.000000 0 2 ioctl
0.00 0.000000 0 2 lseek
0.19 0.000600 7 90 madvise
0.19 0.000595 8 79 mmap
0.16 0.000524 10 54 mprotect
0.06 0.000207 12 17 munmap
7.69 0.024495 67 366 nanosleep
0.01 0.000031 1 36 34 newfstatat
0.05 0.000163 10 17 openat
0.00 0.000008 8 1 prlimit64
0.11 0.000351 14 26 6 read
0.02 0.000055 55 1 readlinkat
0.04 0.000121 1 128 rt_sigaction
0.51 0.001629 10 165 rt_sigprocmask
0.00 0.000007 7 1 sched_getaffinity
0.24 0.000779 5 146 sched_yield
0.03 0.000110 6 20 set_robust_list
0.00 0.000006 6 1 set_tid_address
0.00 0.000000 0 2 setsockopt
0.09 0.000297 7 40 sigaltstack
0.02 0.000062 16 4 socket
0.00 0.000014 14 1 uname
0.01 0.000040 8 5 write

100.00 0.318578 3349 160 total
root@cloud:~/hyper/cloud-hypervisor#

perf with qemu
root@ubuntu:/home/ubuntu# strace -c -f -S name docker run --rm -itd --name=kata-test --runtime kata-runtime busybox
strace: Process 31697 attached
strace: Process 31698 attached
strace: Process 31699 attached
strace: Process 31700 attached
strace: Process 31701 attached
strace: Process 31702 attached
strace: Process 31703 attached
strace: Process 31704 attached
strace: Process 31705 attached
strace: Process 31706 attached
strace: Process 31707 attached
strace: Process 31708 attached
strace: Process 31709 attached
strace: Process 31710 attached
strace: Process 31712 attached
strace: Process 31726 attached
strace: Process 31729 attached
strace: Process 31730 attached
2601c0644fe8a3426641cf978c8b1c3d4ce0c92122c35d84e35c8208dc2d4c54
% time seconds usecs/call calls errors syscall

0.00 0.000018 6 3 brk
0.00 0.000000 0 1 capget
61.85 3.154694 75 42012 clock_gettime
0.01 0.000428 24 18 clone
0.00 0.000067 3 21 close
0.00 0.000029 7 4 2 connect
0.00 0.000015 15 1 epoll_create1
0.00 0.000035 3 12 4 epoll_ctl
0.20 0.010071 246 41 epoll_pwait
0.00 0.000000 0 1 execve
0.00 0.000054 6 9 9 faccessat
0.00 0.000055 6 9 fcntl
0.00 0.000033 2 14 fstat
19.53 0.996099 754 1321 105 futex
0.00 0.000016 8 2 getpeername
0.00 0.000017 9 2 getpid
0.00 0.000016 16 1 getrandom
0.00 0.000018 9 2 getsockname
0.01 0.000257 14 19 gettid
0.00 0.000005 5 1 gettimeofday
0.00 0.000000 0 1 getuid
0.00 0.000000 0 2 ioctl
0.00 0.000000 0 2 lseek
0.01 0.000655 9 70 madvise
0.01 0.000648 9 76 mmap
0.02 0.000877 17 52 mprotect
0.00 0.000242 13 18 munmap
13.13 0.669892 2318 289 nanosleep
0.00 0.000034 1 33 29 newfstatat
0.00 0.000193 10 19 openat
0.00 0.000009 9 1 prlimit64
0.01 0.000453 15 30 6 read
0.00 0.000059 59 1 readlinkat
0.02 0.000935 7 128 rt_sigaction
0.03 0.001690 10 162 rt_sigprocmask
0.00 0.000009 9 1 sched_getaffinity
5.14 0.262299 13 20738 sched_yield
0.00 0.000177 9 19 set_robust_list
0.00 0.000007 7 1 set_tid_address
0.00 0.000016 8 2 setsockopt
0.01 0.000342 9 38 sigaltstack
0.00 0.000065 16 4 socket
0.00 0.000000 0 1 uname
0.00 0.000122 24 5 write

**Comment by devimc** [comment]
cc @rbradford @likebreath @sameo

**Comment by egernst** [comment]
Can you please include the Kata/CLH versions you are using? Is this with the packaged guest kernel?

**Comment by likebreath** [comment]
@magnate3 As you are using the docker CLI, I believe you are using kata 1.x. We did have metrics reference numbers on boot time for both qemu(+virtiofs) and cloud-hyervisor (+virtiofs) for kata 1.x, where their mid-val are 0,99s ([link](https://github.com/kata-containers/tests/blob/master/cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml#L19)) and 1.10s ([link](https://github.com/kata-containers/tests/blob/master/cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml#L19)) respectively. We have metrics CIs running to make sure those reference numbers are respected.  What's more, I just did a quick tests locally with the command you shared above, but I did not reproduce your observations. My setup was everything from kata 1.x upstream master, and the number I got was ~1.6s vs ~2.2s for qemu-virtiofsd and clh respectively.

With that being said, we don't expect to see the observations you reported. So can you please share more about your setup (especially the version/packaging information that @egernst requested above)? Thank you.

**Comment by magnate3** [comment]
@likebreath  my setting is following

 root@cloud:~# uname -a
Linux cloud 5.5.19-050519-generic #202004210831 SMP Tue Apr 21 08:49:56 UTC 2020 **aarch64 aarch64 aarch64 G**NU/Linux
root@cloud:~# 


root@cloud:~# kata-runtime -v
kata-runtime  : 1.12.0-alpha1
   commit   : 37be079641a1c6640c85ec66b934df2e4fbfedf3-dirty
   OCI specs: 1.0.1-dev
root@cloud:~# cloud-hypervisor -V
cloud-hypervisor v0.10.0-201-g8c92d1db
root@cloud:~# virtiofsd -V
using FUSE kernel interface version 7.29
root@cloud:~# containerd -v
containerd github.com/containerd/containerd v1.4.0-2256-g31a6d1113.m 31a6d11133f0c8b4a631aeba3f5f2d21e303f23e.m

**Comment by likebreath** [comment]
@magnate3 I don't think I followed your setup information. We did have a easy way to setup the released version of kata w/ kata-deploy (https://github.com/kata-containers/packaging/tree/master/kata-deploy). To rule out the variances on your host system, can you please try to use the `kata-deploy` to setup kata on your machine and run your experiments again?

**Comment by magnate3** [comment]
I think virtiofs is the  key point, if I  change hypervisor  and use qemu int the same environment,the start can be started up

**Comment by fidencio** [comment]
@magnate3, as this issue seems to be stale, I'm closing it.

I'd like to ask you, though, that if you still think it's a problem with the current code, **please**, do not hesitate on reopening this issue or opening a new one.

Thanks a lot for raising the issue!
