### ISSUE TITLE
agent build: rust musl toolchain not available for ppc64le

### ISSUE THREAD

**Issue by clnperez** [kata-containers/kata-containers#1067]
# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:

# Description of problem

https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/agent/README.md#build-from-source

It appears that the build process for kata agent has changed, and requires the use of musl. However, the musl toolchain isn't available from stable for ppc64le (`powerpc64le`). At least, not the `std` component. 

```
$ rustup target add "${arch}-unknown-linux-musl" 
error: toolchain 'stable-powerpc64le-unknown-linux-gnu' does not contain component 'rust-std' for target 'powerpc64le-unknown-linux-musl'
```

I've asked around and can't find a build of it anywhere else, so, I'm wondering if this was unknown when the doc was updated, or, if it's expected that we build our own, etc. 

official doc platform support:
https://doc.rust-lang.org/nightly/rustc/platform-support.html

github doc platform support with a mention of big-endian (not le) powerpc64-unkown-linux-musl in Tier 3:
https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support.md

**Comment by clnperez** [comment]
cc @bpradipt @Amulyam24 @jing-wang4

**Comment by fidencio** [comment]
@clnperez, we explicitly use glibc instead of musl for ppc: https://github.com/kata-containers/kata-containers/blob/8823ca31adb80008d1158292052af2e58669e5cd/src/agent/Makefile#L38-L42

I wonder how you're not hitting that code path.

**Comment by fidencio** [comment]
Hmm. I think I may understand why you're not hitting that code path, @clnperez.
Let's say you ignore the README, uses the rustc from your distro, and just do a simple `make` to build the agent, does that work for you?

**Comment by jing-wang4** [comment]
@fidencio 
The `make` agent of latest `2.0-dev` failed, however it is good with 2.0.0 release.

**Comment by clnperez** [comment]
Yep. Thanks @jing-wang4. That's what made us go back and re-read the README and try another build route, @fidencio . So If we need to just fix that location issue, then we can modify the readme for Power. As-written, it doesn't sound like we are still using glibc only for Power. Jing said that she can build pre- https://github.com/kata-containers/kata-containers/commit/9e9988df291ed76444381f2de811352d9fb23bca

**Comment by fidencio** [comment]
@clnperez, cool. Mind if I ask you to open 2 issues?
1. One about the regression introduced on https://github.com/kata-containers/kata-containers/commit/9e9988df291ed76444381f2de811352d9fb23bca
2. About updating the documentation.

Then I think this one could be closed.

**Comment by jing-wang4** [comment]
Thanks @fidencio !
2 issues are opened accordingly.

**Comment by fidencio** [comment]
@jing-wang4, thanks a lot!
@clnperez, do you mind if we close this one and track what has to be done in the issues opened by @jing-wang4?

**Comment by clnperez** [comment]
Nope. Thanks for the input @fidencio!
