### ISSUE TITLE
Building agent of latest 2.0-dev failed on ppc64le

### ISSUE THREAD

**Issue by jing-wang4** [kata-containers/kata-containers#1068]
# Description of problem

Building agent of latest 2.0-dev failed on ppc64le.

```
error: failed to run custom build command for `prost-build v0.5.0`

Caused by:
  process didn't exit successfully: `/home/fedora/go/src/github.com/kata-containers/kata-containers/src/agent/target/release/build/prost-build-ea57d3bb40141ace/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH', /home/fedora/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.5.0/build.rs:97:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:111: target/powerpc64le-unknown-linux-gnu/release/kata-agent] Error 101
# Expected result

```

Building agent of release 2.0.0 is good.

See [here](https://github.com/kata-containers/kata-containers/issues/1067#issuecomment-719829901) for more info.

**Comment by fidencio** [comment]
@jing-wang4,

Installing `protobuf-compiler` on Fedora may solve the issue for you. However, I'm still puzzled why I don't have such package installed on my (x86_64) machine and I think it's being dowloaded, used, and then removed when building the agent.

**Comment by jing-wang4** [comment]
Thanks @fidencio! 
Built agent fine with `protobuf-compiler` installed.

**Comment by fidencio** [comment]
Okay, that's good to know, we must add this as part of the dependencies and I need to figure out why I didn't need this for x86_64.
@bergwolf, any idea what brings protoc in during the agent build process?

**Comment by fidencio** [comment]
And let me also CC the pp64 folks CC'ed in the original issue.
/cc @bpradipt @Amulyam24 @jing-wang4

**Comment by jing-wang4** [comment]
@fidencio @bergwolf @bpradipt 
What would you think the solution be for this issue? 
Doc/README update or build process fix? 
Thanks!

**Comment by clnperez** [comment]
@fidencio -- assuming there's a bundled protoc for x86 but not Power: `there is no bundled protoc for this platform`
Tiny doc update for this in https://github.com/kata-containers/kata-containers/pull/1334

**Comment by bpradipt** [comment]
> @fidencio @bergwolf @bpradipt
> What would you think the solution be for this issue?
> Doc/README update or build process fix?
> Thanks!

doc update should be fine imho

**Comment by fidencio** [comment]
@clnperez, firstly, please, always ping me if I forget to come back to a PR. Sometimes things get lost, mainly after time off periods. :-)

I do agree with @bpradipt here that a documentation update is good enough for this.
