### ISSUE TITLE
README: update for agent build for ppc64le

### ISSUE THREAD

**Issue by jing-wang4** [kata-containers/kata-containers#1069]
# Description of problem

As per [suggestion](https://github.com/kata-containers/kata-containers/issues/1067#issuecomment-719829901), [README](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/agent#build-from-source) may need to be updated.

**Comment by fidencio** [comment]
Let me also CC the pp64 folks CC'ed in the original issue.
/cc @bpradipt @Amulyam24 @jing-wang4
