### ISSUE TITLE
Proposal: kata shimv2 rewritten by rust

### ISSUE THREAD

**Issue by abel-von** [kata-containers/kata-containers#1071]
**Which feature do you think can be improved?**

Kata agent has been rewritten by rust in kata 2.0, if the kata runtime or the shim v2 can be rewritten by rust, It will bring many advantages. Firstly the languages can be unified, also shimv2 server written by rust can save lots of memory. Furthermore, the rust shimv2 can integrate  rust vmm as a library and can launch a vm inside the process, with this, pods and processes on host will be one to one corresponding, not only saves memory on host, but also brings better stability and maintainability.

**How can it be improved?**

I have implemented a containerd shimv2 lib by rust and built runc and kata based on it, it can be integrated in k8s and do the pod creation/start/deletion/exec and so on. 
Recently it is just a shimv2 server and a CommandRuntime trait is provided to integrate runc and kata-runtime command line to do the real container manipulation. 
But I also made a prototype to integrate the cloud hypervisor libs to launch vm inside the process and request to kata-agent using hybrid vsock, all in one process.

**Additional Information**

I will remedy the prototype to give it the full feature of kata-containers, and also give it a better scalability.

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?  Yes

I'd like to push it to the community, but I don't know if it is welcome or if something is already done.  So is there any suggestion about it?

**Comment by jodh-intel** [comment]
Hi @abel-von - Thanks for raising and letting us know you're working on this! It sounds interesting and we are always open to considering new ideas and approaches.

Once you've read through the [contributing guide](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md), please feel free to raise an [rfc PR](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#github-labels-and-keywords-that-block-prs) to get some initial feedback.

**Comment by bergwolf** [comment]
Interesting. To avoid wasting time and efforts, you can also join one of the[ arch committee meetings ](https://etherpad.opendev.org/p/Kata_Containers_2020_Architecture_Committee_Mtgs) to introduce the overall design and discuss pros/cons.

**Comment by abel-von** [comment]
@jodh-intel @bergwolf  thanks for reply, I'm preparing to submit a rfc PR firstly.

**Comment by jshachm** [comment]
@bergwolf @jodh-intel Glad to hear you are Interested in this feature~

**Comment by gnawux** [comment]
> @jodh-intel @bergwolf thanks for reply, I'm preparing to submit a rfc PR firstly.

Nice.

If it takes weeks of time, I suggest we could have a short discussion in the following AC meeting firstly.

**Comment by gnawux** [comment]
@jshachm Welcome back! Has OpenEuler already had a Rust version now?

**Comment by liubin** [comment]
See #3052
