### ISSUE TITLE
Update Kernel config for overlayfs

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#1075]
We package a recent kernel and use overlayfs inside of Kata and have found you really need to update the `fs` config to include...

`CONFIG_OVERLAY_FS_METACOPY=y`
... to have reasonable performance for recursive chmod and similar calls.

`CONFIG_OVERLAY_FS_XINO_AUTO=y`
... less critical but set primarily because it is recommended for POSIX compliance

See... https://github.com/torvalds/linux/blob/master/fs/overlayfs/Kconfig
and https://github.com/torvalds/linux/blob/master/Documentation/filesystems/overlayfs.rst

These settings have been present since 4.19 so it might be time to make them mainstream.

**Comment by egernst** [comment]
Thanks @skaegi! Are you running with these options today?

Seems reasonable to me -- you interested in submitting a PR?

**Comment by skaegi** [comment]
Yes and have been for some time with 5.8.x and now 5.9.x. Sure let me create a PR.

**Comment by fidencio** [comment]
@skaegi, thanks for raising the issue.  I've opened a #1384 that should cover your recommendations.

**Comment by skaegi** [comment]
Thanks @fidencio -- I never got back to this but yes you've covered it.

**Comment by c3d** [comment]
@fidencio You fix look good, but I think it might be better to actually pass that as mount options to overlayfs in case you pick up a kernel that does not have the option set (e.g., at random, a Fedora kernel).
