### ISSUE TITLE
k8s-copy-file.bats is failing with CRI-O 1.18.4

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#1080]
Looks like https://github.com/kata-containers/kata-containers/pull/1037 is the offending change.

ref:
http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR/497/
http://jenkins.katacontainers.io/job/kata-containers-2.0-debian-PR/518
http://jenkins.katacontainers.io/job/kata-containers-2.0-centos-PR/518

After reverting the offending commit, cofigmap passes w/o issue:
http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR/522/console
http://jenkins.katacontainers.io/job/kata-containers-2.0-debian-PR/521/console
http://jenkins.katacontainers.io/job/kata-containers-2.0-centos-PR/520/console

**Comment by fidencio** [comment]
@bergwolf, it's not ConfigMap which is failing.  Looking at the logs I see:
```
1..1
ok 1 Running with postStart and preStop handlers
1..1
ok 1 Block Storage Support
1..1
ok 1 ConfigMap for a pod
1..2
Build timed out (after 5 minutes). Marking the build as aborted.
Build was aborted
```

What's failing is the test coming after ConfigMap, which I assume to be "Copy file in a pod" (which matches the 2 tests).

I'll keep debugging this one Tomorrow.

**Comment by fidencio** [comment]
Okay, I've decided to stay a little bit longer.

Turns out that `k8s-copy-file.bats` is **super flaky**, at least on my VM, and there's absolutely no way I can get 10 consecutive runs without facing some (what I think that is) timing issue.  Interestingly enough, I can easily check from the command line that the file exists inside the pod and does have the right content.

**Comment by fidencio** [comment]
Okay, `kubectl cp` simply hangs. :-).
I'll have to get back to this Tomorrow afternoon and do a proper debug on that.

**Comment by fidencio** [comment]
@bergwolf, this is the commit on the CRI-O side that introduced the regression: https://github.com/cri-o/cri-o/commit/217c71453284b46629daeb0f98256ff25e9c20b3

@liubin, as the commit comes from you, what was the case you were fixing when you proposed that patch? Or, IOW, what may break if we revert the patch?

**Comment by fidencio** [comment]
Just for the record, https://github.com/kata-containers/kata-containers/pull/440 is the Kata Containers side of the https://github.com/cri-o/cri-o/commit/217c71453284b46629daeb0f98256ff25e9c20b3.

**Comment by liubin** [comment]
Hi @fidencio , this is the original issue: https://github.com/cri-o/cri-o/issues/4046 , it seems the copy is completed, but IO is not closed.

**Comment by fidencio** [comment]
While on this I found out that https://github.com/cri-o/cri-o/commit/6913515c831b6e795d4bf31a5a11415aa21dfa9e is missing a partial backport.

@liubin, Do you known when `SetInitPid()` was introduced? I see it's not a valid call on 1.18, at least.

**Comment by liubin** [comment]
Do you mean this https://github.com/cri-o/cri-o/commit/009ccb65ec96e47e0d6c1073c90290cdcdf260b0 ? @fidencio

**Comment by fidencio** [comment]
By the way, issue still happens on git main.
@liubin, what was the problem you were trying to solve when https://github.com/cri-o/cri-o/issues/4046 was created? I mean, was there some specific test failing? Is there something I can use to try to reproduce the issue to ensure that we wouldn't introduce yet another regression while fixing this one?

**Comment by liubin** [comment]
This one: https://github.com/kata-containers/tests/issues/2770  @fidencio

**Comment by fidencio** [comment]
Perfect, thanks @liubin!
