### ISSUE TITLE
kata-runtime does not have subcommands "create", delete" after compiling from source

### ISSUE THREAD

**Issue by hdxia** [kata-containers/kata-containers#1082]
Hi,

I compiled the runtime from source with branch 2.0, but when I run it, it does not have any OCI commands such as create, list, etc. Any suggestions?

thanks

/usr/local/bin/kata-runtime
NAME:
    -  runtime

is a command line program for running applications packaged
according to the Open Container Initiative (OCI).

USAGE:
   kata-runtime [global options] command [command options] [arguments...]

VERSION:
     : 2.0.0
   commit   : e2424b9eb19b571fcda413bfcecd95bf894fcce1-dirty
   OCI specs: 1.0.1-dev

COMMANDS:
     version     display version details
     kata-check  tests if system can run Kata Containers
     kata-env    display settings. Default to TOML
     exec        Enter into guest by debug console
     factory     manage vm factory
     help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --kata-config value               Kata Containers config file path
   --log value                       set the log file path where internal debug information is written (default: "/dev/null")
   --log-format value                set the format used by logs ('text' (default), or 'json') (default: "text")
   --root value                      root directory for storage of container state (this should be located in tmpfs) (default: "/var/run/kata-containers")
   --rootless value                  ignore cgroup permission errors ('true', 'false', or 'auto') (default: "auto")
   --kata-show-default-config-paths  show config file paths that will be checked for (in order)
   --systemd-cgroup                  enable systemd cgroup support, expects cgroupsPath to be of form "slice:prefix:name" for e.g. "system.slice:runc:434234"
   --help, -h                        show help
   --version, -v                     print the version

**Comment by caoruidong** [comment]
Kata 2.0 only maintain shimv2 api,no cli https://github.com/kata-containers/kata-containers/issues/332

**Comment by devimc** [comment]
thanks @caoruidong for answering this, closing issue.
