### ISSUE TITLE
Re-add ability to detect stale assets

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#1083]
When we [removed the OCI CLI commands](https://github.com/kata-containers/kata-containers/issues/332), we inadvertently removed a feature:

```bash
$ kata-runtime list  -f json --kata-all
```

The Kata-specific `--kata-all` option extended the default `list` output to include asset details *for the running containers*:

- https://github.com/kata-containers/runtime/blob/master/cli/list.go#L227..L274

It also showed if those container-specific asset versions were "stale". The term "stale" is used to mean that newer asset versions exist locally and implying that the container with stale assets is:

- "long running".
- needs to be restarted to make use of the latest assets.

An alternative to re-adding `list` is to extend the output of `kata-runtime kata-env` to include details of all running containers and their assets (although if we do that, I think we should add an extra option to `kata-env` to show that extra detail).

**Comment by fidencio** [comment]
@jodh-intel, I'm removing the "needs- review" label from this issue.

**Comment by jodh-intel** [comment]
Closing in favour of #1153.
