### ISSUE TITLE
Add ARM64 job in Travis-CI

### ISSUE THREAD

**Issue by odidev** [kata-containers/kata-containers#1087]
Hi Team,

I have been trying to add ARM64 job in Travis for kata-containers. I have done small changes like adding arm64 job in the matrix and install **haveged** dependency. Please check https://github.com/odidev/kata-containers/commit/85d1b77fffbf6fa5250097f0f35de7d9a9b9310e for more details.

I am almost getting the same result as of ppc64le but one extra case is failing stated as below:
```
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -73,3 +73,3 @@
        	            	   },
        	            	-  VMContainerCapable: (bool) true,
        	            	+  VMContainerCapable: (bool) false,
        	            	   SupportVSocks: (bool) true
        	Test:       	TestEnvGetEnvInfoSetsCPUType
--- FAIL: TestEnvGetEnvInfoSetsCPUType (0.14s)
```
Please check [this report](https://travis-ci.com/github/odidev/kata-containers/jobs/428696710) for more details on this.

If you are interested in adding an ARM64 job in Travis, I am happy to contribute to the same.

As a start, can I get any pointers on above issue?

**Comment by jodh-intel** [comment]
Hi @odidev - Thanks for raising and working on this. I think the best person to talk to is @jongwu who I believe manages the aarch64 Jenkins CI we use.

**Comment by jongwu** [comment]
Thanks @odidev -, I'm happy to see someone contribute for arm and you just do what I want to do. 
It seems that travis CI will do unit test then there will be lots of test cases fail. I think what we should do is that analyze the failure case by case. Maybe we can fix it if it's easy to do or just skip it first reserving it for future to fix. It's a good beginning whatever. You can raise a PR in kata-containers then others can involve into to move it fast.

**Comment by odidev** [comment]
@jodh-intel and @jongwu,

Thanks for the reply and support.

I am happy to contribute but we need to use arm64-graviton2 builds to run in **vm** as normal arm64 builds uses lxd containers where it seems **vsock** is not supported. For running arm64-graviton2 builds we need to migrate from **travis-ci.org** to **travis-ci.com**.

**Travis report in travis-ci.com:** https://travis-ci.com/github/odidev/kata-containers/builds/198639870

I can raise PR once Travis execution is migrated to travis-ci.com. We will have to eventually move to travis-ci.com as the .org is going to be disabled at the end of the year.

**Comment by jongwu** [comment]
Thanks @odidev -, I learn a lot from you about the latest news of Travis. There is a big l difference between VM and bare metal for arm. As nested virtualization is not available on arm, some test cases like TestCCCheckCLIFunction which try to get kvm modules will fail. So we can just skip these cases. other failure also need to see into case by case.

By the way，@jodh-intel -, can we put these unit tests on Jenkins? so we can avoid the problem running in VM as the Jenkins test run on bare metal.

**Comment by jodh-intel** [comment]
@jongwu - I thought Jenkins was running all the tests (including unit tests)?:

- https://github.com/kata-containers/tests/blob/master/.ci/jenkins_job_build.sh#L359

I suggest raising a https://github.com/kata-containers/tests issue and maybe discussing with @GabyCT.

**Comment by odidev** [comment]
> Thanks @odidev -, I learn a lot from you about the latest news of Travis. There is a big l difference between VM and bare metal for arm. As nested virtualization is not available on arm, some test cases like TestCCCheckCLIFunction which try to get kvm modules will fail. So we can just skip these cases. other failure also need to see into case by case.
> 
> By the way，@jodh-intel -, can we put these unit tests on Jenkins? so we can avoid the problem running in VM as the Jenkins test run on bare metal.

@jongwu,

I can provide a PR but arm64-graviton2 is considered as amd64 in travis-ci.org. Until migration to travis-ci.com which can be done following https://docs.travis-ci.com/user/migrate/open-source-repository-migration, we can go through issues in arm64 from my local Travis(https://travis-ci.com/github/odidev/kata-containers/jobs/429365913).

Please find below test cases which are failing for arm64:

- **TestVersion** is failing with the below issue

```
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
FAIL
FAIL	github.com/kata-containers/kata-containers/src/runtime/cli	10.767s
?   	github.com/kata-containers/kata-containers/src/runtime/cli/containerd-shim-kata-v2	[no test files]
?   	github.com/kata-containers/kata-containers/src/runtime/cli/kata-monitor	[no test files]

```

- TestEnvGetEnvInfoNoHypervisorVersion
- TestEnvGetEnvInfo
- TestEnvGetHostInfo
- TestEnvGetEnvInfoSetsCPUType

All these above 4 tests are failing with below issue.

```
time="2020-11-06T05:21:22Z" level=info msg="Unable to know if the system is running inside a VM" source=virtcontainers
time="2020-11-06T05:21:22Z" level=info msg="kernel property found" arch=arm64 description="Kernel-based Virtual Machine" name=kvm pid=14245 source=runtime type=module
time="2020-11-06T05:21:22Z" level=warning msg="modprobe insert module failed: modprobe: ERROR: could not insert 'vhost': Operation not permitted\n" arch=arm64 error="exit status 1" module=vhost name=kata-runtime pid=14245 source=runtime
time="2020-11-06T05:21:22Z" level=error msg="kernel property not found" arch=arm64 description="Host kernel accelerator for virtio" name=vhost pid=14245 source=runtime type=module
time="2020-11-06T05:21:22Z" level=warning msg="modprobe insert module failed: modprobe: ERROR: could not insert 'vhost_net': Operation not permitted\n" arch=arm64 error="exit status 1" module=vhost_net name=kata-runtime pid=14245 source=runtime
time="2020-11-06T05:21:22Z" level=error msg="kernel property not found" arch=arm64 description="Host kernel accelerator for virtio network" name=vhost_net pid=14245 source=runtime type=module
time="2020-11-06T05:21:22Z" level=warning msg="modprobe insert module failed: modprobe: ERROR: could not insert 'vhost_vsock': Operation not permitted\n" arch=arm64 error="exit status 1" module=vhost_vsock name=kata-runtime pid=14245 source=runtime
time="2020-11-06T05:21:22Z" level=error msg="kernel property not found" arch=arm64 description="Host Support for Linux VM Sockets" name=vhost_vsock pid=14245 source=runtime type=module
    TestEnvGetEnvInfoSetsCPUType: kata-env_generic_test.go:51: 
        	Error Trace:	kata-env_generic_test.go:51
        	            				kata-env_arm64_test.go:20
        	Error:      	Not equal: 
        	            	expected: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.25"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Version:main.VersionInfo{Semver:"2.0.0-rc0", Major:0x2, Minor:0x0, Patch:0x0, Commit:"cbc3f6cf500b240f79117b22be08689a4429da68"}, OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/174767832/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, SandboxCgroupOnly:false, Experimental:[]experimental.Feature(nil), Path:"/tmp/go-build179574780/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/174767832/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", SharedFS:"virtio-9p", VirtioFSDaemon:"/tmp/174767832/virtiofsd", Msize9p:0x2000, MemorySlots:0xa, PCIeRootPort:0x2, HotplugVFIOOnRootBus:true, Debug:false}, Image:main.ImageInfo{Path:"/tmp/174767832/image"}, Kernel:main.KernelInfo{Path:"/tmp/174767832/kernel", Parameters:"systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Agent:main.AgentInfo{Debug:false, Trace:false, TraceMode:"", TraceType:""}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8", CPUs:2}, Memory:main.MemoryInfo{Total:0x7969b8, Free:0x43d3d4, Available:0x702d74}, VMContainerCapable:true, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:main.VersionInfo{Semver:"<<unknown>>", Major:0x0, Minor:0x0, Patch:0x0, Commit:"<<unknown>>"}, Path:"/tmp/174767832/netmon", Debug:false, Enable:false}}
        	            	actual  : main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.25"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Version:main.VersionInfo{Semver:"2.0.0-rc0", Major:0x2, Minor:0x0, Patch:0x0, Commit:"cbc3f6cf500b240f79117b22be08689a4429da68"}, OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/174767832/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, SandboxCgroupOnly:false, Experimental:[]experimental.Feature(nil), Path:"/tmp/go-build179574780/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/174767832/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", SharedFS:"virtio-9p", VirtioFSDaemon:"/tmp/174767832/virtiofsd", Msize9p:0x2000, MemorySlots:0xa, PCIeRootPort:0x2, HotplugVFIOOnRootBus:true, Debug:false}, Image:main.ImageInfo{Path:"/tmp/174767832/image"}, Kernel:main.KernelInfo{Path:"/tmp/174767832/kernel", Parameters:"systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Agent:main.AgentInfo{Debug:false, Trace:false, TraceMode:"", TraceType:""}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8", CPUs:2}, Memory:main.MemoryInfo{Total:0x7969b8, Free:0x43d3d4, Available:0x702d74}, VMContainerCapable:false, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:main.VersionInfo{Semver:"<<unknown>>", Major:0x0, Minor:0x0, Patch:0x0, Commit:"<<unknown>>"}, Path:"/tmp/174767832/netmon", Debug:false, Enable:false}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -73,3 +73,3 @@
        	            	   },
        	            	-  VMContainerCapable: (bool) true,
        	            	+  VMContainerCapable: (bool) false,
        	            	   SupportVSocks: (bool) true
```
Can I get any suggestions on above issues?

**Comment by odidev** [comment]
I was able to pass these tests after updating `expectedVMContainerCapable := false` in **src/runtime/cli/kata-env_arm64_test.go**. But I am not sure whether we can make them pass with this method and for raising a PR with all these changes travis-ci needs to be   migrated to travis-ci.com as I am using arm64-graviton2 which works in travis-ci.com only.

**Comment by jongwu** [comment]
thanks @odidev -, I think that the most test workload has been undertaken by jenkins in kata. so we can let travis do something in small area like x86 does. It will be easy to do.

**Comment by fidencio** [comment]
@jongwu, @odidev, we stopped relying on Travis by the end of the last year.  With that in mind, I'll close this issue.

@odidev, as you could feel from @jongwu and @jodh-intel, contributions are super welcome and we'd love to have help in all areas you want to help!  So, please, reach us out eithar via IRC or Slack!

Thanks a lot for the issue raised!
