### ISSUE TITLE
kata-collect no longer exist in 2.0

### ISSUE THREAD

**Issue by didier-durand** [kata-containers/kata-containers#1112]
Hi There,

The template of an issue like this one mentions the need to need to use kata-collect.sh to supply config info.

When kata is installed via snap, kata-collect is no longer present.

Thanks!

Didier

## to replicate

**sudo snap install kata-containers --classic**
kata-containers 2.0.0 from Kata Containers (katacontainers*) installed

**sudo snap list | grep 'kata-containers'**
kata-containers   2.0.0     705    latest/stable    katacontainers*    classic

**sudo find / -name 'kata*'**

/snap/bin/kata-containers.runtime
/snap/kata-containers
/snap/kata-containers/705/usr/bin/kata-collect-data.sh
/snap/kata-containers/705/usr/bin/kata-monitor
/snap/kata-containers/705/usr/bin/kata-runtime
/snap/kata-containers/705/usr/libexec/kata-containers
/snap/kata-containers/705/usr/libexec/kata-containers/kata-netmon
/snap/kata-containers/705/usr/share/bash-completion/completions/kata-runtime
/snap/kata-containers/705/usr/share/defaults/kata-containers
/snap/kata-containers/705/usr/share/kata-containers
/snap/kata-containers/705/usr/share/kata-containers/kata-containers.img
/usr/lib/python3/dist-packages/sos/report/plugins/__pycache__/kata_containers.cpython-38.pyc
/usr/lib/python3/dist-packages/sos/report/plugins/kata_containers.py
/var/snap/kata-containers
/var/lib/snapd/snaps/kata-containers_705.snap
/var/lib/snapd/sequence/kata-containers.json

**Comment by c3d** [comment]
Indeed, the template is wrong. It should be `kata-collect-data.sh`.

**Comment by c3d** [comment]
Actually, I just checked the template, and it does say `kata-collect-data.sh`. @didier-durand where did you find a template mentioning `kata-collect.sh`?

**Comment by didier-durand** [comment]
@c3d : My bad: I misread the template. Sorry for that!

Anyway to use kata-collect-data.sh, I need to give its full path (originated in the snap library) : /snap/kata-containers/705/usr/bin/kata-collect-data.sh

Shouldn' t it be aliased to 'kata-collect-data.sh to make it more convenient to use ? I have such aliases when I use other snaps (microk8s, lxc, etc.) . Additionally, the wording in the template says that you have to do 'sudo kata-collect-data.sh'

But, I get:

> sudo kata-collect-data.sh
sudo: kata-collect-data.sh: command not found

Finally, when I use the absolute path, result is not what you would expect. See below: "runtime too old" is worrying as I am on last version,

Do I miss something here ? (I just switched to v2.0 from from 1.12 install working fine)
Thanks for your help!
Didier

## sudo /snap/kata-containers/705/usr/bin/kata-collect-data.sh

sudo /snap/kata-containers/705/usr/bin/kata-collect-data.sh
<details>
<summary>Show <tt>kata-collect-data.sh</tt> details</summary>
<p>


# Meta details

Running `kata-collect-data.sh` version `2.0.0 (commit af462824669685616ea4db9356056bb6d8382d21)` at `2020-11-13.11:51:26.525334988+0000`.

---

<details>
<summary>Runtime</summary>
<p>

Runtime is `/snap/bin/kata-containers.runtime`.

# `kata-env`

<details>
<summary><tt>/snap/bin/kata-containers.runtime kata-env</tt></summary>
<p>

```toml
io.containerd.kata.v2: shim namespace cannot be empty
```

</p>
</details>

---


</p>
</details>
<details>
<summary>Runtime config files</summary>
<p>


# Runtime config files

flag provided but not defined: -kata-show-default-config-paths
Usage of /snap/kata-containers/705/usr/bin/containerd-shim-kata-v2:
  -address string
    	grpc address back to main containerd
  -bundle string
    	path to the bundle if not workdir
  -debug
    	enable debug output in logs
  -id string
    	id of the task
  -namespace string
    	namespace that owns the shim
  -publish-binary string
    	path to publish binary (used for publishing events) (default "containerd")
  -socket string
    	abstract socket path to serve
ERROR: kata-collect-data.sh: failed to check config files - runtime is probably too old (Kata Containers containerd shim: id: "io.containerd.kata.v2", version: 2.0.0, commit: af462824669685616ea4db9356056bb6d8382d21 )

**Comment by jodh-intel** [comment]
Thanks for reporting @didier-durand.

@devimc - it looks like we may be setting the runtime variable as the shim (which doesn't support `--kata-show-default-config-paths`).

**Comment by jodh-intel** [comment]
@devimc - looking at the collect script, I wonder if we should allow all the variables at the top to have a default value, but also allow them to be set by the user so they can override in case of problems like the one reported on this issue:

```diff
-typeset -r runtime_name="@RUNTIME_NAME@"
+typeset -r runtime_name="${runtime_name:-@RUNTIME_NAME@}"
```

**Comment by didier-durand** [comment]
@jodh-intel : you're welcome. Happy to provide more info if needed. Didier

**Comment by devimc** [comment]
@didier-durand thanks for raising this, https://github.com/kata-containers/kata-containers/pull/1124 should fix this and https://github.com/kata-containers/kata-containers/issues/1122 , also https://github.com/kata-containers/.github/pull/31 updates the bug report template.
Henceforth you can use the following equivalent kata snap commands:

```
kata-containers.runtime      -> kata-runtime
kata-containers.shim         -> containerd-shim-kata-v2
kata-containers.collect-data -> kata-collect-data.sh
```

**Comment by didier-durand** [comment]
Thanks!
Last question: do you know the snap number under which it will be available?

**Comment by devimc** [comment]
@didier-durand  710

**Comment by didier-durand** [comment]
Merci!

**Comment by didier-durand** [comment]
I just tried: snap 705 is still the version that comes for me

kata-containers   2.0.0     705    latest/stable    katacontainers*    classic

I'll try again tomorrow

**Comment by devimc** [comment]
@didier-durand https://github.com/kata-containers/kata-containers/pull/1124 has not been merged :sweat_smile:

**Comment by didier-durand** [comment]
Now , I understand better! ;-)

**Comment by devimc** [comment]
fixed, @didier-durand I've released a new version of kata-containers, you can install it running the following command:

```
 sudo snap install --edge --classic kata-containers
```


thanks

**Comment by didier-durand** [comment]
It is all right:

sudo snap install --edge --classic kata-containers
kata-containers (edge) 2.0.1 from Kata Containers (katacontainers✓) installed

sudo snap list
Name              Version   Rev    Tracking         Publisher          Notes
core18            20200929  1932   latest/stable    canonical✓         base
core20            20        634    latest/stable    canonical✓         base
google-cloud-sdk  318.0.0   159    latest/stable/…  google-cloud-sdk✓  classic
**kata-containers   2.0.1     710    latest/edge      katacontainers✓    classic**
lxd               4.7       18137  latest/stable/…  canonical✓         -
snapd             2.47.1    9721   latest/stable    canonical✓         snapd

That's why I love snaps: very fast & direct path from producer to consumer while remaining fully structured.

I don't have time to test tonight but I'll do that tomorrow morning 1st thing to confirm here.

Didier

**Comment by devimc** [comment]
@didier-durand they work fine if you run them with `sudo`, the issue you are facing in https://github.com/kata-containers/kata-containers/issues/1131 is expected since `kata-runtime check` is unable to load kernel modules, I'm working on that.

**Comment by didier-durand** [comment]
@devimc fine, pls, let me know when there is a new snap available for testing.

**Comment by devimc** [comment]
@didier-durand sure thing, thanks for testing
