### ISSUE TITLE
kata-runtime kata-check no longer working when kata 2.0 installed via snap

### ISSUE THREAD

**Issue by didier-durand** [kata-containers/kata-containers#1113]
Hello,

# Description of problem 

I have upgraded a working Kata test case from version 1.12 installed by bash -c "$(curl -fsSL https://raw.githubusercontent.com/kata-containers/tests/master/cmd/kata-manager/kata-manager.sh) install-docker-system" to version 2 now installed by 
sudo snap install kata-containers --classic

I was using with v1 /bin/kata-runtime kata-check and kata-runtime kata-env to validate my install.

Now when I do the same but with the kata runtime found in snap, I get  that the system is NOT capable to run Katas: it was in the past.

/snap/kata-containers/705/usr/bin/kata-runtime kata-check

No newer release available
WARN[0000] modprobe insert module failed: modprobe: ERROR: could not insert 'vhost_vsock': Operation not permitted  arch=amd64 error="exit status 1" module=vhost_vsock name= pid=4516 source=runtime
ERRO[0000] kernel property not found                     arch=amd64 description="Host Support for Linux VM Sockets" name=vhost_vsock pid=4516 source=runtime type=module
WARN[0000] modprobe insert module failed: modprobe: ERROR: could not insert 'vhost': Operation not permitted  arch=amd64 error="exit status 1" module=vhost name= pid=4516 source=runtime
ERRO[0000] kernel property not found                     arch=amd64 description="Host kernel accelerator for virtio" name=vhost pid=4516 source=runtime type=module
WARN[0000] modprobe insert module failed: modprobe: ERROR: could not insert 'vhost_net': Operation not permitted  arch=amd64 error="exit status 1" module=vhost_net name= pid=4516 source=runtime
ERRO[0000] kernel property not found                     arch=amd64 description="Host kernel accelerator for virtio network" name=vhost_net pid=4516 source=runtime type=module
ERRO[0000] ERROR: System is not capable of running Kata Containers  arch=amd64 name= pid=4516 source=runtime
**ERROR: System is not capable of running Kata Containers**

# Expected result

I would expect system to continue being able to run Katas

# Actual result

see above

# Configuration

(I could not run kata-collect as requested : see https://github.com/kata-containers/kata-containers/issues/1112)

install kata containers:
kata-containers 2.0.0 from Kata Containers (katacontainers*) installed

sudo snap list | grep 'kata-containers'
kata-containers   2.0.0     705    latest/stable    katacontainers*    classic

**Comment by jodh-intel** [comment]
Hi @didier-durand - I assume you were running as a non-privileged user? Can you check what happens when you run `sudo kata-runtime kata-check`? running as `root` runs additional checks so would be interesting to compare the output on your system.

/cc @devimc.

**Comment by didier-durand** [comment]
@jodh-intel: 

To answer your question: yes, I run without sudo privilege.

I will close this one with 'can't reproduce' because GCE has updated its version of Ubuntu 20.04 on the 13th with a new cut named 'ubuntu-2004-focal-v20201111'. I use a fully automated script that starts with a fresh instance each time: so, when I restart now, 'kata-runtime kata-check' runs fine (sudo or not) because vhost_vsock can now be loaded - see below - with the new Ubuntu release (I can no longer access the older one). I don't have the details of the changes made to Ubuntu install.

/snap/kata-containers/705/usr/bin/kata-runtime kata-check
No newer release available
System is capable of running Kata Containers

ddurand@microk8s-kata:~$ lsmod
Module                  Size  Used by
vhost_vsock            24576  0
vmw_vsock_virtio_transport_common    32768  1 vhost_vsock
vsock                  36864  2 vmw_vsock_virtio_transport_common,vhost_vsock
vhost_net              32768  0
tap                    24576  1 vhost_net
vhost                  49152  2 vhost_vsock,vhost_net
nls_iso8859_1          16384  1
dm_multipath           32768  0
scsi_dh_rdac           16384  0
scsi_dh_emc            16384  0
scsi_dh_alua           20480  0
kvm_intel             282624  0
kvm                   663552  1 kvm_intel
virtio_net             53248  0
net_failover           20480  1 virtio_net
psmouse               155648  0
failover               16384  1 net_failover
crct10dif_pclmul       16384  1
crc32_pclmul           16384  0
ghash_clmulni_intel    16384  0
aesni_intel           372736  0
input_leds             16384  0
serio_raw              20480  0
crypto_simd            16384  1 aesni_intel
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
glue_helper            16384  1 aesni_intel
sch_fq_codel           20480  5
drm                   491520  0
virtio_rng             16384  0
ip_tables              32768  0
x_tables               40960  1 ip_tables
autofs4                45056  2

**Comment by jodh-intel** [comment]
Ok, thanks @didier-durand. Feel free to re-open if need be in future.
