### ISSUE TITLE
snap install kata-runtime : /bin/kata-runtime no longer exists - Only usable from /snap dir: impact on Docker

### ISSUE THREAD

**Issue by didier-durand** [kata-containers/kata-containers#1122]
In Kata v1, `kata-runtime` was loaded in /bin with the standard runtime `runc`.

When I move to v2 with an install via snap (currently at v 705 - see below), `kata-runtime` is now only accessible at `/snap/kata-containers/current/usr/bin/kata-runtime` (current is linked to xxx where xxx is snap version) which is a product specific instance.

If we compare with other snaps: they tend to keep such binaries on $PATH. See example below with the snap install of Docker.

So, shouldn't we also avoid references to `/snap/kata-containers/current/usr/bin/kata-runtime` ?

Impact on Docker is described in #1123 

Thanks!

Didier

ddurand@microk8s-kata:~$ which docker
/snap/bin/docker

ddurand@microk8s-kata:~$ ls -l /snap/bin/docker
lrwxrwxrwx 1 root root 13 Nov 16 14:39 /snap/bin/docker -> /usr/bin/snap

ddurand@microk8s-kata:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

ddurand@microk8s-kata:~$ which kata-runtime

ddurand@microk8s-kata:~$ sudo snap list
Name              Version    Rev    Tracking         Publisher          Notes
core              16-2.47.1  10185  latest/stable    canonical✓         core
core18            20200929   1932   latest/stable    canonical✓         base
core20            20         634    latest/stable    canonical✓         base
docker            19.03.11   471    latest/stable    canonical✓         -
google-cloud-sdk  318.0.0    159    latest/stable/…  google-cloud-sdk✓  classic
kata-containers   2.0.0      705    latest/stable    katacontainers✓    classic
lxd               4.0.4      18150  4.0/stable/…     canonical✓         -
snapd             2.47.1     9721   latest/stable    canonical✓         snapd
ddurand@microk8s-kata:~$

**Comment by devimc** [comment]
@didier-durand thanks for raising this, I will fix it in the next release

**Comment by didier-durand** [comment]
@devimc : you're welcome! Question for you: how can I now that a new version of the snap gets published? I'd like to get pinged by some automated process when you release a new version > my current v705. Thanks!  Didier

**Comment by devimc** [comment]
> I'd like to get pinged by some automated process when you release a new version > my current v705. Thanks! Didier

afaik that's not possible, snapd will update the package automatically when a new version is detected

**Comment by didier-durand** [comment]
I had same understanding. But, I hoped that you knew something better. Thanks anyway.
