### ISSUE TITLE
`service.StartShim()` does not need to wait Shim process to finish

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1127]
In [`(s *service) StartShim`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/service.go#L169), a new shim process will be started to serve as ttrpc server, and the current  shim process will write the socket  address back  to containerd and exit, [there](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/service.go#L218-L219) is no need to wait the second shim process.

```
// make sure to wait after start
go cmd.Wait()
```

@lifupan can we delete this two lines?

**Comment by lifupan** [comment]
@liubin  Yeah, you are right, I do think there's no need to wait it here.
