### ISSUE TITLE
[k8s + kata] kubernetes hostPath volume mount not working with kata 2.0 

### ISSUE THREAD

**Issue by lining2020** [kata-containers/kata-containers#1129]
# Description of problem
kubernetes hostPath volume mount is not working in kata 2.0 

Kata version: kata-static-2.0.0-x86_64.tar (the only kata 2.0 release)

Here is my testing pod yaml. 
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  runtimeClassName: kata
  containers:
  - name: busybox-pod
    image: busybox
    command: ["sleep", "60000"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /tmp/
      name: tmp
  volumes:
  - name: tmp
    hostPath:
      path: /tmp/
```

# Expected result

Pod can run normally.

# Actual result

Pod failed to start.

```
ln@ubuntu:~$ kubectl describe pod busybox
Name:         busybox
Namespace:    default
Priority:     0
Node:         ubuntu/172.20.146.80                                                                                                                Start Time:   Wed, 18 Nov 2020 22:11:09 +0800                                                                                                     Labels:       name=busybox
Annotations:  <none>
Status:       Running
IP:           10.244.0.14                                                                                                                         IPs:                                                                                                                                                IP:  10.244.0.14                                                                                                                                Containers:
  busybox-pod:                                                                                                                                        Container ID:  containerd://b714b2a8190dd8ad7278ed4d68832b637f7b9ecfd30b534f1a389b6b82b85b8f
    Image:         busybox                                                                                                                            Image ID:      docker.io/library/busybox@sha256:a9286defaba7b3a519d585ba0e37d0b2cbee74ebfe590960b0b1d6a5e97d1e1d
    Port:          <none>                                                                                                                             Host Port:     <none>                                                                                                                             Command:                                                                                                                                            sleep                                                                                                                                             60000                                                                                                                                           State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: vm_path:/dev/sdb doesn't exist: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 08:00:00 +0800
      Finished:     Wed, 18 Nov 2020 22:14:02 +0800
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /tmp/ from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-95rz7 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tmp:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/
    HostPathType:
  default-token-95rz7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-95rz7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                       node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m24s                  default-scheduler  Successfully assigned default/busybox to ubuntu
  Normal   Pulled     4m14s                  kubelet            Successfully pulled image "busybox" in 8.745293222s
  Warning  Failed     4m8s                   kubelet            Error: failed to create containerd task: ENOENT: No such file or directory: unknown
  Normal   Pulled     3m55s                  kubelet            Successfully pulled image "busybox" in 11.941361844s
  Normal   Pulled     3m27s                  kubelet            Successfully pulled image "busybox" in 5.459255929s
  Warning  Failed     3m18s (x2 over 3m49s)  kubelet            Error: failed to create containerd task: vm_path:/dev/sdb doesn't exist: unknown
  Normal   Pulled     2m39s                  kubelet            Successfully pulled image "busybox" in 13.796570185s
  Normal   Created    2m32s (x4 over 4m10s)  kubelet            Created container busybox-pod
  Warning  Failed     2m30s                  kubelet            Error: failed to create containerd task: vm_path:/dev/sda doesn't exist: unknown
  Warning  BackOff    2m2s (x7 over 3m48s)   kubelet            Back-off restarting failed container
  Normal   Pulling    109s (x5 over 4m22s)   kubelet            Pulling image "busybox"
  Normal   Pulled     95s                    kubelet            Successfully pulled image "busybox" in 13.868126858s
```

# Further information
When I replace the runtimeClassName with runc, the busybox pod can bootup normally
runtimeClass yaml
```
kind: RuntimeClass
metadata:
  name: runc
handler: runc
---
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: kata
handler: kata
```
<details>
<summary>/etc/containerd/config.toml.</summary>
<pre><code>
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
plugin_dir = ""
disabled_plugins = []
required_plugins = []
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  tcp_address = ""
  tcp_tls_cert = ""
  tcp_tls_key = ""
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[ttrpc]
  address = ""
  uid = 0
  gid = 0

[debug]
  address = ""
  uid = 0
  gid = 0
  level = ""

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[timeouts]
  "io.containerd.timeout.shim.cleanup" = "5s"
  "io.containerd.timeout.shim.load" = "5s"
  "io.containerd.timeout.shim.shutdown" = "3s"
  "io.containerd.timeout.task.state" = "2s"

[plugins]
  [plugins."io.containerd.gc.v1.scheduler"]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
  [plugins."io.containerd.grpc.v1.cri"]
    disable_tcp_service = true
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    stream_idle_timeout = "4h0m0s"
    enable_selinux = false
    sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2"
    stats_collect_period = 10
    systemd_cgroup = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    disable_cgroup = false
    disable_apparmor = false
    restrict_oom_score_adj = false
    max_concurrent_downloads = 3
    disable_proc_mount = false
    [plugins."io.containerd.grpc.v1.cri".containerd]
      snapshotter = "overlayfs"
      default_runtime_name = "runc"
      no_pivot = false
      [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]
        runtime_type = ""
        runtime_engine = ""
        runtime_root = ""
        privileged_without_host_devices = false
      [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime]
        runtime_type = ""
        runtime_engine = ""
        runtime_root = ""
        privileged_without_host_devices = false
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v1"
          runtime_engine = ""
          runtime_root = ""
          privileged_without_host_devices = false
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"
          runtime_engine = ""
          runtime_root = ""
          privileged_without_host_devices = false
    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"
      max_conf_num = 1
      conf_template = ""
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
    [plugins."io.containerd.grpc.v1.cri".x509_key_pair_streaming]
      tls_cert_file = ""
      tls_key_file = ""
  [plugins."io.containerd.internal.v1.opt"]
    path = "/opt/containerd"
  [plugins."io.containerd.internal.v1.restart"]
    interval = "10s"
  [plugins."io.containerd.metadata.v1.bolt"]
    content_sharing_policy = "shared"
  [plugins."io.containerd.monitor.v1.cgroups"]
    no_prometheus = false
  [plugins."io.containerd.runtime.v1.linux"]
    shim = "containerd-shim"
    runtime = "runc"
    runtime_root = ""
    no_shim = false
    shim_debug = false
  [plugins."io.containerd.runtime.v2.task"]
    platforms = ["linux/amd64"]
  [plugins."io.containerd.service.v1.diff-service"]
    default = ["walking"]
  [plugins."io.containerd.snapshotter.v1.devmapper"]
    root_path = ""
    pool_name = ""
    base_image_size = ""
</code></pre>
</details>

**Comment by lining2020** [comment]
hello  kata comunity,

Do you have any practice on k8s with kata 2.0, can they work well now.

**Comment by liubin** [comment]
Hi , @lining2020 , you have closed this issue, had you resolved the problem ?

**Comment by lining2020** [comment]
Hi @liubin, Actually not. 

I found that this problem is related to the `securityContext`.
```
securityContext:
    privileged: true
```
When I set `privilege` to `false`, the pod can run normally. And set `privileged` to `true`, the pod can not start (which is the problem I raised in this ticket). 

I am not sure this is a limit of kata containers, I need to have a look at docs, so I close the issue temporarily .

**Comment by lining2020** [comment]
@liubin If you are familiar with how the file/device passed to Pod works, please help confirm whether this is a bug or a limitation of kata.

**Comment by liubin** [comment]
I tested with `crictl`, it worked. 

```
pid=`sudo crictl runp -r kata ~/vagrant/pod.yaml` && echo $pid
cid=`sudo crictl create $pid ~/vagrant/container.yaml ~/vagrant/pod.yaml` && echo $cid
sudo crictl start $cid

sudo crictl exec -it $cid bash
```
Yaml files:

```yaml
# pod.yaml 
metadata:
  attempt: 1
  name: test-pod
  namespace: default
  uid: hdishd83djaidwnduwk28bcsb
log_directory: /tmp
dns_config:
  servers:
    - 3.4.5.6
  searches:
    - dns-kata.test.search  
linux:
  namespaces:
    options: {}
  security_context:
    privileged: true
```

```yaml
# container.yaml 
metadata:
  name: stress
image:
  image: containerstack/alpine-stress:latest
command:
- top
mounts:
- container_path: /tmp
  host_path: /tmp
linux:
  resources:
    memory_limit_in_bytes: 524288000
log_path: stress.0.log
```

**Comment by lining2020** [comment]
@liubin Thanks for your info. I was using  containerd 1.4.1，k8s 1.19.0. 
Let me try it again using another versions.

**Comment by liubin** [comment]
And, it's not a problem of `hostPath`, may be of `privileged`. I deleted volume from Pod and leaved:

```yaml
securityContext:
  privileged: true
```

This will get the same error.

**Comment by lining2020** [comment]
@liubin YES，I just means maybe the privileged issue, not the problem of hostPath.

**Comment by liubin** [comment]
@lining2020 this may help you https://github.com/kata-containers/runtime/issues/1568#issuecomment-519475588

**Comment by lining2020** [comment]
> @liubin YES!，I just means maybe the `privileged` issue, not `hostPath`.
> But I can not reproduce the issue without volume mounting just leaving the `securityContext\n privileged: true`
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: busybox
>   labels:
>     name: busybox
> spec:
>   runtimeClassName: kata
>   containers:
>   - name: busybox-pod
>     image: busybox
>     command: ["sleep", "60000"]
>     securityContext:
>       privileged: true
> ```

: ( , I am so confused  now. Now It came into another error reporting.
I meet the following error using the this YAML now.
```
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  16s               default-scheduler  Successfully assigned default/busybox to ubuntu
  Normal   Pulled     6s                kubelet            Successfully pulled image "busybox" in 8.750052286s
  Normal   Created    4s                kubelet            Created container busybox-pod
  Warning  Failed     1s                kubelet            Error: failed to create containerd task: ENOENT: No such file or directory: unknown
  Normal   Pulling    0s (x2 over 15s)  kubelet            Pulling image "busybox"
```

**Comment by lining2020** [comment]
I think i am not very clear about what is the problem now, so keep the issue closed.
And I open a new one when I get clear about what the problem is.
