### ISSUE TITLE
kata-runtime v2.0.0 is missing oci commands

### ISSUE THREAD

**Issue by cskarby** [kata-containers/kata-containers#1133]
# Description of problem

kata-runtime is a command line program for running applications packaged according to the Open Container Initiative (OCI), however kata-runtime v2.0.0 is missing commands required by the [specification](https://github.com/opencontainers/runtime-spec/blob/44341cdd36f6fee6ddd73e602f9e3eca1466052f/runtime.md#operations).

To reproduce download the binaries from the release and run -h
```
wget https://github.com/kata-containers/kata-containers/releases/download/2.0.0/kata-static-2.0.0-x86_64.tar.xz && \
tar xfv kata-static-2.0.0-x86_64.tar.xz && \
./opt/kata/bin/kata-runtime -h
```
An OCI compatible runtime is required in order to work with [cri-o](https://cri-o.io/)

# Expected result
It is expected that kata-runtime supports all operations from the [OCI Runtime specification](https://github.com/opencontainers/runtime-spec/blob/44341cdd36f6fee6ddd73e602f9e3eca1466052f/runtime.md#operations)

Here is output from kata-runtime v1.11.4, showing state,create,start,kill,delete commands as required by the spec.
```
NAME:
   kata-runtime - kata-runtime runtime

kata-runtime is a command line program for running applications packaged
according to the Open Container Initiative (OCI).

USAGE:
   kata-runtime [global options] command [command options] [arguments...]

VERSION:
   kata-runtime  : 1.11.4
   commit   : 0c07dedd123b2e0255d5780461b077264a47c3bc
   OCI specs: 1.0.1-dev

COMMANDS:
     create         Create a container
     delete         Delete any resources held by one or more containers
     exec           Execute new process inside the container
     kill           Kill sends signals to the container's init process
     list           lists containers started by kata-runtime with the given root
     pause          suspend all processes in a container
     ps             ps displays the processes running inside a container
     resume         unpause all previously paused processes in a container
     run            create and run a container
     spec           create a new specification file
     start          executes the user defined process in a created container
     state          output the state of a container
     update         update container resource constraints
     events         display container events such as OOM notifications, cpu, memory, and IO usage statistics
     version        display version details
     kata-check     tests if system can run Kata Containers
     kata-env       display settings. Default to TOML
     kata-network   manage interfaces and routes for container
     kata-overhead  provides kata overhead at sandbox level
     factory        manage vm factory
     help, h        Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --kata-config value               Kata Containers config file path
   --log value                       set the log file path where internal debug information is written (default: "/dev/null")
   --log-format value                set the format used by logs ('text' (default), or 'json') (default: "text")
   --root value                      root directory for storage of container state (this should be located in tmpfs) (default: "/var/run/kata-containers")
   --rootless value                  ignore cgroup permission errors ('true', 'false', or 'auto') (default: "auto")
   --kata-show-default-config-paths  show config file paths that will be checked for (in order)
   --systemd-cgroup                  enable systemd cgroup support, expects cgroupsPath to be of form "slice:prefix:name" for e.g. "system.slice:runc:434234"
   --help, -h                        show help
   --version, -v                     print the version

NOTES:

- Commands starting "kata-" and options starting "--kata-" are Kata Containers extensions.

URL:

  The canonical URL for this project is: https://github.com/kata-containers
```

# Actual result

Here is output from kata-runtime v2.0.0, where the follwing commands required by [the spec](https://github.com/opencontainers/runtime-spec/blob/44341cdd36f6fee6ddd73e602f9e3eca1466052f/runtime.md#operations) are missing: state,create,start,kill,delete
```
NAME:
    -  runtime

 is a command line program for running applications packaged
according to the Open Container Initiative (OCI).

USAGE:
   kata-runtime [global options] command [command options] [arguments...]

VERSION:
     : 2.0.0
   commit   : aa295c91f2ec5ec3389992111a1c6acecb46024b
   OCI specs: 1.0.1-dev

COMMANDS:
     version     display version details
     kata-check  tests if system can run Kata Containers
     kata-env    display settings. Default to TOML
     exec        Enter into guest by debug console
     factory     manage vm factory
     help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --kata-config value               Kata Containers config file path
   --log value                       set the log file path where internal debug information is written (default: "/dev/null")
   --log-format value                set the format used by logs ('text' (default), or 'json') (default: "text")
   --root value                      root directory for storage of container state (this should be located in tmpfs) (default: "/var/run/kata-containers")
   --rootless value                  ignore cgroup permission errors ('true', 'false', or 'auto') (default: "auto")
   --kata-show-default-config-paths  show config file paths that will be checked for (in order)
   --systemd-cgroup                  enable systemd cgroup support, expects cgroupsPath to be of form "slice:prefix:name" for e.g. "system.slice:runc:434234"
   --help, -h                        show help
   --version, -v                     print the version

NOTES:

- Commands starting "kata-" and options starting "--kata-" are Kata Containers extensions.

URL:

  The canonical URL for this project is: https://github.com/kata-containers

```

# Further information

Trying to use kata-runtime v2.0.0 with cri-o provides the follwing error message:
```
Warning  FailedCreatePodSandBox  9s (x2 over 25s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: Invalid command "create"
```

This indicates that it is not just about the documentation provided via the -h help flag, but actually something is missing in the kata-runtime v2.0.0 in order to be an OCI compatible runtime.

**Comment by bergwolf** [comment]
hi, we intentionally dropped OCI command line support in favor of the newer v2 shim architecture, which both containerd and cri-o have supported for a long time. The new architecture is more stable and saves a lot of shim processes in production deployments.

That said, it seems that the crio installation guide need some updating to tell how to set up shimv2 daemon.

To be short, to configure crio, you need something like:
```
$ sudo tee -a "/etc/crio/crio.conf.d/99-runtime.conf" > /dev/null <<EOF
[crio.runtime]
default_runtime = "runc"
manage_ns_lifecycle = true
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_root = "/run/vc"
runtime_type = "vm"
privileged_without_host_devices = true
[crio.runtime.runtimes.runc]
runtime_path = "/usr/local/bin/crio-runc"
runtime_type = "oci"
runtime_root = "/run/runc"
EOF
```

**Comment by cskarby** [comment]
I managed to get it into a semiworking state following the new instructions, except I had to remove the `runtime_root = "/run/vc"` in the crio.runtime.runtimes.kata section you provided. However I experience problems with some containers and kata-collect-data.sh is not working, so I've filed a separate issue for that, see #1164

**Comment by fidencio** [comment]
@cskarby, I'm closing this one as we'll be tracking the re-addition (or not) of the OCI CLI commands as part o the issue #722.  Please, feel free to subscribe to that issue for getting updates on this.

**Comment by struanb** [comment]
I'm sharing the following in case it's helpful to anyone who, like us, needed VM isolation for their container workloads, a virtiofs-based solution (ruling out Kata v1) and compatibility with `docker run` or `podman run` (ruling out Kata v2).

Due to issues like this one, experienced using Docker/Podman CLI to launch Kata Containers, we built [RunCVM](https://github.com/newsnowlabs/runcvm) (Run Container VM): an experimental open-source Docker container runtime, for launching standard container workloads in VMs.

Please note that RunCVM is not a direct competitor to Kata: as an experimental runtime, RunCVM cannot offer the same levels of stability and support as Kata. However RunCVM _may_ be suitable for some use cases and _is compatible_ with `docker run` today (with experimental support for `podman run`). Like Kata v2, RunCVM is also virtiofs-based for speed. RunCVM has minimal system dependencies: it relies on the Linux KVM module, and can even be installed in a [GitHub Codespace](https://codespaces.new/newsnowlabs/runcvm).
