### ISSUE TITLE
How to install Kata Containers via Snap on Ubuntu

### ISSUE THREAD

**Issue by dev-rke** [kata-containers/kata-containers#1138]
Hi there,

i am new to kata, when installing, i had to solve a lot of issues. 
This enhancement request is intended to improve documentation and help others also having issues installing kata via snap.

## Installation via Snap

My Environment: Ubuntu 18.04 Desktop using Docker 19.03.13.
The most simple approach i thought was installing it using [snap](https://github.com/kata-containers/documentation/blob/master/install/README.md#packaged-installation-methods).
So i installed it using `sudo snap install kata-containers --classic`, as described in the [documentation](https://github.com/kata-containers/documentation/blob/master/install/snap-installation-guide.md), which is also one of the first hits on google.

## Steps to get kata running

When running `docker run hello-world`, kata did not run.
Then i reasearched and copied the [configuration](https://github.com/kata-containers/packaging/blob/master/snap/README.md#configure-kata-containers) from the snap to my host.
Then i found out via github issues, that kata 2.0 seems to be not compatible with docker due to some shim issues, so i switched the snap channel to receive the older version 1.12.0 using the command `sudo snap refresh kata-containers --channel=latest/candidate`.
This still was not working using docker run, as i got the message, that the runtime file was not found.
I found out i need to configure the new runtime within the [docker daemon.json](https://github.com/kata-containers/documentation/blob/master/install/docker/ubuntu-docker-install.md).
Afterwards i reloaded daemon and docker.
```bash
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
``` 
Then i still was not able to execute `docker run hello-world`.

After some googling i inspected `/etc/docker/daemon.json` and changed the runtime path to
```json
{
  "default-runtime": "kata-runtime",
  "runtimes": {
    "kata-runtime": {
      "path": "/snap/bin/kata-containers.runtime"
    }
  }
}
```
Afterwards i reloaded daemon and docker again.
Finally i was able to run containers and verified it is using kata-containers using `docker inspect <container id>`.

## Conclusion

Even as an experienced user researching and testing took me around two hours, so currently i cannot recommend to install kata via snap. Using the old (still supported?) version 1.12.0 also leaves a sad feeling regarding security.

I assume most developers will use docker, as this is the only and well-known solution to run applications on windows, macos and linux environments. Therefore distribution of kata via snap should get compatible to docker by default.

## Recommendation

* Documentation of snap installation needs improvements
* Ensure docker compatibility by fixing the shim issue of kata 2.0 or downgrade snap channel stable/latest to 1.12 by default
* Simplify installation process via snap to reduce manual interaction or document post installation steps more clearly

**Comment by devimc** [comment]
thanks @dev-rke - I will take a look

**Comment by dev-rke** [comment]
Hi @devimc,

thank you, i like this project! :-)

My experience using apt:
I installed kata on Debian Buster (=Debian 10) a few days ago, too.
It was irritating to use debian_9.x instead of debian_10.x when applying the apt repository - but it seems to work as expected.
Furthermore by default kata 1.12 is installed when using apt, so it works out of the box when using docker.
There were no further issues, so i can recommend to use the apt installation method.
