### ISSUE TITLE
netmon not running in kata 2.x

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#1154]
Is netmon running with kata 2.x? I tried to run a container using `ctr run` and enabling netmon but when I am looking with
`pgrep -a -f /usr/libexec/kata-containers/kata-netmon` it seems that is not running as I am not getting any netmon process.

**Comment by amshinde** [comment]
@GabyCT Was this resolved? IIRC, we need to enable it explicitly in the config.toml.

**Comment by liangxianlong** [comment]
In my case, `kata-netmon` will become `Z`:
```shell
 5179 ?        Ssl    0:00 /usr/bin/containerd
   5335 ?        Sl     0:00 /usr/bin/containerd-shim-kata-v2 -namespace k8s.io -address /run/containerd/containerd.sock -publish-binary /usr/bin/containerd -id 3bd06b439210a2a278dd57b8edfff422045eb1f480aad5184d
   5369 ?        Z      0:00  \_ [kata-netmon] <defunct>
   5370 ?        Sl     0:00  \_ /opt/kata/libexec/kata-qemu/virtiofsd --fd=3 -o source=/run/kata-containers/shared/sandboxes/3bd06b439210a2a278dd57b8edfff422045eb1f480aad5184d8de5e1a7485e8f/shared -o cache=auto
   5385 ?        Sl     0:00      \_ /opt/kata/libexec/kata-qemu/virtiofsd --fd=3 -o source=/run/kata-containers/shared/sandboxes/3bd06b439210a2a278dd57b8edfff422045eb1f480aad5184d8de5e1a7485e8f/shared -o cache=
   5382 ?        Sl     0:01 /opt/kata/bin/qemu-system-x86_64 -name sandbox-3bd06b439210a2a278dd57b8edfff422045eb1f480aad5184d8de5e1a7485e8f -uuid 0990d6de-461b-42a4-9ee2-bff2d9aa192e -machine pc,accel=kvm,kerne
```

**Comment by liangxianlong** [comment]
@amshinde @jodh-intel

**Comment by valliscooper** [comment]
when starting kata-netmon 'by hand' inside the namespace of the container with debug enabled kata-netmon terminates upon adding links or changing routes in the namespace because it tries to run the command **kata-network**  on the runtime which is not present anymore. Could this perhaps be a side-effect i.e. related to issue #722 ?

**Comment by egernst** [comment]
@GabyCT how was this resolved?
