### ISSUE TITLE
monitor results in noisy kata logs

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1155]
**Which feature do you think can be improved?**

We get a lot of (not useful) chatter when enabling debug logs for the runtime.

**How can it be improved?**

Remove some of the noise. In particular, it seems that we are printing each VMM and gRPC check over.. and over... and over... 

It would be helpful to remove some of this steady-state noise. Example:

```
Nov 30 14:09:32 ubuntu kata[2363456]: time="2020-11-30T14:09:32.964427018-08:00" level=debug msg="sending request" name=grpc.CheckRequest pid=2363456 req="&CheckRequest{Service:,XXX_unrecognized:[],}" sandbox=8b3f64b9a76aa84aa7d19b741429a910bcfd5a02ef00259a61a36078ae52e327 source=virtcontainers subsystem=kata_agent
Nov 30 14:09:32 ubuntu containerd[2361560]: time="2020-11-30T14:09:32.964427018-08:00" level=debug msg="sending request" name=grpc.CheckRequest pid=2363456 req="&CheckRequest{Service:,XXX_unrecognized:[],}" sandbox=8b3f64b9a76aa84aa7d19b741429a910bcfd5a02ef00259a61a36078ae52e327 source=virtcontainers subsystem=kata_agent
Nov 30 14:09:33 ubuntu kata[2363456]: time="2020-11-30T14:09:33.962913342-08:00" level=info msg="{\"execute\":\"query-status\"}" pid=2363456 sandbox=8b3f64b9a76aa84aa7d19b741429a910bcfd5a02ef00259a61a36078ae52e327 source=virtcontainers subsystem=qmp
Nov 30 14:09:33 ubuntu containerd[2361560]: time="2020-11-30T14:09:33.962913342-08:00" level=info msg="{\"execute\":\"query-status\"}" pid=2363456 sandbox=8b3f64b9a76aa84aa7d19b741429a910bcfd5a02ef00259a61a36078ae52e327 source=virtcontainers subsystem=qmp
Nov 30 14:09:33 ubuntu kata[2363456]: time="2020-11-30T14:09:33.963943149-08:00" level=info msg="{\"return\": {\"status\": \"running\", \"singlestep\": false, \"running\": true}}" pid=2363456 sandbox=8b3f64b9a76aa84aa7d19b741429a910bcfd5a02ef00259a61a36078ae52e327 source=virtcontainers subsystem=qmp
Nov 30 14:09:33 ubuntu containerd[2361560]: time="2020-11-30T14:09:33.963943149-08:00" level=info msg="{\"return\": {\"status\": \"running\", \"singlestep\": false, \"running\": true}}" pid=2363456 sandbox=8b3f64b9a76aa84aa7d19b741429a910bcfd5a02ef00259a61a36078ae52e327 source=virtcontainers subsystem=qmp
```

As a user, I can  just: 
```sudo journalctl  -fu containerd | grep -v info.*qmp | grep -v CheckRequest```

We shouldn't pollute logs that much though, as it is expensive when these are stored for many pods on many nodes...

**Comment by fidencio** [comment]
I think this is still an issue and I sincerely think we should do some larger effort approaching this one.

I can see several different problems here:
1. We only get kata-containers logs when CRI-O / containerd logs are set to debug:  this doesn't lookright, kata-containers log should be independent from containerd/CRI-O ones;
2. We must have a better understanding of what's logged, and in which level;

This is exactly a work that @marcel-apf started doing by last year, and it's a quite big change and should be looked at carefully.

@egernst, what do you think?

**Comment by egernst** [comment]
Next govmm revenuer will handle: merged in govmm: https://github.com/kata-containers/govmm/pull/166

**Comment by egernst** [comment]
Revendored in already.
