### ISSUE TITLE
cpuset is not set correctly in guest

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1159]
Create a  sandbox with two containers and cpuset is set to `0-1` and `2-3`, but after containers started, the cpusets have all set to `0-4`:

```
# pwd
/sys/fs/cgroup/cpuset/k8s.io
bash-4.2# cat */cpuset.cpus
0-4
0-4
0-4
```

Should't these containers to be set to?

- ``(pause container)
- `0-1`
- `2-3`

Maybe rust agent lost these lines: https://github.com/kata-containers/agent/blob/2b839fef29995b8269317f484fcbb28d704f3431/grpc.go#L219-L221

cc @egernst @lifupan

**Comment by egernst** [comment]
@liubin I think in-guest CPUSets are challenging in general. Are you assuming that the runtime is already translating the CPUsets from host to ones that would be applicable in the guest? For example, host: ctr1 `7-8`, ctr2 `15-17`, and in guest: ctr1 `1-2`, ctr2 `3-5` ?
