### ISSUE TITLE
ipv6: fail to set default route inside the VM, resulting in failed connectivity

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1171]
# Description of problem

On 2.0, ipv6 routes are not appropriately reflected in the guest.

# Expected result

The routes should match what is created in the network namespace of the pod on the host

# Actual result

Default route is missing.

It appears that the request is being sent correctly, but that the agent itself fails to set the default route, but also fails to return an error in this case?

What I see with additional prints added:

```
level=debug msg="sending request" name=grpc.UpdateRoutesRequest pid=3962618 req="&UpdateRoutesRequest{Routes:&Routes{Routes []*Route{&protocols.Route{Dest:,Gateway:2620:149:1021:d1c::2,Device:eth0,Source:,Scope:0,XXX_unrecognized:[],},},XXX_unrecognized:[],},XXX_unrecognized:[],}" sandbox=806c63be9efb95b9a454029a508ad6765548ed83f0ad88be6caef1beee6c013a source=virtcontainers subsystem=kata_agent

vmconsole="[    0.489873] netlink: 'client_handler': attribute type 5 has an invalid length."
vmconsole="{\"msg\":\"not route message!\",\"level\":\"INFO\",\"ts\":\"2020-12-04T21:53:27.256897799+00:00\",\"subsystem\":\"netlink\",\"source\":\"agent\",\"pid\":\"80\",\"name\":\"kata-agent\",\"version\":\"0.1.0\"}"
vmconsole="{\"msg\":\"not route message!\",\"level\":\"INFO\",\"ts\":\"2020-12-04T21:53:27.256958052+00:00\",\"version\":\"0.1.0\",\"subsystem\":\"netlink\",\"source\":\"agent\",\"name\":\"kata-agent\",\"pid\":\"80\"}"
vmconsole="{\"msg\":\"update routes in netlink called!\",\"level\":\"INFO\",\"ts\":\"2020-12-04T21:53:27.256998974+00:00\",\"source\":\"agent\",\"name\":\"kata-agent\",\"pid\":\"80\",\"subsystem\":\"netlink\",\"version\":\"0.1.0\"}"
vmconsole="{\"msg\":\"gateway route handling\",\"level\":\"INFO\",\"ts\":\"2020-12-04T21:53:27.257055266+00:00\",\"name\":\"kata-agent\",\"subsystem\":\"netlink\",\"pid\":\"80\",\"source\":\"agent\",\"version\":\"0.1.0\"}"
vmconsole="{\"msg\":\"route handling: route; gw: 2620:149:1021:d1c::2, device: eth0, dst: , src: \",\"level\":\"INFO\",\"ts\":\"2020-12-04T21:53:27.257096879+00:00\",\"subsystem\":\"netlink\",\"pid\":\"80\",\"version\":\"0.1.0\",\"name\":\"kata-agent\",\"source\":\"agent\"}"
level=debug msg="update routes request completed" pid=3962618 resulting-routes="&Routes{Routes:[]*Route{},XXX_unrecognized:[],}" routes-requested="[&Route{Dest:,Gateway:2620:149:1021:d1c::2,Device:eth0,Source:,Scope:0,XXX_unrecognized:[],}]" sandbox=806c63be9efb95b9a454029a508ad6765548ed83f0ad88be6caef1beee6c013a source=virtcontainers subsystem=kata_agent
```

**Comment by liubin** [comment]
Seems not implemented yet https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/agent/netlink/src/agent_handler.rs#L248-L252

**Comment by egernst** [comment]
When reviewing the netlink crate we implemented, I wondered if we considered pulling in a preexisting crate, or of that would be too much more than we need.

**Comment by yyyeerbo** [comment]
What's the candidates? It look like rtnetlink is a good candidate, but the connection created from function new_connection is future connection, it must be run with tokio. I am not sure about it, correct me if I am wrong. We definitely don't want to import tokio for several route/link apis.
neli and netlink-sys is low level crate. If we use one of them, we almost build wheel from start. Also, there is netlink-packet-route in middle. I read the example for netlink-packet-route, looks like we can save a little effort in prepare request and parse response.

I really hope there is a way to use rtnetlink with tokio. The rtnetlink crate looks appropriate for agent

**Comment by yyyeerbo** [comment]
ping @gnawux @sameo @kata-containers/architecture-committee @egernst 
Any thoughts on this?

**Comment by mxpv** [comment]
`rtnetlink` is a decent crate with lots of features. Given that netlink is a socket based API, use of async runtime is a natural decision.

Bringing in an async runtime onboard is not a bad idea IMO (`Tokio`, `async-std`, `smol`), since it'll help to utilize threads better and hence improve the overall performance. It may be useful not only to manage netlink stuff. There are APIs for [std fs, io, mpsc, etc](https://docs.rs/tokio/0.3.6/tokio/#modules). Also there are many places with manual `thread::spawn` in the Agent that will be easier to manage via tasks / async runtimes. I'd be happy to help with this.

**Comment by yyyeerbo** [comment]
we might use netlink-sys or netlink-packet-generic(maybe) for uevent, if we switch to rtnetlink

**Comment by mxpv** [comment]
I'll open a PR with `rtnetlink` once we get Tokio PR in.

**Comment by yyyeerbo** [comment]
Besides route netlink, we also use generic netlink for uevent in agent

**Comment by mxpv** [comment]
@yyyeerbo I believe @Tim-Zhang got rid of netlink dependency there while migrating to tokio: https://github.com/kata-containers/kata-containers/pull/1210/files#diff-900711fa586a7ff862ef069894f489163b849d403517141025173c6cc5a62e6cR125 (though we can use higher level API with rtnetlink crate).

**Comment by fidencio** [comment]
@bergwolf, @mxpv, @lifupan,
https://github.com/kata-containers/kata-containers/commit/23f3aefa1dda453d3e3b0bd5faa11adcaff32d3c is something we really need backported.   However, AFAIU, this would require a backport of the whole switch to Tokio.

While I'm in favour of doing that for stable-2.0, I'd like to hear your opinion on this.  What do you think?  Shall we backport the whole async work to the stable branch?
