### ISSUE TITLE
Missing end-to-end flow diagram for katacontainers

### ISSUE THREAD

**Issue by zanetworker** [kata-containers/kata-containers#1185]
**Which feature do you think can be improved?**

/area documentation 
/kind enhancment

More illustrations on kata end-to-end flow. 

**How can it be improved?**

Creating a figure for illustrating kata end-to-end flow.

**Comment by egernst** [comment]
@zanetworker -- nice level of detail on the drawings!

**Comment by zanetworker** [comment]
@egernst thanks, did try to cover as much as possible :)

**Comment by zanetworker** [comment]
Also, it was reviewed by others already @fidencio @fidencio @c3d @pmores @ariel-adam to add extra details if missing.
