### ISSUE TITLE
kata-netmon  process will not exit after the container is stopped

### ISSUE THREAD

**Issue by yangfeiyu20102011** [kata-containers/kata-containers#1187]
The way to recur:
1.start a container
2.stop the container
3.kata-netmon process will not exit

I have read the netmon code
```
// Go into the main loop.
	if err := n.handleEvents(); err != nil {
		n.logger().WithError(err).Fatal("handleEvents()")
		os.Exit(1)
	}
->
func (n *netmon) handleEvents() (err error) {
	for {
		select {
		case ev := <-n.linkUpdateCh:
			if err = n.handleLinkEvent(ev); err != nil {
				return err
			}
		case ev := <-n.rtUpdateCh:
			if err = n.handleRouteEvent(ev); err != nil {
				return err
			}
		}
	}
}
```
The function handleEvents ends only if error happens.

**Comment by yangfeiyu20102011** [comment]
@devimc

**Comment by devimc** [comment]
Hi @yangfeiyu20102011 - I couldn't reproduce this, since you raised this in the 2.x repository, I'm running Kata Containers 2.x using `ctr`. Could you provide more details?

btw I'll be on PTO starting tomorrow :beach_umbrella:

**Comment by liubin** [comment]
hi @yangfeiyu20102011 netmon is stopped by killing it in `virtcontainers/netmon.go` .

**Comment by yangfeiyu20102011** [comment]
> Hi @yangfeiyu20102011 - I couldn't reproduce this, since you raised this in the 2.x repository, I'm running Kata Containers 2.x using `ctr`. Could you provide more details?
> 
> btw I'll be on PTO starting tomorrow 🏖️

I used the 1.x Kata Containers, the problem does not exist in 2.x, I will close it.

**Comment by yangfeiyu20102011** [comment]
> hi @yangfeiyu20102011 netmon is stopped by killing it in `virtcontainers/netmon.go` .

Thank you. I will read the code.
