### ISSUE TITLE
how to look kata container guest machine's syslog

### ISSUE THREAD

**Issue by magnate3** [kata-containers/kata-containers#1197]
how to look kata container guest machine's syslog

**Comment by liubin** [comment]
Hi @magnate3 , [here](https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/Developer-Guide.md#capturing-kernel-boot-logs) is the answer

**Comment by magnate3** [comment]
@liubin  could you give a more effective  way to  contact you , I have changed kata rootfs and vmlinuz to support **docker android** in . now  **docker android** successfully run

**Comment by liubin** [comment]
> @liubin could you give a more effective way to contact you , I have changed kata rootfs and vmlinuz to support **docker android** in . now **docker android** successfully run

wechat sakura79
