### ISSUE TITLE
Ship the cargo vendored bits with the released tarball

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1203]
Distros, such as Fedora, do not have access to the internet while building their packages.  Because of this, would be really helpful if a `cargo vendor` could be run as part of the release process, and .cargo/config could be changed accordingly.

This has been discussed in the architecture committee's meeting already, with a positive agreement on doing it, but no issue was opened so far (sorry, my bad!).

Let's have this opened so distros can point to this issue, if needed.

**Comment by etrunko** [comment]
Currently running cargo vendor on the source code and adding it as a patch for Fedora package.

**Comment by fidencio** [comment]
This one is still an issue for those who'll be packaging 2.0 and their infra doesn't provide / allow internet connectivity during the builds.

I sincerely think we should do a full vendor of the packages, as we can't do that as part of a "make dist", because the tarballs are automatically generated from the GitHub tags.

@lifupan, @liubin, @bergwolf, would you be okay with the full cargo vendor?

**Comment by lifupan** [comment]
Hi @fidencio 

I think it's reasonable to afford a full cargo vendor in the release tarball.

**Comment by fidencio** [comment]
@lifupan, ack, then I'll provide the patch, thanks @lifupan!

**Comment by etrunko** [comment]
This could help preventing issues like #2111 from happening
