### ISSUE TITLE
Proposal: Consider switching to async runtime in Rust Agent (Tokio)

### ISSUE THREAD

**Issue by mxpv** [kata-containers/kata-containers#1209]
This comes out from the discussion [here](https://github.com/kata-containers/kata-containers/issues/1171#issuecomment-748390552).

The proposal is to adopt Tokio in the Rust Agent.

Async/await stuff is already in stable Rust and allows us to write async code (see [Why Async?](https://rust-lang.github.io/async-book/01_getting_started/02_why_async.html) and [The State of Asynchronous Rust](https://rust-lang.github.io/async-book/01_getting_started/03_state_of_async_rust.html)).

Async runtimes is a natural fit for applications that process incoming requests / spawn threads / work with sockets, etc. 
Benefits are:
- Agent will utilize threads more efficiently which will lead to better runtime performance.
- Open a gate for `rtnetlink` crate (which relies on Tokio)

I've opened a PR (https://github.com/kata-containers/kata-containers/pull/1210) with minimal changes needed to run the Agent in async mode with Tokio. It doesn't utilize all async features, but runs TTRPC server in async mode (ttrpc crate already supports Tokio via feature toggle)

**Comment by Tim-Zhang** [comment]
Hi, @mxpv 
I have been working on this months ago and I am almost done. I will propose an available PR in a couple of days.

**Comment by mxpv** [comment]
@Tim-Zhang would it make sense to consolidate changes with #1210 ?

**Comment by Tim-Zhang** [comment]
> @Tim-Zhang would it make sense to consolidate changes with #1210 ?

OK, I will try.

**Comment by dgibson** [comment]
I don't really know async or tokio well enough to review thoroughly.  I will say I think the second patch needs a more detailed commit message, especially to clarify what it's doing differently from the first patch.

**Comment by mxpv** [comment]
@dgibson #1210 has 5 commits. Which one needs more clarity? 2dc303c ?

**Comment by dgibson** [comment]
The second of five, as noted.  It currently has no content in the commit message at all.
