### ISSUE TITLE
is katacontainer  support sr-iov?

### ISSUE THREAD

**Issue by wanghonglei5181** [kata-containers/kata-containers#1223]
in some blog,i found sr-iov 
is katacontainer  support sr-iov default?

**Comment by fidencio** [comment]
kata-containers does support SR-IOV.  @dgibson, and @bpradipt  may be able to give you more info on what's the current state on 2.x branch.

**Comment by wanghonglei5181** [comment]
i found the doc about this issue!
https://github.com/kata-containers/kata-containers/blob/2.0.0/docs/use-cases/using-SRIOV-and-kata.md

thanks !!!

**Comment by zhonglin6666** [comment]
Does kata-container support SRIOV using `sriov-network-operator`, https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin.
I only find docker command line docs.
