### ISSUE TITLE
add github actions for stable-1.12

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#1248]

**Comment by fidencio** [comment]
Based on the [following comment](https://github.com/kata-containers/kata-containers/pull/1249#issuecomment-763861371) from @GabyCT, I'm closing this one:
```
(...) it seems that for stable-1.12 we will not have the github actions for kata containers. I will close this PR.
```

@GabyCT, please, feel free to reopen the issue in case I misunderstood something!
