### ISSUE TITLE
Update to Tokio 1.0

### ISSUE THREAD

**Issue by mxpv** [kata-containers/kata-containers#1257]
After getting in https://github.com/kata-containers/kata-containers/pull/1210 we need to migrate to [Tokio 1.0](https://tokio.rs/blog/2020-12-tokio-1-0) (https://github.com/kata-containers/kata-containers/pull/1210#discussion_r554577078).

Agent dependencies that use Tokio must be updated first:
- [x] tokio-vsock: https://github.com/fsyncd/tokio-vsock/pull/5
- [x] ttrpc: https://github.com/containerd/ttrpc-rust/pull/79
- [x] netlink https://github.com/little-dude/netlink/pull/134 https://github.com/little-dude/netlink/issues/142
- [ ] Agent https://github.com/kata-containers/kata-containers/pull/1305

**Comment by Tim-Zhang** [comment]
@mxpv thank you
