### ISSUE TITLE
how to run kata2.0 with cri-o + k8s + kata-qemu in centos  

### ISSUE THREAD

**Issue by xiaofeng0303** [kata-containers/kata-containers#1278]
deploy following the docs but failed many times.  Who can give me a detailed document, treat me as a novice user. ths

**Comment by fidencio** [comment]
What failed according to the documentation? Can you be more specific on the issue you're facing? This will help us to provide better answers for the problem.

**Comment by xiaofeng0303** [comment]
> What failed according to the documentation? Can you be more specific on the issue you're facing? This will help us to provide better answers for the problem.

error msg:
`Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: Invalid command "create"`

**Comment by xiaofeng0303** [comment]
crio.conf:

`
[crio]
log_dir = "/var/log/crio/pods"
version_file = "/var/run/crio/version"
version_file_persist = "/var/lib/crio/version"
[crio.api]
listen = "/var/run/crio/crio.sock"
stream_address = "127.0.0.1"
stream_port = "0"
stream_enable_tls = false
stream_tls_cert = ""
stream_tls_key = ""
stream_tls_ca = ""
grpc_max_send_msg_size = 16777216
grpc_max_recv_msg_size = 16777216
[crio.runtime]
default_runtime = "kata-qemu"
no_pivot = false
decryption_keys_path = "/etc/crio/keys/"
conmon = "/usr/libexec/crio/conmon"
conmon_cgroup = "system.slice"
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]
default_env = [
]
selinux = true
seccomp_profile = "/etc/crio/profile.json"
apparmor_profile = "crio-default-1.17.5"
cgroup_manager = "systemd"
default_capabilities = [
	"CHOWN",
	"DAC_OVERRIDE",
	"FSETID",
	"FOWNER",
	"NET_RAW",
	"SETGID",
	"SETUID",
	"SETPCAP",
	"NET_BIND_SERVICE",
	"SYS_CHROOT",
	"KILL",
]
default_sysctls = [
]
additional_devices = [
]
hooks_dir = [
	"/usr/share/containers/oci/hooks.d",
]
default_mounts = [
	"/usr/share/rhel/secrets:/run/secrets",
]
pids_limit = 1024
log_size_max = -1
log_to_journald = false
container_exits_dir = "/var/run/crio/exits"
container_attach_socket_dir = "/var/run/crio"
bind_mount_prefix = ""
read_only = false
log_level = "info"
log_filter = ""
uid_mappings = ""
gid_mappings = ""
ctr_stop_timeout = 0
manage_ns_lifecycle = false
namespaces_dir = "/var/run"
pinns_path = ""
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"

[crio.runtime.runtimes.kata]
runtime_path = "/opt/kata/bin/containerd-shim-kata-v2"
runtime_root = "/run/vc"
runtime_type = "vm"
[crio.runtime.runtimes.kata-qemu]
runtime_path = "/opt/kata/bin/kata-runtime"
runtime_type = "oci"
privileged_without_host_devices = true

[crio.runtime.runtimes.kata-clh]
runtime_path = "/opt/kata/bin/kata-clh"
privileged_without_host_devices = true

[crio.image]
default_transport = "docker://"
global_auth_file = ""
pause_image = "registry.aliyuncs.com/google_containers/pause:3.2"
pause_image_auth_file = ""
pause_command = "/pause"
signature_policy = ""
image_volumes = "mkdir"
[crio.network]
network_dir = "/etc/cni/net.d/"
plugin_dirs = [
	"/usr/libexec/cni/",
]
[crio.metrics]
enable_metrics = false
metrics_port = 9090
`

**Comment by xiaofeng0303** [comment]
This project is too inactive i ware close my issues

**Comment by fidencio** [comment]
@xiaofeng0303, you can always connect to our Slack channel if you need a faster response, but you have to understand that we're working on several other things while also replying to issues on github.

Anyways, I see the error you're facing, would you mind updating more info?
I'm interested to know which kata you're using, are you using "kata" or "kata-qemu"? can you share the kata configuration file?

Whenever you open an issue there's a guide on the minimum information needed so it can speed up the reviewing process, please, follow that next time, it may help with the agility of the process.
