### ISSUE TITLE
missing kata-containers download for Ubuntu 16.04-LTS

### ISSUE THREAD

**Issue by jackfrancis** [kata-containers/kata-containers#128]
Hi kata folks!

# Description of problem

It seems that the Ubuntu 16.04-LTS download artifacts are no longer available for x86_64 via the canonical source URI documented here:

https://github.com/kata-containers/documentation/tree/master/install#supported-distributions

See:

http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.7/

(Note the missing `xUbuntu_16.04/` directory)

# Expected result

We expect the following to be a valid URL:

- `http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.7/xUbuntu_16.04/Release.key`

# Actual result

The above URL (and any other artifacts under `x86_64:/stable-1.7/xUbuntu_16.04/`) return 404.

I come by way of `aks-engine`, a Kubernetes bootstrap tool for k8s + azure. We ship a cluster configuration w/ kata-containers 1.7 and folks who use this configuration + 16.04 are no longer able to build/scale clusters.

Thanks!

**Comment by amshinde** [comment]
@jackfrancis We have 16.04 packages for our latest stable 1.10 release, need to see why those were missing for stable 1.7. cc @jcvenegas Can you check.
@jackfrancis I would also suggest upgrading to latest stable 1.10 Kata release.

**Comment by ariel-adam** [comment]
1.11 is available so we are closing this issue.
