### ISSUE TITLE
kernel: Upgrade to kernel 5.10 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/kata-containers#1288]
**Which feature do you think can be improved?**

Kernel support,  The kata project follows the latest LTS kernel release of the current year. This reduce the
maintenance  overhead and stability over the kata releases.

Now that 5.10 will be a LTS kernel the project should move to it.

Some features to track for this are 

DAX support for virtiofs

<Insert any other feature we should track here >

**How can it be improved?**

Virtiofs DAX support 

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by fidencio** [comment]
I got to this issue while going through the open issues with the "needs-review" label.  As this is a valid enhancement request, I'm removing the "needs-review" label, and I'm adding the "area/packaging" one.

@jcvenegas, feel free to adjust the labels accordingly, if you notice that something is wrong.
