### ISSUE TITLE
clh: Use vanilla kernel

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/kata-containers#1316]
**Which feature do you think can be improved?**

Qemu uses vanilla kernel for virtiofs, cloud-hypervisor should do the same

**Comment by fidencio** [comment]
I got to this issue while going through the open issues with the "needs-review" label.  As this is a valid enhancement request, I'm removing the "needs-review" label, and I'm adding the "area/cloud-hypervisor" one.

@jcvenegas  , feel free to adjust the labels accordingly, if you notice that something is wrong.

**Comment by jcvenegas** [comment]
This is already fixed
