### ISSUE TITLE
Documentation: Kubernetes How-To is outdated

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#1325]
Looking at https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md, I noticed that the page is practically a copy-paste of the 1.x documentation from https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md.

It contains a number of outdated pieces of information, and does not refer to a modern way of doing things. For example, there is no mention of `runtimeClass`, but there is still a reference to the `io.kubernetes.cri.untrusted-workload` annotation.

**Comment by liubin** [comment]
Hi @c3d , I'll take this one, if you haven't began.

**Comment by fidencio** [comment]
I got to this issue while going through the open issues with the "needs-review" label.  As this is a valid issue, I'm removing the "needs-review" label, and I'm adding the "area/documentation" one.

@c3d, feel free to adjust the labels accordingly, if you notice that something is wrong. Also, last but not least, would you mind reviewing #1354 to ensure everything you raised is addressed there?
