### ISSUE TITLE
qemu error,when i use sriov

### ISSUE THREAD

**Issue by wanghonglei5181** [kata-containers/kata-containers#1326]
what happened?

[root@d0028 docker]#  docker run --runtime="kata-runtime"    --net=vfnet --cap-add SYS_ADMIN --ip=10.31.240.2 -it alpine /bin/sh
docker: Error response from daemon: OCI runtime create failed: failed to launch qemu: exit status 1, error messages from qemu log: qemu-kvm: error: failed to set MSR 0x48e to 0xfff9fffe04006172
qemu-kvm: /builddir/build/BUILD/qemu-4.2.0/target/i386/kvm.c:2695: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.: unknown.
ERRO[0004] error waiting for container: context canceled

**Comment by devimc** [comment]
you are running on a VM (hyperv?) that doesn't support KVM very well, you have two options:
1. update your guest kernel to something >= 5.3
2. Disable `vmx-rdseed-exit` - see https://github.com/kata-containers/tests/blob/ac8a2c8c5d09c7527522a6cfe07f467c93e7aabd/.ci/install_runtime.sh#L98

**Comment by wanghonglei5181** [comment]
@devimc   thanks!

running on a  dell machine, not vm 

i will have a try!

**Comment by fidencio** [comment]
@wanghonglei5181, using a new enough version of QEMU also will help, as that bug was fixed as part of 5.0, IIRC.

**Comment by fidencio** [comment]
@wanghonglei5181, I'll close this one for now. **Please**, feel free to re-open it in case you need any further assistance.  Okay?
