### ISSUE TITLE
Improvements for console access

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1329]
**Which feature do you think can be improved?**

We are still inconsistent on how console setup is carried out among the different VMM solutions. Since vsock is available on each VMM now, I think we could deprecate /dev/console. This'll make the setup consistent between each.

Today, enabling console debug doesn't work on QEMU, since we don't expect a VPORT to be specified.

Similarly, kata-runtime exec <pod id> is a sweet setup, and will allow us to avoid needing vsock support in socat. The downside currently is that it relies on kata-monitor to determine the port and the socket location. I think we should instead augment kata-exec handling to just find the socket path, and search for either console or clh.sock or fcHybrid.sock within the /run/vc/vm/<sandboxid>/ path.

This'll make it easier to quickly debug VMs, and avoid dependency on another long running process on the host.

**Comment by liubin** [comment]
Yes, we can and should not depend on kata-monitor to get the agent address.
Now kata-exec will call kata-monitor, and then kata-monitor call kata-shim to get the agent address.
For vsock like `vsock://31513974:1024` we can't compose it without querying kata-shim.

**Comment by fidencio** [comment]
I got to this issue while going through the open issues with the "needs-review" label.  As this is a valid enhancement request, I'm removing the "needs-review" label, and I'm adding the "area/runtime", "area/debug" ones.

@egernst, feel free to adjust the labels accordingly, if you notice that something is wrong.
