### ISSUE TITLE
kata-deploy doesn't update containerd config.toml if deployed through Docker affecting ctr usage

### ISSUE THREAD

**Issue by eadamsintel** [kata-containers/kata-containers#1350]
This occurred on Ubuntu but likely affects other OS's. If you want to use the `ctr` interface with containerd, then the `/etc/containerd/config.toml` needs to include all of the additional kata runtimes when it is installed through `kata-deploy`. In addition, containerd expects a shim v2 binary in `/usr/local/bin` for each runtime.  When `kata-deploy` is installed through a Kubernetes daemonset it sets these values but does not when installed through the `docker run` command. It would be very helpful and useful if the `kata-deploy.sh` script also configured containerd to work with the `ctr` tool. 

**config.toml** 
```
[plugins.cri.containerd.runtimes.kata]
  runtime_type = "io.containerd.kata.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration.toml"
[plugins.cri.containerd.runtimes.kata-fc]
  runtime_type = "io.containerd.kata-fc.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-fc.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-fc.toml"
[plugins.cri.containerd.runtimes.kata-qemu]
  runtime_type = "io.containerd.kata-qemu.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-qemu.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-qemu.toml"
[plugins.cri.containerd.runtimes.kata-qemu-virtiofs]
  runtime_type = "io.containerd.kata-qemu-virtiofs.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-qemu-virtiofs.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-qemu-virtiofs.toml"
[plugins.cri.containerd.runtimes.kata-clh]
  runtime_type = "io.containerd.kata-clh.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-clh.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-clh.toml"
```

**Example containerd script to redirect to the binary**
```
$ cat /usr/local/bin/containerd-shim-kata-qemu-v2
#!/bin/bash
KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration-qemu.toml /opt/kata/bin/containerd-shim-kata-v2 $@
```

**Comment by fidencio** [comment]
@eadamsintel, thanks for the issue reported.  This is a valid issue, thus I'm removing the "needs-review" label.

I've also added some labels to the issue, such as "area/packaging", "area/containerd", and I've swapped it to an "enchancement" request rather than a "bug" report.

Please, if you feel like I have missed something on applying the correct labels, feel free to change them accordingly.

**Comment by fidencio** [comment]
@egernst, I guess I can address this one together with removing the `kata-deploy-docker` scripts.  What do you think?

**Comment by egernst** [comment]
@eadamsintel -- Will not fix...

   I *think* we are dropping the docker installation option for kata-deploy for 2.x, and if you're doing just a docker install, I think it doesn't make sense to touch a containerd or crio configuration.
