### ISSUE TITLE
runtime: some runtime trace spans have incorrect parent/child relationship

### ISSUE THREAD

**Issue by cmaf** [kata-containers/kata-containers#1355]
Related to issue #1347 

Some runtime trace spans have incorrect parent/child ordering which in some cases can be fixed by returning the context when creating a span:
```
span, ctx := opentracing.StartSpanFromContext(ctx, name)
```

Another, `bindMount`, appears parentless in the output because in [kata_agent.go](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/kata_agent.go#L439) the background context is being passed to `bindMount()`. It can be switched to `k.ctx` although then this particular span does not show up in the trace output (either parentless or grouped under `New()`).

**Comment by liubin** [comment]
Hi @cmaf , I'm doing #1352 now, can you start this base on that PR or after that PR has been merged?

**Comment by cmaf** [comment]
@liubin yes it will be after that PR. There is also https://github.com/kata-containers/runtime/pull/3100 which is waiting for another approval and needs to be ported to 2.x/main.

**Comment by fidencio** [comment]
@cmaf, @liubin, I've swapped the "need-reviews" label for the "area/runtime" and "area/tracing" ones.  Please, feel free to correct the labels as you do understand way better of what has to be done for this issue.
