### ISSUE TITLE
docs: Update QAT instructions to work with Kata 2.0 repos

### ISSUE THREAD

**Issue by eadamsintel** [kata-containers/kata-containers#1362]
I went through and rewrote significant parts of the QAT guide to work with the new Kata 2.0 repos, to show how to verify with ctr/containerd, and also gave examples of how to use and verify with kubernetes.

**Comment by fidencio** [comment]
@eadamsintel, I've swapped the "needs-review" by the "area/documentation" label.  Please, feel free to change it to a more accurate one, in case it's needed.
