### ISSUE TITLE
GitHub labels are not showing all the issues containing it

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1374]
# Description of problem

When clicking on an issue that has the `needs-review` label, as this one, we're presented to the view of all the open issues containing this label.  However, that doesn't actually contain all the issues opened, instead the view contains only a fraction of the opened issues.

# Expected result

Clicking on a label would lead us to all the issues opened containing that label.

# Actual result

Only a fraction of the issues is displayed.

# Further information

This is most likely something we should report to GitHub, rather than investing much time on solve it ourselves.  However, I'm opening an issue here as it directly affects the backlog review meetings.

/cc @ariel-adam, @cpmeadors, @jodh-intel

**Comment by fidencio** [comment]
@jodh-intel nailed it, noticing that we have different results accoding to whether we use `is:issue` or `type:issue`, as show in the pictures below.

* "is:issue":
![Captura de pantalla de 2021-02-08 14-01-25](https://user-images.githubusercontent.com/112762/107223430-7c2bc480-6a16-11eb-8df3-41b352212af5.png)

* "type:issue":
![Captura de pantalla de 2021-02-08 14-01-38](https://user-images.githubusercontent.com/112762/107223479-88178680-6a16-11eb-9e54-fbcce8ef004e.png)

**Comment by fidencio** [comment]
I created a GitHub support ticket linking this one there, let's wait and see what happens.

**Comment by byron-marohn** [comment]
I believe this has been resolved - it's been two years and these queries now appear to return the same, complete, results. 

![image](https://user-images.githubusercontent.com/2992380/234713010-980131a0-8bdb-4461-96f9-05fd16508c82.png)
![image](https://user-images.githubusercontent.com/2992380/234713084-6ef4ae7e-b2c1-4009-a651-e25eee9c8b6a.png)
