### ISSUE TITLE
docs: "configure-hypervisor.sh qemu" is not correct

### ISSUE THREAD

**Issue by ManaSugi** [kata-containers/kata-containers#1379]
# Description of problem

```kata.cfg``` is created by the following command  according to the doc.
https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#build-a-custom-qemu

```
$ ${GOPATH}/src/github.com/kata-containers/kata-containers/tools/packaging/scripts/configure-hypervisor.sh qemu > kata.cfg
```

In this configuration,  create virtiofsd under /usr/libexec/qemu.
But, the runtime assumes that virtiofsd is under /usr/libexec/kata-qemu
Therefore, ctr fails because it can not  find virtiofs daemon.

So, we need to change `qemu` to `kata-qemu` in the doc like below.

```
$ ${GOPATH}/src/github.com/kata-containers/kata-containers/tools/packaging/scripts/configure-hypervisor.sh kata-qemu > kata.cfg
```

We can run kata-container properly. 

# Expected result

Kata-container works without any problems.

# Actual result

```
$sudo ctr run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello sh
ctr: virtiofs daemon /usr/libexec/kata-qemu/virtiofsd returned with error: fork/exec /usr/libexec/kata-qemu/virtiofsd: no such file or directory: unknown
```

**Comment by fidencio** [comment]
@ManaSugi, thanks for the bug report.  As this is a valid bug, I've removed the "needs-review" label and added the other ones accordingly.

We have basically two solutions for this:
1. Change the docs, as you mentioned;
2. Change the scripts, to install virtiofsd under kata-qemu

May I ask if you'd have the interest to work on fixing this issue?

**Comment by ManaSugi** [comment]
@fidencio, thank you for the review.

Yes, I'd have the interest to fix this issue.

I think it's better to change `qemu` to `kata-qemu` in the docs to avoid the name conflict  by other software.
I want to set the unique name: `kata-qemu` because `qemu` is general name.

Could you tell me what you think about it?

**Comment by fidencio** [comment]
@ManaSugi, I agree! :-)

Please, submit a pull-request changing that bit.  Also, please, take a look at our contributing guide: https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md

One you open the PR, please, feel free to /cc me there.

**Comment by fidencio** [comment]
Also, I've assigned this issue to you.  Please, don't feel pressured by that, that's just a formality as you will submit the pull request.
Thanks for opening the issue, thanks for contributing to the project!
