### ISSUE TITLE
oci: Seccomp configuration should be updated for the future support

### ISSUE THREAD

**Issue by ManaSugi** [kata-containers/kata-containers#1391]
**Which feature do you think can be improved?**

Seccomp configuration should be updated to prepare for the future seccomp support based on the latest OCI specification.

applicable parts:
https://github.com/kata-containers/kata-containers/blob/main/src/agent/oci/src/lib.rs#L707

**How can it be improved?**

Update the oci library about seccomp.
https://github.com/kata-containers/kata-containers/blob/main/src/agent/oci/src/lib.rs#L707

We add `flags` which is used with seccomp(2) in `LinuxSeccomp` struct.
In addition, we add `errnoRet` which is errno return code in `LinuxSyscall` struct.
Also, add some new seccomp actions and an architecture.

**Additional Information**

The latest OCI specification about seccomp: 
https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp

**Comment by fidencio** [comment]
@ManaSugi, I see you already started working on this!
I'll assign this issue to you, based on that.

Thanks for raising the issue and I'm looking forward to seeing the PR.
