### ISSUE TITLE
Disable trace for healthcheck

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1395]
With trace enabled, there will be too many spans for health check requests.

![image](https://user-images.githubusercontent.com/1212008/107596984-57bd2b80-6c54-11eb-87f2-d8bec4641a8a.png)

Should we delete spans from health checks or stats ?

**Comment by cmaf** [comment]
@liubin what command are you running to get this output?

**Comment by liubin** [comment]
@cmaf Nothing special, a normal pod running for 3d20h, the health check will run at a 1-second interval.

**Comment by cmaf** [comment]
@liubin I verified it. I think we should remove the spans or create a config option for reduced span output. Related to https://github.com/kata-containers/kata-containers/issues/1504

**Comment by liubin** [comment]
Hi @cmaf  I'm not working on it yet.
