### ISSUE TITLE
runtime from main branch fails to read shimv2 configPath option

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1411]
Building latest on main, the configPath is not being honored for shimv2.

If you specify configpath as part of your containerd configuration, it will pass the config path as an option to the v2 as part of the create request.

On main branch e830192fcab199dac9c7c2166182bd28adb797ce, I see this fail:
```
[eernst@localhost runtime]$ sudo ctr run --rm --runtime-config-path /etc/kata-containers/configuration-qemu.toml --runtime io.containerd.kata-qemu.v2  -t docker.io/library/busybox:latest test3 sh
ctr: io.containerd.kata.v2: Cannot find usable config file (config file "/etc/kata-containers/configuration.toml" unresolvable: file /etc/kata-containers/configuration.toml does not exist, config file "/usr/share/defaults/kata-cont
ainers/configuration.toml" unresolvable: file /usr/share/defaults/kata-containers/configuration.toml does not exist)
```

Stable 2.0 works as expected:

```
[eernst@localhost runtime]$ sudo ctr run --rm --runtime-config-path /etc/kata-containers/configuration-qemu.toml --runtime io.containerd.kata-qemu.v2  -t docker.io/library/busybox:latest test3 sh
/ #
```

You'll see same behavior if you're calling from crictl and leveraging the containerd config toml.

**Comment by egernst** [comment]
Looks like this is introduced here in https://github.com/kata-containers/kata-containers/pull/904.

In particular, on New, we load the Kata configuration, but we do it from the default path, which doesn't necessarily exist. We may need to push initialization to a later stage if we cannot rely on the configuration coming from the CRI side of the shimv2 api.

/cc @cmaf

**Comment by cmaf** [comment]
@egernst the simplest solution is to move tracer initialization to `Create()` after the configuration is loaded. This will fix the containerd config problem with the side effect of losing some spans from `New()` and `Start()` which we can quantify and address after span ordering is fixed in https://github.com/kata-containers/kata-containers/pull/1389.
