### ISSUE TITLE
kata-deploy: Update runtimeClass definitions

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1425]
We need to update the runtimeClass definitions to match what we currently ship and, preferrably, have them in `k8s` directory (rather than a `k8s-$version`), such as:
```
fidencio@dahmer ~/go/src/github.com/kata-containers/kata-containers/tools/packaging/kata-deploy $ ls k8s-1.1*
k8s-1.13:
kata-clh-runtimeClass.yaml  kata-fc-runtimeClass.yaml  kata-qemu-runtimeClass.yaml  kata-qemu-virtiofs-runtimeClass.yaml  runtimeclass-crd.yaml

k8s-1.14:
kata-clh-runtimeClass.yaml  kata-fc-runtimeClass.yaml  kata-qemu-runtimeClass.yaml  kata-qemu-virtiofs-runtimeClass.yaml
```

Also, the fact we have directories mentioining with super old versions of k8s gives the feel that the project won't work with newer versions, which is totally **not** the case.

**Comment by egernst** [comment]
IIRC, it dealt with changes regarding the Runtime Class definitions which changed between 1.13 and 1.14. Further, I think we may still have one more round of this for changes in the 1.16 time frame.

I'd be delighted to see us remove pre 1.16. With that in place, I think we can do with a single set of sample yaml for RuntimeClass object.
