### ISSUE TITLE
Do we need src/runtime/virtcontainers/documentation anymore?

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1439]
I noticed that there is an [API document](https://github.com/kata-containers/kata-containers/tree/main/src/runtime/virtcontainers/documentation) for `virtcontainers` package.

Do we need to keep it update or delete it completely?

Since it will not be an independent package and used by an external package, I recommend deleting it.

/cc @bergwolf @jodh-intel @egernst

**Comment by lifupan** [comment]
Hi @liubin 

By now I have just support the shimv2 api with a warper on virtcontainers, but maybe there's some other interface/api to be supported in the future, thus I think it's better to keep it and update it timely.

**Comment by liubin** [comment]
Ok.
