### ISSUE TITLE
It's better to return the hypervisor's pid to cri as the container's pid

### ISSUE THREAD

**Issue by lifupan** [kata-containers/kata-containers#1451]
# Description of problem

Since the kata's hypervisor process is in the network namespace,
which is close to container's process, and some host metrics
such as cadvisor can use this pid to access the network namespace
to get some network metrics.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with an explanation of what actually happened)

# Further information

(replace this text with any extra information you think might be useful)

**Comment by fidencio** [comment]
@lifupan, thanks for raising this and the PR!
