### ISSUE TITLE
How to install kata 2.x ?

### ISSUE THREAD

**Issue by LiangZhou9527** [kata-containers/kata-containers#1453]
Hi there, 

I want to install Kata 2.x on my Ubuntu but finally I still got the kata-runtime 1.x .
Here's my steps to install the Kata 2.x, which is totally followed the kata 2.x guide here:
https://github.com/kata-containers/kata-containers/blob/main/docs/install/ubuntu-installation-guide.md

$ sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
$ curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
$ sudo -E apt-get update
$ sudo -E apt-get -y install kata-runtime kata-proxy kata-shim

Then I got:

root@ubuntu:/home/root# kata-runtime -v
kata-runtime  : 1.13.0-alpha0
   commit   : <<unknown>>
   OCI specs: 1.0.1-dev

Is there any correct doc I should refer to install 2.x ?

Thank you in advance.

-Liang

**Comment by LiangZhou9527** [comment]
I also tried the centos guide but still got 1.x finally...
This is the guide I refer to : https://github.com/kata-containers/kata-containers/blob/main/docs/install/centos-installation-guide.md

**Comment by htlabc** [comment]
you can install kata 2.x container accross  kata manager or snap

**Comment by LiangZhou9527** [comment]
> you can install kata 2.x container accross kata manager or snap

Hi htlabc,

Thanks for your comments.

I tried to follow the guide https://github.com/kata-containers/kata-containers/blob/main/docs/install/snap-installation-guide.md to install 2.x using snap on CentOS8, but after installation when I run /snap/kata-containers/current/usr/bin/kata-runtime  I just got few commands which is much less than the number of commands in Kata 1.x. Even it does not support "run" or "create" commands...


COMMANDS:
     version     display version details
     kata-check  tests if system can run Kata Containers
     kata-env    display settings. Default to TOML
     exec        Enter into guest by debug console
     factory     manage vm factory
     help, h     Shows a list of commands or help for one command



Anything I missed?

Thanks.

-Liang

**Comment by liubin** [comment]
Hi @LiangZhou9527 Kata 2.0 doesn't support `run` or `create` sub-commands anymore. The best way of using Kata Containers 2.0 is to use CRI compatible tools such as `crictl`/`ctr` or run Pods in Kubernetes.

**Comment by LiangZhou9527** [comment]
> Hi @LiangZhou9527 Kata 2.0 doesn't support `run` or `create` sub-commands anymore. The best way of using Kata Containers 2.0 is to use CRI compatible tools such as `crictl`/`ctr` or run Pods in Kubernetes.

Thank you @liubin for your reply.

I'm new to container tech so actually I have lots of things which made me confused :-(
Would you mind to answer some questions for me if you got time? 

Could you please elaborate more about why cut off those commands from Kata2.0 ?
My understanding is that the OCI compatible runtime should support those commands according to the OCI spec but I'm not sure if those commands should be exposed by CLI way or by inline way . 
I found runc actually supports those commands by CLI way, so does Kata 1.x.  
So I got a bit confused why Kata 2.0 not support it? Isn't better to keep them as what has been done by Kata 1.0, in order to facilitate the user ?

Thank you in advance.

**Comment by liubin** [comment]
Many considerations, the main one is that [Docker will support shim v2 as contaienrd](https://github.com/kata-containers/kata-containers/issues/190).
And there is an [issue](https://github.com/kata-containers/kata-containers/issues/191) tracking it

**Comment by htlabc** [comment]
> > Hi @LiangZhou9527 Kata 2.0 doesn't support `run` or `create` sub-commands anymore. The best way of using Kata Containers 2.0 is to use CRI compatible tools such as `crictl`/`ctr` or run Pods in Kubernetes.
> 
> Thank you @liubin for your reply.
> 
> I'm new to container tech so actually I have lots of things which made me confused :-(
> Would you mind to answer some questions for me if you got time?
> 
> Could you please elaborate more about why cut off those commands from Kata2.0 ?
> My understanding is that the OCI compatible runtime should support those commands according to the OCI spec but I'm not sure if those commands should be exposed by CLI way or by inline way .
> I found runc actually supports those commands by CLI way, so does Kata 1.x.
> So I got a bit confused why Kata 2.0 not support it? Isn't better to keep them as what has been done by Kata 1.0, in order to facilitate the user ?
> 
> Thank you in advance.

I have successfully installed Kata 2.x, please contact me if you have any questions

**Comment by LiangZhou9527** [comment]
> Many considerations, the main one is that [Docker will support shim v2 as contaienrd](https://github.com/kata-containers/kata-containers/issues/190).
> And there is an [issue](https://github.com/kata-containers/kata-containers/issues/191) tracking it

Thank you @liubin for your explanation, it helps .

**Comment by LiangZhou9527** [comment]
> > > Hi @LiangZhou9527 Kata 2.0 doesn't support `run` or `create` sub-commands anymore. The best way of using Kata Containers 2.0 is to use CRI compatible tools such as `crictl`/`ctr` or run Pods in Kubernetes.
> > 
> > 
> > Thank you @liubin for your reply.
> > I'm new to container tech so actually I have lots of things which made me confused :-(
> > Would you mind to answer some questions for me if you got time?
> > Could you please elaborate more about why cut off those commands from Kata2.0 ?
> > My understanding is that the OCI compatible runtime should support those commands according to the OCI spec but I'm not sure if those commands should be exposed by CLI way or by inline way .
> > I found runc actually supports those commands by CLI way, so does Kata 1.x.
> > So I got a bit confused why Kata 2.0 not support it? Isn't better to keep them as what has been done by Kata 1.0, in order to facilitate the user ?
> > Thank you in advance.
> 
> I have successfully installed Kata 2.x, please contact me if you have any questions

Hi htlabc, 

Thank you very much for your help.

Following the snap command as you suggested, I succesfully installed Kata2.x on my CentsOS8 and now I can use ctr tool to launch a busybox container. 
And I also tried to build "containerd-shim-kata-v2" from source code and it works with containerd.

Thank you again for your help.

-Liang

**Comment by LiangZhou9527** [comment]
> Hi @LiangZhou9527 Kata 2.0 doesn't support `run` or `create` sub-commands anymore. The best way of using Kata Containers 2.0 is to use CRI compatible tools such as `crictl`/`ctr` or run Pods in Kubernetes.

Hi @liubin,

I still got some confusion about why Docker cannot support Kata shimv2.

My understanding of Docker is as the call chain below: 
docker -> dockerd --> containerd -> containerd-shim-kata-v2 

If my understanding is correct, dockerd just be interactive with containerd, why docker only supports shim-kata-v1 but not shim-kata-v2?

Seems that it's containerd's responsibiliy to take care of v1 or v2, right ?

Thanks.

-Liang

**Comment by liubin** [comment]
Hi @LiangZhou9527 , Docker is using a hardcoded [io.containerd.runc.v2](https://github.com/moby/moby/blob/03a07af6def280d77dab18782fca3fceb6784743/daemon/runtime_unix.go#L147).

**Comment by cmaf** [comment]
@LiangZhou9527 since this was resolved I'll be closing the issue. If you have additional questions please reopen or create a new issue.
