### ISSUE TITLE
kata-proxy channel error

### ISSUE THREAD

**Issue by htlabc** [kata-containers/kata-containers#1454]
i want to run a pod with kata container in k8s 

I want to run an example of kata container on k8s ，This is my yaml file 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-untrusted4
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx

Ping the pod id at the beginning, but after a while
Can't ping the pod ip 

nginx-untrusted4    1/1     Running            8          18m     10.244.0.135   deep-optiplex-7070   <none>           <none>
nginx-untrusted5    0/1     CrashLoopBackOff   5          9m39s   10.244.0.139   deep-optiplex-7070   <none>           <none>
root@deep-OptiPlex-7070:~# ping 10.244.0.135
PING 10.244.0.135 (10.244.0.135) 56(84) bytes of data.
From 10.244.0.1 icmp_seq=1 Destination Host Unreachable
From 10.244.0.1 icmp_seq=2 Destination Host Unreachable
From 10.244.0.1 icmp_seq=3 Destination Host Unreachable
From 10.244.0.1 icmp_seq=4 Destination Host Unreachable

this is log for k8s pod
Events:
  Type     Reason          Age                   From                         Message
  ----     ------          ----                  ----                         -------
  Normal   Scheduled       19m                   default-scheduler            Successfully assigned default/nginx-untrusted4 to deep-optiplex-7070
  Warning  Failed          19m                   kubelet, deep-optiplex-7070  Error: failed to create containerd task: OCI runtime create failed: Proxy is not running: unknown
  Normal   Pulling         16m (x4 over 19m)     kubelet, deep-optiplex-7070  Pulling image "docker.io/library/nginx"
  Normal   Pulled          16m (x4 over 19m)     kubelet, deep-optiplex-7070  Successfully pulled image "docker.io/library/nginx"
  Normal   Created         16m (x4 over 19m)     kubelet, deep-optiplex-7070  Created container nginx
  Normal   Started         16m (x3 over 19m)     kubelet, deep-optiplex-7070  Started container nginx
  Normal   SandboxChanged  14m (x3 over 18m)     kubelet, deep-optiplex-7070  Pod sandbox changed, it will be killed and re-created.
  Warning  BackOff         14m (x7 over 19m)     kubelet, deep-optiplex-7070  Back-off restarting failed container
  Warning  Failed          8m48s                 kubelet, deep-optiplex-7070  Error: failed to get sandbox container task: no running task found: task 46c9dc9bccddb0b05869e80c18dde6299aed9f173d1b490ec91a218ae688c568 not found: not found
  Warning  BackOff         6m36s (x6 over 9m7s)  kubelet, deep-optiplex-7070  Back-off restarting failed container
  Normal   Pulling         6m24s (x4 over 10m)   kubelet, deep-optiplex-7070  Pulling image "docker.io/library/nginx"
  Normal   Pulled          6m18s (x4 over 10m)   kubelet, deep-optiplex-7070  Successfully pulled image "docker.io/library/nginx"
  Normal   Created         6m15s (x3 over 10m)   kubelet, deep-optiplex-7070  Created container nginx
  Normal   Started         6m11s (x3 over 10m)   kubelet, deep-optiplex-7070  Started container nginx
  Normal   Killing         4m48s                 kubelet, deep-optiplex-7070  Stopping container nginx
  Normal   SandboxChanged  37s (x22 over 10m)    kubelet, deep-optiplex-7070  Pod sandbox changed, it will be killed and re-created

i run kata-runtimelist can find the kata process

root@deep-OptiPlex-7070:~# kata-runtime list
ID                                                                 PID         STATUS      BUNDLE                                                                                                                                       CREATED                         OWNER
ba7a8f8267a8f0729bcbba8b3dc019328ab696253174272f30ba86df530ffabd   23619       running     /soft/containerd/k8s/run/containerd/io.containerd.runtime.v1.linux/k8s.io/ba7a8f8267a8f0729bcbba8b3dc019328ab696253174272f30ba86df530ffabd   2021-02-24T10:49:50.57733578Z   #0

but id see the kata log have many error，Please tell me the idea of troubleshooting 

[error.log](https://github.com/kata-containers/kata-containers/files/6035375/error.log)

**Comment by liubin** [comment]
Hi @htlabc  I will close this issue and track it  by https://github.com/kata-containers/tests/issues/3267
Feel free to remind me if I was wrong.
