### ISSUE TITLE
[ASoC2020] Support cgroups v2 in rust agent

### ISSUE THREAD

**Issue by devimc** [kata-containers/kata-containers#146]
Description:
From https://github.com/kata-containers/runtime/issues/2494#issuecomment-590555279

rust agent should have an option similar to `system.unified_cgroup_hierarchy` (`agent.unified_cgroup_hierarchy`?)  to enable or disable cgroups v2

Goal:
-. make rust agent be able to setup v2 cgroups to constraint containers in the guest.

Difficulty Level: medium

**Comment by diru1100** [comment]
@devimc 

### My understanding so far:

-  An option similar to system.unified_cgroup_hierarchy  to enable or disable cgroups v2 is already implemented in go language here(https://github.com/kata-containers/agent/pull/750/files).
- I couldn't find the rust agent repository where this idea would be implemented. Could you please share the link for the same?
- If there is no repo for rust agent, the ASoC 2020 would be to implement kata agent in rust?

Can you please help me understand this better?

Thanks

**Comment by devimc** [comment]
@diru1100 

>    An option similar to system.unified_cgroup_hierarchy to enable or disable cgroups v2 is already implemented in go language here(https://github.com/kata-containers/agent/pull/750/files).

Yes, you are right - https://github.com/kata-containers/agent/#cgroups-v2

> I couldn't find the rust agent repository where this idea would be implemented. Could you please share the link for the same?

https://github.com/kata-containers/kata-containers/tree/master/src/agent

**Comment by diru1100** [comment]
> https://github.com/kata-containers/kata-containers/tree/master/src/agent
Thanks for sharing, it was right there and I missed it 😅  

Are there any beginner issues to work on, to get a better understanding of the project and workflow? 

Also, I would like to share a draft of my proposal as the deadline is approaching and get your valuable input on it. VMs and Containers is something I always wanted to work on and Kata container looks like the perfect place to get started.

**Comment by devimc** [comment]
> Are there any beginner issues to work on, to get a better understanding of the project and workflow?

All the issues that start with `tests:` are `good-first-issue`, take a look https://github.com/kata-containers/kata-containers/issues?q=is%3Aissue+is%3Aopen+tests%3A+

**Comment by diru1100** [comment]
Hello @devimc 

There seem to be no tests written so far for rust-agent. This is the main issue I found for all the unit-tests related issues: https://github.com/kata-containers/kata-containers/issues/275

I also got to know the format and the way tests are written through this wonderful guide. https://github.com/kata-containers/tests/blob/master/Unit-Test-Advice.md#rust-temporary-files

I will try to write tests for any one of the issues present, hopefully, I am going in the right direction.

I will also share the proposal document here with all details filled for you to have a look before submitting it to the official site.

**Comment by diru1100** [comment]
Hello @devimc 

[Here is my draft of the proposal for ASoC 2020](https://cbitcollege-my.sharepoint.com/:w:/g/personal/ugs160185_cse_rohit_cbit_org_in/ETCNMZXOARNBkRc-aZGDB8gBjnf0cH4uqccYLfi7bL2x7Q?e=xiagUr), kindly have a look when free and give your valuable feedback.

**Comment by bergwolf** [comment]
@diru1100 Kind reminder that the proposal needs to be submit on https://www.alibabacloud.com/zh/campaign/summerofcode2020 and the submission deadline is June 30.

**Comment by diru1100** [comment]
> @diru1100 Kind reminder that the proposal needs to be submit on https://www.alibabacloud.com/campaign/summerofcode2020 and the submission deadline is June 30.

Hi @bergwolf 

I have submitted my proposals, but I am not getting any mail confirming my submission. A notification popped up saying wait for confirmation mail. I have filled the form twice and now I am getting worried if I submitted properly or not. Kindly look into this and give an update.

Thank you very much.

**Comment by bergwolf** [comment]
@diru1100 Don't worry. I can see your submission in the system.

BTW, I would encourage you to start by writing some documentation about how cgroups v2 is handled in the go agent that would serve both as a reference and as a documentation basis for the rust implementation.

And what's your familiarity with rust? There is a slightly high learning curve for rust so if you haven't written any rust before, I'd suggest you getting your hands dirty by writing some simple code piece as soon as possible.

**Comment by diru1100** [comment]
> @diru1100 Don't worry. I can see your submission in the system.

Thank you for confirming 😄 

> BTW, I would encourage you to start by writing some documentation about how cgroups v2 is handled in the go agent that would serve both as a reference and as a documentation basis for the rust implementation.

Yes, that would be good way to start. Should I create an issue for the same?

> And what's your familiarity with rust? There is a slightly high learning curve for rust so if you haven't written any rust before, I'd suggest you getting your hands dirty by writing some simple code piece as soon as possible.

I have written basic code in rust, will complete some tutorials and understand the syntax, semantics, and how it works properly.

**Comment by bergwolf** [comment]
> Should I create an issue for the same?

Yes, please go ahead a create an issue. The documentation have [moved into the kata-containers repository too](https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs). So you can just create a new issue in the kata-containers/kata-containers repository.

**Comment by diru1100** [comment]
@devimc  @bergwolf 

It seems the proposal wasn't good enough, thank you for reviewing it.
Any feedback would be constructive. It would be great if there are any similar opportunities in kata itself for students, I really liked the whole concept and how it is built.

Thank you

**Comment by bergwolf** [comment]
@diru1100 Sorry that you were not selected. Kata Containers community still welcomes you and appreciates your contribution. Thanks!

**Comment by devimc** [comment]
@diru1100 Sorry to hear that, feedback is always important, I hope you receive it

**Comment by devimc** [comment]
@bergwolf @lifupan is the ant group working on this?

**Comment by lifupan** [comment]
> @bergwolf @lifupan is the ant group working on this?

Yes, @liubin  is working on it.
