### ISSUE TITLE
Add flexible mechanism to bind mount host files into the sandbox, but not expose to container

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1464]
**Is your feature request related to a problem? Please describe.**

As someone running Kata, I need a flexible mechanism for including files or directories into the sandbox for running guest services. As an example, I'd like to provide certs that are unique to the host into the guest environment.
 
**Describe the solution you'd like**

A way to identify one or more files or directories to be bind mounted read only into the guest.

**Describe alternatives you've considered**

Considered: 
 - baking these into the rootfs, but this can be painful if its unique to the machine it runs on, or if the secrets are updated at a frequency that is greater than updates to the guest image.
 - add in using existing Kubernetes volumes -- in this case, I don't want to have to update PodSpec, nor do I want to expose this to the container workload or end user

**Additional context**

We'll likely want the ability to make these available before the agent is necessarily up and running, and this is part of the reason we want to make sure Agent doesn't error out if the kataShared mount tag is mounted already before sandbox create request. See: https://github.com/kata-containers/kata-containers/pull/1457

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by jodh-intel** [comment]
Hi @egernst - shall we close this issue now?
