### ISSUE TITLE
What's the intent of the `master` branch of the project?

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1465]
We recently renamed `2.0-dev` branch to `main`, **yay**, but there's still another branch that may cause confusion for newcomes joining the project: `master`.

It's not totally clear to me why we need the `master` branch.  Seems it's there for 1.x related things, but what are those things, specifically?

I'm fine waiting till we deprecate 1.x (which will happen in a few months) before getting rid of the `master` branch, but I'd like to have some idea of why it's needed, and maybe drop it sooner if there's not a strong reason to keep it.

**Comment by fidencio** [comment]
@kata-containers/architecture-committee @bergwolf @chavafg

**Comment by chavafg** [comment]
I think `master` branch is not needed anymore. 
/cc @jcvenegas

**Comment by ariel-adam** [comment]
We need inputs from @egernst on this topic to decide how to progress

**Comment by cmaf** [comment]
@fidencio can we close this issue?

**Comment by fidencio** [comment]
Oh, we totally can.

We got rid of the `master` branch some time already and all projects under our org are using `main` instead.
