### ISSUE TITLE
simplify kata agent: make rust agent default

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#147]
When we introduced kata rust-agent, we have showed that it can reduce kata-agent memory footprint to 10% (11MB -> 1.1MB). While we continue making rust agent stable and featureful, we should make it default to allow more users to benefit from it in the 2.0 time frame.

**Comment by jodh-intel** [comment]
Closing as the rust agent is the default in the 2.0-dev branch.
