### ISSUE TITLE
Improve kata observability/events/debuggability

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#150]
A few important missing pieces for kata 1.x are observability, events and debuggability. While we do have some container metrics matching that of runc, there are a lot of important kata specific metrics getting dropped because of it.

In Kata 2.0, we would like to introduce kata's own metrics API, to expose more kata specific informatioin to production users who would want to either integrate it directly in their monitor or use via some third party tools like prometheus. Also we want to add kata's event API to expose kata specific events including container OOM events, guest panic events etc. And current debug console is very much limited. We'd like to extend its functionality and availability to users like system admins.

**Comment by ariel-adam** [comment]
@bergwolf could you add the PRs associated to this issue? 
That way we wont need to track (we will see it as in progress).

**Comment by devimc** [comment]
related to https://github.com/kata-containers/kata-containers/pull/441

**Comment by bergwolf** [comment]
@ariel-adam we have already merged the metrics PRs. Let's close it once #441 gets merged.
