### ISSUE TITLE
runtime: isolated spans in trace output from background context

### ISSUE THREAD

**Issue by cmaf** [kata-containers/kata-containers#1504]
In [#1389](https://github.com/kata-containers/kata-containers/pull/1389) a context parameter is added to many functions in order to fix span ordering for tracing output. Changes in that PR result in `Read()`, `Write()`, and `Close()` in [iostream.go](https://github.com/kata-containers/runtime/blob/master/virtcontainers/iostream.go) calling functions that accept a context argument which is then used in subsequent calls (specifically [`sendReq()`](https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L2148)) for tracing. Since `Read()`, `Write()`, and `Close()` implement standard interfaces and do not have a context argument, the background context is used for subsequent calls which creates parentless `sendReq()` spans in the tracing output. 

It can be fixed by creating wrapper functions that accept a context specifically for tracing output (this will produce the most accurate span ordering) or adding trace calls functions preceding `sendReq()` (will give some context to spans but not ideal).

**Comment by liubin** [comment]
My question is that should add spans for `Check`/`ReadStderr`/`ReadStdout`/`WriteStdin`, these RPC calls may lead to too much data, and will make significant storage pressure.

**Comment by cmaf** [comment]
@liubin I agree, I think adding more spans will generate too much output. But modifying a few things so that the existing `sendReq()` spans are not orphaned won't. However, you're correct in #1395 that we already have a significant amount of health check requests, so ultimately maybe we should remove spans. We could also consider adding a config option for full vs reduced trace output.

Any thoughts? @egernst @jodh-intel

**Comment by cmaf** [comment]
Closing since we are disabling tracing for sendReq() as part of disabling it for the health check in #1678.
