### ISSUE TITLE
[ASoC2020] Better IO stream handling

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#151]
Description:
Currently kata containerd shimv2 has an important design defect -- IO stream handling. Container IO stream is handled in the same channel as the container control messages. In Kata 2.0 phase, we would like to separate IO streams from container control messages, so that they do not affect each other and the control plane components can restart without breaking container IO streams.

The idea is to let CRI daemon (such as containerd) streaming server make direct use of a stdio stream exposed by vmm, so that kata-runtime and host pipes are not involved during the data copy.

The goal would be:
1. modify kata-agent and runtime to setup a connection fd as container io stream raw data connection
2. sendfd from kata runtime to containerd
3. modify containerd streaming server to make use of such fd

Difficulty Level: high

**Comment by crosbymichael** [comment]
What are the containerd changes that would need to be made?  Which specific streaming server are you referring to here?

**Comment by jodh-intel** [comment]
Could you provide an update on this @bergwolf?
