### ISSUE TITLE
virtiofs options annotation not working

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#1523]
Looking at the code here: https://github.com/kata-containers/kata-containers/blob/50f317dcff6a71f474c37f0af831aaf759782b5c/src/runtime/virtcontainers/pkg/oci/utils.go#L752-L802 it looks like the `sbConfig.HypervisorConfig.VirtioFSExtraArgs` is never processed.

**Comment by c3d** [comment]
@pmores Can you please submit your patch on the processing here? I t was better than mine in the parsing of the annotation (from memory).

**Comment by fidencio** [comment]
I've added a "nice-to-have" label that will help me to check whether we'll have something to backport or not by the moment we cut the release.

**Comment by pmores** [comment]
@c3d I've started working of this issue again and I plan to work on it until I fix it. :-)  Let's see how far I get and then decide what to do next - does this sound reasonable?
