### ISSUE TITLE
rust agent dep `path-absolutize` fails to compile

### ISSUE THREAD

**Issue by crobinso** [kata-containers/kata-containers#153]
rust agent dep `path-absolutize` is pinned to version `v1.1.3`, but that fails to compile in [`osbuilder` CI](https://travis-ci.org/kata-containers/osbuilder/jobs/657538198#L3093) and locally:

```console
error[E0133]: use of mutable static is unsafe and requires unsafe function or block
  --> src/unix.rs:15:35
   |
15 |             let path = Path::join(&CWD, self);
   |                                   ^^^^ use of mutable static
   |
   = note: mutable statics can be mutated by multiple threads: aliasing violations or data races will cause undefined behavior

error: aborting due to previous error
```

Tag `v1.2.0` seems to fix that error, so I'll send a PR to bump the dep

**Comment by devimc** [comment]
I think this was fixed https://github.com/kata-containers/kata-containers/pull/145/files#diff-8353020a225c84e78799e4dff57cfa08

**Comment by devimc** [comment]
https://github.com/kata-containers/kata-containers/pull/145/files#diff-b5e341af3fb9b6af210ddf28f3c63e9d

**Comment by crobinso** [comment]
Ahh too slow I guess. Let's close this
