### ISSUE TITLE
unify the way of getting guest online cpus

### ISSUE THREAD

**Issue by lifupan** [kata-containers/kata-containers#1536]
# Get your issue reviewed faster

# Description of problem

It's better to get the guest system's online cpus from "/sys/devices/system/cpu/online".

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with an explanation of what actually happened)

# Further information

(replace this text with any extra information you think might be useful)

**Comment by c3d** [comment]
@lifupan Assigned to you since you already seem to be on it.
