### ISSUE TITLE
How to configure devicemapper for kata container

### ISSUE THREAD

**Issue by free2k** [kata-containers/kata-containers#159]
**Is your feature request related to a problem? Please describe.**

How to configure devicemapper for kata container？
configuration.toml configuration files need to be changed

**Describe the solution you'd like**
Support devicemapper

**Describe alternatives you've considered**

**Additional context**

**Before raising this feature request**

**Comment by grahamwhaley** [comment]
Hi @free2k - I presume you are wanting or looking for some documentation. I'm not sure if we have any already - if we do, maybe it needs to be easier to find. /cc @devimc @amshinde who might know the current state.

**Comment by devimc** [comment]
@free2k 
> How to configure devicemapper for kata container？

afaik this is container engine specific (for example [docker](https://docs.docker.com/storage/storagedriver/device-mapper-driver/#configure-docker-with-the-devicemapper-storage-driver
)) and it may change depending on the version, it could be a pain to maintain *"external"* documentation up-to-date

> configuration.toml configuration files need to be changed

why? what is missing or wrong in this file?

**Comment by jodh-intel** [comment]
Hi @free2k - since Kata is effectively "middleware", we would suggest you look at the documentation for your chosen container manager for information on dm.

Closing for now, but feel free to re-open.
