### ISSUE TITLE
FS cleanup isn't carried out  if container create request times out

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1609]
In the event that a ttRPC request to the kata-agent times out (60 seconds), I've noticed that while the processes (containerd-shim-kata-v2 and vmm) are deleted, there are still mounts left on the host filesystem (/run/kata-containers/shared/sandboxes/)

We should ensure that in this event, we cleanup the mounts/fs.

**Comment by egernst** [comment]
This looks like an issue where s.Delete will error out because containers aren't in correct state. Debug WIP.

**Comment by bergwolf** [comment]
should be fixed by https://github.com/kata-containers/kata-containers/pull/985
