### ISSUE TITLE
2.1-alpha1 is a wrong tag name

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1617]
This is something that was overlooked by us and not caught during the tests because of: https://github.com/kata-containers/kata-containers/issues/1579

The correct tag name should actually be 2.1.0-alpha1, and the previous one 2.1.0-alpha0, and the VERSION file should be updated accordingly.

EDITED:
We use semver (https://github.com/blang/semver) to check release format to compare the release format (useful for upgrading), etc. That's used here: https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cli/release.go

And here's a simple example of how it breaks.

```
package main

import (
	"fmt"
	"github.com/blang/semver"
)

func main() {
	version, err := semver.Make("2.1-alpha1")
	fmt.Printf("version: %s, err: %v\n", version, err)
	
	version, err = semver.Make("2.1.0-alpha1")
	fmt.Printf("version: %s, err: %v", version, err)
}
```

And its output:
```
version: 0.0.0, err: No Major.Minor.Patch elements found
version: 2.1.0-alpha1, err: <nil>
```

**Comment by fidencio** [comment]
@bergwolf, would you mind to take a look at updating the new tags and whatnot?
I'm submitting a PR for a the changes on the VERSION file and on the kata-deploy file.

**Comment by fidencio** [comment]
@bergwolf, @egernst, @jcvenegas, @kata-containers/architecture-committee, maybe it'd be good to go for a 2.1.0-alpha2 release, just for the sake of having this bit corrected?

**Comment by egernst** [comment]
Why doesn't 2.1-alpha1 work? I think 2.1.0-alpha0 was a mistake.

**Comment by fidencio** [comment]
@egernst, the main problem is not that we changed the pattern, but we depend on semver (https://github.com/blang/semver) to check release format  to compare the release format (useful for upgrading), etc.  That's used here: https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cli/release.go

For semver, "2.1-alpha1" is invalid as "No Major.Minor.Patch elements found".  while "2.1.0-alpha1" is parseable.  We just didn't get it before because we were not updating the VERSION file on the runtime side.
