### ISSUE TITLE
Consider remove `ProcessListContainer` from VCSandbox interface

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1668]
In Kata Containers 1.x, this API is needed for [`kata-runtime ps` command](https://github.com/kata-containers/runtime/blob/59e227336903383fcb04e0075e0b55cbd98c42bb/cli/ps.go), In Kata Containers 2.x should be removed.

/cc @jodh-intel @egernst @fidencio @bergwolf @lifupan

**Comment by lifupan** [comment]
AFAK, there is no api in shimv2 corresponding with the "kata-runtime ps", which means there's no caller on  ProcessListContainer, I think it's reasonable to cleanup this api.
