### ISSUE TITLE
Update qemu and qemu-experimental to  6.1.0

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/kata-containers#1691]
Release candidate 3 patches are out.  And DAX patches where updated to for that tag.

**Comment by wainersm** [comment]
Hi @jcvenegas , @cmaf , QEMU 6.0.0 is released** now. I think that we should bump the version of both standard and experimental QEMU.

/cc @fidencio @c3d  

** Find the announcement in https://www.qemu.org/2021/04/30/qemu-6-0-0/

**Comment by fidencio** [comment]
A huge plus one for me, mainly if we can get it done **Today**. :-)

**Comment by dgibson** [comment]
This seems to have stalled, and 6.1 is now nearly out.  I have some reasons to update to 6.1 ASAP (see https://github.com/kata-containers/kata-containers/issues/2174) so possibly we want to leapfrog this.

I'm working on an update to 6.1, I'll use the PR for this as a basis.

**Comment by dgibson** [comment]
Since qemu-6.1 is now out, updating the title for this issue to skip 6.0 and go straight to 6.1.
