### ISSUE TITLE
Remove romfile= if not exist

### ISSUE THREAD

**Issue by QiuMike** [kata-containers/kata-containers#1694]
**Which feature do you think can be improved?**

The commandline of Vendor QEMU, with romfile field could be removed if it does not exist,
Currently, will shows below:
 -device virtio-rng-pci,rng=rng0,**romfile=** 

**How can it be improved?**

Just check if it equals "" before add this field in the commandline

**Additional Information**

The whole commandline:
/usr/bin/qemu-system-x86_64 -name sandbox-0502329ba44e5011c3a3851ea7bcddb32100
4fd61ccacf48b092af27d2817006 -uuid d07a7c9a-4bb9-4935-ba80-6b6f92593390 -machine pc,accel=kvm,kernel_irqchip,nvdimm=on -cpu host,pmu=off -qmp u
nix:/run/vc/vm/0502329ba44e5011c3a3851ea7bcddb321004fd61ccacf48b092af27d2817006/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=16908M -device
pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=true,id=serial0,romfile=,max
_ports=2 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/0502329ba44e5011c3a3851ea7bcddb32
1004fd61ccacf48b092af27d2817006/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/
share/kata-containers/kata-containers.img,size=536870912 -device virtio-scsi-pci,id=scsi0,disable-modern=true,romfile= -object rng-random,id=rn
g0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device vhost-vsock-pci,disable-modern=true,vhostfd=3,id=vsock-3588604826,gue
st-cid=3588604826,romfile= -chardev socket,id=char-d7d1e08ecd3b0ce4,path=/run/vc/vm/0502329ba44e5011c3a3851ea7bcddb321004fd61ccacf48b092af27d28
17006/vhost-fs.sock -device vhost-user-fs-pci,chardev=char-d7d1e08ecd3b0ce4,tag=kataShared,romfile= -netdev tap,id=network-0,vhost=on,vhostfds=
4,fds=5 -device driver=virtio-net-pci,netdev=network-0,mac=36:f3:10:d2:bc:ae,disable-modern=true,mq=on,vectors=4,romfile= -rtc base=utc,driftfi
x=slew,clock=host -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic --no-reboot -daemonize -object memo
ry-backend-file,id=dimm1,size=2048M,mem-path=/dev/shm,share=on -numa node,memdev=dimm1 -kernel /usr/share/kata-containers/vmlinux-5.10.25-84 -a
ppend tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k co
nsole=hvc0 console=hvc1 cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfst
ype=ext4 quiet systemd.show_status=false panic=1 nr_cpus=8 systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.ma
sk=systemd-networkd.socket scsi_mod.scan=none -pidfile /run/vc/vm/0502329ba44e5011c3a3851ea7bcddb321004fd61ccacf48b092af27d2817006/pid -smp 1,c
ores=1,threads=1,sockets=8,maxcpus=8

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?
Yes

**Comment by QiuMike** [comment]
I have write a patch to fix this issue,

if this issue could be accept, I will submit the patch

**Comment by cmaf** [comment]
@QiuMike please submit the PR and someone on the team will review. Thanks!

**Comment by cmaf** [comment]
Closing since issue is fixed by https://github.com/kata-containers/govmm/pull/169
