### ISSUE TITLE
Missing backports fixes in stable-2.0

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#1698]
I am trying to enable github actions in stable-2.0 to remove the travis CI. However, I am facing with a lot of issues, I already did some backports in the agent that were missing to make the agent build properly https://github.com/kata-containers/kata-containers/pull/1687, however, I was getting a failure in `static-checks.sh` with a lot of errors. I tried to backport 36e438f, however, it seems that other backports are missing like `opentelemetry` PRs and so on. As I am getting errors like 
```
Error: ../virtcontainers/sandbox.go:48:2: cannot find package "." in:
	/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/vendor/go.opentelemetry.io/otel/trace
```
Could you please submit to `stable-2.0` the PRs to fix the static checks, opentelemetry, etc to stable-2.0 so I can later enable the github actions @liubin @jodh-intel @cmaf @chavafg @fidencio

**Comment by GabyCT** [comment]
I miss to add @bergwolf for this task. Thanks

**Comment by cmaf** [comment]
Regarding the missing opentelemetry, https://github.com/kata-containers/kata-containers/pull/1539 (PR that contains https://github.com/kata-containers/kata-containers/commit/36e438f883e617c2ae413b85520eb994cfc7b180) has fixes for static checks and unit tests, some of which are changes with tracing after we migrated from opentracing to opentelemetry (https://github.com/kata-containers/kata-containers/pull/1352) and a bunch of calls were updated (https://github.com/kata-containers/kata-containers/pull/1389). To fix the errors you're getting, we could try a few things:

1. Backport only the specific changes we need from https://github.com/kata-containers/kata-containers/pull/1539, disregarding all tracing changes
2. Backport opentelemetry patch + static checks from the following PRs:
    https://github.com/kata-containers/kata-containers/pull/1352
    https://github.com/kata-containers/kata-containers/pull/1539 (we will have to modify this to not include tracing changes)
3. Completely backport tracing to stable-2.0:
    https://github.com/kata-containers/kata-containers/pull/1352
    https://github.com/kata-containers/kata-containers/pull/1389
    https://github.com/kata-containers/kata-containers/pull/1539
    https://github.com/kata-containers/kata-containers/pull/1551
    https://github.com/kata-containers/kata-containers/pull/1563
    
My question is, do we want to backport tracing changes to stable-2.0? I am able to do this, but I'm not sure it is a feature we want in stable-2.0. @GabyCT @chavafg

**Comment by GabyCT** [comment]
The main issue that I see is that `static-check.sh` will fail on stable-2.0 which will not allow us to have github actions as we have in all the repos and we will need to keep Travis CI (which I believe will stop working in a future) so I do not see another option...wdyt @chavafg

**Comment by GabyCT** [comment]
Also another point is that I am not sure but as far as I see the way that Travis is doing running is running the compiler checks and then running the static checks and as on the other hand the github actions is running the static checks and then the compiler checks.

**Comment by GabyCT** [comment]
@cmaf I noticed the PR https://github.com/kata-containers/kata-containers/pull/1539 that you suggested us, I believe that you can do the backport of that and before merging opentelemetry and so on, once that you do the backporting, I will run again the github actions and see if we still need the other commits or with this is more than enough , thanks for the help

**Comment by GabyCT** [comment]
@bergwolf can we backport #1539 to stable-2.0?

**Comment by cmaf** [comment]
Closing since PR was merged
