### ISSUE TITLE
handling changes to the agent's gRPC protocol buffer protocol version

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#17]
First things first: this issue is about the version of the Kata Containers defined agent protocol, **not** the version of protocol buffers (`proto2`, `proto3`, ...) used to define the agent protocol!

---

# Overview

- The [agent protocol](https://github.com/kata-containers/agent/blob/master/protocols/grpc/agent.proto) which underlies Kata is a gRPC protocol buffer based.
- A protocol buffer protocol requires each message member or field to be numbered.
- If the ordering of the message fields in a protocol buffer changes, all components that use the protocol nominally need to be updated to ensure they are all "*speaking the same language*".

# Handling protocol changes

Protocol buffers do have some basic features to handle protocol changes:
- https://developers.google.com/protocol-buffers/docs/proto3#updating
- https://developers.google.com/protocol-buffers/docs/proto3#enum_reserved
- https://developers.google.com/protocol-buffers/docs/proto3#unknowns
- The "deprecated" field option.

# Requirements

Since we have made lots of change and will no doubt wish to make changes at some point in the future, we need a documented approach for:

- How to deal with protocol modifications.
- How to test such changes.

# Concrete example

Assume we are already creating Kata Containers [packages](https://github.com/kata-containers/packaging/) (we're not yet)...

- A new image package is created containing a new agent version which is using a new gRPC protocol version.
- Unless packages for all system components are updated **at the same time** for this new gRPC protocol version (*), the system will not function correctly.

# Implications

This implies:

- We need some sort of "trigger" so that if any of the `*.proto` files in the directory below change in the `master `branch:

  - https://github.com/kata-containers/agent/blob/master/protocols/grpc/

  ... that this somehow triggers a re-vendor of the agent code for the other system components.

- We should start looking at the how best to handle protocol changes (see links above).

---
[*] - This also assumes we aren't using any of the protocol buffer features to handle protocol changes.

**Comment by sboeuf** [comment]
@jodh-intel Thanks for taking the time to explain this very accurately. I think that we should do two things to avoid those kind of issues as much as possible.
- Add to the developer documentation the good practices to update a `.proto` file
- Write a binary checking for bad practices, that would be run by the CI as part of the `make check`

**Comment by bergwolf** [comment]
Agreed @sboeuf. And I think we should only declare a stable API when releasing kata containers and try not to commit to any inter-operability during early stage of development for the sake of easier maintenance. IOW, while it is a nice thing to have, I would prefer to enforce it only when we are about to release kata containers.

**Comment by jodh-intel** [comment]
Yes, at this stage, I think we still expect changes to the `.proto` files but once we are providing packaged components, we need to be extra careful.

I've raised https://github.com/kata-containers/agent/issues/175 which should give us another level of protection.
