### ISSUE TITLE
Create 2.0-dev branch?

### ISSUE THREAD

**Issue by gnawux** [kata-containers/kata-containers#170]
As we decide to begin 2.0 development in parallel with version 1.12, I think we should create branch `2.0-dev` for 2.0 development and CI.

Any comments, @kata-containers/architecture-committee ?

**Comment by lifupan** [comment]
Hi @gnawux 

For this 2.0-dev branch, do we switch from grpc to ttrpc?

**Comment by bergwolf** [comment]
We've agreed to branch during AC meeting. Let's do it!

**Comment by bergwolf** [comment]
branched
