### ISSUE TITLE
Suspicious no-op return in register_memory_event_v2

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#1702]
# Description of problem

Running make check on the agent with current rust clippy (1.51) gives this warning, amongst others:

```
error: unneeded `return` statement
   --> rustjail/src/cgroups/notifier.rs:125:13
    |
125 |             return;
    |             ^^^^^^^ help: remove `return`
    |
    = note: `-D clippy::needless-return` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
```

Some more context in the code shows this, at the end of a spawned async closure within `register_memory_event_v2`:

```
        // When a cgroup is destroyed, an event is sent to eventfd.
        // So if the control path is gone, return instead of notifying.
        if !Path::new(&event_control_path).exists() {
            return;
        }
```

So, indeed the return does nothing, and therefore so does the if which invokes it.

It looks to me like this was transcription error while converting from an explicit thread to tokio runtime in commit 332fa4c65.  It looks like this was, and still should be inside the preceding `while` loop.

@Tim-Zhang, can you confirm.

**Comment by Tim-Zhang** [comment]
it was confirmed
