### ISSUE TITLE
kata-deploy: Generate a new image on every merged PR

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1710]
Currently `kata-deploy` is the recommended way for users to give a try on Kata Containers.  However, I think `kata-deploy` could be explored more, tested more, taken more advantage of.

I sincerely can think a few uses cases of this on our project, but this would benefit a lot CIs from other projects (such as CRI-O?) to easily consume our latest work and test against it.

/cc @jcvenegas @chavafg @wainersm @eadamsintel

**Comment by eadamsintel** [comment]
@fidencio Based on the vPTG I opened up an enhancement request to `kata-deploy` so that the script could run without requiring Docker or Kubernetes. That request might be redundant with the `kata-manager` script existing, but it seems that these different installation efforts could be streamlined and updated to allow installing the latest versions of Kata based on a release version (currently supported) or based on the latest pull request or a nightly build. 

https://github.com/kata-containers/kata-containers/issues/1708

**Comment by fidencio** [comment]
@eadamsintel, I saw that and I don't think that request is redundant, at all.  I see this, and a few other issues raised Today for `kata-deploy`, which were discussed as part of the vPTG, as small interlinked tasks.

Thanks a lot for opening #1708 and that could be the first one to be attacked (even for the current state, where we only update the binaries as part of the releases).

**Comment by jcvenegas** [comment]
About build components, and identify is up-date. 
I usually like to build things in docker images.
  - If a file in the dockerimage changes docker will detect it and rebuild.
  - We could have something similar without docker build by using  checking all the files needed to build  hast not changed over the time. Components need to be self contained. 
e.g.
```
cd kata-containers/assets/qemu
./build-tarball.sh
```
The ID of this qemu is not only the version if qemu but know that none of the builds scripts have changed.
We need to hash the files and his last modification date.  Does it make sense?

When we have self build contained assets. This is:
- qemu
- cloud-hypervisor
- runtime(shimv2)
- image
- kernel

1) Each of them can be build in parallel. 
2) The asssets can be cached. And know if we need to build based in ID(hash of all files needed to build).

The scripts builds should support both build inside of a container and in the host.
- Containerized build help to get an static binary without install deps in your host( helpful for host that may be old and decencies may be hard).

After each component is build it is just a matter of join all the files in one single directory (as kata-deploy does today).
