### ISSUE TITLE
kata-runtime kata-exec:  assumes console is via vsock?

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1712]
Was playing with kata-runtime exec earlier, and was seeing timeouts when dialing vsock. In particular, I was testing trying to attach to the console of a running Kata pod, utilizing QEMU. 

In reviewing code, I see we use getConn, which I *think* is assuming that the console is accessible via a particular vsock port. In the case of QEMU; aren't we still exposing as a console device at a particular fs location (/var/run/vc/vm/console.sock), and not vsock?

https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cli/kata-exec.go#L97

**Comment by bergwolf** [comment]
@egernst the shimv2 metrics server will always start regardless of whether `kata-monitor` is started or not. See https://github.com/kata-containers/kata-containers/blob/main/src/runtime/containerd-shim-v2/shim_management.go#L130

So what `kata-runtime exec` does it first query the shimv2 metrics server to get the vsock address of a pod via `getConn` and then connect to it.

**Comment by egernst** [comment]
I was surprised based on usually using the console.sock when connecting with QEMU. If we can via VSOCK, the question then becomes -- we do we support console today? If we require vsock anyway at this point, we might as well (finally) drop console.

**Comment by egernst** [comment]
Closing this, and opened #1723 to track dropping console.
