### ISSUE TITLE
Remove stray whitespaces

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#1735]
It's annoying that we accept [stray trailing whitespaces](https://github.com/kata-containers/kata-containers/pull/1733#discussion_r619083328) in the code

**Comment by fidencio** [comment]
I'd strongly recommend that either we enforce this by using something like https://github.com/igorshubovych/markdownlint-cli or we just don´t bother about this at all.

**Comment by c3d** [comment]
What surprises me is that our go files also have trailing whitespaces in them. I thought we were enforcing formatting with `gofmt`. Does `gofmt` leave whitespace behind?

**Comment by c3d** [comment]
There is an existing action that checks whitespaces: https://github.com/harupy/find-trailing-whitespace

**Comment by ariel-adam** [comment]
Closing this issue together with its PR.
