### ISSUE TITLE
Add document for  setting `enable_pprof` in Pod annotations

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1744]
Now `enable_pprof` is supported for individual pods [through annotation](https://github.com/kata-containers/kata-containers/blob/2fc7f75724ac9e18e60f63dcc9aa395dc51c184d/src/runtime/containerd-shim-v2/shim_management.go#L175-L179), but not described in `docs/how-to/how-to-set-sandbox-config-kata.md` yet.

**Comment by Tim-Zhang** [comment]
add document for pr: https://github.com/kata-containers/kata-containers/pull/398
