### ISSUE TITLE
refactor QEMU to utilize virtiofsd interface

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1757]
Much of the virtiofsd management is identical between CLH and QEMU. Let's refactor to use a single implementation of virtiofsd to deduplicate, and minimize code maintenance.

This came up as part of https://github.com/kata-containers/kata-containers/pull/1756

**Comment by fidencio** [comment]
This should be fixed as part of 72cd8f5ef677cebeb84e1f64cdab6dbdc831619e
Please, feel free to re-open it if that's not the case.
