### ISSUE TITLE
runtime: dropped error

### ISSUE THREAD

**Issue by alrs** [kata-containers/kata-containers#1761]
# Description of problem
An `err` variable is being dropped in `runtime/virtcontainers/pkg/cloud-hypervisor/client`.

**Comment by cmaf** [comment]
@alrs are you still having this problem? If so, could you provide more details?

**Comment by fidencio** [comment]
@cmaf, this one was solved in the code generation side by @likebreath.

@alrs, please, let us know if you face the same issue in newer releases and we can follow up with Bo on the cloud-hypervisor side.

Closing it for now.
