### ISSUE TITLE
Does Kubernetes + Docker + Kata Containers work？

### ISSUE THREAD

**Issue by Corgi-Google** [kata-containers/kata-containers#1775]
Just a question. I don't kown whether it works or not. I have tried CRI-O and Containerd and they worked fine. But I use Docker as CRI, I can use Docker with kata-runtime alone. But when I try to use Kata Containers as Docker CRI with Kuberntes. It occurs error.

Error：
Failed to create pod sandbox: rpc error: code = Unknown desc = RuntimeHandler "kata-runtime" not supported

kubectl get runtimeclass
NAME              HANDLER        AGE
kata-containers   kata-runtime   19m

**Comment by fidencio** [comment]
@Corgi-Google, short answer is no, it does not.

We drop CLI support when switched from kata-containers 1.x to 2.x and so far we don't have plans to add it back.  However, this decision is not set and we have an issue opened about that, that you can use to track the progress on that front: https://github.com/kata-containers/kata-containers/issues/722

**Comment by Corgi-Google** [comment]
> @Corgi-Google, short answer is no, it does not.
> 
> We dropped the CLI support when switched from kata-containers 1.x to 2.x and so far we don't have plans to add it back. However, this decision is not set and we have an issue opened about that, that you can use to track the progress on that front: #722

Thank you. I did not make myself clear. My Kata version is 1.x. When I use docker with kata as runtime alone, It works. But when in Kubernetes, it can not work. Do I need some further configuration?

**Comment by fidencio** [comment]
> > @Corgi-Google, short answer is no, it does not.
> > We dropped the CLI support when switched from kata-containers 1.x to 2.x and so far we don't have plans to add it back. However, this decision is not set and we have an issue opened about that, that you can use to track the progress on that front: #722
> 
> Thank you. I did not make myself clear. My Kata version is 1.x. When I use docker with kata as runtime alone, It works. But when in Kubernetes, it can not work. Do I need some further configuration?

Aha!  So, this issue should have been filled on `kata-containers/runtime` repo, and I can transfer it there, no problem.
I won't be able to help you con the specific configuration you need for that, but I'd say it's supposed to work.

However, mind that 1.x is reaching its EOL in May.

**Comment by Corgi-Google** [comment]
> > > @Corgi-Google, short answer is no, it does not.
> > > We dropped the CLI support when switched from kata-containers 1.x to 2.x and so far we don't have plans to add it back. However, this decision is not set and we have an issue opened about that, that you can use to track the progress on that front: #722
> > 
> > 
> > Thank you. I did not make myself clear. My Kata version is 1.x. When I use docker with kata as runtime alone, It works. But when in Kubernetes, it can not work. Do I need some further configuration?
> 
> Aha! So, this issue should have been filled on `kata-containers/runtime` repo, and I can transfer it there, no problem.
> I won't be able to help you con the specific configuration you need for that, but I'd say it's supposed to work.
> 
> However, mind that 1.x is reaching its EOL in May.

Okay.Thank you. BTW, can Kata 2.x work on CentOS 7.6?

**Comment by fidencio** [comment]
> > > > @Corgi-Google, short answer is no, it does not.
> > > > We dropped the CLI support when switched from kata-containers 1.x to 2.x and so far we don't have plans to add it back. However, this decision is not set and we have an issue opened about that, that you can use to track the progress on that front: #722
> > > 
> > > 
> > > Thank you. I did not make myself clear. My Kata version is 1.x. When I use docker with kata as runtime alone, It works. But when in Kubernetes, it can not work. Do I need some further configuration?
> > 
> > 
> > Aha! So, this issue should have been filled on `kata-containers/runtime` repo, and I can transfer it there, no problem.
> > I won't be able to help you con the specific configuration you need for that, but I'd say it's supposed to work.
> > However, mind that 1.x is reaching its EOL in May.
> 
> Okay.Thank you. BTW, can Kata 2.x work on CentOS 7.6?

It may, as long as you use kata-deploy (https://github.com/kata-containers/kata-containers/tree/main/tools/packaging/kata-deploy).  if you want to use packages from the distro, I'd strongly recommend using CentOS 8.

We (@etrunko, to be honest) are maintaining the Fedora / CentOS distros, doing the updates as soon as a new release is out (and now waiting for 2.1.0 is out to update the package there).

**Comment by egernst** [comment]
You need either containerd or crio to work with Kata. Dockershim is not compatible with sandbox runtimes like Kata Containers.

**Comment by Corgi-Google** [comment]
> You need either containerd or crio to work with Kata. Dockershim is not compatible with sandbox runtimes like Kata Containers.

Thank you. What you said is Kata 1.x or Kata 2.x ?

**Comment by egernst** [comment]
@Corgi-Google  -- both.

**Comment by ariel-adam** [comment]
@Corgi-Google closing the issue since the question seems to be answered.
Please reopen if needed :-).
