### ISSUE TITLE
Just one question

### ISSUE THREAD

**Issue by zgen0623** [kata-containers/kata-containers#180]
Why not make the kata-containers support to run multiple pods that belong to the same namespace of kubernetes in one vm?

**Comment by grahamwhaley** [comment]
That's an interesting idea. I'm not sure it is a security model that k8s supports though, so would be an interesting differentiator.
Right now kata runs all containers in a pod in a single VM.
/cc @kata-containers/architecture-committee for thoughts etc.

**Comment by zgen0623** [comment]
The following is the concept of namespace of k8s.
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by bergwolf** [comment]
Because we think that a VM is a more natural fit for the Kuernetes pod concept: https://kubernetes.io/docs/concepts/workloads/pods/pod/
