### ISSUE TITLE
cc1: error: -Werror=date-time: no option -Wdate-time 

### ISSUE THREAD

**Issue by Corgi-Google** [kata-containers/kata-containers#1806]
https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/README.md#build-kata-containers-kernel

I try to build Kata kernel from source code. 
First, I run "./build-kernel.sh setup" in  /src/github.com/kata-containers/kata-containers/tools/packaging/kernel. And It worked fine.
But when I run "./build-kernel.sh build", It occured errors:

[root@host-178-104-163-130 kernel]# ./build-kernel.sh build
~/go/src/github.com/kata-containers/tests ~/go/src/github.com/kata-containers/kata-containers/tools/packaging/kernel
~/go/src/github.com/kata-containers/kata-containers/tools/packaging/kernel
INFO: Config version: 84
INFO: Kernel version: 5.10.25
  DESCEND  objtool
  CC      scripts/mod/empty.o
  CC      scripts/mod/devicetable-offsets.s
cc1: error: -Werror=date-time: no option -Wdate-time
cc1: error: -Werror=date-time: no option -Wdate-time
make[2]: *** [scripts/mod/empty.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/mod/devicetable-offsets.s] Error 1
make[1]: *** [prepare0] Error 2
make: *** [__sub-make] Error 2

How should I fix it ?? Is it a bug??

**Comment by ManaSugi** [comment]
@Corgi-Google 
It seems that `gcc` you use does not have the `-Wdate-time` option.
The `-Wdate-time` option  has been added from `gcc 4.9`.
https://gcc.gnu.org/gcc-4.9/changes.html

Did you use `gcc 4.9` or higher version?

**Comment by Corgi-Google** [comment]
> @Corgi-Google
> It seems that `gcc` you use does not have the `-Wdate-time` option.
> The `-Wdate-time` option has been added from `gcc 4.9`.
> https://gcc.gnu.org/gcc-4.9/changes.html
> 
> Did you use `gcc 4.9` or higher version?

Ohh, Thank you. I update my gcc 4.8.x to 9.3.x. And It works.
