### ISSUE TITLE
NewTestConstraint in runtime/katatestutils panic on Debian testing/sid

### ISSUE THREAD

**Issue by zhsj** [kata-containers/kata-containers#1864]
# Description of problem

As Debian testing and sid are rolling update OS, they don't have version.

So when `getDistroDetails` returns `errUnknownDistroName`, `NewTestConstraint` panic.

# Expected result

Can run test on Debian testing and sid.

# Actual result

Panic

# Further information

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by zhsj** [comment]
I'd like to fix it. However I'd like to see your opinions. I don't see any use of  `NeedDistroVersionXX`, can we just remove them? It seems complex to implement these fucntions well for rolling update OS.

**Comment by zhsj** [comment]
CC @jodh-intel , as these functions are implemented in https://github.com/kata-containers/runtime/pull/1587/files

**Comment by c3d** [comment]
Any PR would be welcome. I don't see your work as overlapping with what @jodh-intel was proposing.
