### ISSUE TITLE
docs: how-to set runtime configuration values from within k8s pod spec 

### ISSUE THREAD

**Issue by jimcadden** [kata-containers/kata-containers#1865]
Is it possible to overwrite the values in `configuration.toml` on a per-pod basis through the pod's yaml spec?  If so, there should be documentation to illustrate how it is done.

**Comment by egernst** [comment]
see  https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md

**Comment by jimcadden** [comment]
Thanks @egernst ... Not sure how I missed that! :)
