### ISSUE TITLE
qemu-kvm Property '.cache-size' not found

### ISSUE THREAD

**Issue by lingniao2000** [kata-containers/kata-containers#1866]
qemu-kvm-common-5.1
kata-containers-2.0.1

```
# Default size of DAX cache in MiB
virtio_fs_cache_size = 2000
```
failed to create containerd task: failed to launch qemu: exit status 1, error messages from qemu log: qemu-kvm: -device vhost-user-fs-pci,chardev=char-2bb49b4f158e44cc,tag=kataShared,cache-size=2000M,romfile=: Property '.cache-size' not found

It seem not support  parameter virtio_fs_cache_size,what should I do ?

**Comment by fidencio** [comment]
Same comment as https://github.com/kata-containers/kata-containers/issues/1867#issuecomment-842231432

You're trying to use DAX on a QEMU and kernel that do not have DAX support enabled.  It won't work.
You either have to build or own QEMU / kernel, or use `virtio_fs_cache_size = 0` till the upstream work reaches CentOS.

**Comment by lingniao2000** [comment]
Is there any reference document, can I learn from it

**Comment by fidencio** [comment]
https://virtio-fs.gitlab.io/ is a good place to take a look at the DAX support state, which is still marked as experimental.
