### ISSUE TITLE
Property '.cache-size' not found

### ISSUE THREAD

**Issue by lingniao2000** [kata-containers/kata-containers#1867]
kata-containers-2.0.1
qemu-kvm-core-5.1

/usr/share/defaults/kata-containers/configuration.toml
```
# Default size of DAX cache in MiB
virtio_fs_cache_size = 2000
```

failed to create containerd task: failed to launch qemu: exit status 1, error messages from qemu log: qemu-kvm: -device vhost-user-fs-pci,chardev=char-2bb49b4f158e44cc,tag=kataShared,cache-size=2000M,romfile=: Property '.cache-size' not found

**It seems not support this parameter ,What should I do ?**

**Comment by fidencio** [comment]
Oh. now coming back to this one.

DAX is not enabled on the kernel / virtiofs you're using (assuming you're using from CentOS).
Please, give it a try with `virtio_fs_cache_size = 0` (DAX disabled) and / or build your own kernel / QEMU that has support to it.
