### ISSUE TITLE
docs: Update the stable branch strategy according to what was proposed in our ML

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#1876]
Last week I've proposed a new release cadence in our mailing list, and the email can be found [here|http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001894.html].

As there was no push-back, now I'm trying to make it official by updated the related documents.

All in all, the proposal involves maintaining **only one** stable branch per active major release;

EDITED: There was a light push back on having the releases out in a 8 weeks cadence rather than 12 weeks, so we can rediscuss this for the 2.3 release cycle, if needed. 2.2 release cycle will happen 12 weeks after 2.1 release cycle happened.

Please, @kata-containers/architecture-committee, I'd like to have an approval of each one of the active members before going ahead with this one.

**Comment by egernst** [comment]
I wonder if every 2 weeks is a bit too often? If there are considerable bug fixes I could see doing faster, but to me I think 4 weeks makes more sense. I feel somewhat similar about the 12 -> 8 week reduction. Unless we are hitting a lot of new features we need to get out?

(sorry for being late to weigh in here!)

**Comment by fidencio** [comment]
> I wonder if every 2 weeks is a bit too often? If there are considerable bug fixes I could see doing faster, but to me I think 4 weeks makes more sense. I feel somewhat similar about the 12 -> 8 week reduction. Unless we are hitting a lot of new features we need to get out?

I think timely wise it may hurt some downstream consumers of our project.  However, as I don't see that happening for 2.2 release cycle, I'd say let's keep 12 weeks and rediscuss this, **if needed**, as part of 2.3 release cycle.
Does this sound reasonable?

However, there's one change that I'd like to have that's only having a 2 weeks of feature freeze between rc and the final release.
1 whole month is  way too long and it'll lead us to having issues figuring out what has to be backported or not, as it already happened in the past, increase the load on the one doing the release.

Please, see the proposed release schedule for 2.2.0 here:
https://github.com/kata-containers/community/wiki/Release-Team-Rota

I have updated the PRs and this issue, dropping the change of the cadence of the release, keeping only the stable branch strategy change.

> 
> (sorry for being late to weigh in here!)

That's fine, Eric, thanks for jumping in and I appreciate the review.

**Comment by egernst** [comment]
The RC part SGTM, and happy with plan to reevaluate as well.
