### ISSUE TITLE
Can Kata Containers support MIPS64?

### ISSUE THREAD

**Issue by hellocloudnative** [kata-containers/kata-containers#1890]
Can Kata Containers support MIPS?
 It would be great if we could support MIPS64. 
If I want to transplant Kata containers myself, what should I do? 
Could you please tell me a detailed procedure and precautions? 

Thank you very much

**Comment by ariel-adam** [comment]
We have not tested this on MIPS64 and since we don't have HW for that (nor a CI to run on it) it's currently not supported.
@hellocloudnative  Would you be interested in pushing this forward?

**Comment by hellocloudnative** [comment]
@ariel-adam  I have the hardware here and I'm working on it.
But I met a lot of problems, if you are interested, I don't know whether we can push forward the work together, communicate with each other.
If so, may I have your contact information?
Thank you very much

**Comment by cmaf** [comment]
Hi @hellocloudnative, any progress on the MIPS64 testing?

**Comment by cmaf** [comment]
@hellocloudnative since MIPS64 is not supported and we haven't heard back I'm going to close this issue. If you have done work related to it please create a new issue. Thanks!
