### ISSUE TITLE
docs: Developer guide - Add a custom agent to the rootfs image command incorrect?

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#1904]
Sorry if the bug report doesn't quite fit the template as it is a doc issue (and my first time raising one on this project)

# Description of problem

I've been using the [developer guide](../blob/main/docs/Developer-Guide.md) to try understand the project a bit better and wanted to build a custom kata agent and get it added into my rootfs image to test out the process:
I made a change to `/src/agent/src/main.rs` to add a custom line to the 'announce` logging:
```rust
fn announce(logger: &Logger, config: &AgentConfig) {
    info!(logger, "stevenh's agent #2: announce";
````
so I could see in the logs if the new code was picked up, but after several attempts and re-following through the process I was still getting the standard announce logging when I tested through containerd:
`time="2021-05-20T05:54:44.224598309-07:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test-kata/console.sock name=containerd-shim-v2 pid=161286 sandbox=test-kata source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"announce\",\"level\":\"INFO\",\"ts\":\"2021-05-20T12:54:44.153053502+00:00\",\"name\":\"kata-agent\",\"pid\":\"53\",\"source\":\"agent\",\"subsystem\":\"root\",\"version\":\"0.1.0\",\"config\":\"AgentConfig { debug_console: false, dev_mode: false, log_level: Debug, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \\\"vsock://-1:1024\\\", unified_cgroup_hierarchy: false }\",\"agent-commit\":\"2.1.0-rc0-f6c5f7c0ef8058fbd70bf6d47e7b2698214b729c\",\"api-version\":\"0.0.1\",\"agent-type\":\"rust\",\"agent-version\":\"2.1.0-rc0\"}"`
Note the `"msg\":\"announce\"`

After a look of digging I think that problem is with the `$ sudo install -o root -g root -m 0550 -t ${ROOTFS_DIR}/bin ../../../src/agent/target/x86_64-unknown-linux-musl/release/kata-agent` command. It puts the custom kata agent in `${ROOTFS_DIR}/bin/kata-agent`, but the original rootfs creation has an kata-agent binary in `${ROOTFS_DIR}/usr/bin/kata-agent` and the `${ROOTFS_DIR}/usr/lib/systemd/system/kata-agent.service` points to the `/usr/bin/kata-agent` copy:
```bash
$ sudo cat ${ROOTFS_DIR}/usr/lib/systemd/system/kata-agent.service
...
[Service]
...
ExecStart=/usr/bin/kata-agent
```
not `/bin/kata-agent` where we've copied it.

### Fix?

When I changed the first 'Add a custom agent to the rootfs image' command to `$ sudo install -o root -g root -m 0550 -t ${ROOTFS_DIR}/usr/bin ../../../src/agent/target/x86_64-unknown-linux-musl/release/kata-agent` (*note `${ROOTFS_DIR}/bin` -> `${ROOTFS_DIR}/usr/bin`*) and then built and installed the kata-agent my new code got picked up and the logs were changed:
`time="2021-05-21T01:44:16.242322801-07:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test-kata/console.sock name=containerd-shim-v2 pid=193240 sandbox=test-kata source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"stevenh's agent #2: announce\",\"level\":\"INFO\",\"ts\":\"2021-05-21T08:44:16.194836264+00:00\",\"name\":\"kata-agent\",\"subsystem\":\"root\",\"version\":\"0.1.0\",\"source\":\"agent\",\"pid\":\"54\",\"agent-type\":\"rust\",\"agent-commit\":\"2.1.0-stevenh-1df5aac71766ac0313537d00305d829a73bcbf19-dirty\",\"config\":\"AgentConfig { debug_console: false, dev_mode: false, log_level: Debug, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \\\"vsock://-1:1024\\\", unified_cgroup_hierarchy: false }\",\"agent-version\":\"2.1.0-rc0\",\"api-version\":\"0.0.1\"}"`
Note: `\"msg\":\"stevenh's agent #2: announce\"`

I hope this makes sense. I'm happy to create the PR for the very simple change if you agree that my logic is correct. Thanks!

**Comment by fidencio** [comment]
@stevenhorsman, please, go ahead with the PR as I do believe your logic is correct (or, we're wrong together ;-)).

**Comment by stevenhorsman** [comment]
Thanks for the swift reply @fidencio - I created #1906 for this. I've tried to follow the contributing guidelines, so I hope it is correct :)
