### ISSUE TITLE
cannot launch VM via qemu: kata-containers.img for guest RAM: Read-only file system

### ISSUE THREAD

**Issue by LiangZhou9527** [kata-containers/kata-containers#1916]
Hi there,

I tried to install kata2.x on my CentOS 8 with snap command, following the guide "snap-installation-guide.md" with channel "stable"：
But seems that the kata1.x is installed , instead of kata2.x:

> [root@localhost bin]# sudo snap install kata-containers --stable --classic
kata-containers 1.12.1 from Kata Containers (katacontainers✓) installed
[root@localhost /]# /snap/kata-containers/current/usr/bin/kata-runtime -v
kata-runtime  : 1.12.1
   commit   : b967088a667018b7468a9f93d48cb81650e0dfa4
   OCI specs: 1.0.1-dev

So I changed the channel from "stable" to "candidate", yes now the 2.x is installed:

> [root@localhost /]# sudo snap install kata-containers --candidate --classic
kata-containers (candidate) 2.1.0 from Kata Containers (katacontainers✓) installed
[root@localhost /]# /snap/kata-containers/current/usr/bin/kata-runtime -v
kata-runtime  : 2.1.0
   commit   : 0f822919268e4095dd9bdbbb2351248b53746501
   OCI specs: 1.0.1-dev

However, with this intallation, the qemu guest cannot be launched:

> [root@localhost /]# ctr run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello uname -a
ctr: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -object memory-backend-file,id=mem0,mem-path=/var/lib/snapd/snap/kata-containers/719/usr/share/kata-containers/kata-containers.img,size=134217728: can't open backing store /var/lib/snapd/snap/kata-containers/719/usr/share/kata-containers/kata-containers.img for guest RAM: Read-only file system
: unknown

What did I missed ?

Thanks.

**Comment by fidencio** [comment]
Hey, I never used snap on CentOS.  However, I'd really recommend you to use the CentOS packages, maintained by @etrunko.
Please, refer to: https://github.com/kata-containers/kata-containers/blob/main/docs/install/centos-installation-guide.md

And yes, you need the advanced-virt module enabled.

If there's some issue, please, report it back here and @etrunko can take a lok at that.

**Comment by LiangZhou9527** [comment]
> Hey, I never used snap on CentOS. However, I'd really recommend you to use the CentOS packages, maintained by @etrunko.
> Please, refer to: https://github.com/kata-containers/kata-containers/blob/main/docs/install/centos-installation-guide.md
> 
> And yes, you need the advanced-virt module enabled.
> 
> If there's some issue, please, report it back here and @etrunko can take a lok at that.

Thank you @fidencio for your reply, yes way you suggested works on my CentOS. 
Seems for snap way it's a regression because two month ago I tried the snap way and it worked at that time, but now it does not work as expected.

**Comment by devimc** [comment]
@LiangZhou9527 thanks for the heads up, I will take a look

**Comment by liangjw-china** [comment]
I installed kata-containers with snap version 2.51 on ubuntu20.04 LTS and got the same error when I tried to start a container using ctr
kata-runtime  : 2.1.1
   commit   : 0e2be438
   OCI specs: 1.0.1-dev

**Comment by devimc** [comment]
Hi @liangjw-china yes, I'm working on that

**Comment by devimc** [comment]
@liangjw-china  @LiangZhou9527   fixed, please try again
