### ISSUE TITLE
Failed to mount /sys/kernel/tracing directory.

### ISSUE THREAD

**Issue by sunwoo2** [kata-containers/kata-containers#1923]
# Description of problem

I try to mount '/sys/kernel/tracing' using docker volume for some tracing in kata container, but an error occurs. Other common directories do not fail. What's the problem ??

# Actual result
`$ docker run --rm -it --runtime kata-qemu -v /sys/kernel/tracing:/home syscall_trace:v5.0 bash`
```
docker: Error response from daemon: OCI runtime create failed: rpc error: code = Internal desc = Could not run process: 
container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: 
mounting \\\"/sys/kernel/tracing\\\" to rootfs \\\"/run/kata-containers/shared/containers/93ccc1cf668967d20c057e7ebb9a349684264cdb4a68c865a57374039e7d0bc0/rootfs\\\" at 
\\\"/home\\\" caused \\\"stat /sys/kernel/tracing: no such file or directory\\\"\"": unknown.
```

# Further information

I'm using ubuntu 20.04 as docker image.
```
kata-runtime  : 1.12.0
   commit   : 439d131e706e18018094bca48ae20adfa5d0fb7a
   OCI specs: 1.0.1-dev
```

**Comment by devimc** [comment]
Hi @sunwoo2 - Kata 1.x has been deprecated also you are trying to share a sysfs directory with the VM, something that I think virtiofs not support

cc @kata-containers/redhat @dagrh

**Comment by dagrh** [comment]
Is this actually a question of whether you have a /sys/kernel/tracing on the kernel in the kata child kernel?
Using a standalone qemu+virtiofs I did manage to mount /sys/kernel/tracing into a guest - although interestingly can't actually read anything from the 'files'.

**Comment by sunwoo2** [comment]
@devimc Thanks. Can kata 2.x be used in ubuntu?

**Comment by sunwoo2** [comment]
@dagrh Thanks. Actually, What I want is to mount  /sys/kernel/tracing in host to kata containers to write at `trace_marker` file.
Can you tell me how mount /sys/kernel/tracing into a guest? Any more details?
And what's the meaning of `can't actually read anything from the 'files'`?

**Comment by devimc** [comment]
@sunwoo2 

> @devimc Thanks. Can kata 2.x be used in ubuntu?

yes, but I think you need to build & install it from source  or from the snapcraft store

**Comment by sunwoo2** [comment]
> @dagrh Thanks. Actually, What I want is to mount /sys/kernel/tracing in host to kata containers to write at `trace_marker` file.
> Can you tell me how mount /sys/kernel/tracing into a guest? Any more details?
> And what's the meaning of `can't actually read anything from the 'files'`?
