### ISSUE TITLE
metrics: kata-monitor should report virtiofsd metrics

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/kata-containers#1926]
**Which feature do you think can be improved?**

virtiofs is a common common component for shared filesystems  and it may increase kata overhead (depending on how is configured). Kata  should provide metrics to monitor it.

**How can it be improved?**

Export metrics   using kata-monitor.

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by jcvenegas** [comment]
@devimc @egernst @liubin @bergwolf  does it make sense to you ?

**Comment by jcvenegas** [comment]
It would be great to have it exported to provide more data in metrics tests. See : https://github.com/kata-containers/tests/issues/3569

**Comment by liubin** [comment]
Yes, it will be helpful to ensure the Kata Containers is working by monitoring all the components.
