### ISSUE TITLE
Kata containers didn't  work against the latest containerd

### ISSUE THREAD

**Issue by lifupan** [kata-containers/kata-containers#1971]
# Description of problem

Since the containerd had switched the socket from abstract socket to unix path socket, see https://github.com/containerd/containerd/commit/4a4bb851f5da563ff6e68a83dc837c7699c469ad,
thus kata should upgrade containerd vendor to compatible with the latest containerd.

@fidencio 
I think the crio also need some change to be compatible with it. 

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with an explanation of what actually happened)

# Further information

(replace this text with any extra information you think might be useful)

**Comment by fidencio** [comment]
@lifupan, I'll double check on CRI-O side but I think we're fine there as we're already vendoring the latest containerd bits on the CRI-O side.

Thanks for the head's up and I'll update this later Today / Tomorrow.

**Comment by davidhay1969** [comment]
Thanks for raising this @lifupan following the [thread](https://katacontainers.slack.com/archives/C86U7NZND/p1623010730069900) in the `kata-containers` Slack.

Purely FYI, I hit an issue with the most recent build of `containerd` using this job: -

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kata-job
spec:
  template:
    spec:
      runtimeClassName: kata
      containers:
      - name: kata-job-container
        image: nginx
        command: ["bash"]
        args:
        - "-c"
        - "uname -a"
      restartPolicy: Never
```

The pod stays in `ContainerCreating` and `kubectl describe pod` shows: -

```text
...

Events:
  Type     Reason                  Age              From               Message
  ----     ------                  ----             ----               -------
  Normal   Scheduled               10s              default-scheduler  Successfully assigned default/kata-job-29jmf to telicity2.fyre.ibm.com
  Warning  FailedCreatePodSandBox  2s (x5 over 9s)  kubelet            Failed to create pod sandbox: rpc error: code = NotFound desc = failed to create containerd task: failed to create shim: not found
```

This is how I install `containerd` into the existing K8s `1.21` cluster: -

##  Set a variable for the required version

`export version="1.5.2"`

##  Retrieve the requisite version

`wget --quiet https://github.com/containerd/containerd/releases/download/v"$version"/containerd-"$version"-linux-amd64.tar.gz -O containerd.tar.gz && tar xvzf containerd.tar.gz -C /usr/local`

##  Validate

```bash
ls -al `which containerd`
```

```text
-rwxr-xr-x 1 1001 lxd 49049696 May 19 09:56 /usr/local/bin/containerd
```

`containerd --version`

```text
containerd github.com/containerd/containerd v1.5.2 36cc874494a56a253cd181a1a685b44b58a2e34a
```

##  Restart the `containerd` service

`systemctl restart containerd.service`

If I step down to, say, `1.3.6` : -

```text
containerd github.com/containerd/containerd v1.3.6 be75852b8d7849474a20192f9ed1bf34fdd454f1
```

all is well: -

```text
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  16s   default-scheduler  Successfully assigned default/kata-job-mskf4 to telicity2.fyre.ibm.com
  Normal  Pulling    14s   kubelet            Pulling image "nginx"
  Normal  Pulled     13s   kubelet            Successfully pulled image "nginx" in 1.259731059s
  Normal  Created    12s   kubelet            Created container kata-job-container
  Normal  Started    12s   kubelet            Started container kata-job-container
```

Let me know if I can help further 🙇‍♂️

**Comment by inahga** [comment]
Hello! We're affected by the same issue--`containerd v1.5.2` not working with `stable-2.1`.

Fortunately it looks like https://github.com/kata-containers/kata-containers/pull/2040 solves the issue. I dropped in `containerd-shim-kata-v2` patched with https://github.com/kata-containers/kata-containers/pull/2040 and it brought the Kata pods back to life.

Any chance of this fix being backported to `stable-2.1`? Would be happy to help/test any way I can.

**Comment by lifupan** [comment]
@inahga 

I'm still working on the CI, since the upgrading containerd vendor would break the CI  too. Once the CI worked, we'll merge it into main branch first. But for the backport, we would have a carefully evaluation: since it would break the compatibility with the older containerd.  Hi @fidencio,  once we upgraded the containerd vendor, it would only work with the containerd 1.5.x, so would we like to backport it to the stable-2.1 or any other stable release?

**Comment by inahga** [comment]
Ah--I didn't realize it would break compatibility that far back. In that case I can't reasonably expect a backport, so no worries! We can build the shim from main branch.

**Comment by fidencio** [comment]
> @inahga
> 
> I'm still working on the CI, since the upgrading containerd vendor would break the CI too. Once the CI worked, we'll merge it into main branch first. But for the backport, we would have a carefully evaluation: since it would break the compatibility with the older containerd. Hi @fidencio, once we upgraded the containerd vendor, it would only work with the containerd from v1.3.9, v1.4.3 and v1.5.0, so would we like to backport it to the stable-2.1 or any other stable release?

This is quite intrusive. :-).
I'd say we use it only for main and have a huge release note about this.  I'm trying to figure out what we need to fix on the CRI-O side to unblock the CI, but we plan to have this one fixed ASAP.

**Comment by davidhay1969** [comment]
@fidencio @lifupan just to double-check, are we still "blocked" from taking the more recent builds of `containerd` with Kata `2.1.1` or `2.2.0-alpha1/2` ?

I ask because there's a known vulnerability with `containerd` [USN-5012-1: containerd vulnerabilities](https://ubuntu.com/security/notices/USN-5012-1) that requires us to update to `containerd` `1.5.2` 

With this version, it looks like the `shim` interaction is again borked :-(

```text
  Warning  FailedCreatePodSandBox  1s (x2 over 3s)  kubelet            Failed to create pod sandbox: rpc error: code = NotFound desc = failed to create containerd task: failed to create shim: not found
```

I'm now testing `2.2.0-alpha1` with `containerd` `1.5.0` .....

**Comment by davidhay1969** [comment]
I did note this: -

```text
containerd vendored code has been updating, thus this release will only
work with the following versions of containerd onwards: v1.3.9, v1.4.3,
and v1.5.0.
```

in the `2.2.0-alpha1` [release notes](https://github.com/kata-containers/kata-containers/releases/tag/2.2.0-alpha1) ...

**Comment by davidhay1969** [comment]
So that *appears* to work ...

```text

Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  9s    default-scheduler  Successfully assigned default/nginx-kata to sideling2.fyre.ibm.com
  Normal  Pulling    4s    kubelet            Pulling image "nginx"
  Normal  Pulled     2s    kubelet            Successfully pulled image "nginx" in 1.561940495s
  Normal  Created    2s    kubelet            Created container nginx
  Normal  Started    2s    kubelet            Started container nginx
```

`containerd --version`

```text
containerd github.com/containerd/containerd 1.5.2-0ubuntu1~20.04.2
```

`kata-runtime --version`

```text
kata-runtime  : 2.2.0-alpha1
   commit   : a8a623fb75816b8749f8e0806c83b1f33c76d6bc
   OCI specs: 1.0.2-dev
```
