### ISSUE TITLE
Re-assess OBS packaging and CI distro versions

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#198]
# TL;DR

We need to reassess which distro versions we create [OBS packages](http://download.opensuse.org/repositories/home:/katacontainers:/releases:/) for and run [our CI](http://jenkins.katacontainers.io/).

# Problems

## Packaging

- We cannot produce OBS packages for every version of every current distro on every architecture.

  Why? Too much maintenance and testing required.

## CI

- We do not have resources to run the CI for every version of every current distro on every architecture.

  Why? There are maintenance and financial costs running our current CI system.

# Assumptions

- The CI systems will only be running on distro versions for which we have OBS packages
  (however, the snap packages break this assumption).

- Therefore, under certain circumstances the CI problem is a sub-set of the packaging problem, namely when we use the CI to test OBS packages (for new releases - latest and stable branch versions). But normally, the CI will build components from source rather than relying on OBS packaged versions.

# Minimum Requirements

## CI

Atleast one CI node running the latest version of each major distro.

## Packaging

Provide packages for atleast one current distro version *until distributions start providing Kata packages themselves*.

# Current status

| Distro | Supported versions | Packaged versions | CI versions | Missing Packages | Missing CI |
|-|-|-|-|-|-|
| CentOS | 7, 8 | 7 | 7 | 8 | 8 |
| Debian LTS | 8, 9, 10 | 9, 10 | 10 | 8 | 8, 9 |
| Fedora <sup>[[1]](#footnote-1)</sup> | 31 | 30  | 31 | 32 | 32 |
| openSUSE <sup>[[2]](#footnote-2)</sup> | 15.1 | ? | 15.1 | ? | - |
| RHEL | 7, 8 |  | 7 | 7, 8 | 8 |
| SLES | 12, 15 | 15 | 12, 15 | 12 | - |
| Ubuntu LTS | 16.04, 18.04, 20.04 | 16.04, 18.04 | 16.04, 18.04 | 20.04 <sup>[[3]](#footnote-3)</sup> | 20.04 <sup>[[3]](#footnote-3)</sup> |

Footnotes

- <a name="footnote-1">[1]</a>: Fedora 32 due out 28 April 2020 and Fedora 30 EOL 19 May 2020.
- <a name="footnote-2">[2]</a>: OpenSUSE 15.2 due out in May 2020.
- <a name="footnote-3">[3]</a>: Debatable since we provide snaps!

See:

- http://jenkins.katacontainers.io
- https://github.com/kata-containers/ci/tree/master/jenkins/jobs

## Native distro packaging

- See https://github.com/kata-containers/packaging/wiki/Distro-packaging-status.

# Next steps

The landscape is constantly moving:

- Ubuntu 20.04 LTS was released last week bringing the number of supported LTS releases to three (16.04, 18.04, 20.04).
- F32 is due out this week.
-  OpenSUSE 15.2 due out in May 2020.

Due to the short development cycles for these distro versions (6 months is common), we cannot realistically handle all of them since we cannot run all CI tests on all these versions for each PR.

Hence, we need to concentrate on "LTS or latest".

# Proposals

## CI

- Only test using the latest version of a distros "LTS" version.

  I'm using a loose definition of LTS to include distro versions labelled as "LTS", but also distro versions that are released less frequently than every 6 months (including CentOS, RHEL and SLES).

- If there is no LTS version, use the latest version only.

## Packaging

- Continue to provide snaps and static releases (for cloud environments).

- If a distro supports snaps "out of the box", don't create "native" OBS packages for it - just use the snap!

- Only create OBS packages for the latest LTS version of a distros that provide an LTS release.

## Impact of proposals

What the above means if we agree:

### Changes

- Switch to CentOS 8 and RHEL 8 in the CI.
- Move to packaging CentOS 8 only (note: no RHEL OBS packages).

### Deletions

- Stop CI testing of Ubuntu 16.04 and 18.04.
- Stop CI testing of SLES 12.

- Stop *all* Ubuntu OBS packaging, since we have snap.
- Stop creating Debian 9 OBS packages.
- Stop creating Fedora OBS packages (since Fedora provides them for the packaging aspect and since we build from source for testing on Fedora in the CI).

# Questions

- Should a [Flatpak](https://flathub.org) be created for Kata for parity with the snap package?

  This would bring parity with the snap solution. Are the Fedora folks already doing this?

# Summary

The proposals will:

- Simplify our OBS packaging and CI setups.
- Reduce the amount of "churn" required since the only fast-moving release we'll be chasing is Fedora (but even that may disappear if a flatpak is created?)
- Minimise the load on our CI.
- Reduce the maintenance of both the CI and the cost of maintaining the OBS packaging.

# Alternatives

We might be able to provide OBS packages and / or CI systems for further distro versions if the community can provide additional CI resources and/or packaging expertise.

**Comment by jodh-intel** [comment]
:doughnut: <-- for @grahamwhaley :smile:

**Comment by grahamwhaley** [comment]
quick notes of the top of my head then:
 - yes, I think the snap can be used for Ubuntu, and we can drop OBS. /cc @devimc 
 - iirc, there were feature issues that prevent us from doing a kata flatpak - not enough system perms or similar. again /cc @devimc 
 - I think you don't actually specify why drop RHEL from OBS. I suspect one of two reasons - either, as RHEL are packaging Kata themselves, or RHEL and Centos are similar enough that we don't really have to do both.... can you clarify @jodh-intel

**Comment by devimc** [comment]
> yes, I think the snap can be used for Ubuntu, and we can drop OBS. /cc @devimc

yup, here the list of supported distros https://snapcraft.io/docs/installing-snapd

> iirc, there were feature issues that prevent us from doing a kata flatpak - not enough system perms or similar. again /cc @devimc

I don't have any experience with flatpak, might be redhat folks can guide us here cc @fidencio @slp @c3d @crobinso

**Comment by fidencio** [comment]
Answering here from my **personal** experience, don't take this as a "Red Hat" answer as I have no property at all to talk about flatpkat.

I don't understand much the value of having something as "kata-containers" flatpak'ed. My understanding (probably bogus?) is that flatpak is rather interesting for apps.

As my knowledge is quite limited I'd rather point to someone else here who has been dealing with flatpaks for a considerable amount of time and, more than that, who has dealt with flatpaking an app that depends on QEmu / libvirt. @felipeborges, would you mind giving us some input here?

Also, what kind of info you'd need in order to actually be able to provide us some input here? Last but not least, sorry if I said something wrong and, please, correct me if that's the case.

**Comment by felipeborges** [comment]
There are indeed CLI applications shipped as Flatpaks, although that's not the project's main goal (see Vim for instance).

GNOME Boxes runs libvirtd, qemu, and all inside the flatpak sandbox, but we make sure it doesn't need to escalate any privileges in doing so. Privilege escalation cannot be done in a Flatpak container (especially to perform tasks in the host). For that we have Portals, which are out-of-the-process DBus services that applications talk to in order to perform privileged/host tasks.

I am not familiar with kata-containers, but if it can run unprivileged without requiring any host adjustments, it likely can be Flatpak. Is that the case?

**Comment by devimc** [comment]
> I am not familiar with kata-containers, but if it can run unprivileged without requiring any host adjustments, it likely can be Flatpak. Is that the case?

If we compare snap and flatpak, kata runs without a confinement in the snap, because it needs access to `/dev/{kvm,vhost-net,vhost-vsock}`, so I think privileges are required

**Comment by felipeborges** [comment]
> > I am not familiar with kata-containers, but if it can run unprivileged without requiring any host adjustments, it likely can be Flatpak. Is that the case?
> 
> If we compare snap and flatpak, kata runs without a confinement in the snap, because it needs access to `/dev/{kvm,vhost-net,vhost-vsock}`, so I think privileges are required

Flatpak supports poking holes in the sandbox for filesystem and device access. GNOME Boxes accesses /dev/kvm and /dev/dri, for instance. The issue would be for things that need to be run as root.

**Comment by devimc** [comment]
I guess root is not required for /dev/kvm and /dev/dri because their groups are non-root (kvm and video/lp respectively ?) , but what about the other devices vhost-net and vhost-vsock? also when devicemapper is the graph driver, kata will need access to the devicemapper devices (/dev/dm*) that are created dynamically by the container manager, so kata needs a stainer, not a sandbox

**Comment by chavafg** [comment]
On CI side, we agreed in the Architecture meeting to use latest versions of each distro and only use the 2 latest for Fedora (31, 32) and Ubuntu (18.04 and 20.04). Thanks to @GabyCT who is already working to add support for ubuntu 20.04 and centos 8. Next we will add support for Fedora 32.

For packaging, an idea from @jcvenegas is to create a survey to ask current users if what is their preferred way to install kata (using OBS packages, kata-deploy?) and with this information we could make decisions on what approach we can take for 2.0.

**Comment by jodh-intel** [comment]
@grahamwhaley - Just seen your comments regarding RHEL (https://github.com/kata-containers/kata-containers/issues/198#issuecomment-622438629) and I think there is a bit of confusion here. If you look at the table at the top of this issue, [although OBS supports RHEL](https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets), [we don't currently provide OBS RHEL packages](https://github.com/kata-containers/packaging/issues/510), so there is no change :smile:

**Comment by jodh-intel** [comment]
Closing this issue since:

- We are not providing OBS packages for Kata 2.x - users can install official distro-provided packages: https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs/install#official-packages
- https://github.com/kata-containers/kata-containers/issues/198#issuecomment-624923768 explains the CI distro versions that will be used going forwards.
