### ISSUE TITLE
kata with cloud-hypervisor build from source code may failed with the dirty name (v15.0-213-g8f1404ee-dirty)

### ISSUE THREAD

**Issue by Apokleos** [kata-containers/kata-containers#1991]
The information provided will help us to understand the problem more quickly
so saves time for both of us! :smile:

# Description of problem
1. When I compile cloud-hypervisor with the lastest source code from `https://github.com/cloud-hypervisor/cloud-hypervisor.git` and get a new binary. and its source code version as below:
```
$ git describe --dirty
v15.0-213-g8f1404ee-dirty
$ cargo build 
$ target/debug/cloud-hypervisor --version
cloud-hypervisor v15.0-213-g8f1404ee-dirty
```

2.  I have download the latest kata-static from `https://github.com/kata-containers/kata-containers/releases/download/2.1.0/kata-static-2.1.0-x86_64.tar.xz` 
3. replace the /opt/kata/bin/cloud-hypervisor with version `cloud-hypervisor v15.0-213-g8f1404ee-dirty`
4. execute command as below:
```
# ctr run -t --rm --runtime io.containerd.kata-clh.v2 --device /dev/vfio/109 docker.io/library/ubuntu:20.04.1 ubuntu-clh-debug /bin/bash
ctr: Failed to parse cloud-hypervisor version field. Illegal length: unknown
```
5.  the clh.go `getAvailableVersion()` may not fit cloud-hypervisor's name with dirty info or new naming rule  ,details: https://github.com/cloud-hypervisor/cloud-hypervisor/commit/30a01277655bf943a5ccdab67d9d398b0335d669

# Expected result

when I do `ctr run -t --rm --runtime io.containerd.kata-clh.v2 --device /dev/vfio/109 docker.io/library/ubuntu:20.04.1 ubuntu-clh-debug /bin/bash` will correctly run.

# Actual result
failed with msg: `ctr: Failed to parse cloud-hypervisor version field. Illegal length: unknown`
```
# ctr run -t --rm --runtime io.containerd.kata-clh.v2 --device /dev/vfio/109 docker.io/library/ubuntu:20.04.1 ubuntu-clh-debug /bin/bash
ctr: Failed to parse cloud-hypervisor version field. Illegal length: unknown
```

# My solution
```
func (clh *cloudHypervisor) getAvailableVersion() error {
	clhPath, err := clh.clhPath()
	if err != nil {
		return err
	}

	cmd := exec.Command(clhPath, "--version")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return err
	}

	words := strings.Fields(string(out))
	if len(words) != 2 {
		return errors.New("Failed to parse cloud-hypervisor version response. Illegal length")
	}

	versionSplit := strings.SplitN(words[1], ".", -1)
	if len(versionSplit) < 2 {
		fmt.Printf("versionSplit: %+v", versionSplit)
		return errors.New("Failed to parse cloud-hypervisor version field, fields. Illegal length\n")
	}

	// revision could have aditional commit information separated by '-'
	revisions := strings.SplitN(versionSplit[len(versionSplit) - 1], "-", -1)

	// revisions[0] maybe versionSplit[2] or versionSplit[1]
	versionSplit[len(versionSplit) - 1] = revisions[0]
	revision, err := strconv.ParseUint(revisions[0], 10, 64)
	if err != nil {
		return err
	}

	// Remove 'v' prefix if has one
	versionSplit[0] = strings.TrimLeft(versionSplit[0], "v")
	major, err := strconv.ParseUint(versionSplit[0], 10, 64)
	if err != nil {
		return err
	}

	minor, err := strconv.ParseUint(versionSplit[1], 10, 64)
	if err != nil {
		return err
	}

	// A new naming rule will be used when clh version >= v15.0,
	//https://github.com/cloud-hypervisor/cloud-hypervisor/commit/30a01277655bf943a5ccdab67d9d398b0335d669
	if major >= 15 {
		revision = 0
	}

	clh.version = CloudHypervisorVersion{
		Major:    int(major),
		Minor:    int(minor),
		Revision: int(revision),
	}

	return nil
}
```

**Comment by likebreath** [comment]
@Apokleos Thanks for opening the issue. Yes, I encountered the same issue recently and had to use a similar workaround to make Kata happy with my custom build of cloud-hypervisor. I think this 'limitation' is definitely not preferable, and can be improved/loosed. 

I may miss the context of the rationality behind of having this version check, Any comments/advises? @jodh-intel @jcvenegas @devimc

**Comment by devimc** [comment]
@likebreath clh was not stable with a lot of changes in its API and we depended on experimental features, I guess we can get rid of that check since now it's *"stable"*, right?

**Comment by Apokleos** [comment]
> @Apokleos Thanks for opening the issue. Yes, I encountered the same issue recently and had to use a similar workaround to make Kata happy with my custom build of cloud-hypervisor. I think this 'limitation' is definitely not preferable, and can be improved/loosed.
> 
> I may miss the context of the rationality behind of having this version check, Any comments/advises? @jodh-intel @jcvenegas @devimc

@likebreath Thanks for your reply.  I agree with you.

**Comment by Apokleos** [comment]
> @likebreath clh was not stable with a lot of changes in its API and we depended on experimental features, I guess we can get rid of that check since now it's _"stable"_, right?

Thanks @devimc , checking `stable` will ensure the released kata with stable clh version. But it may also cause the similar problem.
I now have a new doubt that what is the purpose of version checking? for version specification or something else?

**Comment by devimc** [comment]
> I now have a new doubt that what is the purpose of version checking? for version specification or something else?

we don't need that check anymore :smile:

**Comment by Apokleos** [comment]
> > I now have a new doubt that what is the purpose of version checking? for version specification or something else?
> 
> we don't need that check anymore

Thanks @devimc , I want to confirm that the method `func (clh *cloudHypervisor) getAvailableVersion() error {...}` will be removed in future, or somthing else?

**Comment by likebreath** [comment]
>  clh was not stable with a lot of changes in its API and we depended on experimental features, I guess we can get rid of that check since now it's _"stable"_, right?
@devimc Thanks for sharing your thoughts. It makes sense to me that the version check was in place when clh was not "stable" (API wise).

If there is no objections, I will send a PR to remove the version check from the CLH driver (`clh.go`) in Kata. @jcvenegas 
@jodh-intel  @chavafg @amshinde @egernst

**Comment by jodh-intel** [comment]
Thanks @likebreath!
