### ISSUE TITLE
enable power and ubuntu sev amd CI until they are ready?

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#1996]
I have seen that most of the PRs at this repository seem to be failing but most of them are "failing" because we currently have the Power and the sev amd CI failing in each PR. I believe that we should enable these CIs to be trigger in each PR until they are ready to make clearer the environment and easier to detect which PRs are ready to review and to merge. I know that a lot work has been done to include these CIs but I believe that who are in charge on enabling them can create a test PR in this repository and then just trigger the specific CI that they want to test for that test PR  (and not in all the PRs) and see which changes needs to be addressed.
Wdyt @chavafg  @bergwolf @fidencio @bpradipt

**Comment by fidencio** [comment]
Agree!

**Comment by bpradipt** [comment]
Makes sense. We need to do some work on our side to make the CI runs stable on ppc64le.

**Comment by GabyCT** [comment]
@bpradipt changes applied to power ci, to trigger it use `/test-power`

**Comment by GabyCT** [comment]
and for the sev-amd CI , `/test-amd`

**Comment by GabyCT** [comment]
As these CIs will not longer be triggered in each PR, I will close this issue
