### ISSUE TITLE
quickstart for kata-deploy

### ISSUE THREAD

**Issue by pohly** [kata-containers/kata-containers#2005]
# Description of problem

The https://github.com/kata-containers/kata-containers/releases/tag/2.1.0 release notes mention "improvements to kata-deploy, which is the preferred way of deploying the project". I used kata-deploy in the past, but now had problems finding it again.

When searching for kata-deploy with Google, the first hit is the obsolete 
packaging/kata-deploy repo.

The next hit is the medium.com blog article with also out-dated instructions.

Then there is https://hub.docker.com/r/katadocker/kata-deploy. The quick start talks about `kubectl apply -f kata-rbac.yaml` without saying where that file is supposed to come from. One has to guess that the source repository is needed, which doesn't help because it is the obsolete packaging/kata-deploy.

# Expected result

I'd expect to find instructions that actually tell me how to get started :sweat_smile: 

My suggestions:
- Edit the READMEs (top-level and kata-deploy) in kata-containers/packaging with a clear warning that the content is out-dated and link to the replacement.
- In the kata-containers release notes, always link to the "kata-deploy". Right now it links to https://github.com/kata-containers/kata-containers/tree/2.1.0/docs/install, which doesn't mention kata-deploy.
- Replace the local file references in the Docker page with https://github.com/kata-containers/kata-containers/raw/main/tools/packaging/kata-deploy/kata-rbac/base/kata-rbac.yaml and https://github.com/kata-containers/kata-containers/raw/main/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- Explain that "main" should be replaced with a specific release number.
- Fix the source repo link.

**Comment by eadamsintel** [comment]
I would also add on to this issue that the Docker hub description still refers to trusted and untrusted which is an old  way of doing things for containerd.  

Also, and this might deserve its own issue, the `kata-deploy:latest` tag points to a 1.12 image and is 7 months old. If you use `kata-deploy.yaml` as is unmodified it will install an unsupported Kata 1.12 image. You have to actually edit the kata-deploy.yaml file and add in the specific version that you want to install to get the latest releases.

**Comment by fidencio** [comment]
I'm taking this one and will work on making it more visible and updating the tags.

I don't have access to the dockerhub repo, though, and I may need help from someone who has in order to access it.
@chavafg, maybe you can help me here?

**Comment by pohly** [comment]
> Also, and this might deserve its own issue, the kata-deploy:latest tag points to a 1.12 image and is 7 months old. If you use kata-deploy.yaml as is unmodified it will install an unsupported Kata 1.12 image. You have to actually edit the kata-deploy.yaml file and add in the specific version that you want to install to get the latest releases.

So now it is the opposite of what I pointed out when I first used kata-deploy.yaml: at that time, checking out a certain release of "packaging" always installed the latest version instead of the one that was checked out. I think I filed an issue at that time to always ensure that the YAML file gets updated for the tagged release.

This is now a bit harder: you first have to update the YAML file on master with the version of the upcoming release, then create the release. That's how we do it for csi-driver-host-path releases. It has the same issue with YAML files embedded in the source code repo.

**Comment by fidencio** [comment]
> > Also, and this might deserve its own issue, the kata-deploy:latest tag points to a 1.12 image and is 7 months old. If you use kata-deploy.yaml as is unmodified it will install an unsupported Kata 1.12 image. You have to actually edit the kata-deploy.yaml file and add in the specific version that you want to install to get the latest releases.
> 
> So now it is the opposite of what I pointed out when I first used kata-deploy.yaml: at that time, checking out a certain release of "packaging" always installed the latest version instead of the one that was checked out. I think I filed an issue at that time to always ensure that the YAML file gets updated for the tagged release.

I ended up doing that a few months ago in order to ensure a released version would always point to the released content.
However, it caused such issues with folks consuming content from `main`.  We even have an issue open for that, but I never got to actually work on it.

> This is now a bit harder: you first have to update the YAML file on master with the version of the upcoming release, then create the release. That's how we do it for csi-driver-host-path releases. It has the same issue with YAML files embedded in the source code repo.

Yep, we're currently updating that as part of the release scripts, but well, not optimal indeed.

**Comment by pohly** [comment]
> However, it caused such issues with folks consuming content from main.

You could revert to "latest" after tagging or do all releases on a branch. In PMEM-CSI, we branch.

But either way, the underlying question is who you annoy more: actual users who should be using only stable releases, or developers who want "main" + latest.

My opinion is that users should be more important. Life for them should be as easy as possible to avoid mistakes without having to read many instructions, whereas developers should know how the project works and thus can adapt to some additional steps.

**Comment by fidencio** [comment]
Yep, I'll try to get access to the dockerhub later Today and solve the issue with latest pointing to 1.x.

Another crazy idea we had in the past was to always generate a kata-deploy for testing / development versions after each merged PR, and maybe even use that to test things, only changing the bits that changed on each PR.  But that's a material for future future.

**Comment by eadamsintel** [comment]
This is following on to what @pohly said but how hard would it be so that `main` always had `kata-deploy:latest` in the yaml file but every single tag of the repo replaced the `latest` with the tagged version?  If you checked out 2.0.1 of that kata-deploy yaml file then the container image in it would be `kata-deploy:2.0.1`?  That then follows GitHub tags and makes the most sense. People who consume the yaml from main would expect the latest kata container release and people who take a specific tagged version of the repo would get a specific version of Kata.  I am not sure how easy it is to automate this in GitHub.

**Comment by fidencio** [comment]
@eadamsintel, for instance, this is what we have as part of the stable-2.1 branch:
https://github.com/kata-containers/kata-containers/blob/stable-2.1/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml

**Comment by eadamsintel** [comment]
Ah thanks.  That must have changed at some point in the past that I never noticed.  That is really useful.

**Comment by fidencio** [comment]
This was part of https://github.com/kata-containers/kata-containers/issues/1665, fixed by https://github.com/kata-containers/kata-containers/pull/1667

But the other points are still super valid and must be addressed.

**Comment by fidencio** [comment]
Okay, I've gotten access to the repo and in the next few days I'll update the information there.

Another change that I'm doing is also pointing `:latest` to the latest development release (in our case now, 2.2.0-alpha0), and pointing `:stable` to the latest stable release (2.1.1).

Sorry for how long it's taking to get this updated, but we finally will be working on this one.

**Comment by fidencio** [comment]
@pohly, I'm closing this one as we've updated the deployment instructions on both https://quay.io/repository/kata-containers/kata-deploy?tab=info and https://hub.docker.com/r/katadocker/kata-deploy.

And https://github.com/kata-containers/kata-containers/issues/2450 covers the last bit suggested by you.

Please, feel free to re-open the issue in case you notice something is still missing.  Opening a new issue for the missing part is also a valid approach.

**Comment by fidencio** [comment]
Ah, note that I couldn't figure out a way to switch the repo the docker hub points to (the deprecated packaging one) /o\
