### ISSUE TITLE
io.katacontainers.config.hypervisor.memory_offset: must be larger than 32 bit

### ISSUE THREAD

**Issue by pohly** [kata-containers/kata-containers#2006]
**Which feature do you think can be improved?**

Kata Containers and PMEM-CSI can be used together to make PMEM volumes available inside a container (https://intel.github.io/pmem-csi/0.9/docs/design.html#kata-containers-support). It's currently broken (https://github.com/intel/pmem-csi/issues/987) but that'll get addressed.

**How can it be improved?**

`io.katacontainers.config.hypervisor.memory_offset` (https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md) or the corresponding global config must be used to reserve enough of the address space for PMEM.

- Right now, that annotation is limited to uint32 values, i.e. 4GB maximum. This is not useful for real PMEM, which is considerably larger. This basically has to become a uint64.

- Specifying such large numbers as decimals is not useful. Consider accepting a short hand like "400Gi", for example by parsing with https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#ParseQuantity

- Ideally, Kata Containers should figure out that a container uses PMEM and then adapt the offset automatically.

CC @devimc

**Comment by devimc** [comment]
working on this
