### ISSUE TITLE
Add support for host-created EmptyDir

### ISSUE THREAD

**Issue by evanfoster** [kata-containers/kata-containers#2053]
This is a recreation of [this issue](https://github.com/kata-containers/runtime/issues/2518) raised against Kata 1.X. A PR will be inbound shortly.

**Is your feature request related to a problem? Please describe.**

Kubernetes EmptyDirs are sometimes used as a way to share data from the host to a guest. The work done in https://github.com/kata-containers/runtime/pull/1485 drastically improved performance for most use-cases, but broke host->guest sharing of files.

**Describe the solution you'd like**

A flag in the configuration that disables guest-created EmptyDirs, allowing users to fall back to slower, host-created ones.

**Describe alternatives you've considered**

Unfortunately, there aren't really any other good solutions to the problem my org is using EmptyDir to solve. There are multi-tenancy issues with host volumes, and our use-case relies on linking container logs on the host to a logging container in a pod.

**Additional context**

I've already implemented this and my org is running a fork with a disable_guest_empty_dir flag, but I'd like to gauge upstream's interest in this. It's a very small changeset (+42 -11) and would allow folks to use EmptyDir with Kata in this way again.

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

Yes.

**Comment by evanfoster** [comment]
Apologies, testing this change is taking a bit longer than expected. I'll have a PR in tomorrow.

**Comment by c3d** [comment]
@evanfoster Since there is a trade-off that, IMO, depends more on the workload than on the location, have you considered also adding an annotation to configure `disable_host_empty_dir`? That way, you could disable it for a specific workload rather than fro all workloads on a node. It would also be more user friendly, since it would not require deploying a configuration file to all nodes (which requires admin collaboration) just to be able to share files with the host.

**Comment by evanfoster** [comment]
Hey @c3d,

I had attempted to add an annotation previously, but I was unable to figure out a way to do that cleanly. The annotation data wasn't available when setting up the pod sandbox in Kata 1.x, and the volumes were already set up by the time the data was present. I'll take another look now, since it appears that there's been some architectural changes in `containerd-shim-v2/create.go`.
