### ISSUE TITLE
Make sure agent is built and tested with glibc

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/kata-containers#206]
**Is your feature request related to a problem? Please describe.**

Some distros does not support musl, this could be a integration blocker.

**Describe the solution you'd like**
-[ ]Add test cases to build glibc
-[ ] This will make a not static binary so tooling to build the rootfs need to check shared libs linked to the agent binary are added.

**Describe alternatives you've considered**

**Additional context**

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

@amshinde @bergwolf @fidencio

**Comment by bergwolf** [comment]
Will this be an optional feature? I would prefer to using musl built agent (which is smaller and easier to distribute as a static binary) by default.

**Comment by jcvenegas** [comment]
I like musl over glibc, but because some adopeters may not use musl we probaby want to make sure it works with it.  Specifically Fedora does not provide that.
\cc @fidencio

**Comment by fidencio** [comment]
Fedora does provide that, but RHEL / CentOS doesn't. If we want kata to be distro friendly we better ensure things will work properly with what the distros are using by default.
