### ISSUE TITLE
stable-2.1: crio: exit time for the container is not initialized in container status

### ISSUE THREAD

**Issue by littlejawa** [kata-containers/kata-containers#2098]
Need to backport the fix for #2096 

Using Kata with cri-o, when running "crictl inspect [container id]" on a stopped container, the "FinishedAt" field is not set.
When using runc, the same field is properly filled.

This error was found while running the integration tests from cri-o.
Namely: ctr.bats file, test 6 "ctr lifecyle", checks the start and finish time for a container.
With Kata, the test fails when checking the finish time.

**Comment by fidencio** [comment]
Closing this one as the PR has already been merged.
