### ISSUE TITLE
`cargo vendor` fails with duplicate version of netlink-packet-utils

### ISSUE THREAD

**Issue by etrunko** [kata-containers/kata-containers#2111]
Trying to build the latest released version of kata-containers for Fedora, I got the following error while running `cargo vendor`, to generate the vendored code.

```
error: failed to sync

Caused by:
  found duplicate version of package `netlink-packet-utils v0.4.0` vendored from two sources:

  	source 1: registry `https://github.com/rust-lang/crates.io-index`
  	source 2: https://github.com/little-dude/netlink?rev=a9367bc4700496ddebc088110c28f40962923326#a9367bc4

```

Happens with both kata-containers-2.1.1 and 2.2.0-aplha0 releases.

It appears to be caused by commit 9e3349c18e31e57277622046b300e1021eedae8c.

**Comment by etrunko** [comment]
@fidencio has a patch that appears to fix this:

https://paste.centos.org/view/3145d201

**Comment by fidencio** [comment]
> @fidencio has a patch that appears to fix this:
> 
> https://paste.centos.org/view/3145d201

Ooiii!
It's not a patch, it's a quick and dirty workaround to be able to offline vendor the code, I wouldn't add my `Signed-off-by:` on that. :-)

@Tim-Zhang, what's the best approach to take on these cases?

**Comment by fidencio** [comment]
@lifupan, @liubin, may we get some help with this one?

**Comment by liubin** [comment]
hi @etrunko , can you give a try of [this patch](https://github.com/kata-containers/kata-containers/pull/2129/files#diff-ea496d70d6c5b9af96b8df30a08de6e4d8352d88c12f6cdb06d79932137dc058)
