### ISSUE TITLE
osbuilder: Evaluate whether makes sense to keep supporting the centos rootfs

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2140]
This is part of a [bigger effort](https://github.com/kata-containers/tests/issues/3657) to simplify what we support and ensure we actually test what we say we support.

The outcome of this should be:
* Whether we support or not the centos rootfs
* Where do we use the centos rootfs
* Who's the person responsible for maintaining the centos rootfs

All the information will end up going to a Wiki page so we can actually act whenever an issue shows up or an update has to be made.

**Comment by fidencio** [comment]
CentOS image is not supported nor officially used anywhere so far.  However, https://github.com/kata-containers/tests/pull/3658 makes it tested by every single PR running on the CentOS CI.

This currently uses CentOS 7 by default (please, see https://github.com/kata-containers/kata-containers/blob/main/tools/osbuilder/rootfs-builder/centos/config.sh#L8) and it should be updated to use CentOS 8.

Would someone from @kata-containers/redhat volunteer to maintain this one?

Mind that downstream CentOS uses dracut rather than building its own rootfs image.

**Comment by Jakob-Naucke** [comment]
I wonder if there are good reasons to maintain it beside Fedora?
