### ISSUE TITLE
osbuilder: Evaluate whether makes sense to keep supporting the debian rootfs

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2142]
This is part of a [bigger effort](https://github.com/kata-containers/tests/issues/3657) to simplify what we support and ensure we actually test what we say we support.

The outcome of this should be:
* Whether we support or not the debian rootfs
* Where do we use the debian rootfs
* Who's the person responsible for maintaining the debian rootfs

All the information will end up going to a Wiki page so we can actually act whenever an issue shows up or an update has to be made.

**Comment by Jakob-Naucke** [comment]
I wonder if there are good reasons to maintain it beside Ubuntu?

**Comment by fidencio** [comment]
Debian image is not supported nor officially used anywhere so far.  However, https://github.com/kata-containers/tests/pull/3658 makes it tested by every single PR running on the Debian CI.

This currently uses Debian 9.5 by default (please, see https://github.com/kata-containers/kata-containers/blob/7d37fbfdfba05be660b11f2b4d6545dfdfbecd63/tools/osbuilder/rootfs-builder/debian/config.sh#L6-L9) and it should be updated to use latest Debian.

Would someone from the community volunteer to maintain this one?

**Comment by fidencio** [comment]
923e098db61696ee5ec9c35f9a1a8891732025ca removed the debian support.
