### ISSUE TITLE
osbuilder: Evaluate whether makes sense to keep supporting the fedora rootfs

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2143]
This is part of a [bigger effort](https://github.com/kata-containers/tests/issues/3657) to simplify what we support and ensure we actually test what we say we support.

The outcome of this should be:
* Whether we support or not the fedora rootfs
* Where do we use the fedora rootfs
* Who's the person responsible for maintaining the fedora rootfs

All the information will end up going to a Wiki page so we can actually act whenever an issue shows up or an update has to be made.

**Comment by fidencio** [comment]
Debian image is not supported nor officially used anywhere so far.  However, https://github.com/kata-containers/tests/pull/3658 makes it tested by every single PR running on the Debian CI.

This currently uses Debian 9.5 by default (please, see https://github.com/kata-containers/kata-containers/blob/7d37fbfdfba05be660b11f2b4d6545dfdfbecd63/tools/osbuilder/rootfs-builder/debian/config.sh#L6-L9) and it should be updated to use latest Debian.

Would someone from the community volunteer to maintain this one?

**Comment by Jakob-Naucke** [comment]
@fidencio I think you meant to put that in https://github.com/kata-containers/kata-containers/issues/2142 :)
I'd vow for keeping it because Ubuntu is flakey with Podman, see https://github.com/kata-containers/tests/pull/3636#issuecomment-867701599

**Comment by fidencio** [comment]
> @fidencio I think you meant to put that in #2142 :)
> I'd vow for keeping it because Ubuntu is flakey with Podman, see [kata-containers/tests#3636 (comment)](https://github.com/kata-containers/tests/pull/3636#issuecomment-867701599)

Just updated the comment, thanks!
