### ISSUE TITLE
tarball of cri-containerd-release v1.3.7 is gone

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#2158]
13:40:10 Trying to install containerd from static tarball
13:40:35 Download tarball from https://storage.googleapis.com/cri-containerd-release/v1.3.7/cri-containerd-cni-1.3.7-linux-amd64.tar.gz
13:40:35   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
13:40:35                                  Dload  Upload   Total   Spent    Left  Speed
13:40:35 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
13:40:35 curl: (22) The requested URL returned error: 404 
13:40:35 Failed to download tarball from https://storage.googleapis.com/cri-containerd-release/v1.3.7/cri-containerd-cni-1.3.7-linux-amd64.tar.gz
13:40:35 Trying to install containerd from source
13:40:35 error: pathspec 'v1.3.7' did not match any file(s) known to git.
13:40:35 Failed at 44: git checkout "${cri_containerd_tarball_version}"
13:40:35 Failed at 39: ( cd "${GOPATH}/src/${cri_containerd_repo}" >> /dev/null; git fetch; git checkout "${cri_containerd_tarball_version}"; make BUILDTAGS="${BUILD_TAGS:-}" cri-cni-release; tarball_name="cri-containerd-cni-${cri_containerd_version}-${CONTAINERD_OS}-${CONTAIENRD_ARCH}.tar.gz"; sudo tar -xvf "./releases/${tarball_name}" -C / )
13:40:35 ERROR: containerd not installed
13:40:35 Build step 'Execute shell' marked build as failure

see [here](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-initrd-PR/805/console) to find more

@jodh-intel @fidencio

**Comment by MatthieuSarter** [comment]
Additionally, the install from the sources fails ("error: pathspec 'v1.3.7' did not match any file(s) known to git.").

This is because the repository referenced in versions.yaml is containerd/cri, while the v1.3.7 tag is a tag from the containerd/containerd repository.
Switching to containerd/containerd in versions.yaml fixes the second issue, I'm currently testing if it does not break anything else.

**Comment by ariel-adam** [comment]
Closing this bug for now since all of the links above point to invalid locations.
We'd appreciate if you could provide more details and logs in case you would like to reopen it.
