### ISSUE TITLE
agent: Crate tokio was yanked

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#2165]
Found by Cargo Audit, for both agent and agent-ctl

Reported-by: Przemyslaw Roguski <proguski@redhat.com>

Crate:         tokio
Version:       1.6.0
Warning:       yanked
Dependency tree:
tokio 1.6.0
├── ttrpc 0.5.1
│   ├── protocols 0.1.0
│   │   ├── rustjail 0.1.0
│   │   │   └── kata-agent-ctl 0.0.1
│   │   └── kata-agent-ctl 0.0.1
│   └── kata-agent-ctl 0.0.1
├── tokio-vsock 0.3.0
│   └── ttrpc 0.5.1
├── rustjail 0.1.0
└── inotify 0.9.3
   └── rustjail 0.1.0

**Comment by egernst** [comment]
Should we just specify 1.6 instead of 1.6.0, so we can get 1.6.2, or newer?

**Comment by egernst** [comment]
cargo update on master should resolve this issue.
