### ISSUE TITLE
osbuilder: Rootfs Image of ARM CentOS script had a error setting for GPG_KEY_ARCH_URL ENV variable

### ISSUE THREAD

**Issue by YchauWang** [kata-containers/kata-containers#2181]
# Description of problem

There is a error or changed for GPG_KEY_ARCH_URL setting, when I tried to build dev arm rootfs image of [centos](tools/osbuilder/rootfs-builder/centos/config_aarch64.sh).

# Expected result

GPG_KEY_ARCH_URL="http://mirror.centos.org/altarch/7/os/aarch64/RPM-GPG-KEY-CentOS-7"

GPG_KEY_ARCH_FILE="RPM-GPG-KEY-CentOS-7"

# Actual result

GPG_KEY_ARCH_URL="http://mirror.centos.org/altarch/7/os/aarch64/RPM-GPG-KEY-CentOS-7-aarch64"

GPG_KEY_ARCH_FILE="RPM-GPG-KEY-CentOS-7-aarch64"

**Comment by jongwu** [comment]
Hello @YchauWang -, for now kata only support ubuntu on arm64, if you want to use centos, you can raise a PR to fix it.
