### ISSUE TITLE
[ASoC2020] IO throttling at vmm level

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#219]
Description:
The idea is to throttle network and block device IO for kata containers at the vmm level. An example is given at [Block device throttling](https://github.com/kata-containers/runtime/issues/2160) but we would like to do it for both nics and block devices. virtiofs might be optional if time is allowed.

Goal:
1. add support in kata-runtime to let qemu/cloud-hypervisor/firecracker support block device throttling
2. add support in kata-runtime to let qemu/cloud-hypervisor/firecracker support network device throttling
3. define a high level API to expose the above capability
4. [optional] add support for virtiofs to be able to throttle guest IO, and integrate it in kata-runtime

Difficulty level: high

**Comment by Pennyzct** [comment]
Hi @bergwolf 

I've enabled `rate limiter` for kata-containers with firecracker in PR , and it aims to throttling network inbound/outbound throughput. 
The implementation of rate limiter in firecracker is based on `TBF`(Token Bucket Filter), and see more details in [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/rate_limiter/src/lib.rs).
And we have done a few discussion there to whether we should implement similar scheme in other hypervisors, like `qemu`, etc.
Quoting the comments there for better understanding:
> > cc @dagrh @stefanha who might know whether there are similar options in QEMU
> 
> QEMU is usually deployed with vhost_net and network I/O happens in the host kernel. Therefore QEMU has no options for rate limiting network traffic.
> 

And we still talks about enabling **tc tbf filter** in guest for qemu to do the outbound throttling, but it may bring security issue.
> @Pennyzct You mentioned "it needs to be implemented in guest". It is safer to apply restrictions on the host rather than inside the guest. That way more layers of defense need to be compromised before a malicious container can disable rate limiting.
> 
> For example, if you use tc inside the guest then rate limiting can be disabled/bypassed after a container escape inside the sandbox VM. If you use tc on the host then a compromised guest is still rate limited.
> 
> I haven't investigated the details and maybe it's not practical to do it on the host, but that is where restrictions should be enforced when possible.

Not sure the status of cloud hypervisor, but we could bring an issue there to discuss whether we should implement rate limiter??

**Comment by devimc** [comment]
> Not sure the status of cloud hypervisor, but we could bring an issue there to discuss whether we should implement rate limiter??

cc @likebreath @sboeuf

**Comment by sboeuf** [comment]
@rbradford @sameo adding rate limiter to some of our virtio devices sounds like a good idea, especially if Kata Containers will use it.
WDYT?
