### ISSUE TITLE
Remove TravisCI

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#22]
Tracking issue for the removal of TravisCI.

It's been useful, but as we found for Clear Containers, Travis is too limited in its abilities. The main issues being:

- The "[dreaded Travis bug](https://github.com/travis-ci/travis-ci/issues/7830)".

- No VT-x meaning we can only run unit tests.

  Too restrictive: we need to be able to run [all our tests](https://github.com/kata-containers/tests).

Remove the Travis config file from the following repos:

- [ ] agent
- [ ] ksm-throttler
- [ ] osbuilder
- [ ] proxy
- [ ] qemu
- [ ] runtime
- [ ] shim
- [ ] tests

Before removing Travis from a repo, ensure the following:

- Ensure unit tests running and passing under Jenkins

  Known issue: Jenkins doesn't provide `/dev/tty` whereas Travis does.

- Ensure code coverage being reported under Jenkins.

- Ensure no other checks called from `.travis.yml` missing from Jenkins.

**Comment by jodh-intel** [comment]
We now have a new reason to keep Travis: non-`x86_64` architecture support. Hence, I think we can retain the Travis config but only for PPC64le (remove `linux` aka `x86_64`):

```
os:
- linux-ppc64le
```

/cc @egernst, @nitkon, @chavafg.

**Comment by nitkon** [comment]
@jodh-intel : Yes ppc64le needs Travis-CI until we get a ppc64le publically accessible for Jenkins which I don't see happening in the near future.

**Comment by jodh-intel** [comment]
@ydjainopensource - out of interest, what type of CI do you plan to use for zSeries?

**Comment by ydjainopensource** [comment]
@jodh-intel I already have access to 2 CI nodes. I should be able to get Jenkins running on it hopefully by the end of the day.

**Comment by ydjainopensource** [comment]
So Travis isn't really necessary for us

**Comment by nitkon** [comment]
@jodh-intel : IBM Z provides nested virtualization and hence I guess @ydjainopensource will run Jenkins in VM's on Z. That's not the case with IBM Power Systems and hence we will have to provide a bare metal to run the tests on. (For which I do not have a timeline)

**Comment by jodh-intel** [comment]
Great news - thanks for the update guys.

**Comment by jodh-intel** [comment]
We also need to retain Travis for osx / darwin.

**Comment by jodh-intel** [comment]
Just a reminder to those working on the following architectures:

- osx (@raravena80)
- ppc64le (@nitkon)
- zSeries (@ydjainopensource)

... that the public Travis service doesn't support virtualisation afaik. As such, the architectures above will not benefit from any of the tests in our tests repo:

- https://github.com/kata-containers/tests

Hence, nominally, those architectures will only be running unit tests which really isn't ideal given the need to test more thoroughly using different test types and container managers.

As such, I think we need to treat Travis as a (very) temporary solution and aim to migrate to a system (Jenkins, zuul, blah) that has virtualisation support for all our architectures, enabling **all** the tests to run on all architectures.

**Comment by jodh-intel** [comment]
FTR, the "dreaded Travis bug" mentioned on the description seems to have died - I don't recall having seen it for atleast a year.

**Comment by grahamwhaley** [comment]
True, if that is the 'oops I forgot which commit you were on, and stuck to the one that no longer exists', then indeed, not seen that for a long time...

**Comment by jodh-intel** [comment]
A quick update. Since all architectures are we believe all capable of hosting Jenkins CI's, these are the remaining reasons to retain Travis:

- It's fast!

  Could still be useful for a CI "sniff-test" that could be used to trigger a complete CI run.

- It's being used for OSX testing.

  However, the only components which build on OSX currently are proxy and shim so there is no working version of Kata for OSX (we're lacking the crucial runtime and agent builds).


@raravena80 - The OSX initiative is essentially what is tying us to Travis afaics. Could you provide a brief update on thoughts on its future? Are you actively attempting to work on porting the remaining components? Would you be upset if we got rid of Travis? Could you get an OSX Jenkins instance setup somewhere instead?

**Comment by GabyCT** [comment]
@jodh-intel are we still going to do this? Right now, travis is running all the `static-checks`

**Comment by jodh-intel** [comment]
Let's close if @chavafg is happy?

**Comment by chavafg** [comment]
yeah, lets close this for now and revisit in the future if needed (maybe after we have pipelines working?)

**Comment by jodh-intel** [comment]
Sounds good to me.
