### ISSUE TITLE
[ASoC2020] call for project ideas

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#220]
As I mentioned in the last AC meeting, we have subscribed kata-containers for Alibaba Summer of Code. We would need to provide some small projects for students to work on during in the summer. I have walked through our issue list and found some interesting ones:

1. [Support cgroups v2 in the guest](https://github.com/kata-containers/kata-containers/issues/146): The idea is to add cgroups v2 support in the rust-agent
2. [Better IO stream handling](https://github.com/kata-containers/kata-containers/issues/151): The idea is to let CRI daemon (such as containerd) streaming server make direct use of a stdio stream exposed by vmm, so that kata-runtime and host pipes are not involved during the data copy. 
3. [IO throttling at vmm level](https://github.com/kata-containers/kata-containers/issues/219): The idea is to throttle network and block device IO for kata containers at the vmm level. An example is given at [Block device throttling](https://github.com/kata-containers/runtime/issues/2160) but we would like to do it for both nics and block devices. virtiofs might be optional if time is allowed.

Any other ideas people would like to include? Please feel free to comment and share your thoughts.

**Comment by c3d** [comment]
@bergwolf It looks like this is quite stale now. I closed it for now, please feel free to re-open whatever remains to be done? (Unless there is still a pending and relevant ASoC2020 project, in which case I apologize for the early close?)
