### ISSUE TITLE
RO mounts may be simplified

### ISSUE THREAD

**Issue by rapiz1** [kata-containers/kata-containers#2205]
**Which feature do you think can be improved?**
In `virtcontainers`，there's a snippet of code handling the RO mounts from host to the guest, which performs 4 steps as showing below.

https://github.com/kata-containers/kata-containers/blob/69bf7e7519a06467dc8299347c689ac7663955c6/src/runtime/virtcontainers/container.go#L480-L501

Indeed, this solution looks a bit tricky.

**How can it be improved?**

I think a clearer 3-step solution can be used here:

1. make a private ro bind mount at `privateDest` to the mount source 
2. make a bind mount(no need to remount) at `mountDest` to the mount created in step 1
3. umount the private bind mount created in step 1 

In this way, the bind mount in `mounts` will be created in step 2 and propagated to `shared` as well as the `virtiofsd` mount namespace, all with the readonly flag.

No need to fancy binding itself and moving mount. Just plain use of bind mount.

**Additional Information**

Nothing

**Comment by Rapiz1** [comment]
@bergwolf FYI

**Comment by bergwolf** [comment]
@Rapiz1 Looks reasonable. Would you make a PR for it?
