### ISSUE TITLE
Always use initrd for snap builds

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#2218]
Branched out from #2190. Image build (currently) requires privileged containers because of `losetup`, which you cannot do on Snapcraft.

**Comment by diddledani** [comment]
This isn't necessarily accurate. While you cannot `losetup` a file inside the readonly filesystem housing the snap, [snapd supports hooks](https://snapcraft.io/docs/supported-snap-hooks) that may be used to copy the file to `$SNAP_DATA` or `$SNAP_COMMON` on `install` and `post-refresh`. This would then allow you to run `losetup` against the file.

To add the hooks, create a script called `install` and a symlink to it called `post-refresh` in the `snap/hooks` folder (create it :-) ) with a simple `cp` of the rootfs image to the `$SNAP_DATA` or `$SNAP_COMMON` paths. Then amend the configuration file for kata to reference the rootfs file at `/var/snap/kata-containers/common/filename.ext` or `/var/snap/kata-containers/current/filename.ext`.

**Comment by Jakob-Naucke** [comment]
Thank you @diddledani -- I will TAL when I find the time.
