### ISSUE TITLE
Pods do not start when using ConfigPath with containerd v1.4.4 (at least)

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2258]
This issue has been discovered during the release process of kata-containers 2.2.0-alpha1, and then hitting the following issue when testing kata-deploy:
```
+ kubectl apply -f ./tools/packaging/kata-deploy//examples/nginx-deployment-qemu.yaml
NAMESPACE   NAME                            STATUS   ROLES    AGE   VERSION   LABELS
            node/k8s-agentpool-15410489-0   Ready    agent    83s   v1.20.5   agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/cluster=kata-deploy-594ff3a5bd,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-agentpool-15410489-0,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_D4s_v3,storageprofile=managed,storagetier=Premium_LRS,topology.kubernetes.io/region=westus2,topology.kubernetes.io/zone=0
            node/k8s-master-15410489-0      Ready    master   83s   v1.20.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/cluster=kata-deploy-594ff3a5bd,kubernetes.azure.com/role=master,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-master-15410489-0,kubernetes.io/os=linux,kubernetes.io/role=master,node-role.kubernetes.io/master=,node.kubernetes.io/exclude-disruption=true,node.kubernetes.io/exclude-from-external-load-balancers=true,node.kubernetes.io/instance-type=Standard_D2_v2,topology.kubernetes.io/region=westus2,topology.kubernetes.io/zone=0
verify connectivity with a pod using Kata
deployment.apps/nginx-deployment-qemu created
+ sleep 3
+ kubectl wait --timeout=5m --for=condition=Available deployment/nginx-deployment-qemu
error: timed out waiting for the condition on deployments/nginx-deployment-qemu
+ destroy_aks
+ set +x
```

A `kubectl describe pod ...` shows:
```
Events:
  Type     Reason                  Age               From               Message
  ----     ------                  ----              ----               -------
  Normal   Scheduled               29s               default-scheduler  Successfully assigned default/nginx-deployment-qemu-5d97b689f4-r4j4x to k8s-agentpool-16181271-0
  Warning  FailedCreatePodSandBox  5s (x3 over 28s)  kubelet            Failed to create pod sandbox: rpc error: code = NotFound desc = failed to create containerd task: not found
```

This wasn't caught by our CI as we the containerd version used there seems to have it fixed already.  However, this should be worked around on the kata-containers side, if possible

**Comment by egernst** [comment]
Can we share which exact versions are exhibiting this? What version of containerd do we test in CI, versus what w the latest AKS-engine changes we introduced?

I appreciate you working really hard on this challenging release. I just want to make sure the failure is precisely understood; importing v1 feels wrong, and I want to understand if it’s a regression, and what specifically regressed.

**Comment by fidencio** [comment]
> Can we share which exact versions are exhibiting this? What version of containerd do we test in CI, versus what w the latest AKS-engine changes we introduced?

I could reproduce this with 1.4.3, and 1.4.4.  The latest version on AKS is 1.4.4, while our CI runs 1.5.2.

> I appreciate you working really hard on this challenging release. I just want to make sure the failure is precisely understood; importing v1 feels wrong, and I want to understand if it’s a regression, and what specifically regressed.

Let's take a step back.  "importing v1 feels wrong", but this is **exactly** what we've been doing **all the time**, it's not a change.  The change is importing whatever we always imported but from a different location: "github.com/containerd/containerd/pkg/runtimeoptions/v1" (the new location) x "github.com/containerd/cri-containerd/pkg/api/runtimeoptions/v1" (the old location).

Mind, **both are v1**, both would be the "only way" to support ConfigPath passed (as far as I understand from my limited knowledge on containerd).

It seems something (the descriptor?) changed during the move from one repo to another.  From our side, as we can work this around, I don't see why we wouldn't.
