### ISSUE TITLE
Test cases can be simplified

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#2281]
These cases can be simplified by a table-driven style test.

https://github.com/kata-containers/kata-containers/blob/1b71d31121b2826c8ae13c9332b470b839591fdc/src/runtime/virtcontainers/utils/utils_test.go#L425-L478

**Comment by cpmeadors** [comment]
I removed the "good-first-issue" label.  To make this a good first issue, there needs to be some guidance about how to simplify the test cases.  Test cases can be written many different ways.  Once there is some guidance the "good-first-issue" label can be added back.
