### ISSUE TITLE
Add index page for kata monitor

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#2292]
```bash
$ curl localhost:8090
404 page not found
```

Add an index page showing all the sub-commands(pages) will be helpful:

```
$ curl localhost:8090
/metircs: show sandbox metrics
/sandboxes: list all sandboxes
...
```

**Comment by liubin** [comment]
A reference implementation https://github.com/liubin/kata-containers/commit/a45aa0696d55ae2dae1360342d9c9e9fe4eb7c46 .

**Comment by ariel-adam** [comment]
@fgiudici does this also relate to your planned work?

**Comment by liubin** [comment]
related to #2293

**Comment by fgiudici** [comment]
> @fgiudici does this also relate to your planned work?

@ariel-adam: this is not addressed in https://github.com/kata-containers/kata-containers/pull/2233 but is a nice to have and should be easy to port there the @liubin reference implementation (thanks @liubin!).
