### ISSUE TITLE
Create tags for 0.0.1 version

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/kata-containers#23]
In order to exercise  packaging tools for releases  is need to have tags.

Today all the kata projects has the version 0.0.1 lets tag them and allow packing testing.

See:

https://github.com/kata-containers/packaging/issues/15

cc @egernst @erick0z

**Comment by jcvenegas** [comment]
@laijs  @bergwolf @sameo @mcastelino @sboeuf @jodh-intel @grahamwhaley  @devimc   I'll be tagging the repos today

**Comment by jcvenegas** [comment]
Related to https://github.com/kata-containers/kata-containers/issues/15

**Comment by jodh-intel** [comment]
Also related to https://github.com/kata-containers/documentation/issues/32.

**Comment by jodh-intel** [comment]
@jcvenegas - can this be closed now?

**Comment by GabyCT** [comment]
Closing this issue as it was already fixed by https://github.com/kata-containers/runtime/issues/223
