### ISSUE TITLE
kata-deploy: use an up-to-date image as base for our images

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2303]
The current base for kata-deploy images is the `centos/systemd` image, which has not been updated in the past 3 years, see https://hub.docker.com/r/centos/systemd/tags?page=1&ordering=last_updated.

Due to its lack of maintainance, all our images show as high in vulnerabilities according to quay.io https://quay.io/repository/kata-containers/kata-deploy?tag=latest&tab=tags.

In order to avoid giving such a bad impression to our users, let's use a better maintained base image.

**Comment by jodh-intel** [comment]
ouch :) Random thought: sites like the docker hub could purposely slow downloads (a lot) for images that are "very old". If it took > 15 minutes to download such an image, builds would time out and users would get some sort of indication that something was potentially wrong.
