### ISSUE TITLE
stable-2.1 | bump containerd version to the latest patch version

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2350]
As we're approaching a new stable release, let's bump our containerd deps to the latest patch version of the 1.3 release cycle.

**Comment by cmaf** [comment]
@fidencio, based on the comments in https://github.com/kata-containers/kata-containers/pull/2222, since the PR for this issue seems to have been included in https://github.com/kata-containers/kata-containers/pull/2226 I am closing it.
