### ISSUE TITLE
packaging: Improve readability / maintainability of kata-deploy-binaries.sh

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2354]
https://github.com/kata-containers/kata-containers/blob/2d142bc92da091c6d604ba5495772c7e1a9fdd24/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L22-L27

As pointed out by James, it may be worth creating a variable for the common "${repo_root_dir}/tools/packaging/static-build/" prefix to make all these lines shorter / easier to read.

**Comment by converge** [comment]
Hi,
I did this task:
https://github.com/kata-containers/kata-containers/pull/2369
