### ISSUE TITLE
Improve runtime test coverage for 2.0

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#237]
... It's that time again! :smile:

# Summary

Whilst we used to have very high coverage, due to all the awesome features that have been added, the levels have dropped.

This is a tracking issue to discuss how to improve the runtime unit test coverage figures and divide up the work.

# Coverage figures

This is just a snapshot but gives a good indication of the status (just look at the colours ;-)

| Filename | Coverage colour | Coverage (%) |
|-|-|-|
| [`cli/console.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/console.go) | :green_circle: | 89.2 |
| [`cli/create.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/create.go) | :green_circle: | 93.2 |
| [`cli/delete.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/delete.go) | :green_circle: | 97.3 |
| [`cli/events.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/events.go) | :orange_circle: | 44.2 |
| [`cli/exec.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/exec.go) | :green_circle: | 90.9 |
| [`cli/exit.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/exit.go) | :green_circle: | 100.0 |
| [`cli/factory.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/factory.go) | :orange_circle: | 32.3 |
| [`cli/kata-check.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/kata-check.go) | :green_circle: | 84.2 |
| [`cli/kata-check_amd64.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/kata-check_amd64.go) | :orange_circle: | 35.7 |
| [`cli/kata-env.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/kata-env.go) | :green_circle: | 95.9 |
| [`cli/kata-overhead.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/kata-overhead.go) | :red_circle: | 0.0 |
| [`cli/kill.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/kill.go) | :green_circle: | 94.6 |
| [`cli/list.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/list.go) | :green_circle: | 89.7 |
| [`cli/main.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/main.go) | :yellow_circle: | 76.7 |
| [`cli/network.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/network.go) | :yellow_circle: | 76.6 |
| [`cli/oci.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/oci.go) | :green_circle: | 92.1 |
| [`cli/pause.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/pause.go) | :green_circle: | 95.8 |
| [`cli/ps.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/ps.go) | :green_circle: | 86.1 |
| [`cli/run.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/run.go) | :green_circle: | 90.3 |
| [`cli/spec.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/spec.go) | :yellow_circle: | 68.0 |
| [`cli/start.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/start.go) | :green_circle: | 93.2 |
| [`cli/state.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/state.go) | :green_circle: | 90.5 |
| [`cli/update.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/update.go) | :green_circle: | 95.3 |
| [`cli/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/utils.go) | :green_circle: | 94.6 |
| [`cli/utils_arch_base.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/utils_arch_base.go) | :green_circle: | 100.0 |
| [`cli/version.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/cli/version.go) | :green_circle: | 85.7 |
| [`containerd-shim-v2/container.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/container.go) | :green_circle: | 100.0 |
| [`containerd-shim-v2/create.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/create.go) | :yellow_circle: | 61.5 |
| [`containerd-shim-v2/delete.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/delete.go) | :red_circle: | 0.0 |
| [`containerd-shim-v2/errors.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/errors.go) | :green_circle: | 100.0 |
| [`containerd-shim-v2/exec.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/exec.go) | :red_circle: | 26.5 |
| [`containerd-shim-v2/metrics.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/metrics.go) | :red_circle: | 16.7 |
| [`containerd-shim-v2/service.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/service.go) | :red_circle: | 17.7 |
| [`containerd-shim-v2/start.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/start.go) | :orange_circle: | 36.7 |
| [`containerd-shim-v2/stream.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/stream.go) | :orange_circle: | 35.7 |
| [`containerd-shim-v2/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/utils.go) | :red_circle: | 29.4 |
| [`containerd-shim-v2/wait.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/wait.go) | :orange_circle: | 41.4 |
| [`netmon/netmon.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/netmon/netmon.go) | :orange_circle: | 54.4 |
| [`pkg/katatestutils/constraints.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katatestutils/constraints.go) | :green_circle: | 90.0 |
| [`pkg/katatestutils/constraints_api.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katatestutils/constraints_api.go) | :green_circle: | 94.1 |
| [`pkg/katatestutils/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katatestutils/utils.go) | :red_circle: | 0.0 |
| [`pkg/katautils/config.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/config.go) | :yellow_circle: | 73.1 |
| [`pkg/katautils/container_engine.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/container_engine.go) | :yellow_circle: | 73.1 |
| [`pkg/katautils/create.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/create.go) | :orange_circle: | 55.6 |
| [`pkg/katautils/hook.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/hook.go) | :green_circle: | 90.9 |
| [`pkg/katautils/logger.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/logger.go) | :green_circle: | 83.3 |
| [`pkg/katautils/network.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/network.go) | :green_circle: | 84.3 |
| [`pkg/katautils/oci.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/oci.go) | :green_circle: | 81.6 |
| [`pkg/katautils/tracing.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/tracing.go) | :red_circle: | 21.7 |
| [`pkg/katautils/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/katautils/utils.go) | :yellow_circle: | 75.0 |
| [`pkg/signals/signals.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/pkg/signals/signals.go) | :yellow_circle: | 60.0 |
| [`virtcontainers/acrn.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/acrn.go) | :orange_circle: | 34.2 |
| [`virtcontainers/acrn_arch_base.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/acrn_arch_base.go) | :red_circle: | 29.1 |
| [`virtcontainers/agent.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/agent.go) | :green_circle: | 95.5 |
| [`virtcontainers/api.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/api.go) | :yellow_circle: | 73.5 |
| [`virtcontainers/bridgedmacvlan_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/bridgedmacvlan_endpoint.go) | :red_circle: | 21.2 |
| [`virtcontainers/cgroups.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/cgroups.go) | :green_circle: | 85.7 |
| [`virtcontainers/clh.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/clh.go) | :orange_circle: | 42.5 |
| [`virtcontainers/container.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/container.go) | :orange_circle: | 54.0 |
| [`virtcontainers/device/config/config.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/config/config.go) | :red_circle: | 23.1 |
| [`virtcontainers/device/config/pmem.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/config/pmem.go) | :orange_circle: | 40.0 |
| [`virtcontainers/device/drivers/block.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/block.go) | :red_circle: | 0.0 |
| [`virtcontainers/device/drivers/generic.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/generic.go) | :orange_circle: | 34.1 |
| [`virtcontainers/device/drivers/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/utils.go) | :red_circle: | 19.0 |
| [`virtcontainers/device/drivers/vfio.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/vfio.go) | :red_circle: | 12.9 |
| [`virtcontainers/device/drivers/vhost_user_blk.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/vhost_user_blk.go) | :red_circle: | 0.0 |
| [`virtcontainers/device/drivers/vhost_user_fs.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/vhost_user_fs.go) | :red_circle: | 0.0 |
| [`virtcontainers/device/drivers/vhost_user_net.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/vhost_user_net.go) | :red_circle: | 0.0 |
| [`virtcontainers/device/drivers/vhost_user_scsi.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/drivers/vhost_user_scsi.go) | :red_circle: | 0.0 |
| [`virtcontainers/device/manager/manager.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/manager/manager.go) | :yellow_circle: | 66.7 |
| [`virtcontainers/device/manager/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/device/manager/utils.go) | :orange_circle: | 59.1 |
| [`virtcontainers/endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/endpoint.go) | :yellow_circle: | 63.5 |
| [`virtcontainers/experimental/experimental.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/experimental/experimental.go) | :yellow_circle: | 66.7 |
| [`virtcontainers/factory/cache/cache.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/factory/cache/cache.go) | :yellow_circle: | 76.1 |
| [`virtcontainers/factory/direct/direct.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/factory/direct/direct.go) | :yellow_circle: | 63.6 |
| [`virtcontainers/factory/factory.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/factory/factory.go) | :green_circle: | 81.6 |
| [`virtcontainers/factory/template/template.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/factory/template/template.go) | :yellow_circle: | 72.5 |
| [`virtcontainers/fc.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/fc.go) | :red_circle: | 1.9 |
| [`virtcontainers/hypervisor.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/hypervisor.go) | :green_circle: | 80.5 |
| [`virtcontainers/implementation.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/implementation.go) | :red_circle: | 0.0 |
| [`virtcontainers/iostream.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/iostream.go) | :green_circle: | 100.0 |
| [`virtcontainers/ipvlan_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/ipvlan_endpoint.go) | :red_circle: | 20.6 |
| [`virtcontainers/kata_agent.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/kata_agent.go) | :yellow_circle: | 60.7 |
| [`virtcontainers/kata_builtin_proxy.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/kata_builtin_proxy.go) | :green_circle: | 83.3 |
| [`virtcontainers/kata_builtin_shim.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/kata_builtin_shim.go) | :red_circle: | 0.0 |
| [`virtcontainers/kata_proxy.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/kata_proxy.go) | :yellow_circle: | 76.5 |
| [`virtcontainers/kata_shim.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/kata_shim.go) | :yellow_circle: | 73.9 |
| [`virtcontainers/macvtap_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/macvtap_endpoint.go) | :red_circle: | 14.8 |
| [`virtcontainers/mock_hypervisor.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/mock_hypervisor.go) | :green_circle: | 87.9 |
| [`virtcontainers/monitor.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/monitor.go) | :yellow_circle: | 76.0 |
| [`virtcontainers/mount.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/mount.go) | :green_circle: | 80.0 |
| [`virtcontainers/netmon.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/netmon.go) | :yellow_circle: | 70.4 |
| [`virtcontainers/network.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/network.go) | :orange_circle: | 46.9 |
| [`virtcontainers/noop_agent.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/noop_agent.go) | :green_circle: | 90.5 |
| [`virtcontainers/noop_proxy.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/noop_proxy.go) | :green_circle: | 100.0 |
| [`virtcontainers/noop_shim.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/noop_shim.go) | :green_circle: | 100.0 |
| [`virtcontainers/nsenter.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/nsenter.go) | :green_circle: | 100.0 |
| [`virtcontainers/persist.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/persist.go) | :yellow_circle: | 78.9 |
| [`virtcontainers/persist/fs/fs.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/persist/fs/fs.go) | :yellow_circle: | 72.2 |
| [`virtcontainers/persist/fs/mockfs.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/persist/fs/mockfs.go) | :yellow_circle: | 61.5 |
| [`virtcontainers/persist/fs/rootlessfs.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/persist/fs/rootlessfs.go) | :red_circle: | 0.0 |
| [`virtcontainers/persist/manager.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/persist/manager.go) | :yellow_circle: | 76.5 |
| [`virtcontainers/physical_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/physical_endpoint.go) | :red_circle: | 24.2 |
| [`virtcontainers/pkg/cgroups/manager.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/cgroups/manager.go) | :orange_circle: | 39.1 |
| [`virtcontainers/pkg/cgroups/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/cgroups/utils.go) | :green_circle: | 93.3 |
| [`virtcontainers/pkg/compatoci/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/compatoci/utils.go) | :orange_circle: | 51.1 |
| [`virtcontainers/pkg/nsenter/nsenter.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/nsenter/nsenter.go) | :green_circle: | 94.6 |
| [`virtcontainers/pkg/oci/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/oci/utils.go) | :green_circle: | 82.3 |
| [`virtcontainers/pkg/rootless/rootless.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/rootless/rootless.go) | :red_circle: | 15.9 |
| [`virtcontainers/pkg/uuid/uuid.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/uuid/uuid.go) | :green_circle: | 87.5 |
| [`virtcontainers/pkg/vcmock/container.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/vcmock/container.go) | :red_circle: | 0.0 |
| [`virtcontainers/pkg/vcmock/mock.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/vcmock/mock.go) | :green_circle: | 86.4 |
| [`virtcontainers/pkg/vcmock/sandbox.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/vcmock/sandbox.go) | :red_circle: | 0.0 |
| [`virtcontainers/pkg/vcmock/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/pkg/vcmock/utils.go) | :green_circle: | 100.0 |
| [`virtcontainers/proxy.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/proxy.go) | :yellow_circle: | 74.7 |
| [`virtcontainers/qemu.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/qemu.go) | :red_circle: | 25.6 |
| [`virtcontainers/qemu_amd64.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/qemu_amd64.go) | :green_circle: | 100.0 |
| [`virtcontainers/qemu_arch_base.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/qemu_arch_base.go) | :yellow_circle: | 77.3 |
| [`virtcontainers/sandbox.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/sandbox.go) | :yellow_circle: | 69.4 |
| [`virtcontainers/sandboxlist.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/sandboxlist.go) | :green_circle: | 93.8 |
| [`virtcontainers/shim.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/shim.go) | :green_circle: | 81.1 |
| [`virtcontainers/store/backend.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/store/backend.go) | :yellow_circle: | 66.7 |
| [`virtcontainers/store/filesystem_backend.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/store/filesystem_backend.go) | :yellow_circle: | 66.2 |
| [`virtcontainers/store/manager.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/store/manager.go) | :orange_circle: | 46.3 |
| [`virtcontainers/store/vc.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/store/vc.go) | :orange_circle: | 35.9 |
| [`virtcontainers/syscall.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/syscall.go) | :green_circle: | 92.9 |
| [`virtcontainers/tap_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/tap_endpoint.go) | :red_circle: | 2.7 |
| [`virtcontainers/tuntap_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/tuntap_endpoint.go) | :red_circle: | 0.0 |
| [`virtcontainers/types.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/types.go) | :green_circle: | 100.0 |
| [`virtcontainers/types/asset.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/types/asset.go) | :orange_circle: | 59.3 |
| [`virtcontainers/types/bridges.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/types/bridges.go) | :orange_circle: | 51.9 |
| [`virtcontainers/types/capabilities.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/types/capabilities.go) | :yellow_circle: | 75.0 |
| [`virtcontainers/types/container.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/types/container.go) | :red_circle: | 0.0 |
| [`virtcontainers/types/sandbox.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/types/sandbox.go) | :red_circle: | 0.0 |
| [`virtcontainers/utils/compare.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/utils/compare.go) | :red_circle: | 0.0 |
| [`virtcontainers/utils/proc_linux.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/utils/proc_linux.go) | :red_circle: | 0.0 |
| [`virtcontainers/utils/utils.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/utils/utils.go) | :yellow_circle: | 66.7 |
| [`virtcontainers/utils/utils_linux.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/utils/utils_linux.go) | :yellow_circle: | 74.4 |
| [`virtcontainers/utils/utils_linux_generic.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/utils/utils_linux_generic.go) | :green_circle: | 100.0 |
| [`virtcontainers/veth_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/veth_endpoint.go) | :red_circle: | 21.3 |
| [`virtcontainers/vhostuser_endpoint.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/vhostuser_endpoint.go) | :orange_circle: | 50.0 |
| [`virtcontainers/virtiofsd.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/virtiofsd.go) | :orange_circle: | 45.1 |
| [`virtcontainers/vm.go`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/vm.go) | :orange_circle: | 54.4 |

Key:
 - :green_circle:: coverage >= 80%
 - :yellow_circle:: 60% >= coverage < 80%
 - :orange_circle:: 30% >= coverage < 60%
 - :red_circle:: coverage < 30%

> **Note:**
>
> These figures apply to the [`2.0-dev`](https://github.com/kata-containers/kata-containers/tree/2.0-dev) branch, which is where the Kata 2.0 development is happening.

# Areas of importance

- The `sandbox.go` and `container.go` file: these are fundamentally important.
- The individual hypervisor files (`acrn.go`, `clh.go`, `fc.go`, `qemu.go`).
- virtcontainers `persist` package.
- virtcontainers `devices` package.
- virtcontainers `rootless`.

# How to help

If you'd like to be involved in improving the unit tests, take a look at the doc below then let us know!

- https://github.com/kata-containers/tests/blob/master/Unit-Test-Advice.md

# Process

We need to be aware that changes to the runtime need to be fixed in **two** locations:

| Repo | Description |
|-|-|
| https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime | Kata 2.0 version of runtime |
| https://github.com/kata-containers/runtime | Kata 1.x.y version of runtime |

# Considerations

For 2.0, we are planning to simplify and refine. Hence, before writing new unit tests in the 2.0 repo, we need to consider carefully whether the feature the tests will exercise is needed for 2.0 or can be removed [*].

----

[*] - Deleting code is good: should help improve overall test coverage figures and reduces potential attack surface :smile:

**Comment by jodh-intel** [comment]
Issues raised for individual code areas. These issues have been added to the Kata 2.0 GitHub project:

- https://github.com/kata-containers/kata-containers/projects/2

**Comment by jensfr** [comment]
I could take some of these. Would #267 be good to start with?

**Comment by cmaf** [comment]
virtcontainers/types tests were added with the following:

- virtcontainers/types/bridges.go, #423 
- virtcontainers/types/asset.go, #425 
- virtcontainers/types/capabilities.go, #429 
- virtcontainers/types/sandbox.go, #450 
- virtcontainers/types/container.go, #452 
- virtcontainers/utils/utils.go, #504
