### ISSUE TITLE
Error when running $EDITOR /etc/kata-containers/configuration.toml with snap install

### ISSUE THREAD

**Issue by edwardchang0112** [kata-containers/kata-containers#2371]
Run 
```
$EDITOR /etc/kata-containers/configuration.toml
```
shows errors
```
/etc/kata-containers/configuration.toml: line 13: [hypervisor.qemu]: command not found
/etc/kata-containers/configuration.toml: line 14: path: command not found
/etc/kata-containers/configuration.toml: line 15: kernel: command not found
/etc/kata-containers/configuration.toml: line 16: initrd: command not found
/etc/kata-containers/configuration.toml: line 17: machine_type: command not found
/etc/kata-containers/configuration.toml: line 29: kernel_params: command not found
/etc/kata-containers/configuration.toml: line 33: firmware: command not found
/etc/kata-containers/configuration.toml: line 45: default_vcpus: command not found
/etc/kata-containers/configuration.toml: line 61: default_maxvcpus: command not found
/etc/kata-containers/configuration.toml: line 73: default_bridges: command not found
/etc/kata-containers/configuration.toml: line 77: default_memory: command not found
/etc/kata-containers/configuration.toml: line 103: disable_block_device_use: command not found
/etc/kata-containers/configuration.toml: line 108: shared_fs: command not found
/etc/kata-containers/configuration.toml: line 111: virtio_fs_daemon: command not found
/etc/kata-containers/configuration.toml: line 114: virtio_fs_cache_size: command not found
/etc/kata-containers/configuration.toml: line 122: virtio_fs_extra_args: command not found
/etc/kata-containers/configuration.toml: line 137: virtio_fs_cache: command not found
/etc/kata-containers/configuration.toml: line 142: block_device_driver: command not found
/etc/kata-containers/configuration.toml: line 162: enable_iothreads: command not found
/etc/kata-containers/configuration.toml: line 184: enable_vhost_user_store: command not found
/etc/kata-containers/configuration.toml: line 190: vhost_user_store_path: command not found
/etc/kata-containers/configuration.toml: line 277: [factory]: command not found
/etc/kata-containers/configuration.toml: line 320: [proxy.kata]: command not found
/etc/kata-containers/configuration.toml: line 321: path: command not found
/etc/kata-containers/configuration.toml: line 327: [shim.kata]: command not found
/etc/kata-containers/configuration.toml: line 328: path: command not found
/etc/kata-containers/configuration.toml: line 345: [agent.kata]: command not found
/etc/kata-containers/configuration.toml: line 385: [netmon]: command not found
/etc/kata-containers/configuration.toml: line 394: path: command not found
/etc/kata-containers/configuration.toml: line 400: [runtime]: command not found

```
Anyone had experienced on this issue? Please share some advise with me!

**Comment by devimc** [comment]
Hi @edwardchang0112 , did you follow these instructions https://github.com/kata-containers/kata-containers/blob/main/docs/install/snap-installation-guide.md#configure-kata-containers ?

**Comment by edwardchang0112** [comment]
> Hi @edwardchang0112 , did you follow these instructions https://github.com/kata-containers/kata-containers/blob/main/docs/install/snap-installation-guide.md#configure-kata-containers ?

Hi @devimc,
Yes, I followed this instruction. I tried this on NVIDIA NX (which ic arm64 based), could that be a problem?

**Comment by devimc** [comment]
ohh you are using arm, snap for arm has not been updated for long time

cc @jongwu

**Comment by edwardchang0112** [comment]
> Thanks @devimc -, I will fix it soon. @edwardchang0112 wait for me a day or two, I will give you at least a workaround.

Hi @jongwu, 

Thanks for your reply. Sure! Look forward to the solution! Please also share all the procedures that can actually correctly run on arm64, really need that! Thanks!

**Comment by fidencio** [comment]
So, wait a minute, I guess the error you're getting has not much to do with kata-containers' snap working well on ARM or not.
What's the output of `echo $EDITOR`?

**Comment by edwardchang0112** [comment]
> So, wait a minute, I guess the error you're getting has not much to do with kata-containers' snap working well on ARM or not.
> What's the output of `echo $EDITOR`?

Hi @fidencio, 
The machine is in my office, I will go to check ```echo $EDITOR``` tomorrow or the day after tomorrow. What should be the result of ```echo $EDITOR``` ? Could you share an example? Then I can go to check in the following 2 days. Really appreciated!

**Comment by fidencio** [comment]
It should point to some text editor:
```
fidencio@quino ~ $ echo $EDITOR
vim
```

**Comment by jongwu** [comment]
Thanks @fidencio -, it's not an issue @edwardchang0112.  `$EDITOR /etc/kata-containers/configuration.toml` is just used for opening and editing the config file.

**Comment by edwardchang0112** [comment]
> Thanks @fidencio -, it's not an issue @edwardchang0112. `$EDITOR /etc/kata-containers/configuration.toml` is just used for opening and editing the config file.

@jongwu, 
Thanks for your reply.
After following the rest step in https://github.com/kata-containers/kata-containers/blob/main/docs/install/snap-installation-guide.md#configure-kata-containers I cannot correctly run ````kata-runtime check```
```
/etc/kata-containers/configuration.toml: line 13: [hypervisor.qemu]: command not found /etc/kata-containers/configuration.toml: line 14: path: command not found /etc/kata-containers/configuration.toml: line 15: kernel: command not found /etc/kata-containers/configuration.toml: line 16: initrd: command not found /etc/kata-containers/configuration.toml: line 17: machine_type: command not found /etc/kata-containers/configuration.toml: line 29: kernel_params: command not found /etc/kata-containers/configuration.toml: line 33: firmware: command not found /etc/kata-containers/configuration.toml: line 45: default_vcpus: command not found
```
Could you successfully run ```kata-runtime check``` on arm64? what are the steps should be? Is that possible to share the procedures with me? THX!

**Comment by jongwu** [comment]
hello @eadamsintel -, it seems that the path(e.g. qemu binary) is not set correctly in '/etc/kata-containers/configuration.toml'. please check for that. The default configuration file will give you a default path but it maybe not match with your host.

**Comment by edwardchang0112** [comment]
> hello @eadamsintel -, it seems that the path(e.g. qemu binary) is not set correctly in '/etc/kata-containers/configuration.toml'. please check for that. The default configuration file will give you a default path but it maybe not match with your host.

@jongwu ,
Can I directly change the PATH in configuration.toml? And How can I check what is the PATH of qemu binary?

**Comment by jongwu** [comment]
@edwardchang0112 -, yes, you can change the "path" directly. You can get the "path", e.g. qemu, by running "which qemu-system-aarch64" if you have installed qemu in your host.
But I wonder why your configuration path is not correct. As snap will handle all of the installation work accordingly. all of the binaries will be put under /snap/kata-containers and the "path" in configuration file will point to that. Please print your configuration file here and check the related path under /snap/kata-containers.

**Comment by c3d** [comment]
@jongwu Assigned to you since you said you would fix it.

**Comment by edwardchang0112** [comment]
> @edwardchang0112 -, yes, you can change the "path" directly. You can get the "path", e.g. qemu, by running "which qemu-system-aarch64" if you have installed qemu in your host.
> But I wonder why your configuration path is not correct. As snap will handle all of the installation work accordingly. all of the binaries will be put under /snap/kata-containers and the "path" in configuration file will point to that. Please print your configuration file here and check the related path under /snap/kata-containers.

I just checked the my /etc/kata-container/configuration.toml
```
[hypervisor.qemu]
path = "/snap/kata-containers/current/usr/bin/qemu-system-aarch64"
kernel = "/snap/kata-containers/current/usr/share/kata-containers/vmlinuz.container"
initrd = "/snap/kata-containers/current/usr/share/kata-containers/kata-containers-initrd.img"
machine_type = "virt"
```
then I checked the qemu-system-aarch64 by ```which qemu-system-aarch64``` and there is nothing returned... So I think I need to install qemu-system-aarch64 first. Is that right?

**Comment by edwardchang0112** [comment]
> @edwardchang0112 -, yes, you can change the "path" directly. You can get the "path", e.g. qemu, by running "which qemu-system-aarch64" if you have installed qemu in your host.
> But I wonder why your configuration path is not correct. As snap will handle all of the installation work accordingly. all of the binaries will be put under /snap/kata-containers and the "path" in configuration file will point to that. Please print your configuration file here and check the related path under /snap/kata-containers.

@jongwu 
OH! However, when I checked  
```
root@NX-desktop:/snap/kata-containers/current/usr/bin# ls
containerd-shim-kata-v2  kata-runtime
kata-collect-data.sh     qemu-system-aarch64
```
There exists "qemu-system-aarch64"!

**Comment by edwardchang0112** [comment]
> @edwardchang0112 -, yes, you can change the "path" directly. You can get the "path", e.g. qemu, by running "which qemu-system-aarch64" if you have installed qemu in your host.
> But I wonder why your configuration path is not correct. As snap will handle all of the installation work accordingly. all of the binaries will be put under /snap/kata-containers and the "path" in configuration file will point to that. Please print your configuration file here and check the related path under /snap/kata-containers.

@jongwu 

But after checking on all directories in configuration.toml, I found that some of them are "not" in the directories that it shows:
1. virtio_fs_daemon = "/snap/kata-containers/current/usr/bin/virtiofsd"
2. vhost_user_store_path = "/var/run/kata-containers/vhost-user"

Where can I find the above 2 missing files?

**Comment by jongwu** [comment]
Hello @edwardchang0112 -, don't care about the "vhost_user_store_path", it will be created dynamically. 
for "virtio_fs_daemon", you can just comment it out. The kata version installed by snap is too old and does not support virtio-fs. Thus, set "shared_fs" to "virtio-9p". 
I'm working on snap build on arm64, so, I hope we can install the latest kata on arm using snap soon.

**Comment by edwardchang0112** [comment]
> Hello @edwardchang0112 -, don't care about the "vhost_user_store_path", it will be created dynamically.
> for "virtio_fs_daemon", you can just comment it out. The kata version installed by snap is too old and does not support virtio-fs. Thus, set "shared_fs" to "virtio-9p".
> I'm working on snap build on arm64, so, I hope we can install the latest kata on arm using snap soon.

OK, looking forward to the update! Hope we can successfully install kata on arm and use kata-runtime as well! Already stuck on this issue for couples of days... Hope it can be solved in these days! Really appreciated to your support!!

**Comment by edwardchang0112** [comment]
> Hello @edwardchang0112 -, don't care about the "vhost_user_store_path", it will be created dynamically.
> for "virtio_fs_daemon", you can just comment it out. The kata version installed by snap is too old and does not support virtio-fs. Thus, set "shared_fs" to "virtio-9p".
> I'm working on snap build on arm64, so, I hope we can install the latest kata on arm using snap soon.

@jongwu 
Any update for kata on arm?

**Comment by jongwu** [comment]
@edwardchang0112 -, can you share your email address here or connect me via email jianyong.wu@arm.com?

**Comment by edwardchang0112** [comment]
> @edwardchang0112 -, can you share your email address here or connect me via email [jianyong.wu@arm.com](mailto:jianyong.wu@arm.com)?

OK, my email is edward.ee05g@nctu.edu.tw , and I have already sent you an email, please check your mailbox.
