### ISSUE TITLE
firecracker k8s pod never terminates when running jailed

### ISSUE THREAD

**Issue by ananos** [kata-containers/kata-containers#2387]
@jrieck1991 reported having issues when terminating a pod in k8s using kata-fc.

we tested the issue in versions v2.0.0, v2.1.0-rc0, v2.1.0-alpha0 and the latest master (using firecracker v0.21.1 and v0.23.1).

It seems the error is related to the relative path passed to the hotplug remove function which does not differentiate the jailed from the non-jailed case.

The error reported when enabling debug in the FC `logs.fifo`:
```
[c28fb7aeab19d0b0f317cab3c1c430dc] The API server received a Patch request on "/drives/drive_1" with body "{\"drive_id\":\"drive_1\",\"path_on_host\":\"/run/vc/firecracker/c28fb7aeab19d0b0f317cab3c1c430dc/root/drive_1\"}\n".
[c28fb7aeab19d0b0f317cab3c1c430dc] Received Error. Status code: 400 Bad Request. Message: Cannot open block device. Invalid permission/path.
```
and in the kata logs:
```
kata[3869640]: level=error msg="Failed to unplug block device" error="[PATCH /drives/{drive_id}][400] patchGuestDriveByIdBadRequest  &{FaultMessage:Cannot open block device. Invalid permission/path.}" pid=3869640 sandbox=c28fb7aeab19d0b0f317cab3c1c430dc08746747e7988d23bdaea01773d77c6e source=virtcontainers subsystem=device
kata[3869640]: " level=warning msg="stop container failed" container=3fb84655f124951ba0407259928140e252c245d4b76ce76f41dac78c4fff1178 error="[PATCH /drives/{drive_id}][400] patchGuestDriveByIdBadRequest  &{FaultMessage:Cannot open block device. Invalid permission/path.}" pid=3869640 sandbox=c28fb7aeab19d0b0f317cab3c1c430dc08746747e7988d23bdaea01773d77c6e source=containerd-kata-shim-v2
```

It seems that `hotplugBlockDevice` needs to follow the same principle for removing the device as for adding the device (strip the preceding `jailerRoot` when running with the jailer: https://github.com/kata-containers/kata-containers/blob/03325f0612b384b821d02b40921369bfcbd71646/src/runtime/virtcontainers/fc.go#L1058).

**Comment by fidencio** [comment]
While taking a look at http://jenkins.katacontainers.io/job/kata-containers-2.0-firecracker-ubuntu-PR/ I've just noticed that it's been using the `master` branch as its entrypoint.
```
#!/bin/bash

set -e

export DEBUG=true
export KATA_HYPERVISOR="firecracker"
export CI="true"
export CI_JOB="FIRECRACKER"
export SHIMV2_TEST="true"

curl -OL https://raw.githubusercontent.com/kata-containers/tests/master/.ci/ci_entry_point.sh
bash -x ci_entry_point.sh "${GIT_URL}"
```

I've switched that to `main` and I am going to retrigger the tests here.
