### ISSUE TITLE
ensure_destination_exists() has incorrect and unused "bind" mount handling

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#2390]
I was testing ensure_destination_exists and missed the upstream fixes recently merged.

Noticed the existing tests that were added don't really exercise directory; just file bind mount. Let's augment to cover dir as well..

**Comment by dgibson** [comment]
As discussed in #2389 the basic problem here isn't really the unit test, it's that `ensure_destination_exists()` isn't actually doing anything particularly useful.  It's "bind" special case is 1) unused and 2) wrong.

Updating title accordingly.
