### ISSUE TITLE
Refine netlink crate to be reused by other projects

### ISSUE THREAD

**Issue by jiangliu** [kata-containers/kata-containers#241]
**Which feature do you think can be improved?**
The netlink crate in kata-container project.

Specify the feature you think could be made better.
The netlink crate could be implemented as a generic library and may be  reused by other projects.

**How can it be improved?**
1) get rid of dependency on the rustjail crate
2) split Kata specific code out of generic code
3) reduce unsafe code
4) reduce the dependency chain. By default it has dependency on about 70 crates.
5) define features to conditionally enable features.

Describe how specifically you think it could be improved.

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by ariel-adam** [comment]
Closing this issue since the PR has been merged.
