### ISSUE TITLE
Cleanup kernel build doc and scripts

### ISSUE THREAD

**Issue by dcmiddle** [kata-containers/kata-containers#2422]
# Description
Collection of minor issues with the kernel build documentation and scripts in `tools/packaging/kernel` and relates places. Collected into one issue for efficiency. I will create logically separate commits, though.

	1. Readme instruction incomplete
	2. build script typo in help message
	3. document dependencies for (a) kata scripts and (b) kernel builds
	4. kernel version/url mismatch in versions.yaml
	5. Remove old jenkins file referencing archived repo

# Details

## 1. should be a sudo on this line...                                                           
```bash                                                                                             
$ ./build-kernel.sh install                                                                         
```                                                                                                 
of tools/packaging/kernel/README.md                                                       

## 2. build -h has a typo
`Description: This script is the *ONLY* to build a kernel for development.`
Missing "way"
Also in the README display of that message.

## 3.a. build script assumes yq is installed.
```
$ ./build-kernel.sh build
  kata-containers/tools/packaging/kernel/../scripts/lib.sh: line 39: yq: command not found
```
https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/build-kernel.sh#L494-L496

	https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/scripts/lib.sh#L35-L42

I propose adding a brief dependency instruction for yq to the docs.
Note the deprecated version 3 is required (e.g. snap install yq --channel=v3/stable)
  (It is also possible to automate this but those scripts only seem appropriate for CI... 
  The helper script ../scripts/lib.sh
  has a function to get the tests repo and run an installer script from there, but that seems more onerous than just listing the tool dependency in the docs.
  see https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/scripts/lib.sh#L28-L33)

## 3.b. Add guidance to install kernel build dependencies
E.g. flex, bison, libelf-dev are necessary for the kernel scripts. 
Reference the CI scripts (e.g. https://github.com/kata-containers/tests/blob/main/.ci/setup_env_ubuntu.sh) rather than try to prescribe exact packages.

## 4. Versions URL is out of date:
https://github.com/kata-containers/kata-containers/blob/main/versions.yaml#L158                     
Update URL to 5.x here:
https://github.com/kata-containers/kata-containers/blob/main/versions.yaml#L155                     
and here:
https://github.com/kata-containers/kata-containers/blame/main/versions.yaml#L162 

It causes broken links in the release notes, e.g.,
https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/release/release-notes.sh#L63
	Which links to the invalid:                                                                                
	https://cdn.kernel.org/pub/linux/kernel/v4.x//linux-5.4.60.tar.xz     

## 5.  Kernel Jenkins pipeline calls archived repos. Assume that means this jenkins file is not in use and has been obviated by github actions.
This calls archived packaging repo:
https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/Jenkinsfiles/release_pipeline/Jenkinsfile#L28
This appears to reference a fork of an archived agent repo:
https://github.com/kata-containers/kata-containers/blame/main/tools/packaging/Jenkinsfiles/release_pipeline/git_credential_cache.sh#L44
Propose removing all of https://github.com/kata-containers/kata-containers/tree/main/tools/packaging/Jenkinsfiles

**Comment by dcmiddle** [comment]
I intend to work on this issue.

**Comment by fidencio** [comment]
> I intend to work on this issue.

I've assigned the issue to you, Dan.
