### ISSUE TITLE
ARM-ubuntu-Arm-clh-containerd-k8s-minimal CI failing

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#2458]
The jenkins-ci-ARM-ubuntu-Arm-clh-containerd-k8s-minimal is constantly failing see
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR-Arm-clh-containerd-k8s-minimal/33/console
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR-Arm-clh-containerd-k8s-minimal/31/console
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR-Arm-clh-containerd-k8s-minimal/30/console
It seems that the environment is not clean
```
01:39:19 [init] Using Kubernetes version: v1.21.1
01:39:27 [preflight] Running pre-flight checks
01:39:27 error execution phase preflight: [preflight] Some fatal errors occurred:
01:39:27 	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
01:39:27 [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
01:39:27 To see the stack trace of this error execute with --v=5 or higher
01:39:27 [init.sh:122] ERROR: sudo -E kubeadm init --config /tmp/kata-containers/kubeadm_config.TolwY8.yaml
01:39:27 [setup.sh:29] ERROR: bash ./init.sh
```

**Comment by jongwu** [comment]
thanks @GabyCT -,  you are right. the environment should be clean.

**Comment by GabyCT** [comment]
thanks @jongwu for your help and answer
