### ISSUE TITLE
Has v1 been silently abandoned?

### ISSUE THREAD

**Issue by PeterSurda** [kata-containers/kata-containers#2470]
After many hours of searching, it appears to me that v1 of kata-containers, alongside with support with v1 OCI runtime and docker, has been discontinued. There has been no new code in the `stable-1.12` branch. since 1.12.1 was released 7 months ago, apart from some build script fixes. The documentation that refers to docker is obsolete and doesn't work (for example, it mentions that the "stable" snap is for v1 and "candidate" for v2, well that's not true, the "stable" snap is pointing to v2).

However I can't find any announcement or documentation about this. Just stuff that used to work silently breaks when redeploying / upgrading.

Is my conclusion correct? Can you at least document it somewhere so that people don't waste time figuring this out? Can you maybe add some helpful error messages that explain the issue to people who are stupidly trying to use the current version with docker, for example? Maybe have 'kata-docker-deploy' script inside the kata-deploy image echo "Docker isn't supported in kata v2, use kata v1", rather than simply being absent?

**Comment by fidencio** [comment]
@PeterSurda 

> After many hours of searching, it appears to me that v1 of kata-containers, alongside with support with v1 OCI runtime and docker, has been discontinued.

Yes, that's the case.

We wrote a blog post about that https://medium.com/kata-containers/about-kata-containers-releases-8b3d91d1166e, we tweeted about the blog post, we dropped several emails to our mailing list about the plans, and we discussed those openly as part of the kata-containers architecture committee meetings.

It seems none of those reached you.  What do you think that would be the best way to reach consumers like you for future interations?

> There has been no new code in the `stable-1.12` branch. since 1.12.1 was released 7 months ago, apart from some build script fixes. The documentation that refers to docker is obsolete and doesn't work (for example, it mentions that the "stable" snap is for v1 and "candidate" for v2, well that's not true, the "stable" snap is pointing to v2).

The branches were archived for a reason.  Or is the wrong documentation in this current branch?  If so, would be posssible to either submit a PR fixing the issue or point us at the links so we can do that?

> However I can't find any announcement or documentation about this. Just stuff that used to work silently breaks when redeploying / upgrading.

I covered this above.

> Is my conclusion correct? Can you at least document it somewhere so that people don't waste time figuring this out? Can you maybe add some helpful error messages that explain the issue to people who are stupidly trying to use the current version with docker, for example? Maybe have 'kata-docker-deploy' script inside the kata-deploy image echo "Docker isn't supported in kata v2, use kata v1", rather than simply being absent?

Also covered this above, I think.


While here, Peter, I understand your frustration and we're here to improve our ways of communicating and also try to get folks using our project to get more involved with its development, with the decisions we take.  With this in mind, **please**, help us to know how to improve on those bits.

Also, please, join our mailing list (http://lists.katacontainers.io/cgi-bin/mailman/listinfo), join our Slack channel (https://bit.ly/kataslack).  Feel free to ping me there if you want to vent.

Is there something else this community can do for you?

**Comment by fidencio** [comment]
Ah, of course, if you want an alternative that would work with v2, take a look at `ctr`.  I **think** `nerdctl` would work as well, as I remember some conversations happening here and there.

**Comment by PeterSurda** [comment]
First of all, thank you for the kind reply.

> > After many hours of searching, it appears to me that v1 of kata-containers, alongside with support with v1 OCI runtime and docker, has been discontinued. 
> Yes, that's the case.

Ok, that clarifies things.
 
> We wrote a blog post about that https://medium.com/kata-containers/about-kata-containers-releases-8b3d91d1166e, we tweeted about the blog post, we dropped several emails to our mailing list about the plans, and we discussed those openly as part of the kata-containers architecture committee meetings.

Unfortunately I haven't found it until you mentioned. I'm not involved in the development, I just use it, and provisioning scripts stopped working, error messages were not helpful, and searching for hours didn't provide anything. Maybe I wasn't searching for the right things?

> It seems none of those reached you. What do you think that would be the best way to reach consumers like you for future interations?

This is an excellent question and I have the same problem with my own projects. I wish I had a good answer. For myself, I don't need a complicated explanation or the reasoning, I understand projects evolve and things change and docker swarm isn't that popular anymore. If I think about this, your blog post appears to be targeted perhaps at a slightly different segment of the community. I'm not following the development, I'm not really a part of the community. I just deploy it. So, if the errors I'm getting at deployment were considering my position, that would be greatly helpful.

> The branches were archived for a reason. Or is the wrong documentation in this current branch? If so, would be posssible to either submit a PR fixing the issue or point us at the links so we can do that?

I understand that you archive EOL'd stuff, the problem I have is the documentation became obsolete too, and that's not obvious beforehand. Now in retrospect I understand that better.

> I covered this above.

Yes, thank you again.

> While here, Peter, I understand your frustration and we're here to improve our ways of communicating and also try to get folks using our project to get more involved with its development, with the decisions we take. With this in mind, **please**, help us to know how to improve on those bits.

Thank you, let me reciprocate by providing concrete yet simple suggestions:

- inside the `katadocker/kata-deploy` images, put a script `kata-deploy-docker` which just prints "Kata v2 doesn't support docker anymore, you can use v1.12.1 image, but keep in mind it's EOL". This alone would have saved me hours.
- even though https://github.com/kata-containers/documentation/blob/master/install/snap-installation-guide.md is archived, consider updating it to reflect that v1 is discontinued, and perhaps also update reference to snap. At the moment as far as I understand it's not possible to install kata v1 using snap, snap doesn't have a facility to cherry pick an older release
- on the description of the archived repos on github, consider adding "EOL" to the description.

> Is there something else this community can do for you?

As now I understand kata v1 is discontinued, that's all I needed to know. I'm not asking for anything else, I just hope my suggestions can help others in similar situation.

> Ah, of course, if you want an alternative that would work with v2, take a look at ctr. I think nerdctl would work as well, as I remember some conversations happening here and there.

I found several alternatives to kata, there is also firecracker for example, but the thing is, I don't just want to use docker, I want to use docker swarm, and it appears to me that at the moment the EOLed kata is the only option for me. Maybe I'll have to move to kubernetes after all.

**Comment by fidencio** [comment]
> First of all, thank you for the kind reply.
> 
> > > After many hours of searching, it appears to me that v1 of kata-containers, alongside with support with v1 OCI runtime and docker, has been discontinued.
> > > Yes, that's the case.
> 
> Ok, that clarifies things.
> 
> > We wrote a blog post about that https://medium.com/kata-containers/about-kata-containers-releases-8b3d91d1166e, we tweeted about the blog post, we dropped several emails to our mailing list about the plans, and we discussed those openly as part of the kata-containers architecture committee meetings.
> 
> Unfortunately I haven't found it until you mentioned. I'm not involved in the development, I just use it, and provisioning scripts stopped working, error messages were not helpful, and searching for hours didn't provide anything. Maybe I wasn't searching for the right things?
> 
> > It seems none of those reached you. What do you think that would be the best way to reach consumers like you for future interations?
> 
> This is an excellent question and I have the same problem with my own projects. I wish I had a good answer. For myself, I don't need a complicated explanation or the reasoning, I understand projects evolve and things change and docker swarm isn't that popular anymore. If I think about this, your blog post appears to be targeted perhaps at a slightly different segment of the community. I'm not following the development, I'm not really a part of the community. I just deploy it. So, if the errors I'm getting at deployment were considering my position, that would be greatly helpful.
> 
> > The branches were archived for a reason. Or is the wrong documentation in this current branch? If so, would be posssible to either submit a PR fixing the issue or point us at the links so we can do that?
> 
> I understand that you archive EOL'd stuff, the problem I have is the documentation became obsolete too, and that's not obvious beforehand. Now in retrospect I understand that better.
> 
> > I covered this above.
> 
> Yes, thank you again.
> 
> > While here, Peter, I understand your frustration and we're here to improve our ways of communicating and also try to get folks using our project to get more involved with its development, with the decisions we take. With this in mind, **please**, help us to know how to improve on those bits.
> 
> Thank you, let me reciprocate by providing concrete yet simple suggestions:
> 
>     * inside the `katadocker/kata-deploy` images, put a script `kata-deploy-docker` which just prints "Kata v2 doesn't support docker anymore, you can use v1.12.1 image, but keep in mind it's EOL". This alone would have saved me hours.

Would be possible to open an issue for this? (I am sorry, I am going off for a week now and I am afraid I will have a hard time to get back to it unless there's an issue opened).

> 
>     * even though https://github.com/kata-containers/documentation/blob/master/install/snap-installation-guide.md is archived, consider updating it to reflect that v1 is discontinued, and perhaps also update reference to snap. At the moment as far as I understand it's not possible to install kata v1 using snap, snap doesn't have a facility to cherry pick an older release

That makes sense and also deserve an issue.

> 
>     * on the description of the archived repos on github, consider adding "EOL" to the description.
> 

Same about this, all **really great suggestions!** that we didn't cross our minds.  Sorry about that. /o\

> 
> > Is there something else this community can do for you?
> 
> As now I understand kata v1 is discontinued, that's all I needed to know. I'm not asking for anything else, I just hope my suggestions can help others in similar situation.
> 
> > Ah, of course, if you want an alternative that would work with v2, take a look at ctr. I think nerdctl would work as well, as I remember some conversations happening here and there.
> 
> I found several alternatives to kata, there is also firecracker for example, but the thing is, I don't just want to use docker, I want to use docker swarm, and it appears to me that at the moment the EOLed kata is the only option for me. Maybe I'll have to move to kubernetes after all.

Yeah, maybe kubernetes is the way to go after all.

Thanks for the feedback, @PeterSurda, really appreciated!

I really would like to ask you to open the issues about the suggestions you made and if no-one works on those till I come back from vacation, I'll try to address those in the first or second week of September.

**Comment by cmaf** [comment]
Hi @fidencio, @PeterSurda, are there additional issues that should be opened based on the feedback here, or can we close this issue?

**Comment by PeterSurda** [comment]
I'm sorry but I stopped paying attention, since I'm staying with docker I can't use kata anymore.
