### ISSUE TITLE
Failed to get OOM event from sandbox is a horribly chatty red herring, and should be info, not warn

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#2478]
AFAICT, we will hit this, [1], for most every sandbox when it is shutting down. If you run a lot of Kata pods, you'll see a log of these messages when there isn't an OOM event to be received.

We should probably downgrade this from a warning to info, and should consider adding smarter error handling here to identify when the agent is not responding? 

[1]- https://github.com/kata-containers/kata-containers/blob/3e8137399c6dc1ad2af7a236c281a2ee60a817a7/src/runtime/containerd-shim-v2/wait.go#L150

**Comment by egernst** [comment]
Looks like this was added to help address: https://github.com/kata-containers/kata-containers/commit/cb0e6094ff93a2720ced71bf569c6b170b81e16c

But, really we shouldn't be outputting this as a warning, then, since shutdown is a very common scenario shared by all.

@liubin  - WDYT?

**Comment by liubin** [comment]
I have ever considered to check the sandbox's state, for example if in the `shuttingdown` state then break the for loop.
Or using a chan to receive sandbox shutdown event to break the for loop.

**Comment by sameo** [comment]
I think we should only print out an error if the agent is not shutting down. When it is shutting down and destroying the sandbox, the OOM event receiver will be closed and we will hit that path: https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L1197. This is where we could add a custom ttrpc error string/code and handle that nicely from the runtime.
But meanwhile, I believe we should at least downgrade to info.

**Comment by ariel-adam** [comment]
@snir911 also relevant to your work

**Comment by liubin** [comment]
closed via #4425
