### ISSUE TITLE
device: Allow "VmPath" to be used when adding block devices 

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#248]
Apply the golang agent feature to the [new rust agent](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/agent]).

See:

- https://github.com/kata-containers/agent/issues/789
- https://github.com/kata-containers/agent/pull/790

**Comment by bergwolf** [comment]
Fixed by #790

**Comment by amshinde** [comment]
@bergwolf Has this been implemented in the rust agent?

**Comment by likebreath** [comment]
@amshinde I don't think so. The reason why I haven't submited a PR to introduce the similar chance in rust agent (as what's done in https://github.com/kata-containers/agent/pull/790) is this change to agent will be meaningful only if this runtime PR (https://github.com/kata-containers/runtime/pull/2721) is ported to kata 2.0. 

Note that the changes to agent is backwards compatible (won't break anything w/o the corresponding runtime changes). If it is better to have the parity on (rust) agent first (while runtime is not), I can definitely send a PR to rust agent. Just let me know your thoughs.

**Comment by amshinde** [comment]
@likebreath If the runtime change hasnt been ported to 2.0, lets do that followed by the agent change. 
The reason I asked was that the issue was closed erroneously. Reopening.
