### ISSUE TITLE
ARM CI failing constantly 

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#2484]
The ARM CI is not stable as it has been failing randomly and constantly as you can see on 
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/1159/
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/1164/
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/1159/

**Comment by jongwu** [comment]
@GabyCT -, thanks for reminder. can you help to review my [PR](https://github.com/kata-containers/tests/pull/3848), thanks again.
