### ISSUE TITLE
s390x CI failing randomly

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#2485]
The s390x CI is failing randomly see
17:06:39 Error response from daemon: Could not kill running container 73d79883d0e4095db5c853d39878453f4e12ce73a9b4fb0edffa4df7cae9bfe2, cannot remove - Cannot kill container 73d79883d0e4095db5c853d39878453f4e12ce73a9b4fb0edffa4df7cae9bfe2: connection error: desc = "transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout": unavailable
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/114/
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/117/
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/115/

**Comment by Jakob-Naucke** [comment]
@GabyCT recent s390x runs on the tests job were pretty healthy and the issue of the linked runs has been fixed, #2465 is also resolved at least temporarily (testing a potential fix internally). I'm still fighting failures like http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR/425/ (can reproduce on a dev machine, still investigating).
