### ISSUE TITLE
The  SRIOV  use cases document still keep kata v1.x

### ISSUE THREAD

**Issue by YchauWang** [kata-containers/kata-containers#2489]
# Description of problem

The demo example of SRIOV and kata, still using the docker runtime. 
`$ sudo docker network create -d sriov --internal --opt pf_iface=enp1s0f0 --opt vlanid=100 --subnet=192.168.0.0/24 vfnet

E0505 09:35:40.550129    2541 plugin.go:297] Numvfs and Totalvfs are not same on the PF - Initialize numvfs to totalvfs
ee2e5a594f9e4d3796eda972f3b46e52342aea04cbae8e5eac9b2dd6ff37b067
`
The shim v2 didn't support docker runtime. Who can give a ctr demo, thanks?

**Comment by ariel-adam** [comment]
@YchauWang could please clarify what exactly is the problem you would like to address?
@dgibson adding you as well if related to SRIOV in kata2.x

**Comment by c3d** [comment]
@YchauWang Adding to Ariel's comment: SR-IOV does not work too well with Kata 2.0 yet, so I suspect that the reason the documentation is not updated is that the code does not work well enough yet for us to document it. @dgibson can give you more details here?

Maybe we should just make sure we remove examples that don't work?

**Comment by YchauWang** [comment]
Thank you @c3d and @ariel-adam for your attention. I just want to know how to config the SR-IOV with kata 2.x. You know, kata 2.x doesn't support the docker runtime. I found a page about k8s with sr-iov, https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#quick-start. Does this page give some help for kata 2.x with SR-IOV?

**Comment by dgibson** [comment]
Huh.  I had the impression that vfio worked as much with Kata 2 as it did with Kata 1 - which is to say some limited but *extremely* fragile things.  I don't remember enough about Kata 1 to say that with confidence though.
