### ISSUE TITLE
runtime/virtcontainers: Append max ports to virtio-serial device

### ISSUE THREAD

**Issue by justin-he** [kata-containers/kata-containers#249]
**Which feature do you think can be improved?**

virtcontainers: Append max ports to virtio-serial device

**How can it be improved?**

Govmm has provided a "max_ports" parameter to allow API consumers to change the maximum number of ports in the virtio-serial devices, setting a lower number of ports can improve the
boot time and reduce the attack surface.

**Additional Information**

No

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?
Yes

This is to backport from https://github.com/kata-containers/runtime/issues/2676

**Comment by c3d** [comment]
@justin-he It looks like this is a forward-port placeholder for https://github.com/kata-containers/runtime/issues/2676

**Comment by cmaf** [comment]
Closing since this was ported in da79b4be6
