### ISSUE TITLE
vfio ci always fail on stable-2.1

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#2495]
see http://jenkins.katacontainers.io/job/kata-containers-2.0-vfio-PR/1620/console
the error shows:  cgo: exec gcc: exec: "gcc": executable file not found in $PATH

@GabyCT @devimc

**Comment by GabyCT** [comment]
@devimc could you please take a look

**Comment by GabyCT** [comment]
I think the issue is related with
```
04:03:15 /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/tests /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/kata-containers /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/tests
04:03:15 .ci/jenkins_job_build.sh: line 167: .ci/ci_job_flags.sh: No such file or directory
```
It seems that it is missing that backport? let me take a look

**Comment by GabyCT** [comment]
@jongwu the missing backport was done and VFIO CI is working on stable 2.1 http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-vfio-PR/939/
