### ISSUE TITLE
How do I specify a configuration file in cri-o?

### ISSUE THREAD

**Issue by jclab-joseph** [kata-containers/kata-containers#2498]
For containerd you can find this at "https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/containerd-kata.md"
But in the case of cri-o, there is no example.

How can I specify a config file in cri-o?

Also, request to improve the documentation.

**Comment by ariel-adam** [comment]
@fgiudici any idea?

**Comment by c3d** [comment]
@jclab-joseph The procedure for `cri-o` should be very similar to what you do for `containerd`. I agree the documentation could be improved.

**Comment by fgiudici** [comment]
CRI-O should be configured to let it know that kata runtime is available.
It could be done adding a configuration snippet like this:
`[crio.runtime.runtimes.kata-shim2]`
`  runtime_path = "/usr/local/bin/containerd-shim-kata-v2"`
`  runtime_type = "vm"`
`  runtime_root = "/run/vc"`
`  privileged_without_host_devices = true`

**Comment by jclab-joseph** [comment]
@fgiudici Yes it can be solved with a shell script containing environment variable. thank you :)

https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/run-kata-with-k8s.md
This documentation says to use the oci runtime.
But oci doesn't work (#2497), vm runtime works fine and fgiudici's advice also works.

**Comment by fidencio** [comment]
While going through the old issues I noticed this one, and took the freedom to just open a PR updating the docs.
