### ISSUE TITLE
Ensure components can always consume on-disk state from previous versions

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#25]
If component C at version X creates persistent on-disk state, that state must be consumable by component C at version X+1.

This guarantee is required to support a "live upgrade" scenario.

## Approaches

We could either:

### Version the on-disk state

- Embed a version field into the start of each state file.
- Versions would be semver :)

Pros:

- :+1: very quick to determine if state formats differ.

Cons:

- :-1: every new on-disk format change requires the component to understand all the previous versions potentially.
- :-1: spaghetti code:
  - :-1: more fragile / less reliable.
  - :-1: difficult to maintain and test.

### Make the X+1 component version tolerant to missing elements

- If a particular element from state file format version X+1 is not found in the on-disk state file, default that value to an X+1 state file format version value.

This is more like the autoconf approach where the tooling looks for host features rather than rigid feature versions.

Pros:

- :+1: simpler code.
- :+1: more reliable.

Cons:

- :-1: slower than just comparing version strings.

### Atomicity

The state handling (serialising and deserialising) needs to be atomic to handle failure scenarios.

### Dynamically loaded (and unloaded) state conversion?

If the state deserialisation code becomes big (maybe due to lots of different state versions), it might be worth investigating components dynamically loading a package to handle converting the on-disk state version X-n to the current state version X. Ideally, that package would be unloaded after successful conversion.

## Testing

- We'll need to create tests for every component which changes its on-disk state format version.
  - Each test will need to assert the component can consume state version X and state version X-1.
    - Store old state files in tests repo and arrange for tests to make component consume them.

## Related

- See https://github.com/kata-containers/ci/issues/10.

/cc @WeiZhang555.

**Comment by WeiZhang555** [comment]
Thank @jodh-intel for filing this! 👍 
 I will be so happy to see test cases for guarantee this, we have lots of works to do later and more details to discuss.v
