### ISSUE TITLE
kata-runtime support "kata-runtime exec {sandbox name}" or add new command "kata-runtime list pods" to query sandbox id 

### ISSUE THREAD

**Issue by Bevisy** [kata-containers/kata-containers#2505]
**Is your feature request related to a problem? Please describe.**

When I need to enter the virtual machine corresponding to the container, I always need to use crictl to query the sandbox id, and then use kata-runtime exec to enter the guest vm, maybe kata-runtime can support querying the sandbox name or id directly, or kata-runtime exec parameter supports the sandbox name

**Describe the solution you'd like**

1. modify kata-runtime exec to support {sandbox-id} and {sandbox name}
2. add new commad kata-runtime list pods/containers to query sandbox id or container id

**Describe alternatives you've considered**

maybe choose 1

**Comment by c3d** [comment]
@Bevisy Are you using kata 1.x? If so, then we no longer support this. Also, the shim-v2 binary does not support as many commands as before, see https://github.com/kata-containers/kata-containers/issues/722

**Comment by Bevisy** [comment]
> @Bevisy Are you using kata 1.x? If so, then we no longer support this. Also, the shim-v2 binary does not support as many commands as before, see #722

I am using kata v2.x. To clarify, I want kata-runtime to be able to access the vm directly via pod(/sandbox) name, like kubectl
`kata-runtime exec {POD_NAME} -n {NAMESPACE}`

**Comment by liubin** [comment]
@Bevisy Now the `kata-runtime exec pod-id` can run into a shell inside the guest if debug console is enabled, but there is no `kata-runtime list-pod` available.
