### ISSUE TITLE
Invalid workflow file : .github/workflows/require-pr-porting-labels.yaml#L14

### ISSUE THREAD

**Issue by rapiz1** [kata-containers/kata-containers#2506]
# Description of problem

I see this happens with many PRs, like:
https://github.com/kata-containers/kata-containers/actions/runs/1161749807

# Expected result

the workflow file is valid

# Actual result

the workflow file is invalid

**Comment by cmaf** [comment]
Closing since https://github.com/kata-containers/kata-containers/pull/2516 was closed and issue was resolved in another PR
