### ISSUE TITLE
Use single storage implementation for Kata 2.0

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#252]
The runtime currently includes two storage implementations:

| Implementation | Location | Original PR |
|-|-|-|
| `store` | https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime/virtcontainers/store | https://github.com/kata-containers/runtime/pull/1066 |
| `persist` | https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime/virtcontainers/persist | https://github.com/kata-containers/runtime/pull/2239 |
- [`store`](https://github.com/kata-containers/runtime/pull/1066)
- [`persist`](https://github.com/kata-containers/runtime/pull/2239)

Since `persist` landed a long time ago, we should be able to delete the older `store` implementation for Kata 2.0. This will:

- Simplify the code (yay! No more calls to [`useOldStore()`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/persist.go#L594) :smile:)
- Improve unit test coverage (yay! :smile:)

/cc @WeiZhang555, @amshinde, @sameo.

See also:

- https://github.com/kata-containers/runtime/pull/1889

**Comment by liubin** [comment]
Should this can be closed due to #368 ? @jodh-intel

**Comment by jodh-intel** [comment]
Fixed by #376.
