### ISSUE TITLE
Allow users to use labels

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#2521]
It seems that not all the users have the permissions to add labels to their PRs which makes difficult to them to add something like `needs-backport`, `backport` ,  `WIP`, `area/testing`, etc. Maybe it is a good idea to not have restrictions for the labels so everybody can label his or her PR properly and make easier the contributions to the project.
/cc @jodh-intel @chavafg @fidencio

**Comment by fidencio** [comment]
@GabyCT, I agree with the idea, but I'm not sure whether it's do-able.
This week I don't have any free cycles to investigate how it works with GitHub, but I think it's a "limitation" on their side.  Maybe actions (`/something`) could be relaxed to any user and we could explore that path to allow people adding some labels?  Not sure, but that's something worth investigating.
