### ISSUE TITLE
Why does it seem that the overhead.podFixed resources has NOT work fine in Kata VM?

### ISSUE THREAD

**Issue by Corgi-Google** [kata-containers/kata-containers#2557]
overhead.podFixed:
```shell
$ kubectl get pod huayun-kata -o jsonpath='{.spec.overhead}'
map[cpu:5 memory:1000Mi]
```

pod limit: 
```yaml
resources:
    limits:
        cpu: "1"
        memory: 2000Mi
```
     

in Kata VM:
```shell
$ cat /proc/cpuinfo  | grep processor | wc -l
2
```
```shell
free -m
              total        used        free      shared  buff/cache   available
Mem:           4042          50        3961          28          30        3923
Swap:             0           0           0
```
    
part of my Kata configuration file:
```toml
default_maxvcpus = 0
default_vcpus = 1
default_memory = 2048
sandbox_cgroup_only=true
```

My understanding is that 5 cpus are set in the overhead, plus 1 cpu in the pod limit and 1 cpu in the kata configuration file. I should see 7 cpus in the kata vm. 
But it seems that the resources in Kata VM is not affected by overhead. 
So why? Did i misunderstanding something?

**Comment by Bevisy** [comment]
Hi, perhaps there is a misunderstanding of the concept of pod overhead, which is only used for kube-scheduler scheduling pods, or for resource statistics when evicting pods, and not for vm physical configuration. You can refer to the description [here](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/)

**Comment by Corgi-Google** [comment]
> Hi, perhaps there is a misunderstanding of the concept of pod overhead, which is only used for kube-scheduler scheduling pods, or for resource statistics when evicting pods, and not for vm physical configuration. You can refer to the description [here](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/)

So is the recommended overhead resources value consistent with the cpu and memory size in the kata default configuration(1C 2G)?

**Comment by Bevisy** [comment]
> > Hi, perhaps there is a misunderstanding of the concept of pod overhead, which is only used for kube-scheduler scheduling pods, or for resource statistics when evicting pods, and not for vm physical configuration. You can refer to the description [here](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/)
> 
> So is the recommended overhead resources value consistent with the cpu and memory size in the kata default configuration(1C 2G)?

I think it should be based on the actual vm resource usage, if it is set directly to the default configuration of the vm, then it will cause a lot of cpu and memory resources to be wasted (the node will have a lot of free resources, but the node cannot be scheduled). The virtual machine actually runs with relatively few resources：
```sh
bash-4.4# free -m
              total        used        free      shared  buff/cache   available
Mem:           1929          26        1871           0          30        1877
Swap:             0           0           0
```

**Comment by c3d** [comment]
There is an issue with CPU requests in Kata (https://github.com/kata-containers/kata-containers/issues/2071), but as @Bevisy pointed out, the pod overhead is intended to represent the cost of running in a VM, not the size of the VM.

You can change the `default_vcpus`, or pass that as an annotation (`io.katacontainers.config.hypervisor.default_vcpus = 5`) as a workaround for the moment.

**Comment by Corgi-Google** [comment]
> There is an issue with CPU requests in Kata (#2071), but as @Bevisy pointed out, the pod overhead is intended to represent the cost of running in a VM, not the size of the VM.
> 
> You can change the `default_vcpus`, or pass that as an annotation (`io.katacontainers.config.hypervisor.default_vcpus = 5`) as a workaround for the moment.

Does this annotation work on Containerd + Kata ?

**Comment by Bevisy** [comment]
@Corgi-Google You should do 3 changes as below:

> enable_annotations = ["io.katacontainers.config.hypervisor.qemu.default_vcpus"]

modify to  `enable_annotations = ["default_vcpus"]`

>     io.katacontainers.config.hypervisor.qemu.default_vcpus: "5"
modify to `io.katacontainers.config.hypervisor.default_vcpus: "5"`

Then you should modify containerd config enable pod_annotations like:
```toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"
          privileged_without_host_devices = false
          shim_debug = true
          pod_annotations = ["io.katacontainers.*"]   #  <-- look here
```

I have already verified locally using `io.katacontainers.config.hypervisor.default_vcpus: "3"`
```sh
bash-4.2# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
```

**Comment by egernst** [comment]
@Corgi-Google  -- any reason you don't just set the req/limits for the workload? This'll result in a properly sized VM
