### ISSUE TITLE
Support running rootless VMM in FC/CLH hypervisors

### ISSUE THREAD

**Issue by fengwang666** [kata-containers/kata-containers#2567]
**Which feature do you think can be improved?**

We're making a change to [enable running QEMU VMM as a non-root user](https://github.com/kata-containers/kata-containers/pull/2432), which can also be extended to Firecracker and Cloud Hypervisor as well. This issue is to track the task.

**Comment by cpmeadors** [comment]
PR is already open.  Assigning to @fengwang666
