### ISSUE TITLE
tests: Improve coverage for virtcontainers/persist/ for Kata 2.0

### ISSUE THREAD

**Issue by jamesodhunt** [kata-containers/kata-containers#259]
The following [`2.0-dev` runtime branch](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime) files need more unit tests:

```virtcontainers/persist/```

See: https://github.com/kata-containers/kata-containers/issues/237

**Comment by cmaf** [comment]
Current coverage is 66%
