### ISSUE TITLE
tests: Improve coverage for virtcontainers/factory/ for Kata 2.0

### ISSUE THREAD

**Issue by jamesodhunt** [kata-containers/kata-containers#260]
The following [`2.0-dev` runtime branch](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime) files need more unit tests:

```virtcontainers/factory/```

See: https://github.com/kata-containers/kata-containers/issues/237

**Comment by cmaf** [comment]
Current coverage is 34%
