### ISSUE TITLE
CI failure: QMP command query-cpus not found

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#2643]
> Warning  FailedCreatePodSandBox  11s (x6 over 88s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = CreateContainer failed: failed to get thread ids from hypervisor: QMP command failed: The command query-cpus has not been found: unknown

Looks to be related to https://github.com/kata-containers/kata-containers/pull/2502 ?

/cc @dgibson Does qemu v6.1 drop some QMP commands?

**Comment by dgibson** [comment]
Bother.  What circumstances is that error showing up in?  It didn't show up in the CI.

It ppears that `query-cpus` was replaced with `query-cpus-fast`.

**Comment by dgibson** [comment]
Sorry, misread something.  Which CI case is this problem showing up in?  I got a passing CI before merging #2502, so I'm a bit confused as to why it's failing now.  Nonetheless, I now have a draft PR to fix it.

**Comment by fidencio** [comment]
Okay, what I think that happened is:
* #2332 touches the code related to `getThreadIDs()`
* That raises failures in pieces of the code that were already present (see: #2593)
* @dgibson has been testing his PR against a HEAD that's, obviously, behind #2332 (which was not even merged)
* We merge #2332 with green CI
* We merge #2502 with green CI
* Next run explodes as #2332 uses a function that exposes an issue with #2502.

What to do to mitigate this?  Maybe having a bot to only have the code **pushed** after CI **also** passes with the "merge" into the current state of the main would be a way to go.

**Comment by dgibson** [comment]
@fidencio nice analysis, thanks

**Comment by dgibson** [comment]
> What to do to mitigate this? Maybe having a bot to only have the code **pushed** after CI **also** passes with the "merge" into the current state of the main would be a way to go.

That sounds like a good idea in principle.  But I think the CI needs to be a bit more reliably green before it's feasible - otherwise merges are likely to fail mysteriously when the CI suffers an unrelated breakage :(.

**Comment by fidencio** [comment]
> > What to do to mitigate this? Maybe having a bot to only have the code **pushed** after CI **also** passes with the "merge" into the current state of the main would be a way to go.
> 
> That sounds like a good idea in principle. But I think the CI needs to be a bit more reliably green before it's feasible - otherwise merges are likely to fail mysteriously when the CI suffers an unrelated breakage :(.

This is what's done on CRI-O, by the way, where a bot ensures a `/retest` would be ran automagically.  With the proposal of the green CI raised by @ariel-adam and @chavafg, and with people allocated to work and to monitor the baselines, I think it'll be doable in a not so remote future.
