### ISSUE TITLE
CI: enable firecracker CI job in stable branch PRs

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#2677]
Right now it is not enabled as shown in 2.2.0 PRs like https://github.com/kata-containers/kata-containers/pull/2668

**Comment by fidencio** [comment]
Following Tao's request and a conversation on #kata-ci Slack, I've enabled the firecracker-ci to run as **non-required** for the stable-2.* branches, and I'm taking advantage of #2668 to ensure it works (sorry, @cmaf, but it shouldn't cause much disruptions),

The job to monitor is http://jenkins.katacontainers.io/job/kata-containers-2.0-firecracker-ubuntu-PR/1162/, and I'm closing this one.  If there are failures with the CI, @ananos can help us to track things down.  But it **should** be okay.

Thanks for opening the issue so we could track the change, @bergwolf!
