### ISSUE TITLE
tests: Improve coverage for virtcontainers/container.go for Kata 2.0

### ISSUE THREAD

**Issue by jamesodhunt** [kata-containers/kata-containers#268]
The following [`2.0-dev` runtime branch](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime) file needs more unit tests:

```virtcontainers/container.go```

See: https://github.com/kata-containers/kata-containers/issues/237

**Comment by Amulyam24** [comment]
Hi @jodh-intel , I would like to work on adding tests to `container.go`. Feel free to assign me if needed :)

**Comment by jodh-intel** [comment]
Thanks @Amulyam24 ! :smile:

Take a look at https://github.com/kata-containers/tests/blob/main/Unit-Test-Advice.md if you haven't already. Also, reading through some of the existing test code can help a lot. But feel free to ping us if you have any queries!

**Comment by Amulyam24** [comment]
Hi @jodh-intel, apologies in getting back on this. 

Thanks for the input, I will definitely check the existing test code for a better understanding and get back in case I have questions.
