### ISSUE TITLE
Ensure https://github.com/qemu/qemu/commit/9911ca0d1bca846f159ebdb48b9d8a784c959589 is applied for QEMU 5.x

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#2698]
All CIs that have to build QEMU and still rely on QEMU 5.x should have https://github.com/qemu/qemu/commit/9911ca0d1bca846f159ebdb48b9d8a784c959589 applied in order to workaround git.qemu.org instabilities.

The CIs affected are everything on `stable-2.2` branch, but as some of those rely on cached QEMU, the ones we can see being more impacted are:
* s390x
* aarch64
* snap

And then aarch64 on `main`, as it relies on QEMU 5.2.

Having https://github.com/qemu/qemu/commit/9911ca0d1bca846f159ebdb48b9d8a784c959589 as part of our patches would solve the breakage.

/cc @jongwu @devimc @Jakob-Naucke @wainersm @c3d

**Comment by Jakob-Naucke** [comment]
@jongwu I can create a patch for QEMU 5.2 on `stable-2.2`, how do you want to handle ARM?

**Comment by jongwu** [comment]
@fidencio @Jakob-Naucke -,  arm is using qemu 5.1.0. So can you help apply the patch for qemu 5.1.x on stable-2.2?

**Comment by cmaf** [comment]
@Jakob-Naucke @fidencio https://github.com/kata-containers/kata-containers/pull/2699 and https://github.com/kata-containers/kata-containers/pull/2702 were both merged, but based on comments it looks like the ARM CI may still be failing. Is this the case, or can we close this issue?

**Comment by cmaf** [comment]
@Jakob-Naucke disregard, I see you **just** closed it as I was writing

**Comment by Jakob-Naucke** [comment]
Yes, the linkage didn't work. Issues on ARM should be fixed by #2753.
