### ISSUE TITLE
Make sure cached QEMU/kernel builds are not used in production

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#2700]
> only sort of related but: are we making sure no one uses these builds in production unintentionally? Because supply chain security wouldn't be optimal if we didn't.

Good question, I don't know. I don't think kata-deploy and kata snap use those cached artifacts, but IMO it is worth checking. Certainly it deserves a new issue.

Thanks for bringing that topic, @Jakob-Naucke !

_Originally posted by @wainersm in https://github.com/kata-containers/tests/issues/3999#issuecomment-925073147_

**Comment by Jakob-Naucke** [comment]
I don't think so:
https://github.com/kata-containers/kata-containers/blob/b6ff23d21beacf9c67361ac3421f405c2a47ffc8/snap/snapcraft.yaml#L313
https://github.com/kata-containers/kata-containers/blob/b6ff23d21beacf9c67361ac3421f405c2a47ffc8/tools/packaging/static-build/qemu/Dockerfile#L78
https://src.fedoraproject.org/rpms/kata-containers/blob/c7544c2cf7878b71d30b1cad80d741fb31418c01/f/kata-containers.spec#_151
Anything else?

**Comment by Jakob-Naucke** [comment]
ah, and kernel (this was just QEMU):
https://github.com/kata-containers/kata-containers/blob/b6ff23d21beacf9c67361ac3421f405c2a47ffc8/snap/snapcraft.yaml#L207
https://github.com/kata-containers/kata-containers/blob/b6ff23d21beacf9c67361ac3421f405c2a47ffc8/tools/packaging/static-build/kernel/build.sh#L32
https://src.fedoraproject.org/rpms/kata-containers/blob/c7544c2cf7878b71d30b1cad80d741fb31418c01/f/kata-osbuilder.sh#_124

**Comment by Jakob-Naucke** [comment]
@fidencio are there any other official build pipelines?

**Comment by fidencio** [comment]
> @fidencio are there any other official build pipelines?

Here's where we build the QEMU that's shipped with the kata-deploy image:
https://github.com/kata-containers/kata-containers/blob/653976c0fdf3c1751e20f3eacf9f0998d606db06/.github/workflows/main.yaml#L80-L104

And here's where we build the kernels that we ship with the kata-deploy image:
https://github.com/kata-containers/kata-containers/blob/653976c0fdf3c1751e20f3eacf9f0998d606db06/.github/workflows/main.yaml#L24-L78

So, yeah, we end up building things from scratch and not relying on the cached QEMU / kernel builds.

**Comment by Jakob-Naucke** [comment]
Thank you @fidencio -- closing.
