### ISSUE TITLE
kata-deploy is not multi-arch

### ISSUE THREAD

**Issue by paleozogt** [kata-containers/kata-containers#2758]
# Description of problem

While kata is distributed for many arches (the snap store shows `amd64`, `arm64`, `ppc64le`, `x390x`), the kata-deploy image (e.g. `quay.io/kata-containers/kata-deploy:2.2.0`) is only for `amd64`.

# Expected result

`quay.io/kata-containers/kata-deploy:x.y.z` should be a multi-arch manifest.

# Actual result

`quay.io/kata-containers/kata-deploy:x.y.z` is a single-arch image for `amd64`.

# Further information

The base image used in `tools/packaging/kata-deploy/Dockerfile` is single-arch image `registry.centos.org/centos:7`.  This could be changed to `centos:7` to get a multi-arch base image.

**Comment by fidencio** [comment]
@paleozogt, I'm closing this one as this is a dup of https://github.com/kata-containers/kata-containers/issues/2639.  Please, subscribe to that one instead.
