### ISSUE TITLE
[RFC][WIP] tools: Add standard OCI container runtime based on Kata agent

### ISSUE THREAD

**Issue by ManaSugi** [kata-containers/kata-containers#2784]
# Proposal: Add a standard OCI container runtime based on Kata agent

## Motivation

The `kata-agent` has most of the [features](https://github.com/kata-containers/kata-containers/tree/main/src/agent#features) needed for the container runtime and delivers high performance with a low memory footprint owing to the implementation by Rust language.

If we can develop a Rust-based standard container runtime that spawns and runs normal containers, not hardware-virtualized containers, using the mechanism provided by the `kata-agent`, it should be possible to create a high-performance container runtime than existing runtimes like `runc` while preventing reinventing the wheel.

Besides, by developing the standard runtime, the `kata-agent` can be adopted in various systems that do not always require the VM environment and we can increase the number of `kata-agent` users. This leads to boost the development speed of `kata-agent` and make the `kata-agent` easier to follow the latest [OCI runtime specifications](https://github.com/opencontainers/runtime-spec).

In addition, the runtime can be also used as a test+debug tool for the `kata-agent` like the `agent-ctl`. The users and developers can handle the `kata-agent` like `runc`, making it easier to test and debug.

## Proposal

The goal of this proposal is to develop a Rust-based standard OCI container runtime, `runk`,  based on the `kata-agent`.
`runk` aims to become one of the alternatives to existing OCI compliant container runtimes. `runk` provides an OCI Command-Line Interface (CLI) that is defined in [the runtime spec](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md). `runk` leverages the mechanism of the `kata-agent` internally.

<br>
  <image src="https://user-images.githubusercontent.com/66765615/135791230-47de95dd-29a2-4cf8-9624-d90790c9e91f.png" width="700">
<br>

The important thing here is to minimize `kata-agent` modifications for `runk` considering the maintainability. To minimize the modifications, `runk` should call the `kata-agent` binary in the same as `kata-agent/rpc.rs`. Of course, the `kata-agent` cannot be used as it is, so it needs to be changed so that it can be used from `runk`.

## Implementation

I have developed a prototype of `runk` and sent the PR. 
Currently, `runk` supports [five OCI operations](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#operations) and `run` operation that runtimes MUST support.
As of now, `runk` modified and added only 212 lines of code in the existing `kata-agent`.

For the details, please see the PR (#2785) code and the [README](https://github.com/ManaSugi/kata-containers/blob/standard-container-runtime/tools/runk/README.md).

## Status of `runk`

PR link: #2785 

`runk` is currently an experimental tool. Hence, `runk` does not support many features that the existing OCI container runtimes like `runc` have.

**Features compared to `runc`:**

| Feature                                                 | Status                                                                                                                              |
|:--------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------:|
| crictl                                                  | :white_check_mark:                                                                                                                  |
| Docker                                                  | :heavy_multiplication_x:                                                                                                            |
| Podman                                                  | :heavy_multiplication_x:                                                                                                            |
| OCI commands (`state`/`create`/`start`/`kill`/`delete`) | :white_check_mark:                                                                                                                  |
| `run` command                                           | :white_check_mark:                                                                                                                  |
| `spec` command                                          | :white_check_mark:                                                                                                                  |
| `exec` command                                          | :heavy_multiplication_x:                                                                                                            |
| `list` command                                          | :heavy_multiplication_x:                                                                                                            |
| `ps` command                                            | :heavy_multiplication_x:                                                                                                            |
| `pause`/`resume` commands                               | :heavy_multiplication_x:                                                                                                            |
| `update` command                                        | :heavy_multiplication_x:                                                                                                            |
| `events` command                                        | :heavy_multiplication_x:                                                                                                            |
| `init` command                                          | :heavy_multiplication_x:                                                                                                            |
| `checkpoint`/`restore` commands (CRIU)                  | :heavy_multiplication_x:                                                                                                            |
| Foreground terminal mode                                | :heavy_multiplication_x: <br> See the [runc modes].(https://github.com/opencontainers/runc/blob/master/docs/terminals.md#foreground) |
| Cgroups v1                                              | :white_check_mark:                                                                                                                  |
| Cgroups v2                                              | :white_check_mark:                                                                                                                  |
| Systemd Cgroups                                         | :heavy_multiplication_x:                                                                                                            |
| Namespaces                                              | :white_check_mark:                                                                                                                  |
| no pivot_root                                              | :heavy_multiplication_x:  <br> `kata-agent` supports this feature, but `runk` CLI does not have an option to enable this feature currently.                                                                                                                |
| Capabilities                                            | :white_check_mark:                                                                                                                  |
| Seccomp                                                 | :white_check_mark:                                                      |
| AppArmor                                                | WIP on [#2227](https://github.com/kata-containers/kata-containers/issues/2227)                                                      |
| SELinux                                                 | :heavy_multiplication_x:                                                                                                            |
| Rlimit                                                  | :white_check_mark:                                                                                                                  |
| Readonly path                                           | :white_check_mark:                                                                                                                  |
| Masked path                                             | :white_check_mark:                                                                                                                  |
| Hooks                                                   | :white_check_mark:                                                                                                                  |
| Rootless                                                | :heavy_multiplication_x:                                                                                                            |

**Comment by c3d** [comment]
@ManaSugi, as I briefly discussed during a presentation you made earlier, @dgibson and myself am somewhat interested in leveraging `runk` for a few possible additional use cases:

* Invoking the kata agent over the RPC interface (rather than through direct calls), in order to prepare for being able to talk to a confidential container over a secure channel
* Leverage the same command-line interface, but then target the shimv2 interface, in order to provide a wrapper that would restore compatibility with tools like `podman`.

I wanted to know if you thought this was in line with your plans for that work? In order for this to work, we'd have to split the command-line parsing half of `runk` from the execution half, and that execution half would have multiple "back-ends", one for the current implementation, one for indirect calls over RPC, etc.

What do you think?

**Comment by ManaSugi** [comment]
@c3d Thank you for the proposal about new use cases of `runk`.
It's awesome and I'm glad to hear that you can leverage `runk` in those ways.  If we can successfully split `runk` according to each use case, I totally agree with you.
If there is anything I can do, please let me know. 
Thanks.
