### ISSUE TITLE
linting: guestProtection is unused on ARM

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#2801]
As far as **I** can tell, this should trigger on all architectures because two out of TDX+SEV/PEF/SE would be missing on x86_64/ppc64le/s390x too.

Soon to be in https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/qemu_arch_base.go#L156-L174

_Originally posted by @Jakob-Naucke in https://github.com/kata-containers/kata-containers/issues/2774#issuecomment-936092091_

**Comment by jongwu** [comment]
Hello @Jakob-Naucke -, these guestProtection are used in qemu_${arch}_test.go for non-arm, thus golint won't warn. But there is no such implementation for arm64, so the nolint is only for arm64.

**Comment by Jakob-Naucke** [comment]
@jongwu you are right. While `qemu_${arch}.go` only use the respectively supported protection types, `qemu_${arch_except_arm}_test.go` test _all_ the protection types (in the cases of the "foreign" ones, they verify it errors out), e.g. https://github.com/kata-containers/kata-containers/blob/988eb95621b0cea53c78136e1c1b759b64316202/src/runtime/virtcontainers/qemu_amd64_test.go#L268-L272

I concede that this seems at least a bit stupid, but maybe the best way to go forward is to simply add checks like this for all the protection types in `qemu_arm64_test.go`.
