### ISSUE TITLE
why the kata vm bind with host cpu has no expected effect in kata  2.0.1？ 

### ISSUE THREAD

**Issue by lilongjiang1** [kata-containers/kata-containers#2807]
# Description of problem
when we use docker update --cpuset-cpus command in docker+runc，we can see that container thread bind to host cpu as we expected。
But use docker update --cpuset-cpus command in docker+kata 2.0.1，we found that the bind action is done in kata vm，we found nothing happend between kata vm and host cpu。

# Expected result

bind kata vm to host cpu as update request

# Actual result

we found nothing happend between kata vm and host cpu。

# Further information

test with kata 2.0.1

**Comment by devimc** [comment]
afaik docker doesn't support kata 2.0.1 :confused:  :interrobang:

**Comment by lilongjiang1** [comment]
this commit fixed the problem:https://github.com/kata-containers/kata-containers/commit/831224aa224a5d4bf04a21216a4fe8745e2e9549. 

this issuse need to close，thanks

**Comment by lilongjiang1** [comment]
the bug fixed in commit https://github.com/kata-containers/kata-containers/commit/831224aa224a5d4bf04a21216a4fe8745e2e9549.   The issuse could be closed.

**Comment by fidencio** [comment]
Closing per https://github.com/kata-containers/kata-containers/issues/2807#issuecomment-961747833
