### ISSUE TITLE
ARM unit tests are broken

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#2809]
Hello @Amulyam24 -, I run unit test on arm and there are lots of failure, thus you can disable unit test on arm in this PR and I will fix and enable it later.

_Originally posted by @jongwu in https://github.com/kata-containers/tests/issues/4029#issuecomment-932250396_

Tracking here for easier reference, one example failure is:
```
thread 'watcher::tests::create_tmpfs' panicked at 'assertion failed: !is_mounted(WATCH_MOUNT_POINT_PATH).unwrap()', src/watcher.rs:993:9
```

@jongwu if I may :)

**Comment by jongwu** [comment]
thanks @Jakob-Naucke

**Comment by Jakob-Naucke** [comment]
For the first time, I also saw the failure in the OP on s390x; last night in internal CI. Taking a look...

**Comment by Jakob-Naucke** [comment]
reopening -- #2844 fixed another ARM unit test issue, but not this one

**Comment by Jakob-Naucke** [comment]
sorry, that was just a sub-issue, now tracked in #2946. Closing.
