### ISSUE TITLE
Firecracker not working?

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#2818]
I'm having problems getting Firecracker working (with or without jailer) using the static binaries on the GH releases page:

```bash
$ sudo ctr run --runtime "io.containerd.kata.v2" --rm -t "quay.io/prometheus/busybox:latest" foo sh
ctr: failed to create shim: failed to mount "/run/kata-containers/shared/containers/foo/rootfs" to "/run/kata-containers/foo/rootfs", with error: No such file or directory (os error 2): unknown
```

The journal shows:

```
time="2021-10-11T16:51:58.235929419+01:00" level=error msg="container create failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/foo/rootfs\" to \"/run/kata-containers/foo/rootfs\", with error: No such file or directory (os error 2)" name=containerd-shim-v2 pid=3798 sandbox=foo source=virtcontainers subsystem=container
```

Same result using the following versions:

- `2.1.1`
- `2.2.1`
- `2.3.0-alpha0`

Anyone else seeing this and / or interested in helping to debug?

/cc @egernst, @mcastelino

**Comment by eadamsintel** [comment]
Is it expected that Firecracker would work out of the box with `kata-deploy`?  I had a cluster with crio and the latest Kata running and when I tried the `kata-fc` runtime class I had similar errors.  If firecracker can't work out of the box with `kata-deploy` I wonder if it should be included as a runtime class. We don't include a `kata-acrn` runtimeclass. 

```
Warning  FailedCreatePodSandBox  1s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = CreateContainer failed: failed to mount "/run/kata-containers/shared/containers/3eb5a63a639b34d31384cc933f0c2fd5db1ae5653baf76fa3eeb6ce5894466e3/rootfs" to "/run/kata-containers/3eb5a63a639b34d31384cc933f0c2fd5db1ae5653baf76fa3eeb6ce5894466e3/rootfs", with error: ENOENT: No such file or directory: unknown
```

**Comment by fidencio** [comment]
So, I'm closing this issue as we know why firecracker didn't work for @jodh-intel.


Please, feel free to re-open it in case something is still missing.
