### ISSUE TITLE
tests: Improve unit test coverage for rustjail/process.rs for Kata 2.0 agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#285]
The following [`2.0-dev` agent branch](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/agent) file needs more unit tests:

```rustjail/process.rs```

See: https://github.com/kata-containers/kata-containers/issues/275

**Comment by devimc** [comment]
Does anyone know why the code coverage of the struct is 0? in Golang the structs are not considered
Thanks in advance

![rust-codecov](https://user-images.githubusercontent.com/13009432/90257312-a0fb0280-de0c-11ea-8554-01c34d721e16.png)

**Comment by liubin** [comment]
I found this https://github.com/mozilla/grcov/issues/450#issuecomment-640039459 , may be the answer if you are using `grcov`.

**Comment by devimc** [comment]
@liubin  yes I'm using grcov and that's the issue, thanks
