### ISSUE TITLE
Regression for systemd cgroups following last vendoring

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#2868]
As very briefly documented in [a comment attached to PR #2332](https://github.com/kata-containers/kata-containers/pull/2332#issuecomment-947463493) and in a [question asked on containerd/cgroups](https://github.com/containerd/cgroups/issues/209#issuecomment-947466225), it looks like there was a regression introduced with the last vendored version of `containerd/cgroups` regarding the `systemd` case.

@fgiudici is presently investigating more in depth, as it appears to have broken metrics at least in the OpenShift case.

This is distantly related to #2539 insofar as it seems to be impacted by the same vendored code.

**Comment by c3d** [comment]
From @fgiudici:

The cgroups creation complying with the systemd cgroups management has been dropped .
See [kata code](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cgroups/cgroups.go#L125)

What we need seems to be to create the cgroups as explained [in the containerd/cgroups README](https://github.com/containerd/cgroups#create-with-systemd-slice-support)

**Comment by c3d** [comment]
From private exchanges between @fgiudici and myself, it looks like a regression introduced by revendoring:

The cgroups creation (through `containerd/cgroup` code) seems now cgroupfs compliant only (coming to this statement following the links in the above comment)).

Yep, it is a regression. @sameo  changed the cgroups library we used this is why not trivial to spot.
[Previous library had a boolean flag](https://github.com/kata-containers/kata-containers/blob/stable-2.1/src/runtime/virtcontainers/pkg/cgroups/manager.go#L128) to control the creation of the cgroup in cgroupfs vs systemd way, managing all of this transparently using an interface and different back-ends implementing the interface.
Now, with the containerd cgroup code, we have to pass the right hierarchy type (i.e. pass `cgroups.Systemd`) and optionally pre-parse the cgroup path (to comply with the systemd slice format) based on the cgroup driver in use (cgroupfs vs systemd) as showed in the links in the above comment. Samuel just set it statically the cgroupfs way.

**Comment by egernst** [comment]
Francesco, Christophe -- is there an e2e / integration test in place that should've caught this?  (I expect there wasn't?) Can you share a test for reproducing the failure?
