### ISSUE TITLE
CCv0 | rootfs - Need to add CentOS 8.4 into supported OS list

### ISSUE THREAD

**Issue by liangzhou121** [kata-containers/kata-containers#2873]
# Description of problem
- As CentOS, currently rootfs build script only support CentOS 7. But we need to build a guest rootfs image that can be used inside TDX environment. And currently TDX's offical MVP package only supports CentOS 8.4. And we also don't sure whether TDX will support CentOS 7 in future.

# Proposal
- In order to let CCv0 also workable inside TDX, it needs to extend the rootfs build script supported OS list to include CentOS 8.4 also.

**Comment by stevenhorsman** [comment]
We switched the confidential rootfs support to be ubuntu, not centos, so this is no longer applicable.
