### ISSUE TITLE
hypervisor: use consistent logging pattern throughout hypervisor and hypervisor implementation code

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#2884]
var moduleLogger = log.WithField("subsystem", "module")

func (m * M) SetLogger(logger *log.Entry) {
	fields := moduleLogger.Data
	moduleLogger = logger.WithFields(fields)
}

func (m *M) logger() *log.Entry {
	return moduleLogger
}

**Comment by ariel-adam** [comment]
Eric, what is the logging pattern you would like to see here?

**Comment by c3d** [comment]
I'm curious if the code you showed is the pattern you want to apply?
