### ISSUE TITLE
tests: Improve unit test coverage for src/namespace.rs for Kata 2.0 agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#289]
The following [`2.0-dev` agent branch](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/agent) file needs more unit tests:

```src/namespace.rs```

See: https://github.com/kata-containers/kata-containers/issues/275

**Comment by YchauWang** [comment]
Hi @jodh-intel, I would like to work on adding tests to namespaces.rs. Please assign it to me if needed, thanks.
