### ISSUE TITLE
tests: Improve unit test coverage for src/network.rs for Kata 2.0 agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#290]
The following [`2.0-dev` agent branch](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/agent) file needs more unit tests:

```src/network.rs```

See: https://github.com/kata-containers/kata-containers/issues/275

**Comment by wainersm** [comment]
hi @jodh-intel , I was looking at `src/agent/src/network.rs`, and there is already a unit test for the `setup_guest_dns()` method which is the only function provided in the module. So can we close this issue?
