### ISSUE TITLE
clh: need 'fds' in netConfig

### ISSUE THREAD

**Issue by xuhui187** [kata-containers/kata-containers#2904]
Cloud-hypervisor use 'fds' in NetConfig. If using 'fd' in vm config, it won't works.

cloud-hypervisor netConfig struct: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vmm/src/config.rs

![image](https://user-images.githubusercontent.com/34016331/138830574-abf63114-bb81-4732-a1dc-088afc1e946c.png)

**Comment by cmaf** [comment]
Closing this since https://github.com/kata-containers/kata-containers/pull/2903 was closed after deciding PR should be submitted to Cloud Hypervisor
