### ISSUE TITLE
Kata-runtime not support Host networking mode ?

### ISSUE THREAD

**Issue by zhutongcloud** [kata-containers/kata-containers#2912]
**Before raising this question**
I change my k8s cluster node2 runtime to kata-runtime,but flannel and kube-proxy pod is hostnetwork mode,so cause create pod failed.
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               12h                   default-scheduler  Successfully assigned kube-system/kube-flannel-ds-amd64-pqgj9 to node2
  Warning  FailedCreatePodSandBox  24m (x13 over 25m)    kubelet, node2     Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-amd64-pqgj9": Error response from daemon: OCI runtime create failed: Host networking requested, not supported by runtime: unknown
  Normal   SandboxChanged          24m (x12 over 25m)    kubelet, node2     Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  20m (x12 over 20m)    kubelet, node2     Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-amd64-pqgj9": Error response from daemon: OCI runtime create failed: Host networking requested, not supported by runtime: unknown
  Normal   SandboxChanged          44s (x1077 over 20m)  kubelet, node2     Pod sandbox changed, it will be killed and re-created.

[root@node2 ~]# kata-runtime --version
kata-runtime  : 1.11.5
   commit   : 3fc5e06c2e50a265e97aae4b730e21e04969633e
   OCI specs: 1.0.1-dev

Have you looked at our [document](https://github.com/kata-containers/kata-containers/tree/main/docs) and still haven't found the answer?

**Comment by cmaf** [comment]
@zhutongcloud were you able to resolve this with @liubin's suggestion? If so, this issue can be closed.
