### ISSUE TITLE
NVIDIA GPU passthrough not working, QMP fails

### ISSUE THREAD

**Issue by zvonkok** [kata-containers/kata-containers#2938]
### Host
```
OS: Ubuntu 20.04
Kernel: 5.4.0-89-generic
```

### Kata version (also tested with 2.2.x version) 
```
$ kata-runtime -v
kata-runtime  : 2.3.0-alpha2
   commit   : <<unknown>>
   OCI specs: 1.0.2-dev
```
### containerd version 

```
$ ctr -v
ctr containerd.io 1.4.11
```
### Simple Kata containers run without hardware passthrough

```
$ image="docker.io/library/busybox:latest"
$ sudo ctr run --runtime "io.containerd.kata.v2" --rm -t "$image" test-kata uname -r
5.10.25-nvidia-gpu
```

### IOMMU Group with PCIe bridges and a GPU

The GPU is bound to the VFIO driver via kernel command flag since most of the distributions are not building VFIO as a module anymore. 

```
IOMMU Group 66:
	3c:01.0 PCI bridge [0604]:  PCIe Bridge  [13ac:1178] (rev 01)
	3e:00.0 PCI bridge [0604]:  PCIe Bridge [13ac:1178] (rev 01)
	3f:08.0 PCI bridge [0604]:  PCIe Bridge [13ac:1178] (rev 01)
	40:00.0 3D controller [0302]: NVIDIA Corporation Device [10de:0fbb]
```
### Kata with IOMMU Group 66

```
$ sudo ctr run --runtime "io.containerd.kata.v2" --rm -t --device /dev/vfio/66 "$image" test-kata uname -r
ctr: QMP command failed: Device 'vfio-bf35ce81cd1f15c20' not found: not found
```

Followed this guide https://github.com/kata-containers/kata-containers/blob/main/docs/use-cases/Nvidia-GPU-passthrough-and-Kata.md and build the kernel and tried out also various configuration settings in the config file (machine type, etc...) nothing worked. 

In Kata 2.2.0 I got the error message that one of the PCI bridges could not be found rather then the `vfio-xxxxx` device.

Is Kata trying to use all of the devices in an IOMMU Group? 

Does Kata make a differentiation between PCI root, PCI bridges, and the actual devices in an IOMMU group?

**Comment by fidencio** [comment]
@zvonkok, @dgibson has done a bunch of work related to this that is part of the `main` branch now but not yet part of an official release.  The first thing I'd like to ask you is, would it be possible for you to give it a try with latest `main`?

Also, @dgibson, does this ring a bell?

**Comment by zvonkok** [comment]
@fidencio Yes, on it. Will report.

**Comment by zvonkok** [comment]
### Update
Still the same error message

```
$ sudo ctr run --runtime "io.containerd.kata.v2" --rm -t --device /dev/vfio/66 "$image" test-kata uname -r
ctr: QMP command failed: Device 'vfio-4655be9ca1b196770' not found: not found
```

### contained shim v2 version
```
containerd-shim-kata-v2:
  Version:  1.5.7+unknown
  Revision: 
  Go version: go1.13.8
```

### Kata version
```
kata-runtime  : 2.3.0-alpha2
   commit   : e15c8460dbeddfe6a13d03e9c4fd16fc78714a6e
   OCI specs: 1.0.2-dev

```
### git head/main/origin
```
commit e15c8460dbeddfe6a13d03e9c4fd16fc78714a6e (HEAD -> main, origin/main, origin/HEAD)
Merge: 51e9038a e66d0473
Author: Jianyong Wu <jianyong.wu@arm.com>
Date:   Mon Nov 1 10:43:16 2021 +0800
```


### The build scripts only support `yq` version 3, latest (4.2.x)  `yq` fails 

```
 qemu_version=$(get_from_kata_deps "assets.hypervisor.qemu.version")
Error: unknown command "read" for "yq"
Run 'yq --help' for usage.
```

**Comment by zvonkok** [comment]
@dgibson Any pointers?

**Comment by dgibson** [comment]
Hrm.  Unfortunately that `Device 'vfio-bf35ce81cd1f15c20' not found` message doesn't help much with figuring out what's going on, since it's just a generated name with no obvious link to the underlying device.  It's worth seeing if Kata has logged anything more useful to the syslog.

Some assorted points:

- Yes, Kata will use all the devices in the group (there's nothing else it can do: Kata's input in the OCI spec is a VFIO group device node, not PCI addresses, plus a group is the unit of ownership anyway).  The problem might well be related to that
- Possibly we should be explicitly excluding bridge devices from that - their inclusion doesn't make much sense, and could be causing problems.
- Are you using `hotplug_vfio_on_root_bus = true` in your Kata configuration?  Although in many cases that would be the better option, it can't work for this case.  That will attempt to plug every device under a separate PCIe root port in the guest.  That means the devices would be separate IOMMU groups in the guest, and devices which are in the same group in the host must cannot be in different groups in the guest.

> The GPU is bound to the VFIO driver via kernel command flag since most of the distributions are not building VFIO as a module anymore.

- Which distros are those?  There's still a VFIO module in all the ones I've used recently.  In any case having VFIO built in shouldn't prevent you from runtime binding the device to vfio (note that using `driverctl` is nearly always a better idea that manually poking at sysfs, or module/kernel options).

**Comment by zvonkok** [comment]
This is the error message for 2.3.0 (vfio-xxxxx) , in 2.2.0 I had one of the PCI brigdes listed as not found, so Kata tries to use all PCI devices in the group, indeed. 

PCI root or bridges should not be used when doing passthrough. 

`hotplug_vfio_on_root_bus = true` not using this one, I want to keep the host topology, this could break GPUDirect when GPU and NIC are used which are in different IOMMU groups on the host. 

Oh and the distro statement, it is the other way around most of them have the vfio module, some have it builtin like Ubuntu 20.04, thanks for pointing this out. 

Minikube does handle it right, but KVM uses the PCI addr in the virsh config

```
   <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0x3d' slot='0x00' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </hostdev>
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0x40' slot='0x00' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x0a' function='0x0'/>
    </hostdev>
```

Could we add some logic for filtering for an IOMMU group? When the runtime receives the IOMMU Group that it looks only  for the devices that are bound to `vfio-pci` and only uses those devices? 

Something like this: 
```
$ for i in `ls /sys/kernel/iommu_groups/66/devices`
> do PASSTHR=$(basename `readlink /sys/bus/pci/devices/$i/driver`)
> if [ $PASSTHR == "vfio-pci" ]; then echo $i $PASSTHR; fi
done

$ 0000:40:00.0 vfio-pci
```

**Comment by jodh-intel** [comment]
Possibly related (Nvidia GPUs + vfio): #835, #1142, #1704.

**Comment by zvonkok** [comment]
@dgibson In kubeVirt we're providing the PCI addresses for any passthrough device and the UUID of any mediated devices, which would translate to: 

```
# QEMU passthrough
...  -device vfio-pci,host=01:10.0

# QEMU mediated
... -device vfio-pci, sysfsdev=/sys/bus/mdev/devices/<UUID>
```

Rather then passing the whole IOMMU group one could use env vars e.g. to make those things available. 
```
sudo ctr  run --env PCI_PASSTHROUGH=<0000:40:00.0, ...>   --runtime "io.containerd.kata.v2" --rm -t  "$image" test-kata uname -r

# OR

sudo ctr  run --env PCI_MDEV=<UUID0, UUID1, ...>   --runtime "io.containerd.kata.v2" --rm -t  "$image" test-kata uname -r
```
WDYT?

**Comment by dgibson** [comment]
> This is the error message for 2.3.0 (vfio-xxxxx) , in 2.2.0 I had one of the PCI brigdes listed as not found, so Kata tries to use all PCI devices in the group, indeed.
> 
> PCI root or bridges should not be used when doing passthrough.
> 
> `hotplug_vfio_on_root_bus = true` not using this one, I want to keep the host topology, this could break GPUDirect when GPU and NIC are used which are in different IOMMU groups on the host.

I'm not really sure what you mean by this.  Neither mode really preserves the host topology.  Usually I'd say that `hostplug_vfio_on_root_bus = true` would be closer to the host than without (assuming a PCIe host).  As noted this can't be used in your case though.

> Oh and the distro statement, it is the other way around most of them have the vfio module, some have it builtin like Ubuntu 20.04, thanks for pointing this out.
> 
> Minikube does handle it right, but KVM uses the PCI addr in the virsh config
> 
> ```
>    <hostdev mode='subsystem' type='pci' managed='yes'>
>       <source>
>         <address domain='0x0000' bus='0x3d' slot='0x00' function='0x0'/>
>       </source>
>       <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
>     </hostdev>
>     <hostdev mode='subsystem' type='pci' managed='yes'>
>       <source>
>         <address domain='0x0000' bus='0x40' slot='0x00' function='0x0'/>
>       </source>
>       <address type='pci' domain='0x0000' bus='0x00' slot='0x0a' function='0x0'/>
>     </hostdev>
> ```
> 
> Could we add some logic for filtering for an IOMMU group? When the runtime receives the IOMMU Group that it looks only for the devices that are bound to `vfio-pci` and only uses those devices?

How to implement the filtering isn't really a problem, we'd just need to do it.  I think explicitly looking for bridges is probably safer than excluding anything not bound to `vfio-pci`.  If the VFIO group device exists then everything in the group must be either bound to `vfio-pci` or bound to nothing anyway.  The relevance of bridges in this case isn't really that they're bridges, just that they will do their job without any active driver (kernel or userspace) managing them.  They're thus safe (more or less) to ignore, which is not usually true of just about any other device.

**Comment by dgibson** [comment]
> @dgibson In kubeVirt we're providing the PCI addresses for any passthrough device and the UUID of any mediated devices, which would translate to:
> 
> ```
> # QEMU passthrough
> ...  -device vfio-pci,host=01:10.0
> 
> # QEMU mediated
> ... -device vfio-pci, sysfsdev=/sys/bus/mdev/devices/<UUID>
> ```
> 
> Rather then passing the whole IOMMU group one could use env vars e.g. to make those things available.
> 
> ```
> sudo ctr  run --env PCI_PASSTHROUGH=<0000:40:00.0, ...>   --runtime "io.containerd.kata.v2" --rm -t  "$image" test-kata uname -r
> 
> # OR
> 
> sudo ctr  run --env PCI_MDEV=<UUID0, UUID1, ...>   --runtime "io.containerd.kata.v2" --rm -t  "$image" test-kata uname -r
> ```
> 
> WDYT?

Not really applicable to Kata.  kubeVirt has explicitly managed VM objects, and has specific configuration for each one which can include this information.  The information Kata gets is an OCI specification, so what we see is a VFIO group device.

Technically I guess the environment is in there as well, but that's really for consumption by the payload not the runtime, so I don't think configuring ourselves based on that is a good idea.  We will already have to mangle the environment variables created by the SR-IOV plugin to adjust them to guest PCI addresses (#2897) so that the payload can find them correctly.  That's already a layering violation, but we don't really have any option.

**Comment by zvonkok** [comment]
@dgibson Took a look at your PR for SR-IOV, long story short, Kata has a different guest PCI topology, addresses. I understand it is a "hack" but is this something that could be used to bridge the gap until a "clean" solution is developed? 

@jodh-intel You added the VM config to the OCI spec, https://github.com/opencontainers/runtime-spec/blob/main/config-vm.md is there any work going on to extend this interface to make the upper case "better"?

**Comment by dgibson** [comment]
> @dgibson Took a look at your PR for SR-IOV, long story short, Kata has a different guest PCI topology, addresses. I understand it is a "hack" but is this something that could be used to bridge the gap until a "clean" solution is developed?

Sorry, I don't understand what you're asking.  Do you mean #2927?  I don't see how that's applicable to this problem.

**Comment by zvonkok** [comment]
Yes I mean #2927 the SR-IOV plugin will provide ENV variables with PCI addresses that need to be translated to guest PCI addresses. 

The  NV device-plugin will provide ENV variables with PCI addresses  (passthrough) that need to be translated to guest PCI addresses. 

kubeVirt uses those very same ENV variables to configure either the SR-IOV devices or the other passthrough devices as an example. 

You build something for SR-IOV how to correctly handle the ENV var PCI addrs, my question is can we use this very mechanism for passthrough devices which are/ can be provided as an ENV var as well? 

Another question I had is Kata able to handle mediated devices?

**Comment by zvonkok** [comment]
On the command line, rather then providing the iommu group, provide the env var with the pci addrs of the pass-through devices or sriov VF pci addrs.

**Comment by zvonkok** [comment]
> > @dgibson In kubeVirt we're providing the PCI addresses for any passthrough device and the UUID of any mediated devices, which would translate to:
> > 
> > ```
> > # QEMU passthrough
> > ...  -device vfio-pci,host=01:10.0
> > 
> > # QEMU mediated
> > ... -device vfio-pci, sysfsdev=/sys/bus/mdev/devices/<UUID>
> > ```
> > 
> > Rather then passing the whole IOMMU group one could use env vars e.g. to make those things available.
> > 
> > ```
> > sudo ctr  run --env PCI_PASSTHROUGH=<0000:40:00.0, ...>   --runtime "io.containerd.kata.v2" --rm -t  "$image" test-kata uname -r
> > 
> > # OR
> > 
> > sudo ctr  run --env PCI_MDEV=<UUID0, UUID1, ...>   --runtime "io.containerd.kata.v2" --rm -t  "$image" test-kata uname -r
> > ```


Like this, as stated before ^^

**Comment by zvonkok** [comment]
I mean as an addition to the iommu device mounted in we need that nevertheless.

**Comment by dgibson** [comment]
@zvonkok, I guess it would be possible, but I don't really like the idea.

The current handling of the env variables is updating information aimed at the payload to remain accurate for what the payload is going to see.  Actually reading and reacting to the environment variables ourself is a significant step further.  Moreover, only using the devices specified in `process.env` would be taking information from the spec we're not really supposed to be using, and not only using it, but having it override information from the spec we *are* supposed to be using.

In more practical terms, it would mean that in order to use VFIO in a manual created Kata pod (with `ctr` or `crictl`) it would be mandatory to supply the environment variables.  That's not true now for Kata - and is not true for runC pods.  I don't think we want to commit to having behaviour that's different from runC when we don't have to.

**Comment by mythi** [comment]
I'm reading this whole thread so that @zvonkok wants cold-plugged PCI devices into the sandbox and a mechanism to specify which PCI IDs are added?

I understand the OCI part but OTOH, for kubernetes specifically,  we are already seeing other resources moving to cold-plug: CRI just added sandbox CPU/mem resources which is a sum of individual containers resources and kata 's sandbox sizing work (#2941) seems to be building on top. I could see a few reasons why this could be useful for devices too (e.g., device reuse between initcontainers and app containers).

**Comment by zvonkok** [comment]
> I'm reading this whole thread so that @zvonkok wants cold-plugged PCI devices into the sandbox and a mechanism to specify which PCI IDs are added?

Yes and no, the higher level use-case is to do passthrough, mediated devices and VFs (PF also if the dev is managed by a container) into containers, how this is done exactly is secondary. Which PCI ID are added was or is needed since Kata gets the whole IOMMU group and tries to mount all PCIe devices in there, inclusively PCI bridges which fails since those are not bound via VFIO. 

> I understand the OCI part but OTOH, for kubernetes specifically, we are already seeing other resources moving to cold-plug: CRI just added sandbox CPU/mem resources which is a sum of individual containers resources and kata 's sandbox sizing work (#2941) seems to be building on top. I could see a few reasons why this could be useful for devices too (e.g., device reuse between initcontainers and app containers).

@mythi I see, so the question from my side is, where and how are we providing enough information to do passthrough, mediated and VFs in a container. 

There is the CRI, OCI spec and some other unofficial "hacks". Besides that we have also https://github.com/container-orchestrated-devices/container-device-interface that was started to create something like a common device interface. 

I was part of the resources management working group years ago, but I think this group is not active anymore do you guys have any pointers where such things could be discussed more generally?

**Comment by zvonkok** [comment]
I have this working with some hardcoded values for the PCIe-root-port, my GPU has some pretty large BARs: 

```
$ lspci -s d0:00.0 -vv | grep Region
        Region 0: Memory at e7000000 (32-bit, non-prefetchable) [size=16M]
        Region 1: Memory at 222800000000 (64-bit, prefetchable) [size=32G] 
        Region 3: Memory at 223810000000 (64-bit, prefetchable) [size=32M]
```
I have seen some comments from @dgibson that Kata moved to ACPI hotplug and have tested that the "old" fixes do not work anymore (for me at least), especially this #1147 and @Bevisy has also something similar https://github.com/Bevisy/kata-containers/commit/367134903d236147e22dee0bd513f57f64281edf#. 

The only way to get this working was to preallocate enough memory so that the BARs can be mapped. Inspired by this: https://bugzilla.redhat.com/show_bug.cgi?id=1529618 and the comments by @marcel-apf on some other Issues, PRs I went on and did this: 

```
`diff --git a/src/runtime/virtcontainers/qemu.go b/src/runtime/virtcontainers/qemu.go
index 242b3645..f4315f3e 100644
--- a/src/runtime/virtcontainers/qemu.go
+++ b/src/runtime/virtcontainers/qemu.go
@@ -2335,6 +2335,8 @@ func genericAppendPCIeRootPort(devices []govmmQemu.Device, number uint32, machin
                                Slot:          strconv.FormatUint(uint64(i), 10),
                                Multifunction: multiFunction,
                                Addr:          addr,
+                               Pref64Reserve: "64G",
+                               MemReserve:    "32M",
                        },
                )
        }
(END)
```
Could we leverage https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md to set those values per annotation to the PCIe components ? We have already the ["Hypervisor Options"](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md) and hence would just extend them. @jodh-intel FYI 

Related Issues, PRs: https://github.com/kata-containers/kata-containers/issues/835 https://github.com/kata-containers/kata-containers/issues/1704 https://github.com/kata-containers/kata-containers/pull/1147 https://github.com/kata-containers/kata-containers/issues/2938 


`nvidia-smi` with Guest OS driver + toolkit + hook here is the first draft of the documentation update: https://github.com/kata-containers/kata-containers/pull/3907
```
$ sudo ctr --debug run --runtime "io.containerd.kata.v2"  --device /dev/vfio/192  --rm -t "docker.io/nvidia/cuda:11.6.0-base-ubuntu20.04" cuda nvidia-smi
Fri Mar 18 11:09:06 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A30X         Off  | 00000000:02:00.0 Off |                    0 |
| N/A   37C    P0    66W / 230W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by zvonkok** [comment]
Currently testing vGPU aka mdev devices and see some other "weird" errors 
```
ctr: QMP command failed: Bus 'pcie.0' does not support hotplugging: unknown
```

Looks like something gets mixed up and the VFIO of an mdev device is not assigned to a pcie-root-port.

**Comment by dgibson** [comment]
> @dgibson Is there any support for `mdev` devices in Kata?

"Yes" in the sense that there is definitely code that talks about the mediate device case.  I've never tested it though (and don't have hardware to do so).  So it wouldn't surprise me if it's deeply broken.

> Currently testing vGPU aka mdev devices and see some other "weird" errors
> 
> ```
> ctr: QMP command failed: Bus 'pcie.0' does not support hotplugging: unknown
> ```
> 
> Looks like something gets mixed up and the VFIO of an mdev device is not assigned to a pcie-root-port.

Yeah, that looks like it's trying to hotplug directly onto the PCIe root bus, which won't work.

**Comment by zvonkok** [comment]
@jodh-intel @dgibson I will close this issue, I have a fix for the mdev use-case. The other fix I have in the pipeline will also come soon for the BAR sizes.
