### ISSUE TITLE
watcher::tests::test_watch_entries fails occasionally

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#2946]
across [x86_64 and s390x], I can also observe
```
---- watcher::tests::test_watch_entries stdout ----
thread 'watcher::tests::test_watch_entries' panicked at 'assertion failed: `(left == right)`
  left: `"original"`,
 right: `"updated"`', src/watcher.rs:739:9
```

_Originally posted by @Jakob-Naucke in https://github.com/kata-containers/kata-containers/issues/2809#issuecomment-940788225_

This has not been fixed by #2844.

**Comment by Jakob-Naucke** [comment]
@fidencio I _suspect_ this doesn't happen on x86's GHA because its resources are single-threaded. We've seen other problems in the Rust unit tests that were due to multithreading, like #2833.

**Comment by Jakob-Naucke** [comment]
Suspicions around glibc or multithreading could not be confirmed, also I cannot reproduce it on x86 any more. Possibly truly an s390x issue.

**Comment by Jakob-Naucke** [comment]
here's an MWE:
```rust
async fn test_watch_entries() {
    skip_if_not_root!();
    let dir = tempfile::tempdir().expect("failed to create tempdir");
    let (storage0, _) = create_test_storage(dir.path(), "1").await.expect("failed to create storage");
    let (storage1, src1_path) = create_test_storage(dir.path(), "2").await.expect("failed to create storage");
    fs::write(src1_path.join("foo.txt"), "original").unwrap();
    let logger = slog::Logger::root(slog::Discard, o!());
    let mut entries = SandboxStorages { ..Default::default() };
    entries.add(std::iter::once(storage0), &logger).await.unwrap();
    entries.add(std::iter::once(storage1), &logger).await.unwrap();
    fs::write(src1_path.join("foo.txt"), "updated").unwrap();
    assert!(entries.check(&logger).await.is_ok());
    assert_eq!(fs::read_to_string(&entries.0[1].target_mount_point.as_path().join("foo.txt")).unwrap(), "updated");
}
```

when it doesn't work, the logs **don't** have this one line: `Copy from /tmp/.tmpHF7DnG/src2/foo.txt to /tmp/.tmpHF7DnG/dest2/foo.txt`

**Comment by Jakob-Naucke** [comment]
and with some more logging, I can tell that this failure happens iff this https://github.com/kata-containers/kata-containers/blob/e34893a0c470a79a42ca8724d8ea4994ae08520b/src/agent/src/watcher.rs#L156-L163 doesn't find any changed files (which regularly happens on s390x).

**Comment by egernst** [comment]
Interesting! How often do you see t his on your end Jakob?

I assume you're doing something like

while true; do cargo test watcher::tests::test_watch_entries | grep 1\ failed; done ?

**Comment by Jakob-Naucke** [comment]
> How often do you see this on your end Jakob?
> 
> I assume you're doing something like:
> 
> ```
> while true; do cargo test watcher::tests::watch_directory_with_symlinks  2>&1 | grep 1\ failed; echo "."; done
> ```

I run some Highly Advanced Statistics Gathering with sth like
```
for i in {1..100}; do sudo sh -lc "cargo test watcher::tests::test_watch_entries" &> /dev/null && echo success || echo failure; done | sort | uniq -c
```

(test requires root), yeah :) Gives me 35-60% success. The "MWE" above bumps it down to more like 5-15%.

> I think we should introduce a delay in the tests between a write to the filesystem and then scanning the filesystem in order to better ensure it picks up the change the first time.

_I could almost swear I tried that and it didn't work, but_ something like
```diff
diff --git a/src/agent/src/watcher.rs b/src/agent/src/watcher.rs
index b111aa16..50e5f350 100644
--- a/src/agent/src/watcher.rs
+++ b/src/agent/src/watcher.rs
@@ -705,6 +705,8 @@ mod tests {
             .set_len(10)
             .unwrap();
 
+        thread::sleep(Duration::from_secs(1));
+
         // source 1: expect just an update
         fs::write(src1_path.join("foo.txt"), "updated").unwrap();

```

gives me 100% success.

**Comment by egernst** [comment]
That surprises me, as I was thinking the time difference between the write and then reading the filesystem, checking for updated timestamp from the files metadata. (ie, your example is before carrying out the write to the file)

**Comment by egernst** [comment]
Was able to verify this with a simple MWE:

```
    async fn scan_mwe() {
        let source_dir = tempfile::tempdir().unwrap();
        let source_file = source_dir.path().join("1.txt");

        fs::write(&source_file, "original").unwrap();

        let modified = source_file
            .symlink_metadata()
            .unwrap()
            .modified()
            .unwrap();

        //thread::sleep(Duration::from_secs(1));

        fs::write(&source_file, "1").unwrap();

        let new_mod = source_file
            .symlink_metadata()
            .unwrap()
            .modified()
            .unwrap();

        assert!(new_mod > modified, "{:?}, {:?}", &new_mod, &modified);
    }
```

This fails 100% on s390, and a higher percentage of time on x86. From testing, we see that adding a 20ms delay passes 500/500 iterations on s390 (and x86).

It looks like on s390 in particular, there wasn't enough delay during our code execution between consecutive writes to the filesystem, resulting in the timestamp regularly (~50% of time) not being unique by the time we check the filesystem again.
