### ISSUE TITLE
agent: remove_container umounts container_mounts twice

### ISSUE THREAD

**Issue by Burning1020** [kata-containers/kata-containers#2965]
hi, all,
Recently I found something strange that container mountpoints umount twice when agent removes container.
1. https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L261 
2. https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L271

Mount point that umounted in the first place will be umounted again in the second place. So the second umount will return an error when traverse the mount points, leaving the other mount point's refCount not zero. When the container was created again, its storage will not be mounted(refCont is greater than 0) but actually it has been umounted in the first place

**Comment by egernst** [comment]
Thanks for bringing this up @Burning1020!  

Is this something that you would be able to submit a PR to address?

**Comment by Burning1020** [comment]
Sure, i'll submit it several hours later.
But, hasn't anyone reported it ever before as it is a obvious repeat umount call and this bug would possiably have happened at many muilti-mounts scenarios.
Or it's just my fault that soemthing i didn't relized in other codes that could possiably fixes it.

**Comment by Burning1020** [comment]
ping @yyyeerbo @sboeuf @harche

**Comment by egernst** [comment]
@Burning1020 -- can you prepare reproduction example for this? I would assume you saw this when utilizing `crictl`?
