### ISSUE TITLE
when create rootfs with alpine, does it mean use musl libc instead of glibc?

### ISSUE THREAD

**Issue by a74731248** [kata-containers/kata-containers#2983]
just like the title. when I create a rootfs with alpine, does it mean use musl libc rather than glibc?

**Comment by jodh-intel** [comment]
Hi @a74731248 - yes, Alpine doesn't use glibc.

**Comment by a74731248** [comment]
> Hi @a74731248 - yes, Alpine doesn't use glibc.

and is the app run in that container must use musl libc to invoke syscall ?

**Comment by jodh-intel** [comment]
@a74731248 - unless you build a static binary for your workload or do clever things, yes ;) I'm confused though - if you need glibc, why are you using alpine? (and why do you need a particular libc ooi?) osbuilder provides configuration files for lots of other distros so you can choose an alternative if alpine isn't suitable for your use-case.

**Comment by a74731248** [comment]
> @a74731248 - unless you build a static binary for your workload or do clever things, yes ;) I'm confused though - if you need glibc, why are you using alpine? (and why do you need a particular libc ooi?) osbuilder provides configuration files for lots of other distros so you can choose an alternative if alpine isn't suitable for your use-case.

thank you! I am looking for alpine to build a lightweight rootfs and I just want to confirm that your alpine does not use glibc for compability.
