### ISSUE TITLE
Conflict with libvirtd?

### ISSUE THREAD

**Issue by git-noise** [kata-containers/kata-containers#2988]
**Before raising this question**

Have you looked at our [document](https://github.com/kata-containers/kata-containers/tree/main/docs) and still haven't found the answer?

I did and did not find that specific qemu/kvm-related question.

**Question**

When installed via snap on an Ubuntu hypervisor, I observed that their seem to be a conflict between kata-containers and libvirtd, where libvirtd does not seem to be able to find KVM anymore and tries to fall back to another emulated accelerator. Existing VMs run fine, but launching a new one will trigger that error libvirtd side.

Is it an expected behavior where kata-containers and other qemu/kvm manager cannot use the VVM at the same time, or kata "masks" it to other daemons?

**Comment by Jakob-Naucke** [comment]
Hmm. Can you check `/usr/bin/qemu-system-$(uname -m) -version`, is that still the one from system? It should be, but let's just make sure.

**Comment by git-noise** [comment]
Hello @Jakob-Naucke, many thanks for your answer. So it is strange, I re-installed kata via snap again and with the latest version (2.2.3), it seems that this behavior disappeared and now libvirtd seems happy - issue was with the 2.2.2.

To answer your question, qemu version is:
```
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.18)
```
No clue what happened, there, maybe a glitch or something changed in 2.2.3? I will close this for now and revert if I see this happening again?

Best,
