### ISSUE TITLE
Vendored source code not released together with 2.3.0-rc0

### ISSUE THREAD

**Issue by etrunko** [kata-containers/kata-containers#2989]
There is no vendor code tarball released with the latest 2.3.0-rc0 version. It has been used for Fedora packaging for quite some time now, since #2573 was merged.

**Comment by fidencio** [comment]
@etrunko, this is a known issue right now.

The vendored code is uploaded as part of a GitHub action that, post release, will test kata-deploy, tag and upload the kata-deploy image on quay.io and dockerhub, upload the static binaries, and the vendored code.  However, the action is failing (please, see: https://github.com/kata-containers/kata-containers/actions/runs/1426047295).

@bergwolf spent some time debugging it over the weekend, I did some test this afternoon, but I think we will only be able to solve it in the coming day or two.

I will comment here and let you know when it gets solved.  Thanks for the issue report.

**Comment by fidencio** [comment]
@etrunko: https://github.com/kata-containers/kata-containers/releases/tag/2.3.0-rc1

**Comment by etrunko** [comment]
Thank you for the quick response
