### ISSUE TITLE
Detect updated external versions

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#30]
# Problem

We have to poll lots of different sites to find out when external versions change. This is not efficient and we often don't notice when changes occur.

# Background

We use a lot of external resources, some of which are encoded in the versions database in nice, machine-parseable and human-readable YAML:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml

# Solution

We need a "`check-versions`" tool to detect when new versions of these resources change. The simplest approach would probably be to:

- Add in the missing details to `versions.yaml` for:
  - The distro names and versions (and crucially URLs! :) for all the CI slaves we use.
  - Whatever else we've forgotten to add (take a look at the file and see what's missing :)

- Write a golang tool to parse the YAML which can determine new versions of the resources specified in the versions database.

- Run the tool periodically (atleast weekly) which will then send a mail / irc/slack ping when new versions are detected.

It should be possible for anyone to run the tool and see changes. The best location for it is *probably* below https://github.com/kata-containers/tests/tree/master/cmd.

Writing such a tool will no doubt require some changes to the format of `versions.yaml` (maybe to add in RSS feeds [is that still even "a thing"? :)] for things like new distro versions).

# Minimum functionality

We absolutely must be informed automatically about new:

- stable kernel versions (https://kernel.org)
- stable qemu releases.
- distro versions (new Ubuntu release, etc).
- docker versions
- k8s versions
- golang versions

This is a new issue on the same problem described on https://github.com/kata-containers/ci/issues/41. I've moved it here as it's a general problem (plus finding the issue just referenced always takes too long - I should have created it here :)

/cc @egernst, @bergwolf, @grahamwhaley, @chavafg.

**Comment by grahamwhaley** [comment]
yaml driven tool run periodically from Jenkins would be great!
@chavafg already has something internal here - we should check if we can re-use some of that.
The hard bit for Jenkins I think is how to get it to report its findings - do we have an MTA we can use for instance? Or maybe there is a jenkins slack plugin (I'm an email fan, but at least slack is not transient like irc)

**Comment by jodh-intel** [comment]
MTA? No idea :) Also, maybe zuul has such functionality? +1 to slack (and maybe https://gitter.im which is also non-transient, but we'd need to create a channel there first :-).

/cc @cboylan.

**Comment by jodh-intel** [comment]
Making this a P2 as we need this feature and cannot just wait until someone notices such changes :smile:

**Comment by jodh-intel** [comment]
Think security :)
