### ISSUE TITLE
Drop support for ACRN hypervisor until we are able to support with CI.

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#3027]
I am working with community to refactor virtcontainers into better abstractions, including a hypervisor and network pkg, and removing circular dependencies between sandbox, hypervisor, etc.

As part of this I noticed a few challenging points with Acrn. An example, the hypervisor structure today requires Sandbox. With these circular dependencies and lack of any CI for acrn, continued support is going to be very challenging, and I'm sure acrn is or will be broken.

I am looking to drop support for Acrn until we have appropriate / active owners and CI for this hypervisor implementation.

**Comment by egernst** [comment]
related: https://github.com/projectacrn/acrn-hypervisor/issues/5761

**Comment by zmlcc** [comment]
hi @egernst ，is there any detailed plan or schedule about virtcontainers refactoring ？

**Comment by gvancuts** [comment]
Thanks for the heads-up @egernst . I can look at the CI integration piece again (ran out of time/bandwidth at the time :-()

It also sounds though as if the refactoring may require additional engineering support to adapt the ACRN implementation, is that a correct assumption?

Thanks!

**Comment by egernst** [comment]
@gvancuts  - correct, it would require some cleanup / refactoring on the ACRN implementation of the hypervisor interface.

**Comment by gvancuts** [comment]
> @gvancuts - correct, it would require some cleanup / refactoring on the ACRN implementation of the hypervisor interface.

OK, we're looking into this (as well as the CI piece). Will keep you posted.

**Comment by amshinde** [comment]
@vijaydhanraj  I see the hypervisor interface requires the sandbox mainly for this:
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/acrn.go#L232

ACRN needs to update the global block index. We should see if that can be reworked a bit to get rid of the reference. 
@egernst Any ideas since you are already looking at the refactoring work.

**Comment by vijaydhanraj** [comment]
@amshinde thanks, you are right with respect to ACRN. We set `/dev/vda**1**` as the rootfs. 

Any reason to get rid of this logic? or if you have any GitHub issue regarding this, can you please point me to that? Also @egernst if you have any ideas, please do share.

**Comment by amshinde** [comment]
@vijaydhanraj The issue that @egernst is facing while refactoring the code is that the ACRN hypervisor has a reference to sandbox as seen here :
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/acrn.go#L92

What I see is that you require this reference to update the global block index. @egernst is refactoring the code to place the hypervisor in its own go package, however this dependency on the `sandbox` structure in case of ACRN poses a problem to split the hypervisor in its own separate package.

What I can suggest as a quick solution though it isnt the cleaned solution is to update the global block index in the sandbox itself in case of ACRN. It would be something :
```
if sandboxConfig.HypervisorType = AcrnHypervisor {
        if _, err = a.sandbox.GetAndSetSandboxBlockIndex(); err != nil {
		return nil, err
	}
}
```

I suppose this could be added here: https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/sandbox.go#L480.

You could test this change out with an already working stack and see if the works. 
This could atleast unblock @egernst without the need to get rid of ACRN support altogether. Meanwhile you could continue your work on adding a CI for ACRN.

@jodh-intel Wdyt?

**Comment by jodh-intel** [comment]
Thanks @amshinde. That would work. Another approach would be to add a new API to the hypervisor interface that `sandbox.go` would call for all hypervisors to trigger the call you mention. Something like:

```go
type Hypervisor interface {
  HypervisorNeedsGlobalBlockIndex() bool

  // ...
}
```

Or even better something like:

```go
type HypervisorOptions struct {
  NeedSandboxBlockIndex bool

  // ...
}

type Hypervisor interface {
  RegisterHypervisorOptions(options HypervisorOptions) error

  // ...
}
```

(or abuse `HypervisorConfig()`)


That way, any hypervisor can set that value and then the code in `sandbox.go` would call it as appropriate, without having to do an explicit check for ACRN.

**Comment by amshinde** [comment]
> That way, any hypervisor can set that value and then the code in `sandbox.go` would call it as appropriate, without having to do an explicit check for ACRN.

Wouldn't this still need a reference to the sandbox somewhere inside the hypervisor?

**Comment by vijaydhanraj** [comment]
@amshinde thanks for the clarification. Let me try out the suggestions and get back.

**Comment by egernst** [comment]
@vijaydhanraj et al -- you can see the PR that is cleaning the hypervisor here: https://github.com/kata-containers/kata-containers/pull/3028

In particular, I made modifications to acrn which'll allow: acrn to compile, and the unit tests to pass. We should not have the hypervisor code dependent on persist API, nor should we have any knowledge of "sandbox."

You can see the ACRN specific changes here: https://github.com/kata-containers/kata-containers/pull/3028/commits/e6299daf71b557807a28db61ab6fbfa77d63e0ce

**Comment by jodh-intel** [comment]
> Wouldn't this still need a reference to the sandbox somewhere inside the hypervisor?

No - I think folk may have misunderstood - what I'm saying is that by having a hypervisor "register interest" in the sandbox, we could use the code in https://github.com/kata-containers/kata-containers/issues/3027#issuecomment-973909375, but without making it acrn specific as that's slightly kludgy :smile:
