### ISSUE TITLE
CCv0: Add native container image downloading for kata-agent

### ISSUE THREAD

**Issue by arronwy** [kata-containers/kata-containers#3041]
Currently we use [skopeo](https://github.com/containers/skopeo) + [ocicrypt](https://github.com/containers/ocicrypt) for container image downloading and decryption.

But skopeo is a bit heavy and we can use rust crate [oci-distribution](https://github.com/krustlet/oci-distribution) + [ocicrypt-rs](https://github.com/containers/ocicrypt-rs) for image downloading and decryption as a lightweight option.

The final solution will be use [image-rs](https://github.com/confidential-containers/image-rs) for container image download and management.

**Comment by stevenhorsman** [comment]
I think this issue just covered the native integration, not image-rs, so can be closed
