### ISSUE TITLE
CCv0: Some issues arising from merging main branches.

### ISSUE THREAD

**Issue by wllenyj** [kata-containers/kata-containers#3044]
Since we sync the master branch with the CCv0 branch on a weekly basis. This can cause some compatibility issues with the code.
e.g. this patch (https://github.com/kata-containers/kata-containers/commit/8ab90e1068cebffe1055322c843c730677dcd04b) modifies the `utils::get_option` interface, but the code of the CCv0 branch is not modified accordingly, when merging the main branch to CCv0. So a patch needs to be submitted for the fix. 

Or is there any other good way?

**Comment by stevenhorsman** [comment]
Hi @wllenyj - we've recently (last week) changed the strategy from rebasing `ccv0` on `main` each week to merging `main` into `CCv0`, so I wonder if that has caused the issue, or maybe fixed it? How long have you seen the problems. Can you give more details on the `utils::get_option` issue as I thought I'd fixed the conflicts as part of the merge, but maybe missed something?

**Comment by stevenhorsman** [comment]
This has been resolved as `CCv0` is not supported.
