### ISSUE TITLE
agent: musl target build is broken

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#3048]
It seems that `LIBC=xxx` is ignored now?

```
$make LIBC=musl
<snip...>
$ldd target/x86_64-unknown-linux-musl/release/kata-agent
        linux-vdso.so.1 (0x00007fffff9dd000)
        libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007f2c4de30000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2c4da6a000)
        /lib/ld64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f2c4e07e000)
```

**Comment by bergwolf** [comment]
Ok, turns out that I have to disable seccomp support as well.

**Comment by fidencio** [comment]
> Ok, turns out that I have to disable seccomp support as well.

@bergwolf, just thinking out-loud here, but wouldn't be reasonable to keep this issue open and work on our Makefile to disable seccomp when using `LIBC=musl`, unless its usage is explicitly required?

**Comment by ManaSugi** [comment]
@bergwolf @fidencio 
Thank you for the issue.
If `LIBSECCOMP_LINK_TYPE=static`  is not set, the Kata agent tries to link the `libseccomp` dynamically that already exists in the system, so the `kata-agent` binary is generated as above.
I may need to fix the `Makefile` to build the agent with seccomp capability only if `LIBSECCOMP_LINK_TYPE=static` and `LIBSECCOMP_LIB_PATH` environment variables are set as follows.
https://github.com/kata-containers/kata-containers/blob/main/tools/osbuilder/rootfs-builder/rootfs.sh#L579

If the variables are not set, the agent is built with `SECCOMP=no` forcibly.
Could you give me your thoughts? Thank you.
