### ISSUE TITLE
Defer functions never run with os.Exit(0)

### ISSUE THREAD

**Issue by cmaf** [kata-containers/kata-containers#3059]
We use a `defer` function in `Shutdown` [here](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L930) and [here,](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L926) but they never run because of [os.Exit(0)](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L956). See https://pkg.go.dev/os#Exit. This could be fixed by moving the code to just before `os.Exit(0)`, and also before the [`return`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L942) in the `if statement`.

**Comment by Bevisy** [comment]
> We use a `defer` function in `Shutdown` [here](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L930) and [here,](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L926) but they never run because of [os.Exit(0)](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L956). See https://pkg.go.dev/os#Exit. This could be fixed by moving the code to just before `os.Exit(0)`, and also before the [`return`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L942) in the `if statement`.

We can keep the original `defer func()` to take effect in the `if statement` and add the functions that would otherwise be executed in the `defer func()` before os.exit().
