### ISSUE TITLE
Support for host cgroupv2

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#3073]
The current implementation does not support cgroupv2 on the host.

Adding support for the unified cgroup hierarchy would be useful. It is the default on Fedora since (I believe) F31, and is likely to become the default in a no-so-distant release of Red Hat Enterprise Linux and derivative products.

**Comment by zvonkok** [comment]
Do we have any plans for this feature? Arch has v2 as default, Ubuntu 21.10 will ship v2 by default, yes F31 is the first major distro to default to v2

**Comment by surajssd** [comment]
If anyone is trying katacontainers with host supporting cgroupv2 out of the box then their container creation will fail with the following error:

```console
# ctr --debug run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello sh
ctr: failed to create shim: Could not add runtime PID 4321 to sandbox cgroup:  not implemented for cgroup v2 unified hierarchy: unknown
```

Fix it by disabling cgroupv2 by adding the kernel command line param `systemd.unified_cgroup_hierarchy=0`. If you are on Fedora use grubby:

```bash
grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
reboot
```

**Comment by bergwolf** [comment]
@yaoyinnan has started to work on it. @surajssd Are you looking at the same issue as well?

**Comment by yaoyinnan** [comment]
Could you please assign this task to me? I am currently attending a summer code event and solving this problem.

**Comment by surajssd** [comment]
@bergwolf nope I was not looking into it from the perspective of fixing it but rather documenting the current state. Linux distros that have moved to cgroupv2 fail to start kata based containers. And it fails cryptically also it is not documented anywhere so I created a PR to document that currently only cgroupv1 is supported.
