### ISSUE TITLE
packaging: Move away from `hub` and use `gh` instead

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#3083]
**Which feature do you think can be improved?**

Although `hub` is still receiving patches, it hasn't had a release since March 5th, 2020, and in the meantime GitHub has released its GitHub CLI, named `gh`. (Please, see: https://github.com/cli/cli)

**How can it be improved?**

Update the documentation and scripts related to the release process to use `gh` instead of `hub`.
Mind that this is not exactly an 1:1 conversion, but it should be quite close to that,

**Additional Information**

Anything else to add?

Please, grep for "hub_bin" to find places where we do install and utilise `hub`.
```
[ffidenci@ffidenci-desk kata-containers]$ rg hub_bin
tools/packaging/scripts/lib.sh
16:hub_bin="hub-bin"
65:		hub_bin="${cmd}"
68:		hub_bin="${tmp_dir:-/tmp}/hub-bin"
77:	./script/build -o "${hub_bin}"

tools/packaging/release/update-repository-version.sh
204:		${hub_bin} fork --remote-name=fork
206:		${hub_bin} push fork -f "${branch}"
209:		out=$("${hub_bin}" pull-request -b "${target_branch}" -F "${notes_file}" 2>&1) || echo "$out" | grep "A pull request already exists"

tools/packaging/release/tag_repos.sh
179:	if ! "${hub_bin}" release show "${tag}"; then
185:		"${hub_bin}" -C "${repo_dir}" release create ${rc_args} -m "${PROJECT} ${tag}" "${tag}"
```

**Comment by jodh-intel** [comment]
Sounds interesting and I wonder if this would allow us to replace these`hub` scripts with a simpler `gh` one-liner?:

https://github.com/kata-containers/.github/tree/main/scripts

**Comment by jodh-intel** [comment]
/me wonders how long before `gh` gets rewritten in rust too... :smile:

**Comment by jodh-intel** [comment]
Ah - and although `gh` isn't available in Fedora, it is available as a snap:

- https://snapcraft.io/gh

It doesn't appear to be available as a flatpak, but don't try searching on https://flathub.org/ as it won't allow a 2 character search term!

**Comment by fidencio** [comment]
I got it installed on Fedora via third-party repos, see: https://github.com/cli/cli/blob/trunk/docs/install_linux.md#fedora-centos-red-hat-enterprise-linux-dnf
