### ISSUE TITLE
Support "docker run --security-opt "

### ISSUE THREAD

**Issue by nitkon** [kata-containers/kata-containers#31]
# Description of problem

This Docker --security-opt option is not honoured.

# Expected result
The seccomp profile passed inside the VM, should get honoured

# Actual result
The seccomp profile passed gets dropped at the runtime itself and has no effect inside the container.

 cat sleep.json 
{
        "defaultAction": "SCMP_ACT_ALLOW",
        "syscalls": [
                {
                        "name": "nanosleep",
                        "action": "SCMP_ACT_ERRNO"                               
                }               
                        ]
}

docker run -it --security-opt seccomp=sleep.json --runtime kata-runtime busybox sh
/ # sleep 6   ( Sleeps for 6 seconds)
/ #

**Comment by nitkon** [comment]
Related seccomp issues and discussions:
1. kata-containers/agent#104
2. kata-containers/runtime#327
3. https://github.com/kata-containers/runtime/issues/688
4. https://github.com/kata-containers/osbuilder/issues/155

**Comment by jodh-intel** [comment]
Related apparmor issue: https://github.com/kata-containers/runtime/issues/707.
