### ISSUE TITLE
release kata for non-x86 in snapcraft store manually

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#3114]
kata has its latest release in snapcraft store for x86 but not for Arm, ppc and s390 as they lack of  related github action script for release. Thus we need release it manually. How to get there? I think , we can do as following:
when x86 new release kick:

- install kata using snap from the edge channel and test locally. I see the edge channel is the latest release for each arch.
- release kata to stable channel of snapcraft store manually (but for now, I have no idea about how to do it)

@devimc @Jakob-Naucke @Amulyam24 @fidencio

**Comment by fidencio** [comment]
+1 for the effort, @jongwu!

It'll require some effort to coordinate when the release is out and when the other arch builds can be kicked off, but I think it's do-able.  We could give it a try on the release that's planned for next week (the 2.3.0 final release).

About the release process, I think the process will be quite similar to what's done as part of this action: https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/snap-release.yaml, and I think @devimc can add / provide the permissions for the maintainers of different arches to do the release on their side.

**Comment by simos** [comment]
There's [a build-server for snap packages](https://snapcraft.io/build). Have you tried using the build server for the automatic creation of snap packages? Does this project have special build requirements that cannot build the snap packages on the build-server?
