### ISSUE TITLE
How to set Capabilities of the process started by RUN and EXEC cmdline?

### ISSUE THREAD

**Issue by mgjrr** [kata-containers/kata-containers#3115]
I'm using ctr to manuplate containers, but when i using RUN and EXEC like:
`sudo ctr run --runtime io.containerd.kata.v2 --t --rm docker.io/library/fio:v2 kata1 bash`
and
`sudo ctr t exec --exec-id e1 -t  kata1  bash`
the cap of them are
`root@6a68261e48ba:/# cat /proc/self/status |grep Cap`
`CapInh: 00000000a80425fb`
`CapPrm: 00000000a80425fb`
`CapEff: 00000000a80425fb`
`CapBnd: 00000000a80425fb`
`CapAmb: 0000000000000000`

I want them to have more capabilities like CAP_SYS_ADMIN.
Hoping for your help.

**Comment by ManaSugi** [comment]
@mgjrr 

Unfortunately, `ctr` does not support Linux Capabilities control flags currently, so you cannot set them directly. If you want to have more capabilities like `CAP_SYS_ADMIN`, you can use `--privileged` flag. However, the flag has some problems when you use it in Kata containers as mentioned by #2467.
Please check [the comment](https://github.com/kata-containers/kata-containers/issues/2689#issuecomment-926799282).

FYI, just now, I sent a [PR](https://github.com/containerd/containerd/pull/6289/commits/95b3ab2a4ac7707044e5cb9d53835434a642c375) that adds the flags (`--cap-add` and `--cap-drop`) to `ctr` in the mainline.
If you want to control Capabilities (`--cap-add` and `--cap-drop`) right now, please checkout [my branch](https://github.com/ManaSugi/containerd/tree/add-ctr-caps) and run `make`. 

```
$ sudo ./bin/ctr run --runtime io.containerd.run.kata.v2 --cap-add "CAP_SYS_ADMIN" --rm docker.io/library/busybox:latest foo cat /proc/self/status | grep Cap
CapInh: 00000000a82425fb
CapPrm: 00000000a82425fb
CapEff: 00000000a82425fb
CapBnd: 00000000a82425fb
CapAmb: 0000000000000000
```

**Comment by mgjrr** [comment]
@ManaSugi 

Your branch solved my problem perfectly, thank you so much!

**Comment by ManaSugi** [comment]
That's great. After my PR is merged into upstream, please switch from my branch to upstream :)

**Comment by ManaSugi** [comment]
I close this issue because it has been already solved.
