### ISSUE TITLE
experimental and vanilla kernels are the same kernel

### ISSUE THREAD

**Issue by devimc** [kata-containers/kata-containers#3119]
http://jenkins.katacontainers.io/job/kata-containers-2.0-kernel-experimental-x86_64-nightly/ and http://jenkins.katacontainers.io/job/kata-containers-2.0-kernel-vanilla-x86_64-nightly/  are basically the same kernel, is this expected?

cc @wainersm @jcvenegas

**Comment by wainersm** [comment]
Hi @devimc , to be honest I don't know much about the experimental kernel so when I created both jobs I didn't check whether the experimental kernel were still used or not. Therefore, the jobs are same except that [kata-containers-2.0-kernel-experimental-x86_64-nightly](http://jenkins.katacontainers.io/job/kata-containers-2.0-kernel-experimental-x86_64-nightly) does  export `experimental_kernel=true`

**Comment by jcvenegas** [comment]
@devimc  those should not be the same,  a good question should be cached kernel somewhere

**Comment by jcvenegas** [comment]
@devimc let me take a look to the ci jobs

**Comment by devimc** [comment]
moving issue to https://github.com/kata-containers/tests/issues/4453
