### ISSUE TITLE
Corrupted `initrd` images in static archives 

### ISSUE THREAD

**Issue by pete842** [kata-containers/kata-containers#3144]
# Description of problem

Many released static archives (`kata-static-<version>-x86_64.tar.xz`) contain a corrupted `initrd` image.

# Expected result

It should contains a valid `initrd` image.

# Actual result

Corrupted `initrd` images are `gzip` compressed empty files.

# Further information

- Latest valid `initrd` image was shipped with tag `2.2.0-alpha1`
- All static archives released from tag `2.2.0-rc0` to `2.3.0-rc1` contain corrupted `initrd` 
- Valid `initrd` images can however be compiled using `tools/osbuilder`.

**Comment by fidencio** [comment]
/cc @jcvenegas 
Carlos, if you happen to have some cycles, mind to take a look at this one?

I think this one is a release blocker.

**Comment by Bevisy** [comment]
@fidencio @jcvenegas By looking at the github action logs, it looks like the build environment is missing the `cpio` command causing the build to fail
```sh
INFO: Creating /home/runner/work/kata-containers/kata-containers/tools/osbuilder/kata-containers-initrd.img based on rootfs at /home/runner/work/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build/build/rootfs-initrd/builddir/initrd-image/alpine_rootfs
/home/runner/work/kata-containers/kata-containers/tools/osbuilder/initrd-builder/initrd_builder.sh: line 77: cpio: command not found
```
