### ISSUE TITLE
Power (ppc64le) Travis builds are failing

### ISSUE THREAD

**Issue by bpradipt** [kata-containers/kata-containers#315]
# Description of problem

Power travis builds are failing

# Expected result

Power travis builds should work

# Actual result
The Power travis build fails with the following error:
```
Could not execute command /usr/bin/qemu-system-ppc64le --version
--- FAIL: TestQemuPPC64leMemoryTopology (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```
The issue was reported by @jodh-intel [here](https://github.com/kata-containers/kata-containers/pull/225#issuecomment-640522052). The failure comes from the following [code](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/qemu_ppc64le_test.go#L44) which executes qemu to get it's version. Since we use a `setup_type == minimal` for travis, qemu doesn't get installed and  consequently the test fails.

The reason why the specific approach to detect qemu version in unit test was added is mentioned in the following PR -https://github.com/kata-containers/runtime/pull/1309

For Power we do no support running with older qemu (<4.x) and hence the approach doesn't really make sense. It should be possible to have the same approach for the unit test cases like the other supported Kata architectures.

**Comment by ariel-adam** [comment]
The issue has been resolved in PR #316. 
Closing this issue.
