### ISSUE TITLE
Task: Run basic functionality tests with virtiofsd

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#3155]
This is the first step for #3036 

The objective is to manually replace the C version with the Rust version and run some basic testing to get an idea whether it makes sense to run more advanced tests.

**Comment by fidencio** [comment]
I've done that as reported on https://github.com/kata-containers/kata-containers/issues/3036#issuecomment-1026219261.
Right now, using v1.1.0 it works as a drop-in replacement for what we support by default on Kata Containers.

Also, there are some bits known to be missing, that already have PRs opened.  Regardless of those, as they're not default options, we'd be good to go for running more extensive tests in the CI.
