### ISSUE TITLE
virtiofsd-rs: Run end-to-end tests to compare with regular virtiofsd

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#3156]
This task is part of #3036 and can be done once we have positive results for #3155.

Once we know that `virtiofsd-rs` passes a basic sanity tests, we can run complete end-to-end tests to be able to compare how well it behaves relative to the previous `virtiiofs`.

**Comment by fidencio** [comment]
Got `integration/kubernetes` testing passing as expected with both QEMU and Cloud Hypervisor, thus, closing this one!
