### ISSUE TITLE
CCv0 kata-deploy should also support image

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#3160]
In #3127, I claimed that image (rather than initrd) would not work with confidential containers, as I had found even `/tmp` to be unwritable on images (which, in general, are mounted read-only). This is not true, something:tm: was off with my setup. The kata-deploy workflow should also support image alongside initrd. For the very short term, a consumable end-to-end demo remains a higher priority.

/cc @bpradipt @sameo

**Comment by stevenhorsman** [comment]
`CCv0` has been dropped and the code merged into `main`, so this is no longer applicable
