### ISSUE TITLE
CCv0: EAA BKC module should also be supported in rootfs image (ubuntu)

### ISSUE THREAD

**Issue by liangzhou121** [kata-containers/kata-containers#3167]
Currently EAA KBC module isn't supported by CCv0 rootfs image. 
And build ubuntu rootfs image with "AA_KBC=eaa_kbc" option will exit with failure.

/cc @Jakob-Naucke @jodh-intel

**Comment by Jakob-Naucke** [comment]
*grumble* I linked that one before merge! *grumble*
