### ISSUE TITLE
Port rootfs access fix to rust agent.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/kata-containers#317]
We need to apply this to the rust agent: 
https://github.com/kata-containers/agent/pull/792

Since this is a security fix, we need to prioritize this.

**Comment by amshinde** [comment]
@bergwolf @lifupan

**Comment by lifupan** [comment]
> @bergwolf @lifupan

@amshinde   I'll take a look.

**Comment by bergwolf** [comment]
fixed by #319
