### ISSUE TITLE
Deprecation messages about Kubernetes APIs from the CI

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#3191]
Observed running a local CI:

```
Warning: node.k8s.io/v1beta1 RuntimeClass is deprecated in v1.22+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

I suspect the complaint is more about `v1beta1` than about `RuntimeClass` or `PodSecurityPolicy`. We should fix that before having to switch to k8s 1.25.

**Comment by c3d** [comment]
@wainersm @bpradipt Co-assigned it to you to get your advice on the best course of action.

**Comment by fidencio** [comment]
Please, whoever will work on this, pretty please, mind: https://kubernetes.io/releases/.

If something is deprecated in v1.21+, we can only drop it when v1.20 reaches its EOL (which should happen in 2022-02-08).
If something is deprecated in v1.22+, we can only drop it when v1.21 reaches its EOL (which should happen in 2022-06-28).

**Comment by fidencio** [comment]
Let me close this one in favour of https://github.com/kata-containers/kata-containers/issues/3185, which was opened first.

**Comment by fidencio** [comment]
@c3d, I just noticed that @liubin's issue only covers the RuntimeClass case, which is a straightforward move.

Your issue, OTOH, mixed two problems together.  Would be possible to open a new issue specifically about the PSP?  Please, link https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ on the issue that you open.
