### ISSUE TITLE
Refine directory for v3.0

### ISSUE THREAD

**Issue by jiangliu** [kata-containers/kata-containers#3204]
**Is your feature request related to a problem? Please describe.**

Currently there is only one component written by rust under `src/`, and the subdirectories under `/src` is grouped by subsystem/binary as.
```
drwxr-xr-x  18 liujiang  staff  576 Dec  4 11:55 agent
drwxr-xr-x  19 liujiang  staff  608 Dec  4 11:44 runtime
drwxr-xr-x   7 liujiang  staff  224 Dec  4 11:44 trace-forwarder
```
There are going to be more binaries/components developed by rust for v3.0, which will share some codes with `agent`. So we need to find out a way to organize code for v3.0. 

**Describe the solution you'd like**
A proposal to improve the directory organization as below:
```
src/agent-rs               // renamed from current agent, with a `-rs` suffix
src/image-tools            // example new components/binaries for v3.0
src/libs                   // dir to host shared libraries, which may get published to crates.io
src/libs/kata-protocol-rs  // kata communication protocol between runtime and agent, moved from agent/protocols
src/libs/shim-protocol-rs  // containerd shim-v2/v3 protocol
src/runtime-rs             // runtime written by rust, namely we `runD`
src/runtime                // v2 runtime in go
src/trace-forwarder        // current trace-forwarder
```

**Describe alternatives you've considered**
We may also keep current directory structure and add `runtime-rs` dir as:
```
drwxr-xr-x  18 liujiang  staff  576 Dec  4 11:55 agent
drwxr-xr-x  19 liujiang  staff  608 Dec  4 11:44 runtime
drwxr-xr-x  19 liujiang  staff  608 Dec  4 11:44 runtime-rs
drwxr-xr-x   7 liujiang  staff  224 Dec  4 11:44 trace-forwarder
```
But this directory doesn't show clear dependency among components. `runtime-rs` will depend on `agent`, and they are both workspaces. In future with more components, the dependency graph may get complex and even circular.

**Comment by bergwolf** [comment]
While at it, I think we should move `pkg/logging` to `src/libs/logging`, and `tools/agent-ctl/` to `src/tools/agent-ctl/`. `image-tools` can separately live in `src/tools` as well. IWO, I'm thinking a structure like:
```
└── src
    ├── agent-rs
    ├── libs
    │   └── logging
    ├── runtime
    ├── runtime-rs
    └── tools
        ├── agent-ctl
        └── trace-forwarder
```

@jodh-intel WDYT? This will move agent-ctl, logging and trace-forwarder.

**Comment by bergwolf** [comment]
Let's keep the agent code under `agent` instead of `agent-rs` to avoid breaking too many ongoing PRs, and since we don't have a go-agent there so it looks fine. I'll prepare a PR to do the change.

**Comment by jodh-intel** [comment]
+1 from me @jiangliu and @bergwolf!
