### ISSUE TITLE
Alpine rootfs is much bigger in Kata 2 -- 113 MB vs 14 MB

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#3216]
We build our own rootfs based on alpine and previously had noted the size of the kata-containers-initrd.img...
Kata 1.12 -- 14 MB
Kata 2.3.0 -- 113 MB

It looks like most of this is coming from /usr ...
```
/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/rootfs # du -hs *
2.1M	bin
4.0K	dev
1.3M	etc
4.0K	home
0	init
4.7M	lib
4.0K	media
4.0K	mnt
4.0K	opt
4.0K	proc
4.0K	root
4.0K	run
16M	sbin
4.0K	srv
4.0K	sys
4.0K	tmp
294M	usr
52K	var

/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/rootfs # du -hs usr/*
68M	usr/bin
20M	usr/include
91M	usr/lib
76M	usr/libexec
36K	usr/local
20K	usr/sbin
39M	usr/share
1.6M	usr/x86_64-alpine-linux-musl
```

Not sure of all this stuff is really needed or if the agent is statically compiled

**Comment by liubin** [comment]
This commit https://github.com/kata-containers/kata-containers/commit/eb5dd76e9da1331aecce409d956a2520a6e08a78 installs many packages.

**Comment by fidencio** [comment]
> This commit [eb5dd76](https://github.com/kata-containers/kata-containers/commit/eb5dd76e9da1331aecce409d956a2520a6e08a78) installs many packages.

Hmm.  Let me cc @Jakob-Naucke.

We should be able to only install the packages to build the agent, without increasing the final size of the rootfs image.

**Comment by Jakob-Naucke** [comment]
Hi @skaegi! I overlooked that in Alpine specifically, we don't seem to bootstrap an extra rootfs, but we bootstrap the rootfs from the build container itself. I guess for musl agents (the only ones we (can) use in Alpine), building in a container is not strictly necessary (unlike for glibc agents, where the glibc version must match), but an external bootstrap (similar to `debootstrap` or `dnf --installroot`) would be nicer if possible.

**Comment by Jakob-Naucke** [comment]
Yup, my "partial revert" in #2399 was too partial, https://github.com/kata-containers/kata-containers/commit/76c18aa3454ee7acdc6870b779d617ae26fdced8#diff-eb4755613b9e0aaba0a824cbea01194f29ea0e29a698f77839acf0ffb232b076L35-L40 should also have been brought back (we used to use `apk.static` and moved to "copy a good part of the rootfs" at one point for some reason). This _looks_ like an easy fix.

**Comment by Jakob-Naucke** [comment]
yup, I can just checkout https://github.com/kata-containers/kata-containers/commit/76c18aa3454ee7acdc6870b779d617ae26fdced8 on `tools/osbuilder/rootfs-builder/alpine/rootfs_lib.sh` and get a working, 7.6M initrd. PR pending.
