### ISSUE TITLE
kata-deploy writes invalid containerd config unless already existing

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#3229]
When using containerd, kata-deploy amends some runtime classes to `/etc/containerd/config.toml`: https://github.com/kata-containers/kata-containers/blob/712c5ac6baaade8c85775e5f0875dbc4a9d6f3b3/tools/packaging/kata-deploy/scripts/kata-deploy.sh#L172-L177
This means that when `config.toml` does not exist already, it will only consist of Kata runtime classes, which causes errors:
```
Dec 07 19:57:22 ubuntu2 containerd[4307]: time="2021-12-07T19:57:22.405372205Z" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="invalid plugin config: no corresponding runtime configured in `containerd.runtimes` for `containerd` `default_runtime_name = \"runc\""
…
Dec 07 19:58:06 ubuntu2 kubelet[4460]: E1207 19:58:06.532224    4460 remote_runtime.go:86] "Version from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Dec 07 19:58:06 ubuntu2 kubelet[4460]: E1207 19:58:06.532484    4460 kuberuntime_manager.go:230] "Get runtime version failed" err="get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Dec 07 19:58:06 ubuntu2 kubelet[4460]: E1207 19:58:06.532633    4460 server.go:294] "Failed to run kubelet" err="failed to run Kubelet: failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
```

and events like
```
  Warning  FailedScheduling  3m29s  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.`.
```

A fix might be to dump a `containerd config default` when the file doesn't exist, but since this is pretty much my first time using kata-deploy, I'd like to hear more seasoned experts' opinions first :)
Haven't checked CRI-O.

**Comment by fidencio** [comment]
This is a **non tested** patch, but if you find some time to give it a try, I'd appreciate and then I can open a PR for that;
```sh
[fidencio@kundera kata-deploy]$ git diff
diff --git a/tools/packaging/kata-deploy/scripts/kata-deploy.sh b/tools/packaging/kata-deploy/scripts/kata-deploy.sh
index abdfc677..0d0afcec 100755
--- a/tools/packaging/kata-deploy/scripts/kata-deploy.sh
+++ b/tools/packaging/kata-deploy/scripts/kata-deploy.sh
@@ -266,6 +266,11 @@ function main() {
 
                containerd_conf_file="${containerd_conf_tmpl_file}"
                containerd_conf_file_backup="${containerd_conf_file}.bak"
+       else
+               # runtime == containerd
+               if [ ! -f "$containerd_conf_file" ]; then
+                       containerd config default > "$containerd_conf_file"
+               fi
        fi
 
        action=${1:-}
```

There are other fixes that may be needed, from a quick look at that file.

CRI-O should simply work without issues as we drop the configuration on its snippets folder.

**Comment by egernst** [comment]
If containerd isn't already configured, should we expect Kata to be able to be installed, anyway?

Does the cluster/node work already when the config.toml isn't present (ie, if not present is containerd working without issue?)?

**Comment by Jakob-Naucke** [comment]
You can have a working Kubernetes on default containerd config, yes.

**Comment by Jakob-Naucke** [comment]
@fidencio I tested your patch, it seems to work. (Btw, be careful when copying from a terminal, tabs might be translated to spaces.)
