### ISSUE TITLE
Consider splitting up the architecture document

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3246]
The [architecture document](https://github.com/kata-containers/kata-containers/blob/main/docs/design/architecture.md) is quite large (see also the pending PR #3195 I've opened to update it).

I'm wondering if it makes sense to divide it up into separate files to make it more manageable to read and update. Something like:

- `architecture.md`

   The main doc.

- `architecture-history.md`

  As @eadamsintel notes in #3195, maybe the history isn't relevant for some readers and may distract from the description of the current architecture?

- `architecture-storage.md`:

  Storage is a big topic which arguably needs its own document. The main doc can cover the high-level overview and then refer to the storage doc.

- `architecture-networking.md`

  Same as storage: there are many networking options, concepts and details to explain that may be better in a separate doc.

wdyt @amshinde, @devimc, @jcvenegas, @bergwolf, @egernst, @sameo?

**Comment by devimc** [comment]
I like the idea, architecture document is humongous, I'd suggest to create a new su-bdirectory for the architecture, WDYT?

```
docs/
├── code-pr-advice.md
├── design
│   ├── arch-images
│   ├── architecture
│   │  ├── architecture.md
│   │  ├── storage.md
│   │  ├── networking.md
│   │    .......................
│   ├── data
├── Developer-Guide.md
├── Documentation-Requirements.md
....

```

**Comment by jodh-intel** [comment]
@devimc - yep - better still! We should rename `architecture/architecture.md` to `architecture/README.md` for discoverability though.

**Comment by mcastelino** [comment]
@jodh-intel I can work on the networking bits. I would need some help from @amshinde to cover some of the newer changes.

**Comment by jodh-intel** [comment]
Thanks @mcastelino !

**Comment by jodh-intel** [comment]
Considering https://github.com/kata-containers/kata-containers/pull/3195#discussion_r762619969, we could also add an `architecture/history.md` doc.

**Comment by jodh-intel** [comment]
Based on the current section structure on #3195, the following file structure is starting to emerge:

```
architecture/
  README.md
  history.md
  background.md
  guest-kernel.md
  guest-images.md
  hypervisors.md (probably merge with https://github.com/kata-containers/kata-containers/blob/main/docs/hypervisors.md)
  storage.md
  networking.md
  kubernetes.md
  appendices.md
```
