### ISSUE TITLE
Add support for IBM Z

### ISSUE THREAD

**Issue by alicefr** [kata-containers/kata-containers#33]
This issue tracks the Kata support for s390 architecture.

- Agent:
  - console big endian bug 
      - [x] issue: https://github.com/kata-containers/agent/issues/410
      - [x] pr: https://github.com/kata-containers/agent/pull/411
- Runtime: 
   - Type of Statfs_t struct: 
      - [x] issue: https://github.com/kata-containers/runtime/issues/908
      - [x] pr: https://github.com/kata-containers/runtime/pull/909)
  - console big endian bug 
      - [x] issue: https://github.com/kata-containers/runtime/issues/921
      - [x] pr: https://github.com/kata-containers/runtime/pull/922
  - s390x support:
     - [x] issue: https://github.com/kata-containers/runtime/issues/666
     - [x] pr: https://github.com/kata-containers/runtime/pull/990
  - vendor govmm with s390x support:
     - [x] issue: https://github.com/kata-containers/runtime/issues/983
     - [x] pr: https://github.com/kata-containers/runtime/pull/984

  - verify vsock
     - endianess bug:
          - [x] issue: https://github.com/kata-containers/runtime/issues/947
          - [x] pr: https://github.com/kata-containers/runtime/pull/952
          - [x] issue: https://github.com/kata-containers/runtime/issues/958
          - [x] pr: https://github.com/kata-containers/runtime/pull/960
- govmm
   - s390 support preparation:
        - [x] issue: https://github.com/intel/govmm/issues/61
        - [x] pr: https://github.com/intel/govmm/pull/64
   - s390 support
        - [x] issue: https://github.com/intel/govmm/issues/37
        - [x] pr: https://github.com/intel/govmm/pull/68
    - change cid vsock type
        - [x] issue: https://github.com/intel/govmm/issues/70
        - [x] pr: https://github.com/intel/govmm/pull/71
- Osbuilder: 
     - [x] issue: https://github.com/kata-containers/osbuilder/issues/197 
     - [x] pr:https://github.com/kata-containers/osbuilder/pull/196
     - image 
        - [x]  issue: https://github.com/kata-containers/osbuilder/issues/226
   - fedora:
     -  [x] issue: https://github.com/kata-containers/osbuilder/issues/217
     -  [x] pr: https://github.com/kata-containers/osbuilder/pull/218
- Packaging
   - configure-hypervisor.sh
       - [x] issue: https://github.com/kata-containers/packaging/issues/324
       - [x] pr:https://github.com/kata-containers/packaging/pull/333
  - Snap support for IBM Z
       - [x] issue: https://github.com/kata-containers/packaging/issues/341
       - [x] pr: https://github.com/kata-containers/packaging/pull/342
- Tests
  - Update scripts to run CI on s390x
       - [x] issue:https://github.com/kata-containers/tests/issues/1129
       - [x] pr: https://github.com/kata-containers/tests/pull/1130
   - Remove the disable for CPU hotplug test cases
       - [x] issue: https://github.com/kata-containers/tests/issues/1203
       - [x] pr:https://github.com/kata-containers/tests/pull/1204
   - Add cri-containerd testsuite
       - [ ] issue: https://github.com/kata-containers/tests/issues/1211
- Kernel configs
    - [x] issue: https://github.com/kata-containers/packaging/issues/246
    - [x] pr: https://github.com/kata-containers/kata-containers/issues/33
    - Enable vsock
         - [x] issue:https://github.com/kata-containers/packaging/pull/275
         - [x] pr: https://github.com/kata-containers/packaging/pull/275
    - Update s390 kernel config for 4.19.8
         - [x] issue: https://github.com/kata-containers/packaging/issues/280
         - [x] pr: https://github.com/kata-containers/packaging/pull/281
    -  Fix CPU hotplug config
         - [x] issue: https://github.com/kata-containers/packaging/issues/339
         - [x] pr: https://github.com/kata-containers/packaging/pull/340
- CI systems:
   - [ ] issue: https://github.com/kata-containers/ci/issues/57
   - Ubuntu
   - Other distros:
      - [ ] docker binaries: https://github.com/kata-containers/tests/issues/910

- OBS distro packages:
   - issue: https://github.com/kata-containers/packaging/issues/319
   - Package issue: https://github.com/kata-containers/packaging/issues/328

- Limitations for s390x:
   - vhost-user devices:
      - [x] issue https://github.com/kata-containers/runtime/issues/659
   - memory hotplug:
      - [x] issue: https://github.com/kata-containers/runtime/issues/910
      - [x] pr: https://github.com/kata-containers/runtime/pull/911
  - virtio-blk with devicemapper
     - [x] issue: https://github.com/kata-containers/runtime/issues/1153

- Documentation:
   - [x] issue: https://github.com/kata-containers/osbuilder/issues/198
  -  [x] pr: https://github.com/kata-containers/osbuilder/pull/221

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/ci/issues/57.
