### ISSUE TITLE
virtiofsd log expects to print only error level logs and info level does not expect to print

### ISSUE THREAD

**Issue by MagicStarTrace** [kata-containers/kata-containers#3303]
As shown in the figure below, how should I disable massive log output to syslog? I did not find a place to define the log level

![image](https://user-images.githubusercontent.com/15685376/146631959-ae3c694d-3103-4b3f-b211-8de8807de8ab.png)

**Comment by liubin** [comment]
Now the debug flag is controlled by qemu's debug flag, it's better add an additional config item for virtiofsd.

https://github.com/kata-containers/kata-containers/blob/a40e4877e96fee1b59a6b4a6271ef32c3943d0a9/src/runtime/virtcontainers/qemu.go#L647-L654

/cc @bergwolf @jodh-intel @fidencio @egernst

**Comment by MagicStarTrace** [comment]
> Now the debug flag is controlled by qemu's debug flag, it's better add an additional config item for virtiofsd.
> 
> https://github.com/kata-containers/kata-containers/blob/a40e4877e96fee1b59a6b4a6271ef32c3943d0a9/src/runtime/virtcontainers/qemu.go#L647-L654
> 
> /cc @bergwolf @jodh-intel @fidencio @egernst

Can I modify rsyslog.conf to adjust? Still need to change the configuration of kata
Thank You!

**Comment by liubin** [comment]
Firstly, if you don't need to debug log of Kata Containers, you can disable it, and then the virtiofsd's debug log will be disabled too, so there will be no "noisy" logs.

Secondly, if you want to view kata log, you can use `journalctl -t kata`, with this you will only view kata logs.

Lastly, if you want to disable write virtiofsd log to syslog with kata debug log enabled, modifying [syslog](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-viewing_and_managing_log_files) may be helpful, I'm not sure.

**Comment by MagicStarTrace** [comment]
> Now the debug flag is controlled by qemu's debug flag, it's better add an additional config item for virtiofsd.
> 
> https://github.com/kata-containers/kata-containers/blob/a40e4877e96fee1b59a6b4a6271ef32c3943d0a9/src/runtime/virtcontainers/qemu.go#L647-L654
> 
> /cc @bergwolf @jodh-intel @fidencio @egernst

Now that the logs are getting more and more, I expect to disable them
Because CPU load has been very high 
What can I do now to disable virtiofsd log 

Thank you!

**Comment by jodh-intel** [comment]
@MagicStarTrace - please can you open a new issue for this. Note that there is a [new version of virtiofsd being developed](https://gitlab.com/virtio-fs/virtiofsd) which might also make managing logs easier.

**Comment by liubin** [comment]
@jodh-intel I created a pr #4048  to fix this, PTAL.
