### ISSUE TITLE
www.gnu.org is down and causing all CI's to fail due to ci/install_libseccomp.sh

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3313]
Recent changes to `ci/libseccomp.sh` seem to be causing all the CI's to fail:

```
INFO: Set up libseccomp
++ mktemp -d -t libseccomp.XXXXXXXXXX
+ libseccomp_install_dir=/tmp/libseccomp.SbvP1JHbwz
++ mktemp -d -t gperf.XXXXXXXXXX
+ gperf_install_dir=/tmp/gperf.YswzN0m2kq
+ bash /kata-containers/tools/osbuilder/rootfs-builder/../../../ci/install_libseccomp.sh /tmp/libseccomp.SbvP1JHbwz /tmp/gperf.YswzN0m2kq
/tmp/build-libseccomp.72sur /
Build and install gperf version 3.1
++ handle_error 578
++ local exit_code=7
++ local line_number=578
++ echo 'Failed at 578: bash ${script_dir}/../../../ci/install_libseccomp.sh "${libseccomp_install_dir}" "${gperf_install_dir}"'
++ exit 7
Failed at 578: bash ${script_dir}/../../../ci/install_libseccomp.sh "${libseccomp_install_dir}" "${gperf_install_dir}"
++ error_handler
++ '[' 7 -eq 0 ']'
++ '[' -n '' ']'
+ after_stopping_container
+ return 0
make: *** [Makefile:93: /home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/.ubuntu_rootfs.done] Error 7
[install_kata_image.sh:50] ERROR: sudo -E USE_DOCKER=1 DISTRO=ubuntu make -e image
[install_kata.sh:22] ERROR: .ci/install_kata_image.sh 
[jenkins_job_build.sh:172] ERROR: ci/setup.sh
```

See failing CI's on #3297 for example.

/cc @wainersm.

**Comment by jodh-intel** [comment]
As @liubin has noted (https://github.com/kata-containers/kata-containers/pull/3297#issuecomment-997783126), this problem seems to be because gnu.org is down.

**Comment by jodh-intel** [comment]
I've now merged #3314 as a temporary work around. This begs a few questions though:

- Do we wait for gnu.org to come back online and just revert the change on #3314?

  - We could, but we won't know if gnu have taken steps to avoid this happening again until they issue a report on the outage.

- Do we instead consider switching permanently to http://mirrors.kernel.org/gnu as that is known to have a robust infrastructure?

- Can we switch `ci/install_libseccomp.sh` to make use of the versions database if the snap workflow is now fixed?

  See the comments here: https://github.com/kata-containers/kata-containers/blob/main/ci/install_libseccomp.sh#L25..L30

/cc @wainersm, @devimc.

**Comment by wainersm** [comment]
> I've now merged #3314 as a temporary work around. This begs a few questions though:
> 
>     * Do we wait for gnu.org to come back online and just revert the change on [Switch to GNU mirror as gnu.org is down #3314](https://github.com/kata-containers/kata-containers/issues/3314)?
>       
>       * We could, but we won't know if gnu have taken steps to avoid this happening again until they issue a report on the outage.
> 
>     * Do we instead consider switching permanently to http://mirrors.kernel.org/gnu as that is known to have a robust infrastructure?
> 

I'm okay with switching permanently to mirrors.kernel.org. That domain is maintained by https://www.kernel.org/nonprofit.html which is backed by The Linux Foundation, so I believe they indeed have a robust infra.   

>     * Can we switch `ci/install_libseccomp.sh` to make use of the versions database if the snap workflow is now fixed?
>       See the comments here: https://github.com/kata-containers/kata-containers/blob/main/ci/install_libseccomp.sh#L25..L30
>

I'm not aware of any problem on snap workflow. Given our intrinsic policy of "avoid hard-coded values, use version database", here I am also in favor of using the database.

I spent some minutes investigating on how we could avoid the download and build of libseccomp/gperf, instead we should use the library version provided by the distros. However I didn't find static packages for libseccomp on centos 8, ubuntu 20.04 and fedora 33. Maybe some alternative repositories could provide the package. But anyway, it seems we will need to live with that download-and-build approach...
  
> 
> /cc @wainersm, @devimc.

**Comment by Jakob-Naucke** [comment]
FWIW gnu.org is back

**Comment by fidencio** [comment]
@jodh-intel, this could be closed and the patch could be reverted, no?

**Comment by jodh-intel** [comment]
@fidencio - yep, I've raised #3421 so this issue will be auto-closed when that lands.
