### ISSUE TITLE
cleanup/remove the cli related codes

### ISSUE THREAD

**Issue by lifupan** [kata-containers/kata-containers#332]
**Which feature do you think can be improved?**

Since we won't support the cli mode in  kata2.0, thus it's better to cleanup/remove
those codes used  for cli mode. 

**How can it be improved?**

Describe how specifically you think it could be improved.

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by jodh-intel** [comment]
Don't we still need the cli for `podman`? :confused:

**Comment by bergwolf** [comment]
@jodh-intel We have discussed it several times in different situations. I believe the decision AC have made is to only maintain the shimv2 API for Kata 2.0. For podman, it can also adapt to the v2 shim API if it wants to move to kata 2.x. In the meantime, kata 1.x is in maintenance mode that can live for a long time for legacy users.

**Comment by bergwolf** [comment]
BTW, per [the discussion in podman mailing list](https://lists.podman.io/archives/list/podman@lists.podman.io/thread/FFRDZ74ZYWXFIIMG3NVVQGEAPPYAO55M/#M2MFJK5JN5LB6IQRPG2NVPRL7IXNJHD5), podman is willing to migrate to shimv2, just short of hands right now.
