### ISSUE TITLE
Move agent/oci into libs/oci

### ISSUE THREAD

**Issue by jiangliu** [kata-containers/kata-containers#3348]
**Which feature do you think can be improved?**

The oci crate will be used by runD too, so it would be better to move it into libs/.

BTW, there's another implementation from https://github.com/containers/oci-spec-rs, which provides OCI runtime, image and distribution specs, should we switch to it?

**Comment by lifupan** [comment]
I'd like to use the existing oci temporarily and once  the runtime-rs had merged and stabilized, then we can switch to it for both runtime-rs and agent in the future.
