### ISSUE TITLE
Can Kata Containers version 2.x not be installed on ubuntu 18.04?

### ISSUE THREAD

**Issue by MagicStarTrace** [kata-containers/kata-containers#3352]
I can't find the installation instructions for ubuntu through the following address

https://github.com/kata-containers/kata-containers/tree/main/docs/install

Use the following scheme to install the 1.3 version of kata

ARCH=$(arch)
BRANCH="${BRANCH:-master}"
sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
apt-get update  &&  apt-get -y install kata-runtime kata-proxy kata-shim 

----------------------------------------------
VERSION:
   kata-runtime  : 1.13.0-alpha0

----------------------------------------------

How do I install the latest version of kata 2.* via apt on ubuntu 18.04？
Thank you!

**Comment by jodh-intel** [comment]
Hi @MagicStarTrace - the table here shows the options: https://github.com/kata-containers/kata-containers/tree/main/docs/install#packaged-installation-methods.

For Ubuntu, the simplest and best approach is using snap.

**Comment by MagicStarTrace** [comment]
> Hi @MagicStarTrace - the table here shows the options: https://github.com/kata-containers/kata-containers/tree/main/docs/install#packaged-installation-methods.
> 
> For Ubuntu, the simplest and best approach is using snap.


I want to install on ubuntu, only install kata-runntime 
Is this ok?
https://github.com/kata-containers/kata-containers/blob/2.4.0-alpha0/utils/README.md
Thank You!

**Comment by jodh-intel** [comment]
@MagicStarTrace - you could do that, but a couple of points:

1) Do you _really_ want to install an alpha release?

  Version 2.3.0 might be a better option.

2) Installing with Kata manager will **not** automatically update the installation.

   As shown in the table [here](https://github.com/kata-containers/kata-containers/tree/main/docs/install#packaged-installation-methods), the "automatic" method is not automatically updated, whereas distro packages and snap installs are automatically updated.

   Automatic installs are more suited to developers who just need to install a release quickly. It's not really appropriate for end users but the choice is yours.

**Comment by MagicStarTrace** [comment]
> @MagicStarTrace - you could do that, but a couple of points:
> 
> 1. Do you _really_ want to install an alpha release?
>    Version 2.3.0 might be a better option.
> 2. Installing with Kata manager will **not** automatically update the installation.
>    As shown in the table [here](https://github.com/kata-containers/kata-containers/tree/main/docs/install#packaged-installation-methods), the "automatic" method is not automatically updated, whereas distro packages and snap installs are automatically updated.
>    Automatic installs are more suited to developers who just need to install a release quickly. It's not really appropriate for end users but the choice is yours.

I see that there are many installation methods in the document, is kata-manager.sh the recommended one?

**Comment by MagicStarTrace** [comment]
I successfully installed kata, but the pod has an exception error

![image](https://user-images.githubusercontent.com/15685376/153111389-a0834b41-8fff-48e6-91a1-cacef12ba3c0.png)


Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: /opt/kata/share/defaults/kata-containers/configuration-qemu.toml: host system doesn't support vsock: stat /dev/vhost-vsock: no such file or directory: unknown

**Comment by yaoyinnan** [comment]
Hi @MagicStarTrace, I also encountered this problem and solved it with the following solution.

Before using kata as the runtime, you need to add devices vsock, vhost-vsock, and vhost-net.
It can be added using the following command:
````
$ modprobe vsock
$ modprobe vhost-vsock
$ modprobe vhost-net
````
The following problems may occur when adding:
````
$ modprobe vhost-vsock
modprobe: ERROR: could not insert 'vhost_vsock': Device or resource busy
````
The error may be because vmw_vsock_virtio_transport_common and vmw_vsock_vmci_transport conflict with the vsock and vhost-vsock devices, so just disable them.
````
$ vim /etc/modprobe.d/blacklist-vmware.conf
blacklist vmw_vsock_virtio_transport_common
blacklist vmw_vsock_vmci_transport
````
After that, `sudo reboot`.
The vhost-vsock can then be added using `sudo modprobe vhost-vsock` after reboot.

After that, you can use kata normally. If you have any errors, you can continue to ask questions.

**Comment by MagicStarTrace** [comment]
Thanks, I have installed it successfully

**Comment by cmaf** [comment]
Closing since this issue was resolved.
