### ISSUE TITLE
Backport security fixes into stable releases

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3360]
Backport https://github.com/kata-containers/kata-containers/pull/3297 into the latest two stable releases.

This isn't going to be that trivial given the missing dependent changes in the stable branches.

**Comment by fidencio** [comment]
This is currently covered by https://github.com/kata-containers/kata-containers/pull/3368

**Comment by jodh-intel** [comment]
Thanks @snir911 and @fidencio - closing as fixed.
