### ISSUE TITLE
Can we restore the Debian rootfs ？

### ISSUE THREAD

**Issue by zhaojizhuang** [kata-containers/kata-containers#3372]
Hi, community. Unfortunately found that Debian rootfs has been removed in PR #3154 for lack of maintainers.
Our team is still using the Debian rootfs in production environment , and ... can we restore this PR? 
And If there is no one to maintain it, I‘m willing to maintain this rootfs

cc @GabyCT @jodh-intel 
cc @liubin

**Comment by liubin** [comment]
cc @fidencio @bergwolf

**Comment by fidencio** [comment]
@zhaojizhuang, that's great news!

Would be amazing to restore the Debian rootfs and in the process add some tests to ensure it actually works as expected.
Please, feel free to open a PR restoring it and adding the tests, and mark me to review it and I'll promptly do.

(and sorry for the delay, just coming back from holidays here).

**Comment by zhaojizhuang** [comment]
@fidencio OK, I will create a PR to restore it

**Comment by zhaojizhuang** [comment]
Another PR will be created to track test case
