### ISSUE TITLE
Update Nvidia GPU doc for containerd

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3379]
https://github.com/kata-containers/kata-containers/blob/main/docs/use-cases/Nvidia-GPU-passthrough-and-Kata.md specifies docker, but [this isn't possible with Kata 2.x](https://github.com/kata-containers/kata-containers/issues/722) so update the doc to specify containerd.

Related: #3378, https://github.com/kata-containers/community/issues/246.

**Comment by jodh-intel** [comment]
Does anyone out there have suitable Nvidia hardware and a few cycles to tal at this?

**Comment by Bevisy** [comment]
refer https://github.com/kata-containers/kata-containers/issues/3380#issuecomment-1010058624 , the way which the doc describes already outdated.
I have another solution that supports gpu in kata and it works, but there are still some issues to deal with.
![image](https://user-images.githubusercontent.com/8726659/149117008-6b2cd434-b39a-4243-b857-dd2da8d03383.png)

When the issues are all solved, I can re-update this document.

**Comment by jodh-intel** [comment]
Thanks very much @Bevisy!

**Comment by Jakob-Naucke** [comment]
@Bevisy hey, how did you pass this in k8s? I know `ctr --device`, but I had thought k8s had no correspondent field.

**Comment by Bevisy** [comment]
> @Bevisy hey, how did you pass this in k8s? I know `ctr --device`, but I had thought k8s had no correspondent field.

pls refer https://github.com/NVIDIA/k8s-device-plugin#running-gpu-jobs

**Comment by zvonkok** [comment]
@jodh-intel I am leading the effort at NVIDIA to enable Kata with GPUs and other accelerators, what is the process of adding me to the areas of interest? 

Besides that we need also to move this issue further: https://github.com/kata-containers/kata-containers/issues/2938, Kata handles GPUs fine if they are connected to a PCI-root port or the IOMMU group has no PCI bridge or switch. 

I have the hardware and infrastructure to test GPU, vGPU, passthrough, and other accelerators we might need to enable specific use-cases. We can update these parts as well. 

I can add the parts that are currently missing in the documentation.

**Comment by jodh-intel** [comment]
Thanks @zvonkok! I've added you to https://github.com/kata-containers/community/wiki/Areas-of-interest#gpu and assigned this issue to you.
