### ISSUE TITLE
test-kata-deploy is failing to cleanup on aks

### ISSUE THREAD

**Issue by snir911** [kata-containers/kata-containers#3429]
# Description of problem

When trying to remove deployed kata that was deployed with kata-deploy cleaning up process is failing
This is also causing test-kata-deploy to fail

# Expected result

kata and all kata-deploy related resources are removed and cleaned successfully

# Actual result
test-kata-deploy [fails](https://github.com/kata-containers/kata-containers/runs/4760012461?check_suite_focus=true) with :
```
daemonset.apps/kubelet-kata-cleanup created
+ timeout=120
+ waitForLabelRemoval 120
+ wait_time=120
+ sleep_time=5
+ echo 'waiting for kata-runtime label to be removed'
+ [[ 120 -gt 0 ]]
waiting for kata-runtime label to be removed
++ kubectl get nodes --selector katacontainers.io/kata-runtime
++ grep NAME
+ [[ -z NAME                       STATUS   ROLES   AGE     VERSION ]]
+ sleep 5
+ wait_time=115
.
.
.
+ echo 'failed to cleanup'
633
+ return 1
634
+ destroy_aks
```
(on 2.3.1)
when running locally i get on the kubelet-kata-cleanup pod:
`0/1     Error `
`Back-off restarting failed container`
and the container logs:
`/opt/kata-artifacts/scripts/kata-deploy.sh: line 272: /etc/containerd/config.toml: No such file or directory`

# Further information

I think the issue is caused by the fact 8457150684a8bf5920da8de62c6fd9f1035334ce is trying to create the containerd's conf file also on the [clean up pod](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml) which is missing this path mount and i think runtime bin is also missing

* I encountered this when i sent PR for 2.3.1, however, test-kata-deploy has passed when 2.4.0-alpha1 released although i'd expect it to fail there as well

**Comment by snir911** [comment]
More info:
Although test-kata-deploy [passed](https://github.com/kata-containers/kata-containers/runs/4724384188?check_suite_focus=true)  when 2.4.0-alpha1 PR sent, running the very same kata-deploy-ci image used there locally is also failing at clean up.
Hence i believe kata-deploy is currently failing both in main and stable

**Comment by snir911** [comment]
Despite the #3433 test-kata-deploy still fails (both on main and stable) with the same error `kube-system pod/kubelet-kata-cleanup-2gnxl 0/1 CrashLoopBackOff `(tested with this dummy [PR](https://github.com/kata-containers/kata-containers/runs/4804134838?check_suite_focus=true) actions doesn't use the PR itself).

As locally i encountered the same error and locally it's fixed now, i assume the root cause for the seen error is different (i tend to believe it is related to infra changes in aks or the runner and not changes on our side)
* when test-kata-deploy checked out at f9b4d0b60e2c54114e982eb4979ce6842b27d977 it worked, any later test-kata-deploy was failing
* getting the logs from failing pods and print them would be a good start.

**Comment by wainersm** [comment]
Hi @snir911 ,

> Despite the #3433 test-kata-deploy still fails (both on main and stable) with the same error `kube-system pod/kubelet-kata-cleanup-2gnxl 0/1 CrashLoopBackOff `(tested with this dummy [PR](https://github.com/kata-containers/kata-containers/runs/4804134838?check_suite_focus=true) actions doesn't use the PR itself).

I was looking at the dummy [PR](https://github.com/kata-containers/kata-containers/runs/4804134838?check_suite_focus=true) results and I noticed that in the agentpool node the `katacontainers.io/kata-runtime=clean` label exist: 
```
node/k8s-agentpool-72780039-0 Ready agent 5m57s v1.20.5 agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,katacontainers.io/kata-runtime=cleanup,kubernetes.azure.com/cluster=kata-deploy-cf464668ff,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-agentpool-72780039-0,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_D4s_v3,storageprofile=managed,storagetier=Premium_LRS,topology.kubernetes.io/region=westus2,topology.kubernetes.io/zone=0
```
However on the master node the label doesn't exist, which seems to mean the cleanup ran correctly in that node:
```
node/k8s-master-72780039-0 Ready master 5m57s v1.20.5 beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/cluster=kata-deploy-cf464668ff,kubernetes.azure.com/role=master,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-master-72780039-0,kubernetes.io/os=linux,kubernetes.io/role=master,node-role.kubernetes.io/master=,node.kubernetes.io/exclude-disruption=true,node.kubernetes.io/exclude-from-external-load-balancers=true,node.kubernetes.io/instance-type=Standard_D2_v2,topology.kubernetes.io/region=westus2,topology.kubernetes.io/zone=0
```

Was kata really installed on the agentpool node?

**Comment by snir911** [comment]
@wainersm i can't tell, when i ran it locally i used single node k8s
I think it's fine, i supposed kata is not deployed on master, here's a working [reference](https://github.com/kata-containers/kata-containers/runs/4724384188?check_suite_focus=true)

**Comment by snir911** [comment]
Apparently the failure appeared due to environment change ( ubuntu-20.04 [20211219.1](https://github.com/kata-containers/kata-containers/runs/4724384188?check_suite_focus=true#:~:text=https%3A//github.com/actions/virtual%2Denvironments/blob/ubuntu20/20211219.1/images/linux/Ubuntu2004%2DREADME.md) -> ubuntu-20.04 [20220111.1](https://github.com/actions/virtual-environments/blob/ubuntu20/20220111.1/images/linux/Ubuntu2004-Readme.md), however aks engine is identical AFAIU)
See [these](https://github.com/kata-containers/kata-containers/runs/4724384188?check_suite_focus=true) **two** attempts, checked out at the same commit, same ci-kata-deploy image, first attempt passed, the latter failed. AFAICT the only change is the virtual environment that updated and  i'm not sure what exactly is causing it (in any case printing more logs would be beneficial).

**Comment by snir911** [comment]
It seems the error we are having on aks was indeed fixed by https://github.com/kata-containers/kata-containers/pull/3433, which was also [backported](https://github.com/kata-containers/kata-containers/pull/3561) to stable (tested [here](https://github.com/kata-containers/kata-containers/actions/runs/1757667665)).
The reason it seemed this fix is not helping on main was due to to a bug (https://github.com/kata-containers/kata-containers/issues/3559) which caused kata-deploy to use wrong image (without the fix), this is now fixed https://github.com/kata-containers/kata-containers/pull/3560 and should pass on main.
2.3.1 release is still [not passing](https://github.com/kata-containers/kata-containers/runs/4995638390?check_suite_focus=true) as it does not include the mentioned fix (https://github.com/kata-containers/kata-containers/pull/3561), this should be address in separate, closing.
