### ISSUE TITLE
kata-deploy action is used against wrong branch

### ISSUE THREAD

**Issue by snir911** [kata-containers/kata-containers#3443]
# Description of problem

Running **test-kata-deploy** on **stable** branch is actually running against **main**, generates image and tarball containing **main** branch artifacts

# Expected result

**test-kata-deploy** running on **stable** should run against **stable** and generate **stable** artifacts

# Actual result

**test-kata-deploy** running on **stable** generates **main** based artifices (and IIUC also runs against **main** branch)

# Further information
To validated
1. take the kata-deploy-ci image hash used for a test-kata-deploy action running on stable branch
2. run container using this image and inspect the artifacts (under /opt/) e.g
`docker run -it quay.io/kata-containers/kata-deploy-ci:97e18cf2d0d1a83b139c5117299c1766b6365a22 bash`
(taken from [2.3.1 action](https://github.com/kata-containers/kata-containers/runs/4760012461?check_suite_focus=true))

* It means any kata-deploy changes currently done on stable won't affect (changes on main will)
* Also see, https://github.com/fidencio/kata-containers/commit/edabc1131f45b0c151b0118fd16efd894486e2c8

**Comment by fidencio** [comment]
This is a quite interesting one.

The action used for [testing kata-deploy](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/kata-deploy-test.yaml) is based on the action used to [build the kata-deploy content](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/kata-deploy-push.yaml).  So, both should work in a similar way, right?

Well, they do, apart from this part here:

* [From the test-kata-deploy](https://github.com/kata-containers/kata-containers/blob/7120c789469ed81f2c5cbe4e05960d78c2ca77b5/.github/workflows/kata-deploy-test.yaml#L1-L2):
```
on:
  issue_comment:
    types: [created, edited]
```

* [From the action used to build kata-deploy](https://github.com/kata-containers/kata-containers/blob/7120c789469ed81f2c5cbe4e05960d78c2ca77b5/.github/workflows/kata-deploy-push.yaml#L3):
```
on: [push, pull_request]
```

When taking a look at the [GitHub Actions documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment), I have the amazing suprise that the GITHUB_REF passed is the "default branch".  So, the action is behaving as it's coded to behave.

Digging a little bit more it seems we're not the first ones to face this issue, as shown [here](https://github.com/actions/checkout/issues/331).

I will evaluate the approaches taken there and submit a PR soon.
