### ISSUE TITLE
Is there any way to mount a block device to the kata-container?

### ISSUE THREAD

**Issue by xyz-li** [kata-containers/kata-containers#3467]
We need to read/write a lot of data in the container, and we can mount the data to the container by the way of virtio-fs. But the read/write speed of virtio-fs is very slow, is there any way to mount a block device to the kata-container?

**Comment by liubin** [comment]
@xyz-li are you using K8s? If yes you may be interesting in #3454

**Comment by xyz-li** [comment]
> @xyz-li are you using K8s? If yes you may be interesting in #3454

Yes, I am using k8s. Thanks a lot.

**Comment by cmaf** [comment]
@xyz-li closing since it seems like https://github.com/kata-containers/kata-containers/issues/3454 resolves it, please reopen if you have additional questions or issues
