### ISSUE TITLE
versions: bump to containerd version 1.6

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#3479]
containerd 1.6.0-rc0 is available today, and we expect 1.6.0 very soon.

Once available, let's bump our supported version for integration testing to 1.6.  This version will allow for setting an annotation in sandbox containers' spec to determine sandbox sizing details for pods (when utilized with 1.23 Kubernetes). It'll be good to run our integration testing against this.

**Comment by stevenhorsman** [comment]
We've moved to pull in containerd 1.7 now, so this can be closed as completed.
