### ISSUE TITLE
Redefined the data structure for kata config and be able to update kata config securely by annotation

### ISSUE THREAD

**Issue by Tim-0731-Hzt** [kata-containers/kata-containers#3523]
### Support loading config of Kata runtime, hypervisor, and agent from configuration files. 
1. Define mechanisms for hypervisors to handle the configuration info
2. vendors could extend the Kata configuration structure.

### Wrapping TomlConfig into Kataconfig 
The TomlConfig structure is a parsed form of the Kata configuration file, but it's inconvenient to access the configuration information directly. Wrapping it into KataConfig provides an easier way to access it.

### Avoid hypervisor's config being overwritten insecurely
1. config.hypervisor.enable_annotations defines the allowed annotation
    keys for config.hypervisor.
2. config.hyperisor.xxxx_paths defines allowed values for specific keys.
    
### Implement the functionality to update config by annotation

**Comment by jiangliu** [comment]
Closed by #3542
