### ISSUE TITLE
ctr: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-e81d543c22a8779c,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.

### ISSUE THREAD

**Issue by han2ni3bal** [kata-containers/kata-containers#3541]
My kata was running normally on the node before. After I loaded the VFIO-PCI driver for the GPU device and reconfigured the Kata GUEST KERNEL as the GPU SUPPORT, I found that the Kata container could not be started. Later, even after I reinstalled Kata Still getting these errors. I don't know how to deal with it, really appreciate if you  could tell me how to do it. 

##VERSION INFO
K8s version:1.17
Containerd version:1.4.3
Kata version:2.3.0
Linux kernel:4.9.0

## KATA CREATE COMMAND
ctr run --runtime io.containerd.run.kata.v2 -t --rm {IMAGE REF} ubuntu-kata-test /bin/bash

## ERROR INFO
ctr: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-546ec1dca9e93992,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.
qemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-546ec1dca9e93992,tag=kataShared: vhost_backend_init failed: Protocol error
: unknown

## JOURNALCTL -T KATA INFO
time="2022-01-24T13:41:56.790120902+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/fb0241a6dd9342e4bcefae77f56bf19f/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=745742 sandbox=fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51 source=virtcontainers subsystem=firecracker

time="2022-01-24T13:41:57.024965599+08:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51/rootfs\" to \"/run/kata-containers/fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=745742 sandbox=fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51 source=virtcontainers subsystem=kata_agent
time="2022-01-24T13:41:57.04281354+08:00" level=error msg="container create failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51/rootfs\" to \"/run/kata-containers/fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=745742 sandbox=fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51 source=virtcontainers subsystem=container

time="2022-01-24T13:41:57.042873011+08:00" level=warning error="no such file or directory" name=containerd-shim-v2 pid=745742 rootfs-dir=/run/kata-containers/shared/sandboxes/fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51/mounts/fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51/rootfs sandbox=fb0241a6dd9342e4bcefae77f56bf19f0c4f47365fcd1491f85ac973a5e23b51 source=virtcontainers subsystem=mount

## KATA-COLLECT-DATA INFO
time="2022-01-24T13:28:42.838149473+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/f30fe3ccc00416b5a60ad02ab5a7ff6d/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=667765 sandbox=f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87 source=virtcontainers subsystem=firecracker
time="2022-01-24T13:28:42.848979583+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/f30fe3ccc00416b5a60ad02ab5a7ff6d/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=667765 sandbox=f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87 source=virtcontainers subsystem=firecracker
time="2022-01-24T13:28:43.063453287+08:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87/rootfs\" to \"/run/kata-containers/f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=667765 sandbox=f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87 source=virtcontainers subsystem=kata_agent
time="2022-01-24T13:28:43.075826113+08:00" level=error msg="container create failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87/rootfs\" to \"/run/kata-containers/f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=667765 sandbox=f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87 source=virtcontainers subsystem=container
time="2022-01-24T13:28:43.075880598+08:00" level=warning error="no such file or directory" name=containerd-shim-v2 pid=667765 rootfs-dir=/run/kata-containers/shared/sandboxes/f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87/mounts/f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87/rootfs sandbox=f30fe3ccc00416b5a60ad02ab5a7ff6db6a93239c5fb31e91c113a60f1ffdb87 source=virtcontainers subsystem=mount

#### NOTICED
 io.containerd.snapshotter.v1    devmapper                linux/amd64    ok  
Devmapper have been installed

**Comment by han2ni3bal** [comment]
@jodh-intel

**Comment by liubin** [comment]
Hi, @han2ni3bal recently I reviewed some issues due to not-compatible containerd and Kata Containers, so can you try to upgrade your containerd to the latest version and try again?

**Comment by han2ni3bal** [comment]
@liubin Thanks, I will have a try and reply here.

**Comment by han2ni3bal** [comment]
@liubin Hi Mr Liu, 
I have updated containerd to v1.6.0-rc.1
containerd github.com/containerd/containerd v1.6.0-rc.1 ad771115b82a70cfd8018d72ae489c707e63de16.m
And when I run ctr command, it sill showed: 
ctr: failed to create shim task: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-f72aafadbadc04cb,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.
qemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-f72aafadbadc04cb,tag=kataShared: vhost_backend_init failed: Protocol error
: unknown

Now I am thinking that whether is the qemu occurred problem, when I use ./qemu-system-x86_64, it showed qemu-system-x86_64: failed to find romfile "vgabios-stdvga.bin", which looked not right, and the version of qemu is QEMU emulator version 6.1.0 (kata-static)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

**Comment by liubin** [comment]
You may try to re-install Kata Containers from release pages and use the latest version of Kata.

**Comment by han2ni3bal** [comment]
@liubin  I tried to install the 2.3.1 version Kata, but it showed that no image tag 2.3.1 in repository which is true, so do I need to modify the ds config to pull the tag Latest from image repository?

**Comment by han2ni3bal** [comment]
@liubin I use the 2.4.0-alpha1 straightly.

**Comment by liubin** [comment]
Yes, I found that there are no build assets( kata-static-2.x.y-x86_64.tar.xz) in https://github.com/kata-containers/kata-containers/releases too for 2.3.1

**Comment by han2ni3bal** [comment]
@liubin Hi, now, my containerd version is  v1.6.0-rc.1 and kata version is :
kata-runtime  : 2.4.0-alpha1
commit   : 3704f2aadf8a6f5e473fedb651e3773ab32bb0b5
OCI specs: 1.0.2-dev
But it still shows :   
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-1fcb49a0fd9086a9,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.
qemu-system-x86_64: -device vhost-user-fs-pci,chardev=char-1fcb49a0fd9086a9,tag=kataShared: vhost_backend_init failed: Protocol error
: unknown

I think this may be the error from qemu-system-x86_64, I can use this binary alone ,when I use it ,it still shows  qemu-system-x86_64: failed to find romfile "vgabios-stdvga.bin".

I google this error but did not get a good solution, do u have any thoughts about it?

**Comment by han2ni3bal** [comment]
@liubin Oh another thing is that I truly have the file vgabios-stdvga.bin in both of my /usr/share/qemu and /usr/share/qemu-kvm, I don't know how kata use the binary file qemu-system-x86_64 to search these files.

**Comment by liubin** [comment]
Isn't your kernel is old?

**Comment by han2ni3bal** [comment]
@liubin Thanks for your patiently replies. 
I thought about this issues, but as I mentioned, I have successfully used Kata before in this node and there was no error occur, but suddenly, after I tried to build the guest kernel, it won't work anymore even after I re-install Kata on this host, and Idk why. My linux kernel version is 4.9.2-3.0.0.std7b.el7.5.x86_64 btw.

**Comment by liubin** [comment]
Are you using the matching virtiofsd and qemu?

**Comment by han2ni3bal** [comment]
@liubin 
I use Kata deploy to install kata, which contains qemu and virtiofsd insise. So I think if installing is correct and no error occurs, the virtiofsd and qemu are matching automatically?

**Comment by han2ni3bal** [comment]
@liubin 
The error message : " vhost_backend_init failed"
Is it possible that my kernel mods like Vsock or Vhost-net have some issues? Cause I know that if the Qemu will init vhost-user devices when it starts and I think the error occurs in this step, so I wonder maybe my dev face some problem.

**Comment by han2ni3bal** [comment]
@liubin 
I just tested my vhost-user using C/S mode and it works well.

**Comment by han2ni3bal** [comment]
@liubin Hi, I swift to a 5.4 version kernel linux, it seemed that the kata-qemu could run on this machine which needs a further test but I met some issues with kata-fc, do we need to use devmapper for fc now?
Kata version: 2.4.0-alpha1
Containerd version: 1.5.2
Linux kernel:5.4

Here is the error log: 

Recent  problems found in system journal:
```
time="2022-01-19T13:11:26.634241513+08:00" level=warning msg="failed to get OOM event from sandbox" error="rpc error: code = Internal desc = " name=containerd-shim-v2 pid=431555 sandbox=5297504526dfd5bef204f7233f7efc0fea7c765f78b6dd68594ed422e3155859 source=containerd-kata-shim-v2
time="2022-01-26T15:26:54.999939905+08:00" level=warning msg="failed to get OOM event from sandbox" error="rpc error: code = Internal desc = \"\"" name=containerd-shim-v2 pid=1239063 sandbox=f0bd1547fc6f84dd55f3bd2b04c1b68f2ed669e34bbbd655f38936fa8c15a81a source=containerd-kata-shim-v2
time="2022-01-26T15:39:50.901902573+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/94b5059de8067824bc714a6aa312daad/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=1504820 sandbox=94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202 source=virtcontainers subsystem=firecracker
time="2022-01-26T15:39:50.913104111+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/94b5059de8067824bc714a6aa312daad/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=1504820 sandbox=94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202 source=virtcontainers subsystem=firecracker
time="2022-01-26T15:39:51.290884799+08:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202/rootfs\" to \"/run/kata-containers/94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=1504820 sandbox=94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202 source=virtcontainers subsystem=kata_agent
time="2022-01-26T15:39:51.291464785+08:00" level=error msg="container create failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202/rootfs\" to \"/run/kata-containers/94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=1504820 sandbox=94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202 source=virtcontainers subsystem=container
time="2022-01-26T15:39:51.291698157+08:00" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1504820 rootfs-dir=/run/kata-containers/shared/sandboxes/94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202/mounts/94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202/rootfs sandbox=94b5059de8067824bc714a6aa312daad20939b010753c69e4b2661fb606df202 source=virtcontainers subsystem=mount
time="2022-01-26T15:40:05.165863967+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/94f04cbee5e56cdf6bd3db3787b53723/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=1505733 sandbox=94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f source=virtcontainers subsystem=firecracker
time="2022-01-26T15:40:05.177566623+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/94f04cbee5e56cdf6bd3db3787b53723/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=1505733 sandbox=94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f source=virtcontainers subsystem=firecracker
time="2022-01-26T15:40:05.188717219+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/94f04cbee5e56cdf6bd3db3787b53723/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=1505733 sandbox=94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f source=virtcontainers subsystem=firecracker
time="2022-01-26T15:40:05.560715402+08:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f/rootfs\" to \"/run/kata-containers/94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=1505733 sandbox=94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f source=virtcontainers subsystem=kata_agent
time="2022-01-26T15:40:05.561089221+08:00" level=error msg="container create failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f/rootfs\" to \"/run/kata-containers/94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=1505733 sandbox=94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f source=virtcontainers subsystem=container
time="2022-01-26T15:40:05.561334937+08:00" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1505733 rootfs-dir=/run/kata-containers/shared/sandboxes/94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f/mounts/94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f/rootfs sandbox=94f04cbee5e56cdf6bd3db3787b53723eb4e04dbc8f0ddbeb9a346d638dee22f source=virtcontainers subsystem=mount

**Comment by han2ni3bal** [comment]
@jodh-intel

**Comment by han2ni3bal** [comment]
Hi @liubin  I uses the another nodes with kernel 5.4 resolved this issues, really thanks for your kindly answers!!!!!

**Comment by fighterhit** [comment]
I also encountered this problem, my kata version is 2.3.2, and the host kernel version is also 4.9.0. So what is the root cause of this problem?
