### ISSUE TITLE
configure-hypervisor: states require 5.0; Kata now requires 6.1 is a minimum version

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#3547]
With the  ACPI PCI hotplug changes introduced in 2.3, we require QEMU >= 6.1.  The hypervisor configuration script needs updating to reflect this. See:
https://github.com/kata-containers/kata-containers/blob/016569fd8e0158f709ff23e0f32567bc9918ca26/tools/packaging/scripts/configure-hypervisor.sh#L547

**Comment by bergwolf** [comment]
I wonder which commit brought in the breaking change and if it is possible to restore the backward compatibility to a certain level. v6.1 is really brand new...
