### ISSUE TITLE
When using ctr to run kata container with --net-host, the host networking for the container is diabled.

### ISSUE THREAD

**Issue by han2ni3bal** [kata-containers/kata-containers#3556]
when using sudo ctr -n k8s.io run --net-host --runtime "io.containerd.runc.v2" --rm -t "tensorflow-gpu-1.15.0-xm1.0.0-py3:0.1" gputest /bin/bash, the host networking works.
But when I use sudo ctr -n k8s.io run --net-host --runtime "io.containerd.kata-clh.v2" --rm -t "tensorflow-gpu-1.15.0-xm1.0.0-py3:0.1" gputest /bin/bash, the host networking is not works.
How can I enable host networking inside the container?

**Comment by han2ni3bal** [comment]
I know Kata uses some limitations on the networking, but how can I ，like, install the packages normally inside the container if the kata cannot share the networking with hosts?

**Comment by liubin** [comment]
Kata Containers can work with CNI plugins, so if you configure it with an IP address that can access external network then you should be able to install packages inside containers.
