### ISSUE TITLE
Automatic backporting of pull requests

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#3618]
**Is your feature request related to a problem? Please describe.**

Our development workflow expect the contributor to label his/her pull requests (PR) with `needs-backport` or `no-backport-needed` (and variants for forward porting). There is even the [Require PR porting labels](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/require-pr-porting-labels.yaml) Github action on our repositories to ensure that PRs are properly labeled. In case the pull PR was tagged with `needs-backport` the contributor needs to...well, you know...create the backport PR! However, this process is time-consuming and usually mechanical as often commits can simply be cherry-picked.

Some problems arise from that: 
 * Many PRs are backported not by the original contributor but rather by the developer working on the stable release. Again, it is time consuming as she/he needs to scan a bunch of merged PRs to find candidates;
 * One developer backporting someone else PRs can be error prone as she/he can pick some fixes but forget others that are complementary to fix a major problem;
 * Developers may simply put the label `no-backport-needed` as a automatic reaction because she/he doesn't completely understand the process and/or thinks the PR isn't entitled for backport and/or lack time to create another PR (so simply avoid that problem). 

**Describe the solution you'd like**

@GabyCT brought to discussion on https://github.com/kata-containers/kata-containers/issues/2429 some other aspects of backporting which makes it hard on our project. She suggests better documentation. While she is correct, I went further and drafted a proposal of automation for the backport process in https://github.com/kata-containers/kata-containers/issues/2429#issuecomment-912728980 . Bear in mind I just threw some ideas...help is needed to shape a solution.

**Describe alternatives you've considered**

If you have alternatives, please let us know.

/Cc @ariel-adam @chavafg maybe it is a good candidate for internship  programs (GSoC, etc).

/Cc @kata-containers/architecture-committee your input is highly appreciated.

/Cc @snir911 for bravely work on the stable releases, you may have some ideas too :)

**Comment by snir911** [comment]
Sounds good to me, I'd give it a try, of course auto backporting will fail from time to time, however, i think there are more chances to succeed to cherry-pick when it's done alongside the original PR.
I'd suggest to let the bot to work for a while without to enforce/force merge/label polices and see how it goes (yes it may pollute our PR list a bit, we can define testing period maybe)

**Comment by fidencio** [comment]
@wainersm, +1 for the idea.  I'd take a look on the actions CRI-O has, as they have a `cherry-pick` command that users can call, and the bot would then generate the PR.  I think one way to go would be using what they have and expanding to do it automatically, based on the labels, after the PR gets merged.

If the backport fails, well, then someone does it manually. :-)

**Comment by bookinabox** [comment]
After playing around with some of the actions in the marketplace
1. https://github.com/sqren/backport-github-action seems to work well.

Unlike some of the other actions on the marketplace it supports multiple commits per PR, which is nice.

It basically relies on one label to mark the branch to be auto backported +  labels to whichever branches we want to backport to. By default it creates the PRs on merge.

2. I wasn't sure where the action in the CRI-O repo that allows cherry-picking to work was, but the[ CLI version of the above action](https://github.com/sqren/backport) does have a lot of flexibility in how to generate a backport including an interactive cherry-picking configuration.

3. I haven't yet tested how well the action works across forks, but based on the documentation it should work fine. Unfortunately GitHub doesn't let me fork a repo multiple times so I might have the make another account to mess around with it.

4. Besides that, I'm working on adding the backporting label if there is a Bug label in the issue. We can use that label as the trigger for auto backporting.

I'll comment again if I have more progress.
