### ISSUE TITLE
Add TDx Support with Cloud Hypervisor

### ISSUE THREAD

**Issue by likebreath** [kata-containers/kata-containers#3632]
**Which feature do you think can be improved?**

With recent developments from Cloud Hypervisor on TD-shim support (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3444), we are ready to add the TDx support with Cloud Hypervisor in Kata.

**How can it be improved?**

Following the TDx support with QEMU in Kata (https://github.com/kata-containers/kata-containers/pull/1590), we can start with adding the `confidential_guest` support of TDx with Cloud Hypervisor in Kata.

/cc @sboeuf @rbradford @devimc  @fidencio @chavafg Please feel free to extend/correct me. Thank you.

**Comment by sboeuf** [comment]
The question is, what is missing for the Cloud Hypervisor driver in Kata to support TDX. For sure you're gonna need the `tdx` parameter to which you would provide the `tdshim` binary. But what about device creation? I mean it's not possible to hotplug devices with TDX, so you must ensure this wouldn't happen. @devimc is this something you handled directly from the QEMU driver in Kata, or is it at a higher layer so that Cloud Hypervisor will benefit from it for free?

**Comment by devimc** [comment]
> is this something you handled directly from the QEMU driver in Kata, or is it at a higher layer so that Cloud Hypervisor will benefit from it for free?

No, cloud-hypervisor should handle it

**Comment by fidencio** [comment]
@devimc, @sboeuf, @likebreath, @rbradford, maybe a silly question, but I'd like to have a little bit more context here.

Taking a look at https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/intel_tdx.md I couldn't find a reference for `--tdx` and the `tdshim` binary.

What'd be the command line that should be used? Where's the `tdshim` coming from? Will this be part of the kata-containers configuration file?

@devimc , when you say "cloud-hypervisor should handle it", do you mean on our side or on the cloud-hypervisor project's side? Or both?

**Comment by devimc** [comment]
> when you say "cloud-hypervisor should handle it", do you mean on our side or on the cloud-hypervisor project's side? Or both?

sorry I missed the word **driver** - No, cloud-hypervisor driver (kata side) should handle it

**Comment by sboeuf** [comment]
> @devimc, @sboeuf, @likebreath, @rbradford, maybe a silly question, but I'd like to have a little bit more context here.
> 
> Taking a look at https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/intel_tdx.md I couldn't find a reference for `--tdx` and the `tdshim` binary.

I'll update the docs on the Cloud Hypervisor repo.

> What'd be the command line that should be used? Where's the `tdshim` coming from? Will this be part of the kata-containers configuration file?

Just so that you're not blocked until I update the docs, here is the correct way of running Cloud Hypervisor with TdShim for direct kernel boot:

```
./cloud-hypervisor \
    --tdx firmware=tdshim \
    --kernel bzImage \
    --cmdline "root=/dev/vda1 console=hvc0 tdx_allow_acpi=MCFG rw" \
    --cpus boot=1 \
    --memory size=1G \
    --disk path=tdx_guest_img
```

Assuming the first partition is the Linux partition.

**Comment by devimc** [comment]
@sboeuf have tdx support landed in cloud-hypervisor? I'm using main branch

```
./cloud-hypervisor --tdx firmware=tdshim 
error: Found argument '--tdx' which wasn't expected, or isn't valid in this context
```

**Comment by fidencio** [comment]
This one depends on: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3700

**Comment by fidencio** [comment]
This one depends on: https://github.com/kata-containers/kata-containers/issues/3663
