### ISSUE TITLE
update_spec_pci() is never called

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#3634]
# Description of problem

Commit `78dff468bf1` introduced code to translate k8s supplied `PCIDEVICE_*` environment variables for the change in PCI addresses between host and guest when using VFIO devices with Kata.  The actual applying of this translation to the spec is done by `update_spec_pci()`... which is never called, apart from in its own unit test.  Oops.

# Expected result

`PCIDEVICE_*` environment variables are translated when `vfio_mode = vfio` is configured.

# Actual result

`PCIDEVICE_*` environment variables are never translated.

# Further information

This neatly demonstrates the distinction between unit tests and functional / integration tests.  I'll try to make a change to the tests repo as well to add a working test for this.

**Comment by dgibson** [comment]
Created a tests bug to add a test which would catch this here: https://github.com/kata-containers/tests/issues/4432

**Comment by c3d** [comment]
Ooops 😄 

I guess having a real setup to actually test this exposes this kind of problem.

**Comment by bergwolf** [comment]
I wonder why `rustc` didn't catch it as clearly the function is not used. Looks like the `instrument` macros made such compiler check impossible. We need to keep in mind not to rely on the compiler to find it now. /cc @jodh-intel

**Comment by dgibson** [comment]
> I wonder why `rustc` didn't catch it as clearly the function is not used. Looks like the `instrument` macros made such compiler check impossible. We need to keep in mind not to rely on the compiler to find it now. /cc @jodh-intel

Ah.. I did wonder that.  Good to know.
