### ISSUE TITLE
Use a version of Cloud Hypervisor that exposes the possibility to set a TDx config

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#3663]
TDx support has been part of Cloud Hypervisor for a while, but only very recently (https://github.com/cloud-hypervisor/cloud-hypervisor/commit/55479a64d237d4c757dba19a696abefd27ec74fd).

Let's upgrade cloud-hypervisor so we can start landing patches related to the TDx support without having to wait for its official release.

**Comment by rbradford** [comment]
You'll need to compile it with the optional "tdx" feature.
