### ISSUE TITLE
agent: redundant checks for executable files

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#3730]
` 0o777 & 0o111` equals `0o111`

https://github.com/kata-containers/kata-containers/blob/dfbde2e06cd273b03011c4dd78bee912388fdffb/src/agent/src/sandbox.rs#L320-L326

**Comment by Rouzip** [comment]
Hi, I finish this [patch](https://github.com/kata-containers/kata-containers/pull/5496).

**Comment by Rouzip** [comment]
Hi, I finish it in this [pr](https://github.com/kata-containers/kata-containers/pull/5497).
