### ISSUE TITLE
Incorrect comment

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#3750]
Line 757: `2M` should be `4M`

Line 782: `VirtioMem` is set by configuration file or annotation. And `setupVirtioMem` is called only when `VirtioMem` is true.

https://github.com/kata-containers/kata-containers/blob/6a9e5f90f7b69c3c519087106f3b136e3253852b/src/runtime/virtcontainers/qemu.go#L752-L793

**Comment by yaoyinnan** [comment]
@liubin May I take this issue? I would like to take the opportunity to learn this module.

**Comment by liubin** [comment]
@yaoyinnan are you working on this?
