### ISSUE TITLE
packaging: kernel: Add `CONFIG_IA32_EMULATION` to the kernel configuration

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#3759]
It's been reported on #kata-dev that we don't support 32bits workloads due to a kernel limitation on our guest VM, which comes with `CONFIG_IA32_EMULATION` not enabled.

Let's enable it as the first step and also double-check what may be needed on the rootfs side, later on, to fully support such workloads.

**Comment by Greatsamps** [comment]
We have deployed this kernel, but there still appears to be something missing. We can get a simple application such as notepad.exe to run, but when trying to run something more complex, the program crashes.

The application we use uses sockets, and interestingly using this kernel we are also unable to attach to the supervisord socket via supervisorctl

Please see details of a test docker image that can be used.

Once running, you can http to the container on port 8080 and get into a vnc session. to re-produce the fault please run

wine /wine-prefix-32/drive_c/App/app.exe

it will crash after a short period.

the app should load a desktop application if working correctly.

container: greatsamps/dev:app

![Screenshot 2022-02-25 at 08 53 15](https://user-images.githubusercontent.com/19320680/155685704-f492cb42-cf7a-4d19-9dc3-a1bb073d8bbd.png)

**Comment by fidencio** [comment]
I've took a stab and got the following container image working with my own kernel and image built using https://github.com/fidencio/kata-containers/tree/wip/32-bits-compat-with-ubuntu-18.04.

This use case has been briefly discussed in the Architecture Committee of March 8th, 2022, and this was considered a corner case, and whoever is dealing with this corner case should build their own image / kernel for that.

For now, I'm closing this PR and we should consider, maybe, writing a blog post so folks are aware on what to do in case this use-case becomes needed in the future.

I've synced with @Greatsamps privately and I think we're good on this front (but, please, feel free to re-open it in the future)/
