### ISSUE TITLE
optimize: get_paths() called twice

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#3768]
Manager::new will call `get_paths` and `get_mounts` sequentially 
https://github.com/kata-containers/kata-containers/blob/6a11dbfa8a018d46217350dea8803bf28f0dcf2a/src/agent/rustjail/src/cgroups/fs/mod.rs#L955-L962

But `get_mounts` will also call `get_paths`:

https://github.com/kata-containers/kata-containers/blob/6a11dbfa8a018d46217350dea8803bf28f0dcf2a/src/agent/rustjail/src/cgroups/fs/mod.rs#L920-L923

This can be optimized.

**Comment by gkurz** [comment]
Hi @liubin !

Great thanks for proposing these tiny changes ! This is definitely helpful to get started on rust and the agent code, both for submitters and reviewers.

**Comment by bookinabox** [comment]
I will take a look at this to start getting familiar with Rust.
