### ISSUE TITLE
Why not reserve full commit message in git log

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#3802]
Currently, we can't get full commit message by using "git log" under kata repro. It's not easy for people to learn the background of a certain commit. So, should we reserve them? @fidencio @bergwolf @egernst

**Comment by Jakob-Naucke** [comment]
@jongwu I'm afraid I don't quite understand your question. `git log` does show commit messages, right?

**Comment by jongwu** [comment]
@Jakob-Naucke -, Yeah, but not the full of the commit message. I see that just a title kept in the git log.
