### ISSUE TITLE
Kata spams logs with "failed to get OOM event from sandbox" warnings

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#3815]
# Description of problem

1. Deploy Kata on a kubernetes cluster, default kata-deploy configuration.
2. Have a Kata pod running.
3. Run `journalctl -f -t kata`

# Expected result

Nothing logged (at warning or above level) if there isn't something notable and new.

# Actual result

Around once per second, an error like this is logged:

```
Mar 02 21:35:12 redacted.example.com kata[8592]: time="2022-03-02T21:35:12.850845917-05:00" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" name=containerd-shim-v2 pid=8592 sandbox=8777ade86f39f98eb87e928cef539bb0ea56a4c5c06cae07d9bf5a568033459b source=containerd-kata-shim-v2
```

**Comment by Jakob-Naucke** [comment]
Hmm, I can't reproduce this with full debug and kata-deploy-current. Have you seen this comment? Sorry for the silly question, but are you sure all components are up to date? https://github.com/kata-containers/kata-containers/blob/c54bc8e657dbdd398914fe3f03a3d242561dd229/src/runtime/pkg/containerd-shim-v2/wait.go#L151
