### ISSUE TITLE
Add missing docs on cgroups v2 implementation in go agent

### ISSUE THREAD

**Issue by diru1100** [kata-containers/kata-containers#385]
### Description of problem

Currently, there are no docs explaining the [implementation of cgroups v2 feature in go agent. ](https://github.com/kata-containers/agent/pull/750/files)

This is done to get familiar with cgroups v2 feature in general. Also, to serve both as a reference and as a documentation basis for the rust implementation as mentioned in #146.

**Comment by devimc** [comment]
I guess you plan to write a document similar to this https://github.com/kata-containers/documentation/blob/master/design/host-cgroups.md but for the guest, maybe `guest-cgroups.md` ?
