### ISSUE TITLE
read_pid_file  has a `bundle_path` param but all the others call `self.get_bundle_path()`.

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#3876]
Can you add a comment explaining why this method has a `bundle_path` param but all the others call `self.get_bundle_path()`.

_Originally posted by @jodh-intel in https://github.com/kata-containers/kata-containers/pull/3786#discussion_r824721626_

@quanweiZhou

**Comment by quanweiZhou** [comment]
Thanks for @liubin @jodh-intel. 
There may be a multi-container for a Pod, each container has a bundle path, we need to write the PID to the file for each container in their own bundle path, so we can directly get the `bundle_path()` and write the PID. 
While the real runtime process's PID is stored in the file in the sandbox container's bundle path, so needs to read from the sandbox container's bundle path.
Would it be clearer to pass the sandbox id to `read_pid_file()` and get `bundle_path` in `read_pid_file()`

**Comment by liubin** [comment]
Close this since #3877 has been merged
