### ISSUE TITLE
Installation issues on K3s v1.22.2 - No Runtimes seem to be found?

### ISSUE THREAD

**Issue by lsascha** [kata-containers/kata-containers#3894]
Hello.

I am trying to get kata-containers running on my k3s kubernetes Cluster, running Kubernetes v1.22.2 on Ubuntu 20.04.4 LTS nodes currently.

i followed this documentation https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/README.md

But i had no luck so far.

I see kata-deploy pods running on all nodes.

Some say "node/k3s-agent-2 labeled", some however say "node/k3s-agent-0 not labeled".
I am pretty sure previously all pods once said they labeled the nodes.
And when i check the node labels, they all have `katacontainers.io/kata-runtime=true` as labels.

When i try to run a kata-container, no matter which runtimeClassName i use, it never successfully runs because it seems it can't find the runtimes.

When trying **kata-fc** i get
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: Failed to connect to firecrackerinstance (timeout 10s): unknown
```

When trying **kata-clh** i get
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: failed to launch cloud-hypervisor: "Failed to connect to API (timeout 10s): error: Get \"http://localhost/api/v1/vmm.ping\": dial unix /run/vc/vm/b52e7e7d80be532390a4a5233699d007051535b71d1ca247bd051f5a229c958f/clh-api.sock: connect: no such file or directory reason: ": unknown
```

similar error with **kata-qemu** so i will spare out that error message.

My noob guess would be that i need to install the runtimes to the nodes but i can't find any documentation about that so i am really not sure.

Anyone any idea what i am missing here?

Thanks in advance.

**Comment by liubin** [comment]
Hi @lsascha have you checked if there runtimeclass resources exist?

```bash
$ kubectl get runtimeclass
```

**Comment by lsascha** [comment]
thanks for the help.
runtimeclass resources exist since i created them according to the documentation.

i ran `modprobe -i vhost_vsock` without any output. But `modinfo vhost_vsock` gives me this output:
```
root@k3s-agent-0:/# modinfo vhost_vsock
filename:       /lib/modules/5.4.0-104-generic/kernel/drivers/vhost/vhost_vsock.ko
alias:          devname:vhost-vsock
alias:          char-major-10-241
description:    vhost transport for vsock
author:         Asias He
license:        GPL v2
srcversion:     B222D4F3CC6B403447E6A1E
depends:        vmw_vsock_virtio_transport_common,vhost,vsock
retpoline:      Y
intree:         Y
name:           vhost_vsock
vermagic:       5.4.0-104-generic SMP mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
(...)
```

So i would say the module is loaded.
But i still get the previously mentioned error when trying to start a kata container

**Comment by lsascha** [comment]
I asked the Server Provider and they confirmed that they do not support virtualization for these kind of servers unfortunately.
So i guess when there is no alternative possible, kata containers will not work here.

It can be tested by executing `modprobe kvm-intel`.
If it shows `modprobe: ERROR: could not insert 'kvm_intel': Operation not supported`

it is most likely that Virtualization is not enabled/supported by the server.

I guess this can be closed then. 😞
