### ISSUE TITLE
Consider reworking the agent-ctl tool to be a more generic kata tool

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3917]
The [`agent-ctl`](https://github.com/kata-containers/kata-containers/tree/main/src/tools/agent-ctl) tool is currently used to connect to a running `kata-agent` and send Kata API calls to it.

The tool can talk to the Kata agent using either a standard `VSOCK` socket or a "Hybrid VSOCK" socket. Since interacting with hybrid VSOCK sockets is awkward using `socat(1)` and since connecting to a Hybrid VSOCK socket is required to connect to, for example, Cloud Hypervisor's debug console, we could rework `agent-ctl` to also provide that ability.

# High level plan

## Initial tasks

- Rename the `agent-ctl` source directory and all files in it to `kata-ctl`.
- Change the CLI so that it accepts commands and options (like `git(1)` _et al_):
  ```bash
  $ sudo kata-ctl agent ...  # connect to the agent
  $ sudo kata-ctl dump-guest-log ...  # connect to a hybrid VSOCK socket debug console
  ```

## Possible future tasks

Once we have the kata 3.x parts landed, we could extend it:

- Delete the `kata-runtime` (golang) sources.
- Re-implement `kata-runtime`'s `check`, `env` and `exec` commands in rust:
  ```bash
  $ sudo kata-ctl check # equivalent to "kata-runtime check"
  $ sudo kata-ctl env # equivalent to "kata-runtime env"
  $ sudo kata-ctl env # equivalent to "kata-runtime exec ..."
  ```
- Packaging: sym-link `kata-ctl` to `kata-runtime` for a few releases to allow users to transition.

**Comment by wainersm** [comment]
Thanks for creating @jodh-intel !
It's is a good idea IMHO.
/cc @kata-containers/redhat

**Comment by jodh-intel** [comment]
Closing in favour of #5348.
