### ISSUE TITLE
runtime-rs: support shimv2 create task option

### ISSUE THREAD

**Issue by quanweiZhou** [kata-containers/kata-containers#3961]
runtime-rs: support shimv2 create task option, relay on `shim.proto`
from https://github.com/kata-containers/kata-containers/pull/3879#discussion_r831941742

Options:
https://github.com/containerd/containerd/blob/main/pkg/runtimeoptions/v1/api.proto#L19

**Comment by studychao** [comment]
This issue is already fixed by : https://github.com/kata-containers/kata-containers/commit/d663f110d737a1362d3d49bf58aaea9fd7592271

**Comment by studychao** [comment]
reopen this since we need a commit to fix the comment area above `load_config`
