### ISSUE TITLE
Simplify nproc calls

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3967]
In various places, we run build jobs in parallel (`make -j`).

However, since that can DoS your system if running locally, we tend to reserve a single CPU to avoid DoS-ing our local systems by specifying the cpu count less one. However, the syntax we tend to use can get a bit... hairy. This table summarises the current situation and what we should be doing:

| Description | | Shell | Makefile | Notes |
|-|-|-|-|-|
| good | :smile: | `make -j $(nproc --ignore=1)` | `$(shell nproc --ignore=1)` | What we should be doing |
| bad | :disappointed: | `make -j $(nproc)` | `$$((nproc))` | What we should not do |
| ugly | :sob: | `make -j $(($(nproc)-1))` | `$$(( $$(nproc) - 1  ))` | What we are currently doing |

Extra points if we conditionally set `--ignore=1` if we're running in a CI environment (where we want all the CPU power we can get:

```bash
nproc_args=
[ -n "$CI" ] && nproc_args="--ignore 1"
```

**Comment by bookinabox** [comment]
I was thinking of using:

`$(nproc ${CI:+--ignore 1}) `

as a means of argument expansion rather than setting a separate variable. I'm fairly new to shell scripting, so are there any obvious downsides to this approach?
