### ISSUE TITLE
'--privileged' broken with newer container versions

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3968]
Passing `--privileged` to containerd's `ctr` command no longer works, even when `privileged_without_host_devices = true` is set in `/etc/containerd/config.toml`.

See:

- https://github.com/kata-containers/kata-containers/issues/2467
- https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/privileged.md

## QEMU

```bash
$ sudo ctr run -t --privileged --runtime "io.containerd.kata.v2" --rm "quay.io/prometheus/busybox:latest" aaa1145 sh
ctr: failed to create shim: Conflicting device updates for /dev/dm-1: unknown

$ journalctl -q -o cat -t kata|grep level=error
time="2022-03-25T14:46:23.346998371Z" level=error msg="createContainer failed" error="rpc error: code = Internal desc = Conflicting device updates for /dev/dm-1" name=containerd-shim-v2 pid=8468 sandbox=aaa1145 source=virtcontainers subsystem=kata_agent
time="2022-03-25T14:46:23.347181505Z" level=error msg="container create failed" container=aaa1145 error="rpc error: code = Internal desc = Conflicting device updates for /dev/dm-1" name=containerd-shim-v2 pid=8468 sandbox=aaa1145 source=virtcontainers subsystem=container

$ journalctl -q -o cat -t kata|grep 'Device has not been passed to the container"' |head -n1
time="2022-03-25T14:21:47.461624939Z" level=info msg="Device has not been passed to the container" device=/dev/autofs name=containerd-shim-v2 pid=5894 sandbox=aaa1145 source=virtcontainers subsystem=deviceManager

$ journalctl -q -o cat -t kata|grep 'Device has not been passed to the container"' |grep -o "device=[^ ]*"|sort -u|sed 's/device=//g'|wc -l
212
```

## Cloud Hypervisor

```bash
$ sudo ctr run -t --privileged --runtime "io.containerd.kata.v2" --rm "quay.io/prometheus/busybox:latest" aaa1145 sh

ctr: failed to create shim: failed to hotplug block device &{File:/dev/loop0 Format:raw ID:drive-b4519e6165f4d22e MmioAddr: SCSIAddr: NvdimmID: VirtPath:/dev/vdc DevNo: PCIPath: Index:2 ShareRW:false ReadOnly:false Pmem:false Swap:false} error: 500  reason: VmAddDisk(VmAddDisk(DeviceManager(DetectImageType(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })))): unknown

$ journalctl -q -o cat -t kata|grep level=error
time="2022-03-25T14:44:46.470757678Z" level=error msg="container create failed" container=aaa1145 error="failed to hotplug block device &{File:/dev/loop0 Format:raw ID:drive-b4519e6165f4d22e MmioAddr: SCSIAddr: NvdimmID: VirtPath:/dev/vdc DevNo: PCIPath: Index:2 ShareRW:false ReadOnly:false Pmem:false Swap:false} error: 500  reason: VmAddDisk(VmAddDisk(DeviceManager(DetectImageType(Error { kind: UnexpectedEof, message: \"failed to fill whole buffer\" }))))" name=containerd-shim-v2 pid=7211 sandbox=aaa1145 source=virtcontainers subsystem=container

$ journalctl -q -o cat -t kata|grep 'Device has not been passed to the container"' |grep -o "device=[^ ]*"|sort -u|sed 's/device=//g'|wc -l
212
```

## When did it break?

We need to bisect. #2467 shows that it was borked in containerd 1.4.9, but it was working in version [1.3.10](https://github.com/kata-containers/kata-containers/blob/stable-2.1/versions.yaml#L191).

## Tests

Once this is fixed we need a set of `--privileged` tests to avoid (upstream) regressions like this.

**Comment by devimc** [comment]
Thanks @jodh-intel for raising this, I can see two possible options to fix this issue

Option 1
===

Solution
---
Investigate and fix the bug in the upstream projects (containerd and crio)

Cons:
---
we need to add and maintain external jobs to make sure pull requests in these projects don't break it again (regression), the question is: who is willing to maintain another job when there are not enough hands to maintain ours (https://github.com/kata-containers/ci/issues/403)? :man_shrugging: 

Option 2
===

Solution
---
Add an option in the `config.toml` to run privileged container without host devices (`privileged_without_host_devices`), kata will filter the list of devices adding needed devices only

Cons
---
what devices are allowed? how to implement it without clashing with `-v /dev:/dev` option?

related to https://github.com/kata-containers/kata-containers/issues/3214

**Comment by jodh-intel** [comment]
## Prep work

Before we decide on the best option, I think we need to dig into this a bit to be sure Kata didn't break. If it's definitely not Kata, we need to know why two separate projects broke Kata behaviour (maybe they share a common dependent library which actually caused a breakage?)

## Option 1

As a minimum, I think we need to determine:

- The latest known working combinations of:
  - Kata + containerd.
  - Kata + crio.
- Details of the breaking changes for both.

## Option 2

I like the idea :) It would be more complex but I wonder if we should add an allow list and a deny list with a default of "allow no host devices".

## Considerations

We don't want to spend a lot of engineering effort on a new feature for the current runtime without considering the new rust runtime (to minimise / avoid having to do the work twice).

/cc @bergwolf, @liubin.

## Follow on work

We need to [enable tests](https://github.com/kata-containers/tests/issues/4629) once this is fixed to avoid a future regression.

/cc @amshinde.

**Comment by liubin** [comment]
But does `PrivilegedWithoutHostDevices` only affect the `CRI` interface? the `ctr` is not controlled by this configuration?

If we want to control host devices at Kata Containers side, I'm preferring to option 2 too. But it may make the user experience complex too, what we should think about is to let users do little configure.

**Comment by egernst** [comment]
Can you verify that it is broken when testing using crictl or kubernetes rather than with ctr?

**Comment by bergwolf** [comment]
Yeah, ctr is not CRI, and its purpose is to do testing FWICT. I'd wonder more if nerdctl works though.

**Comment by dborquez** [comment]
FYI, testing containerd [1.6.6](https://github.com/containerd/containerd/releases/tag/v1.6.6) using --privileged and following the workaround given in [2467](https://github.com/kata-containers/kata-containers/issues/2467#issuecomment-947772200) shows the issue still remains:

```
sudo -E ctr run -t --privileged  --runtime quay.io/prometheus/busybox:latest mw-kata bash
ctr: failed to create shim task: QMP command failed: The device is not writable: Permission denied: unknown

sudo rm /dev/loop*

sudo -E ctr run -t --privileged  --runtime quay.io/prometheus/busybox:latest mw-kata bash

ctr: failed to create shim task: Conflicting device updates for /dev/sdb2: unknown

sudo rm /dev/sdb* /dev/sda*

sudo -E ctr run -t --privileged  --runtime quay.io/prometheus/busybox:latest mw-kata bash
ctr: failed to create shim task: Creating container device LinuxDevice { path: "/dev/full", type: "c", major: 1, minor: 7, file_mode: Some(438), uid: Some(0), gid: Some(0) }

Caused by:
    EEXIST: File exists: unknown
```

**Comment by dborquez** [comment]
> FYI, testing containerd [1.6.6](https://github.com/containerd/containerd/releases/tag/v1.6.6) using --privileged and following the workaround given in [2467](https://github.com/kata-containers/kata-containers/issues/2467#issuecomment-947772200) shows that the issue still remains:
> 
> ```
> sudo -E ctr run -t --privileged  --runtime quay.io/prometheus/busybox:latest mw-kata bash
> ctr: failed to create shim task: QMP command failed: The device is not writable: Permission denied: unknown
> 
> sudo rm /dev/loop*
> 
> sudo -E ctr run -t --privileged  --runtime quay.io/prometheus/busybox:latest mw-kata bash
> 
> ctr: failed to create shim task: Conflicting device updates for /dev/sdb2: unknown
> 
> sudo rm /dev/sdb* /dev/sda*
> 
> sudo -E ctr run -t --privileged  --runtime quay.io/prometheus/busybox:latest mw-kata bash
> ctr: failed to create shim task: Creating container device LinuxDevice { path: "/dev/full", type: "c", major: 1, minor: 7, file_mode: Some(438), uid: Some(0), gid: Some(0) }
> 
> Caused by:
>     EEXIST: File exists: unknown
> ```

**Comment by liubin** [comment]
Both ctr and nerdctl now support skip passing host devices to guest, the latest ctr/nerdctl will not affect by this error.

- nerdctl

From: v0.23.0

PR: https://github.com/containerd/nerdctl/pull/1291

- ctr

From: not released yet, you need to build from the source.
PR: https://github.com/containerd/containerd/pull/7328
