### ISSUE TITLE
CCv0 | agent: Remove skopeo and umoci from agent code once blockers addressed

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#3970]
We currently have two paths of code in `image_rpc.rs`:
- If the `skopeo` binary is present this is used to pull (and verify signatures and decrypt images if required) the container image and then `umoci` binary is used to unpack them
- Otherwise the default image pull path in the CC Kata agent uses `image-rs` to perform the pull and unpack.

We currently have the following inhibitor for removing skopeo & umoci from our codebase without introducing some local/offline attestation regressions:
- #4581
- #4601

Once this issue is addressed, we should be at a point to replace the `pull_image_from_registry` function and related code from [image_rpc.rs](https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/image_rpc.rs) that uses skopeo & umoci and streamline to use a single path.

Things to note and change along with this the `image_rpc.rs` changes:
- Remove the `SKOPEO` and `UMOCI` parameters and related code from [`rootfs.sh`](https://github.com/kata-containers/kata-containers/blob/CCv0/tools/osbuilder/rootfs-builder/rootfs.sh)
- Ensure that we have removed the skopeo information from the [CCv0 docs](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md#basic-script-set-up-and-optional-environment-variables) and `ccv0.sh` script as we no longer will need to provide it as an option.
- As a follow-up task, or along with this change we'll want to update the image signature verification integration tests that Wainer added in https://github.com/kata-containers/tests/issues/4572 and probably just remove the skopeo test job and get them running on the standard `crictl` test job.
- Remove the `container_policy_file` config, now it isn't needed.
- Consider if we remove the skopeo and umoci entries from the versions.yaml, unless we decide we wish to use them for the pause pull & unpack.

**Comment by stevenhorsman** [comment]
@arronwy - FYI I've raised this issue for the replacement of `skopeo` and `umoci` once the signature verification has been merged into `image-rs` for tracking purposes. I've added some links of things to change at the same (and I've probably missed some!), which could possibly be split into separate items. If you and the team need any help with them, then give me a shout :)

**Comment by wainersm** [comment]
I was looking at the [development plan for image-rs](https://github.com/confidential-containers/image-rs/issues/2#issue-1069217952) and wondering how far from **step 1** completion we are. I was also wondering if finishing the *step 1* is a requirement for this issue ("Remove skopeo and umoci from agent code") or if have https://github.com/confidential-containers/image-rs/pull/5 merged is sufficient.

**Comment by stevenhorsman** [comment]
> I was looking at the [development plan for image-rs](https://github.com/confidential-containers/image-rs/issues/2#issue-1069217952) and wondering how far from **step 1** completion we are. I was also wondering if finishing the _step 1_ is a requirement for this issue ("Remove skopeo and umoci from agent code") or if have [confidential-containers/image-rs#5](https://github.com/confidential-containers/image-rs/pull/5) merged is sufficient.

@arronwy will be able to answer more accurately, but from what I've picked up we seem to be getting close to the end of step1:
- We have at least some, if not all, of the pull capability
- Decryption support is in, and with [confidential-containers/image-rs#5](https://github.com/confidential-containers/image-rs/pull/5) signature verification will be supported. In order to replace the current skopeo behaviour we don't *need* to support different policies, but if it isn't implemented initially, then we'll at least want an easier mechanism for allowing policies to be set in the attesation-agent and flowed through, for all KBCs (I think only EAA supported it at the moment and we can't use that in a non-TEE environment based on my extremely limited understanding)
- Unpacking is currently supported and I'm not sure if we require the snapshot module support
- This item is supposed to cover the full integration with the Kata agent

@wainersm - I hope that helps and I haven't given you too much mis-information!

**Comment by arronwy** [comment]
> @arronwy - FYI I've raised this issue for the replacement of `skopeo` and `umoci` once the signature verification has been merged into `image-rs` for tracking purposes. I've added some links of things to change at the same (and I've probably missed some!), which could possibly be split into separate items. If you and the team need any help with them, then give me a shout :)

Thanks @stevenhorsman , yes, after signature verification feature merged into `image-rs`, we will run the kata integration tests locally to ensure it can works with the CC test cases for skopeo.

**Comment by stevenhorsman** [comment]
Closed with #6104 merging
