### ISSUE TITLE
kata-deploy: Provide a kata-deploy image to be used with the Confidential Containers operator

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#3992]
This issue is for brainstorming what are the requirements needed from each one of the players involved, so a kata-deploy image containing the artefacts for confidential containers can be generated and used there.

From the Intel side, we know that we need:
* Guest kernel with TDX and SGX support
* QEMU with TDX and SGX support
  * TDVF
* Cloud Hypervisor with TDX and SGX support
  * td-shim

@devimc, @sboeuf, did I miss something here?

From the AMD side, we know that we need:
* Guest kernel with SEV and SEV-ES support
* QEMU with SEV and SEV-Es support
  * OVMF

From the IBM side, we know that we need:
* An image built on s390x 

The common parts for all architectures is:
* A rootfs image containing the patched agent
* The runtime built with the patched containerd vendored code

I have a few assumptions that I'd like to confirm with the community.
* We'll have *one* multi-arch manifest
  * The operator will be responsible for deploying the capable technologies based on the node's features (eg, the operator will be the one ensuring that no SEV is tried to be used on a TDX capable node, and vice-versa)
* There'll be one runtime-class per "technology" (eg: kata-sev, kata-sev-es, kata-tdx, kata-se)
* The x86_64 image may be big as it may contain different kernels, and the configuration should point to the correct one according to the runtime classes being deployed

This is a braindump and issues will be opened to track this effort, right now we mostly need feedback from the parts interested in the effort.

**Comment by wainersm** [comment]
Allow me to link this with [ci: Add confidential-containers awareness to the build/test jobs](https://github.com/kata-containers/tests/issues/4626) as the kata-deploy might need some way to identify it is building for CC.

**Comment by wainersm** [comment]
@fidencio thanks for starting this discussion.

Unfortunately due my lack of expertise on this area I have more questions than answers. Here goes:

1. Do we have a single kernel that fills the requirements for Intel and AMD technologies? Based on the assumption of "the x86_64 image may be big as it may contain different kernels" it seems not, but I would like to clarify that.
2. Can the kata-deploy image size (much bigger than today) be a problem to the operator so that we will need to split it?
3. @fidencio you said about "one multi-arch image" then later "the x86_64 image...". I didn't get whether it will be a single or multiple images.

**Comment by fidencio** [comment]
> 1. Do we have a single kernel that fills the requirements for Intel and AMD technologies? Based on the assumption of "the x86_64 image may be big as it may contain different kernels" it seems not, but I would like to clarify that.

I don't think we do, as the TDX patches are not fully merged into the kernel yet.
I'm not sure about the status of SEV / SEV-ES from the AMD side, and I hope someone from their side could chime in.

> 2. Can the kata-deploy image size (much bigger than today) be a problem to the operator so that we will need to split it?

I don't think so, mainly as this is something that will be temporary (till everything gets merged).

> 3. @fidencio you said about "one multi-arch image" then later "the x86_64 image...". I didn't get whether it will be a single or multiple images.

That's confusing, indeed.  I'd like to have one manifest, like, kata-deploy-cc:latest, which would then include manifests for different architectures (a :s390x, and a :x86_64 one).  This would allow the correct image to be pulled in when used in the correct architecture.  With this in mind, for the : x86_64 one, we may have to have ... 

Did I answer your questions in a satisfactory way?

**Comment by wainersm** [comment]
> > 1. Do we have a single kernel that fills the requirements for Intel and AMD technologies? Based on the assumption of "the x86_64 image may be big as it may contain different kernels" it seems not, but I would like to clarify that.
> 
> I don't think we do, as the TDX patches are not fully merged into the kernel yet. I'm not sure about the status of SEV / SEV-ES from the AMD side, and I hope someone from their side could chime in.
> 
> > 2. Can the kata-deploy image size (much bigger than today) be a problem to the operator so that we will need to split it?
> 
> I don't think so, mainly as this is something that will be temporary (till everything gets merged).
> 
> > 3. @fidencio you said about "one multi-arch image" then later "the x86_64 image...". I didn't get whether it will be a single or multiple images.
> 
> That's confusing, indeed. I'd like to have one manifest, like, kata-deploy-cc:latest, which would then include manifests for different architectures (a :s390x, and a :x86_64 one). This would allow the correct image to be pulled in when used in the correct architecture. With this in mind, for the : x86_64 one, we may have to have ...
> 
> Did I answer your questions in a satisfactory way?

Yes, as always my friend. thanks!

**Comment by sphrasavath** [comment]
In regards to upstream kernel support for SEV and SEV-ES, >= 4.16 and >= 5.11 respectively.  I think we could just target anything greater than 5.11.  Thanks!

**Comment by sphrasavath** [comment]
@fidencio Is the kata-shim considered part of the kata-deploy image?  Also, what is the minimal qemu version needed for tdx?  Perhaps there is an opportunity to consolidate here as well? For sev, we would like to baseline with 6.2.

**Comment by Alex-Carter01** [comment]
Thanks! This seems like a good thing to have everyone on the same page about.

In addition to the kernel support [sphrasavath](https://github.com/sphrasavath) mentioned, we will need to have the efi_secret kernel module in the Initrd. And then efi_secret also itself needs some kernel patches that are still working on being upstreamed.

**Comment by fidencio** [comment]
> @fidencio Is the kata-shim considered part of the kata-deploy image?

Yes, that's what I refer to as
"""
* The runtime built with the patched containerd vendored code
"""

> Also, what is the minimal qemu version needed for tdx? Perhaps there is an opportunity to consolidate here as well? For sev, we would like to baseline with 6.2.

The minimum we'll have is 6.2. :-)

**Comment by fidencio** [comment]
> In addition to the kernel support [sphrasavath](https://github.com/sphrasavath) mentioned, we will need to have the efi_secret kernel module in the Initrd. And then efi_secret also itself needs some kernel patches that are still working on being upstreamed.

That's perfectly fine, as long as the patches are public and we could build them in a reproducible way from our side.

**Comment by wainersm** [comment]
Hi @Alex-Carter01 ,

> Thanks! This seems like a good thing to have everyone on the same page about.
> 
> In addition to the kernel support [sphrasavath](https://github.com/sphrasavath) mentioned, we will need to have the efi_secret kernel module in the Initrd. And then efi_secret also itself needs some kernel patches that are still working on being upstreamed.

When you said "we will need", did you mean tdx? Or both sev and tdx? Or none of the former options :D

**Comment by fidencio** [comment]
> All in all, I am trying to understand if kata-deploy will need to distribute two builds of QEMU.

We may need to distribute two QEMU builds, at least for a while, as TDX support is not yet merged on QEMU.
That's the same reason we may need two different kernels as well.

That's not hard to solve via configuration files pointing to the right binary, by the way.  It will just increase the size of the image for a while (till we have everything merged upstream, from everyone ;-))

**Comment by Alex-Carter01** [comment]
> When you said "we will need", did you mean tdx? Or both sev and tdx? Or none of the former options :D

@wainersm for SEV. Sorry for being vague

**Comment by dcmiddle** [comment]
There is a device plugin for SGX[1] that is also available in the Intel device plugin operator[2].
[1]https://github.com/intel/intel-device-plugins-for-kubernetes#sgx-device-plugin
[2]https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/operator/README.md

**Comment by fidencio** [comment]
This one can be closed as there was a payload used for the first CC release.
