### ISSUE TITLE
Add configuration support for cloud-hypervisor network rate-limitting / io-throttling

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#4017]
In our multi-tenant CI/CD we have seen noisy neighbor issues and we're looking to make use of [cloud-hypervisor rate-limit / io-throttling](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/io_throttling.md) for virtio-block and virtio-net. The cloud-hypervisor configuration file we use for kata containers does not currently permit this (or at least we haven't figured out how to do it). 

What we'd like is to have the equivalent of setting the [cloud-hypervisor "Disk and Network" parameters](https://www.cloudhypervisor.org/docs/prologue/commands/). Is there some clever way to do this with the current configuration file, or if not could this support be added.

**Comment by likebreath** [comment]
> So, it's just a matter of exposing those in the configuration files and hooking them up in the Cloud Hypevisor driver.

@fidencio This sounds about right to me. If the Kata configuration asks for some thing that is different from what's being offered by CLH's API, there might be conversations needed. Or anything we may need to adjust from CLH side, please let me know.

>  I can assign this to myself and work on it next week, or you can do so if you have enough cycles. Let me know what's your preference.

 You are definitely more familiar with general Kata code base. Please go ahead and assign the issue to yourself. Thanks a lot.

**Comment by fidencio** [comment]
@likebreath, @skaegi,

What I can see offered by the Cloud Hypervisor's API is the following, for both net and disk.
```yaml
        rate_limiter_config:
          ops:
            size: 0
            one_time_burst: 0
            refill_time: 0
          bandwidth:
            size: 0
            one_time_burst: 0
            refill_time: 0
```

What kata-containers currently exposes for some VMMs is:
```toml
# Use rx Rate Limiter to control network I/O inbound bandwidth(size in bits/sec for SB/VM).
# In Firecracker, it provides a built-in rate limiter, which is based on TBF(Token Bucket Filter)
# queueing discipline.
# Default 0-sized value means unlimited rate.
#rx_rate_limiter_max_rate = 0
# Use tx Rate Limiter to control network I/O outbound bandwidth(size in bits/sec for SB/VM).
# In Firecracker, it provides a built-in rate limiter, which is based on TBF(Token Bucket Filter)
# queueing discipline.
# Default 0-sized value means unlimited rate.
#tx_rate_limiter_max_rate = 0
```

The question I have is, exposing only `{tx,rx}_rate_limiter_max_rate` would be enough for the net case?
And what about the disk?

**Comment by likebreath** [comment]
@fidencio May worth looking at what's being done from Firecracker side in Kata, as Cloud Hypervisor shares the same rate_limiter code/API.

**Comment by fidencio** [comment]
I'm going to break this issue in two, keep this one related to network, and open a new one to address disk.
