### ISSUE TITLE
fsGroup support for direct-assigned volume

### ISSUE THREAD

**Issue by yibozhuang** [kata-containers/kata-containers#4018]
**Which feature do you think can be improved?**

direct-assigned volume

**How can it be improved?**

When using Kata with K8s with direct-assigned volume, there isn't a good way to honor the `fsGroup` specified by pod security context since the `fsGroup` change is [done by Kubelet today](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L283) after CSI `NodePublishVolume` is called.

Although there is an option to defer `fsGroup` to the CSI driver from this [KEP](https://github.com/gnufied/enhancements/blob/master/keps/sig-storage/2317-fsgroup-on-mount/README.md) but its use case is mostly intended for plugins (like SMB) that does not support fsGroup but does similar with mount options.

Thus, right now the CSI client call ctx for CSI APIs are very short at [2 minutes](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L53)
so if we use the defer `fsGroup` to CSI driver, the recursive group change can take quite a bit of time for large number of files and can cause the client to timeout.

I propose we enhance the direct-assign volume feature to add additional options to specify `fsGroup` and `fsGroupChangePolicy` as part of the `Metadata` info in `MountInfo` struct [here](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/direct-volume/utils.go#L33)
and have those fields made available to the kata agent. The agent will do the optional recursive group owner change after the filesystem has been mounted.

**Additional Information**

I think we can add these two fields to the current `agent.proto` under [Storage](https://github.com/kata-containers/kata-containers/blob/main/src/libs/protocols/protos/agent.proto#L404)

And then in the kata-agent code, in `common_storage_handler` handler, after performing `mount_storage()`, we can add the additional logic to perform the group owner change.

**Before raising this enhancement request**

Have you looked at the [limitations document](https://github.com/kata-containers/kata-containers/blob/main/docs/Limitations.md)? Yes

**Comment by yibozhuang** [comment]
cc @fengwang666 @ddebroy @egernst

**Comment by fengwang666** [comment]
@yibozhuang Sounds reasonable. But what if the fsgroup doesn't exist inside the guest? Who is responsible for creating the group inside the guest for the first time?

**Comment by yibozhuang** [comment]
@fengwang666 the fsGroup is just a gid here and `chown` doesn't really care what it is (i.e. can be arbitrary).
Kubelet today also just blindly chown and I think the kata-agent here can do the same.
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/volume_linux.go#L73

**Comment by yibozhuang** [comment]
I can take an initial stab at implementing this.

/assign
