### ISSUE TITLE
About the new version of virtiofsd How to upgrade?

### ISSUE THREAD

**Issue by MagicStarTrace** [kata-containers/kata-containers#4046]
Is it an upgrade of the kata engine?

I need to disable logging now, what

https://github.com/kata-containers/kata-containers/issues/3303

**Comment by fidencio** [comment]
I don't fully understand what's being asked here.
Please, subscribe yourself to https://github.com/kata-containers/kata-containers/issues/3036 if you want to follow the transition.

For now, I am closing it due to the lack of information.

**Comment by liubin** [comment]
@MagicStarTrace I reopened the original #3303 and created #4048 to fix it.
