### ISSUE TITLE
Rust agent crashes if rdma cgroup present

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#408]
If you run the new rust agent in a QEMU env that supports rdma, the agent will crash. Although we disable rdma in the packaging repo, a distro-built version of QEMU will probably have rdma enabled.

# Host

The `CreateContainer` API fails with `RpcStatus(code: INTERNAL message: "EINVAL: Invalid argument")` and the agent crashes:

# In a QEMU VM that supports rdma

## cgroups

```sh
$ grep rdma /proc/cgroups
rdma    12      5       1
```

## agent crash 

```
{"msg":"create container process error Error(Nix(Sys(EINVAL)), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(   0: error_chain::backtrace::imp::InternalBacktrace::new
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/backtrace.rs:56
   1: <error_chain::State as core::default::Default>::default

   at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/lib.rs:687
   2: rustjail::errors::Error::from_kind
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/error_chain.rs:269
   3: <rustjail::errors::Error as core::convert::From<nix::Error>>::from
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/error_chain.rs:361
   4: <T as core::convert::Into<U>>::into
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/convert/mod.rs:559
   5: rustjail::cgroups::fs::get_subsystem
             at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/cgroups/fs/mod.rs:1140
   6: <rustjail::cgroups::fs::Manager as rustjail::cgroups::Manager>::set
             at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/cgroups/fs/mod.rs:1254
   7: rustjail::container::join_namespaces
             at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/container.rs:1183
   8: <rustjail::container::LinuxContainer as rustjail::container::BaseContainer>::start
             at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/container.rs:894
   9: kata_agent::rpc::agentService::do_create_container
             at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/src/rpc.rs:163
  10: <kata_agent::rpc::agentService as protocols::agent_ttrpc::AgentService>::create_container
             at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/src/rpc.rs:527
  11: <protocols::agent_ttrpc::CreateContainerMethod as ttrpc::server::MethodHandler>::handler
             at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/protocols/src/agent_ttrpc.rs:246
  12: ttrpc::server::start_method_handler_thread::{{closure}}
             at /home/james/.cargo/git/checkouts/ttrpc-rust-f4052649e2b990ed/ba1efe3/src/server.rs:205
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys_common/backtrace.rs:130
  14: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:475
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
  16: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  17: __rust_try
  18: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  19: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  20: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:474
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/ops/function.rs:232
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys/unix/thread.rs:87
  23: start_thread
  24: __clone
```

# Minimal workaround

The following stops the crash, but we should handle unknown cgroups more elegantly:

```diff
diff --git a/src/agent/rustjail/src/cgroups/fs/mod.rs b/src/agent/rustjail/src/cgroups/fs/mod.rs
index aba62822..84f5314e 100644
--- a/src/agent/rustjail/src/cgroups/fs/mod.rs
+++ b/src/agent/rustjail/src/cgroups/fs/mod.rs
@@ -1242,6 +1242,10 @@ pub const FROZEN: &'static str = "FROZEN";
 impl CgroupManager for Manager {
     fn apply(&self, pid: pid_t) -> Result<()> {
         for (key, value) in &self.paths {
+            if key == "rdma" {
+                continue;
+            }
+
             apply(value, pid)?;
         }

@@ -1250,6 +1254,10 @@ impl CgroupManager for Manager {

     fn set(&self, spec: &LinuxResources, update: bool) -> Result<()> {
         for (key, value) in &self.paths {
+            if key == "rdma" {
+                continue;
+            }
+
             let _ = fs::create_dir_all(value);
             let sub = get_subsystem(key)?;
             sub.set(value, spec, update)?;
```

/cc @lifupan, @devimc.

**Comment by lifupan** [comment]
> If you run the new rust agent in a QEMU env that supports rdma, the agent will crash. Although we disable rdma in the packaging repo, a distro-built version of QEMU will probably have rdma enabled.
> 
> # Host
> The `CreateContainer` API fails with `RpcStatus(code: INTERNAL message: "EINVAL: Invalid argument")` and the agent crashes:
> 
> # In a QEMU VM that supports rdma
> ## cgroups
> ```shell
> $ grep rdma /proc/cgroups
> rdma    12      5       1
> ```
> 
> ## agent crash
> ```
> {"msg":"create container process error Error(Nix(Sys(EINVAL)), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(   0: error_chain::backtrace::imp::InternalBacktrace::new
>              at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/backtrace.rs:56
>    1: <error_chain::State as core::default::Default>::default
> 
>    at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/lib.rs:687
>    2: rustjail::errors::Error::from_kind
>              at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/error_chain.rs:269
>    3: <rustjail::errors::Error as core::convert::From<nix::Error>>::from
>              at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.2/src/error_chain.rs:361
>    4: <T as core::convert::Into<U>>::into
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/convert/mod.rs:559
>    5: rustjail::cgroups::fs::get_subsystem
>              at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/cgroups/fs/mod.rs:1140
>    6: <rustjail::cgroups::fs::Manager as rustjail::cgroups::Manager>::set
>              at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/cgroups/fs/mod.rs:1254
>    7: rustjail::container::join_namespaces
>              at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/container.rs:1183
>    8: <rustjail::container::LinuxContainer as rustjail::container::BaseContainer>::start
>              at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/rustjail/src/container.rs:894
>    9: kata_agent::rpc::agentService::do_create_container
>              at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/src/rpc.rs:163
>   10: <kata_agent::rpc::agentService as protocols::agent_ttrpc::AgentService>::create_container
>              at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/src/rpc.rs:527
>   11: <protocols::agent_ttrpc::CreateContainerMethod as ttrpc::server::MethodHandler>::handler
>              at /home/james/go/src/github.com/kata-containers/kata-containers/src/agent/protocols/src/agent_ttrpc.rs:246
>   12: ttrpc::server::start_method_handler_thread::{{closure}}
>              at /home/james/.cargo/git/checkouts/ttrpc-rust-f4052649e2b990ed/ba1efe3/src/server.rs:205
>   13: std::sys_common::backtrace::__rust_begin_short_backtrace
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys_common/backtrace.rs:130
>   14: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:475
>   15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
>   16: std::panicking::try::do_call
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
>   17: __rust_try
>   18: std::panicking::try
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
>   19: std::panic::catch_unwind
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
>   20: std::thread::Builder::spawn_unchecked::{{closure}}
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:474
>   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/ops/function.rs:232
>   22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
>       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
>       std::sys::unix::thread::Thread::new::thread_start
>              at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys/unix/thread.rs:87
>   23: start_thread
>   24: __clone
> ```
> 
> # Minimal workaround
> The following stops the crash, but we should handle unknown cgroups more elegantly:
> 
> ```diff
> diff --git a/src/agent/rustjail/src/cgroups/fs/mod.rs b/src/agent/rustjail/src/cgroups/fs/mod.rs
> index aba62822..84f5314e 100644
> --- a/src/agent/rustjail/src/cgroups/fs/mod.rs
> +++ b/src/agent/rustjail/src/cgroups/fs/mod.rs
> @@ -1242,6 +1242,10 @@ pub const FROZEN: &'static str = "FROZEN";
>  impl CgroupManager for Manager {
>      fn apply(&self, pid: pid_t) -> Result<()> {
>          for (key, value) in &self.paths {
> +            if key == "rdma" {
> +                continue;
> +            }
> +
>              apply(value, pid)?;
>          }
> 
> @@ -1250,6 +1254,10 @@ impl CgroupManager for Manager {
> 
>      fn set(&self, spec: &LinuxResources, update: bool) -> Result<()> {
>          for (key, value) in &self.paths {
> +            if key == "rdma" {
> +                continue;
> +            }
> +
>              let _ = fs::create_dir_all(value);
>              let sub = get_subsystem(key)?;
>              sub.set(value, spec, update)?;
> ```
> 
> /cc @lifupan, @devimc.

@jodh-intel  Ok, I'll take a look on how to fix it.
