### ISSUE TITLE
Add support for pod specific IPtables

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#4080]
We have a use case where we want to inject pod-specific ip table rules. In the case of runc this is as simple as creating the rules within the applicable network namespace.

For Kata this won't work, since the rules are managed managed at L3, while we use tcfilter at L2. Since we're doing a direct connection, no rules are exercised.

What I'd like to see is a mechanism to reflect the host side IPTables rules inside the guest, similar to what we do today with routes. In this way, we'd be able to effectively do "iptables-save" in the pod's network namespace on the host, and then have the agent do an iptables-restore inside the guest OS.

Further, there are use cases where the IPtables will be dynamic over time (Kube-proxy scenario), and we'd like to have a way to receive notification that a pods network namespace/iptables have been updated. This'll allow for updates to the IPTables rules when the pod is running, and will also allow us to not (re)introduce something like network-monitor.

**Comment by christopherhein** [comment]
Thank you @egernst for filing this issue!

**Comment by bergwolf** [comment]
@egernst We had a `netmon` to do similar work in the old 1.X times (https://github.com/kata-containers/runtime/blob/master/netmon/netmon.go#L671). While we certainly do not want to bring `netmon` back, we can use a goroutine thread from the shimv2 process to enter the pod netns on the host and do the same ip/route monitoring and copying work. Have you considered that approach?

**Comment by egernst** [comment]
I had considered looking at net link (in the pod namespace, not host).  For our use case I didn’t need  to complicate things, add event listening. I think this can still be added on top of this implementation - it would just call directly from the shim’s go routine.
