### ISSUE TITLE
Kata containers agent build warns a lot

### ISSUE THREAD

**Issue by sameo** [kata-containers/kata-containers#409]
# Description of problem

Dozens of Rust warnings when building Kata Containers 2.0

# Expected result

Clean build.

**Comment by fidencio** [comment]
+1 for this. The fact that none of those warning are harmful and all of those seem simple enough to solve is just a push for solving them now. :-)

**Comment by devimc** [comment]
fixed https://github.com/kata-containers/kata-containers/pull/795
