### ISSUE TITLE
Kata 1.6.2 dependency chain broken

### ISSUE THREAD

**Issue by maburlik** [kata-containers/kata-containers#41]
# Description of problem

Kata 1.6.2 release page here: https://github.com/kata-containers/runtime/releases/tag/1.6.2

We are trying to consume the latest stable-1.6 release of kata but are hitting the dependency error below when attempting to install the package.

$ sudo apt install kata-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
kata-runtime : Depends: kata-linux-container (>= 4.19.34.33-4) but 4.19.28.31-3 is to be installed
E: Unable to correct problems, you have held broken packages.

http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.6/xUbuntu_16.04/

https://imgur.com/aA8GOe2.jpg

Also the previous 1.6.1 release appears to have been removed, so we can't work around this without self-hosting a previous set of debs.

# Expected result

Expecting package to be available due to new requirement from 1.6.2 kata-runtime:
kata-linux-container (>= 4.19.34.33-4) 

As a backup, we were expecting the older 1.6.1 release to be available in the repo in case we need to roll back.

# Actual result

Latest kata-linux-container package that's been published is 4.19.28.31-3.

---

**Comment by gkhanna79** [comment]
CC @gkhanna79

**Comment by egernst** [comment]
Fixed. Working through post mortem to make sure this doesn’t happy again. 

Ptal and let me know if issue still persists.

**Comment by maburlik** [comment]
Confirmed the package installs from my end. Thanks.

**Comment by gkhanna79** [comment]
Thank you for the quick turnaround on this @egernst.
