### ISSUE TITLE
Moving kata-log-parser to the kata-containers repo

### ISSUE THREAD

**Issue by snir911** [kata-containers/kata-containers#4100]
**Which feature do you think can be improved?**

[kata-log-parser](https://github.com/kata-containers/tests/tree/main/cmd/log-parser)

**How can it be improved?**

[kata-log-parser](https://github.com/kata-containers/tests/tree/main/cmd/log-parser) is a tool used for parsing logfmt kata logs which is currently existing under the tests repository, I'd like to suggest to move it under the main kata-containers repository (under kata-containers/src/tools/kata-log-parser?)

**Why?**
* It allows you to convert kata logs to other formats so that they can be searched and inspected more easily which could be useful for developers (and already used by some)
* kata-log-parser is used by tests only for the teardown.sh script, it emits an error in many/most jobs that is being ignored
* It could be utilized by the [kata-collect-data.sh](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/data/kata-collect-data.sh.in) script to re-order or to present collected logs more conveniently
* It may encourage more people to use it and contribute to it

**Additional Information**
* kata-log-parser contains many legacy kata v1 code which probably could be removed and requires more work and fixes, **however**:
  * It currently works decently with the current version thanks to several recent PRs
  * More work on the code and documentation is just around the corner
* Once this is agreed another issue should be opened against tests for removing the kata-log-paser
* This suggestion is regardless to test/kata-containers repos merge initiative
* Changes on the logging side (runtime-rs, switching logs libraries..) may require adjustments in the parser

**Comment by snir911** [comment]
cc @littlejawa @jodh-intel (the original author AFAIU) @fidencio
WDYT?

**Comment by fidencio** [comment]
+1 from me.

**Comment by jodh-intel** [comment]
wfm!
