### ISSUE TITLE
runk: get invalid container state

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#4181]
Use runk step by step through the readme:

```bash
root@master:/tmp/bundle# runk create test
root@master:/tmp/bundle# runk state test
{
  "ociVersion": "1.0.2-dev",
  "id": "test",
  "pid": 12289,
  "status": "stopped",
  "bundle": "/tmp/bundle",
  "created": "2022-04-29T12:54:08.229216651Z"
}
root@master:/tmp/bundle# runk start test
ERROR: cannot start a container in the stopped state
```

The state is stopped, it should be created.

**Comment by ManaSugi** [comment]
@liubin Have you had a chance to fix the `config.json` created by `runk spec` as mentioned in [REAMDE](https://github.com/kata-containers/kata-containers/tree/main/src/tools/runk#prerequisites)?

> Note: If you use the unmodified runk spec template, this should give a sh session inside the container. However, if you use runk directly and run a container with the unmodified template, runk cannot launch the sh session because runk does not support terminal handling yet. You need to edit the process field in the config.json should look like this below with "terminal": false and "args": ["sleep", "10"].

**Comment by liubin** [comment]
@ManaSugi Thank you, I will try it again later.
