### ISSUE TITLE
Add dynamic tracing mode feature to rust agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#419]
The golang agent supports dynamic tracing via the `StartTracing` and `StopTracing` API's. Add them to the rust agent.

**Note:** This feature may be of limited use since:

- Using these API calls requires a user to write their own application to modify the state of a running container
  (although they could just run https://github.com/kata-containers/kata-containers/tree/2.0-dev/tools/agent-ctl which supports calling these APIs).
- It's likely that calls to `StartTracing` and `EndTracing` will result in an incomplete trace transaction since the caller cannot know what all the agent threads are doing. `EndTracing` could potentially wait for a transaction to be "complete", but that may be problematic and is arguably modifying the behaviour of the program being traced (so not ideal).

Treating as low priority unless someone speak up with a good use-case for this.

**Comment by cmaf** [comment]
@jodh-intel closing since we're removing this in https://github.com/kata-containers/kata-containers/pull/2986
