### ISSUE TITLE
Cannot build kata-runtime with go1.18

### ISSUE THREAD

**Issue by zvonkok** [kata-containers/kata-containers#4194]
When building with go1.18, 

```
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
```
To resolve this one needs to set `--buildvcs=false` , related golang issue: https://github.com/golang/go/issues/51748. 

Are we going to include any version control information into the binaries build? 

Related release notes: https://tip.golang.org/doc/go1.18

We may add GOFLAGS to the Makefile to turn off or turn on such features coming with new golang versions.

```
$ export GOFLAGS=-buildvcs=false
$ sudo -E PATH=$PATH make install  
...
	qemu hypervisor path (QEMUPATH) : /usr/bin/qemu-system-x86_64
	cloud-hypervisor hypervisor path (CLHPATH) : /usr/bin/cloud-hypervisor
	firecracker hypervisor path (FCPATH) : /usr/bin/firecracker
	acrn hypervisor path (ACRNPATH) : /usr/bin/acrn-dm
	assets path (PKGDATADIR) : /usr/share/kata-containers
	shim path (PKGLIBEXECDIR) : /usr/libexec/kata-containers

     INSTALL  install-scripts
     INSTALL  install-completions
     INSTALL  install-configs
     INSTALL  install-configs
     INSTALL  install-bin
     INSTALL  install-containerd-shim-v2
     INSTALL  install-monitor
```

**Comment by liubin** [comment]
Hi @zvonkok thank you for this info.
Now we are using 1.17:

https://github.com/kata-containers/kata-containers/blob/79d93f1fe78b545e6171df51832490be74d56a24/versions.yaml#L251-L262

When upgrading golang, the build flag should be changed too as you said.

**Comment by liubin** [comment]
Go version issue https://github.com/kata-containers/tests/issues/5134
