### ISSUE TITLE
Add collated tracing type to new rust agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#420]
The rust agent supports static tracing, but the golang agent also supports collated tracing. Consider adding this to the rust agent for parity.

**Comment by jodh-intel** [comment]
See https://github.com/kata-containers/agent/blob/master/TRACING.md.

**Comment by cmaf** [comment]
@jodh-intel closing since we no longer allow for configuration of static vs collated tracing
