### ISSUE TITLE
optimize: use nix::unistd::User to get user home dir

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#4209]
In https://github.com/kata-containers/kata-containers/pull/1495, we parse the `/etc/passwd` file to get the home dir for one user, but it seems we can use nix::unistd::User to do the same thing, this will reduce some code.

/cc @lifupan

**Comment by justxuewei** [comment]
Hi Bin,

I wonder if this PR was assigned to anyone else? If not, I'd like to take this task. Thanks.
