### ISSUE TITLE
Does kata2.x support centos7？

### ISSUE THREAD

**Issue by TickFairy** [kata-containers/kata-containers#4218]
I find the offical packages only support centos 8 ， so I tried to install kata with kata-deploy in centos7 kubernetes， and the kata-deploy daemonset is ok， but when I set runtimeClassName for a pod ，it doesn't running,  then I describe the
 pod

![image](https://user-images.githubusercontent.com/68361970/167335861-ad9bc123-925b-4f8e-be05-300ead680dde.png)

at last, I  install kata with kata-deploy in centos8 , it works fine.

Is there any way to install kata in centos7 ? Or why kata2.0 does't support centos7 any more ?

**Comment by egernst** [comment]
It looks like your host kernel doesn’t have vsock module loaded. Try running insmod vhost_vsock on the host. 

It should run fine on centos 7.

**Comment by egernst** [comment]
If this answer works for you, please go ahead and close the issue. Thanks!

**Comment by TickFairy** [comment]
thanks a lot！

**Comment by TickFairy** [comment]
> It looks like your host kernel doesn’t have vsock module loaded. Try running insmod vhost_vsock on the host.
> 
> It should run fine on centos 7.

by the way ，the kernal seems doesn't support insmod vhost_vsock?

```
[root@master ~]# uname -a
Linux master 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@master ~]# insmod vhost_vsock
insmod: ERROR: could not load module vhost_vsock: No such file or directory


```

**Comment by egernst** [comment]
The you need to update your kernel to include vsock.

**Comment by marcosfsch** [comment]
CentOS 7 does support vsock-host, just run modprobe vsock_host. With insmod you'd need to provide the full path to the module.

**Comment by TickFairy** [comment]
thanks！
