### ISSUE TITLE
Support vfio-pci device as only network device

### ISSUE THREAD

**Issue by xiaosuiba** [kata-containers/kata-containers#4232]
**Is your feature request related to a problem? Please describe.**

We are working on Kata container + kubeovn + ovs HW offload. In this scenario, an sriov device will be pass to kata guest os as the only network device. It's an pci device and need to be setup by an network driver(e.g. mlx5_core). To archive this we need:
1. modprobe mlx5_core before kata-agent doing an network provisioning.
2. ignore pci env update as the sriov device is a network device now.

Currently, 
1. kata-agent do modprobe **after** network provisioning, so it cannot find the link and argu "Link not found"
2. even if we do a modprobe before network provisioning by adding an `ExecStartPre=modprobe mlx5_core` in kata-agent.service, it will still fail the `update_env_pci` [check](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/device.rs#L622)

**Describe the solution you'd like**
1. kata-agent should do modprobe before network provisioning,
2. bypass sriov device in `update_env_pci` 

**Describe alternatives you've considered**

**Additional context**

**Comment by fu7100** [comment]
You can recompile the kernel and add the `mellanox driver` so that you don’t need to execute `modprobe mlx5_core`
