### ISSUE TITLE
rpc::tests::test_do_write_stream is randomly failing

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#4246]
```
thread 'rpc::tests::test_do_write_stream' panicked at 'called `Result::unwrap()` on an `Err` value: failed to find FS type for mount point /', src/rpc.rs:2117:53
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c[172](https://github.com/kata-containers/kata-containers/runs/6417576912?check_suite_focus=true#step:14:172)5b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: kata_agent::rpc::tests::test_do_write_stream::{{closure}}
             at ./src/rpc.rs:2117:31
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
   7: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:62
   8: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
  11: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  12: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:39
  14: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:29
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  16: tokio::runtime::basic_scheduler::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:5
  17: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:230:9
  18: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:501:9
  19: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:[186](https://github.com/kata-containers/kata-containers/runs/6417576912?check_suite_focus=true#step:14:186):24
  20: tokio::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:461:46
  21: kata_agent::rpc::tests::test_do_write_stream
             at ./src/rpc.rs:2113:9
  22: kata_agent::rpc::tests::test_do_write_stream::{{closure}}
             at ./src/rpc.rs:2042:11
  23: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba[196](https://github.com/kata-containers/kata-containers/runs/6417576912?check_suite_focus=true#step:14:196)8c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
```

I've faced this as part of the 1.16 static checks.

**Comment by liubin** [comment]
The same as #4103

**Comment by liubin** [comment]
reopen since it is not really fixed. #4355 only adds more log.

**Comment by liubin** [comment]
Another [error](https://github.com/kata-containers/kata-containers/runs/6843561357?check_suite_focus=true):

> thread 'rpc::tests::test_do_write_stream' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable (os error 11)', src/rpc.rs:2224:53

**Comment by liubin** [comment]
Log from https://github.com/kata-containers/kata-containers/runs/6843888946?check_suite_focus=true:

> thread 'rpc::tests::test_do_write_stream' panicked at 'called `Result::unwrap()` on an `Err` value: failed to find FS type for mount point /, mount file content: Ok("device /dev/root mounted on / with fstype ext4\ndevice devtmpfs mounted on /dev with fstype devtmpfs\ndevice sysfs mounted on /sys with fstype sysfs\ndevice proc mounted on /proc with fstype proc\ndevice securityfs mounted on /sys/kernel/security with fstype securityfs\ndevice tmpfs mounted on /dev/shm with fstype tmpfs\ndevice devpts mounted on /dev/pts with fstype devpts\ndevice tmpfs mounted on /run with fstype tmpfs\ndevice tmpfs mounted on /run/lock with fstype tmpfs\ndevice tmpfs mounted on /sys/fs/cgroup with fstype tmpfs\ndevice cgroup2 mounted on /sys/fs/cgroup/unified with fstype cgroup2\ndevice cgroup mounted on /sys/fs/cgroup/systemd with fstype cgroup\ndevice pstore mounted on /sys/fs/pstore with fstype pstore\ndevice none mounted on /sys/fs/bpf with fstype bpf\ndevice cgroup mounted on /sys/fs/cgroup/devices with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/memory with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/misc with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/freezer with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/perf_event with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/net_cls,net_prio with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/cpu,cpuacct with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/hugetlb with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/pids with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/rdma with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/blkio with fstype cgroup\ndevice cgroup mounted on /sys/fs/cgroup/cpuset with fstype cgroup\ndevice systemd-1 mounted on /proc/sys/fs/binfmt_misc with fstype autofs\ndevice hugetlbfs mounted on /dev/hugepages with fstype hugetlbfs\ndevice mqueue mounted on /dev/mqueue with fstype mqueue\ndevice debugfs mounted on /sys/kernel/debug with fstype debugfs\ndevice tracefs mounted on /sys/kernel/tracing with fstype tracefs\ndevice fusectl mounted on /sys/fs/fuse/connections with fstype fusectl\ndevice configfs mounted on /sys/kernel/config with fstype configfs\ndevice /dev/loop0 mounted on /snap/core20/1494 with fstype squashfs\ndevice /dev/loop1 mounted on /snap/lxd/22753 with fstype squashfs\ndevice /dev/loop2 mounted on /snap/snapd/15904 with fstype squashfs\ndevice /dev/sdb15 mounted on /boot/efi with fstype vfat\ndevice binfmt_misc mounted on /proc/sys/fs/binfmt_misc with fstype binfmt_misc\ndevice /dev/sda1 mounted on /mnt with fstype ext4\ndevice tmpfs mounted on /run/snapd/ns with fstype tmpfs\ndevice nsfs mounted on /run/snapd/ns/lxd.mnt with fstype nsfs\n")', src/rpc.rs:2224:53
stack backtrace:
