### ISSUE TITLE
virtiofsd: Switch to using the rust version of virtiofsd for Snap

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#4261]
I am really not familiar with how the snap build of QEMU is done, and which options it's using, but it seems to be done here: https://github.com/kata-containers/kata-containers/blob/d1f2852d8bfacd615ef7b6eb09759125baefb2d9/snap/snapcraft.yaml#L227

We'd need to stop passing the `--enable-virtiofsd` for it and start relying on the download / built on our side binary of the virtiofsd instead.

I'm not totally sure who's now responsible for the snap work.
/cc @amshinde, @jodh-intel, do you happen to know?  Does it happen to be one of you? :-)

**Comment by jodh-intel** [comment]
It looks like it should be a simple tweak to:

- https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/scripts/configure-hypervisor.sh#L320..L344 
- https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/scripts/configure-hypervisor.sh#L415

Could you give that a try and see what the CI makes of it? If it's unhappy, I can tal at this tomorrow...

**Comment by jodh-intel** [comment]
@fidencio - I'm looking at adding the rust version of virtiofsd into the snap build atm...
