### ISSUE TITLE
why not use systemd as the cgroup driver?

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#4299]
From kubenetes official page [here](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#:~:text=A%20single%20cgroup%20manager%20simplifies,two%20views%20of%20those%20resources.) we find that:

"A single cgroup manager simplifies the view of what resources are being allocated and will by default have a more consistent view of the available and in-use resources. When there are two cgroup managers on a system, you end up with two views of those resources. In the field, people have reported cases where nodes that are configured to use cgroupfs for the kubelet and Docker, but systemd for the rest of the processes, become unstable under resource pressure."

But we have disabled "systemd" as the cgroup driver in kata. Should this let kata take the risk of unstable?

**Comment by liubin** [comment]
Ping @kata-containers/architecture-committee @lifupan @jodh-intel
