### ISSUE TITLE
Namespace osbuilder variables for improved reliability

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#43]
The [`osbuilder`](https://github.com/kata-containers/osbuilder) tool can be run natively or under docker by setting a special variable. It also supports various other variables to allow the build to change behaviour. However, it's easy to add new variables and forget to update the internal docker call to pass those new variables to the docker container.

By renaming the public variables to use an `OSBUILDER_` prefix, we namespace those variables and make exporting them to docker reliable. For further details see: https://github.com/kata-containers/osbuilder/issues/274

# Tasks

- [ ] osbuilder: update code + docs to prefix all public variables with `OSBUILDER_`
     See https://github.com/kata-containers/osbuilder/issues/274#issuecomment-490068323.
- [ ] documentation: Update dev guide to add `OSBUILDER_` to osbuilder commands:
  - https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md
- [ ] packaging: Update:
  - https://github.com/kata-containers/packaging/blob/master/snap/snapcraft.yaml
  - https://github.com/kata-containers/packaging/blob/master/obs-packaging/build_from_docker.sh
  - https://github.com/kata-containers/packaging/blob/master/obs-packaging/kata-containers-image/build_image.sh

**Comment by xiaoding945** [comment]
can I try to take the first task?

**Comment by grahamwhaley** [comment]
That's odd, my email is telling me that @xiaoding945 commented on this item asking if they could take a look at it (sure you can! welcome!). But, I don't see the comment in the github UI?...

**Comment by DingWei-070** [comment]
this is my another account ，xiaoding945 is also my account 
I want to join kata

**Comment by grahamwhaley** [comment]
:-) Hi @DingWei-070 - all welcome here :-)
If this is your first look at contributing to Kata, then we recommend if you have not already, you start by reading the [code of conduct](https://www.openstack.org/legal/community-code-of-conduct/) and the [contributing guide](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md) to start with.
Any questions, just ask!
