### ISSUE TITLE
Another shim leak and questions on the exit error handing 

### ISSUE THREAD

**Issue by fengwang666** [kata-containers/kata-containers#4359]
### Bug Description ### 

When a container process exits, its wait goroutine invokes [sandbox.StopContainer](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/wait.go#L81), which then calls the [stop()](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/container.go#L966) method in `container.go`. In the error case we hit, the `stop()` method exits early due to an error returned from the kata agent when calling [stopContainer()](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L1006-L1008) method, which results in a shim leak. 

Because of the early exit, the `container state` is [not set](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L1035-L1037) to `StateStopped`. The `wait goroutine` [logs a warning](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/wait.go#L82) on the error from `StopContainer` and continues its execution to its end, which also [set the container task status](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/wait.go#L85) to `StatusStopped`. In this case the [KillRequest](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L740) from containerd cri server is fulfilled completely. 

The failure happens in the [DeleteRequest](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L469). The `Delete()` method fails on [deleteContainer](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L490) because the `container state` is [neither StateReady nor StateStopped](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/container.go#L897-L900). 
The relevant error log we see:
```
Jun 01 03:51:44 aks-c1811c73c813-11566618-vmss000000 containerd[1850]: time="2022-06-01T03:51:44.227345662Z" level=debug msg="failed to delete task" error="rpc error: code = Unknown desc = Container not ready or stopped, impossible to delete" id=318c34675f73397660f8868ad2029bfbf1b8577c390092d9f5bf8085eb2de534
```
By now the shim is leaked. The containerd will keep sending `DeleteRequest` and fails every time. Also because the `task status` has been set to `StatusStopped`, deleteContainer [will not try to call](https://github.com/kata-containers/kata-containers/blob/a9a3074828d916660f64cd5e8e1c6e4b0782a96c/src/runtime/pkg/containerd-shim-v2/delete.go#L19-L23) `StopContainer` again.

On the containerd side, as part of the `TaskExit` [event handling](https://github.com/fengwang666/containerd/blob/5c2426a7b23d209a3ba46bce5ab81ec280e5b3ae/pkg/cri/server/events.go#L284), it will try to [delete the task](https://github.com/fengwang666/containerd/blob/5c2426a7b23d209a3ba46bce5ab81ec280e5b3ae/pkg/cri/server/events.go#L387). But the DeleteRequest will fail and the containerd event handler will keep retrying. Since the delete fails, the [container.stop()](https://github.com/fengwang666/containerd/blob/5c2426a7b23d209a3ba46bce5ab81ec280e5b3ae/pkg/cri/server/events.go#L413) channel is never closed, which [prevent the container stop from succeeding](https://github.com/fengwang666/containerd/blob/91bbaf67993d2602aa9efee574234160b5768c04/pkg/cri/server/container_stop.go#L191). 

Relevant log we see:
```
Jun 01 18:40:41 aks-c1811c73c813-11566618-vmss000000 containerd[1850]: time="2022-06-01T18:40:41.692100591Z" level=error msg="StopPodSandbox for \"10c701c20adcf1df3bae0b53baf5b8b9649555b2a58b64442cbe6e0019fdb0dc\" failed" error="rpc error: code = DeadlineExceeded desc = failed to stop container \"318c34675f73397660f8868ad2029bfbf1b8577c390092d9f5bf8085eb2de534\": an error occurs during waiting for container \"318c34675f73397660f8868ad2029bfbf1b8577c390092d9f5bf8085eb2de534\" to be killed: wait container \"318c34675f73397660f8868ad2029bfbf1b8577c390092d9f5bf8085eb2de534\": context deadline exceeded"
```

The original error from the kata agent in the `stopContainer` call  is an ESRCH, which is thrown from [signal.kill()](https://github.com/kata-containers/kata-containers/blob/b257e0e5abb72636a399487ca6b992d394be1c32/src/agent/rustjail/src/container.rs#L1035) invoked by [ctrl.destroy()](https://github.com/kata-containers/kata-containers/blob/a9a3074828d916660f64cd5e8e1c6e4b0782a96c/src/agent/src/rpc.rs#L333). The log in the kata agent code path is extremely limited and the above statement is solely based on code tracing. The root cause of ESRCH is unclear, but in general it's not a huge concern for `kill()` to throw ESRCH. 

The relevant log we see:
```
May 31 23:47:17 aks-c1811c73c813-11566618-vmss000000 containerd[1850]: time="2022-05-31T23:47:17.389052208Z" level=warning msg="stop container failed" container=318c34675f73397660f8868ad2029bfbf1b8577c390092d9f5bf8085eb2de534 error="rpc error: code = Internal desc = ESRCH: No such process" name=containerd-shim-v2 pid=14175 sandbox=10c701c20adcf1df3bae0b53baf5b8b9649555b2a58b64442cbe6e0019fdb0dc source=containerd-kata-shim-v2
```

### Fixes and discussion ###

The smallest and safest fix is to check the return error from [stopContainer](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L1006-L1008) and gracefully ignore ESRCH. 

Alternatively, we can move [setContainerState](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L1035-L1037) to the [defer](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L998-L1004) block, which guarantees that the container state is set to `StateStopped` even if some of the clean up steps failed. However, I'm not sure if it's an intentional choice to [check the error code ](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L1006-L1030) before setting the container state. Is there any downside to always set the `container state` to `StateStopped` even if some of the clean up steps failed? Would love to hear from others. It's also interesting to mention there is [3-year old todo in the comment](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L1000) asking about the same thing.
 
Another question I have, what's the different purpose between [container state](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L93) and [task status](https://github.com/kata-containers/kata-containers/blob/4f7cc186224fa9e724dc503f98dbebbb151bd2c8/src/runtime/pkg/containerd-shim-v2/container.go#L37)? Especially why their values are allowed to be out of sync?

**Comment by fengwang666** [comment]
@kata-containers/architecture-committee PTAL

**Comment by bergwolf** [comment]
@fengwang666 Thanks for such a detailed analysis!

> Is there any downside to always set the container state to StateStopped even if some of the clean up steps failed?

We would like to have a graceful shutdown and cleanup. So a failure in `stop` should be caught. But there is not really much that the shim and containerd can do in the case of a half-stopped container. So I would propose that we do the following:
1. If agent reports stop success, runtime should return success as well, even if there are other cleanup failures (like removing the storage, tearing up the rootfs, etc.)
2. If agent reports stop failure, runtime should return failure without further cleaning up any container resources on the runtime side.
3. When a container process exits, we should [force stop the container in wait.go](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/wait.go#L81).

So in your specific failure, the 3rd case above should address it.

> what's the different purpose between [container state](https://github.com/databricks/kata-containers/blob/9049409bc3ef9a594c2a3a750550ad58e58ef826/src/runtime/virtcontainers/container.go#L93) and [task status](https://github.com/kata-containers/kata-containers/blob/4f7cc186224fa9e724dc503f98dbebbb151bd2c8/src/runtime/pkg/containerd-shim-v2/container.go#L37)? Especially why their values are allowed to be out of sync?

It is mostly a historical reason. Virtcontainers was developed before shimv2 and was designed for the runc-like CLI to work. When shimv2 was added, it added its own sandbox and container status management. Ideally, we can now just consolidate them to have a single source of status authority. I remember that we discussed such a change at some point after shimv2 was introduced, but it didn't end up in implementation.

**Comment by pmores** [comment]
@fengwang666 Thanks for the perfect analysis of the problem! I'm wondering about the ESRCH root cause since the [kill()](https://github.com/kata-containers/kata-containers/blob/a238d8c6bd4f9a97161c3be25149f9faba3f6026/src/runtime/virtcontainers/container.go#L989) and [waitProcess()](https://github.com/kata-containers/kata-containers/blob/a238d8c6bd4f9a97161c3be25149f9faba3f6026/src/runtime/virtcontainers/container.go#L995) pair of calls seem to be designed to prevent that (hopefully I'm not mixing things up here, I'm not familiar with this code! :-) ).

So if that's the case, what's the explanation for ESRCH still happening?

**Comment by fengwang666** [comment]
@pmores You're absolutely correct. In the expected case, ESRCH shouldn't happen in the [destroy](https://github.com/kata-containers/kata-containers/blob/bd50d463b245a0c7841ff384d1873b437f0c5a4d/src/agent/src/rpc.rs#L329) call because all the processes should have been terminated by then and the pids should have been [removed](https://github.com/kata-containers/kata-containers/blob/bd50d463b245a0c7841ff384d1873b437f0c5a4d/src/agent/src/rpc.rs#L567) inside the wait_process operation. My guess is there is a race somewhere inside the agent causing the pid reference not cleaned up. But I don't know the exact root cause.
