### ISSUE TITLE
agent: "unable to write to a control group file" on kernel>=5.16

### ISSUE THREAD

**Issue by dubek** [kata-containers/kata-containers#4390]
(This is a preliminary report, I'll be able to add more details and kata-collect-data output next week. I wondered if anyone noticed this as well.)

# Description of problem

Agent doesn't start if the guest VM has kernel 5.16 or later.

# Expected result

Agent starts with newer kernels (>= 5.16)

# Actual result

```
{"msg":"cgroup manager set cpu","level":"INFO","ts":"2022-05-31T19:57:24.957559869+00:00","pid":"1","version":"0.1.0","source":"agent","subsystem":"cgroups","name":"kata-agent"}
{"msg":"cgroup manager set memory","level":"INFO","ts":"2022-05-31T19:57:24.957577181+00:00","version":"0.1.0","pid":"1","source":"agent","subsystem":"cgroups","name":"kata-agent"}
{"msg":"create container process error unable to write to a control group file caused by: Os { code: 95, kind: Uncategorized, message: \"Not supported\" }","level":"ERRO","ts":"2022-05-31T19:57:24.957629159+00:00","subsystem":"container","module":"rustjail","eid":"e22a347dcc0d7ccbbfc6f8684b47c8bca0f5da69296378d7727d7f038cef0a75","source":"agent","name":"kata-agent","cid":"e22a347dcc0d7ccbbfc6f8684b47c8bca0f5da69296378d7727d7f038cef0a75","version":"0.1.0","pid":"1"}
{"msg":"child exited unexpectedly","level":"INFO","ts":"2022-05-31T19:57:24.957651851+00:00","pid":"1","version":"0.1.0","child-pid":"66","name":"kata-agent","source":"agent","subsystem":"signals"}
{"msg":"read child process log end","level":"INFO","ts":"2022-05-31T19:57:24.957763361+00:00","eid":"e22a347dcc0d7ccbbfc6f8684b47c8bca0f5da69296378d7727d7f038cef0a75","version":"0.1.0","module":"rustjail","subsystem":"container","name":"kata-agent","pid":"1","action":"child process log","source":"agent","cid":"e22a347dcc0d7ccbbfc6f8684b47c8bca0f5da69296378d7727d7f038cef0a75"}
```

# Further information

Specifically the call that fails is `set_kmem_limit()` call in `src/agent/rustjail/src/cgroups/fs/mod.rs`.

I believe [this change](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=58056f77502) in the kernel (merged in v5.16) is causing the issue -- writing to `memory.kmem.limit_in_bytes` returns `-ENOTSUPP`. This write is what `set_kmem_limit` is doing under the hood (actual code is in cgroup-rs crate).

A possible solution is to remove all the `set_kmem_limit` calls from the agent (I found 3 callsites).

Another option is to modify cgroups-rs to silence this error?

**Comment by dubek** [comment]
Cc: @fitzthum

**Comment by liubin** [comment]
I'd prefer to handle this error silently in the `cgroup-rs` crate.

**Comment by dubek** [comment]
> I'd prefer to handle this error silently in the `cgroup-rs` crate.

Thanks @liubin , I managed to reproduce the issue with the cgroups-rs crate and reported it there: https://github.com/kata-containers/cgroups-rs/issues/81 . 

Note that this only happens in cgroup v1; so maybe a workaround (for the agent) is to work with the `unified_cgroup_hierarchy=1`.

**Comment by dubek** [comment]
This issue was fixed in cgroups-rs and a new crate was released: https://crates.io/crates/cgroups-rs/0.2.10

I see that the crate is referenced both in `src/agent/Cargo.toml` and in `src/agent/rustjail/Cargo.toml` -- should I updated both?
