### ISSUE TITLE
Bump golang to 1.18.3

### ISSUE THREAD

**Issue by amshinde** [kata-containers/kata-containers#4392]
golang 1.16.x is no longer supported as of Feb 2021 according to
https://endoflife.date/go
Bump the minimum version supported to 1.17.11 and the newest 
version supported to 1.18.3.

**Comment by liubin** [comment]
Related to https://github.com/kata-containers/tests/issues/5134

**Comment by stevenhorsman** [comment]
We are at go 1.22.2 now, so this is out of date.
