### ISSUE TITLE
When QEMU process is killed by oom-killer Pod Status is Succeeded instead of Error

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#4419]
We've noticed when there is memory pressure on the nodes where we run kata that invariably the VMM processes are the top of the list to be killed by the oom-killer as they generally have several Gigs of RAM in use. e.g. `/opt/kata/bin/qemu-system-x86_64`

Unfortunately when the oom-killer sends a sigkill to the vmm process to reclaim memory the resulting Pod state is...
```
Status:       Succeeded
```
With all containers similarly looking like...
```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 07 Jun 2022 11:38:21 -0700
      Finished:     Tue, 07 Jun 2022 11:40:18 -0700
 ```
 
 If running Jobs or TektonTasks this state is a real problem for us because this appears that things completed correctly when in reality things were summarily halted half way through the job/task.
 
 Instead the pod State should be something  like...
 ```
Status: Failed (or possibly OOMKilled but this is harder to determine)
```
With any "running" containers looking like...
```
    State:          Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 07 Jun 2022 15:17:56 -0700
      Finished:     Tue, 07 Jun 2022 15:18:25 -0700
 ```
 
 Would it be possible for the shim / runtime to manage an abruptly terminated VMM process it's managing and report the error.
 
 --
 
To replicate this problem you can simulate what the oom-killer is doing by starting any pod that stays running under kata onto the pod's node and `kill -9` the associated `/opt/kata/bin/qemu-system-x86_64` process or whichever VMM process. Then exit the node and `kubectl describe` the pod

To replicate the "correct" error state again start any pod that stays running under kata and then nsenter onto the pod's node and `kill -9` the `/opt/kata/bin/containerd-shim-kata-v2` process. Again exit the node and `kubectl describe` the pod

**Comment by skaegi** [comment]
Can someone give me a hand here. I'd like to contribute a fix but am having a hard time figuring out where to start. Thanks.

**Comment by fengwang666** [comment]
@skaegi It probably requires some code tracing. You can start with kubelet to see how the PodStatus is updated, and then trace down to containerd, and kata runtime to see which information is passed up to transit the PodStatus. 
Also, have you reproduced this on runc container?
Can you also upload the kubelet and containerd logs?

**Comment by fengwang666** [comment]
@skaegi Actually I couldn't reproduce this following your description using `kill -9`. Another QEMU process is automatically restarted, which is expected behavior. Is there anything special with your kubernetes workload? Was the Pod in `Running` Status before it's killed?

**Comment by liubin** [comment]
@fengwang666 I think @skaegi 's pod has a  pod with config `restartPolicy: Never`

**Comment by liubin** [comment]
@skaegi I created #4549 to set a non-zero return code if qemu is killed for some reason.

With this PR, if qemu is killed I will see:

```bash
$ kubectl describe pod hp
Name:         hp
Namespace:    default
Containers:
  container-2:
    Container ID:  containerd://9357588cb5b8613d5703285f09091f693791ef325d30457d3915a1ff2630e2be
    Image:         busybox:latest
    Command:
      sleep
      999999
    State:          Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 29 Jun 2022 12:28:31 +0800
      Finished:     Wed, 29 Jun 2022 12:30:24 +0800
    Ready:          False
    Restart Count:  0

$ kubectl get pods hp -o json | jq .status.containerStatuses
[
  {
    "containerID": "containerd://9357588cb5b8613d5703285f09091f693791ef325d30457d3915a1ff2630e2be",
    "image": "docker.io/library/busybox:latest",
    "imageID": "docker.io/library/busybox@sha256:3614ca5eacf0a3a1bcc361c939202a974b4902b9334ff36eb29ffe9011aaad83",
    "lastState": {},
    "name": "container-2",
    "ready": false,
    "restartCount": 0,
    "started": false,
    "state": {
      "terminated": {
        "containerID": "containerd://9357588cb5b8613d5703285f09091f693791ef325d30457d3915a1ff2630e2be",
        "exitCode": 255,
        "finishedAt": "2022-06-29T04:30:24Z",
        "reason": "Error",
        "startedAt": "2022-06-29T04:28:31Z"
      }
    }
  }
]

```

This PR can't get the OOM killed reason though, it gives users some exception messages.

As you said, getting the VMM exit reason is hard on the host.

**Comment by liubin** [comment]
And here is a patch that can "detect" the oom killed event by grep syslog:

```diff
diff --git a/src/runtime/pkg/containerd-shim-v2/wait.go b/src/runtime/pkg/containerd-shim-v2/wait.go
index ebb742790..cd82fa666 100644
--- a/src/runtime/pkg/containerd-shim-v2/wait.go
+++ b/src/runtime/pkg/containerd-shim-v2/wait.go
@@ -7,7 +7,9 @@ package containerdshim
 
 import (
        "context"
+       "fmt"
        "os"
+       osExec "os/exec"
        "path"
        "time"
 
@@ -21,6 +23,20 @@ import (
 
 const defaultCheckInterval = 1 * time.Second
 
+func isKilledByOOMKiller(ctx context.Context, s *service) bool {
+       pattern := fmt.Sprintf("Killed process %d", s.hpid)
+
+       _, err := osExec.Command("grep", pattern, "/var/log/syslog").Output()
+       if err != nil {
+               // error includes *exec.ExitError, when can't find the string, grep will
+               // return 1, so here return false will be ok.
+               shimLog.WithError(err).Error("failed to grep /var/log/syslog")
+               return false
+       }
+
+       return true
+}
+
 func wait(ctx context.Context, s *service, c *container, execID string) (int32, error) {
        var execs *exec
        var err error
@@ -54,6 +70,13 @@ func wait(ctx context.Context, s *service, c *container, execID string) (int32,
                        "pid":       processID,
                }).Error("Wait for process failed")
 
+               if isKilledByOOMKiller(ctx, s) {
+                       // FIXME: skip send event for pause container.
+                       s.send(&events.TaskOOM{
+                               ContainerID: c.id,
+                       })
+
+               }
                // set return code if wait failed
                if ret == 0 {
                        ret = exitCode255
```

Very this path by:

```bash

## 1. create a new group temp

root@kant-server:/sys/fs/cgroup/memory/tmp# cat memory.limit_in_bytes 
499712

## 2. add tasks to this group

root@kant-server:/sys/fs/cgroup/memory/tmp# echo 3852 > tasks 
root@kant-server:/sys/fs/cgroup/memory/tmp# echo $$ > tasks 

## wait OOM, since the limit is too small, any operations in the current shell will cause an OOM

root@kant-server:/sys/fs/cgroup/memory/tmp# ls
Killed
kant@kant-server:~$ 
```

Check the status of the pod:

```bash
Containers:
  container-2:
    Container ID:  containerd://c7b353a57cb5c2d16cb7b4d87a60162599799b9c48337e9a715850b34a596962
    Image:         busybox:latest
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    255
      Started:      Wed, 29 Jun 2022 13:30:17 +0800
      Finished:     Wed, 29 Jun 2022 13:31:53 +0800
    Ready:          False
```

This is only a hack and I'm not sure we should merge such a patch because grepping syslog is not an ideal idea.

**Comment by skaegi** [comment]
Thanks @liubin and yep I'm using `restartPolicy: Never` in this case. The OOMKilled detection is nice to have -- FWIW I think Kubernetes has similar hackery to detect them and I believe the original author had similar reservations ;) I'll test this out asap.

**Comment by skaegi** [comment]
Tested. Thanks @liubin this does exactly what I expected.
