### ISSUE TITLE
is runk at the practical stage yet?

### ISSUE THREAD

**Issue by ningmingxiao** [kata-containers/kata-containers#4444]
**Before raising this question**
I want use runk instead of runc

**Comment by liubin** [comment]
hi @ningmingxiao, `runk` is currently an experimental tool and only supports some basic command-line sub-commands/options. Welcome to evaluate it, but only continue if you are using a non-critical system.

BTW https://github.com/kata-containers/kata-containers/issues/4373 is aimed to support most of the features as an OCI command-line tools

**Comment by ningmingxiao** [comment]
ok thank you

**Comment by liubin** [comment]
@ningmingxiao I will close this issue now, if you have questions or requests, please comment at #4373
