### ISSUE TITLE
Built-in Sandbox Dragonball: Add support for aarch64 vcpu

### ISSUE THREAD

**Issue by studychao** [kata-containers/kata-containers#4445]
Currently, we mark TODO for aarch64 vCPU implementation. This issue is to track aarch64 vCPU support in Dragonball.

**Comment by studychao** [comment]
@xuejun-xj

**Comment by studychao** [comment]
test_vcpu_run_emulation unit test should be enabled in aarch64

**Comment by xuejun-xj** [comment]
See #4543
