### ISSUE TITLE
ci: snap ci failed because of the different snapcraft version

### ISSUE THREAD

**Issue by Bevisy** [kata-containers/kata-containers#4457]
I found snap ci failed when I create a pr, the error is:
```sh
Installing Snapcraft for Linux…
snapcraft 7.0.4 from Canonical* installed

Run snapcraft -d snap --destructive-mode
Usage: snapcraft [options] command [args]...
Try 'snapcraft pack -h' for help.
Error: unrecognized arguments: -d
Error: Process completed with exit code 1.
```
related ci: https://github.com/kata-containers/kata-containers/runs/6895444804?check_suite_focus=true

But the older pr which snap ci run successfully will show:
```sh
Installing Snapcraft for Linux…
snapcraft 6.1 from Canonical* installed
```
related ci: https://github.com/kata-containers/kata-containers/runs/6867509523?check_suite_focus=true

So the new version snapcraft break the ci.
cc @devimc

**Comment by jodh-intel** [comment]
@Bevisy - thanks for raising. I've just noticed this too. I'll tal at raising a PR to fix this now...

**Comment by Bevisy** [comment]
> @Bevisy - thanks for raising. I've just noticed this too. I'll tal at raising a PR to fix this now...

Thank you, waiting for your good news.
