### ISSUE TITLE
get handled signal include SigBlk, SigIgn and SigCgt

### ISSUE THREAD

**Issue by quanweiZhou** [kata-containers/kata-containers#4478]
At present, to stop the container will send the SIGTERM and then the SIGKILL. Currently, for the scenario where SIGTERM is not processed by the container, it will be converted to SIGKILL. The `is_signal_handled` function determine which signal the container process has been handled. But currently `is_signal_handled` only handles catching (SigCgt). 
When the container process is ignoring (SigIgn), blocking (SigBlk) also should not be converted to SIGKILL, should use SIGTERM.

**Comment by gkurz** [comment]
> The `is_signal_handled` function in the agent/src/rpc.rs should include handled signal SigBlk SigIgn and SigCgt.

Hi @quanweiZhou !

The semantics of this function as described in the comment header are:
```
// Check if the container process installed the
// handler for specific signal.
```
which maps exactly to the semantics of `SigCgt`.

'SigIgn' and 'SigBlk' have really different semantics. It is thus hard to see what you're trying to do here.

You'd need to put more context. Why is this needed ? Does it fix an actual bug ?

**Comment by quanweiZhou** [comment]
> > The `is_signal_handled` function in the agent/src/rpc.rs should include handled signal SigBlk SigIgn and SigCgt.
> 
> Hi @quanweiZhou !
> 
> The semantics of this function as described in the comment header are:
> 
> ```
> // Check if the container process installed the
> // handler for specific signal.
> ```
> 
> which maps exactly to the semantics of `SigCgt`.
> 
> `SigIgn` and `SigBlk` have really different semantics. It is thus hard to see what you're trying to do here.
> 
> You'd need to put more context. Why is this needed ? Does it fix an actual bug ?

At present, to stop the container will send the SIGTERM and then the SIGKILL. Currently, for the scenario where SIGTERM is not processed by the container, it will be converted to SIGKILL. The `is_signal_handled` function determine which signal the container process has been handled. But currently `is_signal_handled` only handles catching (SigCgt).
When the container process is ignoring (SigIgn) or blocking (SigBlk) also should not be converted to SIGKILL, should use SIGTERM. For example, when use terminationGracePeriodSeconds the k8s will send SIGTERM first and then send SIGKILL , in this case the container ignore the SIGTERM, so we should send the SIGTERM not the SIGKILL to container.
