### ISSUE TITLE
Add hotplug net device support for cloud hypervisor

### ISSUE THREAD

**Issue by BetaXOi** [kata-containers/kata-containers#453]
**Is your feature request related to a problem? Please describe.**

Add hotplug net device support for cloud hypervisor

**Describe the solution you'd like**

Use cloud hypervisor `/vm.add-net` API to hotplug net device

**Describe alternatives you've considered**

**Additional context**

Currently executing `docker network connect test_container test_net` has no effect, and the log shows the following error
> Jul 24 17:09:46 A23074915-33 kata-runtime[9023]: time="2020-07-24T17:09:46.142298499+08:00" level=error msg="Error attach virtual ep" arch=amd64 command=kata-network container=aec7f1d3a255f9132a2e33326e312549de87eb1c01c8ddd41dcc11da1db859a4 error="cannot hotplug device: unsupported device type '2'" name=kata-runtime pid=9023 sandbox=aec7f1d3a255f9132a2e33326e312549de87eb1c01c8ddd41dcc11da1db859a4 source=virtcontainers subsystem=network

**Comment by fidencio** [comment]
@likebreath, @jcvenegas, @BetaXOi, is this issue still valid?  Or could we just close it?

**Comment by fidencio** [comment]
I've removed the "needs-review" label and added the "area/cloud-hypervisor" one.  Please, feel free to set the label accordingly, in case what I added is not correct, or not as accurate as it could be.
