### ISSUE TITLE
CC | packaging: Allow building Cloud Hypervisor for the CC effort

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#4566]
Currently there's no single command that allow us to build Cloud Hypervisor in a way it can be used in the Confidential Containers effort.

What's currently missing is a build target in the scripts used to generate the tarball that could build Cloud Hypervisor and have it installed the appropriate destdir (/opt/confidential-containers/...)

**Comment by stevenhorsman** [comment]
Closed with #4570 merging
