### ISSUE TITLE
CC | packaging: Allow building QEMU for the CC effort

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#4568]
Currently there's no single command that allow us to build the QEMU in a way it can be used in the Confidential Containers effort.

What's currently missing is a build target in the scripts used to generate the tarball that could build QEMU and have it installed the appropriate destdir (/opt/confidential-containers/...).

For now we don't care about having the QEMU built for a specific TEE flavour, as the first target of the release will be targeting non-TEE hardware (as part of our CI).

**Comment by stevenhorsman** [comment]
Closed with #4570 merging
