### ISSUE TITLE
CC | packaging: Allow building virtiofsd for the CC effort

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#4569]
Currently there's no single command that allow us to build the virtiofsd in a way it can be used in the Confidential Containers effort.

What's currently missing is a build target in the scripts used to generate the tarball that could build virtiofsd and have it installed the appropriate destdir (/opt/confidential-containers/...).

Keeping in mind that virtiofsd will **NOT** be used by the CC effort, but as the very first release target doesn't include TEE support, let's not force those who want to give it a try to setup devicemapper.

**Comment by stevenhorsman** [comment]
Closed with #4570 merging
