### ISSUE TITLE
Update CCv0 documentation for the ccv0-ssh demos so that skopeo is no longer required

### ISSUE THREAD

**Issue by tong-luo1** [kata-containers/kata-containers#4587]
**Which feature do you think can be improved?**

We did a test of the [ccv0-ssh demo](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md#using-kubernetes-to-create-a-kata-confidential-containers-pod-from-the-encrypted-ssh-demo-sample-image) and realized that `skopeo` is no longer a required tool for the demo to succeed, so `export SKOPEO="yes"` could now be removed from the demo documentation.

**How can it be improved?**

We think the line `export SKOPEO="yes"` could be deleted from [this section](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md#using-kubernetes-to-create-a-kata-confidential-containers-pod-from-the-encrypted-ssh-demo-sample-image) of the document.

**Additional Information**

Anything else to add? Nothing comes to mind so far.

**Before raising this enhancement request**

Have you looked at the [limitations document](https://github.com/kata-containers/kata-containers/blob/main/docs/Limitations.md)?  YES!

**Comment by stevenhorsman** [comment]
This was closed with #4682 merging
