### ISSUE TITLE
Running make as non-privilged user fails for cloud-hypervisor buiild

### ISSUE THREAD

**Issue by amshinde** [kata-containers/kata-containers#4594]
While running make as non-privileged user, the make errors out with
the following message:
`INFO: Build cloud-hypervisor enabling the following features: tdx
Got permission denied while trying to connect to the Docker daemon
socket at unix:///var/run/docker.sock: Post
"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=cloudhypervisor%2Fdev&tag=20220524-0":
dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%22TARGETARCH%22%3A%22amd64%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=cloudhypervisor%2Fdev%3A20220524-0&target=dev&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
[Cloud Hypervisor] Error pulling/building container image. Aborting.
`

Even though the user may be part of docker group, when clh is built from
source in case of additional features, it performs a docker in docker build. It is necessary for the user of
the nested container to be part of docker build for the build to succeed.

This issue is not seen when the build is run as a non-privileged user in github actions, as the user account is setup in such a way that the effective group id of the user is "docker" be default:
`uid=1001(runner) gid=121(docker) groups=121(docker),4(adm),101(systemd-journal)`

**Comment by cmaf** [comment]
I was able to replicate this with the same error, latest commit from kata-containers
