### ISSUE TITLE
UT failure: test_update_container_namespaces is unstable

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#4598]
> thread 'rpc::tests::test_update_container_namespaces' panicked at 'called `Result::unwrap()` on an `Err` value: Bad file descriptor (os error 9)', src/rpc.rs:2413:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: kata_agent::rpc::tests::test_update_container_namespaces::{{closure}}
             at ./src/rpc.rs:2413:31
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:508:48
   8: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
  11: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  12: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:508:25
  14: tokio::runtime::basic_scheduler::Context::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:[362](https://github.com/kata-containers/kata-containers/runs/7207764293?check_suite_focus=true#step:13:363):19
  15: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:507:36
  16: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:565:57
  17: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs:61:9
  18: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:565:27
  19: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:498:9
  20: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/basic_scheduler.rs:174:24
  21: tokio::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/mod.rs:480:46
  22: kata_agent::rpc::tests::test_update_container_namespaces
             at ./src/rpc.rs:2409:9
  23: kata_agent::rpc::tests::test_update_container_namespaces::{{closure}}
             at ./src/rpc.rs:2307:11
  24: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test rpc::tests::test_update_container_namespaces ... FAILED

**Comment by bergwolf** [comment]
I've debugged it into `get_mount_fs_type_from_file()` and it is an error reading `/proc/self/mountstats` and failing with `EBADF`. However, I am not sure why it failed that way. And I even tried to replace `/proc/self/mountstats` with `/proc/mounts` (which shouldn't be affected by the possible vanishing tokio worker threads) but it still failed with `EBADF` randomly.

See my changes at https://github.com/bergwolf/kata-containers/commits/github/agent-error

**Comment by bergwolf** [comment]
The error I now get (with my changes) is
> thread 'rpc::tests::test_update_container_namespaces' panicked at 'called `Result::unwrap()` on an `Err` value: read mount file /proc/mounts: Bad file descriptor (os error 9)', src/rpc.rs:2398:53

**Comment by liubin** [comment]
> The error I now get (with my changes) is
> 
> > thread 'rpc::tests::test_update_container_namespaces' panicked at 'called `Result::unwrap()` on an `Err` value: read mount file /proc/mounts: Bad file descriptor (os error 9)', src/rpc.rs:2398:53

The same as https://github.com/kata-containers/kata-containers/issues/4103#issuecomment-1170037907

I doubt whether it only occurs in GitHub action runners.

**Comment by bergwolf** [comment]
> I doubt whether it only occurs in GitHub action runners.

Nop, I can reproduce it reliably locally.

> Does set a default value of ext4 reasonable in case of get_mount_fs_type_from_file fail? Though it's a "workaround" for this case.

It may work but I'd like to get to the root cause. Besides, ext4 may not always be a proper default. E.g., Red Hat may choose to default to XFS instead. It's better if we can identify and fix the root cause.

**Comment by bergwolf** [comment]
A few more thoughts:
1. Does tokio create worker threads with shared FD table?
2. At what point does tokio move workloads among threads?

Pinging more tokio experts, @Tim-Zhang @lifupan. Any idea about these questions?

**Comment by bergwolf** [comment]
Looks like FDs in the tokio runtime is somewhat in a mess:
```
thread 'sandbox::tests::unset_sandbox_storage' panicked at 'Failed building the Runtime: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', src/sandbox.rs:677:10
```
