### ISSUE TITLE
clh: Migrate the development efforts on cloud-hypervisor to Kata 2.0

### ISSUE THREAD

**Issue by likebreath** [kata-containers/kata-containers#461]
**Which feature do you think can be improved?**

As for now, the development efforts on cloud-hypervisor (clh) in Kata are still focusing on Kata 1.x ( fro repo kata-runtime, kata-tests, kata-packaging, etc). Given Kata 2.0 is now stabilized and are recommended for feature development, it is the right time to migrate clh development efforts to Kata 2.0 too.

**How can it be improved?**

In general, we will need to make sure clh support in Kata 2.0 is on parity with Kata 1.x: 1) Enable clh related CI jobs, e.g. docker/k8s integration tests, VFIO, e2e, metrics, etc. 2) Consolidate the feature supports of cloud-hypervisor in Kata 1.x and 2.0 (mostly port missing patches from 1.x to 2.0). 3) Migrate open issues/PRs on clh to Kata 2.0.

**Comment by likebreath** [comment]
/cc  @amshinde @bergwolf @jcvenegas @chavafg @jodh-intel  @GabyCT @devimc  @sboeuf @BetaXOi

Please let me know your thoughts about whether it is the right time to make this move. Also, any comments or advises about how to migrate, please don't hesitate to share. Thanks.

**Comment by chavafg** [comment]
+1 on porting the CLH patches to 2.0 branch and add initial CI jobs. There will be tests that currently do not work, but initial testing with containerd and k8s should work.
