### ISSUE TITLE
Add error handling for the getVersionInfo function in cloud-hypervisor

### ISSUE THREAD

**Issue by amshinde** [kata-containers/kata-containers#463]
The function for getting version info was failing on a system
without any indication of the error.

**Comment by ariel-adam** [comment]
Fixed in issue #2863

**Comment by jodh-intel** [comment]
Hi @amshinde - please could you port this one to 2.0?

**Comment by cmaf** [comment]
@amshinde can we close this, or do we still need to port to 2.0?
