### ISSUE TITLE
Support for latest version of firecracker (>= 1.0) planned?

### ISSUE THREAD

**Issue by tomhatzer** [kata-containers/kata-containers#4673]
**Before raising this question**

Have you looked at our [document](https://github.com/kata-containers/kata-containers/tree/main/docs) and still haven't found the answer?

Yes, I have 😃

----------------

Dear kata-containers team 🤗 

first of all, thank you very, very much for your hard work on this incredible piece of software. 🚀 

I'd like to ask if there's support for the latest version of firecracker planned on your side or if this is something that's not on the roadmap?

Thank you very much and have a joyful day! 🙇 

Best wishes
Tom

**Comment by ananos** [comment]
Hi Tom! 

we are actually working on getting updated FC support as we speak ;) We had v0.25 support, but it fell through the cracks... 

FC v1.1 should be available on a branch in the next couple of weeks and we might as well be ready to include it in the next release (IIRC due late Aug). We will keep you posted.

thanks for your interest and your kind words!

cheers,
Tassos

**Comment by tomhatzer** [comment]
Hi Tassos!

This is incredible, thank you very much. 🥳

Best wishes
Tom
