### ISSUE TITLE
agent: add support for guest-hooks

### ISSUE THREAD

**Issue by lifupan** [kata-containers/kata-containers#475]
# Description of problem

Adds support for running OCI hooks within the guest.
just as  https://github.com/kata-containers/agent/pull/393 did.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by bergwolf** [comment]
closed by https://github.com/kata-containers/kata-containers/pull/563
