### ISSUE TITLE
During rootfs creation, attestation-agent fails to build due to 'libgit2-sys' dependency issue

### ISSUE THREAD

**Issue by ryansavino** [kata-containers/kata-containers#4764]
# Description of problem

Building the rootfs in kata-containers branch `CCv0`.

CI command used (directory: kata-containers/tools/osbuilder):
```
sudo -E USE_DOCKER=true DISTRO=ubuntu AA_KBC=offline_sev_kbc UMOCI=yes make -e "image"
```

My testing command used (directory: kata-containers/tools/osbuilder/rootfs-builder):
```
sudo -E GOPATH=~/go AGENT_INIT=yes USE_DOCKER=true DOCKER_RUNTIME=runc AA_KBC=offline_sev_kbc SKOPEO_UMOCI=yes  ./rootfs.sh ubuntu
```

# Expected result

Building the rootfs should result in a successful output from the rootfs.sh and the creation of the rootfs on the host disk.

# Actual result

The rootfs script throws an error during the attestation-agent build:
```
Cloning into 'attestation-agent'...
/attestation-agent/app /
    Updating crates.io index
error: failed to select a version for the requirement `libgit2-sys = "^0.13.4"`
candidate versions found which didn't match: 0.13.2+1.4.2, 0.13.1+1.4.2, 0.13.0+1.4.1, ...
location searched: crates.io index
required by package `git2 v0.14.4`
    ... which satisfies dependency `git2 = "^0.14.2"` (locked to 0.14.4) of package `shadow-rs v0.11.0`
    ... which satisfies dependency `shadow-rs = "^0.11.0"` (locked to 0.11.0) of package `attestation-agent v1.0.0 (/attestation-agent/app)`
Failed at 672: CC= cargo build --release --target "${target}" --no-default-features --features "${AA_KBC}"
Script done, file is typescript
```

**Comment by ryansavino** [comment]
The attestation-agent throws this error when building against a rust version 1.58.1. Updating to stable 1.62.0 resolves the issue. To do this inside the rootfs created docker container, kata-containers/versions.yaml needs to be updated. Will generate a PR for main for this.

**Comment by wainersm** [comment]
We are likely to suffer of rust compiler version breakages while we keep fetching from attestation-agent main branch (see https://github.com/kata-containers/kata-containers/blob/CCv0/versions.yaml#L178). In other words, at the point we agree that attestation-agent fills all our requirements for CC v1 release then we must pin in a commit/branch/tag.

@fitzthum  @jialez0 how far are we from having the attestation-agent ready for v1?

**Comment by fitzthum** [comment]
Honestly we could probably cut a release just about anytime. I think all of the core functionality for the first release has been supported for a while. That said, I am trying to sneak in a few SEV related features (mainly for signature support). If it would greatly simplify your life we can cut a release in the near future. Otherwise it might be nice to wait a few weeks. 

I think we can solve this issue with a simple bump of the Rust version. I don't foresee a lot of problems in the next month if we do that

WDYT @jialez0
