### ISSUE TITLE
CI kata-deploy failing to make kata tarball due to shared agent directory conflicts

### ISSUE THREAD

**Issue by ryansavino** [kata-containers/kata-containers#4787]
# Description of problem

CI kata-deploy test for 'make-kata-tarball' fails for branch `main`.

Testing command used to reproduce (directory: kata-containers):
```
make kata-tarball
```

# Expected result

kata tarball should be created.

# Actual result

The kata-agent fails to build during the tarball creation.
tools/packaging/kata-deploy/local-build/Makefile
Target: rootfs-initrd-tarball-build

```
   Compiling slog v2.7.0
   Compiling hashbrown v0.12.1
error: could not write output to /kata-containers/src/agent/target/release/build/slog-e9179efe9a84fbd0/build_script_build-e9179efe9a84fbd0.build_script_build.ca7294ca-cgu.13.rcgu.o: No such file or directory

error: error writing dependencies to `/kata-containers/src/agent/target/release/deps/hashbrown-d69ab10a53de4603.d`: No such file or directory (os error 2)

error: could not compile `slog` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `hashbrown` due to previous error
make: *** [Makefile:116: target/x86_64-unknown-linux-musl/release/kata-agent] Error 101
Failed at 585: make LIBC=${LIBC} INIT=${AGENT_INIT} SECCOMP=${SECCOMP}
make: *** [Makefile:93: /home/runner/work/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build/build/rootfs-initrd/builddir/initrd-image/.alpine_rootfs.done] Error 2
make[2]: *** [tools/packaging/kata-deploy/local-build/Makefile:34: rootfs-initrd-tarball-build] Error 1
make[2]: Leaving directory '/home/runner/work/kata-containers/kata-containers'
make[1]: *** [/home/runner/work/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build/Makefile:56: rootfs-initrd-tarball] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/runner/work/kata-containers/kata-containers'
make[1]: Leaving directory '/home/runner/work/kata-containers/kata-containers'
make: *** [tools/packaging/kata-deploy/local-build/Makefile:22: all-parallel] Error 2
Error: Process completed with exit code 2.
```

**Comment by ryansavino** [comment]
`No such file or directory` errors are being thrown because `tools/packaging/kata-deploy/local-build/Makefile` runs the target `all-parallel` target.

```
all-parallel: $(MK_DIR)/dockerbuild/install_yq.sh
        ${MAKE} -f $(MK_PATH) all -j$$(( $$(nproc) - 1  )) V=

all: cloud-hypervisor-tarball \
        firecracker-tarball \
        kernel-tarball \
        qemu-tarball \
        rootfs-image-tarball \
        rootfs-initrd-tarball \
        shim-v2-tarball \
        virtiofsd-tarball
```

The docker container mounts the host `kata-containers` repo as a volume:

```
-v /root/kata-fork/kata-containers/tools/osbuilder/rootfs-builder/../../../:/kata-containers
```

This means that all tasks share the kata-agent directories of the repo from the host. Multiple tasks sharing the agent directory while building is causing these errors. Specifically the rootfs.sh is runng and agent `make clean` which is deleting files and directories that are used by the other Makefile tasks.

There are a couple ways to resolve this:
1. Stop running the tasks in parallel - I've confirmed this works consistently
2. Mount separate volumes or add git checkout for kata-containers repo in each task
3. Remove the rootfs kata-agent `make clean` - there may still be other issues

Thoughts? @fidencio

**Comment by liubin** [comment]
Thank you, @ryansavino
Is it possible that [this commit](https://github.com/kata-containers/kata-containers/commit/0e40ecf383850c6eeb23ac2e80702f0f13a76d7a) introduced this problem? This commit changed the `-j` options for builds.

**Comment by ryansavino** [comment]
Even if it's 2 threads, I think it could run into the same issue, right? @bookinabox

**Comment by bookinabox** [comment]
@ryansavino @liubin I believe the Github Runner runs on two processing units, so it should be 1. $CI should be set as `true` when we run it through actions. Not sure why it would not ignore 1.

**Comment by ManaSugi** [comment]
@ryansavino @bookinabox 
I guess this issue will be solved by https://github.com/kata-containers/kata-containers/pull/4951 that passes `CI` variable.

**Comment by ManaSugi** [comment]
@bookinabox @ryansavino
Is this `$(shell nproc ${CI:+--ignore 1}` correct behavior?
I think this adds `--ignore 1` if the `CI` variable is set. Hence, as mentioned in https://github.com/kata-containers/kata-containers/issues/3967, we cannot avoid DoS-ing our local systems.

**Comment by wainersm** [comment]
> `No such file or directory` errors are being thrown because `tools/packaging/kata-deploy/local-build/Makefile` runs the `all-parallel` target.
> 
> ```
> all-parallel: $(MK_DIR)/dockerbuild/install_yq.sh
>         ${MAKE} -f $(MK_PATH) all -j$$(( $$(nproc) - 1  )) V=
> 
> all: cloud-hypervisor-tarball \
>         firecracker-tarball \
>         kernel-tarball \
>         qemu-tarball \
>         rootfs-image-tarball \
>         rootfs-initrd-tarball \
>         shim-v2-tarball \
>         virtiofsd-tarball
> ```
> 
> The docker container mounts the host `kata-containers` repo as a volume:
> 
> ```
> -v /root/kata-fork/kata-containers/tools/osbuilder/rootfs-builder/../../../:/kata-containers
> ```
> 
> This means that all tasks share the kata-agent directories of the repo from the host. Multiple tasks sharing the agent directory while building is causing these errors. Specifically the rootfs.sh is running an agent `make clean` which is deleting files and directories that are used by the other Makefile tasks.
> 

Very good analysis @ryansavino !

IIUC rootfs-image-tarball and rootfs-initrd-tarball targets cannot run in parallel as they will share the the agent source directory.

As explained by @ManaSugi somewhere, github gives 2 cpus for the job.  We were running in `nproc -1` (i.e. in 1 cpu), therefore `all-parallel` was actually running in serial. However, https://github.com/kata-containers/kata-containers/commit/0e40ecf383850c6eeb23ac2e80702f0f13a76d7a introduced a bug that unveiled the problem as now the job run with `nproc` (i.e. in 2 cpu) as @liubin noticed.

> There are a couple ways to resolve this:
> 
>     1. Stop running the tasks in parallel - I've confirmed this works consistently
>

Yep, but it will increase a lot the build time.... :(

>     2. Mount separate volumes or add git checkout for kata-containers repo in each task
>

Could you please explain this "mount separate volumes"?
 
>     3. Remove the rootfs kata-agent `make clean` - there may still be other issues

Yeah, there might be other issues...also with confidential containers we will build two kernels (tdx and sev), two qemu..etc...and we still don't know what issues will raise.

> 
> 
> Thoughts? @fidencio

**Comment by ryansavino** [comment]
Option 2 is probably not viable. I was thinking we could create separate directories and mount them to the container so that separate work for each thread would not interrupt files being modified in the agent. However, the Makefile in the repo wouldn't be called in parallel in this case anyways.

What if we create a separate target for tasks that have to be run serially and then add that to the `all` target? @wainersm?

**Comment by wainersm** [comment]
> Option 2 is probably not viable. I was thinking we could create separate directories and mount them to the container so that separate work for each thread would not interrupt files being modified in the agent. However, the Makefile in the repo wouldn't be called in parallel in this case anyways.
> 
> What if we create a separate target for tasks that have to be run serially and then add that to the `all` target? @wainersm?
> 

@ryansavino I thought exactly on that for the short term. On long run maybe we could try to mount a overlay fs on the volume so the changes aren't propagated to other containers.

> Something like:
> 
> ```
> all-parallel: $(MK_DIR)/dockerbuild/install_yq.sh
>         ${MAKE} -f $(MK_PATH) all -j$$(( $$(nproc) - 1  )) V=
> 
> all: cloud-hypervisor-tarball \
>         firecracker-tarball \
>         kernel-tarball \
>         qemu-tarball \
>         rootfs-tarballs \
>         shim-v2-tarball \
>         virtiofsd-tarball
> 
> rootfs-tarballs: rootfs-image-tarball \
>         rootfs-initrd-tarball
> ```

@ryansavino could you please send a PR with ^ fix?
