### ISSUE TITLE
Fix all compiler warnings in new rust agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#48]
The [new rust agent builds](https://github.com/alipay/kata-rust-agent/), but the compiler isn't 100% happy.

**Comment by yyyeerbo** [comment]
I am working on this

**Comment by jodh-intel** [comment]
Thanks @yyyeerbo !

**Comment by yyyeerbo** [comment]
The pr is here: https://github.com/alipay/kata-rust-agent/pull/8

**Comment by yyyeerbo** [comment]
We'd like to get your comments

**Comment by bergwolf** [comment]
already fixed.
