### ISSUE TITLE
runtime-rs: build failed when the arch is s390x

### ISSUE THREAD

**Issue by Tim-0731-Hzt** [kata-containers/kata-containers#4816]
`kata-containers-2.0-ubuntu-s390x-unit` will compile the `runtime-rs`. However, `s390x` platform is not supported currently for `runtime-rs.`

**Comment by studychao** [comment]
PS: rust runtime could work with s390x but our built-in VMM could not work on s390x platform.

After we implement the support for QEMU, we could have support for s390x through QEMU.
