### ISSUE TITLE
Runk: support cgroup v2 for `status::get_all_pid`

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#4821]
Test fails on Ubuntu 22.04 because `status::get_all_pid` only works on cgroup v1 now.  Temporarily skip tests on cgroup v2 environment.  Please run test again.  @ManaSugi @liubin

_Originally posted by @cyyzero in https://github.com/kata-containers/tests/issues/4942#issuecomment-1205248326_

**Comment by liubin** [comment]
@cyyzero would you like to fix this?

**Comment by cyyzero** [comment]
Please assign to me.

**Comment by cyyzero** [comment]
This issue is fixed and can be closed now.

**Comment by liubin** [comment]
Hi @cyyzero which PR fixed this?

**Comment by liubin** [comment]
Close it by #4870

**Comment by ManaSugi** [comment]
@cyyzero Thank you!
