### ISSUE TITLE
Update Roadmap in architecture_3.0

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#4884]
In [roadmap](https://github.com/kata-containers/kata-containers/blob/main/docs/design/architecture_3.0/README.md#roadmap), the `Development Stage` should be updated:

- For implemented features, add `(implemented)`
- For features that not been implemented, add an issue link after the `stage 1/2/3`.

**Comment by liubin** [comment]
Who's better to assign this issue to? @Tim-0731-Hzt @quanweiZhou @studychao

**Comment by Tim-0731-Hzt** [comment]
Thanks @liubin , I will do this later this week
