### ISSUE TITLE
[Feature Request] Support disable_new_netns with Kube-OVN CNI.

### ISSUE THREAD

**Issue by xujunjie-cover** [kata-containers/kata-containers#4914]
## Background
Kube-OVN can provide tap or vhostuserclinet device for Kata Containers. Kata Containers can used these devices directly.
Kube-OVN support ovs-dpdk (datapath_type netdev).

## Status
Detailed introduction link https://github.com/kata-containers/kata-containers/issues/1922

current data flow like this:
![原架构](https://user-images.githubusercontent.com/27765472/184659870-6267fcbc-fed8-48a7-a79a-a0f0d7171454.png)

## Proposal
Kata containers use tap devices in host NetNS. then data flow like this:
![新架构](https://user-images.githubusercontent.com/27765472/184659797-94629e39-eb49-4f7d-b770-3bcfebb9d35a.png)
*we can reduce network stack jumps*.

control flow for using tap device directly:
![control flow](https://user-images.githubusercontent.com/27765472/184660419-cbd7d49f-018b-475a-bd09-5edf892bc473.png)

**the part of kube-ovn is same as provide vhost-user.**

## Need Kube-OVN to do
- create dummy device to transmit network info.
- create multiple vhost-user or tap device for one kata container.
- support use tap or vhost-user device as frist nic.

## Need Kata to change
- add support for vhost-user with server type like this. "server=on"
```
-chardev socket,id=char-6ca95a82dad2acd6,path=/var/run/openvswitch/vhost_sockets/c3851524-a4bb-48bb-8878-98449e988b7e/hugepages/sock,server=on
```
- add support: multiple nic queues for kata with multiple cpus. get better performance.
- add support tap device in host netNs like this.
```
-netdev tap,id=network-0,vhost=on,ifname=tap_69adfedcf5c,downscript=no,script=no
```

## Performance
TODO: we are doing test. More details will be shown here later.
some test using vhostuserclinet provided by ovs-dpdk:
ovs: 4c8g
1. ovs-dpdk + dpdk app runing in kata
```
Tools: dpdk-testpmd
Version: v21.02
Driver: uio_pci_generic
Hugepages: 512 2M
cpu: 1c already set by cpu_manage. (Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz)
Env: two kata containers in same node.
```
Packet Len(bytes) | pps(M) | Throughput (Gbits/second)
-- | -- | --
64 | 6.5 | 3.1
1400 | 3.93 | 41

2. ovs-dpdk + general app
```
Tools: qperf
Hugepages: 512 2M
cpu: 2c already set by cpu_manage. (Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz)
```
we thought the performance limitations is from qperf use cpu.
*two kata containers in same node*
Packet Len(bytes) | tcp_lat(us) | Throughput
-- | -- | --
64 | 10.7 | 518 Mb/sec
256 | 9.7 | 1.36 Gb/sec
512 | 11 | 1.83 Gb/sec
1024 | 10.1 | 2.25 Gb/sec
2048 | 14.9 | 3.19 Gb/sec
4096 | 16.2 | 6.35 Gb/sec
8192 | 17.5 | 9.8 Gb/sec

*two kata containers in different node, physical nic X710 10GbE SFP+*
Packet Len(bytes) | tcp_lat(us) | Throughput
-- | -- | --
64 | 17 | 556 Mb/sec
256 | 17.1 | 1.67 Gb/sec
512 | 18.1 | 2.41 Gb/sec
1024 | 19.4 | 3.09 Gb/sec
2048 | 39.9 | 7.55 Gb/sec
4096 | 40.8 | 8.49 Gb/sec
8192 | 43.9 | 8.99 Gb/sec

## Related Link:
https://github.com/kubeovn/kube-ovn/issues/1811

**Comment by bergwolf** [comment]
cc @kata-containers/architecture-committee

**Comment by oilbeater** [comment]
@xujunjie-cover do you have the comparison data before and after the optimization

**Comment by justxuewei** [comment]
I wonder why Kata containers need to support tap devices in the host netns if it could connect to vhost-user-socket directly?
