### ISSUE TITLE
When using kernel 5.15.57+ on x86_64 need CONFIG_SPECULATION_MITIGATIONS=y

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#4918]
I'm building using Kata 2.4.3 on x86_64 and needed to update the kernel to something very recent (5.15.57+). When running `./build-kernel.sh ... setup` I got the following fatal error.

```
INFO: Constructing config from fragments: /root/go/src/github.com/kata-containers/kata-containers/tools/packaging/kernel/configs/fragments/x86_64/.config
INFO: Some CONFIG elements failed to make the final .config:
INFO: Value requested for CONFIG_RETPOLINE not in final .config
Value requested for CONFIG_PAGE_TABLE_ISOLATION not in final .config
INFO: Generated config file can be found in /root/go/src/github.com/kata-containers/kata-containers/tools/packaging/kernel/configs/fragments/x86_64/.config
ERROR: Failed to construct requested .config file
```

For now I'm managing this by adding `CONFIG_SPECULATION_MITIGATIONS=y`. Looking at the [5 .15.57 diff](https://lore.kernel.org/all/165857484915686@kroah.com/t/) Kconfig has been updated to now require SPECULATION_MITIGATIONS to enable RETPOLINE and PAGE_TABLE_ISOLATION and a few other related config settings.

I noticed this is already in-progress  for the move to 5.19 -- https://github.com/kata-containers/kata-containers/pull/4861 -- but I wanted to call this out explicitly for those who are sticking with 5.15.x and if another kernel bump happens for 2.4.x.

**Comment by fidencio** [comment]
@skaegi, with us releasing Kata Containers 2.5.0 Today the stable-2.4 branch will stop being maintained.  Still, we need to fix that there as well.

If you're going to stay in the 2.4.x for a while, and that's understandable, I'd recommend you to:

* Bump the kernel version in the `versions.yaml` file:
```
diff --git a/versions.yaml b/versions.yaml
index b22a33486..09e61bd5c 100644
--- a/versions.yaml
+++ b/versions.yaml
@@ -153,7 +153,7 @@ assets:
   kernel:
     description: "Linux kernel optimised for virtual machines"
     url: "https://cdn.kernel.org/pub/linux/kernel/v5.x/"
-    version: "v5.15.26"
+    version: "v5.15.60"
     tdx:
       description: "Linux kernel that supports TDX"
       url: "https://github.com/intel/tdx/archive/refs/tags"

```

* Remove the non-needed patches for ARM (@jongwu, I could have your help to confirm that's actually the case)
```
rm tools/packaging/kernel/patches/5.15.x/arm-experimental/0006-arm64-mm-avoid-fixmap-race-condition-when-create-pud.patch
rm tools/packaging/kernel/patches/5.15.x/arm-experimental/0007-virtio-mem-enable-virtio-mem-on-arm64.patch
```

* Add the `CONFIG_SPECULATION_MITIGATIONS=y` to the base.conf file for the x86_64 architecture
```
diff --git a/tools/packaging/kernel/configs/fragments/x86_64/base.conf b/tools/packaging/kernel/configs/fragments/x86_64/base.conf
index 3734b51bd..f66885aa2 100644
--- a/tools/packaging/kernel/configs/fragments/x86_64/base.conf
+++ b/tools/packaging/kernel/configs/fragments/x86_64/base.conf
@@ -16,6 +16,7 @@ CONFIG_NR_CPUS=240
 # For security
 CONFIG_LEGACY_VSYSCALL_NONE=y
 CONFIG_RETPOLINE=y
+CONFIG_SPECULATION_MITIGATIONS=y
 
 # Boot directly into the uncompressed kernel
 # Reduce memory footprint
```

And that should be enough for you to have what you need.  I just built it myself from my side and it worked as expected.

**Comment by skaegi** [comment]
Yep our build currently builds the kernel independently in a custom docker image where we're currently doing this...
```
# Support for Kernel 5.15 (remove arm-experimaental)
RUN \
	rm -rf ~/go/src/github.com/kata-containers/kata-containers/tools/packaging/kernel/patches/5.15.x/arm-experimental

# Support for Kernel 5.15.57+ (CONFIG_SPECULATION_MITIGATIONS required)
RUN \
	sed -i '/^CONFIG_RETPOLINE=y/i CONFIG_SPECULATION_MITIGATIONS=y' \
	~/go/src/github.com/kata-containers/kata-containers/tools/packaging/kernel/configs/fragments/x86_64/base.conf
```

**Comment by jongwu** [comment]
@fidencio -, I see that the patch which enable virtio-mem on arm64 has not backport to 5.15, therefore, we should not remove 0007-virtio-mem-enable-virtio-mem-on-arm64.patch. We can remove 0006-arm64-mm-avoid-fixmap-race-condition-when-create-pud.patch as it has been backport to 5.15.

**Comment by skaegi** [comment]
Closing. This is just old now ;)
