### ISSUE TITLE
CC | kata-deploy should be flexible to build the image with/without skopeo

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#4959]
**Which feature do you think can be improved?**

Currently `make cc-rootfs-image` will always build the image with *skopeo*, see https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L116

We got CI jobs to test the guest with and without skopeo. Some tests will simply be skipped if skopeo is not installed (see on the log below), those tests rely on the `SKOPEO` variable to decide when to skip. If we want to use kata-deploy assets on CI then we need to:
 1. Build the image without skopeo too;
 2. Honor the value of `SKOPEO` exported in the environment 

```
ok 1 [cc][agent][kubernetes][containerd] Test can pull an unencrypted image inside the guest
ok 2 [cc][agent][kubernetes][containerd] Test can pull a unencrypted signed image from a protected registry # skip Skopeo seems not installed in guest
ok 3 [cc][agent][kubernetes][containerd] Test cannot pull an unencrypted unsigned image from a protected registry # skip Skopeo seems not installed in guest
ok 4 [cc][agent][kubernetes][containerd] Test can pull an unencrypted unsigned image from an unprotected registry # skip Skopeo seems not installed in guest
ok 5 [cc][agent][kubernetes][containerd] Test unencrypted signed image with unknown signature is rejected # skip Skopeo seems not installed in guest
1..2
ok 1 [cc][agent][kubernetes][containerd] Test can pull an encrypted image inside the guest with decryption key
ok 2 [cc][agent][kubernetes][containerd] Test cannot pull an encrypted image inside the guest without decryption key
```

**How can it be improved?**

Ideally we should have one asset with skopeo (rootfs-image-skope) and another without (rootfs-image). However the plan is to remove skopeo still on the first release CCv1, so it is not worth the effort. An alternative is to just not hardcode the value on the script, something like:

```
diff --git a/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh b/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
index 5aa8bd336..a06a0c4c9 100755
--- a/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
+++ b/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
@@ -112,11 +112,11 @@ install_cc_clh() {
 
 #Install cc capable guest image
 install_cc_image() {
-       info "Create CC image"
-       export SKOPEO=yes
+       export SKOPEO=${SKOPEO:-yes}
        export UMOCI=yes
-       export AA_KBC="offline_fs_kbc"
+       export AA_KBC=${AA_KBC:-"offline_fs_kbc"}
 
+       info "Create CC image configured with SKOPEO=${SKOPEO} UMOCI=${UMOCI} AA_KBC=${AA_KBC}"
        "${rootfs_builder}" --imagetype=image --prefix="${cc_prefix}" --destdir="${destdir}"
 }
``` 

Cc @fidencio @stevenhorsman

**Comment by stevenhorsman** [comment]
@wainersm - Hey Wainer, can this be closed now #4960 has been merged, or is there anything outstanding?
