### ISSUE TITLE
Using loop device with ctr --mount

### ISSUE THREAD

**Issue by wenzt** [kata-containers/kata-containers#4962]
kata version：2.3.0
ctr run --rm  --runtime io.containerd.run.kata.v2 --mount type=ext4,src=/dev/loop0,dst=/loopdisk -t image name cmd

I get error report from guest kernel: 
blk_update_request: I/O error, dev loop0, sector 2 op 0x0:(READ) flags 0x1000 phys_seg 1 prio class 0"
EXT4-fs (loop0): unable to read superblock

--device /dev/loop0 works and guest kernel auto mount /dev/loop0 as /dev/sda.
Is auto mounting result in --mount option failed ?

**Comment by liubin** [comment]
Can you give us some logs with [debug enabled](https://github.com/kata-containers/kata-containers/blob/bee7915932c25665353b2a3f35315bd915be5146/docs/Developer-Guide.md#enable-full-debug)? @wenzt

**Comment by wenzt** [comment]
@liubin Thank you for response.
Many logs, don't know which part you need.
Some guest kenel messages here.

time="2022-08-25T15:19:58.446480979+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.469506] Key type dns_resolver registered"
time="2022-08-25T15:19:58.446604304+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.469627] NET: Registered protocol family 40"
time="2022-08-25T15:19:58.448228667+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.471208] IPI shorthand broadcast: enabled"
time="2022-08-25T15:19:58.448362471+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.471335] sched_clock: Marking stable (468834051, 1531731)->(481992641, -11626859)"
time="2022-08-25T15:19:58.448492624+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.471526] registered taskstats version 1"
time="2022-08-25T15:19:58.449090873+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.472047] EXT4-fs (pmem0p1): DAX enabled. Warning: EXPERIMENTAL, use at your own risk"
time="2022-08-25T15:19:58.449114816+08:00" level=debug msg="event forwarded" ns=default topic=/tasks/exit type=containerd.events.TaskExit
time="2022-08-25T15:19:58.449867795+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.472805] EXT4-fs (pmem0p1): mounted filesystem with ordered data mode. Opts: dax,data=ordered,errors=remount-ro"
time="2022-08-25T15:19:58.449988747+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.472974] VFS: Mounted root (ext4 filesystem) readonly on device 259:1."
time="2022-08-25T15:19:58.450286270+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.473315] devtmpfs: mounted"
time="2022-08-25T15:19:58.451313040+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.474283] Freeing unused kernel image (initmem) memory: 1344K"
time="2022-08-25T15:19:58.452409614+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.475380] Write protecting the kernel read-only data: 18432k"
time="2022-08-25T15:19:58.454251673+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.477224] Freeing unused kernel image (text/rodata gap) memory: 2036K"
time="2022-08-25T15:19:58.454991427+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.477965] Freeing unused kernel image (rodata/data gap) memory: 716K"
time="2022-08-25T15:19:58.455062341+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.478092] Run /sbin/init as init process"
time="2022-08-25T15:19:58.455105285+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.478147]   with arguments:"
time="2022-08-25T15:19:58.455154906+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.478199]     /sbin/init"
time="2022-08-25T15:19:58.455211010+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.478229]   with environment:"
time="2022-08-25T15:19:58.455256441+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.478282]     HOME=/"
v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.628872] systemd[89]: Executing: /usr/bin/kata-agent"
time="2022-08-25T15:19:58.605972126+08:00" level=debug msg="event forwarded" ns=default topic=/tasks/exec-added type=containerd.events.TaskExecAdded
time="2022-08-25T15:19:58.612960097+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.635853] systemd[90]: Failed to set up namespace, assuming containerized execution, ignoring: Operation not permitted"
time="2022-08-25T15:19:58.613109801+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.636114] systemd[90]: Executing: /usr/sbin/chronyd"
time="2022-08-25T15:19:58.622036436+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.644931] systemd[95]: Failed to set up namespace, assuming containerized execution, ignoring: Operation not permitted"
time="2022-08-25T15:19:58.625393453+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.645192] systemd[95]: Executing: /usr/libexec/chrony-helper update-daemon"
time="2022-08-25T15:19:58.663728119+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.685763] blk_update_request: I/O error, dev loop0, sector 2 op 0x0:(READ) flags 0x1000 phys_seg 1 prio class 0"
time="2022-08-25T15:19:58.663770411+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="[    0.685883] EXT4-fs (loop0): unable to read superblock"
time="2022-08-25T15:19:58.663897306+08:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = EIO: I/O error" name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=kata_agent
time="2022-08-25T15:19:58.664372723+08:00" level=error msg="container create failed" error="rpc error: code = Internal desc = EIO: I/O error" name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=container
time="2022-08-25T15:19:58.664458057+08:00" level=warning error="no such file or directory" name=containerd-shim-v2 pid=38906 rootfs-dir=/run/kata-containers/shared/sandboxes/test/mounts/test/rootfs sandbox=test source=virtcontainers subsystem=mount
time="2022-08-25T15:19:58.664507057+08:00" level=info msg="Stopping sandbox in the VM" name=containerd-shim-v2 pid=38906 sandbox=test source=virtcontainers subsystem=sandbox

**Comment by liubin** [comment]
@wenzt Kata will not mount a loop device or block device as a file system into a container, that is , you must mount the device on the host into the container, and mount the device to a local directory in the container:

```bash
# dd if=/dev/zero of=loopbackfile.img bs=10M count=10
# losetup -fP loopbackfile.img
# mkfs.ext4 loopbackfile.img 

# ctr run --privileged -t --rm --runtime io.containerd.kata.v2 \
  --mount type=bind,src=/dev/loop26,dst=/loopdisk,options=bind \
  docker.io/containerstack/alpine-stress:latest c1 sh
/ # ls /loopdisk 
/loopdisk
/ # mkdir loopfs
/ # mount /loopdisk loopfs/
/ # ls loopfs/
abc         lost+found
```

And pay attention to the mount parameter: `type=bind,src=/dev/loop26,dst=/loopdisk,options=bind`.

**Comment by liubin** [comment]
Reopen it, it has been closed by #5011.

**Comment by wenzt** [comment]
@liubin Thanks!
I notice this because I want to use loop device on kata to get better IO performencs.
Using bind options means loop device IO needs go through virtiofsd ? That means a lot of IO speed lose right?
I also noticed  **direct-blk-device-assignment** and **k8s raw block volume**.

**Comment by liubin** [comment]
@wenzt Block devices are devices in QEMU, and not shared by virtiofsd.

In k8s case, kubelet will handle all storage and expose them as mounted directories to container runtime, that is a few different from `ctr` which directly communicate with containerd.

`direct-blk-device-assignment` is just a way to delay the mount from the host side into guest.

For better performance, you should choose `direct-blk-device-assignment` if you are using k8s.

**Comment by wenzt** [comment]
@liubin Thank you again.
When I mount a loop device into container by **ctr**, kata will hotplug it into VM then bind mount to dst path by kata agent.
