### ISSUE TITLE
metrics: unix socket path too long in some system

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#497]
This log is from http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-fedora-PR/108/

```
Aug 11 03:41:24 fedoradocker32-1dc8f0 kata[99783]: time="2020-08-11T03:41:24.201707358Z" level=error msg="failed to create listener" error="\"/containerd-shim/default/e1bb5027099f5844e1054ba3d69e531052b308acb0a617398570e99a50c9c683/shim-monitor.sock\": unix socket path too long (> 106)" source=containerd-kata-shim-v2 subsystem=shim-management
```

**Comment by jodh-intel** [comment]
Hi @liubin - this sounds like a real bug. The error is coming from [`BuildSocketPath()`](https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/utils/utils.go#L220). We could reduce the length of the socket name (how about `shim-monitor.sock` (17 bytes) -> `ksmon` (5 bytes, short for "Kata shim monitor") maybe?)

**Comment by liubin** [comment]
```
$ sudo cat  /run/containerd/io.containerd.runtime.v2.task/k8s.io/d8b8fbc71b850f9c14d6b560207a811fb61d71fb3b7a3ec49b1bbc48ee4b6119/address
/containerd-shim/k8s.io/d8b8fbc71b850f9c14d6b560207a811fb61d71fb3b7a3ec49b1bbc48ee4b6119/shim.sock

$ sudo cat  /run/containerd/io.containerd.runtime.v2.task/k8s.io/d8b8fbc71b850f9c14d6b560207a811fb61d71fb3b7a3ec49b1bbc48ee4b6119/monitor_address
/containerd-shim/k8s.io/d8b8fbc71b850f9c14d6b560207a811fb61d71fb3b7a3ec49b1bbc48ee4b6119/shim-monitor.sock

```

Both shim v2 address and monitor address are using the same format of sock path:

`filepath.Join(string(filepath.Separator), "containerd-shim", ns, id, "shim-monitor.sock")`

So if user are using a long namespace, runtime may not work also.

But for now, make sure all other `vsock` address file name' length smaller than `shim.sock` (8 bytes) is OK.

@jodh-intel  So, my question is should we keep the `.sock` extension or not ?

**Comment by jodh-intel** [comment]
@liubin - I don't think we need the file extension at all, but what do other's think?

/cc @amshinde, @devimc, @bergwolf, @gnawux

**Comment by liubin** [comment]
After some test, my proposal is to remove the `namespace` from socket address. 

In containerd the namespace is fixed as [`k8s.io`](https://github.com/containerd/containerd/blob/822ce4e56e17f03413e2b5fef3fa364c65985671/pkg/cri/constants/constants.go#L23) .
Don't know about CRI-O, but without the `namespace` the address should not conflict .

**Comment by lcaw** [comment]
FYI, it looks this is going to affect to setup a agent debug console on cri-o.

time="2021-03-02T08:10:00.925960853-05:00" level=error msg="failed to create listener" error="\"/containerd-shim/default/0dd03ef3aeba6295254b2eba34727eedccdb56b59d76d736ea73d9ca53be6741/shim-monitor.sock\": unix socket path too long (> 106)" source=containerd-kata-shim-v2 subsystem=shim-management

**Comment by fidencio** [comment]
The namespace may work, as the container id is unique.
Anyhow, I'm not comfortable with the socket being created at `/containerd-shim/...`.

Let me submit a quick patch ...

**Comment by egernst** [comment]
Isn't the socket path a parameter that is passed to the shim?

**Comment by egernst** [comment]
I'm okay with shortening the name, though I'd like to limit the number of unique places we are leaving things on the filesystem. If we want it to reside at a location separate from the shim's socket, I'd like it to be at /run/vc or /run/kata-containers

**Comment by egernst** [comment]
How they resolve to limit length in containerd case: https://github.com/containerd/containerd/pull/3046

**Comment by egernst** [comment]
> After some test, my proposal is to remove the `namespace` from socket address.
> 
> In containerd the namespace is fixed as [`k8s.io`](https://github.com/containerd/containerd/blob/822ce4e56e17f03413e2b5fef3fa364c65985671/pkg/cri/constants/constants.go#L23) .

AFAIU namespace should be able to be non-k8s.io still. From reading the commit above, I'm wondering if we have an assumption on the shim-socket address (ie, it'll be where we assume... unless they do the sha256 trick to shorten?).
