### ISSUE TITLE
portainer cannot manage docker after using kata container

### ISSUE THREAD

**Issue by AC-WhiteGlint** [kata-containers/kata-containers#501]
Hi all,

After using configuring docker to use kata runtime.

Portainer is unable to connect to the docker.socket (which I understand why).

But now I can not even use the docker API on port 2375 (I am unable to expose when kata runtime is used)

Is there a way to allow Portainer to manage the docker host?

**Comment by devimc** [comment]
could you add more details?  afaik kata doesn't work with swarm, are you deplaying with swarm ?

**Comment by AC-WhiteGlint** [comment]
> could you add more details? afaik kata doesn't work with swarm, are you deploying with swarm ?

I will use portainer to manager around 2 to 3 nodes of docker server but no swarm.

SO for I am unable to find a way for portainer to connect the the docker API on port 2375, as I cannot enable this port, it seems that kata runtime prevent it from being enabled.

**Comment by devimc** [comment]
> SO for I am unable to find a way for portainer to connect the the docker API on port 2375, as I cannot enable this port, it seems that kata runtime prevent it from being enabled.

Sorry I still don't understand why kata runtime would be blocking the port 2375, is docker running inside a kata container (DinK)? 
could you enable [full debug](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug), try again and run `sudo kata-collect-data.sh` ?

**Comment by jodh-intel** [comment]
Hi @AC-WhiteGlint - as @devimc says, please provide more details - what commands you are running, what errors you get, an example showing a working environment without Kata, etc.

**Comment by fidencio** [comment]
This issue is quite old, and it comes from the time where we still supported CLI (not the case for some already).
As CLI support has been dropped for some time, let me close this issue.

@AC-WhiteGlint, please, feel free to re-open it in case we end up bringing back the CLI support.
