### ISSUE TITLE
ARM CI seems to have a stale cni0

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#505]
Since [Build #130](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/130) up to the most recent [Build #133](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/133), builds on kata-containers-2.0-ubuntu-ARM-PR fail, all with `failed to set bridge addr: "cni0" already has an IP address different from 10.88.0.1/16`.
Since they're from different PRs, I'm assuming it doesn't have something to do with the changes, but is instead due to a stale cni0.

/cc @jongwu

**Comment by jongwu** [comment]
Thanks @Jakob-Naucke , I noticed that and remove the cni0, but another error occurs. For now I have no privilege to trigger ARM ci to do some tests, so @jodh-intel @chavafg , can you add me to privileged user of ARM jenkins ci?

**Comment by chavafg** [comment]
@jongwu sure, sent you github invitation to join the jenkins team.

**Comment by jongwu** [comment]
hi @Jakob-Naucke ARM ci has passed.

**Comment by Jakob-Naucke** [comment]
Thanks @jongwu !
