### ISSUE TITLE
how to monitor the cloud-hypervisor vm by the kata-monitor?

### ISSUE THREAD

**Issue by FishyFine** [kata-containers/kata-containers#5067]
hi.i found the kata-monitor in the new version. Can i monitor the cloud-hypervisor vm by the kata-monitor? If i can, which step i need to do?such as the arg of kata-monitor ,some config, and some dependent?

**Comment by liubin** [comment]
hi @FishyFine, kata-monitor is Prometheus compatible, so you can use Prometheus to collect the metrics through kata-monitor.

Here is an example of [setting up Prometheus and Grafana in Kubernetes](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-prometheus-in-k8s.md)

By default running kata-monitor will work, it will listen on `127.0.0.1:8090`, and then `curl localhost:8090`  will give you a hint on what to do next.
