### ISSUE TITLE
Update osbuilder to allow rust agent build

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#51]
osbuilder needs to be able to build a rust-based agent.

**Comment by marcov** [comment]
Hi @jodh-intel, are you looking for volunteers for any of these rust-agent related tasks?

**Comment by jodh-intel** [comment]
Hi @marcov - always! ;)

@lifupan - I assume you aren't already working on any of the new issues I've just raised for https://github.com/kata-containers/kata-containers/projects/1?add_cards_query=is%3Aopen ?

**Comment by lifupan** [comment]
Hi @jodh-intel , yes, I'm on vacation this week and I'll have a look once I'm back next week.

**Comment by yyyeerbo** [comment]
rust agent cannot build on centos 7, cmake is 2.8.12. protobuf requires cmake > 3.1.3.

**Comment by yyyeerbo** [comment]
osbuild works on centos and fedora for now :)

**Comment by chavafg** [comment]
osbuilder already has support for the rust agent, closing this one.
