### ISSUE TITLE
stable-2.5: what is min config value of the default_vcpus under the hypervisor.qemu for production env

### ISSUE THREAD

**Issue by YchauWang** [kata-containers/kata-containers#5131]
I check the [vcpu-handling.md](https://github.com/kata-containers/kata-containers/blob/stable-2.5/docs/design/vcpu-handling.md) docs, the `default_vcpus` is setting to 1 for fast boot time. Can I set it to 500m of one CPU? And Who can provider the boot time test data affected by the `default_vcpus`?

**Comment by fengwang666** [comment]
It has to be an integer. AFAIK, hypervisor doesn't accept a fractional CPU as the input.

**Comment by YchauWang** [comment]
> It has to be an integer. AFAIK, hypervisor doesn't accept a fractional CPU as the input.

Thanks, @fengwang666. I think this issue can be closed now.
