### ISSUE TITLE
Codecov did not report tests for kata-containers/kata-containers

### ISSUE THREAD

**Issue by cmaf** [kata-containers/kata-containers#514]
Part of fix for [kata-containers/tests issue #2781](https://github.com/kata-containers/tests/issues/2781)
and [kata-containers/tests issue #2779 ](https://github.com/kata-containers/tests/issues/2779)

Codecov is not running tests for newly created kata-containers/kata-containers repo. It requires several fixes, one of which was [adding codecov execution script back into jenkins_job_build.sh in 2.0-dev branch](https://github.com/kata-containers/tests/pull/2780), [additional changes that were missed in the first PR](https://github.com/kata-containers/tests/pull/2782), and adding the test target to the appropriate Makefile in kata-containers/kata-containers, which will hopefully fix the issue. 

(@chavafg, maybe @jodh-intel)

**Comment by jodh-intel** [comment]
Hi @cmaf - yes. We'll also need to make some changes to enable code coverage stats for the rust agent in `src/agent`.

**Comment by fidencio** [comment]
@cmaf, while going through the opened 2.x issues that have the "needs-review" label, I ended up facing this one.
I'm removing the "need-review" label of the issue.

As far as I understand this is still desirable, but yet not finished, right?

**Comment by egernst** [comment]
I'm curious -- it'd be nice to have equivalent to these available: https://app.codecov.io/gh/kata-containers/agent

**Comment by cmaf** [comment]
Closing since we disabled codecov for now, see  https://github.com/kata-containers/tests/pull/3437
