### ISSUE TITLE
When I create pod with hotplug cpu, the container can't full use the cpu resource

### ISSUE THREAD

**Issue by Gezx** [kata-containers/kata-containers#5152]
Here is the yaml of the pod
```apiVersion: v1
kind: Pod
metadata:
  name: test-cpu-1
  annotations:
spec:
  nodeName: node7
  runtimeClassName: kata
  containers:
  - image: myregistry.com/library/centos
    name : test-cpu-1
    command:
    - sleep
    - "123600"
    resources:
      requests:
        cpu: "2"
        memory: "2G"
      limits:
        cpu: "2"
        memory: "2G"
```
The default_vcpus is 1, so we have 3C in the container and the limit cpu resource is 2. So I run the next task.
test.py
```import threading
def fun():
        k = 0
        for i in range(1, 100000000):
                for j in range(1, 100000000):
                        k = k + i * j
t1 = threading.Thread(target=fun)
t2 = threading.Thread(target=fun)
t1.start()
t2.start()
```
test.sh
```#!/bin/bash
for i in `seq 1 5`;do
        python3 test.py &
done
```
the workload of the cpu in the host as follows:
```  
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
22245 root      20   0 3140920 321360  46140 R 99.9  2.0   5:31.47 qemu-system-x86
22282 root      20   0 3140920 321360  46140 S  2.3  2.0   0:08.71 qemu-system-x86
22239 root      20   0 3140920 321360  46140 S  1.3  2.0   0:50.48 qemu-system-x86
22281 root      20   0 3140920 321360  46140 S  0.7  2.0   0:09.72 qemu-system-x86
27112 root      20   0 3140920 321360  46140 S  0.3  2.0   0:01.92 qemu-system-x86
27114 root      20   0 3140920 321360  46140 S  0.3  2.0   0:01.90 qemu-system-x86
22240 root      20   0 3140920 321360  46140 S  0.0  2.0   0:00.02 qemu-system-x86
22244 root      20   0 3140920 321360  46140 S  0.0  2.0   0:00.19 qemu-system-x86
22253 root      20   0 3140920 321360  46140 S  0.0  2.0   0:07.12 qemu-system-x86
22279 root      20   0 3140920 321360  46140 S  0.0  2.0   0:07.03 qemu-system-x86
27113 root      20   0 3140920 321360  46140 S  0.0  2.0   0:01.91 qemu-system-x86
```
It can be seen only one core is full load, why not two cores. I can't find the reason, Look forward to your reply.

**Comment by YchauWang** [comment]
hi @Gezx, I have the same question. The resources limits of the Pod added using range to the resources cgroups. So your kata container only use the 2 vcpu and 2G memory.

**Comment by Gezx** [comment]
> hi @Gezx, I have the same question. The resources limits of the Pod added using range to the resources cgroups. So your kata container only use the 2 vcpu and 2G memory.

You can see the source code, the numbers of vcpus is the default_vcpus + request cpus when you use resources limits. So you see 3 vcpus.
My question is another, I have solve it. It is my mistake that one node of k8s has this condition, it is solved when I schedule the pod another node.

**Comment by liubin** [comment]
@YchauWang is your question https://github.com/kata-containers/kata-containers/issues/5131?

**Comment by YchauWang** [comment]
> > hi @Gezx, I have the same question. The resources limits of the Pod added using range to the resources cgroups. So your kata container only use the 2 vcpu and 2G memory.
> 
> You can see the source code, the numbers of vcpus is the default_vcpus + request cpus when you use resources limits. So you see 3 vcpus. My question is another, I have solve it. It is my mistake that one node of k8s has this condition, it is solved when I schedule the pod another node.

Yes, @Gezx, you are right. I misunderstand your question. And I think you want to like me, make the container resource limit equal the VM resources config.

**Comment by YchauWang** [comment]
> @YchauWang is your question #5131?
 
Not #5131, It just a requirement of our production. The issue #5131, I want know our kata vm mini config or optimal configuration.
