### ISSUE TITLE
Qemu: ARM QMP command failed: Invalid CPU socket-id: 4294967295 must be in range 0:63

### ISSUE THREAD

**Issue by YchauWang** [kata-containers/kata-containers#5228]
# Description of problem

On the ARM architecture server, I created a pod with 8 core vcpu resources limit, reported error as following:
```
Sep 22 11:43:05 localhost containerd[33760]: time="2022-09-22T11:43:05.147632847+08:00" level=error msg="StartContainer for \"0db8da1944c64002af65d1c74eac9217fe2aeb95a8b5da16f2082aafebd11d4\" failed" error="failed to create containerd task: failed to hot add vCPUs: only 0 vCPUs of 8 were added: unknown"
Sep 22 11:43:05 localhost kubelet[14508]: E0922 11:43:05.147879   14508 remote_runtime.go:251] StartContainer "0db8da1944c64002af65d1c74eac9217fe2aeb95a8b5da16f2082aafebd11d4" from runtime service failed: rpc error: code = Unknown desc = failed to create containerd task: failed to hot add vCPUs: only 0 vCPUs of 8 were added: unknown
Sep 22 11:43:05 localhost kubelet[14508]: E0922 11:43:05.148063   14508 kuberuntime_manager.go:829] container &Container{Name:nginx,Image:docker.io/library/nginx:latest,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{cpu: {{8 0} {<nil>} 8 DecimalSI},memory: {{536870912 0} {<nil>}  BinarySI},},Requests:ResourceList{cpu: {{8 0} {<nil>} 8 DecimalSI},memory: {{536870912 0} {<nil>}  BinarySI},},},VolumeMounts:[]VolumeMount{VolumeMount{Name:default-token-lz8ks,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod nginx-1_default(6dcf8063-55ac-4421-8f02-d6933f7896a5): RunContainerError: failed to create containerd task: failed to hot add vCPUs: only 0 vCPUs of 8 were added: unknown
Sep 22 11:43:05 localhost kubelet[14508]: E0922 11:43:05.148118   14508 pod_workers.go:191] Error syncing pod 6dcf8063-55ac-4421-8f02-d6933f7896a5 ("nginx-1_default(6dcf8063-55ac-4421-8f02-d6933f7896a5)"), skipping: failed to "StartContainer" for "nginx" with RunContainerError: "failed to create containerd task: failed to hot add vCPUs: only 0 vCPUs of 8 were added: unknown"
```
I debug the the action of qmp, error info:
`Sep 22 11:43:04 localhost kata[55228]: time="2022-09-22T11:43:04.593677064+08:00" level=error msg="QMP command failed: Invalid CPU socket-id: 4294967295 must be in range 0:63" name=containerd-shim-v2 pid=55228 sandbox=77664176eaf860425a5bba3d7768a41d01a929f14bb45b75afd33028c45bab54 source=virtcontainers/hypervisor subsystem=qemu`

# Expected result

The pod with 8vcpu is created an working ok.

# Actual result

But get pod status `CrashLoopBackOff`

**Comment by YchauWang** [comment]
I find the [commit ](https://github.com/kata-containers/kata-containers/commit/42771fa7266f90a75d0516fab7b20f0e0b26b656) update file [qemu.go](src/runtime/virtcontainers/qemu.go)
```
		// If CPU type is IBM pSeries, Z or arm virt, we do not set socketID and threadID
		if machine.Type == "pseries" || machine.Type == QemuCCWVirtio || machine.Type == "virt" {
			socketID = ""
			threadID = ""
			dieID = ""
		}
```
the `socketID` is empty string, the qemu would generate a invalid socket-id.

**Comment by jongwu** [comment]
Hello, how do you create kata pod with 8 cpus? For now, the main line code doesn't support cpu hotplug on Arm. You can try this use the experimental kernel and qemu for Arm.

**Comment by YchauWang** [comment]
> Hello, how do you create kata pod with 8 cpus? For now, the main line code doesn't support cpu hotplug on Arm. You can try this use the experimental kernel and qemu for Arm.

We added to the patches for the qemu hotplug cpus. I am not sure I can push these patches to our kata-containers community.

**Comment by jongwu** [comment]
@YchauWang -, there is experimental patch set to support both kernel and qemu for cpu hotplug in kata for now. And the official cpu hotplug support is on the way. I'm waiting for that.

**Comment by YchauWang** [comment]
Me too. And close this issue.
