### ISSUE TITLE
Implement MVP Cloud Hypervisor runtime-rs hypervisor plugin

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#5242]
Implement a basic `runtime-rs` hypervisor plugin for Cloud Hypervisor (CH).

First steps:

- [x] Implement the `ConfigPlugin` trait for CH.
- [x] Implement the `Hypervisor` trait for CH.
  - [x] Implement the `Hypervisor::prepare_vm()` API.
  - [x] Implement the `Hypervisor::stop_vm()` API.
  - [x] Implement remaining lifecycle APIs.

Related: #4634, #5206, #6263.

**Comment by studychao** [comment]
Thanks, james:)
