### ISSUE TITLE
dragonball: runtime-rs build fail on Arm

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#5287]
the error report when build runtime-rs on Arm:

> 12:01:00 error[E0599]: no method named `as_str` found for reference `&Cmdline` in the current scope
12:01:01    --> /home/jenkins/workspace/kata-containers-2.0-ubuntu20.04-ARM-unit/go/src/github.com/kata-containers/kata-containers/src/dragonball/src/vm/aarch64.rs:139:21
12:01:01     |
12:01:01 139 |             cmdline.as_str(),
12:01:01     |                     ^^^^^^ help: there is an associated function with a similar name: `as_cstring`

**Comment by studychao** [comment]
Thanks!!
