### ISSUE TITLE
CC SEV: Allow empty keysets

### ISSUE THREAD

**Issue by fitzthum** [kata-containers/kata-containers#5307]
Today using SEV with CC requires you to use a KBS even if you are using an unencrypted container. The only way to skip connecting to the KBS is to turn of `guest_pre_attestation`, but this will remove the `kernel_hashes_enabled` argument from the QEMU command line so you will have to switch firmware from the AmdSev package to the standard Ovmf package. This is not ideal. 

Instead, we should update the shim to skip connecting to the KBS if the keyset is empty. We might also want to require the GUID to be empty. This might make more sense when we switch to the online KBC.

CC: @ryansavino

**Comment by jimcadden** [comment]
We may want to add `enable_guest_attestation_keybroker = true` to the config instead of implicitly relying on empty fields

**Comment by jimcadden** [comment]
@fitzthum Within the code, `guest_pre_attestation = {true, false}` is the correctly scoped gateway for enabling/disabling the full attestation pathways, it doesn't feel right to include the keyset or GUID in this condition.  On the other hand, the `kernel_hashes_enabled` argument is added based on whether or not `config.LaunchId > 0`, which feels a bit kludgy. Is it possible that we set `kernel_hashes={on,off}` for all SEV deployments (e.g. `=on` with `guest_pre_attestation =  true` and otherwise `=off`)??

**Comment by dubek** [comment]
I think it makes sense to use QEMU's `kernel_hashes=on` (and AmdSev OVMF package) for all SEV kata guests, even if we don't inject secrets (that is, don't connect to KBS).

IMO the term `guest_pre_attestation` means that someone is verifying the attestation/measurement. It is a bit weird to say `guest_pre_attestsion = on` but not connect to KBS. I'd call that mode something like `guest_memory_encryption = on`.

I guess we can choose something simple to implement now; but maybe we need to take a step back on all the CC-related config items (for all the different TEE vendors) and come up with something less confusing (if possible).

**Comment by jimcadden** [comment]
thanks @dubek 

> I think it makes sense to use QEMU's kernel_hashes=on (and AmdSev OVMF package) for all SEV kata guests, even if we don't inject secrets (that is, don't connect to KBS).

I agree, that seems the easiest. @fitzthum would that add any additional complications?  

> IMO the term guest_pre_attestation means that someone is verifying the attestation/measurement. It is a bit weird to say guest_pre_attestsion = on but not connect to KBS. I'd call that mode something like guest_memory_encryption = on.

Agreed. We could assume for SEV that `confidential_guest=on && guest_pre_attestation=off` results in a guest w/ memory encryption only.

**Comment by fitzthum** [comment]
Yeah sorry I missed this at first. I think I agree. We can just use `guest_pre_attestation` to determine whether or not you want to connect to the KBS. If you don't have any encrypted images, you can just turn pre-attestation off and not use a KBS. To make this work we will need to tweak things so that the kernel hashes remain enabled when pre-attestation is off (but confidential-guest is still enabled). This will mean that every SEV guest must use the AMDSEV fw pkg, but that seems fine since we provide it via the operator.
