### ISSUE TITLE
CC | Shall we consider tagging "a release" from the CC branch to be used with the confidential containers operator?

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#5330]
While I'm not big fond of having a tag set on a temporary branch, having such a thing would help us to automate the already scripted process to generate a payload image to be used with the confidential containers operator.

The current process is manual, as in, someone actually calling `make cc-payload`, and this could be part of a GitHub action (as already done for the `main` branch).

/cc @kata-containers/architecture-committee @stevenhorsman @wainersm @bpradipt

**Comment by wainersm** [comment]
Hi @fidencio 

> While I'm not big fond of having a tag set on a temporary branch, having such a thing would help us to automate the already scripted process to generate a payload image to be used with the confidential containers operator.
> 
> The current process is manual, as in, someone actually calling `make cc-payload`, and this could be part of a GitHub action (as already done for the `main` branch).
> 

I never ran `make cc-payload` and I don't understand the process completely. What I know it that the payload get the SHA1 of the repository on its name. Could you expand on how tagging would help?

When you say automate the process, are you thinking in when we release alpha, RC, GA of the payload or as in a CI (i.e. generate the payload as new code is merged in kata)? 

> /cc @kata-containers/architecture-committee @stevenhorsman @wainersm @bpradipt

**Comment by fidencio** [comment]
> I never ran `make cc-payload` and I don't understand the process completely. What I know it that the payload get the SHA1 of the repository on its name. Could you expand on how tagging would help?

Tagging would help on triggering a GitHub action that would generate the payload image.  We can use a tag, or simply have a new action to do so.  Tagging could be easier for folks to consume, but not necessarily needed.

> When you say automate the process, are you thinking in when we release alpha, RC, GA of the payload or as in a CI (i.e. generate the payload as new code is merged in kata)?

Right now nothing on `CCv0` is related to the `main` branch tags.  We'd have our own tags to trigger a GitHub action, to then generate the tarball (without the need of someone running `make cc-payload`) and uploading that to quay.io.

Does this make sense?  We're basically trying to remove the need of a human being running `make cc-payload`. :-)
