### ISSUE TITLE
kata-ctl: check: x86_64: Write kernel module checks

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#5332]
This needs to handle the scenario where the running kernel does not have the appropriate module loaded (so it will need to call `/sbin/modprobe`). See the golang code for further details.

See: #4499

**Comment by jodh-intel** [comment]
This task breaks down into the following sub-tasks for Intel hardware:

- [ ] Ensure `kvm` module loaded or available.
- [ ] Ensure `kvm_intel` module loaded or available.
    - [ ] Ensure `unrestricted_guest` option enabled.
    - [ ] Ensure `nested` option enabled.

**Comment by cmaf** [comment]
We are tentatively dividing this up with @dborquez taking the kvm/kvm_intel items and @cmaf taking the option items

/cc @amshinde @jodh-intel

**Comment by cmaf** [comment]
>     * [ ]  Ensure `kvm` module loaded or available.
> 
>     * [ ]  Ensure `kvm_intel` module loaded or available.
>       
>       * [ ]  Ensure `unrestricted_guest` option enabled.
>       * [ ]  Ensure `nested` option enabled.

As a note, https://github.com/kata-containers/kata-containers/pull/6295 encompasses all these items and can be reused for the vhost* module checks listed in https://github.com/kata-containers/kata-containers/issues/6132
