### ISSUE TITLE
kata-ctl: check: x86_64: Write KVM check

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#5338]
Implement the KVM check as done in the golang version.

See: https://github.com/kata-containers/kata-containers/issues/4499.

**Comment by jodh-intel** [comment]
This task involves  creating and destroying a KVM VM by reimplementing [`genericKvmIsUsable()`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cmd/kata-runtime/kata-check.go#L473) in rust and using either the `libc` or `nix` crates to get access to the `ioctl(2)` system call.

**Comment by cmaf** [comment]
thanks @jodh-intel!

**Comment by jodh-intel** [comment]
This depends on #5332.
