### ISSUE TITLE
kata-ctl: exec: Implement with tests

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#5340]
Implement the `kata-runtime exec` command with unit tests.

See: https://github.com/kata-containers/kata-containers/issues/4499.

**Comment by yipengyin** [comment]
Is anyone working on this feature? I would like to develop if no one is interested.

**Comment by studychao** [comment]
@amshinde @jodh-intel Hi guys, Is there anyone working on this issue? If not, @yipengyin would like to have a try

**Comment by yipengyin** [comment]
@studychao @jodh-intel @amshinde Shall I start coding. ; )

**Comment by amshinde** [comment]
@studychao I have started working on this already. There are a couple of tasks that no one is working on currently like https://github.com/kata-containers/kata-containers/issues/5343
Do you want to take a look at that?

**Comment by yipengyin** [comment]
> @studychao I have started working on this already. There are a couple of tasks that no one is working on currently like #5343 Do you want to take a look at that?

@amshinde That's great. I would use provisional solution for debug console. Looking forwarding to your PR!

**Comment by studychao** [comment]
Thanks !

**Comment by amshinde** [comment]
@studychao @yipengyin I have made some progress on this, but I may have to work on cloud-hypervisor work for the next few weeks, and may not be able to get back to this immediately. If this is something that you require urgently, I would suggest @yipengyin to take a look at this.

**Comment by yipengyin** [comment]
> @studychao @yipengyin I have made some progress on this, but I may have to work on cloud-hypervisor work for the next few weeks, and may not be able to get back to this immediately. If this is something that you require urgently, I would suggest @yipengyin to take a look at this.

@amshinde OK, I will implement this.

**Comment by Apokleos** [comment]
Hi @jodh-intel @studychao @amshinde @yipengyin, 

I have implement the feature `kata-ctl exec` days ago. So if possible, I would like to apply for the issue and patchset will also be posted right now.

Thx.
