### ISSUE TITLE
kata-ctl: check: Add "--only-list-releases" and "--include-all-releases" options

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#5345]
Implement the `--only-list-releases` and `--include-all-releases` options for the `kata-runtime check` command with unit tests.

**Note:** The current golang implementation contains a bug: the output should **not** display the vendor release files!

See: https://github.com/kata-containers/kata-containers/issues/4499.

**Comment by alexlee-23** [comment]
Hey James, I think I would like to try to work on this issue. Could you assign it to me? Thank you!

**Comment by jodh-intel** [comment]
Thanks @alexlee-23 ! Assigned ;) Any problems/questions, please ping one of us. @dborquez might be a good resource as he added the original network check which these options change.

**Comment by jodh-intel** [comment]
@alexlee-23 - I've added this issue to the BU project too.
