### ISSUE TITLE
runtime-rs: implement metrics handler for kata-ctl

### ISSUE THREAD

**Issue by Tim-0731-Hzt** [kata-containers/kata-containers#5368]
implement metrics handler with unit test for kata-ctl

**Comment by jodh-intel** [comment]
Duplicate of #5342, which I think @amshinde was going to look at, but feel free to collaborate with her! :smile:

**Comment by Tim-0731-Hzt** [comment]
same as #5370

**Comment by Ji-Xinyou** [comment]
For future assignees who are taking this one, this is already a promethus client implementation in Rust by tikv. You may check [prometheus](https://github.com/tikv/rust-prometheus) for detail.

**Comment by YushuoEdge** [comment]
Hi，this feature seems to be a duplicate of https://github.com/kata-containers/kata-containers/issues/5017, and @Yuan-Zhuo is working on that issue.

**Comment by Tim-0731-Hzt** [comment]
Thanks, then I will close it
