### ISSUE TITLE
runtime-rs: implement iptable handler for kata-ctl

### ISSUE THREAD

**Issue by Tim-0731-Hzt** [kata-containers/kata-containers#5370]
implement iptable handler (ipv4 and ipv6) with unit test for kata-ctl

**Comment by jodh-intel** [comment]
Hi @Tim-0731-Hzt - I've already created all the issues for `kata-ctl`. The iptables on is #5343.

**Comment by Tim-0731-Hzt** [comment]
Hi @jodh-intel, I don't think this is duplicate. This issue is for handling the request, which should be implemented here https://github.com/kata-containers/kata-containers/tree/main/src/runtime-rs/crates/runtimes/src/shim_mgmt . And @Ji-Xinyou already start working on this 
https://github.com/kata-containers/kata-containers/commit/1943476fc64c53fcb5874397c84c92101cc2378d#

I think the issue #5343 is to support kata-runtime command corresponding to 
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cmd/kata-runtime/kata-iptables.go

I think we need both #5343 and #537

**Comment by jodh-intel** [comment]
Ah - apologies @Tim-0731-Hzt ! In which case, please can you add these issues to the [`kata-ctl` project](https://github.com/orgs/kata-containers/projects/34) and add the `kata-ctl` label too?
