### ISSUE TITLE
Build-in Sandbox: Enhance Static-Check of CI to support nested virtualization. 

### ISSUE THREAD

**Issue by wllenyj** [kata-containers/kata-containers#5378]
Currently, Dragonball's Unit-Testing has not been added to the static checking. The pr #4961 added Dragonball components to Makefile. But [the Static checks / test](https://github.com/kata-containers/kata-containers/actions/runs/3107229536/jobs/5035089044) fail. The reason is, there is no /dev/kvm. 
So we should enhance Static-Check of CI to support nested virtualization. 

### Options
1. Use [self-hosted-runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) for `Static Check`.
   Pros: Change small, This scheme has been used in [Dragonball-sandbox](https://github.com/openanolis/dragonball-sandbox/blob/main/.github/workflows/test.yaml), and the same scheme and machine can be reused.

2. Move the Unit-Testing of the Dragonball to `jenkins-ci` from the `Github Actions`.
   Pros: More unified management of machines.

### Details for Option 1
1. We should add a New Runner in `kata-containers` repository. See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-a-repository
2. Download the runner application and install it on your self-hosted runner machine.
3. Modify your workflow file to use `self-hosted runners`. See https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow. 

### Details for Option 2
1. Remove the `test` in Makefile of Dragonball.
2. Add `cargo test` after `cargo build` for Dragonball in `kata-containers/tests` repo. (or some other location)

**Comment by wllenyj** [comment]
@bergwolf @jon @GabyCT Any suggestions? Thanks.

**Comment by bergwolf** [comment]
Looks like the self-hosted runner is pretty clean that it doesn't require any PAT to integrate with, am I understanding it correctly?

**Comment by wllenyj** [comment]
> Looks like the self-hosted runner is pretty clean that it doesn't require any PAT to integrate with, am I understanding it correctly?

I think so, it looks more clean.
