### ISSUE TITLE
Review documentation prior to 2.0 release

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#539]
TODO:

- [x] Update the [architecture document](https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/design/architecture.md)
- [x] Update the [Upgrading document](https://github.com/kata-containers/kata-containers/issues/928)

**Comment by bergwolf** [comment]
#831 is fixed. Should we close this one as well? @jodh-intel

**Comment by jodh-intel** [comment]
@bergwolf - I think we're almost done, but see https://github.com/kata-containers/kata-containers/issues/928.

**Comment by jodh-intel** [comment]
All done now.
