### ISSUE TITLE
Too similar functions

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#5394]
Functions [`doNetNS`](https://github.com/kata-containers/kata-containers/blob/9806ce86159e376f169f23e6dab696f825f0ddbe/src/runtime/virtcontainers/network_linux.go#L1018) and [`EnterNetNS `](https://github.com/kata-containers/kata-containers/blob/bc1733bb0ee4c6ca72dc9434314dd433507c93f6/src/runtime/pkg/katautils/network_linux.go#L29) are too similar and can be combined into one.

**Comment by Rouzip** [comment]
Hi, can I have a try in this issue?

**Comment by liubin** [comment]
Welcome @Rouzip

**Comment by Rouzip** [comment]
> Functions [`doNetNS`](https://github.com/kata-containers/kata-containers/blob/9806ce86159e376f169f23e6dab696f825f0ddbe/src/runtime/virtcontainers/network_linux.go#L1018) and [`EnterNetNS `](https://github.com/kata-containers/kata-containers/blob/bc1733bb0ee4c6ca72dc9434314dd433507c93f6/src/runtime/pkg/katautils/network_linux.go#L29) are too similar and can be combined into one.

After read the code, I found that `ns.NetNS` is useless where `doNetNS` is used. I plan to remove this function.

**Comment by liubin** [comment]
And also pay attention to the circle importing problem, katautils imports virtcontainers.

Reaming `doNetNS` to `DoNetNS` needs many replace, so I considered this patch at the beginning:

```diff
diff --git a/src/runtime/pkg/katautils/network_linux.go b/src/runtime/pkg/katautils/network_linux.go
index fd37c6605..6c8923f82 100644
--- a/src/runtime/pkg/katautils/network_linux.go
+++ b/src/runtime/pkg/katautils/network_linux.go
@@ -11,7 +11,6 @@ import (
        "fmt"
        "os"
        "path/filepath"
-       goruntime "runtime"
        "strings"
 
        "github.com/containernetworking/plugins/pkg/ns"
@@ -23,34 +22,11 @@ import (
 
 const procMountInfoFile = "/proc/self/mountinfo"
 
-// EnterNetNS is free from any call to a go routine, and it calls
-// into runtime.LockOSThread(), meaning it won't be executed in a
-// different thread than the one expected by the caller.
+// EnterNetNS will run cb in the specified namespace
 func EnterNetNS(networkID string, cb func() error) error {
-       if networkID == "" {
+       return vc.EnterNetNS(networkID, func() error {
                return cb()
-       }
-
-       goruntime.LockOSThread()
-       defer goruntime.UnlockOSThread()
-
-       currentNS, err := ns.GetCurrentNS()
-       if err != nil {
-               return err
-       }
-       defer currentNS.Close()
-
-       targetNS, err := ns.GetNS(networkID)
-       if err != nil {
-               return err
-       }
-
-       if err := targetNS.Set(); err != nil {
-               return err
-       }
-       defer currentNS.Set()
-
-       return cb()
+       })
 }
 
 // SetupNetworkNamespace create a network namespace
diff --git a/src/runtime/virtcontainers/network_linux.go b/src/runtime/virtcontainers/network_linux.go
index cd2157ece..4133f3ea7 100644
--- a/src/runtime/virtcontainers/network_linux.go
+++ b/src/runtime/virtcontainers/network_linux.go
@@ -1012,6 +1012,15 @@ func removeTCFiltering(ctx context.Context, endpoint Endpoint) error {
        return nil
 }
 
+// EnterNetNS is free from any call to a go routine, and it calls
+// into runtime.LockOSThread(), meaning it won't be executed in a
+// different thread than the one expected by the caller.
+func EnterNetNS(netNSPath string, cb func() error) error {
+       return doNetNS(netNSPath, func(_ ns.NetNS) error {
+               return cb()
+       })
+}
+
 // doNetNS is free from any call to a go routine, and it calls
 // into runtime.LockOSThread(), meaning it won't be executed in a
 // different thread than the one expected by the caller.

```

**Comment by Rouzip** [comment]
> And also pay attention to the circle importing problem, katautils imports virtcontainers.
> 
> Reaming `doNetNS` to `DoNetNS` needs many replace, so I considered this patch at the beginning:
> 
> ```diff
> diff --git a/src/runtime/pkg/katautils/network_linux.go b/src/runtime/pkg/katautils/network_linux.go
> index fd37c6605..6c8923f82 100644
> --- a/src/runtime/pkg/katautils/network_linux.go
> +++ b/src/runtime/pkg/katautils/network_linux.go
> @@ -11,7 +11,6 @@ import (
>         "fmt"
>         "os"
>         "path/filepath"
> -       goruntime "runtime"
>         "strings"
>  
>         "github.com/containernetworking/plugins/pkg/ns"
> @@ -23,34 +22,11 @@ import (
>  
>  const procMountInfoFile = "/proc/self/mountinfo"
>  
> -// EnterNetNS is free from any call to a go routine, and it calls
> -// into runtime.LockOSThread(), meaning it won't be executed in a
> -// different thread than the one expected by the caller.
> +// EnterNetNS will run cb in the specified namespace
>  func EnterNetNS(networkID string, cb func() error) error {
> -       if networkID == "" {
> +       return vc.EnterNetNS(networkID, func() error {
>                 return cb()
> -       }
> -
> -       goruntime.LockOSThread()
> -       defer goruntime.UnlockOSThread()
> -
> -       currentNS, err := ns.GetCurrentNS()
> -       if err != nil {
> -               return err
> -       }
> -       defer currentNS.Close()
> -
> -       targetNS, err := ns.GetNS(networkID)
> -       if err != nil {
> -               return err
> -       }
> -
> -       if err := targetNS.Set(); err != nil {
> -               return err
> -       }
> -       defer currentNS.Set()
> -
> -       return cb()
> +       })
>  }
>  
>  // SetupNetworkNamespace create a network namespace
> diff --git a/src/runtime/virtcontainers/network_linux.go b/src/runtime/virtcontainers/network_linux.go
> index cd2157ece..4133f3ea7 100644
> --- a/src/runtime/virtcontainers/network_linux.go
> +++ b/src/runtime/virtcontainers/network_linux.go
> @@ -1012,6 +1012,15 @@ func removeTCFiltering(ctx context.Context, endpoint Endpoint) error {
>         return nil
>  }
>  
> +// EnterNetNS is free from any call to a go routine, and it calls
> +// into runtime.LockOSThread(), meaning it won't be executed in a
> +// different thread than the one expected by the caller.
> +func EnterNetNS(netNSPath string, cb func() error) error {
> +       return doNetNS(netNSPath, func(_ ns.NetNS) error {
> +               return cb()
> +       })
> +}
> +
>  // doNetNS is free from any call to a go routine, and it calls
>  // into runtime.LockOSThread(), meaning it won't be executed in a
>  // different thread than the one expected by the caller.
> ```

Good idea!

**Comment by Rouzip** [comment]
Hi, Can you help review my PR? @liubin
