### ISSUE TITLE
CCv0：running demo get Invalid GPG signature 

### ISSUE THREAD

**Issue by Vanient** [kata-containers/kata-containers#5432]
I used GPG key and signatures provided in https://github.com/kata-containers/tests/tree/CCv0/integration/confidential/fixtures to pull quay.io/kata-containers/confidential-containers:signed in demo, but get following error:

FATA[0003] Source image rejected: Invalid GPG signature: gpgme.Signature{Summary:32, Fingerprint:"67B24AACC459679E0283D7EE58F6ED07EEA6B429", Status:gpgme.Error{err:0x7000099}, Timestamp:time.Time{wall:0x0, ext:63769719183, loc:(*time.Location)(0x5592e99f4c20)}, ExpTimestamp:time.Time{wall:0x0, ext:62135596800, loc:(*time.Location)(0x5592e99f4c20)}, WrongKeyUsage:false, PKATrust:0x0, ChainModel:false, Validity:0, ValidityReason:error(nil), PubkeyAlgo:1, HashAlgo:8} 

It looks like gpg key is invalid, is there any update for the key? Or is there anyone met this problem too?

Thanks

**Comment by stevenhorsman** [comment]
`CCv0` has been unmaintained for about a year, and RHSS support is currently dropped in `main. If you required this feature then please let us know in https://github.com/kata-containers/kata-containers/issues/8121. Thanks.
