### ISSUE TITLE
Apt-Key expired

### ISSUE THREAD

**Issue by lensti** [kata-containers/kata-containers#545]
# Description of problem
The Repository Key seems to be expired:
Following the Installation Guide on Ubuntu 20.04 (18.04):

`$ ARCH=$(arch)
$ BRANCH="${BRANCH:-master}"
$ sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
$ curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
$ sudo -E apt-get update
$ sudo -E apt-get -y install kata-runtime kata-proxy kata-shim`

# Expected result

working Kata-Containers

# Actual result

W: GPG error: http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG D0B37B826063F3ED home:katacontainers OBS Project <home:katacontainers@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_20.04  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

apt-key list | grep -A 1 expired:
pub   rsa2048 2018-03-13 [SC] [expired: 2020-08-20]

**Comment by mwhite-ibm** [comment]
We're seeing the same issue with:
* http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.10/xUbuntu_18.04/Release.key
* http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.11/xUbuntu_18.04/Release.key

**Comment by amshinde** [comment]
@rhafer Looks the apt keys for our Ubuntu packages in OBS have expired. Is this something you could help with?

**Comment by killuazhu** [comment]
Hello @amshinde @rhafer do we know when the release key will be fixed? We can keep installing the packages bypassing the signature verification, but it would be better if we can avoid doing so. Thanks

```shell
apt-get -o Acquire::AllowInsecureRepositories=true update && apt-get --allow-unauthenticated -y install kata-runtime kata-proxy kata-shim kata-ksm-throttler
```

**Comment by rhafer** [comment]
> Looks like the apt keys for our Ubuntu packages in OBS have expired. Is this something you could help with?

@amshinde Sorry I've been out of office for a while. I'll take a look.

> Hello @amshinde @rhafer do we know when the release key will be fixed? We can keep installing the packages bypassing the signature verification, but it would be better if we can avoid doing so. Thanks

AFAIKs the main key in `home:katacontainers` got already extented:

```
osc signkey home:katacontainers | gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048 2018-03-13 [SC] [expires: 2022-10-17]
      9FDC0CB63708CF803696E2DCD0B37B826063F3ED
uid           home:katacontainers OBS Project <home:katacontainers@build.opensuse.org>
```

See the updated expire date. As the subprojects ( `home:katacontainers:releases:x86_64` and friends) do not define their own keys. The above is what they are using as well. However, I guess that since `home:katacontainers:releases:x86_64:stable-1.10:xUbuntu_18.04`  (same for the `xUbuntu_16.04`) haven't build rebuild for a while they didn't pick up the change yet ...

I'll try to find out if there is a way to push the updated key to the subprojects.

**Comment by rhafer** [comment]
@amshinde Apparantly you have to trigger a rebuild of at least one package in the project to the the `Release.key` re-published. Should be possible with `osc rebuild <PROJECT> <PACKAGE>`

**Comment by rhafer** [comment]
https://github.com/openSUSE/open-build-service/issues/1949

**Comment by c3d** [comment]
This will change as we switch to vendor packaging. @fidencio, I think you have opened an issue for that. Could you reference it here? Thanks.

**Comment by paleozogt** [comment]
I'm still seeing this:
```
# sudo -E apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Get:3 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease [1621 B]
Err:3 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease
  The following signatures were invalid: EXPKEYSIG D0B37B826063F3ED home:katacontainers OBS Project <home:katacontainers@build.opensuse.org>
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Reading package lists... Done
W: GPG error: http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease: The following signatures were invalid: EXPKEYSIG D0B37B826063F3ED home:katacontainers OBS Project <home:katacontainers@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Was the fix never propagated?

**Comment by fidencio** [comment]
> I'm still seeing this:
> 
> ```
> # sudo -E apt-get update
> Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
> Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
> Get:3 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease [1621 B]
> Err:3 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease
>   The following signatures were invalid: EXPKEYSIG D0B37B826063F3ED home:katacontainers OBS Project <home:katacontainers@build.opensuse.org>
> Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
> Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
> Reading package lists... Done
> W: GPG error: http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease: The following signatures were invalid: EXPKEYSIG D0B37B826063F3ED home:katacontainers OBS Project <home:katacontainers@build.opensuse.org>
> E: The repository 'http://download.opensuse.org/repositories/home:/katacontainers:/releases:/ppc64le:/master/xUbuntu_18.04  InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```
> 
> Was the fix never propagated?

Those repos are unmaintained nowadays and were only used for kata-containers 1.x.
I'd  strongly recommend folks to use https://quay.io/repository/kata-containers/kata-deploy?tab=info for deploying kata-containers 2.x on their clusters.

**Comment by paleozogt** [comment]
@fidencio I'm using kata's own documentation on installing on Ubuntu ([here](https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md)).  Is that out of date?

**Comment by fidencio** [comment]
> @fidencio I'm using kata's own documentation on installing on Ubuntu ([here](https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md)). Is that out of date?

Extremely.
Once we moved from kata-containers 1.x to 2.x we announced a deprecation plan, but we failed to properly announce that as pointed out by @PeterSurda here: https://github.com/kata-containers/kata-containers/issues/2470

There I replied https://github.com/kata-containers/kata-containers/issues/2470#issuecomment-902465690, which may be interesting for what you're facing.

Sorry about that, we need to do a better job on announcing those changes.

**Comment by paleozogt** [comment]
Given that docker support is removed in 2.x, I think there's going to be continued interest in 1.x.  The keys should at least work even if there won't be any code updates.

(As an aside, since Docker supposedly supports shimv2 I'm a bit confused on why it doesn't work...)

**Comment by fidencio** [comment]
> Given that docker support is removed in 2.x, I think there's going to be continued interest in 1.x. The keys should at least work even if there won't be any code updates.

I don't disagree, I just don't think we have enough capacity to debug & maintain a code base that has been deprecated.
 
> (As an aside, since Docker supposedly supports shimv2 I'm a bit confused on why it doesn't work...)

https://github.com/kata-containers/kata-containers/issues/722 may give you some input.  We dropped the OCI CLI compatibility.  You can still `ctr` or `nerdctl` in case you really need to use this outside of a Kubernetes cluster scope.

**Comment by fidencio** [comment]
I'm closing this one for now as it's mostly related to kata-1.x issues (which reached its EOL a few months ago).
