### ISSUE TITLE
CCv0: SEV: Add unit tests for launch digest calculation

### ISSUE THREAD

**Issue by dubek** [kata-containers/kata-containers#5456]
**Which feature do you think can be improved?**

SEV's launch digest calculation has no unit-tests. The interface to test is:

https://github.com/kata-containers/kata-containers/blob/f087380180853de14e873ae686868b0427512a92/src/runtime/pkg/sev/sev.go#L141-L143

**How can it be improved?**

Add unit tests, so we can add more functionality later (SEV-ES measurement calculation).

**Comment by stevenhorsman** [comment]
@dubek - Hey Dov, can this be closed now #5337 has merged? Thanks!

**Comment by dubek** [comment]
Yes. I thought the "Fixes:" tag line does this automatically. Closing.

**Comment by stevenhorsman** [comment]
> Yes. I thought the "Fixes:" tag line does this automatically. Closing.

Unfortunately that only works on the default branch, not `CCv0` :(
