### ISSUE TITLE
agent: Support local socket address

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#552]
The agent currently creates a ttRPC server that listens on a VSOCK socket. However, the ttRPC crate the agent uses also supports UNIX sockets, so add support for this with a `KATA_AGENT_SERVER_ADDR=...` env var.

This is very useful for testing, particularly in combination with the [`agent-ctl`](https://github.com/kata-containers/kata-containers/tree/2.0-dev/tools/agent-ctl) tool.

See: #549, #550.

**Comment by lining2020** [comment]
It‘s very useful ！
