### ISSUE TITLE
runtime-rs: feature gap between runtime-rs and go runtime

### ISSUE THREAD

**Issue by studychao** [kata-containers/kata-containers#5532]
This issue is for giving a whole picture for showing the feature gap between rust runtime and go runtime to let the community know our working process and give users information for choosing the runtime. still a work in process.

**Comment by stevenhorsman** [comment]
@studychao - are you happy to close this as superceded by https://github.com/kata-containers/kata-containers/issues/8702 now?

**Comment by studychao** [comment]
@stevenhorsman yep, I'll this one
