### ISSUE TITLE
runtime-rs: bind mount volumes in sandbox level

### ISSUE THREAD

**Issue by justxuewei** [kata-containers/kata-containers#5588]
Each container has an exclusive mountpoint for the same file on the host. For example, two containers want to use "/home/example/downloads" on the host. Assume that "aaaa" and "bbbb" are those container ids, respectively. The runtime will create two mountpoints on the host runtime directory:

- for "aaaa" container: /run/kata-containers/shared/sandboxes/$pod/rw/passthrough/aaaa-{uuid}-downloads.
- for "bbbb" container: /run/kata-containers/shared/sandboxes/$pod/rw/passthrough/bbbb-{uuid}-downloads.

In this way, the overall architecture looks like this:

<img src="https://user-images.githubusercontent.com/13026316/200104660-b994cefb-acc4-43e4-b801-20a800d7c850.png" width="600px" />

This architecture is straightforward and intuitive. However, one disadvantage is that those mountpoints have their cache, leading to inconsistent data issues when a container writes something into the "downloads". Another container reads something from the "downloads" at the same time. It may not see those modifications.

One possible solution is sharing the same directory in sandbox level. As shown in the below picture, we only create a shared mountpoint for the downloads directory. Thus, modifications are visible to all containers due to a unified cache.

<img src="https://user-images.githubusercontent.com/13026316/200104672-3c5e72b7-254d-4cad-aa32-c3bd5b4f22ba.png" width="600px" />

There is more work to be done on the sandbox side, such as umount the volumes to which no containers reference, etc.

**Comment by liubin** [comment]
This may give you some idea https://github.com/kata-containers/kata-containers/pull/1463

**Comment by justxuewei** [comment]
> This may give you some idea #1463

Thank you, I'll take a look at this.
