### ISSUE TITLE
CC: Agent endpoint config logic inconsistent

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#5590]
In the change we made to enable overwriting of the agent toml config with kernel params I think we/I introduced a defect:
If you have an agent config, but don’t specify endpoints then we don’t set all_allowed to true, so you end up with something like:
```
kata-agent[696]: {"msg":"announce","level":"INFO","ts":"2022-11-06T16:51:44.871119029Z","source":"agent","subsystem":"root","version":"0.1.0","pid":"696","name":"kata-agent","api-version":"0.0.1","config":"AgentConfig { debug_console: false, dev_mode: false, log_level: Info, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \"unix:///run/kata-containers/agent.sock\", unified_cgroup_hierarchy: false, tracing: false, endpoints: AgentEndpoints { allowed: {}, all_allowed: false }, supports_seccomp: true, container_policy_path: \"\", aa_kbc_params: \"\", https_proxy: \"\", no_proxy: \"\", data_integrity: false, enable_signature_verification: false }","agent-commit":"3.1.0-alpha0-656a3e06a7e406fa8105619c16d3568365fbac44","agent-version":"3.1.0-alpha0"}
```

Discussion on thoughts about this in https://github.com/kata-containers/kata-containers/issues/5590#issuecomment-1305492107

**Comment by fidencio** [comment]
I've been going back and forth with this.

We shouldn't even expose to users EndPoints they can disable that will make Kata Containers **not functional**.
If we allow users to disable those, we should honour such a configuration.

With that said, I sincerely think this is **not** a stop-ship for the `v0.2.0` release, but rather a discussion that we **must** have for `v0.3.0` release, together with action, so we can have a list of EndPoints we expose, with all the others being enabled by default.

**Comment by stevenhorsman** [comment]
As Fabiano has mentioned above we'd have a lot of discussions and changes of opinion this morning, so I'll try and summarise them as best as I can:
- With the current code, if a user creates agent-config.toml (which is admitted not very well documented, so fairly unlikely) then the code defaults to all endpoints being blocked. The reason I flagged this as a bug is:
  - We don’t do that if you just use the kernel_params and I don’t see a good reason why the presence of the agent-config.toml should result in a change of default
  - If you block all endpoints then the agent is useless, so I’m not sure that should be the default

I was planning on just updating the logic so that rather than the endspoint.all_allowed being keys off of the presence of the config file we based on on whether the `endpoints.allowed` was empty. This leads to the follow on question:
- Would we ever want to support a user blocking all end points? If so I’m struggling to think of a nice way (based on the current code) to distinguish between:
  - User deliberately blocked all endpoints in the agent-config.toml:
  ```
  [endpoints]
  allowed = []
  ```
  - User doesn’t add any endpoint info to the agent-config

If the first is a valid option then I’m a bit stuck. This setting would would block all agent endpoints and therefore disabled the kata-agent, so shouldn’t be default, but if a user tries to do it then us interpreting that as allow everything feels pretty bad.

The better solution solution we can see is the one that Fabiano outlines above: Remove the ability to disable endpoints that we have to have and then potentially default the others to be disabled. The immediate list of 'disable-able' endpoints based on historical use is:
- `ExecProcessRequest`
- `ReseedRandomDevRequest`
but we'd need more community participation to ensure this list is complete.

We might also need to decide how we handle this for 'vanilla' kata-containers to ensure compatibility as the endpoint logic  is in the `main` branch and I don't think they will want their endpoints blocked by default. Maybe the best approach, now we can override (most) settings (unfortunately not including the enabled endpoints) in the agent-config is that we package a default 'locked-down' `agent-config.toml`, which signature verification set on and all the 'optional' endpoints disabled in the CC version of rootfs and then the vanilla kata won't have to make changes based on it.

**Comment by fitzthum** [comment]
I don't think this is urgent. In fact I think it's done this way by design. See https://github.com/kata-containers/kata-containers/issues/1837#issuecomment-925826158, where @dcmiddle first suggested that the the agent-config file should have an allow-list. There was some more discussion about this somewhere but ultimately I guess we thought it was more secure. 

Lately I have been thinking that we should actually switch to a deny list. The agent-config isn't really user-facing, so I'm not sure that having a safer default is very useful. The risk is more that some new endpoint will be added to Kata and none of us will notice. With an allow-list this wouldn't have any security implications, but might break the project. A deny-list would be the other way around.

I'm not really sure what is optimal.

**Comment by stevenhorsman** [comment]
Cool - as long as we are happy we are okay for 0.2, then I think we can discuss this on a CC call and get some input from the wider community. Thanks!

**Comment by wainersm** [comment]
> As Fabiano has mentioned above we'd have a lot of discussions and changes of opinion this morning, so I'll try and summarise them as best as I can:
> 
>     * With the current code, if a user creates agent-config.toml (which is admitted not very well documented, so fairly unlikely) then the code defaults to all endpoints being blocked. The reason I flagged this as a bug is:
>       
>       * We don’t do that if you just use the kernel_params and I don’t see a good reason why the presence of the agent-config.toml should result in a change of default
>       * If you block all endpoints then the agent is useless, so I’m not sure that should be the default
> 
> 
> I was planning on just updating the logic so that rather than the endspoint.all_allowed being keys off of the presence of the config file we based on on whether the `endpoints.allowed` was empty. This leads to the follow on question:
> 
>     * Would we ever want to support a user blocking all end points? If so I’m struggling to think of a nice way (based on the current code) to distinguish between:
>       
>       * User deliberately blocked all endpoints in the agent-config.toml:
>       
>       ```
>       [endpoints]
>       allowed = []
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       
>       * User doesn’t add any endpoint info to the agent-config
> 
> 
> If the first is a valid option then I’m a bit stuck. This setting would would block all agent endpoints and therefore disabled the kata-agent, so shouldn’t be default, but if a user tries to do it then us interpreting that as allow everything feels pretty bad.
> 
> The better solution solution we can see is the one that Fabiano outlines above: Remove the ability to disable endpoints that we have to have and then potentially default the others to be disabled. The immediate list of 'disable-able' endpoints based on historical use is:
> 
>     * `ExecProcessRequest`
> 
>     * `ReseedRandomDevRequest`
>       but we'd need more community participation to ensure this list is complete.
> 
> 
> We might also need to decide how we handle this for 'vanilla' kata-containers to ensure compatibility as the endpoint logic is in the `main` branch and I don't think they will want their endpoints blocked by default. Maybe the best approach, now we can override (most) settings (unfortunately not including the enabled endpoints) in the agent-config is that we package a default 'locked-down' `agent-config.toml`, which signature verification set on and all the 'optional' endpoints disabled in the CC version of rootfs and then the vanilla kata won't have to make changes based on it.

Lamer question: why can't the signature verification property being passed via kata-configuration.toml only? Why it needs to be in the agent-config.toml?

**Comment by stevenhorsman** [comment]
> Lamer question: why can't the signature verification property being passed via kata-configuration.toml only? Why it needs to be in the agent-config.toml?

So I think we are mostly talking about the allowed endpoint property here, so signature verification. At the moment it is an array, and an allow-list, so if we could pass it through the kata-config.toml it would be very big. That being said I have suggested in the past (and maybe above) that we have a cut down version of endpoints that we should block for security reasons (though from what Tobin mentioned in the last CC meeting that might be fraught with peril) and default them off, allow them to be allow-listed in the agent-config,toml, but also supply an 'allow_all_endpoint=true` default in the kata-config for vanilla kata. Does that help at all @wainersm 

Alternatively if you are actually meaning signature verification. It can be in either the kata-config, the agent-config, or neither (default to be on for security reasons. It doesn't *need* to be in the agent-config.toml at all, but we need to be able to support that, partly if we want to embed some sensible defaults without cluttering the kata-config.toml, but also for situations, like peer pods, where the kata-agent runs standalone and doesn't get things feed into it via the hypervisor.

I hope that helps? If I missed the point, please let me know. Thanks!
