### ISSUE TITLE
CC: Build agent before cosign verification on s390x 

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#5599]
**Which feature do you think can be improved?**

Despite of an issue #5582, in order to keep the support for `s390x` without the cosign verification for a `CCv0`'s `v0.2.0` release, we need to make the `agent` build refer to `image-rs` differently. This is just a temporary remedy, which should be reverted when #5582 is resolved.

**Comment by stevenhorsman** [comment]
I think this workaround has been completed with #5600 merging.
