### ISSUE TITLE
Landing rust-agent in kata-containers org

### ISSUE THREAD

**Issue by gnawux** [kata-containers/kata-containers#56]
In the past months, we have open-sourced rust-agent ([alipay/kata-rust-agent](https://github.com/alipay/kata-rust-agent.git)). 

Thanks to all the contributors, especially for the inputs from @jodh-intel, it could work with other Kata components: The CI changes are on the way (kata-containers/tests#1966) and the os-builder related issues are mostly fixed.

I discussed with @egernst and we both think we may try to land it in Kata by this month, which means we could have it before the Summit in Nov. Therefore we should have the PR for landing it right now. However, we still need to decide the place to land it:

- A new repo called `rust-agent` or similar
  - **Pro**: easy to do.
  - **Cons**: one more repo, we want to consolidate our repos.
- Re-construct `agent` repo, and put both the Go and Rust agent in the repo
  - **Pro**: it's reasonable as they share the same protocol and same position in the architecture. In short, they are two variants of a same software.
  - **Cons**: needs work in `agent` repo, and we need further work on consolidating the repos after this move.
- Put into the `kata-containers/kata-containers` repo.
  - **Pro**: it will be the first step of consolidating the repos.
  - **Cons**: we need to figure out the repo structure firstly. However, we have not had any detailed conclusions on how to do the consolidation.

Folks here, we need your inputs here. And I suggest we discussed this in the next AC meeting.

@kata-containers/architecture-committee

**Comment by jodh-intel** [comment]
Thanks for raising this @gnawux.

I think we should put the new agent in `kata-containers/kata-containers` since:

- That repo already exists.
- Using it aligns with our plan to consolidate the other repos into `kata-containers/kata-containers` (meaning we won't need to move the existing agent into `kata-containers/kata-containers`, so less work overall).

We can add the other components into `kata-containers/kata-containers` over time.

I agree we need to think carefully about the structure of that repo to ensure it can accommodate both the other components, and code not written in rust.

+1 for discussing this topic at the next AC meeting.

**Comment by gnawux** [comment]
Thanks @jodh-intel 

Do you have a proposed position for rust-agent?

**Comment by jodh-intel** [comment]
Hi @gnawux,

I was thinking about something basic like the following (but more thought is probably required to handle common code, golang vendor requirements, *et cetera*):

```
.
├── components
│   ├── agent
│   ├── proxy
│   ├── runtime
│   └── shim
├── docs
├── packaging
├── tests
└── tools
    └── osbuilder
```

**Comment by yyyeerbo** [comment]
what's the layout of kata-containers/kata-containers? where to put rust agent? kata-containers/kata-contianers/rust-agent? kata-containers/kata-contianers/components/agent/rust? :)

**Comment by jodh-intel** [comment]
Aha! Just seen your comment @yyyeerbo. Yes, exactly what I asked on the PR ;)

We need some more opinions from others, but I like the idea of putting the components into a sub-directory so we can keep the top-level directory "clean" (a `Makefile`, a `README.md` and a few metadata files).
