### ISSUE TITLE
CC: kata-agent failed to unpack image with umoci

### ISSUE THREAD

**Issue by jxyang** [kata-containers/kata-containers#5602]
When using skopeo and umoci to download/unpack a container image, umoci complains that an existing config.json found in the target directory with the message:
```
 failed to unpack image: ExitStatus(unix_wait_status(256))
```

Note, this path is only activated when both `skopeo` and `umoci` are present in the guest image.

https://github.com/kata-containers/kata-containers/blob/38b5818813097f7e09de96798c4b319934ee9d49/src/agent/src/image_rpc.rs#L263

**Comment by jxyang** [comment]
The duplicate config.json was created by this line: https://github.com/kata-containers/kata-containers/blob/38b5818813097f7e09de96798c4b319934ee9d49/src/agent/src/rpc.rs#L276

**Comment by stevenhorsman** [comment]
umoci is no longer used for unpacking images on the agent, so this issue isn't valid any more
