### ISSUE TITLE
runtime-rs: support vhost-vsock

### ISSUE THREAD

**Issue by yipengyin** [kata-containers/kata-containers#5654]
We are integrating runtime-rs with another hypervisor which doesn't support hybrid-vsock. So we want to upstream our patch to support vhost-vsock. Although, I'm not sure whether dragonball support vhost-vsock or not.

**Comment by studychao** [comment]
Welcome! Which part of runtime-rs do you want to support vhost-vsock? Only the runtime-rs part or Dragonball part? 

Currently Dragonball doesn't upstream vhost-vsock now but may be supported in the future, so it might be hard for you to test under runtime-rs.

**Comment by studychao** [comment]
Also I think this feature will also be used for Cloud Hypervisor and QEMU, so it should be generic enough for those VMMs. 

Looking forward for your PR:)

**Comment by yipengyin** [comment]
Only runtime-rs part. We have our own vmm. And the patch has been tested in our vmm. I'm worried about the test in upstream.

**Comment by studychao** [comment]
> Only runtime-rs part. We have our own vmm. And the patch has been tested in our vmm. I'm worried about the test in upstream.

Got that. You could raise the PR and we could first start to review it.

@jodh-intel and @pmores are working on multi-VMM support and also Dragonball will start considering the upstream of vhost-vsock. So any one of us finish the work we could start test the end-to-end process.
