### ISSUE TITLE
runtime-rs: support direct volume

### ISSUE THREAD

**Issue by yipengyin** [kata-containers/kata-containers#5656]
kata 2.0 support direct volume https://github.com/kata-containers/kata-containers/blob/main/docs/design/direct-blk-device-assignment.md

And we are using it to extend volume backend.

**Comment by studychao** [comment]
Thanks. Do you need that feature or do you want to upstream your implementation?

**Comment by yipengyin** [comment]
I will upstream our implementation

**Comment by studychao** [comment]
> I will upstream our implementation

Got that, looking forward to it:)
If you need any help, please let me know.

**Comment by Apokleos** [comment]
Hi @yipengyin, I am working on the feature recently, and I have it done now. If it's OK, I can push my PR.
cc @studychao @lifupan 

Thx.
