### ISSUE TITLE
kata container /lib/modules is empty, how to create kernel module？

### ISSUE THREAD

**Issue by fu7100** [kata-containers/kata-containers#5666]
I don't know much about the linux kernel. Why is `/lib/modules` empty in the kata container? I need to execute `modprobe` to load the driver module. It prompts me that` it cannot be found`. What should I do?

**Comment by cheriL** [comment]
You may need to copy the module files to the rootfs and rebuild the guest img.

**Comment by amshinde** [comment]
Kata mostly uses built-in modules, that is why the directory if empty.  You can take a look here on how to load modules with Kata: 
https://github.com/kata-containers/documentation/blob/master/how-to/how-to-load-kernel-modules-with-kata.md

**Comment by Ji-Xinyou** [comment]
I will mark this as complete since @amshinde and @cheriL already gave the answers.
