### ISSUE TITLE
CC: Fix errors on building cc-builders images on s390x

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#5677]
# Description of problem

The following errors have been found during an e2e test `cc-kubernetes` on s390x to fix https://github.com/kata-containers/tests/issues/5256:

1. Dependency issue on `git` for `ubuntu:20.04`:

- Image `cc-builders:initramfs-cryptsetup`
- Log: http://jenkins.katacontainers.io/job/kata-containers-CCv0-tests-ubuntu-20.04-s390x-PR/167/consoleText

```
The following packages have unmet dependencies:
 git : Depends: git-man (< 1:2.37.3-.) but 1:2.38.1-0ppa1~ubuntu20.04.1 is to be installed
```

2. Reference to configuration files which do not exist for a flag `CI_JOB=CC_CRI_CONTAINERD_K8S_SE_QEMU`:

- Image `cc-builders:shim-v2`
- Log: http://jenkins.katacontainers.io/job/kata-containers-CCv0-tests-ubuntu-20.04-s390x-PR/168/consoleText

```
sed: can't read /home/jenkins/workspace/kata-containers-CCv0-tests-ubuntu-20.04-s390x-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build/build/cc-shim-v2/destdir//opt/confidential-containers/share/defaults/kata-containers/configuration-fc.toml: No such file or directory
```

# Expected result

The e2e test should start without any build error.

# How to cope with the situation

1. Make architecture-specific `Dockerfile` (e.g. `Dockerfile.s390x`, not touching a current [Dockerfile](https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/static-build/initramfs/Dockerfile)) and build `gen_init_cpio` from an linux source archive like:

```diff
diff --git a/tools/packaging/static-build/initramfs/Dockerfile b/tools/packaging/static-build/initramfs/Dockerfile
index 8d3396e76..280522aae 100644
--- a/tools/packaging/static-build/initramfs/Dockerfile
+++ b/tools/packaging/static-build/initramfs/Dockerfile
@@ -14,7 +14,6 @@ SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ENV TZ=UTC
 RUN apt-get update &&\
     apt-get --no-install-recommends install -y software-properties-common &&\
-    add-apt-repository ppa:git-core/ppa -y &&\
     apt-get update && apt-get upgrade -y && \
     apt-get --no-install-recommends install -y \
            apt-utils \
@@ -61,10 +60,11 @@ RUN apt-get update &&\
     strip /usr/sbin/veritysetup.static && \
     popd && \
     echo "Build gen_init_cpio tool" && \
-    git clone --depth 1 --filter=blob:none --sparse https://github.com/torvalds/linux.git && \
-    pushd linux && \
-    git sparse-checkout add usr && cd usr && make gen_init_cpio && \
-    install gen_init_cpio /usr/sbin/ && \
+    latest_linux_version=$(git ls-remote --tags --sort='v:refname' https://github.com/torvalds/linux.git | tail -1 | sed 's/.*\///; s/\^{}//; s/v//') && \
+    curl -LO https://git.kernel.org/torvalds/t/linux-${latest_linux_version}.tar.gz && \
+    tar xfz linux-${latest_linux_version}.tar.gz && \
+    pushd linux-${latest_linux_version}/usr && \
+    make gen_init_cpio && install gen_init_cpio /usr/sbin/ && \
     popd && \
     popd && \
     rm -rf ${build_root}

```

2. Rule out the file reference for `s390x` like:

```diff
diff --git a/tools/packaging/static-build/shim-v2/build.sh b/tools/packaging/static-build/shim-v2/build.sh
index 340daf6d8..b59073224 100755
--- a/tools/packaging/static-build/shim-v2/build.sh
+++ b/tools/packaging/static-build/shim-v2/build.sh
@@ -60,11 +60,13 @@ sudo docker run --rm -i -v "${repo_root_dir}:${repo_root_dir}" \
        bash -c "git config --global --add safe.directory ${repo_root_dir} && make PREFIX="${PREFIX}" DESTDIR="${DESTDIR}"  ${EXTRA_OPTS} install"
 
 sudo sed -i -e '/^initrd =/d' "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-qemu.toml"
-sudo sed -i -e '/^initrd =/d' "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-fc.toml"
+if [ ${arch} != "s390x" ]; then
+    sudo sed -i -e '/^initrd =/d' "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-fc.toml"
 
-for vmm in ${REMOVE_VMM_CONFIGS}; do
-       sudo rm "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-$vmm.toml"
-done
+    for vmm in ${REMOVE_VMM_CONFIGS}; do
+        sudo rm "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-$vmm.toml"
+    done
+fi
 
 pushd "${DESTDIR}/${PREFIX}/share/defaults/kata-containers"
        sudo ln -sf "configuration-qemu.toml" configuration.toml
```

I look forward to any feedback from @hbrueckner @stevenhorsman and @arronwy

**Comment by stevenhorsman** [comment]
I think the 
```
+    for vmm in ${REMOVE_VMM_CONFIGS}; do
+        sudo rm "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-$vmm.toml"
+    done
```
section should be outside of the arch if. IIRC that was just deleting unsupported CC hypervisors (acrn, fc) to make the image smaller, which is also valid for the s390x version?

**Comment by BbolroC** [comment]
> I think the
> 
> ```
> +    for vmm in ${REMOVE_VMM_CONFIGS}; do
> +        sudo rm "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-$vmm.toml"
> +    done
> ```
> 
> section should be outside of the arch if. IIRC that was just deleting unsupported CC hypervisors (acrn, fc) to make the image smaller, which is also valid for the s390x version?
> 
> Otherwise it looks good at first glance

Thanks for the feedback. Yes, I agree.  Then, why don't we just add `-f` option just in preparation of an error where there wouldn't be such files.

**Comment by hbrueckner** [comment]
> > I think the
> > ```
> > +    for vmm in ${REMOVE_VMM_CONFIGS}; do
> > +        sudo rm "${DESTDIR}/${PREFIX}/share/defaults/kata-containers/configuration-$vmm.toml"
> > +    done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > section should be outside of the arch if. IIRC that was just deleting unsupported CC hypervisors (acrn, fc) to make the image smaller, which is also valid for the s390x version?
> > Otherwise it looks good at first glance
> 
> Thanks for the feedback. Yes, I agree. Then, why don't we just add `-f` option just in preparation of an error where there wouldn't be such files.

I think `-f` would help. The alternative approach is to test whether the files exists, and then perform the `rm` and the `sed` (independent of the architecture check). So far (not checked tests repo), I have only seen `REMOVE_VMM_CONFIGS` specified in [install_cc_shimv2()](https://github.com/kata-containers/kata-containers/blob/4c26d8e16ad281ee4958a8f2d54725b56edb2963/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L164). And it looks like there are some implicit assumptions `x86`being different VMMs like qemu and firecracker etc. to be present?!

**Comment by hbrueckner** [comment]
>     1. Make architecture-specific `Dockerfile` (e.g. `Dockerfile.s390x`, not touching a current [Dockerfile](https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/static-build/initramfs/Dockerfile)) and build `gen_init_cpio` from an linux source archive like:
> 
> 
> ```diff
> diff --git a/tools/packaging/static-build/initramfs/Dockerfile b/tools/packaging/static-build/initramfs/Dockerfile
> index 8d3396e76..280522aae 100644
> --- a/tools/packaging/static-build/initramfs/Dockerfile
> +++ b/tools/packaging/static-build/initramfs/Dockerfile
> @@ -14,7 +14,6 @@ SHELL ["/bin/bash", "-o", "pipefail", "-c"]
>  ENV TZ=UTC
>  RUN apt-get update &&\
>      apt-get --no-install-recommends install -y software-properties-common &&\
> -    add-apt-repository ppa:git-core/ppa -y &&\
>      apt-get update && apt-get upgrade -y && \
>      apt-get --no-install-recommends install -y \
>             apt-utils \
> @@ -61,10 +60,11 @@ RUN apt-get update &&\
>      strip /usr/sbin/veritysetup.static && \
>      popd && \
>      echo "Build gen_init_cpio tool" && \
> -    git clone --depth 1 --filter=blob:none --sparse https://github.com/torvalds/linux.git && \
> -    pushd linux && \
> -    git sparse-checkout add usr && cd usr && make gen_init_cpio && \
> -    install gen_init_cpio /usr/sbin/ && \
> +    latest_linux_version=$(git ls-remote --tags --sort='v:refname' https://github.com/torvalds/linux.git | tail -1 | sed 's/.*\///; s/\^{}//; s/v//') && \
> +    curl -LO https://git.kernel.org/torvalds/t/linux-${latest_linux_version}.tar.gz && \
> +    tar xfz linux-${latest_linux_version}.tar.gz && \
> +    pushd linux-${latest_linux_version}/usr && \
> +    make gen_init_cpio && install gen_init_cpio /usr/sbin/ && \
>      popd && \
>      popd && \
>      rm -rf ${build_root}
> ```

Looking into [`gen_init_cpio.c`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/usr/gen_init_cpio.c), it reveals to be a C program using standard C header files (no kernel dependencies). So I like to challenge above approaches with adding ppa causing dependency issues and downloading/cloning megabytes of linux sources for just this program.

Let's simplify this way:
````
hbrueckner@localhost:/tmp/test$ wget -c https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/usr/gen_init_cpio.c
--2022-11-17 13:54:29--  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/usr/gen_init_cpio.c
Resolving git.kernel.org (git.kernel.org)... 145.40.68.75, 2604:1380:4601:e00::1
Connecting to git.kernel.org (git.kernel.org)|145.40.68.75|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14677 (14K) [text/plain]
Saving to: ‘gen_init_cpio.c’

gen_init_cpio.c                          100%[===============================================================================>]  14.33K  --.-KB/s    in 0.02s   

2022-11-17 13:54:29 (580 KB/s) - ‘gen_init_cpio.c’ saved [14677/14677]

hbrueckner@localhost:/tmp/test$ make gen_init_cpio
cc     gen_init_cpio.c   -o gen_init_cpio
brueckner@tuxmaker:/tmp/test$ ./gen_init_cpio -h
Usage:
        ./gen_init_cpio [-t <timestamp>] [-c] <cpio_list>

<cpio_list> is a file containing newline separated entries that
describe the files to be included in the initramfs archive:
````
@arronwy @fidencio Wdyt on above simplification?

**Comment by fidencio** [comment]
Late to the party, but let me add my 2 cents here.

I really prefer @hbrueckner's approach for building gen_init_cpio, and I'd go for that.

About the configs, @hbrueckner, it's been only tested and executed so far on x86, indeed.  What I'd suggest to do is just expand that list, with an if checking for the arch in the https://github.com/kata-containers/kata-containers/blob/4c26d8e16ad281ee4958a8f2d54725b56edb2963/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L164 function.  Having a `-f` is almost for free and I´d take that approach combined with the suggestion above.

**Comment by fidencio** [comment]
And yes, we will need to adapt several scripts so they become more multi-arch friendly. :-)
