### ISSUE TITLE
how to use vm template in runtime-rs along with dragonball?

### ISSUE THREAD

**Issue by xueche** [kata-containers/kata-containers#5725]
there is no the configuration item of `enable_template`in `configuration-dragonball.toml` file,  does dragonball not support tempalte ?

**Comment by studychao** [comment]
Hi, currently it's not support and we will support this feature in the next few months:)

**Comment by xueche** [comment]
> Hi, currently it's not support and we will support this feature in the next few months:)
ok，got it. Thanks~~
