### ISSUE TITLE
[forward port]: dockerfile: QAT: Add an automated QAT kernel/rootfs builder

### ISSUE THREAD

**Issue by jamesodhunt** [kata-containers/kata-containers#575]
Port https://github.com/kata-containers/osbuilder/pull/441 and the bug fix for that PR: https://github.com/kata-containers/osbuilder/pull/441 (issues https://github.com/kata-containers/osbuilder/issues/440 and https://github.com/kata-containers/osbuilder/issues/450) from Kata 1.x.

**Comment by jodh-intel** [comment]
Hi @eadamsintel - could you tal at this please?

**Comment by devimc** [comment]
@GabyCT and I will be working on this
