### ISSUE TITLE
failed to create shim task: Failed to Check if grpc server is working: ttrpc: closed: unknown

### ISSUE THREAD

**Issue by taoohong** [kata-containers/kata-containers#5753]
### version ###
$ containerd -v
containerd github.com/containerd/containerd v1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
$ crictl -v
crictl version 1.24.1
$ kata-runtime -v 
kata-runtime  : 3.1.0-alpha0
commit   : 5f5b4f7da962cf929d25de3dca7cbe1bcec3fa07
OCI specs: 1.0.2-dev

**I'm using CCv0 branch** 

### circtl FATA[0002] error ###
FATA[0002] run pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: Failed to Check if grpc server is working: ttrpc: closed: unknown

### containerd log info ###
INFO[2022-11-24T22:14:32.953515014-05:00] RunPodSandbox for &PodSandboxMetadata{Name:nginx-sandbox,Uid:92995a40-cad0-4f58-b82e-a0430a65a392,Namespace:default,Attempt:1,}
time="2022-11-24T22:14:34.991745444-05:00" level=warning msg="Unable to connect to unix socket (/run/vc/vm/aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2/qmp.sock): dial unix /run/vc/vm/aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2/qmp.sock: connect: no such file or directory" name=containerd-shim-v2 pid=485331 sandbox=aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 source=virtcontainers/hypervisor subsystem=qmp
time="2022-11-24T22:14:34.991808559-05:00" level=error msg="Failed to connect to QEMU instance" error="dial unix /run/vc/vm/aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2/qmp.sock: connect: no such file or directory" name=containerd-shim-v2 pid=485331 sandbox=aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 source=virtcontainers/hypervisor subsystem=qemu
INFO[2022-11-24T22:14:35.440484208-05:00] shim disconnected                             id=aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2
WARN[2022-11-24T22:14:35.440546698-05:00] cleaning up after shim disconnected           id=aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 namespace=k8s.io
INFO[2022-11-24T22:14:35.440554955-05:00] cleaning up dead shim
ERRO[2022-11-24T22:14:35.453971811-05:00] failed to delete                              cmd="/usr/local/bin/containerd-shim-kata-v2 -namespace k8s.io -address /run/containerd/containerd.sock -publish-binary /usr/local/bin/containerd -id aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 -bundle /dev/shm/run/containerd/io.containerd.runtime.v2.task/k8s.io/aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 delete" error="exit status 1"
WARN[2022-11-24T22:14:35.454050937-05:00] failed to clean up after shim disconnected    error="time=\"2022-11-24T22:14:35-05:00\" level=warning msg=\"failed to cleanup container\" container=aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 error=\"open /run/vc/sbs/aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2: no such file or directory\" name=containerd-shim-v2 pid=485370 sandbox=aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 source=containerd-kata-shim-v2\nio.containerd.kata.v2: open /run/vc/sbs/aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2: no such file or directory: exit status 1" id=aeb914a3dc9e931a9262fd71df307e613b42d9b88b6ece92a21efbc344327df2 namespace=k8s.io
ERRO[2022-11-24T22:14:35.454088295-05:00] copy shim log                                 error="read /proc/self/fd/17: file already closed"
ERRO[2022-11-24T22:14:35.514833013-05:00] RunPodSandbox for &PodSandboxMetadata{Name:nginx-sandbox,Uid:92995a40-cad0-4f58-b82e-a0430a65a392,Namespace:default,Attempt:1,} failed, error  error="failed to create containerd task: failed to create shim task: Failed to Check if grpc server is working: ttrpc: closed: unknown"

Thanks a lot

**Comment by ZhizhouTian** [comment]
maybe you compile kata-agent without SECCOMP. There are some description in this [document](https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#connect-to-debug-console):
```
If you enable seccomp in the main configuration file but build the agent without seccomp capability, the runtime exits conservatively with an error message.
```
