### ISSUE TITLE
runtime-rs: When sandbox_cgroup_only is false,  the sandbox controller contrains all threads of containerd-shim-kata-v2 pid

### ISSUE THREAD

**Issue by gaohuatao-1** [kata-containers/kata-containers#5760]
When we have an overhead controller with sandbox_cgroup=false,   we expect to constrain only vCPU threads by moving them into the sandbox controller. Actually， all threads of containerd-shim-kata-v2 pid are moved to sandbox controller, not only vCPU threads but also tokio-runtime-w threads and so on. This behavior does not meet the expectations of the kata overhead design and is inconsistent with kata 2.x .

**Comment by studychao** [comment]
Thanks for reporting this:) @YushuoEdge will help to follow up this issue ~

**Comment by YushuoEdge** [comment]
Thanks for reporting this issue. May I ask that whether you are using cgroup v1 or v2?

**Comment by gaohuatao-1** [comment]
> Thanks for reporting this issue. May I ask that whether you are using cgroup v1 or v2?

We are using cgroup v1.
