### ISSUE TITLE
snap: Packages are not updated

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#5772]
Looking at https://snapcraft.io/kata-containers shows me that the last update is from June 8th 2022, and that the last packages we have per architecture are:
* amd64: 2.4.2
* arm64: 1.11.2
* ppc64el: 1.12.0
* s390x: 1.8.0

None of those versions are supported anymore.

Considering we maintain a few number of CIs running (either on Jenkins or GitHub Actions) to ensure Snap is working, shall we ensure the packages are up-to-date?  Another approach, if we have a notion of how many users actually install Kata Containers from snap, would be to simply remove it from the Snap store.

**Comment by jodh-intel** [comment]
This suggests we have the following problems:

1) The snap release GH action is failing.

2) We didn't notice the snap release GH action was failing.

3) The Kata release process didn't notice the snap release GH action was failing.

4) The process to update the snap on other architectures clearly isn't working.

---

I'll tal at (1) next week if I can. It looks like it could be related to https://github.com/samuelmeuli/action-snapcraft/issues/36. Although that action is useful, I'm starting to question whether we actually need to use it as:

a) It doesn't appear to be actively maintained any more.
b) We can replace it with a few lines of shell code in our own snap actions.

I've also added the topic of snap maintenance to the AC agenda for next week (2022-11-29): https://etherpad.opendev.org/p/Kata_Containers_2022_Architecture_Committee_Mtgs

Any volunteers for (2), (3) and (4)?
