### ISSUE TITLE
CCv0 : Creation of SNP container fails due to qemu argument ‘policy’

### ISSUE THREAD

**Issue by niteeshkd** [kata-containers/kata-containers#5795]
When a SNP container is created using ‘ctr’ with ‘sev_snp_guest = true’ in the Kata configuration file /opt/confidential-containers/share/defaults/kata-containers/configuration-qemu.toml (corresponding to the kata runtime io.containerd.kata-qemu.v2 ) , it reports the following error.
```
$ sudo ctr run --cni --runtime io.containerd.kata-qemu.v2 -t --rm docker.io/library/busybox:latest hello sh
ctr: failed to create shim task: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: sev_snp_launch_start: SNP_LAUNCH_START ret=-5 fw_error=7 'Policy is not allowed'
qemu-system-x86_64: sev_kvm_init: failed to create encryption context
qemu-system-x86_64: failed to initialize kvm: Operation not permitted
: unknown
```
The same error is also observed while trying to create a SNP container by using CoCo operator.

**Comment by mkulke** [comment]
I can confirm, we also ran into this yesterday when attempting to boot an SNP guest

**Comment by jepio** [comment]
Fix has been merged.
