### ISSUE TITLE
 /usr/bin/containerd-shim-kata-v2: no such file or directory: unknown

### ISSUE THREAD

**Issue by stevenlee87** [kata-containers/kata-containers#5800]
ctr run --runtime "io.containerd.kata.v2" --rm -t "$image" test-kata uname -r
ctr: failed to start shim: start failed: : fork/exec /usr/bin/containerd-shim-kata-v2: no such file or directory: unknown

1.Install Kata Containers
https://github.com/kata-containers/kata-containers/releases version:2.5.2

2.containerd
containerd.io-1.6.10-3.1.el8.x86_64
configuration:https://github.com/kata-containers/kata-containers/blob/2.5.2/docs/install/container-manager/containerd/containerd-install.md

3.PATH=/opt/kata:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

when i execute:
ctr run --runtime "io.containerd.kata.v2" --rm -t "$image" test-kata uname -r

echo error:
ctr: failed to start shim: start failed: : fork/exec /usr/bin/containerd-shim-kata-v2: no such file or directory: unknown

and then:
ln -s /opt/kata/bin/containerd-shim-kata-v2 /usr/bin/containerd-shim-kata-v2
ctr run --runtime "io.containerd.kata.v2" --rm -t "$image" test-kata uname -r
5.19.2

Do I have to create soft links manually?

**Comment by YushuoEdge** [comment]
I think yes. We need to create the soft link manually (;
Or we can specify the PATH for "io.containerd.kata.v2" in config.toml of containerd.

**Comment by stevenlee87** [comment]
> I think yes. We need to create the soft link manually (; Or we can specify the PATH for "io.containerd.kata.v2" in config.toml of containerd.

Thanks for the reply, I'll try
