### ISSUE TITLE
[forward port]: qemu: don't disable seccomp - needed for virtiofsd

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#590]
Port https://github.com/kata-containers/packaging/pull/1115 (issue https://github.com/kata-containers/packaging/issues/1116) from Kata 1.x.

**Comment by fidencio** [comment]
QEMU is currently built with `--enable-seccomp`, see: https://github.com/kata-containers/kata-containers/blob/b046c1ef6bbd675ca9f4430572345137b3df6935/tools/packaging/scripts/configure-hypervisor.sh#L409
