### ISSUE TITLE
[forward port]: kata-deploy: Fix typo

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#591]
Port https://github.com/kata-containers/packaging/pull/992 (issue https://github.com/kata-containers/packaging/issues/991) from Kata 1.x.

**Comment by jodh-intel** [comment]
We need a volunteer to look at this one.

/cc @nitkon

**Comment by bporter816** [comment]
Hi! @tommyrousey, @maomarcus, and @yasv123 and I are students at UT Austin, and we're looking to make some open source contributions over the course of the rest of the year as a part of our virtualization class. Could we be assigned to this issue?

**Comment by bergwolf** [comment]
Hi @bporter816 @tommyrousey, @maomarcus, and @yasv123 , sure, we have quite a few beginner issues that can really use your help. Please see look at the issues labeled with `good-first-issue` (https://github.com/kata-containers/kata-containers/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue) and try to fix them. Most of them are simple issues like fixing typos or adding unit tests to existing code.

Looking forward to your contribution. If you have any questions, the github issue page, the kata containers slack channel and the `kata-dev` mailing list are all good places to ask for help.

**Comment by bergwolf** [comment]
And I have assigned this one to you @bporter816. Thank you for your help!

**Comment by bporter816** [comment]
@bergwolf This should be ready for review now. It needs the forward-port tag, which we're not able to add. Let us know if there's any issues with this!

**Comment by jodh-intel** [comment]
Thanks @bporter816 - all done ;)
