### ISSUE TITLE
Rust runtime lacks its own Error type

### ISSUE THREAD

**Issue by Ji-Xinyou** [kata-containers/kata-containers#5918]
In rust runtime, we tend to use anyhow and strings for error handling, which is not a Rust way and not elegant. For each library, implementing its own error type is a more feasible way.

**Comment by OscarTHZhang** [comment]
Hi, I would like to take a look at this issue.

**Comment by OscarTHZhang** [comment]
I saw [shim](https://github.com/kata-containers/kata-containers/blob/main/src/runtime-rs/crates/shim/src/error.rs) already has its own error type. Are we following this and create error types for each of the other crates as well?

**Comment by YushuoEdge** [comment]
Thanks @OscarTHZhang! I think the granularity of Error type can be more granular than crate-level, maybe we can refer to dragonball? In addition, maybe there is also a lack of Error type in the agent? WDYT @Ji-Xinyou

**Comment by OscarTHZhang** [comment]
Sorry, @YushuoEdge, what's "dragonball" you referred to?

**Comment by YushuoEdge** [comment]
Sorry, maybe I didn't explain clearly. Dragonball is a hypervisor/VMM designed for kata scenario. You can see its code in https://github.com/kata-containers/kata-containers/tree/main/src/dragonball.

**Comment by Ji-Xinyou** [comment]
> Thanks @OscarTHZhang! I think the granularity of Error type can be more granular than crate-level, maybe we can refer to dragonball? In addition, maybe there is also a lack of Error type in the agent? WDYT @Ji-Xinyou

I agree. Usually the error type is per-mod and each mod represents a major data structure, whose operations might trigger those error.

**Comment by kalil-pelissier** [comment]
Hi @YushuoEdge @OscarTHZhang :wave:!
Is this issue still up to date? I saw that the `runtime-rs` project has now some specific error definitions.

**Comment by Ji-Xinyou** [comment]
> Hi @YushuoEdge @OscarTHZhang :wave:!
> 
> Is this issue still up to date? I saw that the `runtime-rs` project has now some specific error definitions.   

Hi, I think this is a pretty old issue and I'm going to close it.

Thanks for mentioning this tho!😊
