### ISSUE TITLE
io_uring unknown

### ISSUE THREAD

**Issue by double73** [kata-containers/kata-containers#5931]
I am trying to run the Kata Container in the Kubernetes environment. When creating a Pod, a failure occurs with the following error, so which part should I look at?

`Error: failed to create containerd task: failed to create shim: QMP command failed: Parameter 'aio' does not accept value 'io_uring': unknown
`

kata-container: v3.0.0
host kernel: 5.15.0-56-generic

I built kata-containers snap package myself

**Comment by liubin** [comment]
Can you check your qemu version?

BTW this is for configuring aio for QEMU:

https://github.com/kata-containers/kata-containers/blob/f1381eb361aa2202d48607df8cfc6dbfe6db580c/src/runtime/config/configuration-qemu.toml.in#L226-L238

**Comment by Ji-Xinyou** [comment]
You need to check your `guest kernel version` and `QEMU version`

**Comment by double73** [comment]
QEMU version is 6.2.0
and guest kernel version is 5.19.2. CONFIG_AIO and CONFIG_IO_URING is enabled.
The strange thing is that this error occurs only in one of the two Ubuntu systems I have.

**Comment by Ji-Xinyou** [comment]
hmmm, I would say the io_uring is probably used by QEMU for its IO threads, so the host kernel version probably matters. Sorry for the previous comment letting you check your guest kernel.

Check your host kernel version, please? Maybe the two Ubuntu 20.04 have different host kernels.

**Comment by Ji-Xinyou** [comment]
Woah that seems weird, the two machines have the same host kernel version?

**Comment by double73** [comment]
Yes both have same 5.15.0-56-generic ubuntu kernel

**Comment by Ji-Xinyou** [comment]
Both of them configured with `aio` and `io_uring`? This is getting wild..... I remember these are configured by default.

**Comment by double73** [comment]
Yes, ubuntu kernel enabled aio and io_uring by default.

**Comment by double73** [comment]
I found out that this problem is related to the privileged setting. The problematic system was missing the privileged_without_host_devices = true setting. 
Also, it was confirmed that there was no problem removing the privileged: true setting from the container.

**Comment by liubin** [comment]
Since you have got the answer, can we close this issue? @double73
