### ISSUE TITLE
[certs/Makefile:76: certs/signing_key.x509] Error 1 when build kernel with sev

### ISSUE THREAD

**Issue by immersommer** [kata-containers/kata-containers#5940]
I tried to build kata containers with SEV and followed the developer guide.
I download the code from the branch CCv0 and installed the rootfs image. Then I tried to[ build the kata container kernel ](https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kernel/README.md)

`$ ./build-kernel.sh -v 5.19.2 -g nvidia -f -d -x sev setup`
`$ ./build-kernel.sh -x sev build`
and got error:
```
......
+++++++++++++++  CC      arch/x86/mm/pgprot.o
+++++++++  CC      arch/x86/mm/hugetlbpage.o
++  CC      security/keys/gc.o
++++++++  CC      arch/x86/mm/numa.o
++  CC      security/commoncap.o
  CC      fs/iomap/swapfile.o
+++++++  CC      security/keys/key.o
++  CC      security/keys/keyring.o
  CC      security/min_addr.o
+
-----
  CERT    certs/signing_key.x509
At main.c:161:
- SSL error:0909006C:PEM routines:get_name:no start line: ../crypto/pem/pem_lib.c:745
extract-cert: certs/signing_key.pem: Success
make[1]: *** [certs/Makefile:76: certs/signing_key.x509] Error 1
make[1]: *** Deleting file 'certs/signing_key.x509'
make: *** [Makefile:1849: certs] Error 2
make: *** Waiting for unfinished jobs....
  CC      arch/x86/kernel/cpu/scattered.o
  CC      security/security.o
  CC      security/inode.o
  CC      arch/x86/mm/numa_64.o
  CC      arch/x86/mm/pti.o
  AR      arch/x86/events/intel/built-in.a
  AR      arch/x86/events/built-in.a
  CC      arch/x86/mm/mem_encrypt.o
  CC      arch/x86/kernel/apic/msi.o
......
```
Why it goes wrong?

**Comment by immersommer** [comment]
And I checked the key config on boot
![image](https://user-images.githubusercontent.com/77921310/211198159-c2d8695c-5c44-483d-8b93-ba8e41ed065e.png)

And I also tried to setup it in file build-kernel.sh when I setup sev kernel(line 400-417) But got the same error.
![AGLUY~ GE6~8ZL(I472UZS](https://user-images.githubusercontent.com/77921310/211198270-4309ec78-9ffc-4b98-bb13-3ddf497158d7.png)
![7EQEC8KIOBMWWP}7G2OVJ$3](https://user-images.githubusercontent.com/77921310/211198277-a0ed3f87-6a7b-4861-9566-e4c032987806.png)

@jon @liwei @dubek @bryteise please help me!

**Comment by dubek** [comment]
@immersommer Which Linux distribution+version is your host running? Also, did you clean previous `kata-linux-*` directories from `tools/packaging/kernel/` ?

FWIW I just ran the two commands you mentioned above on Ubuntu 20.04 (branch CCv0) and they pass OK.

**Comment by immersommer** [comment]
> @immersommer Which Linux distribution+version is your host running? Also, did you clean previous `kata-linux-*` directories from `tools/packaging/kernel/` ?
> 
> FWIW I just ran the two commands you mentioned above on Ubuntu 20.04 (branch CCv0) and they pass OK.

I think I have deleted all the files `kata-linux-*` and run on the Ubuntu 20.04(branch CCv0). But I still got this error when I tried to build the kernel with sev. Do you think there is something else that could be wrong? I look forward to your suggestions.

**Comment by immersommer** [comment]
I solved this problem. The error exists in the file ~/kata-containers/tools/packaging/kernel/kata-linux-5.19.2-98/.config
I changed the command `CONFIG_MODULE_SIG_KEY="certs/signing_key.pem"` to `CONFIG_MODULE_SIG_KEY=""`
then I ran `$ ./build-kernel.sh -x sev build` and `$ sudo ./build-kernel.sh -x sev install` and it goes well.
