### ISSUE TITLE
Docker 23.0.0-beta.1 now supports kata with limitations

### ISSUE THREAD

**Issue by marcosfsch** [kata-containers/kata-containers#5941]
**Is your feature request related to a problem? Please describe.**

[Commit](https://github.com/moby/moby/commit/547da0d575519a197fbf4e0543555d508d176084) added support to running kata. This commit was recently released at 23.0.0-beta.1. If running normally it fails:
`vagrant@ubuntu2004:~$ docker run -it --rm --runtime io.containerd.kata.v2 quay.io/centos/centos:stream8`
`docker: Error response from daemon: failed to create shim task: exit status 1: stdout: , stderr: time="2022-12-21T19:37:41Z" level=fatal msg="failed to add interface vethfd9c237 to sandbox: error renaming interface \"vethfd9c237\" to \"eth0\": file exists"
: unknown.`

**Describe the solution you'd like**
If running without network it works.
`vagrant@ubuntu2004:~$ docker run -it --rm --runtime io.containerd.kata.v2 -net none quay.io/centos/centos:stream8`
My request is to review the full support to using docker to run kata containers

**Comment by bergwolf** [comment]
@marcosfsch please see if https://github.com/kata-containers/kata-containers/pull/5972 works in your setup. I've verified it locally with moby 23.0.0-rc.1.

```
[neverland@sources.list.d]$uname -r; docker run -it --rm --runtime io.containerd.kata.v2 busybox uname -r
5.19.0-26-generic
5.19.2
[neverland@sources.list.d]$docker version|grep 23.0
 Version:           23.0.0-rc.1
  Version:          23.0.0-rc.1
```

**Comment by marcosfsch** [comment]
I confirm that this PR does fixes the reported issue:
```
vagrant@ubuntu2004:~$ uname -r; docker run -it --rm --runtime io.containerd.kata.v2 busybox sh -c "uname -r ; ping -c 3 www.baidu.com"
5.4.0-135-generic
5.19.2
PING www.baidu.com (104.193.88.123): 56 data bytes
64 bytes from 104.193.88.123: seq=0 ttl=43 time=188.340 ms
64 bytes from 104.193.88.123: seq=1 ttl=43 time=188.585 ms
64 bytes from 104.193.88.123: seq=2 ttl=43 time=188.516 ms
```
