### ISSUE TITLE
Get some scripts/makefile bits happy on Darwin

### ISSUE THREAD

**Issue by dcantah** [kata-containers/kata-containers#5970]
Substitution in the [yq install script](https://github.com/kata-containers/kata-containers/blob/2d142bc92da091c6d604ba5495772c7e1a9fdd24/ci/install_yq.sh) doesn't like zsh, and additionally the version of yq we're using doesn't have a darwin/arm64 build.

Secondly, the runtime Makefile prints out what binaries it plans to install and uses `readlink -m` to do its bidding. -m doesn;t exist on the BSD variant of readlink, so find an alternative

This is a splitting up of some of the work in https://github.com/kata-containers/kata-containers/pull/4296

**Comment by c3d** [comment]
Hi @dcantah, this looks good to me, but you need to create a pull request and ideally reference that PR in the commit instead of the issue. Unless the iPad GitHub app is all confused...

**Comment by dcantah** [comment]
Not sure, I thought the flow was:

1. Make issue
2. Someone opens a PR to address issue and references the issue ID in the commit

The above is what I followed, the commit (and PR description) for https://github.com/kata-containers/kata-containers/pull/5947 correctly links back to this issue
