### ISSUE TITLE
Add static isolated tracing to agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#60]
For parity with the [golang agent tracing](https://github.com/kata-containers/agent/blob/master/TRACING.md), we need to support the `agent.trace` agent kernel CLI option.

This may not be possible yet given the state of rust-lang bindings for the common tracing frameworks (openTracing, openCensus, openTelemetry). Need to investigate...

**Comment by jodh-intel** [comment]
openTelemetry hasn't made a release yet. Although there are repos for most languages (go, python, js, blah), there isn't an official-looking rust one:

- https://github.com/open-telemetry

However,

- https://github.com/GregBowyer/opentelemetry-rs
- https://docs.rs/opentelemetry_api/0.1.0/opentelemetry_api (not current fwics)

**Comment by jodh-intel** [comment]
openCensus also seems to lack rust support:

- https://github.com/census-instrumentation

And openTracing's offering doesn't look active (hasn't been updated in 2 years and is marked "under initial development and experimental"):

- https://github.com/opentracing/opentracing-rust

(There is also https://github.com/sile/rustracing but that too doesn't appear to be being updated much).

**Comment by davidbarsky** [comment]
(Context: @egernst sent me this issue; y'all might already have an answer.)

There's an alpha-ish [OpenTelemtry exporter in Rust](https://github.com/jtescher/tracing-opentelemetry) that builds atop of the work I did with @hawkw in https://github.com/tokio-rs/tracing/pull/420. As @jtescher is the author, he can speak more to it.

---

Quickly about the `tracing` library: it provides _same_ interface for logs, traces, metrics, or whatever instrumentation format you prefer, but is pretty easy to get started with: it's a drop-in replacement for the [rust-lang/log](https://github.com/rust-lang/log) crate.

**Comment by jodh-intel** [comment]
Thanks for the info @davidbarsky! I'll tal...!

**Comment by davidbarsky** [comment]
Happy to! Feel free to ask questions here or in our Discord channel `tracing-users`: https://discord.gg/EeF3cQw

**Comment by jodh-intel** [comment]
Thanks @davidbarsky - I've got a couple of things to look into first but hope to get round to this later this week...

**Comment by davidbarsky** [comment]
Oh! I see that you're using `slog` at the moment. It's bit more effort to go from `slog` to `tracing` because `tracing` and `slog` take two different approaches to context propagation—`slog` propagates context _explicitly_ by asking you to pass around a logger (if you're not using Slog's [scope](https://github.com/slog-rs/scope)), while `tracing` handles context propagation implicitly. Not surprisingly, I prefer implicit context propagation.

> Thanks @davidbarsky - I've got a couple of things to look into first but hope to get round to this later this week...

No rush! I figured I'd dump some thoughts here first :)

**Comment by jtescher** [comment]
@jodh-intel  [tracing-opentelemetry](https://github.com/jtescher/tracing-opentelemetry/) is ready for some feedback if you want to try it out. Happy to answer any questions you have as you poke around.

**Comment by jodh-intel** [comment]
Hi @davidbarsky and @jtescher - A couple of thoughts:

- Basic OpenTelemetry rust agent tracing

  I think the `#[instrument]` function attribute with some basic opentelemetry / tracer setup code should be enough initially.

  However, since the agent runs in a VM and since we don't want to add extra services to that VM, we need to use VSOCK to allow the spans to flow out to the host for collection by Jaeger, *etc*.

  fwics, that involves creating a custom OpenTelemetry exporter which would handle the VSOCK comms. But that requires the ability to serialise `Span`'s. I found `tracing_serde` but that is a tracing-level facility, not an OpenTelemetry one and doesn't appear to do what we need. Any thoughts?

- Ability to disable tracing

  Our current [golang agent](https://github.com/kata-containers/agent) (which uses OpenTracing / Jaeger) has the ability to enable / disable tracing at runtime. It does this by defaulting to a NOP tracer which is replaced with a real one when needed. Any thoughts again on how this might be achieved with OpenTelemetry and rust?

**Comment by jtescher** [comment]
@jodh-intel for the otel span exporter you will need to be able to serialize opentracing [SpanData](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/exporter/trace/mod.rs#L61) into whichever format you want. You can look at the [jaeger](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-jaeger/src/lib.rs) exporter to see an example of converting the span data to the jaeger expected format.

In terns of disabling at runtime, you can either use the [noop impl](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/api/trace/noop.rs) like in go, you can also use the [Sampler config](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/sdk/trace/sampler.rs#L7-L19) and set it to never or a 0 probability to disable.

**Comment by jodh-intel** [comment]
Thanks @jtescher - I hadn't seen `SpanData` as I'd been looking at your original version of `opentelemetry-rust` :smile: Since `SpanData` contains purely public fields, would you consider adding derives for `Serialize` and `Deserialize` to avoid the awkwardness of manually handling these scenarios?

**Comment by davidbarsky** [comment]
@jodh-intel I think @jtescher covered most of the points here, but I'll note a few things about `tracing`: `tracing` expects that the metadata/spans/fields it exposes to Layers and Subscribers are to be used as an intermediate representation. Specifically, Layers and Subscribers are expected to copy/format the data given to them from `tracing` into whatever structure they are interested in exporting as. In your case, that might be OpenTelemetry-shaped data.

> But that requires the ability to serialise `Span`'s. I found `tracing_serde` but that is a tracing-level facility, not an OpenTelemetry one and doesn't appear to do what we need. Any thoughts?

---

Yep, your understanding on `tracing_serde` is correct. It's meant to be a utility for libraries implementing and exposing `Layers`/`Subscribers`.

I also said "Layers" and "Subscribers" in this reply. "Subscribers" are a pretty low-level implementation detail, and most `tracing` exporters should create "Layers" because features like filtering/teeing/sampling are done in a _much_ better fashion with "Layers". For an example of the functionality that Layers can provide, I recommend checking out https://github.com/tokio-rs/tracing/pull/508. All this stuff needs to be documented, but I haven't had the time to write the documentation yet.

Additionally, I'd like to rename "Layers" to "Subscribers" and the existing "Subscribers" to... something else. However, that rename might be a breaking change to `tracing-core`, which we try to avoid as much as possible.

**Comment by jtescher** [comment]
@jodh-intel sure want to open an issue on https://github.com/open-telemetry/opentelemetry-rust/ to discuss serialization options? 🙏🏻

**Comment by jodh-intel** [comment]
Thanks @jtescher - https://github.com/open-telemetry/opentelemetry-rust/issues/58 raised.

**Comment by jodh-intel** [comment]
My code is essentially blocked on https://github.com/open-telemetry/opentelemetry-rust/pull/64 now, along with new releases for some/all of the following dependent crates:

- `tracing`
- `tracing-attributes`
- `tracing-core`
- `tracing-opentelemetry`
- `tracing-subscriber`

**Comment by hawkw** [comment]
@jodh-intel `tracing-subscriber` 0.2.0 has been [published](https://crates.io/crates/tracing-subscriber/0.2.0). I believe the only unreleased change in `tracing` and `tracing-core` is tokio-rs/tracing#538, if you're blocked on that as well, I'm happy to cut a release. I don't think there are any unreleased changes to `tracing-attributes`?

**Comment by jtescher** [comment]
@jodh-intel the latest `opentelemetry-rust` and `tracing-opentelemetry` have been released 🎉

**Comment by jodh-intel** [comment]
A quick update on this - I now have all the pieces we need, but there is a problem. Here's the current status:

| Component | Status
|-|-|
| VSOCK -> OpenTelemetry trace forwarder | PR raised: #225 |
| Test tool to prod the agent | PR raied #223 |
| agent changes | **blocked** |

I have a rust agent branch that adds trace support and which communicates with the trace forwarder component and which correctly dellivers trace spans from the VM to the Jaeger collector on the host. However, I'm seeing unexpected results which I think relate to the way the tracing [`#[instrument]`](https://docs.rs/tracing-attributes/0.1.8/tracing_attributes/attr.instrument.html) attribute used for instrumentation is working:

- Using `tracing::subscriber::with_default()` only shows the spans for the main thread.
- Using `tracing::subscriber::set_global_default()` creates one trace transaction per thread.

(I have a simple test program that demonstrates this behaviour which proves this isn't a bug with the agent I think. When the test program is run threaded, all threads are started after the relevant tracing API call is made and all threads are waited for before exiting).

This is a problem since the agent is threaded. What we're trying to achieve (and which we already do for the existing golang agent) is to create a single trace for the entire duration of the agent. That trace contains all spans across all threads the agent creates.

@jtescher, @hawkw - Is there some magic setting / API I'm missing? Or is this just the way the tracing crate works?

**Comment by jodh-intel** [comment]
@davidbarsky - do you have any thoughts on https://github.com/kata-containers/kata-containers/issues/60#issuecomment-631980610 ?

**Comment by davidbarsky** [comment]
@jodh-intel Sorry, I'm not sure sure _at this time_. I'm going to dig into this and try to give you an answer later today, if that's alright?

**Comment by jodh-intel** [comment]
@davidbarsky - perfect - thanks! ;)

**Comment by jtescher** [comment]
@jodh-intel do you see this behavior if you explicitly specify the main thread span id as the parent in the spawned thread's spans? e.g. `span!(parent: &main_thread_span_id, tracing::Level::INFO, "thread_1_span_name");`

**Comment by hawkw** [comment]
@jodh-intel If I understand correctly, you want to have a single root span for the entire trace? 

What you're describing is expected behavior. Spawning a thread does _not_ automatically propagate the current span to the spawned thread; you must explicitly propagate that span. This is by design; in many use-cases, a spawned thread is not necessarily considered to be in the same context as the thread that spawned it, so `tracing` gives you the ability to opt in to propagating spans when spawning threads, but doesn't do it by the default.

The `tracing::Span` type implements `Clone` (and is fairly inexpensive to clone; it's an atomic reference count bump internally), so you can send clones of your root span to each thread you spawn and call `Span::enter` on them in the spawned threads. Alternatively, as @jtescher suggested, you can also explicitly set that span's ID as the parent for the spans you create on the child threads. 

Does that make sense?

**Comment by jodh-intel** [comment]
@hawkw, @jtescher - Thanks for the information. I should probably provide the back story here... the existing Kata agent (written in go) supports tracing using openTracing. But that combo of lang+API meant having to litter the code with manually-created spans. That proved to be both cumbersome, ugly and error-prone.

For those reasons and more, I'm really keen to minimise manual span creation for the new rust agent if possible. I don't mind creating a root span and passing a clone of that to each thread. But I really want to leverage  `[#instrument]` as much as possible. If I create a root span in my main thread I think the question resolves to: how do I associate that manually-created root span with the spans auto-generated by  `[#instrument]`?

**Comment by jodh-intel** [comment]
Oh - one more question - is there a way to have spans names on methods include the struct name automatically so the function name would be fully qualified (so that rather than having lots of spans called `new` (for different types) they could be called `Foo::new`, `Bar::new`, *etc*)?

**Comment by jtescher** [comment]
@jodh-intel You should only need to associate the root span in the new thread. Any spans that are children of the root span (using `instrument`, or otherwise) should be correctly associated with the trace from then on.

**Comment by hawkw** [comment]
@jodh-intel 
> Oh - one more question - is there a way to have spans names on methods include the struct name automatically so the function name would be fully qualified (so that rather than having lots of spans called `new` (for different types) they could be called `Foo::new`, `Bar::new`, _etc_)?

Unfortunately, this can't really be done automatically. Since the `#[instrument]` attribute is placed on the function, rather than the `impl` block, it does not have access to a token that is guaranteed to contain the name of the type on which a method is implemented. Procedural macros like `#[instrument]` operate at the level of _syntax_ only, and do not have access to information like the type of a binding, except when it can be determined from the syntax the macro has access to.

However, the `#[instrument]` attribute _does_ support an optional `name = "name"` argument to override the name of the generated span. For example, you could write:
```rust
impl Foo {
    #[tracing::instrument(name = "Foo::new")]
    fn new() -> Self { 
        // ...
    }
   
    // ...

}
```

**Comment by jodh-intel** [comment]
I've tried setting `span!(parent: parent_span, ...)` but still fail to see correct results. I couldn't find any examples or tests that assert the expected behaviour. It sounds like either I'm missing something fundamental, or maybe I'm trying to do something unusual here? I'll tal again tomorrow...

As an aside, I tried to tweak the code that is generated by `#[instrument]` but was foiled by the fact that that crate can only contain proc macros :cry:

**Comment by jtescher** [comment]
@jodh-intel a simple threaded example could look like this (`instrument` should work as well for async):

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    init_tracer()?;

    let app_root = debug_span!("app_root");

    let thread_1_parent = app_root.clone();
    let join_handle_1 = std::thread::spawn(move || {
        let thread_root = debug_span!(parent: thread_1_parent, "thread_1 root");
        let _enter = thread_root.enter();
        debug_span!("thread_1 child");
    });

    let thread_2_parent = app_root.clone();
    let join_handle_2 = std::thread::spawn(move || {
        let thread_root = debug_span!(parent: thread_2_parent, "thread_2 root");
        let _enter = thread_root.enter();
        debug_span!("thread_2 child");
    });

    join_handle_1.join().unwrap();
    join_handle_2.join().unwrap();

    Ok(())
}
```

Shows properly linked spans: 
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/175237/83430090-e9984780-a3e9-11ea-9c71-051ec7932d83.png">

**Comment by jodh-intel** [comment]
@jtescher - thanks very much for the info. However, as mentioned I'm trying to do this without creating spans manually (aside from maybe a root one). Do you know how to produce the results in the graphic above using a single root span + `#[instrument]` on all functions you want to trace? Even my test program that uses both `#[instrument]` and manual spans doesn't seem to produce the correct results but I'll tal tomorrow using your code above to isolate the issue with manually created spans. But that still leaves the issue of how to deal with `#[instrument]`.

**Comment by jtescher** [comment]
@jodh-intel is something like this what you mean? From inside the async `thread_work` function you can use `log`, `span`, await other async functions, etc as you normally would in `tracing`.

```rust
#[instrument]
async fn thread_work() -> &'static str {
    debug!("doing work!");

    "success"
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    init_tracer()?;

    let app_root = debug_span!("app_root");

    let thread_1_parent = app_root.clone();
    let join_handle_1 = std::thread::spawn(move || async {
        let thread_root = debug_span!(parent: thread_1_parent, "thread_1 root");
        thread_work().instrument(thread_root).await
    });

    let thread_2_parent = app_root.clone();
    let join_handle_2 = std::thread::spawn(move || async {
        let thread_root = debug_span!(parent: thread_2_parent, "thread_2 root");
        thread_work().instrument(thread_root).await
    });

    join_handle_1.join().unwrap().await;
    join_handle_2.join().unwrap().await;

    Ok(())
}
```

**Comment by hawkw** [comment]
@jodh-intel 
> @jtescher - thanks very much for the info. However, as mentioned I'm trying to do this without creating spans manually (aside from maybe a root one). Do you know how to produce the results in the graphic above using a single root span + `#[instrument]` on all functions you want to trace? Even my test program that uses both `#[instrument]` and manual spans doesn't seem to produce the correct results but I'll tal tomorrow using your code above to isolate the issue with manually created spans. But that still leaves the issue of how to deal with `#[instrument]`.

Are you entering the root span before calling `#[instrument]`ed functions on the spawned threads? For example:
```rust
#[instrument]
fn do_something() { 
    // ...
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    init_tracer()?;

    // Create the application root span.
    let root_span = info_span!("root");
    let _enter = root_span.enter();
    
    // Clone the span to send to the spawned thread.
    let t1_span = root_span.clone();
    let t1 = std::thread::spawn(move || {
        // Enter the root span **before** calling instrumented functions. 
        let _enter = t1_span.enter();

        // Now, when we call the instrumented function, it will be called in
        // the root span's context, so the span generated by #[instrument]
        // will have the root span as its parent.
        do_something();

        // ...and so on ...
    });
    // ...
}
```

**Comment by jodh-intel** [comment]
I've pushed an updated branch to https://github.com/jodh-intel/kata-containers/tree/2.0-dev-add-tracing-devel. I think this is (again) conflicted with `2.0-dev` but as you can imagine, keeping a branch like this up-to-date is very difficult as almost every agent PR breaks it :sob:

@lifupan, @liubin, @bergwolf - If you could tal at the branch and try to test it, that would be very helpful.

I'll be on and offline quite a bit now until January but I am around next week from Tuesday so maybe we can chat about this problem next week?

/cc @amshinde


# Summary

I'm seeing strange behaviour: the shutdown patch is 100% reliable when run in a normal QEMU VM but when run in a Kata container it looks like I get a thread deadlock in the namespace code (`Sandbox::setup_shared_namespaces()` calling `Namespace::setup()` hangs on `File::create(new_ns_path.as_path())?;`). Popping the top tracing patch would make this clearer.

The tracing patch itself is also problematic in two ways:

1. Unfortunately, it's not using the latest set of tracing+opentelemetry crate versions

   I have not been able to keep up with all the breaking API changes made upstream :sob:
   
1. I'm also seeing shutdown hangs even running in a QEMU VM with the branch above.

   The problem is a thread one again fwics. I need more time to look into it but it may relate to the ttrpc crates use of threads.

# Testing

To test the tracing patch, you need to do the following:

- Build my branch and add to a rootfs image using osbuilder.

- Enable tracing

  ```bash
  $ cfg_file="/etc/kata-containers/configuration.toml"
  $ sudo crudini --set "$cfg_file" agent.kata enable_tracing 'true'
  $ sudo crudini --set "$cfg_file" agent.kata trace_mode '"static"'
  ```

- Start the trace forwarder

  ```bash
  $ cd $GOPATH/src/github.com/kata-containers/kata-containers/src/trace-forwarder
  $ cargo run
  ```
  
- Start the Jaeger trace collector

  Run the docker command here: https://www.jaegertracing.io/docs/1.21/getting-started/#all-in-one

- Create a container

  ```bash
  $ sudo ctr run --runtime "io.containerd.kata.v2" --rm -t "docker.io/library/busybox:latest" foo sh
  ```

# Running in a VM

Alternatively, you can run the agent in a QEMU VM. For example:

- Start agent

  ```bash
  $ sudo RUST_BACKTRACE=full KATA_AGENT_TRACE_TYPE=isolated KATA_AGENT_LOG_LEVEL=debug KATA_AGENT_SERVER_ADDR="unix:///tmp/foo.socket" target/x86_64-unknown-linux-gnu/debug/kata-agent
  ```
  
- Prod it

  ```bash
  $ export bundle_dir=$HOME/tmp/bundle
  $ cargo run -- -l debug connect --server-address "unix://@/tmp/foo.socket" --bundle-dir "$bundle_dir" -c Check -c GetGuestDetails -c CreateSandbox -c CreateContainer -c DestroySandbox
  ```

**Comment by liubin** [comment]
@jodh-intel I am seeing forward to early available of trace both the runtime and agent.

Before commenting on code, I have some questions(not problems) about traces in Kata.

- Our traces is more like lifetime(from create sandbox to delete sandbox) than common talked traces(only one RPC call).
- It seems `trace-forwarder` should be started first for traces, this may bring a bit complexity, both deployment and availability. Is it possible to combine spans from agent and in runtime together? For example agent write spans to runtime or runtime get spans from agent(like the `getOOMEvent` way) ?

**Comment by liubin** [comment]
About stopping-hang, I found this log:

```
398993:Dec 17 17:22:02 k kata[1508955]: time="2020-12-17T17:22:02.89224099+08:00" level=debug msg="reading guest console" ID=1543238f450770a59dbf43bfd5e4311fbb8fb694525b9587b7b3b5ef02cfa653 console-protocol=unix console-url=/run/vc/vm/1543238f450770a59dbf43bfd5e4311fbb8fb694525b9587b7b3b5ef02cfa653/console.sock sandbox=1543238f450770a59dbf43bfd5e4311fbb8fb694525b9587b7b3b5ef02cfa653 source=virtcontainers subsystem=sandbox 
vmconsole="{\"msg\":\"failed to send signal\",\"level\":\"ERRO\",\"ts\":\"2020-12-17T09:22:02.883686929+00:00\",\"pid\":\"56\",\"source\":\"agent\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"subsystem\":\"signals\",
\"error\":\"Some(\\\"SendError(..)\\\")\",\"signal\":\"17\"}"

```

From `crossbeam-channel` [document](https://docs.rs/crossbeam-channel/0.5.0/crossbeam_channel/index.html#disconnection) :

> When all senders or all receivers associated with a channel get dropped, the channel becomes disconnected. No more messages can be sent

But I couldn't find where the sender or receiver was dropped :-( yet.

**Comment by jodh-intel** [comment]
Hi @liubin - yes, the [VSOCK/Jaeger trace forwarder component](https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/trace-forwarder) will need to be started before the agent, either by the runtime itself or by a systemd job by an admin.


> Is it possible to combine spans from agent and in runtime together

Not yet. This is what we called "collated tracing" in the 1.x runtime (see https://github.com/kata-containers/agent/blob/master/TRACING.md#trace-types, https://github.com/kata-containers/kata-containers/issues/420, https://github.com/kata-containers/kata-containers/issues/419, https://github.com/kata-containers/kata-containers/issues/421).

When #1210 lands, this branch is going to have to be almost entirely rewritten fwics, but it should make the code cleaner I hope.

Thanks for the patch - I'll test it later...

**Comment by fidencio** [comment]
@jodh-intel, while going through the opened 2.x issues that have the "needs-review" label, I ended up facing this one.

For now, I'm removing the "needs-review" label, as this very welcome enhancement has been worked on, but there are still some missing pieces (as far as I remember our discussion the AC meeting last week).

**Comment by jodh-intel** [comment]
Hi @Tim-Zhang - An update, and a request for some help...

# Update

I've picked this work up again and plan to raise *two* PRs:

1. PR to shutdown the agent cleanly
2. PR to add the tracing.

By dividing the work like this, I *hope* it's going to be easier to land as landing the whole lot is a major headache due to all the rebasing required :sob:

# A bug

The shutdown code is almost done, but doesn't work in a real Kata VM (although it does work stand-alone). It looks like the new async ttrpc server is (unfortunately again) blocking the shutdown, specifically here:

```diff
diff --git a/src/asynchronous/server.rs b/src/asynchronous/server.rs
index b3e0d13..bc91b58 100644
--- a/src/asynchronous/server.rs
+++ b/src/asynchronous/server.rs
@@ -262,12 +262,13 @@ impl Server {
     pub async fn disconnect(&mut self) {
         if let Some(tx) = self.disconnect_tx.take() {
             tx.send(1).ok();
         }

         if let Some(mut rx) = self.all_conn_done_rx.take() {
+            // XXX: blocks forever here.
             rx.recv().await;
         }
     }

     pub async fn stop_listen(&mut self) {
         if let Some(tx) = self.stop_listen_tx.take() {
```

I'm going to take a closer look at this tomorrow but if you could tal tomorrow AM, that would help a lot (since this is blocking the shutdown PR (which is blocking the tracing PR :))

Ideally, I think we'd have a set of unit tests in the ttrpc crate to help avoid issues like this. However, that's complicated by the requirement to create an actual service. I have created a "NOP" server unit test (no registered service), but it -- annoyingly -- shuts down the server correctly. However, I think we need a more realistic registered service unit test (for sync and async servers).

/cc @lifupan, @liubin.

**Comment by lifupan** [comment]
> Hi @Tim-Zhang - An update, and a request for some help...
> 
> # Update
> I've picked this work up again and plan to raise _two_ PRs:
> 
> 1. PR to shutdown the agent cleanly
> 2. PR to add the tracing.
> 
> By dividing the work like this, I _hope_ it's going to be easier to land as landing the whole lot is a major headache due to all the rebasing required 😭
> 
> # A bug
> The shutdown code is almost done, but doesn't work in a real Kata VM (although it does work stand-alone). It looks like the new async ttrpc server is (unfortunately again) blocking the shutdown, specifically here:
> 
> ```diff
> diff --git a/src/asynchronous/server.rs b/src/asynchronous/server.rs
> index b3e0d13..bc91b58 100644
> --- a/src/asynchronous/server.rs
> +++ b/src/asynchronous/server.rs
> @@ -262,12 +262,13 @@ impl Server {
>      pub async fn disconnect(&mut self) {
>          if let Some(tx) = self.disconnect_tx.take() {
>              tx.send(1).ok();
>          }
> 
>          if let Some(mut rx) = self.all_conn_done_rx.take() {
> +            // XXX: blocks forever here.
>              rx.recv().await;
>          }
>      }
> 
>      pub async fn stop_listen(&mut self) {
>          if let Some(tx) = self.stop_listen_tx.take() {
> ```
> 
> I'm going to take a closer look at this tomorrow but if you could tal tomorrow AM, that would help a lot (since this is blocking the shutdown PR (which is blocking the tracing PR :))
> 
> Ideally, I think we'd have a set of unit tests in the ttrpc crate to help avoid issues like this. However, that's complicated by the requirement to create an actual service. I have created a "NOP" server unit test (no registered service), but it -- annoyingly -- shuts down the server correctly. However, I think we need a more realistic registered service unit test (for sync and async servers).
> 
> /cc @lifupan, @liubin.

@jodh-intel  @Tim-Zhang  I agree, we'd better add some more test cases for ttrpc, in case regressions were introduced. Maybe we can borrow the ttrpc's test cases from the go version.

**Comment by jodh-intel** [comment]
Hi @Tim-Zhang - I've pushed the basic shutdown branch to https://github.com/jodh-intel/kata-containers/tree/agent-shutdown. Could we chat on Slack/IRC tomorrow about this maybe? Just ping me :smile:

**Comment by jodh-intel** [comment]
I thought the issue may be related to the way the runtime is being created, but even switching https://github.com/jodh-intel/kata-containers/blob/agent-shutdown/src/agent/src/main.rs#L293 to use `tokio::runtime::Builder::new_multi_thread()`, I still see the hang.

/cc @mxpv in case he has thoughts on this.

**Comment by jodh-intel** [comment]
@Tim-Zhang has raised #1525 which looks to unblock the hang in the ttrpc create when attempting to shutdown the agent.

**Comment by jodh-intel** [comment]
Raised [PR to allow clean agent shutdown](https://github.com/kata-containers/kata-containers/pull/1535), required to support agent tracing.

**Comment by jodh-intel** [comment]
Hi @jtescher and @davidbarsky,

After a long hiatus, we're now back looking at agent tracing for Kata. The significant change to the code we're trying to add tracing to is that it's now async.

I've been trying to update our now-ancient tracing code that we were using some time ago to use the _latest versions_ of the five tracing crates we seem to need to get global Jaeger tracing with a custom trace exporter:

- `tracing`
- `tracing-subscriber`
- `tracing-opentelemetry`
- `opentelemetry`
- `opentelemetry-jaeger`

Most of these seem to have changed quite a bit. The terminology used also seems to have changed too, so frankly I'm now confused. I've also hit issues with crate examples that don't appear to work (they are marked `norun` so are not being tested which prolly explains the breakage).

# Code Components

What we currently have:

- [x] custom `SpanExporter`
- [x] `TracerProvider`
- [x] `GlobalTracerProvider`
- [x] `sdk::trace::Tracer`

What we _used_ to do is then create a `OpenTelemetryLayer`, create a `Subscriber` from that layer, and then register that subscriber as the default global one:

```rust
let layer = OpenTelemetryLayer::with_tracer(tracer);
let subscriber = Registry::default().with(layer);
tracing::subscriber::set_global_default(trace_subscriber)?;
```

This all seems to have changed now though. Although I have a `Tracer`, I cannot now see how to create a `Layer` that will then allow me to create a `Subscriber`, which I can then register using `tracing::subscriber::set_global_default(trace_subscriber)`.

I've tried scouting around the examples and tests but it quite confusing given the number of crates and inter-dependencies to get a clear picture of the minimum requires for us.

Any help you can provide gratefully received!

**Comment by jtescher** [comment]
@jodh-intel which version of `tracing-opentelemetry` are you currently using? the [latest release](https://github.com/tokio-rs/tracing/blob/v0.1.x/tracing-opentelemetry/Cargo.toml#L25) is compatible with otel `0.13.x`. With those two versions the code you posted should work.

**Comment by jodh-intel** [comment]
@jtescher - To make this easier to explain and debug, I've packaged up a minimal "working" (aka "broken" ;) example here:

- https://github.com/jodh-intel/test-tracing-opentelemetry

If you try to build with `cargo build`, you'll get an angry red rust splat like this:

```cargo
error[E0277]: the trait bound `opentelemetry::sdk::trace::Tracer: opentelemetry::trace::tracer::Tracer` is not satisfied
  --> src/tracer.rs:35:41
   |
35 |     let layer = OpenTelemetryLayer::new(tracer);
   |                                         ^^^^^^ the trait `opentelemetry::trace::tracer::Tracer` is not implemented for `opentelemetry::sdk::trace::Tracer`
   |
   = note: required by `OpenTelemetryLayer::<S, T>::new`

error[E0277]: the trait bound `opentelemetry::sdk::trace::Tracer: PreSampledTracer` is not satisfied
  --> src/tracer.rs:35:41
   |
35 |     let layer = OpenTelemetryLayer::new(tracer);
   |                                         ^^^^^^ the trait `PreSampledTracer` is not implemented for `opentelemetry::sdk::trace::Tracer`
   |
   = note: required by `OpenTelemetryLayer::<S, T>::new`

error: aborting due to 3 previous errors; 3 warnings emitted
```

The problem seems to be that the `Tracer[Provider`] returned by the `opentelemetry` `get_tracer()` call doesn't implement the `PreSampledTracer`.

**Comment by jtescher** [comment]
@jodh-intel if you change https://github.com/jodh-intel/test-tracing-opentelemetry/blob/main/Cargo.toml#L20 to `0.13` instead of `0.14` does it work as expected?

**Comment by jodh-intel** [comment]
@jtescher - Thanks and ouch! :smile: Yes, that does indeed work now.

It seems that my problems haven't ended quite yet though... Reworking [trace forwarder](https://github.com/kata-containers/kata-containers/tree/main/src/trace-forwarder) to use the latest tracing crate versions (crucially `opentelemetry-jaeger = "0.13.0"`) is failing to compile in an interesting way:

```rust
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
  --> src/handler.rs:56:6
   |
56 | ) -> Result<()> {
   |      ^^^^^^^^^^
   |
note: hidden type `impl futures::Future` captures lifetime smaller than the function body
  --> src/handler.rs:56:6
   |
56 | ) -> Result<()> {
   |      ^^^^^^^^^^

error[E0277]: the trait bound `opentelemetry_jaeger::Exporter: SpanExporter` is not satisfied
  --> src/server.rs:74:70
   |
74 |                     let f = handler::handle_connection(logger, conn, &exporter);
   |                                                                      ^^^^^^^^^ the trait `SpanExporter` is not implemented for `opentelemetry_jaeger::Exporter`
   |
   = note: required for the cast to the object type `dyn SpanExporter`
```

I have no idea about the first erorr but I have seen that "not implemented" issue when mixing crate version. However, the trace forwarder only uses a single version of `opentelemetry-jaeger`, so this is unexpected (is it a known issue with that version of `opentelemetry-jaeger`?). I've pushed just that code to https://github.com/jodh-intel/test-trace-forwarder.

**Comment by jtescher** [comment]
@jodh-intel ah yeah should be `opentelemetry-jaeger` version `0.12.x`. Basically otel and otel-jaeger support is still one version back, support for latest versions coming in https://github.com/tokio-rs/tracing/pull/1394

**Comment by jodh-intel** [comment]
Thanks @jtescher. That solves the final error above but not the lifetime error. It appears I can no longer pass around a `&dyn SpanExporter` with `opentelemetry-jaeger`. Is this a known issue or recent change? (if the latter do I need to rework to box it?)

**Comment by jtescher** [comment]
@jodh-intel `opentelemetry-jaeger`'s exporter should work fine as `&dyn SpanExporter`, span processors use that form internally in the sdk. Likely something else, do you have a branch where you're seeing that issue?

**Comment by jodh-intel** [comment]
Hi @jtescher - it's the [same branch](https://github.com/jodh-intel/test-trace-forwarder). I've pushed a commit to downgrade opentelemetry-jaeger from `0.13.0` to `0.12.0` and now see...

```bash
$ make

    :

error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
  --> src/handler.rs:56:6
   |
56 | ) -> Result<()> {
   |      ^^^^^^^^^^
   |
note: hidden type `impl futures::Future` captures lifetime smaller than the function body
  --> src/handler.rs:56:6
   |
56 | ) -> Result<()> {
   |      ^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0700`.
error: could not compile `kata-trace-forwarder`
```

The problem seems to be the `exporter: &dyn SpanExporter` param to `handle_trace_data()` and `handle_connection()`. This code used to work (although admittedly it wasn't `async` way back when).

**Comment by jtescher** [comment]
@jodh-intel interesting looks like it's an issue with async-trait https://github.com/dtolnay/async-trait/issues/48

**Comment by jodh-intel** [comment]
Hi @jtescher and @davidbarsky - I've taken a look at the async trait issue above (and the ones related to it) but am rather confused: there is talk of workarounds but I've tried the "pin and box" and the "struct wrapper" tricks but didn't manage to convince `rustc` to compile the code :cry: Is there a workaround that we can use or is it a case of choosing one of the following options maybe:

- Waiting for a new version of the `async-trait` crate that fixes this lifetime issue?
- Downgrading the `async-trait` crate to a version without the issue?
- Downgrading the `opentelemetry*` crate(s) further (to pre-async days?)?

(I'm loathe to downgrade unless essential because...potential security implications for one thing).

We're _very_ keen to get this feature landed, but keep hitting blockers, I think partly due to the continually evolving landscape. Another part of the problem here is that we have tracing code running inside a VM, and tracing code running outside it on the host system. These two components need to talk together so I would imagine, given the changing APIs, that the only safe option would be to ensure both "sides" are running the exact same crate versions?

tbh, I'm unclear how I would find out which combo of crate versions we should be using (we're trying to follow the latest releases but as shown that is sometimes problematic). There is also the question of how to handle updates to these create versions in the future. On a related note, how close do you think we are to a stable / 1.0.0 "stack" of rust tracing crates?

Any help and/or further advice on the best approach for us would be much appreciated :smile:

/cc @Tim-Zhang, @bergwolf in case they've looked at this too.

**Comment by jtescher** [comment]
@jodh-intel ok couple updates. First latest `tracing-opentelemetry` is now supports otel `0.14` so you can just use latest versions of all the crates 🎉 . Second you can fix your lifetime issue (in either version) by explicitly declaring the lifetime (and the ref has to be mut).

```diff
-async fn handle_trace_data(
+async fn handle_trace_data<'a>(
     logger: Logger,
-    reader: &mut dyn Read,
-    exporter: &dyn SpanExporter,
+    reader: &'a mut dyn Read,
+    exporter: &'a mut dyn SpanExporter,
 ) -> Result<()> {

```

Lots of folks interested in a 1.0 level tracing stack so hopefully well get there soon 😄

**Comment by jodh-intel** [comment]
Thanks @jtescher.
