### ISSUE TITLE
runtime-rs: lack single container support

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#6006]
There are only pod sandbox and pod container support in runtime-rs but lack of single container. When start a container using ctr, runtime-rs treat it as a pod sandbox, that leads to failure of static allocation of resource.

Try for kata3.0

> ctr run --runtime io.containerd.run.kata.v2  --cpus 3.0 --rm -t docker.io/library/ubuntu:latest hello lscpu 

you can see no additional cpus are added into kata.

**Comment by YushuoEdge** [comment]
Thanks @jongwu ! I am not sure whether adding single_container  support can really solve the problem of "no additional cpus are added into kata". I think the problem maybe raised by "cpu hotplug support" is still in progress(?

**Comment by jongwu** [comment]
> Thanks @jongwu ! I am not sure whether adding single_container support can really solve the problem of "no additional cpus are added into kata".

Containers started by ctr is a single container but in runtime-rs it is a pod sandbox, thus resource info lies in oci/spec config file  will not be read. Once we correct it right as a single container, the static resource info can be read.

 I think the problem maybe raised by "cpu hotplug support" is still in progress(?

static resource management is different with cpu/mem hotplug. see https://github.com/kata-containers/kata-containers/blob/853dd98b7b13504d929ef5a5cecce541a92964ad/docs/design/vcpu-handling.md#virtual-cpu-handling-without-hotplug

**Comment by YushuoEdge** [comment]
> > Thanks @jongwu ! I am not sure whether adding single_container support can really solve the problem of "no additional cpus are added into kata".
> 
> Containers started by ctr is a single container but in runtime-rs it is a pod sandbox, thus resource info lies in oci/spec config file will not be read. Once we correct it right as a single container, the static resource info can be read.
> 
> I think the problem maybe raised by "cpu hotplug support" is still in progress(?
> 
> static resource management is different with cpu/mem hotplug. see [`853dd98`/docs/design/vcpu-handling.md#virtual-cpu-handling-without-hotplug](https://github.com/kata-containers/kata-containers/blob/853dd98b7b13504d929ef5a5cecce541a92964ad/docs/design/vcpu-handling.md#virtual-cpu-handling-without-hotplug)

I see! Thank you!
