### ISSUE TITLE
[forward port]: sandbox: Stop and clean up containers that fail to create

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#601]
Port https://github.com/kata-containers/runtime/pull/2826 (issue https://github.com/kata-containers/runtime/issues/2816) from Kata 1.x.

**Comment by jodh-intel** [comment]
Hi @evanfoster - would you be able to tal to see if this needs to be applied to the 2.0 branch?

**Comment by evanfoster** [comment]
Hey @jodh-intel,

That PR was brought forward in https://github.com/kata-containers/kata-containers/pull/434, so I think we should be good to go!

**Comment by jodh-intel** [comment]
Thanks @evanfoster. Closing...
