### ISSUE TITLE
networking: With new prestartHookFunc scanning, internetworking model of none causes container to fail to start

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#6021]
I'm not 100% sure about this problem's reproduce in 'vanilla' kata-containers, but we've hit this error in peer pod https://github.com/confidential-containers/cloud-api-adaptor/issues/505, with the following logs
```
Jan 10 08:34:29 ibm-caa-worker kata[261107]: time="2023-01-10T08:34:29.773508281Z" level=info msg="calling remote hypervisor StartVM (timeout: 600)"
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.701441048Z" level=info msg="hypervisor pid is 261107" name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=sandbox
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.702363934Z" level=info msg="veth interface found" name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=network
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.702417759Z" level=info msg="Attaching endpoint" endpoint-type=virtual hotplug=true name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=network
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.702458597Z" level=error msg="Error bridging virtual ep" error="Invalid internetworking model" name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=network
```

It's in sandbox networking, so way outside of my comfort zone, but I think the issue boils down to:
- https://github.com/kata-containers/kata-containers/commit/578a9c25f05c53525319a968f379ca718e8c9db7 added:
```
// We need to rescan and handle the change.
	if s.factory != nil || prestartHookFunc != nil {
```
which means `s.network.AddEndpoints(ctx, s, nil, true)` is now called during `startVM`
- `AddEndpoints` calls `func (n *LinuxNetwork) addSingleEndpoint(ctx context.Context, s *Sandbox, netInfo NetworkInfo, hotplug bool) (Endpoint, error) {` which calls `func (endpoint *VethEndpoint) HotAttach(ctx context.Context, h Hypervisor) error {` which calls `func xConnectVMNetwork(ctx context.Context, endpoint Endpoint, h Hypervisor) error { `
- This has a switch on the networking model with cases for `mactap` and `tcfilter` and a default which gives `err = fmt.Errorf("Invalid internetworking model")`
- Our configuration for peer pods is `internetworking_model="none"` so we fall into the default case.

**Comment by bergwolf** [comment]
I tried `v3.0.1` (which doesn't have the mentioned commit https://github.com/kata-containers/kata-containers/commit/578a9c25f05c53525319a968f379ca718e8c9db7) with `internetworking_model="none"` and still failed with 
```
FATA[0000] running container: run pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: Invalid internetworking model: unknown
```

If I set `disable_netns=true` together with `internetworking_model="none"`, it passed with `v3.0.1` but still failed on main. I think the issue is that with `disable_netns=true`, the vmm is in the host network namespace and we should not scan the host netns.

**Comment by bergwolf** [comment]
@stevenhorsman FYI, I created #6037 to fix this. Sorry for the trouble.

**Comment by stevenhorsman** [comment]
> @stevenhorsman FYI, I created #6037 to fix this. Sorry for the trouble.

Thanks very much for looking into it. I'll kill off my PR now there is an expert looking at it :)
