### ISSUE TITLE
[forward port]: qemu: add annotations for iommu_platform for s390x virtio devices

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#603]
Port https://github.com/kata-containers/runtime/pull/2831 (issue https://github.com/kata-containers/runtime/issues/2830) from Kata 1.x.

**Comment by jodh-intel** [comment]
Hi @huoqifeng - would you be able to check if this needs to be applied to the 2.0-dev branch?

**Comment by huoqifeng** [comment]
Yes, it should be in 2.0-dev branch. is there a guide on how to deliver code to 2.0-dev branch? @jodh-intel

**Comment by jodh-intel** [comment]
@huoqifeng - There is now! https://github.com/kata-containers/community/wiki/Porting-PRs-between-Kata-1.x-and-Kata-2.0

**Comment by huoqifeng** [comment]
@jodh-intel thanks, so the idea is to generate patch against 1.x repo and apply the generated patch to 2.0 repo.

**Comment by huoqifeng** [comment]
Commit https://github.com/kata-containers/runtime/pull/2831/commits/9305ef722b1ad2192654655ee26e4a246a987d59 already ported to 2.0-dev https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/vendor/github.com/intel/govmm/qemu/qemu.go, so, will just port commit https://github.com/kata-containers/runtime/pull/2831/commits/3a4aec153e5824d437ca1cc2557f4f793dcb9d28
