### ISSUE TITLE
[forward port]: clh: Add support to unplug block devices

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#604]
Port https://github.com/kata-containers/runtime/pull/2833 (issue https://github.com/kata-containers/runtime/issues/2832) from Kata 1.x.

**Comment by likebreath** [comment]
@jodh-intel Thanks for creating those labels and issues to track the forward port. This is awsome.

This particular feature is already landed in kata 2.0 by PR https://github.com/kata-containers/kata-containers/pull/543, so I am closing this issue. Any questions, please let me know.
