### ISSUE TITLE
sandbox.go became linux specific with vCPU changes

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#6044]
unix.CPUSet and unix.SchedSetaffinity are Linux specific -- this was added with 2508d39b7cb43d3465d9975fb780306834826da6

I do not think  vc/sandbox is the best place to add the logic for handling the CPU affinity - we already have a resource controller that explicitly manages CPUSets?  While the approach introduced uses schedule affinity instead of specific group (resource controller manipulation), at least they are somewhat related (ish) and help abstract away Linux specifics from sandbox / virtcontainers package.

**Comment by dcantah** [comment]
I'll look into this

**Comment by egernst** [comment]
I think we'd be better off augmenting resource controller to have a method or just a function for setting a threads' cpu affinity.

something horrid like:
```
func SetThreadAffinity(threadId int, cpuset string) 
```
