### ISSUE TITLE
[forward port]: virtcontainers: Expand unit test coverage for asset

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#605]
Port https://github.com/kata-containers/runtime/pull/2836 (issue https://github.com/kata-containers/runtime/issues/2835) from Kata 1.x.

**Comment by cmaf** [comment]
Forward port: [#425](https://github.com/kata-containers/kata-containers/pull/425) (issue [#424](https://github.com/kata-containers/kata-containers/issues/424))
