### ISSUE TITLE
[forward port]: versions: Update qemu-virtiofs to 5.0 and cloud-hypervisor 0.9

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#606]
Port https://github.com/kata-containers/runtime/pull/2840 (issue https://github.com/kata-containers/runtime/issues/2848) from Kata 1.x.

**Comment by likebreath** [comment]
This particular feature is already landed in kata 2.0 by PR #543, so I am closing this issue. Any questions, please let me know.
