### ISSUE TITLE
In the arm64 environment, the pod cannot set the cpu limit.

### ISSUE THREAD

**Issue by singhwang** [kata-containers/kata-containers#6069]
Description of problem
In the arm64 environment, the pod cannot set the cpu limit, and the error message is: failed to create containerd task: failed to create shim task: failed to query hotpluggable CPUs: QMP command failed: The feature 'query-hotpluggable-cpus' is not enabled: unknown.

The pod is defined and created as follows:
```
$ cat nginx-qemu.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-qemu
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
      requests:
        cpu: "1"
        memory: "200Mi"
$ kubectl create -f nginx-qemu.yaml
```

The version of kata containers is 3.0.0, the version of qemu is 6.2.0, and the static package is built using the following command:
```
$ cd $GOPATH/src/github.com/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build/
$ ./kata-deploy-binaries-in-docker.sh --build=all
```

I have confirmed that the host of the pod supports the cpu hotplug feature, refer to this link https://www.cyberciti.biz/faq/debian-rhel-centos-redhat-suse-hotplug-cpu/

Expected result
The pod can be created successfully.

Actual result
The pod creation failed and the cpu hotplug feature cannot be used. The error message is as follows:
```
$ kubectl describe pod nginx-qemu
......
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  16s               default-scheduler  Successfully assigned default/nginx-qemu to kata-containers
  Normal   Pulled     8s (x2 over 14s)  kubelet            Container image "nginx:latest" already present on machine
  Normal   Created    8s (x2 over 14s)  kubelet            Created container nginx
  Warning  Failed     3s (x2 over 9s)   kubelet            Error: failed to create containerd task: failed to create shim task: failed to query hotpluggable CPUs: QMP command failed: The feature 'query-hotpluggable-cpus' is not enabled: unknown
  Warning  BackOff    1s (x2 over 2s)   kubelet            Back-off restarting failed container
```

Further information
For the problem that the pod cannot set the cpu limit in the arm64 environment, although I know that it can be solved by static_sandbox_resource_mgmt = true, this is treated as the cpu hotplug is not supported, but I want to know, in the arm64 environment, when the host supports using the cpu hotplug feature, kata containers cannot use the cpu hotplug yet, how can I solve it?

**Comment by singhwang** [comment]
@jongwu I asked this question in the community WeChat group, Mr. Liu Bin asked me to raise an issue and ask you for help.

**Comment by jongwu** [comment]
Hi @singhwang -, What do you mean of that the arm64 host can support vCPU hotplug? The vCPU hotplug for linux/qemu is under development and is not supported in mainline. Do you mean you apply the RFC patch for vCPU hotplug in your host?

**Comment by singhwang** [comment]
@jongwu I also started to pay attention to the cpu hotplug feature after encountering this error report in kata, so I first doubted whether the host running the pod supports this feature, and to verify this feature, refer to this link https://www.cyberciti.biz/faq/ debian-rhel-centos-redhat-suse-hotplug-cpu/

**Comment by singhwang** [comment]
@jongwu Also, I didn't apply any additional patches, I used the existing patches in version 3.0.0

**Comment by singhwang** [comment]
@jongwu You mean, the feature for cpu hotplug on arm64 is still under development, currently the mainline version of kata does not support this on arm64 yet. That is to say, at present, in order to ensure that the pod can be created normally, I can only use the configuration static_sandbox_resource_mgmt = true to treat it as not supporting this feature. Is that right?

**Comment by jongwu** [comment]
@singhwang -, I mean vCPU hotplug depends on linux and qemu. Currently, both linux and qemu doesn't support vCPU hotplug. The change for support vCPU hotplug in kata is small. You should enable vCPU hotplug in linux/qemu first then apply it in kata. Otherwise, you can just using static resource management.

**Comment by singhwang** [comment]
@jongwu I got it, thanks for your help.
