### ISSUE TITLE
Two questions about how to monitor pods or containers created using kata

### ISSUE THREAD

**Issue by singhwang** [kata-containers/kata-containers#6079]
1. When sandbox_cgroup_only = true is set through the configuration file, although I cannot see the cgroups directory of the business container in the cgroups directory of the pod, I know that this is managed by the cgroups in the guest vm corresponding to the pod, but I can see a directory at the beginning of  " cri-containerd-", I want to know whether the monitoring information collected through this cgroups directory can represent the actual resource usage amount of the whole pod, or not, it is just the additional resource overhead of creating pods？
My current understanding is the latter.

2. How to monitor containers and pods created using kata? 

I have read the official documents for a long time, but after reading them, I still have doubts about the above two questions. Although there is an official introduction to the first question, but after reading it, I don’t feel very understanding.

**Comment by liubin** [comment]
For 1, you are right, also you may have read this https://github.com/kata-containers/kata-containers/blob/a67402cc1f07094d88ae6fa11cc6675df84d18f0/docs/design/host-cgroups.md#sandbox_cgroup_only--true.

For 2, besides CRI/OCI stats interface, Kata Containers also provides some additional metrics, you can read [this](https://github.com/kata-containers/kata-containers/blob/main/docs/design/kata-2-0-metrics.md).

**Comment by singhwang** [comment]
@liubin Thanks for your answer. I have read this document about kata providing additional metrics through kata monitor. The document does mention "Kata implements CRI's API and supports ContainerStats and ListContainerStats interfaces to expose containers metrics. User can use these interfaces to get basic metrics about containers .”. Now I want to know how to see the containers metrics exposed by the two interfaces ContainerStats and ListContainerStats. Is it possible to obtain this part of information by periodically requesting the kubelet on each node through the k8s metric server? Is there any other more simple and direct way to get it?

**Comment by singhwang** [comment]
@liubin I understand what you mean. Thank you for your help.

**Comment by singhwang** [comment]
@liubin At present, I can use shimV2API to obtain cgroups information in kata vm, but the blkio related information in this information has no value. This part of information is the main data used to generate disk IO monitoring indicators. Is there any good solution for this?
