### ISSUE TITLE
virtcontainers: should we add debug qmp(hmp) for qemu？

### ISSUE THREAD

**Issue by zhaojizhuang** [kata-containers/kata-containers#6092]
**Is your feature request related to a problem? Please describe.**

when I  debug spdk device, i want to see the pci bridge info and device info (such `num-queue` for blk device)。So I had to add an hmp interface for debugging.

**Describe the solution you'd like**

In debug mode, we can add another qmp(hmp) sockets, Convenient to debug qemu devices. such as follows:

```shell
/
/opt/kata/bin/qemu-system-x86_64 \
... ...
 -qmp unix:/run/vc/vm/69f4e854b11158cbb7e046625d7ba487d1c66c8754dbd699068fa08fa7f68bf7/qmp.sock,server=on,wait=off 
 -monitor unix:/run/vc/vm/69f4e854b11158cbb7e046625d7ba487d1c66c8754dbd699068fa08fa7f68bf7/hmp.sock
... ...
```

code like this:

```shell
# add hmp in govmm
func (config *Config) appendQMPSockets() {
 ...
                  // sockets address
                qmpParams := append([]string{}, fmt.Sprintf("%s:%s", q.Type, q.Name))

		if q.IsHmp {
			config.qemuParams = append(config.qemuParams, "-monitor")
		} else {
			config.qemuParams = append(config.qemuParams, "-qmp")
		}

              
		config.qemuParams = append(config.qemuParams, strings.Join(qmpParams, ","))
	}
}


```

**Comment by bergwolf** [comment]
As long as we have a config option for it defaulting to disabled, I'm fine with it ;) Care to send a PR?

**Comment by zhaojizhuang** [comment]
Ok, happy to create a PR later
