### ISSUE TITLE
Implement generic kernel module checks

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6132]
> **Note:**
>
> This issue is to ensure that a number of hardware-agnostic kernel modules are loaded (unlike the related, but Intel specific #5332).

Requirements for this issue:

- Ensure the `vhost` module is loaded or available.
- Ensure the `vhost_net` module is loaded or available.
- Ensure the `vhost_vsock` module is loaded or available.

This breaks down into the following sub-tasks:

- [ ] Rewrite [`RunningOnVMM()`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/hypervisor.go#L858) in rust.
- [ ] Rewrite [`checkKernelModules()`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cmd/kata-runtime/kata-check.go#L218) in rust.
- [ ] Move the agent's [`load_kernel_module()`](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L2002) function into [`src/libs/kata-sys-util`](https://github.com/kata-containers/kata-containers/tree/main/src/libs/kata-sys-util) so it can be used by the agent and `kata-ctl`.
- [ ] Rewrite [`haveKernelModule()`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cmd/kata-runtime/kata-check.go#L135) in rust (depends on `load_kernel_module()`).

## Notes

- The golang code will call `modprobe $module` if the command is running as `root`. We should consider **not** doing this by default even when running as `root` to avoid the command changing the system state. The command should fail gracefully with a clear message stating the admin should run `sudo modprobe $module` before re-running this command. However, we should provide a command-line option to allow the admin to get similar behaviour to the existing golang `kata-runtime check` (particularly for backwards compatibility - see #6090).

- All functions need unit tests (even if those tests simply check that, for example, attempting to `modprobe` a kernel module will fail if the user running the command is non-`root`). Again, care needs to be taken about actually calling `sudo modprobe $module` in a CI environment so we may need to have the code include some test-conditional logic:
  ```rust
     #[cfg(test)]
    // Report that "modprobe $module" *would* be run.

    #[cfg(not(test))]
    // Actually call "modprobe $module"
  ```

**Comment by cmaf** [comment]
This issue will be closed by https://github.com/kata-containers/kata-containers/pull/6800, making https://github.com/kata-containers/kata-containers/pull/6944
