### ISSUE TITLE
(CCv0) Kata agent should check the attestation agent exists before attempting to start it

### ISSUE THREAD

**Issue by mattarnoatibm** [kata-containers/kata-containers#6134]
**Which feature do you think can be improved?**

If `aa_kbc_param` are set in the kata agent config the kata agent should check that the attestation agent executable exists and can be executed before it attempts to launch the attestation agent process.

**How can it be improved?**

If `aa_kbc_params` is set in the kata agent's config the kata agent will attempt to launch the attestation agent. There is the cas where the machine running the kata agent can be mis-configured where the attestation agent binary is missing at the `/usr/local/bin/attestation-agent` path or isn't an executable file. In this case `Command::new(AA_PATH)... .spawn()?;` will immediately return an error. When the kata agent `pull_image` is re-called after this because the `attestation_agent_started` atomic boolean is set to true before `Self::init_attestation_agent()` is called the kata agent won't re-attempt to start the attestation agent, and it will follow the rest of the code path for pulling an image despite there being no running attestation agent process, and will fail the pull image wherever the kata agent needs to use the attestation agent; e.g., when fetching container registry auth from the attestation agent.

In the `init_attestation_agent` function.The kata agent should do a check that the attestation agent binary exists and is executable before it attempts to start it, display a clear error message if the attestation agent binary doesn't exist. It might also make sense if the attestation agent binary doesn't exists to set attestation_agent_started atomic boolean from true to false so future calls to the kata agent pull_image don't go into a scenario where the kata agent assumes the attestation agent is running but there is no attestation agent process to connect to when the kata agent image pull needs to use the attestation agent.

The error message returned when `init_attestation_agent` fails to start the attestation agent (`.spawn()` returns an error) is `Permission denied (os error 13)` with no information about what process (the attestation agent) was attempted to be started.

**Additional Information**

This issue is spun of a discussion we started in the cloud API adaptor project https://github.com/confidential-containers/cloud-api-adaptor/pull/405#discussion_r1044305380 about how to handle combinations of cases where the attestation agent binary is / isn't present in a peer pod image and the `aa_kbc_param` is set / unset in the peer pod image's kata agent's config.

**Comment by stevenhorsman** [comment]
As part of the sealed secrets work, during my review I asked the Intel team to look at this and I it should be resolved with the new logic that produces an error if the attestation-agent fails to launch:
https://github.com/kata-containers/kata-containers/blob/1ad87faaf4d3068569d99c270df640e41465c410/src/agent/src/main.rs#L406-L421
so this can be closed.
