### ISSUE TITLE
kata-runtime: kata-runtime iptables  failed 

### ISSUE THREAD

**Issue by zhaojizhuang** [kata-containers/kata-containers#6148]
# Get your issue reviewed faster

# Description of problem

```
Get "http://shim/iptables": dial unix /run/kata/ced833ca94ae8ac23100ee45b32ce39af47101ae0791b3f233f42d9e7f209eb8/shim-monitor.sock: connect: no such file or directory
```

# Reason

code: https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/shim_management.go#L319

`os.Stat("unix:///run/vc/sbs")` failed, should be `os.Stat("/run/vc/sbs")`

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with an explanation of what actually happened)

# Further information

(replace this text with any extra information you think might be useful)

**Comment by zhaojizhuang** [comment]
@Tim-0731-Hzt

**Comment by Tim-0731-Hzt** [comment]
Thanks for raising this, I will fix it
