### ISSUE TITLE
docker exec hang

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#6154]
Reported by Jim Carroll from Mirantis:

terminal 1:
```docker run --rm -it --name katatest --runtime io.containerd.kata.v2 alpine```
terminal 2:
```docker exec -it katatest /bin/sh```
everything seems fine.
Until I try to exit the exec session, at which point the following happens:
* the exec’d session hangs (tty is effectively frozen)
* the original docker run session exits
* docker ps shows that no containers are running

I have to kill the exec command still hung in terminal 2 to regain control of that lost soul

**Comment by liubin** [comment]
Should this be closed? @bergwolf

**Comment by neersighted** [comment]
Not until we merge the PR in Moby, in my opinion. It looks like GitHub has even set it up to auto-close.

**Comment by neersighted** [comment]
Looks like the auto-close doesn't work across orgs, despite the Web UI claiming so. Anyway, we've merged the fix for the Moby master branch, and the fix for 23.0 is in review for the next patch. I'd suggest this can be closed and those interested in the fixes can monitor the related PRs.

**Comment by bergwolf** [comment]
Thanks @neersighted ! Let's close this as https://github.com/moby/moby/pull/44892 has been merged.
