### ISSUE TITLE
Add hotplug_timeout support to rust agent

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#62]
When the following PR lands, we need to add support to the new rust agent:

- https://github.com/kata-containers/agent/pull/685

**Comment by awprice** [comment]
I'm happy to add this once https://github.com/kata-containers/kata-containers/issues/63 is completed.

**Comment by jodh-intel** [comment]
Thanks @awprice ! :smile:

**Comment by jodh-intel** [comment]
@awprice - #63 has now landed and I've raised https://github.com/kata-containers/tests/pull/2039 if you're still keen? :wink:
