### ISSUE TITLE
runtime-rs: can not run container with privileged option

### ISSUE THREAD

**Issue by YushuoEdge** [kata-containers/kata-containers#6250]
I have test nerdctl & ctr using runtime-rs + dragonball with "--privileged" option, it will report an error:
```
$ ctr run --privileged --rm --runtime io.containerd.kata.v2 docker.io/library/centos:latest test-container /bin/bash
ctr: failed to create shim task: Others("failed to handler message create container\n\nCaused by:\n    0: create\n    1: agent create container\n    2: rpc status: code: INTERNAL message: \"Creating container device LinuxDevice { path: \\\"/dev/full\\\", type: \\\"c\\\", major: 1, minor: 7, file_mode: Some(438), uid: Some(0), gid: Some(0) }\\n\\nCaused by:\\n    EEXIST: File exists\""): unknown
```

**Comment by lifupan** [comment]
Hi @YushuoEdge 

Had you read this https://github.com/containerd/containerd/pull/7328 thread. Can you follow this thread and have a try?

**Comment by YushuoEdge** [comment]
> Hi @YushuoEdge
> 
> Had you read this [containerd/containerd#7328](https://github.com/containerd/containerd/pull/7328) thread. Can you follow this thread and have a try?

It works! Thanks!

**Comment by zhongwen666** [comment]
@lifupan How can I resolve the above issue using the Docker CLI?
