### ISSUE TITLE
Typo in src/runtime-rs/crates/resource/src/cgroups/mod.rs

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#6256]
`ignor`

https://github.com/kata-containers/kata-containers/blob/86501d5f6f2ae3ad16e2f8630f7624386cb8ff0d/src/runtime-rs/crates/resource/src/cgroups/mod.rs#L117

**Comment by jodh-intel** [comment]
I'm going to grab this issue for our outreach students.

**Comment by predatorprasad** [comment]
If it is open
Can I get it assigned
I have found the typo..

**Comment by predatorprasad** [comment]
Could you please merge the pull request
