### ISSUE TITLE
kata-manager should run "kata-runtime check"

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6281]
After installing Kata, [`kata-manager`](https://github.com/kata-containers/kata-containers/blob/main/utils/kata-manager.sh) runs a [test to ensure it can create a Kata Container](https://github.com/kata-containers/kata-containers/blob/main/utils/kata-manager.sh#L659).

However, that can of course fail in mysterious ways. What that function _should_ do first is run `sudo kata-runtime check`. If the return code is zero, it can then proceed to trying to create a container, else it should exit 1 showing the output of `kata-runtime check`.

**Comment by jodh-intel** [comment]
All you need to do is add a line to the [`test_installation()`](https://github.com/kata-containers/kata-containers/blob/main/utils/kata-manager.sh#L659) function before the `sudo ctr run` line that calls:

```bash
sudo kata-runtime check -v
```

**Comment by jodh-intel** [comment]
Hi @tg5788re - this might be a good one for you to look at as a first PR?

**Comment by jodh-intel** [comment]
It'll need testing, but this should be enough:

```diff
diff --git a/utils/kata-manager.sh b/utils/kata-manager.sh
index 1cb65145f..802b636f1 100755
--- a/utils/kata-manager.sh
+++ b/utils/kata-manager.sh
@@ -660,6 +660,8 @@ test_installation()
 {
        info "Testing $kata_project\n"

+       sudo kata-runtime check -v
+
        local image="docker.io/library/busybox:latest"
        sudo ctr image pull "$image"
```

**Comment by predatorprasad** [comment]
**is this issue open to work upon?**
