### ISSUE TITLE
CCv0: Dynamic changes to ConfigMap/DownwardAPI/Secrets volumes are not propagated for remote hypervisor

### ISSUE THREAD

**Issue by bpradipt** [kata-containers/kata-containers#6341]
Kubernetes ConfigMap/DownwardAPI/Secrets volumes support dynamic updates of their contents.  The updated contents eventually propagates to a corresponding volume of the pod.

In the case of remote hypervisor, however, the contents of ConfigMap/DownwardAPI/Secrets are copied only once at pod creation time, and never copied again when they are updated.

This is because the current implementation only copies the volume contents once.
https://github.com/kata-containers/kata-containers/blob/b91337afef54d94e7f6458a0d1548e921dab6ea0/src/runtime/virtcontainers/fs_share_linux.go#L270

Ref: https://github.com/confidential-containers/cloud-api-adaptor/issues/574

**Comment by ariel-adam** [comment]
@bpradipt are the 2 merged PRs (above) covering this issue or there is still work to be done?

**Comment by stevenhorsman** [comment]
Fixes by #6342
