### ISSUE TITLE
k8s: cannot terminate pod when it has an EmptyDir volume

### ISSUE THREAD

**Issue by chavafg** [kata-containers/kata-containers#635]
# Description of problem
Pod cannot be terminated when it has an `EmptyDir` volume. 

`containerd-shim-kata-v2` and `qemu` processes are not terminated
This is affecting one integration test from our test suite, but also EmptyDir tests on k8s e2e conformance tests are affected. 

# Expected result

Pod should terminate correctly. All kata related processes should be terminated as well. 

# Actual result

Pod cannot be terminated and processes keep running. Pod stays in "Terminating" status unless we add `terminationGracePeriodSeconds: 0`, but anyway processes keep running. 

This can be reproduced using this pod spec: https://github.com/kata-containers/tests/blob/master/integration/kubernetes/runtimeclass_workloads/pod-empty-dir.yaml

```
fuentess@e2e-2:~/go/src/github.com/kata-containers/tests/kata-webhook$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY   STATUS        RESTARTS   AGE
default       pod-annotate-webhook-75d459588b-xwcvw   1/1     Running       0          4h7m
default       sharevol-kata                           1/1     Terminating   0          12m
```
I see `Invalid Argument` error appears in kata logs.

Kata Logs:
```
Aug 27 22:59:29 e2e-2 kata[104524]: time="2020-08-27T22:59:29.30692135Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=virtcontainers subsystem=sandbox
Aug 27 22:59:29 e2e-2 kata[104524]: time="2020-08-27T22:59:29.319951399Z" level=warning msg="failed to get OOM event from sandbox" error="rpc error: code = NotFound desc = /grpc.AgentService/GetOOMEvent is not supported" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=containerd-kata-shim-v2
Aug 27 22:59:30 e2e-2 kata[104524]: time="2020-08-27T22:59:30.100434457Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=virtcontainers subsystem=sandbox
Aug 27 23:00:31 e2e-2 kata[104524]: time="2020-08-27T23:00:31.318911857Z" level=warning msg="stop container failed" container=1e999bde94baf827ceca90d9cf8fd7e25c0300b7b267d5ae7a73c3235ff9945d error="rpc error: code = Internal desc = EINVAL: Invalid argument" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=containerd-kata-shim-v2
```

containerd log:
```
Aug 27 22:59:29 e2e-2 kata[104524]: time="2020-08-27T22:59:29.30692135Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=virtcontainers subsystem=sandbox
Aug 27 22:59:29 e2e-2 containerd[65067]: time="2020-08-27T22:59:29.306921350Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=virtcontainers subsystem=sandbox
Aug 27 22:59:29 e2e-2 containerd[65067]: time="2020-08-27T22:59:29.314302678Z" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:sharevol-kata,Uid:203a1ae4-6bc6-4304-a19e-c6f8db932594,Namespace:default,Attempt:0,} returns sandbox id \"e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291\""
Aug 27 22:59:29 e2e-2 kata[104524]: time="2020-08-27T22:59:29.319951399Z" level=warning msg="failed to get OOM event from sandbox" error="rpc error: code = NotFound desc = /grpc.AgentService/GetOOMEvent is not supported" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=containerd-kata-shim-v2
Aug 27 22:59:29 e2e-2 containerd[65067]: time="2020-08-27T22:59:29.319951399Z" level=warning msg="failed to get OOM event from sandbox" error="rpc error: code = NotFound desc = /grpc.AgentService/GetOOMEvent is not supported" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=containerd-kata-shim-v2
Aug 27 22:59:29 e2e-2 containerd[65067]: time="2020-08-27T22:59:29.534599213Z" level=info msg="CreateContainer within sandbox \"e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291\" for container &ContainerMetadata{Name:test,Attempt:0,}"
Aug 27 22:59:29 e2e-2 containerd[65067]: time="2020-08-27T22:59:29.952464097Z" level=info msg="CreateContainer within sandbox \"e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291\" for &ContainerMetadata{Name:test,Attempt:0,} returns container id \"1e999bde94baf827ceca90d9cf8fd7e25c0300b7b267d5ae7a73c3235ff9945d\""
Aug 27 22:59:30 e2e-2 kata[104524]: time="2020-08-27T22:59:30.100434457Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=virtcontainers subsystem=sandbox
Aug 27 22:59:30 e2e-2 containerd[65067]: time="2020-08-27T22:59:30.100434457Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=virtcontainers subsystem=sandbox
Aug 27 23:00:31 e2e-2 kata[104524]: time="2020-08-27T23:00:31.318911857Z" level=warning msg="stop container failed" container=1e999bde94baf827ceca90d9cf8fd7e25c0300b7b267d5ae7a73c3235ff9945d error="rpc error: code = Internal desc = EINVAL: Invalid argument" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=containerd-kata-shim-v2
Aug 27 23:00:31 e2e-2 containerd[65067]: time="2020-08-27T23:00:31.318911857Z" level=warning msg="stop container failed" container=1e999bde94baf827ceca90d9cf8fd7e25c0300b7b267d5ae7a73c3235ff9945d error="rpc error: code = Internal desc = EINVAL: Invalid argument" pid=104524 sandbox=e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291 source=containerd-kata-shim-v2
Aug 27 23:03:01 e2e-2 containerd[65067]: time="2020-08-27T23:03:01.301542623Z" level=info msg="StopPodSandbox for \"e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291\""
Aug 27 23:05:01 e2e-2 containerd[65067]: time="2020-08-27T23:05:01.301722960Z" level=error msg="StopPodSandbox for \"e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291\" failed" error="rpc error: code = DeadlineExceeded desc = failed to stop container \"1e999bde94baf827ceca90d9cf8fd7e25c0300b7b267d5ae7a73c3235ff9945d\": an error occurs during waiting for container \"1e999bde94baf827ceca90d9cf8fd7e25c0300b7b267d5ae7a73c3235ff9945d\" to be killed: wait container \"1e999bde94baf827ceca90d9cf8fd7e25c0300b7b267d5ae7a73c3235ff9945d\": context deadline exceeded"
Aug 27 23:07:31 e2e-2 containerd[65067]: time="2020-08-27T23:07:31.710112820Z" level=info msg="StopPodSandbox for \"e82ccff8d70198f9ec8259fd01da72c936154c6e748fc7c1b487517ecf0ef291\""
```

**Comment by 2qif49lt** [comment]
problem is still here

`lab@lab-System-Product-Name:~$ kubectl get pods -n scr -o wide
NAME                                                 READY   STATUS        RESTARTS   AGE     IP             NODE           NOMINATED NODE   READINESS GATES
cybertron-apollo-5-5995b5849-sw9j2                   0/2     Terminating   2          7h50m   10.244.2.132   ivt-cloud-1u   <none>           <none>
cybertron-apollo-5-69db4fb775-6x8lw                  1/2     Terminating   0          34m     10.244.2.161   ivt-cloud-1u   <none>           <none>
....`

`
$ sudo journalctl -t containerd -r
-- Logs begin at 三 2020-10-14 06:02:42 CST, end at 一 2020-12-07 17:36:42 CST. --
12月 07 17:35:54 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:35:54.057115597+08:00" level=info msg="Kill container \"6ab63e9c8d124b813980d1085d6d13498eb585607b53443b850c9fd016217591\""
12月 07 17:35:36 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:35:36.103523145+08:00" level=error msg="Failed to handle backOff event &TaskExit{ContainerID:6ab63e9c8d124b813980d1085d6d13498eb585607b53443b850c9fd016217591,ID:6ab63e9c8d124b813980d1085d6d13498eb58
12月 07 17:35:35 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:35:35.929773820+08:00" level=info msg="TaskExit event &TaskExit{ContainerID:6ab63e9c8d124b813980d1085d6d13498eb585607b53443b850c9fd016217591,ID:6ab63e9c8d124b813980d1085d6d13498eb585607b53443b850c9f
12月 07 17:35:24 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:35:24.056934370+08:00" level=info msg="Events for \"6ab63e9c8d124b813980d1085d6d13498eb585607b53443b850c9fd016217591\" is in backoff, enqueue event &TaskExit{ContainerID:6ab63e9c8d124b813980d1085d6d
12月 07 17:35:24 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:35:24.056428258+08:00" level=info msg="Stop container \"6ab63e9c8d124b813980d1085d6d13498eb585607b53443b850c9fd016217591\" with signal terminated"
12月 07 17:35:24 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:35:24.055697226+08:00" level=info msg="StopContainer for \"6ab63e9c8d124b813980d1085d6d13498eb585607b53443b850c9fd016217591\" with timeout 30 (s)"
12月 07 17:34:55 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:34:55.691709360+08:00" level=info msg="Kill container \"f597fa4164fb6d68320155cadef823758a4ca222ddb6a347534e4f334b960e46\""
12月 07 17:34:55 ivt-cloud-1u containerd[13583]: time="2020-12-07T17:34:55.657797757+08:00" level=info msg="Kill container \"9172d6f6d38fb28631a7e91001b84680de1b7cec63fb2cd55ec366f7de7fbf4b\""

`

`$ sudo journalctl -t kata -r
-- Logs begin at 三 2020-10-14 06:02:42 CST, end at 一 2020-12-07 17:37:43 CST. --
12月 07 17:28:29 ivt-cloud-1u kata[46647]: time="2020-12-07T17:28:29.726951056+08:00" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" ID=eedd043f038de31dacf018278251a64ebecf5879ad8bd8d625b0684edebb281c sandbox=eedd043f038de31dacf018278251a
12月 07 17:28:29 ivt-cloud-1u kata[46647]: time="2020-12-07T17:28:29.717482706+08:00" level=warning msg="Could not remove container share dir" ID=eedd043f038de31dacf018278251a64ebecf5879ad8bd8d625b0684edebb281c error="no such file or directory" sandbox=eedd043f038de3
12月 07 17:27:21 ivt-cloud-1u kata[46710]: time="2020-12-07T17:27:21.862744935+08:00" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" ID=a41c7e8d17c69e29edb2edfceec3ac3de59b259d91b83ae5dee8f20e88cbb42a sandbox=a41c7e8d17c69e29edb2edfceec3a
12月 07 17:27:21 ivt-cloud-1u kata[46927]: time="2020-12-07T17:27:21.812974182+08:00" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" ID=07c63e0cc44f5c6543dec6318770751d9680b8c389fce601908b21c9dcb6a9aa sandbox=07c63e0cc44f5c6543dec63187707
`
