### ISSUE TITLE
Move cpu info functions to kata-sys-utils

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6383]
## Background

[`kata-ctl`](https://github.com/kata-containers/kata-containers/tree/main/src/tools/kata-ctl) provides a few functions that handle CPU flags:

- [`get_single_cpu_info`](https://github.com/kata-containers/kata-containers/blob/main/src/tools/kata-ctl/src/check.rs#L46)
- [`get_cpu_flags`](https://github.com/kata-containers/kata-containers/blob/main/src/tools/kata-ctl/src/check.rs#LL66C8-L66C21)

## Use cases

It would be useful for the [CH integration work](https://github.com/kata-containers/kata-containers/issues/6263) if these functions were available in [`kata-sys-util`](https://github.com/kata-containers/kata-containers/tree/main/src/libs/kata-sys-util/src) (maybe in a new  `cpu.rs` file).

Also, it would be useful to add some more utility functions so that the consumer could make a single call that would return all flags in the file and then provide a way to check quickly if a flag exists in the returned list. Something like (but not necessarily identical to the following):

```rust
let cpu_flags_list: Vec<String> = get_cpu_flags_vec();

if cpu_flags_list.contains("foo_flag".to_string()) {
    // ...
}

// Or to avoid converting the arg to a string:
if cpu_flags_list.iter().any(|v| v == "foo_flag")) {
    // ...
}
```

Hence...

## Tasks

- [ ] Move cpu info functions from `kata-ctl` to `kata-sys-util` crate.
- [ ] Add a few extra utility functions to make common usage simpler.

**Comment by jodh-intel** [comment]
I've just realised this is very similar to #6257.

/cc @amshinde.

**Comment by Christopher-C-Robinson** [comment]
Interested in this one.

**Comment by nathanwhyte** [comment]
@Christopher-C-Robinson, are you still working on this issue?

I'm taking a course on Virtualization at UT and we've been assigned to contribute to open-source virtualization projects. This issue matches one of the project requirements, so if it's still available could I have a go at resolving the issue?

**Comment by Christopher-C-Robinson** [comment]
Sorry for the late reply. You can take the issue.
