### ISSUE TITLE
network: endpoint hotplug (post-vmm boot) breaks QEMU on aarch64 and Firecracker on x86_64 and aarch64   

### ISSUE THREAD

**Issue by ananos** [kata-containers/kata-containers#6384]
on stable-3.1, we are facing an issue on FC sandboxes regarding networking:

```
# uname -a
Linux hostname 5.10.104-nbfc #4 SMP PREEMPT Mon Feb 13 16:42:13 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
# containerd --version
containerd github.com/containerd/containerd v1.7.0-beta.3 b8962099e7ce533cc62e540ec25f6d1d93e35a0b
# /opt/kata/bin/containerd-shim-kata-v2 --version
Kata Containers containerd shim (Golang): id: "io.containerd.kata.v2", version: 3.1.0-rc0, commit: 4a35d5fa6ea083837670e295370b42d43452374f

### ctr does not add a network endpoint
# ctr run --snapshotter devmapper --runtime io.containerd.run.kata-fc.v2 -t --rm docker.io/library/ubuntu:latest ubuntu-kata-test uname -a
Linux localhost 5.15.26 #2 SMP Mon Feb 13 15:15:16 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux

### nerdctl does add a network endpoint
# nerdctl run --snapshotter devmapper --runtime io.containerd.run.kata-fc.v2 -it --rm ubuntu:latest uname -a
FATA[0000] failed to create shim task: Could not hot add device: unsupported device: &{virtual  {{{2 1500 0 eth0 6e:fe:dd:74:34:aa up|broadcast|multicast 69699 300 0 <nil>  0x4000022180 0 0 1 0x4000128be8 ether <nil> up 0 0 1 1 65536 65535 [] 0 <nil>} veth} {[]  [] []} 0x4000116420 [10.4.0.48/24 eth0 fe80::6cfe:ddff:fe74:34aa/64] [{Ifindex: 2 Dst: <nil> Src: <nil> Gw: 10.4.0.1 Flags: [] Table: 254 Realm: 0} {Ifindex: 2 Dst: 10.4.0.0/24 Src: 10.4.0.48 Gw: <nil> Flags: [] Table: 254 Realm: 0} {Ifindex: 2 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254 Realm: 0}] [{2 10 64 5 0 0 ff02::16 33:33:00:00:00:16 <nil> 0 0 0} {2 10 64 5 0 0 ff02::2 33:33:00:00:00:02 <nil> 0 0 0}]} {{01df6554-fcf7-4da0-b486-7ef1f3d0aff1 br0_kata {tap0_kata 6e:fe:dd:74:34:aa []} [0x400012e0b8] []} {eth0 0a:51:e7:44:ee:9c []} 2} false false}, type: 2: unknown 
```

This is somehow expected on both `x86_64` and `aarch64`, as FC does not support hotplugging the ethernet device post boot. However, the same issue happens with QEMU on `aarch64`:

```
# ctr run --runtime io.containerd.run.kata-qemu.v2 -t --rm docker.io/library/ubuntu:latest ubuntu-kata-test uname -a
Linux localhost 5.15.26 #2 SMP Mon Feb 13 15:15:16 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux

# nerdctl run --runtime io.containerd.run.kata-qemu.v2 -it --rm ubuntu:latest /bin/bash 
FATA[0000] failed to create shim task: QMP command failed: Bus 'pci-bridge-0' does not support hotplugging: unknown 
```

This issue does not happen on stable-3.0:

```
# /opt/kata/bin/containerd-shim-kata-v2 --version
Kata Containers containerd shim: id: "io.containerd.kata.v2", version: 3.0.2, commit: 35b32156ade9ede7ffdfade7bd0c461a483bf101

### QEMU works

# ctr run --runtime io.containerd.run.kata-qemu.v2 -t --rm docker.io/library/ubuntu:latest ubuntu-kata-test uname -a
Linux localhost 5.15.26 #2 SMP Mon Feb 13 15:15:16 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux

# nerdctl run --runtime io.containerd.run.kata-qemu.v2 -it --rm ubuntu:latest uname -a
Linux c3d80a4e63a9 5.15.26 #2 SMP Mon Feb 13 15:15:16 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux

### FC works
# ctr run --snapshotter devmapper --runtime io.containerd.run.kata-fc.v2 -t --rm docker.io/library/ubuntu:latest ubuntu-kata-test uname -a
Linux localhost 5.15.26 #2 SMP Mon Feb 13 15:15:16 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux

# nerdctl run --snapshotter devmapper --runtime io.containerd.run.kata-fc.v2 -it --rm ubuntu:latest uname -a
Linux a8e3c38cf86c 5.15.26 #2 SMP Mon Feb 13 15:15:16 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux
```

We got a hint (@fidencio) that some work on hooks (#5972) might be related, so @bergwolf if you could shed any light on what we could do to resolve this that would be great!

**Comment by ananos** [comment]
a quick update -- this actually breaks the nerdctl invocation, not a k8s invocation. So, presumably kata-fc would not work in docker/nerdctl but it still works on k8s. 

So there must be a set of annotations that nerdctl/docker sets that k8s ignores ?

**Comment by bergwolf** [comment]
@ananos The issue is that there are different expectations on when the OCI `preStart`/`createRuntime` hooks are executed.
* FC expects them to run **before** VM is created as it does not support device hotplug
* docker expect them to run **after** VM is created as it needs the hypervisor pid to find out the container netns

nerdctl, OTOH, does not really care about when they are executed.

So to make things work as much as possible, I think we can:
1. make sure `prestart`/`createRuntime` hooks are executed before starting new VMs.
2. make sure docker + FC combination fail gracefully.

Then we can have both nerdctl + kata + FC/QEMU and docker + kata + QEMU working, while docker + kata + FC would fail until either FC adds network device hotplug, or docker stops depending on host pid to find out the container netns.

@ananos what about adding an option to the FC config to indicate that it does not support device hotplug? Then we can use that option to instruct the runtime to prepare all necessary devices before starting new VMs. wdyt?

**Comment by ananos** [comment]
thanks @bergwolf for the detailed explanation. 

Sounds good to me -- a minor concern/question is whether this could be also related to QEMU (as it seems on the aarch64 setup we have the same issue). As I'm not familiar with the QEMU device support matrix, if someone could shed some light there, that would be great!

This only refers to whether we should add a 2nd dimension (hotplug supported on a specific arch). Otherwise, adding an option for FC would be the way to go I think.

thanks!
