### ISSUE TITLE
Add logs vport config option to rust agent

### ISSUE THREAD

**Issue by devimc** [kata-containers/kata-containers#64]
Add support for log_vport option in rust lang agent.

See: https://github.com/kata-containers/agent/pull/653

**Comment by jodh-intel** [comment]
Thanks @devimc - you might want to wait until https://github.com/alipay/kata-rust-agent/pull/36 lands as it creates the config module.

**Comment by jodh-intel** [comment]
That dependent PR has now landed (as https://github.com/kata-containers/kata-containers/pull/65).

**Comment by lifupan** [comment]
Fixed by this https://github.com/kata-containers/kata-containers/pull/132
