### ISSUE TITLE
ctr: failed to create shim task: exitting QMP loop, command cancelled: unknown

### ISSUE THREAD

**Issue by XiangyiXuWashU** [kata-containers/kata-containers#6421]
Hi: I create and build rootfs image with sudo -E AGENT_INIT=no USE_DOCKER=yes SECCOMP=no ./rootfs.sh "ubuntu" in arm64. But when I launch container from containerd, I get the error info: "ctr: failed to create shim task: exitting QMP loop, command cancelled: unknown." Could anyone tell me the possible causes of "exitting QMP loop". Thanks!

**Comment by ananos** [comment]
two things:

- first it's `nvdimm` with the following error:
```
# nerdctl run --runtime io.containerd.run.kata-qemu.v2 -it --rm ubuntu:latest uname -a
FATA[0000] failed to create shim task: exitting QMP loop, command cancelled: unknown 
```

uncomment this line in configuration-qemu.toml: 
`disable_image_nvdimm = true`

- then it's the network hotplugging issue with the following error: 
```
# nerdctl run --runtime io.containerd.run.kata-qemu.v2 -it --rm ubuntu:latest uname -a
FATA[0000] failed to create shim task: QMP command failed: Bus 'pci-bridge-0' does not support hotplugging: unknown 
```

which only appears in `stable-3.1` onwards (already opened an issue for that: #6384)

going to `stable-3.0` and uncommenting the above line in `configuration-qemu.toml` allows us to boot a qemu sandboxed container on aarch64 (with network).

```
# nerdctl run --runtime io.containerd.run.kata-qemu.v2 -it --rm ubuntu:latest uname -a
Linux 6b7fd599534e 5.15.26 #1 SMP Tue Feb 28 18:49:51 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by XiangyiXuWashU** [comment]
It works! Thanks!
