### ISSUE TITLE
runtime-rs: ch: Implement minimal thread/tid/pid handling

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6438]
Implement the following methods in https://github.com/kata-containers/kata-containers/blob/main/src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs:

- `get_thread_ids()`
- `get_pids()`
- ~`get_vmm_master_tid()`~ (already done)

Seemingly related: #6429

**Comment by joannejchen** [comment]
Hi @jodh-intel! @scotran and I are part of a Virtualization course at UT Austin, and as part of a project we have to contribute to open source repositories. Can we take up this issue? If so, where can we look for resources/more information on intended behavior?

**Comment by jodh-intel** [comment]
Hi @joannejchen - That would be great! I am actually out for a week now, but what you'll need to do is:

- [Install Kata](https://github.com/kata-containers/kata-containers/tree/main/docs/install)
  For development/test purposes only, the simplest way to do that is using the "automatic" method as it's a "one liner":
  
  - https://github.com/kata-containers/kata-containers/blob/main/utils/README.md#to-install-kata-containers-and-containerd
 
- Change the default [configuration](https://github.com/kata-containers/kata-containers/#configuration) to use Cloud Hypervisor (rather than the default QEMU [hypervisor](https://github.com/kata-containers/kata-containers/blob/main/docs/hypervisors.md)):
  ```bash
  $ sudo mkdir -p /etc/kata-containers/
  $ sudo cp /opt/kata/share/defaults/kata-containers/configuration-clh.toml /etc/kata-containers/configuration.toml
  ```
- Enable the [Cloud Hypervisor feature](https://github.com/kata-containers/kata-containers/pull/6201#issuecomment-1413690515) - you just need to change one `Cargo.toml` file as described in the link.

- Build the new rust runtime with that feature enabled
  ```bash
  $ git clone https://github.com/kata-containers/kata-containers
  $ cd kata-containers/src/runtime-rs
  $ make && sudo make install
  ```

- Ensure the version of the runtime you just built is found in the `$PATH` variable first:
  ```bash
  $ which containerd-shim-kata-v2
  /usr/local/bin/containerd-shim-kata-v2
  ```
- Restart containerd to pick up the new runtime version:
  ```bash
  $ sudo systemctl restart containerd
  ```
- Create a new Kata container and start hacking ;)

@amshinde should be able to help you setup the Kata environment I've describe above with the Cloud Hypervisor feature enabled.

@YushuoEdge can also help explain what is required for the actual task of implementing the thread/tid/pid handling in the net namespace.

> **Notes:**
>
> - You'll want to enable [full debug](https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#enable-full-debug) and [containerd debug too (**essential**)](https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#enabling-full-containerd-debug).
> - Since the configuration syntax has changed slightly recently (https://github.com/kata-containers/kata-containers/pull/5959, https://github.com/kata-containers/kata-containers/issues/5954, https://github.com/kata-containers/kata-containers/issues/6020), here's a copy of the config file that should work
>   with runtime-rs with the Cloud Hypervisor feature enabled: https://gist.github.com/jodh-intel/0aa92f1c9145feed2103798b43122976

**Comment by jodh-intel** [comment]
@joannejchen - I'm assuming you didn't get a chance to look at this, so I'm going to grab it :smile:
