### ISSUE TITLE
CC | rootfs: Update pause image version?

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#6461]
In CC we are currently embedding version 3.6 of pause from `k8s.gcr.io/pause`: https://github.com/kata-containers/kata-containers/blob/c9d6b46ea0923672a89e85a01e0d380249e3993f/versions.yaml#L258-L261
Kubernetes have [announced](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/), that
> On Monday, March 20th, the k8s.gcr.io registry [will be redirected to the community owned registry](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/), registry.k8s.io
I wonder if we should update the location we get pause from and also consider pulling a newer version of pause at the same time?

**Comment by c3d** [comment]
Sounds like a good idea to me.
