### ISSUE TITLE
Provide cached components for different architectures

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#6487]
I've worked on caching the components that will be part of the CI, but I've focused on caching x86_64 components, which can be seen here: http://jenkins.katacontainers.io/view/Cached%20jobs/ (all the `kata-containers-main-` jobs).

It'd be nice if folks working on different architectures could also add the support to cache the arftefacts they're using so we can speed up the CI time for the whole CI.

/cc @jongwu @BbolroC @Amulyam24

**Comment by fidencio** [comment]
I've added jobs for aarch64 and s390x.

@Amulyam24, as I'm not familiar at all with power, could you follow the examples in http://jenkins.katacontainers.io/view/Cached%20jobs/ and add the jobs accordingly?

My understand is that for Power we'd only be caching:
* kernel
* rootfs-initrd
* rootfs-image
* shim-v2

QEMU is being built from sources, and virtiofsd is the one coming from QEMU (at least AFAIR).

**Comment by jongwu** [comment]
Thanks @fidencio -, I'll TAL

**Comment by Amulyam24** [comment]
> @Amulyam24, as I'm not familiar at all with power, could you follow the examples in http://jenkins.katacontainers.io/view/Cached%20jobs/ and add the jobs accordingly?
> 
> My understand is that for Power we'd only be caching:
> 
> * kernel
> * rootfs-initrd
> * rootfs-image
> * shim-v2
> 
> QEMU is being built from sources, and virtiofsd is the one coming from QEMU (at least AFAIR).

Hi @fidencio, that's right. I'll take a look at it and add the jobs accordingly. Thanks!

**Comment by BbolroC** [comment]
@Amulyam24 I've finished s390x's. Feel free to reach me if you need any help. 😉

**Comment by Amulyam24** [comment]
> @Amulyam24 I've finished s390x's. Feel free to reach me if you need any help. 😉

Sure @BbolroC, Thank you very much! :)

**Comment by Amulyam24** [comment]
Hi @fidencio, I have created the required cached jobs for ppc64le.
One question, how can I add them to appear under the list of cached builds filter?

**Comment by fidencio** [comment]
Closing as this has been done.
