### ISSUE TITLE
snp: add snp artifacts for osbuilder (main)

### ISSUE THREAD

**Issue by ryansavino** [kata-containers/kata-containers#6575]
@Alex-Carter01 @fitzthum

SNP base PRs mentioned at the start of the meeting:
qemu: https://github.com/kata-containers/kata-containers/pull/6062
ovmf: https://github.com/kata-containers/kata-containers/pull/5850
config: https://github.com/kata-containers/kata-containers/pull/6135

**Comment by Alex-Carter01** [comment]
these have also been all merged into CCv0 now, in case that simplifies getting them into main

**Comment by fidencio** [comment]
I am assuming this one was covered by the PRs that got merged from @fitzthum and @UnmeshDeodhar, and based on that I'm closing the issue. If this is not the case, please, just re-open it and sorry for the noise.
