### ISSUE TITLE
CI | GHA | Also test dragonball as part of the k8s tests

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#6583]
Currently our k8s tests are testing Cloud Hypervisor and QEMU.

Dragonball should also be supported, and in order to add such support the only needed bits are adding `dragonball` to:
* https://github.com/kata-containers/kata-containers/blob/60c62c3b69a2e2a43fd2ad94aee21bdb5645990f/.github/workflows/run-k8s-tests-on-aks.yaml#L15
* https://github.com/kata-containers/kata-containers/blob/60c62c3b69a2e2a43fd2ad94aee21bdb5645990f/.github/workflows/run-k8s-tests-on-aks.yaml#L27
* https://github.com/kata-containers/kata-containers/blob/60c62c3b69a2e2a43fd2ad94aee21bdb5645990f/.github/workflows/run-k8s-tests-on-aks.yaml#L79

It's expected that the owner of this issue will open an issue for each test that is not passing, as done for QEMU and Cloud Hypervisor.

**Comment by fidencio** [comment]
@studychao, let me start on this one Tomorrow, and I'll bother you for a review.

**Comment by studychao** [comment]
> @studychao, let me start on this one Tomorrow, and I'll bother you for a review.

My pleasure.
