### ISSUE TITLE
How to start multiple containeres in the same VM

### ISSUE THREAD

**Issue by XiangyiXuWashU** [kata-containers/kata-containers#6626]
Hi:
Anybody tell me how to start another container in the same VM which is launched by QEMU? Current, I am using containerd with command "ctr run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/ubuntu:focal hello sh".  How to launch another one in same VM by containerd? Thanks!

**Comment by fengwang666** [comment]
@XiangyiXuWashU Unfortunately `ctr` doesn't support that. However, you can use `crictl` instead. Please take a look at this page: https://github.com/kata-containers/kata-containers/blob/65670e6b0a24f10a1906b02e5a0deca7a904d011/docs/how-to/run-kata-with-crictl.md
