### ISSUE TITLE
CC | Roadmap to support `cosign` signature verification for `s390x`

### ISSUE THREAD

**Issue by Xynnn007** [kata-containers/kata-containers#6635]
**Which feature do you think can be improved?**

Support `cosign` image signature verification for `s390x`.

This will also help kata-agent stack to have two build ways, s.t.
- `openssl` or `native`: all crypto suites are based on `openssl` rather than `ring`. In this way `s390x` and some specific arch can be supported.
- `rust`, `rustls` or `ring`: all crypto suites are based on purely rust, sometimes including `ring` but indenpendent from `openssl`. When `ring` is involved, kata-agent can not be built on `s390x`.

**Roadmaps**

- https://github.com/confidential-containers/ocicrypt-rs/issues/61
- https://github.com/confidential-containers/image-rs/issues/134
- https://github.com/kata-containers/tests/issues/5620
- https://github.com/kata-containers/kata-containers/pull/6847

**Comment by Xynnn007** [comment]
Related issue: https://github.com/kata-containers/kata-containers/issues/5582

**Comment by stevenhorsman** [comment]
FYI @Xynnn007 - we have the tests PR (https://github.com/kata-containers/tests/pull/5640) and matching image-rs bump (https://github.com/kata-containers/kata-containers/pull/6847) ready now if you would like to review them. Thanks!

**Comment by stevenhorsman** [comment]
#6847 has merged and all the other tasks closed, so I think this is ready to close now.
