### ISSUE TITLE
Kata Containers streaming IO 

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#6714]
Right now, we forward container io stream (stdin/stdout/stderr) wrapped with ttrpc request, which adds unnecessary overhead and is error-prone. We have been fighting with missing stdin/stdout bytes from time to time since the beginning of the project.

To solve it once and for all, let's add a streaming IO interface between runtime and agent, using vsock connections as the underlying data transfer channel. It can remove the runtime shim and the agent from container IO data path.

For example, for container stdio, we can go from
```
containerd pipefd <-> kata runtime shim <-> vmm <-> kata agent <-> container stdio pipefd
```
to
```
containerd pipefd <-> vmm <-> container stdio pipefd
```

Key change:
* a new fd based vsock backend implementation, which forwards whatever data between the guest vsock device and the host fd
* a new streaming IO agent API that helps to setup the fd connection between guest and host
* runtime-rs/kata-agent change to help setup the fd mapping between guest and host 
* support container stdio with the streaming IO API
* (possibly) portforward with the streaming IO API

**Comment by ClSlaid** [comment]
Anyone taking on this?

**Comment by bergwolf** [comment]
@ClSlaid Yes. It has been assigned to a student in CCF summer of code.
