### ISSUE TITLE
Direct cross-container shared-mount support

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#6715]
Some workloads need a sidecar to mount some storage and share it with the application container.

Currently, there are some drawbacks:
* mount operation inside the sidecar requires SYS_ADMIN privilege. We need to support mount w/o root access.
* to share a mount between containers, we have to set up shared bind mounts between containers and the host. We need a way to share mounts w/o polluting the rootns mount namespace.

To address these drawbacks, we can add userns support in the guest/kata-agent to enable mount w/o root access for containers, and use the new linux kernel mount API (`open_tree()`/`move_mount()`) to set up bind mounts between containers, w/o polluting the guest rootns mount namespace.

Key change:
* agent: support container userns inside the guest
* agent: use open_tree()/move_mount() to set up bind mounts between containers directly 
* runtime-rs: support declaration of shared mounts between containers

**Comment by changweige** [comment]
This is a handy feature for serverless products since customers may pack their fuse storage clients as a sidecar container where the users want to mount file systems alone.  Expecting this 👍

**Comment by h56983577** [comment]
I'm working on it. ^_^
