### ISSUE TITLE
gha: consolidate the CI workflows for TDX, SEV and SNP.

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#6760]
**Which feature do you think can be improved?**

The github CI workflows for TDX, SEV and SNP. 

**How can it be improved?**

They can be consolidated into a single yaml file as described in https://github.com/kata-containers/kata-containers/pull/6712#discussion_r1179516764 so that we remove duplicated code.

Cc @fidencio @ryansavino

**Comment by fidencio** [comment]
https://github.com/kata-containers/kata-containers/pull/6712#discussion_r1182375126
