### ISSUE TITLE
Stop packaging a snap

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6769]
## Intro: Snap build

We currently provide a snap packaged build of Kata:

- https://github.com/kata-containers/kata-containers/tree/main/docs/install#snap-installation
- https://snapcraft.io/kata-containers
- https://github.com/kata-containers/kata-containers/tree/main/snap

## Problem: it broke

However, it appears the snap build broke some time back and we did not get notified of this, so the latest snap version of Kata Containers is 2.4.2, but the _actual_ latest release of Kata is [3.1.0](https://github.com/kata-containers/kata-containers/releases/tag/3.1.0).

## Solution?

We could just fix the snap issue and move on.

However, we seem to be having periodic snap breakages caused by api changes, system issues, tokens expiring, bugs, _etc_. Debugging such failures has historically consumed a lot of time. In summary, the ongoing maintenance cost is too high for those currently involved with the snap.

### Drop Kata Containers snap packaging

We could just stop packaging for snap.

+ve:

+ Saves us time.
+ Simplifies our [range of installation offerings](https://github.com/kata-containers/kata-containers/tree/main/docs/install).

-ve:

- Limits the range of installation offerings.
- Forces existing snap users to move to an alternative installation method.

### Ask the community to take ownership of the snap build

This is a potentially preferable choice, _iff_ a community member volunteers.

## Concerns

- If we decide to drop the snap build, how can we notify all the users? Is there a way to forcibly deprecate a snap and somehow alert affected users?

- The snap users are already using an old version of Kata (but possibly believing that they are running the latest version).

/cc @kata-containers/architecture-committee.

**Comment by fidencio** [comment]
During the AC meeting we've discussed this issue, and we came to conclusion that as it's already been raised last year and considering we don't actually have someone to maintain snap, nor tests actually running Kata Containers with snap, the best we can do for now is to drop it.

If someone from the community steps up to maintain those, then we'll revisit the idea.  However, for now we should drop it.

**Comment by jodh-intel** [comment]
I don't see a way to notify all snap users using the snapstore so, how about we do the following:

## Notification (now)

- Send a mail to the Kata mailing list saying:
  - The snap build is no longer being maintained.
  - The existing snap is old so all user should immediately switch to an [alternative installation method] 
    (https://github.com/kata-containers/kata-containers/tree/main/docs/install).
  - Kata would like a volunteer to take over maintenance of the snap. If no volunteer comes forward within **three weeks**, we'll proceed to delete all the snap code and docs.

- Update https://snapcraft.io/kata-containers to show that the snap is no longer being maintained, with a link back to this issue.

 > **Note:** I've done this now, although it appears the site takes time to be regenerated...?!?

## Mark snap as unmaintained in all docs (now)

- Raise a PR to update all the docs to say that the snap build is now unmaintained and that all users should use an alternative installation method.

  ```
  README.md
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
  docs/install/snap-installation-guide.md
  ```


## If no volunteer comes forward (3 weeks after the notification mail)

- Raise a PR to delete the snap code from the main repo:

  ```
  .github/workflows/snap.yaml
  .github/workflows/snap-release.yaml
  docs/install/snap-installation-guide.md
  docs/install/README.md     # Update to remove snap.
  snap/*
  tools/packaging/Makefile    # Just remove the snap parts ;)
  ```

- Raise a PR to delete the snap code from the tests repo:

  https://github.com/kata-containers/tests/blob/main/.ci/jenkins_job_build.sh

- Send another mail to the mailing list telling them the snap build has now been removed entirely.

**Comment by jodh-intel** [comment]
> Update https://snapcraft.io/kata-containers to show that the snap is no longer being maintained, with a link back to this issue.
> > Note: I've done this now, although it appears the site takes time to be regenerated...?!?

Yep - it's just slow, but it's now been applied.

**Comment by jodh-intel** [comment]
Ok. We'll start executing the plan above to remove the snap build entirely.

If, however, anyone out there has snap skills and wants to volunteer to maintain the Kata Containers snap (and you have the time to resolve the current issues), please let us know here as soon as possible ... if not sooner! :smile:

**Comment by jodh-intel** [comment]
Message sent to Kata mailing list and plan above updated to reflect that:

- https://lists.katacontainers.io/pipermail/kata-dev/2023-May/002625.html

**Comment by jodh-intel** [comment]
Assuming #6794 lands today, let's wait until 31st May before raising a PR to remove the snap docs and code entirely.

**Comment by popey** [comment]
Sorry to "necro" (as the youth say) an old closed bug. I noticed that the very last step of "delete the snap" hasn't been done.

It might be just as quick for someone to log into the store and mark it as "private" or, at the very least, "unlisted". If you're really keen, you could publish an empty snap under that name, or just ask on the [forum](https://forum.snapcraft.io/c/store-requests/19) to have it deleted.

Because right now it's still installable (even with the big shouty warning) and has a ton of potential vulnerabilities.

🙏

**Comment by stevenhorsman** [comment]
@ananos - Did you still have interest in reviving the snap installation, or did the microk8s support in kata-deploy suffice?
