### ISSUE TITLE
Where to download kata static-3.1.0-arm64.tar.xz or aarch and How to integrate firecracker into kata runtime

### ISSUE THREAD

**Issue by weiqiangxu** [kata-containers/kata-containers#6776]
**Before raising this question**

Have you looked at our [document](https://github.com/kata-containers/kata-containers/tree/main/docs) and still haven't found the answer?

yes

**Comment by fidencio** [comment]
We're not yet shipping non-x86_64 binaries as part of our releases yet.  This is an on-going work that has several layers which must be solved together, and thanks to @jongwu and @singhwang work, we're closer to that.

My expectation is that the next minor release (3.2.0, which will happen in a few months) will have support to publish multi-arch binaries.

**Comment by weiqiangxu** [comment]
没有提供amd64的kata-container的包，在集成firecracker的时候非常困难

**Comment by fidencio** [comment]
> There is no kata-container package for amd64, it is very difficult to integrate firecracker

Yep, We understand that, and that's the reason we're working on getting it solved.

**Comment by weiqiangxu** [comment]
> > There is no kata-container package for amd64, it is very difficult to integrate firecracker
> 
> Yep, We understand that, and that's the reason we're working on getting it solved.

请问我要怎么样可以编译出来 [kata-static-3.1.1-x86_64.tar.xz] 的 arm64版本呢，比如 kata-static-3.1.1-arm64.tar.xz

有指引文档么，非常感谢

**Comment by jongwu** [comment]
If you have arm64 server, it's easy to do. Just "make kata-tarball" in the home dir of kata repo.

If not, you need to cross build it. The patch is under review, but you can have a try. See https://github.com/kata-containers/kata-containers/pull/6586 or clone https://github.com/jongwu/kata-containers/tree/cross_build and try "CROSS_BUILD=true TARGET_ARCH=aarch64 ARCH=aarch64 make kata-tarball"

But in this way, there are lots of components tarball and no version tag.

Any comments? How to build a "kata-static-x.x.x-arm64.tar.xz"? @fidencio

**Comment by fidencio** [comment]
Our latesst pre-release contains the arm64 artefacts: https://github.com/kata-containers/kata-containers/releases/tag/3.2.0-alpha3

I'm closing the issue, feel free to re-open if if you think it's needed.
