### ISSUE TITLE
kata-runtime --config="/home/configuration-qemu.toml" kata-check

### ISSUE THREAD

**Issue by weiqiangxu** [kata-containers/kata-containers#6784]
**Before raising this question**

Have you looked at our [document](https://github.com/kata-containers/kata-containers/tree/main/docs) and still haven't found the answer?

yes

我使用了离线安装，解压到 /home/opt/kata , 然后执行 /home/opt/kata/bin/kata-runtime 
就抛出异常了

``` bash
WARN[0000] Not running network checks as super user      arch=amd64 name=kata-runtime pid=172398 source=runtime
ERRO[0000] CPU property not found                        arch=amd64 description="Virtualization support" name=vmx pid=172398 source=runtime type=flag
WARN[0000] modprobe insert module failed                 arch=amd64 error="exit status 1" module=kvm_intel name=kata-runtime output="modprobe: ERROR: could not insert 'kvm_intel': Operation not supported\n" pid=172398 source=runtime
ERRO[0000] kernel property kvm_intel not found           arch=amd64 description="Intel KVM" name=kvm_intel pid=172398 source=runtime type=module
ERRO[0000] ERROR: System is not capable of running Kata Containers  arch=amd64 name=kata-runtime pid=172398 source=runtime
ERROR: System is not capable of running Kata Containers
```

我感觉离线安装部分的文档没法使用，并且在集成firecracker这一方面也很困难

**Comment by fengwang666** [comment]
looks like your node doesn't have the virtualization support to run kata containers. Can you paste the output of `cat /proc/cpuinfo`?

**Comment by weiqiangxu** [comment]
非常感谢

[root]# egrep '(vmx|svm)' /proc/cpuinfo |wc -l
24

打开虚拟化了，目前qemu可以运行，但是使用集成的 firecracker 会出现异常

sudo ctr run --runtime "io.containerd.kata.v2" --rm -t "$image" test-kata uname -r

```
ctr: failed to create shim task: failed to mount "/run/kata-containers/shared/containers/test-kata/rootfs" to "/run/kata-containers/test-kata/rootfs", with error: ENOENT: No such file or directory: unknown
```

我的版本号是

[root bin]# containerd --version
containerd github.com/containerd/containerd v1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1

kata-static-3.0.2-x86_64.tar.xz

**Comment by weiqiangxu** [comment]
我是照着下面这个教程去搭建的

https://github.com/kata-containers/kata-containers/blob/3.0.2/docs/install/container-manager/containerd/containerd-install.md

**Comment by c3d** [comment]
I'm curious why it's trying to load `kvm_intel` when the architecture is `amd64`? Shouldn't it try kvm-amd?

**Comment by weiqiangxu** [comment]
下面是containerd的日志

5月 05 15:54:26 newball-computer containerd[9017]: time="2023-05-05T15:54:26.311673484+08:00" level=warning msg="failed to clean up after shim disconnected" error="time=\"2023-05-05T15:54:26+08:00\" level=warning msg=\"failed to cleanup container\" container=test-kata11 error=\"open /run/vc/sbs/test-kata11: no such file or directory\" name=containerd-shim-v2 pid=9091 sandbox=test-kata11 source=containerd-kata-shim-v2\nio.containerd.kata.v2: open /run/vc/sbs/test-kata11: no such file or directory: exit status 1" id=test-kata11 namespace=default
5月 05 15:54:26 newball-computer containerd[9017]: time="2023-05-05T15:54:26.311707702+08:00" level=error msg="copy shim log" error="read /proc/self/fd/17: file already closed"
5月 05 15:54:49 newball-computer kata[9123]: time="2023-05-05T15:54:49.220528751+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/test-kata11/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 source=virtcontainers subsystem=firecracker
5月 05 15:54:49 newball-computer containerd[9017]: time="2023-05-05T15:54:49.220528751+08:00" level=error msg="getting vm status failed" error="Get \"http://localhost/\": dial unix /run/vc/firecracker/test-kata11/root/run/firecracker.socket: connect: no such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 source=virtcontainers subsystem=firecracker
5月 05 15:54:49 newball-computer kata[9123]: time="2023-05-05T15:54:49.46842375+08:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/test-kata11/rootfs\" to \"/run/kata-containers/test-kata11/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 source=virtcontainers subsystem=kata_agent
5月 05 15:54:49 newball-computer containerd[9017]: time="2023-05-05T15:54:49.468423750+08:00" level=error msg="createContainer failed" error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/test-kata11/rootfs\" to \"/run/kata-containers/test-kata11/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 source=virtcontainers subsystem=kata_agent
5月 05 15:54:49 newball-computer containerd[9017]: time="2023-05-05T15:54:49.468613007+08:00" level=error msg="container create failed" container=test-kata11 error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/test-kata11/rootfs\" to \"/run/kata-containers/test-kata11/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 source=virtcontainers subsystem=container
5月 05 15:54:49 newball-computer kata[9123]: time="2023-05-05T15:54:49.468613007+08:00" level=error msg="container create failed" container=test-kata11 error="rpc error: code = Internal desc = failed to mount \"/run/kata-containers/shared/containers/test-kata11/rootfs\" to \"/run/kata-containers/test-kata11/rootfs\", with error: ENOENT: No such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 source=virtcontainers subsystem=container
5月 05 15:54:49 newball-computer containerd[9017]: time="2023-05-05T15:54:49.468696620+08:00" level=warning error="no such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 share-dir=/run/kata-containers/shared/sandboxes/test-kata11/mounts/test-kata11/rootfs source=virtcontainers subsystem=mount
5月 05 15:54:49 newball-computer containerd[9017]: time="2023-05-05T15:54:49.468722951+08:00" level=warning msg="Could not remove container share dir" error="no such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 share-dir=/run/kata-containers/shared/sandboxes/test-kata11/mounts/test-kata11 source=virtcontainers subsystem="filesystem share"
5月 05 15:54:49 newball-computer kata[9123]: time="2023-05-05T15:54:49.46869662+08:00" level=warning error="no such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 share-dir=/run/kata-containers/shared/sandboxes/test-kata11/mounts/test-kata11/rootfs source=virtcontainers subsystem=mount
5月 05 15:54:49 newball-computer kata[9123]: time="2023-05-05T15:54:49.468722951+08:00" level=warning msg="Could not remove container share dir" error="no such file or directory" name=containerd-shim-v2 pid=9123 sandbox=test-kata11 share-dir=/run/kata-containers/shared/sandboxes/test-kata11/mounts/test-kata11 source=virtcontainers subsystem="filesystem share"

**Comment by weiqiangxu** [comment]
> I'm curious why it's trying to load `kvm_intel` when the architecture is `amd64`? Shouldn't it try kvm-amd?

这我也不清楚哦，只是想最简单的方式搭建一个 containerd && kata-runtime && firecracker 

用手动安装的方式

但是这个让我觉的很困难

**Comment by weiqiangxu** [comment]
按照下面的可以搭建出来，必须安装 snapshotter.devmapper

https://github.com/kata-containers/kata-containers/blob/3.0.2/docs/how-to/how-to-use-kata-containers-with-firecracker.md
