### ISSUE TITLE
containerd && kata-runtime && firecracker 搭建太困难了

### ISSUE THREAD

**Issue by weiqiangxu** [kata-containers/kata-containers#6785]
**Before raising this question**

Have you looked at our [document](https://github.com/kata-containers/kata-containers/tree/main/docs) and still haven't found the answer?

yes

[root ~]# sudo ctr run --runtime "io.containerd.kata.v2" --rm -t "$image" test-kat1a uname -r

```
ctr: failed to create shim task: failed to mount 
"/run/kata-containers/shared/containers/test-kat1a/rootfs" 
to "/run/kata-containers/test-kat1a/rootfs",
with error: ENOENT: No such file or directory: unknown
```

参考链接是 

https://github.com/kata-containers/kata-containers/blob/3.0.1/docs/install/container-manager/containerd/containerd-install.md

**Comment by weiqiangxu** [comment]
[roo ~]# kata-runtime kata-check

WARN[0000] Not running network checks as super user  arch=amd64 name=kata-runtime pid=11120 source=runtime
System is capable of running Kata Containers
System can currently create Kata Containers

**Comment by fidencio** [comment]
Are you properly setting the device-mapper snapshotter to use with firecracker?

**Comment by weiqiangxu** [comment]
> Are you properly setting the device-mapper snapshotter to use with firecracker?

https://github.com/kata-containers/kata-containers/blob/3.0.2/docs/hypervisors.md

我只是按照这个文档，把配置文件更改了而已

> ls -s configuration-qemu.toml configuration.toml

当指向 qemu 的时候可以成功启动容器

> ls -s configuration-fc.toml configuration.toml

当指向 fc 配置的时候则没法启动容器

**Comment by weiqiangxu** [comment]
> Are you properly setting the device-mapper snapshotter to use with firecracker?

当我执行

``` bash
ctr plugins ls
```

输出结果是

``` log
TYPE                                  ID                       PLATFORMS      STATUS    
io.containerd.content.v1              content                  -              ok  
io.containerd.snapshotter.v1          devmapper                linux/amd64    error
```

于是我按照教程

https://github.com/containerd/containerd/blob/main/docs/snapshotters/devmapper.md

配置好了

执行脚本：#1-loopback-devices

``` bash 
[plugins."io.containerd.snapshotter.v1.devmapper"]
    pool_name = "devpool"
    root_path = "/var/lib/containerd/devmapper"
    base_image_size = "10GB"
    discard_blocks = true
```

输出


``` bash
[root home]# ctr plugins ls
TYPE                                  ID                       PLATFORMS      STATUS    
io.containerd.content.v1              content                  -              ok        
io.containerd.snapshotter.v1          aufs                     linux/amd64    ok        
io.containerd.snapshotter.v1          btrfs                    linux/amd64    skip      
io.containerd.snapshotter.v1          devmapper                linux/amd64    ok 
```

**Comment by weiqiangxu** [comment]
> Are you properly setting the device-mapper snapshotter to use with firecracker?

配置完了之后，执行还是报错


``` log
[root🐳 home]# sudo ctr run --cni --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hell123o sh

ctr: failed to create shim task: failed to mount "/run/kata-containers/shared/containers/hell123o/rootfs"
 to "/run/kata-containers/hell123o/rootfs", with error: ENOENT: No such file or directory: unknown
```

**Comment by lifupan** [comment]
Hi @weiqiangxu 

It seemed you hadn't set the snapshotter right in the containerd's configuration file, such as:

[plugins."io.containerd.grpc.v1.cri".containerd]
   snapshotter = "devmapper"

**Comment by weiqiangxu** [comment]
> Hi @weiqiangxu
> 
> It seemed you hadn't set the snapshotter right in the containerd's configuration file, such as:
> 
> [plugins."io.containerd.grpc.v1.cri".containerd] snapshotter = "devmapper"


你好，我重启了containerd服务并执行
``` bash
$ containerd config dump
```
输出了
``
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
      ignore_rdt_not_enabled_errors = false
      no_pivot = false
      snapshotter = "devmapper"
```

但是仍然是无法启动的

``` log
[root🐳 home]# ctr run -d --runtime io.containerd.run.kata.v2 --config bundle/config.json test-kata

ctr: failed to create shim task: failed to mount "/run/kata-containers/shared/containers/test-kata/rootfs" 
to "/run/kata-containers/test-kata/rootfs", 
with error: ENOENT: No such file or directory: unknown
```

**Comment by wenzhaojie** [comment]
@weiqiangxu 遇到了相同的问题，按照教程中kata-deploy的方法安装后，其他的runtime都可以正常使用，唯独firecracker的runtime会报错。

**Comment by aki263** [comment]
> [plugins."io.containerd.grpc.v1.cri".containerd]
> snapshotter = "devmapper"

This helped.
