### ISSUE TITLE
Consider adding the rust log-parser to kata-ctl

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6797]
Now that #6512 has landed, we could consider adding the code to [`kata-ctl`](https://github.com/kata-containers/kata-containers/tree/main/src/tools/kata-ctl) as a sub-command (`kata-ctl log-parser ...`).

/cc @gabevenberg in case he's interested.

**Comment by gabevenberg** [comment]
Ill take this one.

**Comment by gabevenberg** [comment]
reopening, its not closed till #6826 is merged
