### ISSUE TITLE
agent: remove pci-rescan

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#683]
# Description of problem

This is a 2.0 replica of https://github.com/kata-containers/agent/issues/781.

PCI rescan messes up hotplug, notably for SR-IOV. There is PCI-rescan code in the Rust agent as well.

**Comment by fidencio** [comment]
@c3d, while going through the issues with the "need-review" label, I've faced this one.

Wasn't this issue supersed by https://github.com/kata-containers/kata-containers/pull/1190? If so, would make sense to @dgibson to mention this one his PR.

**Comment by dgibson** [comment]
@fidencio, @c3d, no this is not superseded by #1190.  It's a preliminary for this issue, but there's more work to be done.
