### ISSUE TITLE
kata-agent nic info sync raise "Received a netlink error message File exists (os error 17)" error

### ISSUE THREAD

**Issue by yiya1989** [kata-containers/kata-containers#6842]
# Description of problem
pod has two nic(eth1 and eth0),  we expect kata sync these two nic info into vm(eth0 eth1), but raise File exists (os error 17).
It works well of kata-2.3, but it failed of kata-2.5.

Network info in ns of physical machine:
eth1,  mac: BBB
eth0, mac: AAA

Network info of vm :
eth0,  mac: BBB
eth1, mac: AAA

so when kata agent sync info from host's network ns to vm's network,  it raise mac duplicated(`File exists (os error 17)`)

# Expected result
kata works well.
Network info in ns of physical machine:
eth1,  mac: BBB
eth0, mac: AAA

Network info of vm :
eth0,  mac: AAA
eth1, mac: BBB

# Actual result
kata agent raise error:
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: "update interface: Received a netlink error message File exists (os error 17)": unknown

# Further information
I see a related commit:
[Make the network API non Linux specific](https://github.com/kata-containers/kata-containers/pull/3597)
https://github.com/kata-containers/kata-containers/commit/2edea883698bddcc2b17f24ac3c516382027d753

**The old code is collect all endpoint, and then sort endpoints by name,  and then attatch the endpoints.
But the new code is collect one the network info and then attatch this endppint, finally sort endpoints by name after all endpoints attatched, so lead to the difference of vm's nic order with ns's nic order**

The related code is as bellow:
```
func createEndpointsFromScan(networkNSPath string, config *NetworkConfig) ([]Endpoint, error) {
	var endpoints []Endpoint

	idx := 0
	for _, link := range linkList {
                 ....
		if err := doNetNS(networkNSPath, func(_ ns.NetNS) error {
			endpoint, errCreate = createEndpoint(netInfo, idx, config.InterworkingModel, link)
			return errCreate
		}); err != nil {
			return []Endpoint{}, err
		}

		endpoints = append(endpoints, endpoint)
	}

	sort.Slice(endpoints, func(i, j int) bool {
		return endpoints[i].Name() < endpoints[j].Name()
	})
        ...
}

// Add adds all needed interfaces inside the network namespace.
func (n *Network) Add(ctx context.Context, config *NetworkConfig, s *Sandbox, hotplug bool) ([]Endpoint, error) {
        ...
   	endpoints, err := createEndpointsFromScan(n.NetNSPath, config)
	
	err = doNetNS(n.NetNSPath, func(_ ns.NetNS) error {
		for _, endpoint := range endpoints {
				if err := endpoint.Attach(ctx, s); err != nil {
					return err
	}

	n.Endpoints = append(n.Endpoints, endpoints...)

	networkLogger().Debug("Network added")

	return endpoints, nil
}
```

**Comment by yiya1989** [comment]
> 



> Hi @yiya1989
> 
> Can you verify if this PR #6860 solves your issue?

This may solves this issue, but my suggestion is to adjust kata-shim network's endpoint code.
We collect all the netinfo and  endpoints info, and then sort endpoints by name and iter attatch them. Is it ok？

**Comment by lifupan** [comment]
> > 
> 
> > Hi @yiya1989
> > Can you verify if this PR #6860 solves your issue?
> 
> This may solves this issue, but my suggestion is to adjust kata-shim network's endpoint code. We collect all the netinfo and endpoints info, and then sort endpoints by name and iter attatch them.
> 
> I have submit a PR #6863 , Is it ok？

Hi  @yiya1989 

The name of the network card in the guest is affected by the order in which the network card drivers are loaded. Although we can guarantee the order in the runtime, we cannot guarantee the order in which the hypervisor inserts these devices. It’s just that the device insertion order of several hypervisors we use is the same as the order of runtime attach, but this does not mean that all hypervisors handle it this way.

Therefore, in order to be safe, we can add the sort on the runtime side, just as your PR does,  but we also need to deal with the name conflicts on the agent side.

**Comment by yiya1989** [comment]
> 

No problem, i suggest to order the nics due to I found the endpoints's sort action in the older code, It's safter with the kata runtime's older logic. 
As you say, the nic's rename action in vmm may also need to do.
