### ISSUE TITLE
Forward port remote-hypervsior support from `CCv0`

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#6867]
Support for the remote hypervisor was initially added into `CCv0` with PR https://github.com/kata-containers/kata-containers/pull/3697 and has been extended since.

Peer pods, which utilises this has grown to become part of the CoCo release, with previews and offering from multiple companies, so we should get this function merged into `main` when possible.

We went through the original proposal at length with the Architecture Committee, but I think we still want to review this again with them as we want to get it merged into `main`, but first we should try and isolate the changes we need to forward port and check the basics to see if they are ready.

**Comment by stevenhorsman** [comment]
List so far of remote-hypervisor related commits I've found (so far):
- https://github.com/kata-containers/kata-containers/pull/3697/commits/150e8aba6dbc7c0520bb9495d52f320f83127101
- https://github.com/kata-containers/kata-containers/pull/3697/commits/f9278f22c353e2ac253fa2eb2f129685af544bd0
- https://github.com/kata-containers/kata-containers/pull/3697/commits/c3e6b660515046fef704e60d36efb05c10b5060b
- https://github.com/kata-containers/kata-containers/pull/3697/commits/de232b8030eba9908557ac6546b97e8044685bfc
- https://github.com/kata-containers/kata-containers/pull/3697/commits/5422a056f2a7e0e796faed9739656f1a6aebe334
- https://github.com/kata-containers/kata-containers/pull/5937/commits/3ef2fd1784edc1cd0eb48becb664596269346c0d
- https://github.com/kata-containers/kata-containers/pull/6350/commits/7c9a791d677d7e4ddaa272ae312228286c8980e6
- https://github.com/kata-containers/kata-containers/pull/6342/commits/3081cd5f8e847dbde90145bf20406953389707f9
- https://github.com/kata-containers/kata-containers/pull/6617/commits/938447803b64a6118aae1e4b1a31fd81d8593757

**Comment by stevenhorsman** [comment]
When https://github.com/kata-containers/kata-containers/pull/7141 is merged into `CCv0` we'll need to cherry-pick it over.

**Comment by stevenhorsman** [comment]
I've updated the branch to add https://github.com/kata-containers/kata-containers/commit/004f07f076830601102b141041b807c690e560cf and rebase on main

**Comment by stevenhorsman** [comment]
This issue has now got a dependency on https://github.com/kata-containers/kata-containers/issues/7210 which was split out to delivery some of the commits (around propagating configmaps/secrets for non sharedfs scenarios)

**Comment by bpradipt** [comment]
> @bpradipt - with the flexible instance support, so we need to change the default remote config to have `enable_annotation = ["machine_type", "default_memory", "default_vcpus"]`? and/or remove our comments of
> 
Yes, we need these annotations and remove the comments

> ```
> # Note: the remote hypervisor uses the peer pod config to determine the memory of the VM
> ```
> 
> and
> 
> ```
> Note: the remote hypervisor uses the peer pod config to determine the CPUs of the VM
> ```
> 
> for `default_memory` and `default_vcpus` config settings?
> 
> I guess we should do that on `CCv0` in the short-term as well

Right.

**Comment by stevenhorsman** [comment]
Ok, I'll work on that on `CCv0` tomorrow and then pull it into this PR. Thanks!

**Comment by stevenhorsman** [comment]
We also want to pull in the runtimeclass definition from https://github.com/kata-containers/kata-containers/pull/7549 once merged into this PR.
