### ISSUE TITLE
CCv0: Do not update TDX components, as the TDX jenkins CI is running on a 2022ww44 TDX stack

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#6884]
"What's a 2022ww44 TDX stack?", someone would ask, and the answer is that TDX development has been made publicly available, as a full stack that will work end-to-end, in interval of a few weeks between each drop.

Current as part of the CCv0, we're running a Ci that has a system based on the 2022ww44, but on `main` we updated the TDX artefacts to the `2023ww01`, and this was mistakenly brought to the `CCv0` branch (if we'd play the blame games, the reviewer didn't catch this, and the reviewer happens to be myself).

We should revert the patches related to this and ensure that the TDX CI will be up and running in order to avoid any possible issues during the freeze / release time.

**Comment by stevenhorsman** [comment]
I believe this was resolved with #6886
