### ISSUE TITLE
[forward port] rust-agent: setupDNS for guest

### ISSUE THREAD

**Issue by lifupan** [kata-containers/kata-containers#689]
# Description of problem

see for https://github.com/kata-containers/agent/issues/635

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by liubin** [comment]
Related PRs:

- https://github.com/kata-containers/runtime/pull/1939/files
- https://github.com/kata-containers/agent/pull/625/files
