### ISSUE TITLE
Resource allocation: Potential over-allocation of vCPUs in kata-shim leading to UVM bring-up failure

### ISSUE THREAD

**Issue by ms-mahuber** [kata-containers/kata-containers#6909]
**Disclaimer:**
  - This issue is one of the four issues forked based the discussion from [issue 6818, using static resource management for TEEs](https://github.com/kata-containers/kata-containers/issues/6818). All four issues are pre-fixed with "Resource allocation:"
  - I am aware I may be a bit deviating a bit from the style of how a bug/request should be opened, but this reflects an obvious issue observed by other peers, so I assume this is fine.

**Description:**
In some scenarios, the shim is prone to request too many vCPUs, leading to pod creation failures when static resource allocation is enabled.
  - Example: podOverhead of 0.25 CPU shares and a node with capacity of 3.86 CPU shares (a node with 4 CPUs and a bit of CPU reserved for the host kubernetes runtime itself, specified via e.g. --kube-reserved=cpu=140m,memory=2662Mi). If a user requests 3.25 CPU shares via a limit, kubernetes accepts the pod yaml (as 3.25+0.25<3.86). Under the plate, the shim tries to allocate 1+ceil(3.25) vCPUs = 5 vCPUs as part of the calculations via calculateVMResources() and as part of the sum being made in SandboxConfig() in src/runtime/pkg/oci/utils.go: SandboxConfig() (note, this example assumes a value of default_vcpus = 1). At least with CH this leads to a pod bring-up failure because CH basically has an assert that does not allow more vCPUs than present CPUs.
  - This will need improvement. While it is plausible to use at least 1 vCPU, adding the limit value this way is bad.
  - Note, that in the dynamic resource management case, this over-allocation can also happen. I am observing warnings where we try to hotplug 4 vCPUs to a 1 vCPU VM in this scenario (see the updateResources() function in src/runtime/virtcontainers/sandbox.go), but cloud-hypervisor rejects this (see in ResizeVCPUs(), only a warning, not an error is issued), and then kata-shim falls back to using 4 vCPUs, i.e., allocates the max number of CPUs available. Unsure what the specified behavior is (whether a warning and best-effort CPU hotplug is desired, or whether even an error should be thrown)

**Comment by fidencio** [comment]
@ms-mahuber and I had a call Yesterday where we discussed this issue.

The approach we're going to take and propose to the community is:
* Use `default_vcpus` and `default_max_vcpus` as floats, which will allow users to specify a CPU share.
* Once we know the ammount of CPUs requested bia limites we do: `ceil(num_vcpus + limits)`

I'm taking this one to work on.
