### ISSUE TITLE
Set the default cache mechanism of virtiofsd to `none`

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#691]
**Which feature do you think can be improved?**

@jcvenegas mentioned having some synchronisation issues, and @rhvgoyal mentioned that using the default cache mechanism as `none ` should be preferred.

**How can it be improved?**

Just tweak the runtime's Makefile to use `none` as the default cache mechanism.

**Additional Information**

Nops.

**Comment by rhvgoyal** [comment]
@fidencio I am not sure why I suggested cache=none. I would say cache=auto makes most sense for default and that's upstream default too.

cache=none probably will be bad for performance. cache=auto is sort of middle approach where performance is medium and it allows some sharing with host. cache=always assumes that nothing has changed outside guest and cache contents never expire. In terms of performance, this probably is fastest most but will not allow any sharing with host.

**Comment by fidencio** [comment]
@rhvgoyal. thanks **a ton** for jumping in!

Okay, I'll close the PR and I'm glad we have your recommendation recorded here!

**Comment by rhvgoyal** [comment]
cache=always should be faster than cache=auto but it also assumes that nothing will change on host and guest cache is always valid. So if we are not expecting to make any changes on host, then cache=always should be good. But if we expect to make some changes on host, then cache=auto should be a better option.
