### ISSUE TITLE
AArch64: kata components cached results statics

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#6914]
Test if kata components are cached for aarch64:
Test results:

- rootfs-image FAIL
- rootfs-initrd FAIL
- kernel SUCCESS
- qemu FAIL
- firecracker SUCESS
- virtiofsd FAIL
- nydus FAIL
- shim-v2 FAIL

**Comment by fidencio** [comment]
* virtiofsd: cached version is 1.3.0, while the latest version is 1.6.1.  We need to figure out why the caching job is not getting the up-to-date version from Kata Containers.

* nydus:  cached version is 2.1.1, while the latest version is 2.2.0. We need to figure out why the caching job is not getting the up-to-date version from Kata Containers.

* qemu: we don´t have a qemu cache job for aarch64, creating one should be enough to fix this

* shim-v2: the caching job is missing information about the go and rust version.

* rootfs-image: also missing information about versions in the cached job

* rootfs-initrd: also missing information about versions in the cached job

For rootfs-initrd, rootfs-image, and shim-v2, it seems yq is not being installed, thus the jobs are failing to get those versions.  I will take a look at the jobs.

For qemu, I will create a job

For virtiofsd / nydus:  I have no idea why it's happening,. and would appreciate some help here, but it seems we're not pulling / not using the latest version of Kata Containers in the cache jobs.

**Comment by fidencio** [comment]
I've adapted the shim-v2 / rootfs-image / rootfs-initrd jobs to install `yq`.
I've added the QEMU job, but it's not being able to build yet due to some weird failure: http://jenkins.katacontainers.io/view/Cached%20jobs/job/kata-containers-main-qemu-aarch64/2/console

**Comment by fidencio** [comment]
> I've adapted the shim-v2 / rootfs-image / rootfs-initrd jobs to install yq, and triggered a re-build.

This partially solved the issue, now all the components are getting the wrong version, the very same issue that we're facing with virtiofsd / nydus.

**Comment by fidencio** [comment]
Okay, I've changed the cache jobs and I was able to get everything working.

@jongwu, please, give it a try on your side, and if everything is okay, we can close this one.

**Comment by jongwu** [comment]
Hi @fidencio -, except nydus, no changed for other tarball.
