### ISSUE TITLE
[forward port] Fix potential major:minor conflicts during device updates

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#703]
Port https://github.com/kata-containers/agent/pull/836 from Kata 1.x.

**Comment by bergwolf** [comment]
@dgibson ping? This is marked release gating but stale for a long time.

**Comment by jamesodhunt** [comment]
Hi - this issue is labelled `release-gating` but doesn't have an associated PR.

Please can you comment on the status of this item so we know if it could be
included in the [upcoming 2.0 release](https://github.com/kata-containers/kata-containers/wiki/Kata-Containers-2.0-Roadmap)?

**Comment by bergwolf** [comment]
ping @dgibson Any updates?

**Comment by dgibson** [comment]
I've made a start, trying to find time for it amongst other things.  Got a bit sidetracked, because almost none of the existing relevant testcases from the Go agent made it into the Rust agent, and porting those exposed some other problems.

**Comment by bergwolf** [comment]
@dgibson I opened https://github.com/kata-containers/kata-containers/pull/924 to fix the same issues in the rust agent. Please help to take a look. Thanks!
