### ISSUE TITLE
typo error in virtiofsd test code

### ISSUE THREAD

**Issue by Kvasscn** [kata-containers/kata-containers#712]
# Description of problem

"sourcePath"  should be "socketDir"  in virtiofsd test code  https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/virtcontainers/virtiofsd_test.go#L38

# Expected result

	socketDir, err := ioutil.TempDir("", "")
	assert.NoError(err)
	defer os.RemoveAll(socketDir)

# Actual result

	socketDir, err := ioutil.TempDir("", "")
	assert.NoError(err)
	defer os.RemoveAll(sourcePath)

**Comment by fidencio** [comment]
@Kvasscn, the very same issue is present here: https://github.com/kata-containers/runtime/blob/master/virtcontainers/virtiofsd_test.go#L38

Would you mind backporting the patch to that repo as well?
