### ISSUE TITLE
agent: systemd cgroup manager does not really destroy unit

### ISSUE THREAD

**Issue by Yuan-Zhuo** [kata-containers/kata-containers#7142]
The systemd cgroup manager currently calls the stop unit interface of systemd to destroy, which will cause the unit to still exist.

>
> https://github.com/kata-containers/kata-containers/blob/d071a87c7babe157752832e251e7c59683702c25/src/agent/rustjail/src/cgroups/systemd/manager.rs#L83-L86
>

**Comment by justxuewei** [comment]
Fixed by https://github.com/kata-containers/kata-containers/pull/7917.
