### ISSUE TITLE
action: Improve porting checks

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#715]
Improve the PR porting GitHub action by referencing a central script to
handle the checks rather than hard-coding them in the workflow YAML.

This ensures all PRs use the latest porting policy encoded in the
script and makes maintenance easier.

Related: https://github.com/kata-containers/kata-containers/issues/634

**Comment by fidencio** [comment]
@jodh-intel, is this one still valid?

**Comment by jodh-intel** [comment]
All done - https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/require-pr-porting-labels.yaml#L41 calls `pr-porting-checks.sh` so closing this.
