### ISSUE TITLE
CCv0 | Update image-rs to the newest merged image-rs

### ISSUE THREAD

**Issue by Xynnn007** [kata-containers/kata-containers#7152]
**Which feature do you think can be improved?**

After merging `image-rs`, we need to update the `image-rs` to the new rev.

**Comment by stevenhorsman** [comment]
Hey @Xynnn007 - I think we also need to bump where there attestation-agent is being pulled from (and it's revision) in version.yaml
https://github.com/kata-containers/kata-containers/blob/4ff3afc59d42e3a329bb3aac8f41c190b9f3c7df/versions.yaml#L194-L197
as well?

**Comment by stevenhorsman** [comment]
I guess this needs to wait until the image-rs repo has been renamed anyway otherwise we'll update it again soon after. Is there a idea for when this might be done?

**Comment by wainersm** [comment]
image-rs is already merged into guest-components

**Comment by stevenhorsman** [comment]
Yep - I think this is ready to try once we get `CCv0` CI stable

**Comment by wainersm** [comment]
> Yep - I think this is ready to try once we get `CCv0` CI stable

Read "CI stable" makes me cry :(

**Comment by stevenhorsman** [comment]
@Xynnn007 @wainersm - I've had an attempt at this in https://github.com/kata-containers/kata-containers/pull/7228 if you have a chance to check it. Thanks

**Comment by stevenhorsman** [comment]
Closed with #7228 merging
