### ISSUE TITLE
agent: fails to create container(peerpods)

### ISSUE THREAD

**Issue by Amulyam24** [kata-containers/kata-containers#7166]
I'm creating a pod using `ibmcloud-powervs` provider with `cloud-api-adaptor`.

```
2023/06/23 09:47:50 [adaptor/proxy] CreateContainer: successfully pulled image "registry.k8s.io/pause:3.7"
2023/06/23 09:47:50 [adaptor/proxy] CreateContainer fails: rpc error: code = Internal desc = Checking if systemd unit cri-containerd-ddc4a0ba5d22d962fc5723c8b6cf651ad67d8f139368228067b99e19d71ccbe1.scope exists

Caused by:
    0: Establishing a D-Bus connection
    1: invalid value: string "()", expected at least one field signature between `(` and `)`
    2: invalid value: string "()", expected at least one field signature between `(` and `)`
```
The agent is failing to fetch the systemd unit while trying to add the process to the cgroup.
Logs from kata-agent:  [kata-logs.txt](https://github.com/kata-containers/kata-containers/files/11847268/kata-logs.txt)

**Comment by Amulyam24** [comment]
Hi @yoheiueda, I see that you've faced issues related to systemd cgroups manager with kata-agent. Have you come across this issue anytime?

Also tagging @Yuan-Zhuo who has added support for systemd cgroup manager.

**Comment by yoheiueda** [comment]
@Amulyam24 I haven't seen such errors.

It looks like the error occurs around at line, but I have no idea what is going on.

https://github.com/kata-containers/kata-containers/blob/4ff3afc59d42e3a329bb3aac8f41c190b9f3c7df/src/agent/rustjail/src/cgroups/systemd/dbus_client.rs#L40
https://github.com/dbus2/zbus/blob/37d6a9b32d2b43d7a71b9d43d5887f6857967eda/zvariant/src/signature_parser.rs#L223

**Comment by Amulyam24** [comment]
Hi @yoheiueda,

I built a new agent using this [fix](https://github.com/kata-containers/kata-containers/pull/7151). It is working fine with the zbus version 3.13.1 which consists of a patch fixing the above issue. Thanks!

**Comment by justxuewei** [comment]
Fixed by https://github.com/kata-containers/kata-containers/pull/7917.
