### ISSUE TITLE
runtime: Add "none" as a shared_fs option

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#7207]
Currently, even when using devmapper, if the VMM supports virtio-fs /
virtio-9p, that's used to share a few files between the host and the
guest.

This *needed*, as we need to share with the guest contents like secrets,
certificates, and configurations, via Kubernetes objects like configMaps
or secrets, and those are rotated and must be updated into the guest
whenever the rotation happens.

However, there are still use-cases users can live with just copying
those files into the guest at the pod creation time, and for those
there's absolutely no need to have a shared filesystem process running
with no extra obvious benefit, consuming memory and even increasing the
attack surface used by Kata Containers.

For the case mentioned above, we should allow users, making it very
clear which limitations it'll bring, to run Kata Containers with
devmapper without actually having to use a shared file system, which is
already the approach taken when using Firecracker as the VMM.

**Comment by studychao** [comment]
@Tim-0731-Hzt will cover the runtime-rs part for this feature:)

**Comment by fidencio** [comment]
> @Tim-0731-Hzt will cover the runtime-rs part for this feature:)

That's one of the reasons I **really** enjoy working with you guys! <3
