### ISSUE TITLE
runtime: SYSCONFIG PATH broken for SEV

### ISSUE THREAD

**Issue by UnmeshDeodhar** [kata-containers/kata-containers#7213]
As part of this [commit ](https://github.com/kata-containers/kata-containers/pull/7134/files#diff-2ba0cb0d4a795ecfd09b767b2c67bbaac58abaecc743ca4c1281966d940f699f) (merge from main), `SYSCONFIG_PATHS_SEV` was removed and generic `SYSCONFIG_PATHS` was used. This was causing SEV tests to fail.

**Comment by stevenhorsman** [comment]
Fixed in https://github.com/kata-containers/kata-containers/pull/7205
