### ISSUE TITLE
Testing cri-o against kata 3.1.3 fails on "stats" gathering

### ISSUE THREAD

**Issue by littlejawa** [kata-containers/kata-containers#7232]
# Description of problem

I've tried updating the version of kata used by the cri-o CI job, and found a regression on the "stats" test (see https://github.com/cri-o/cri-o/pull/7112).
This is using the kata binaries from https://github.com/kata-containers/kata-containers/releases/tag/3.1.3.

How to reproduce:
run `crictl stats -o json` with a running kata container

# Expected result

Retrieve the stats.
e.g (with kata 3.0.2):
```
# {
#   "stats": [
#     {
#       "attributes": {
#         "id": "d2cfaa24c69f04fe20c02a0e3733790831866a46b0d54bc9c1839ea41f3fafd1",
#         "metadata": {
#           "name": "podsandbox1-redis",
#           "attempt": 0
#         },
#         "labels": {
#           "tier": "backend"
#         },
#         "annotations": {
#           "pod": "podsandbox1"
#         }
#       },
#       "cpu": {
#         "timestamp": "1688471687102082455",
#         "usageCoreNanoSeconds": {
#           "value": "37776965"
#         },
#         "usageNanoCores": null
#       },
#       "memory": {
#         "timestamp": "1688471687102082455",
#         "workingSetBytes": {
#           "value": "266240"
#         },
#         "availableBytes": {
#           "value": "18446744073501519872"
#         },
#         "usageBytes": null,
#         "rssBytes": {
#           "value": "90112"
#         },
#         "pageFaults": {
#           "value": "146"
#         },
#         "majorPageFaults": {
#           "value": "9"
#         }
#       },
#       "writableLayer": {
#         "timestamp": "1688471687102196612",
#         "fsId": {
#           "mountpoint": "/tmp/tmp.mN2Oc9gQJp/crio/overlay/c88e9284a59e7221f4c57fb24bb72a8b9617a884aa6b73facbc84bf807337d19/merged"
#         },
#         "usedBytes": {
#           "value": "22"
#         },
#         "inodesUsed": {
#           "value": "7"
#         }
#       }
#     }
#   ]
# }
```

# Actual result

An empty structure is returned (only the ID of the container is retrieved)
e.g:
```
# {
#   "stats": [
#     {
#       "attributes": {
#         "id": "b6222af76c8dca25874263865b7ebdacffe7304ff815f74c37354ee2746d26e7"
#       }
#     }
#   ]
# }
```

# Further information

- Looking at the logs, I find the following error:
`# time="2023-07-04 15:01:57.382781620+02:00" level=error msg="Error getting container stats b6222af76c8dca25874263865b7ebdacffe7304ff815f74c37354ee2746d26e7: failed to extract container metrics: type with url io.containerd.cgroups.v2.Metrics: not found" file="stats/stats_server.go:145"`

  The full log of the failing test is [available here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/cri-o_cri-o/7112/pull-ci-cri-o-cri-o-main-ci-fedora-kata/1676144548310421504/artifacts/fedora-kata/cri-o-gather/artifacts/testout.txt)

  Looking at the failing url (`io.containerd.cgroups.v2.Metrics`), I find it is part of the vendored `github.com/containerd/cgroups` code in the kata runtime.
https://github.com/kata-containers/kata-containers/blob/ee57732fe08504773b1b5474f2248834ae1fbd66/src/runtime/vendor/github.com/containerd/cgroups/v2/stats/metrics.pb.go#L479
On the cri-o side, we're using containerd/cgroups v1.1.0, and on the kata side we're using v1.0.5-0.20220625035431-cf7417bca682e.
Now there was no change from 3.0 to 3.1 in this area, so I'm not sure why it would start failing.

- Another difference I see when comparing a working 3.0.2 test against the failing 3.1.3 is this:
3.0.2:
`# time="2023-07-04T13:54:46.646484841+02:00" level=info msg="SELinux label from config will be applied to the hypervisor process, not the VM workload" name=containerd-shim-v2 pid=313171 sandbox=e2ce2444fa6bc923bceb66f394217a8aca1754b0c14ee97feb317cba2123b8e2 source=virtcontainers subsystem=kata_agent`

  3.1.3:
`# time="2023-07-04T15:01:56.723142957+02:00" level=info msg="Empty SELinux label for the process and the mount because guest SELinux is disabled" name=containerd-shim-v2 pid=333040 sandbox=18e51dc3620115182b1d43663b369ace605d18845a9f4fa052ad1df343022c23 source=virtcontainers subsystem=kata_agent`

  Could this have an impact on how we report the stats?

What is puzzling is that we have another CI job that runs daily, running the same tests from cri-o against kata's main branch (with the same vendored code), and it doesn't have this issue.
e.g: [last nightly run](http://jenkins.katacontainers.io/view/Daily%20baseline/job/crio-kata-containers-2.0-fedora-35-main-baseline/565/consoleText)

I feel that I am missing something, maybe not even looking in the right direction.
Any guidance is welcome.

**Comment by fidencio** [comment]
Isn't it a cgroupsv1 / cgroupsv2 kind of issue that's being exposed now when running it on a system with cgroupsv2 enabled?

**Comment by littlejawa** [comment]
Right. 01765e17342dd has introduced cgroupv2 structure, I need to make sure cri-o can process it.
