### ISSUE TITLE
dragonball: complete metrics in vmm and devices

### ISSUE THREAD

**Issue by ZizhengBian** [kata-containers/kata-containers#7248]
Currently, the metric in Dragonball is not perfect, so we need to improve the metric information for Dragonball's VMM and devices and output them to the runtime.

**Comment by ZizhengBian** [comment]
Let's continue in kata-containers repo!

**Comment by lisongqian** [comment]
The metrics in Dragonball will be upgraded to:

## DragonballMetrics Definition

The   `DragonballMetrics` is used to collect metrics from device and non-device, and output the information to runtime.

```rust
lazy_static! {
    pub static ref METRICS: RwLock<DragonballMetrics> = RwLock::new(DragonballMetrics::default());
}
pub struct DragonballMetrics {
    /// Metrics related to a vcpu's functioning.
    pub vcpu: HashMap<String, Arc<VcpuMetrics>>,
    /// Metrics related to seccomp filtering.
    pub seccomp: SeccompMetrics,
    /// Metrics related to signals.
    pub signals: SignalMetrics,
    // ...
}
```
When a device is created, the device manager add data(`device_id: Arc<deviceMetrics>`) to `DragonballMetrics`  at the same time.
When a device is dropped,  the device manager remove the `Arc` of the removed device in `DragonballMetrics`.

## Metric of Device
The metric of device is a field of device, such as:
```rust
pub struct Vcpu {
    ...
    metrics: Arc<VcpuMetrics>,
}
```
and update with:
```rust
self.metrics.xxx.inc();
```

We can collect the information of metrics with:
```rust
impl Vcpu {
    pub fn metrics(&self) -> Arc<VcpuMetrics> {
        self.metrics.clone()
    }
}
```

## Metric of Non-device

The metric of non-device is updated in `METRICS`, such as:
```rust
METRICS.read().unwrap().signals.sigbus.inc();
```

**Comment by lisongqian** [comment]
the metric in Dragonball  needs to add include:

|  | type                  | link |
|--|-----------------------|-----|
| [] | vcpu                  |     |
| [] | legacy device         |     |
| [] | virtio net device     |     |
| [] | virtio balloon device |     |
| [] | virtio block device   |     |
| [] | virtio vsock  device  |     |
| [] | virtio fs device      |     |
| [] | virtio mmio device    |     |
| [] | vmm action request    |     |
| [] | upcall device         |     |

**Comment by lisongqian** [comment]
the metric in Dragonball  needs to add include:

|              | type                  | link |
|--------------|-----------------------|------|
| <li>[ ]</li> | vcpu                  |      |
| <li>[ ]</li> | legacy device         |      |
| <li>[ ]</li> | virtio net device     |      |
| <li>[ ]</li> | virtio balloon device |      |
| <li>[ ]</li> | virtio block device   |      |
| <li>[ ]</li> | virtio vsock  device  |      |
| <li>[ ]</li> | virtio fs device      |      |
| <li>[ ]</li> | virtio mmio device    |      |
| <li>[ ]</li> | vmm action request    |      |
| <li>[ ]</li> | upcall device         |      |
