### ISSUE TITLE
gha: sev: Unable to run tests on SEV.

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#7250]
Please, see: https://github.com/kata-containers/kata-containers/actions/runs/5475317703/jobs/9971905159

/cc @ryansavino @UnmeshDeodhar @larrydewey @fitzthum

**Comment by UnmeshDeodhar** [comment]
@fidencio, SEV and SNP nodes are up and running. Here is the link to the test that ran 2 hours ago: 
SEV: https://github.com/kata-containers/kata-containers/actions/runs/5507711281/jobs/10038703514
SNP: https://github.com/kata-containers/kata-containers/actions/runs/5507711281/jobs/10038703738

**Comment by UnmeshDeodhar** [comment]
Thanks @larrydewey for working on that over the weekend!

**Comment by fidencio** [comment]
https://github.com/kata-containers/kata-containers/actions/runs/5623671307/job/15240128000?pr=7326

It's been broken for some time.

**Comment by UnmeshDeodhar** [comment]
The test is now able to launch: https://github.com/kata-containers/kata-containers/actions/runs/5623671307/job/15241771816

**Comment by fidencio** [comment]
Solved, thanks!
