### ISSUE TITLE
Remove unused repo-specific issue templates

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#727]
The following repos include an issue template. However, those templates are not being used since we have a central set of templates here:

- https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE

| repo | PR to remove issue template |
|-|-|
| `agent` | https://github.com/kata-containers/agent/pull/847 |
| `kata-containers` | https://github.com/kata-containers/kata-containers/pull/731 |
| `ksm-throttler` | https://github.com/kata-containers/ksm-throttler/pull/172 |
| `proxy` | https://github.com/kata-containers/proxy/pull/285 |
| `runtime` | https://github.com/kata-containers/runtime/pull/2953 |
| `shim` | https://github.com/kata-containers/shim/pull/271 |

See also: https://github.com/kata-containers/.github/pull/27.

**Comment by fidencio** [comment]
As all the repos mentioned in the issue decription, but the kata-containers one, reached their EOL a few months ago, let's close this issue.

@jodh-intel, please, feel free to re-open it in case you think it's still needed.
