### ISSUE TITLE
cached jobs: It seems that rootfs-initrd-sev always has to be built

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#7291]
It slows down the CI by quite a lot.

Please, take a look at the cached job and let us know what's happening there.

/cc @larrydewey @ryansavino @UnmeshDeodhar @fitzthum

**Comment by jepio** [comment]
The main job was set to poll the CCv0 branch, so it hasn't ran since July 7th. I switched it to main and triggered the job, let's see if that does it.

**Comment by jepio** [comment]
Yup, that was it.

**Comment by ryansavino** [comment]
Thanks @jepio
