### ISSUE TITLE
cached jobs: It seems rootfs-initrd-mariner has always to be built

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#7292]
It slows down the CI by quite a lot.

Please, take a look at the cached jobs, create one if needed, and let us know what's happening there.

/cc @sprt @jepio

**Comment by fidencio** [comment]
@jepio got it working, thus I'm closing this one.

Thanks Jeremi!

**Comment by jepio** [comment]
No not yet :D
