### ISSUE TITLE
CCv0: Avoid use of stale cached artifacts

### ISSUE THREAD

**Issue by UnmeshDeodhar** [kata-containers/kata-containers#7358]
In the CCv0 branch, we observed, runtime artifacts do not get updated when config parameters are changed from the tests repo.
This could be an issue where all the following tests will run with a cached runtime that is now stale. Only when another PR is merged that touches runtime code, it will trigger the caching job. And only then, we will see the latest runtime being rebuilt with all updated configs.

There are a couple of ways we can tackle this issue:
1. Run the caching job periodically (once or twice a week), so that we make sure that we update the artifacts and we do not let stale artifacts sit for a long time.
2. The daily baseline jobs for CCv0 should avoid caching. This way we catch any suspicious stale artifacts on a daily basis.
3. Caching jobs should not use previously cached tarballs to create current artifacts.

**Comment by stevenhorsman** [comment]
`CCv0` has not been maintained for about a year and the caching in `main` should include runtime artifacts.
