### ISSUE TITLE
CCv0: deleting a K8s Secret doesn't delete that Secret from the Guest, when !IsFsSharingSupported

### ISSUE THREAD

**Issue by danmihai1** [kata-containers/kata-containers#7398]
If I read correctly the code from https://github.com/kata-containers/kata-containers/blob/CCv0/src/runtime/virtcontainers/fs_share_linux.go, when !IsFsSharingSupported: 
- The Guest directory for a Secret doesn't get re-created the same way K8s does, and 
- The Guest files from that directory don't get deleted

So:
- Deleting Secret "data-1: dmFsdWUtMQo=" doesn't delete data-1 from the Guest
- Changing a Secret from "data-1: dmFsdWUtMQo=" to "data-3: dmFsdWUtMwo=" doesn't reflect that change onto the Guest.

These K8s conformance tests seem to confirm that incomplete behavior on CCv0:

KUBECONFIG=~/.kube/config sonobuoy run --e2e-focus 'optional updates should be reflected in volume'

Cc: @bpradipt , @stevenhorsman

**Comment by stevenhorsman** [comment]
Thanks very much for raising this Dan, I think this indicates that https://github.com/kata-containers/kata-containers/pull/7211 needs some more work and I think the best approach is probably to get it working properly there and then backport the fix to `CCv0` as we've already made some improvements on the way to `main`

**Comment by bpradipt** [comment]
@danmihai1 looking at the code, it seems the string comparison to identify the secret is incorrect - https://github.com/kata-containers/kata-containers/blob/CCv0/src/runtime/virtcontainers/fs_share_linux.go#L294
It should be `kubernetes.io~secret` instead of `kubernetes.io~secrets`.
I'm working to fix this as part of #7211. 
Ref: https://github.com/bpradipt/kata-containers/tree/pr7211

**Comment by danmihai1** [comment]
@bpradipt , the part I don't get is that I don't see any file or directory delete in that code. If that's the case, I guess at the minimum the propagated directories from the Guest get leaked when K8s decides to delete the original directories, from the Host. 

Please let me know in case I misunderstood how deleting propagated directories works, or if I missed some Delete calls.

**Comment by bpradipt** [comment]
> @bpradipt , the part I don't get is that I don't see any file or directory delete in that code. If that's the case, I guess at the minimum the propagated directories from the Guest get leaked when K8s decides to delete the original directories, from the Host.
> 
> Please let me know in case I misunderstood how deleting propagated directories works, or if I missed some Delete calls.

@danmihai1 Looks like deletion of a secret (or cm/annotation value) is not handled like the updates. So we'll need to update the code to watch for some additional events to identify deletion and propagate it to the agent. I will investigate how this can be done.
