### ISSUE TITLE
agent: Commit number not correctly generated, version stuck at 1.4.5

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#740]
**Which feature do you think can be improved?**

While investigating #557 (specifically https://github.com/kata-containers/kata-containers/issues/557#issuecomment-693530534) I noticed the following in the log:

```
{"msg":"announce","level":"INFO","ts":"2020-08-19T15:00:54.909555391+00:00","source":"agent","name":"kata-agent","version":"0.1.0","pid":"1","subsystem":"root","agent-version":"1.4.5","api-version":"0.0.1","agent-type":"rust","agent-commit":""}
```

This comes from `fn announce()` in `main.rs`: https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/agent/src/main.rs#L85.

This fetches the version from an environment variable `VERSION_COMMIT`. Not sure why. This should probably be a built-time constant, set from `COMMIT_NO` in the Makefile (https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/agent/src/main.rs#L85).

Notice that the agent version number is defined in `version.rs` and has been stuck at `1.4.5` for the longest time (see https://github.com/kata-containers/kata-containers/commits/2.0-dev/src/agent/src/version.rs). That too should probably be changed.

**How can it be improved?**

1. Pass `COMMIT_NO` to the agent source so that we have a precise commit number for the builds.
2. Pass `VERSION` from the makefile to the agent.

**Comment by jodh-intel** [comment]
Partially addressed by https://github.com/kata-containers/kata-containers/pull/726.
