### ISSUE TITLE
Kata Containers on K8s cluster on AWS bare-metal instance not working

### ISSUE THREAD

**Issue by naveenbansalntnx** [kata-containers/kata-containers#7435]
# Description of problem

I am trying to deploy pods using Kata-containers. 
System setup - 2-node K8s cluster ( z1d.metal ). After deploying the cluster I tried deploying kata-containers using [this](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/README.md#vanilla-kubernetes-cluster) page to install kata-containers.

# Expected result
Kata container should run
(replace this text with an explanation of what you thought would happen)

# Actual result
The kata-deploy pod is in CrashLoopBackOff state.
These are the logs of the pod

> copying kata artifacts onto host
warning: /usr/local/bin/containerd-shim-kata-fc-v2 already exists
warning: /usr/local/bin/containerd-shim-kata-qemu-v2 already exists
warning: /usr/local/bin/containerd-shim-kata-v2 already exists
Creating the default shim-v2 binary
warning: /usr/local/bin/containerd-shim-kata-clh-v2 already exists
warning: /usr/local/bin/containerd-shim-kata-dragonball-v2 already exists
Add Kata Containers as a supported runtime for containerd
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc.options, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu.options, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh.options, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-dragonball, overwriting
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-dragonball.options, overwriting
Failed to connect to bus: No data available

I have attached containerd config.toml for worker node

# Further information
[config.toml.txt](https://github.com/kata-containers/kata-containers/files/12159056/config.toml.txt)

**Comment by fidencio** [comment]
Hey @naveenbansalntnx, are you using the `stable`  kata-deploy?
If so, would you mind to give it a try with the following patch? https://github.com/kata-containers/kata-containers/pull/7195

We switched to using ubuntu as the base image, which means that we need to adapt the daemon-set host mounths to the ubuntu image.

I'm really sorry the patch has been opened for a long time and was not merged yet, but I will poke other maintainers for a review.

Please, let us know if that woiks for you.

**Comment by naveenbansalntnx** [comment]
Hi @fidencio , with your change I was able to run kata-containers.
Thanks a lot !!
Just one question , does the host image have any dependency on kata-containers functionality ?

**Comment by fidencio** [comment]
We have some dependency on the host kernel, but anything that's already out there should be good enough. :-)

We have our CI testing Kata Containers on Fedora / Ubuntu / RHEL / OpenAnnolis / etc.
As Amazon Linux is a rebuild of Fedora, things should work.  I'm not sure, though, if Amazon Linux comes with SELinux enforced, and what would be the trickery needed to get it working there.

**Comment by fidencio** [comment]
I'm closing this one as it'll be solved by the PR pointed out in the first comment.

We can keep the discussions here, and please, feel free to re-open it in case you think your issue was not properly addressed.
