### ISSUE TITLE
Host Disk Passthrough

### ISSUE THREAD

**Issue by naveenbansalntnx** [kata-containers/kata-containers#7458]
I have a kubernetes cluster with kata installed on it. I am successfully able to create pods which uses kata-runtime.
How do I configure an instance disk passthrough to a pod on an EC2 instance ?
I did found [this](https://github.com/kata-containers/kata-containers/blob/main/docs/use-cases/Intel-GPU-passthrough-and-Kata.md) but my disk device got unlisted from **/sys/bus/pci/drivers/nvme/** but I don't see it under **/sys/bus/pci/drivers/vfio-pci/** or in output of **ls -l /dev/vfio**

**Comment by yuxi191231** [comment]
> I have a kubernetes cluster with kata installed on it. I am successfully able to create pods which uses kata-runtime. How do I configure an instance disk passthrough to a pod on an EC2 instance ? I did found [this](https://github.com/kata-containers/kata-containers/blob/main/docs/use-cases/Intel-GPU-passthrough-and-Kata.md) but my disk device got unlisted from **/sys/bus/pci/drivers/nvme/** but I don't see it under **/sys/bus/pci/drivers/vfio-pci/** or in output of **ls -l /dev/vfio**

Hello, I have the same problem, have you solved it?
