### ISSUE TITLE
Speed up Travis CI tests

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#748]
Now one travis CI job may take 20 minutes to run. From one of jobs we can see that the most time consumed steps are:

*ordered by stage of lifecycle*

|Stage | Step| Time used| Solution |Action|
|---|---|---|---|---|
|`before_install`|ci/setup.sh |30s| Install packages for Rust | |
|`install`|ci/install_rust.sh |30s|  | deleted |
|`install`|make -C ${TRAVIS_BUILD_DIR}/src/agent |370s| 1. Dose `sccache` work ? Need verify, installing `sccache` may take a long time too. <br> 2. Or use travis provided Rust, does travis support one `.travis.yaml` with two languages?  It seems not, so can we let this `.travis.yaml` run as a Rust project and install go manually (installing go only take 5s) | use cache|
|`install`|make -C ${TRAVIS_BUILD_DIR}/src/agent check |150s|  | use cache|
|`before_script`|ci/install_go.sh |5s| Since travis CI environment includes go, so this step should be deleted | no changes|
|`before_script`|ci/install_vc.sh |30s| Since there is no independent  `virtcontainers`, deleting it will be OK ? | deleted|
|`before_script`|make -C ${TRAVIS_BUILD_DIR}/src/runtime |60s|  | no changes|
|`before_script`|make -C ${TRAVIS_BUILD_DIR}/src/runtime test| 60s|  | no changes|
|`script`|ci/static-checks.sh |8s|  | as said [here](https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server), `cargo  fmt` should after `cargo build`, and in Kata containers, `cargo fmt`  will fail if run before `make src/version.rs` |

And also :
- about the check sequence, can we move lightweight `ci/static-checks.sh` to an early stage ?
- for `cargo test`, use `--test-threads <N>` options
- for `cargo build`, use `--jobs <N>` options

**Notes:**

- Travis build VM has 2 cores

**Comment by jodh-intel** [comment]
Nice summary @liubin ! sccache would definitely be worth investigating. I use it locally with rust. Also note: https://docs.travis-ci.com/user/caching so we could build binaries and store them in the Travis cache (although I wonder if we should look at whethert here is an equivalent for Jenkins).

**Comment by liubin** [comment]
From https://travis-ci.org/github/kata-containers/kata-containers/jobs/729008968 we can see, `make -C ${TRAVIS_BUILD_DIR}/src/agent` costed time is reduced from 370s to 115s, and `make -C ${TRAVIS_BUILD_DIR}/src/agent check` reduced from 150s to 15s.

And total time is 8-9 minutes.

But how to [caches expiration](https://docs.travis-ci.com/user/caching/#caches-expiration) is the new problem, may be the directly way is to [delete it through API or command-line tool](https://docs.travis-ci.com/user/caching/#clearing-caches). If there is no storage limits for caches, we should not worry about it then.

**Comment by liubin** [comment]
As https://github.com/travis-ci/travis-ci/issues/2131#issuecomment-70407972 said, saved caches are not a problem for users, so we should not worry about storage for caches.
