### ISSUE TITLE
Add top-level Makefile

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#75]
We need a top-level `./Makefile` that supports:

- `make agent` (runs `src/agent/Makefile`)
- `make` (builds "everything" (currently just the agent))

**Comment by fidencio** [comment]
@jodh-intel, I'm visiting this one as I'm going through the issues with the "needs-review" label.
We currently have a top  level Makefile, which could be improved.  Considering that, I'll close this one in favour of #331.

Please, feel free to re-open the issue in case something was missed from my side.

**Comment by fidencio** [comment]
And now I noticed that #331 was already closed, but we still didn't achieve what you suggested here.
I'm not sure what to do with this one.  I'm in favour of having a more targets, such as "make agent", "make runtime", and so on.

Please, @jodh-intel, would you mind to chime in here?

**Comment by fidencio** [comment]
Also, I think this is a good first issue, and I'm adding the label accordingly.
