### ISSUE TITLE
kata-deploy: systemctl does not work inside container

### ISSUE THREAD

**Issue by heilerich** [kata-containers/kata-containers#7511]
# Description of problem

Since a recent upgrade of host OS and kata-containers to `3.1.3` the kata-deploy DaemonSet does not work as expected anymore. Specifically, it fails to reload the container runtime by executing `systemctl daemon-reload` and `restart`.

# Expected result

Container runtime is reloaded.

# Actual result

systemctl exits with `Running in chroot, ignoring request:` despite the ` /var/run/dbus/system_bus_socket` being mounted correctly.

# Further information

Since systemctl is so great at providing error messages 🙄 I can only guess what is going wrong. I suspect that maybe a version mismatch between the systemctl shipped with the container and systemd running on the host has something to do with this?

# Potential solution

Without investigating the apparent communication problem of systemctl much further a quick fix seems to be just to use the hosts systemctl by just replacing all systemctl commands in the deploy script with `nsenter -t1 -m systemctl ...` since we are running as root anyways. This should also make the whole process more portable, more robust against changes on system upgrades and remove the dependency on the systemctl shipped with the container image.

Is there any reason why this shouldn't be the default?

**Comment by heilerich** [comment]
We are running Flatcar Linux, a CoreOS fork

**Comment by jepio** [comment]
Thank you for being a Flatcar user. We wanted to fix this issue in the past, I just opened a PR to do what you suggested.
