### ISSUE TITLE
Enable block device (without snapshotter) for CH in runtime-rs

### ISSUE THREAD

**Issue by cmaf** [kata-containers/kata-containers#7539]
Using ctr with runtime-rs and adding a block device is working with `--snapshotter devmapper`, but not `--device /dev/loop[dev]`. 

```
$ sudo ctr run --device /dev/loop19 --runtime "io.containerd.kata.v2" -rm -t quay.io/prometheus/busybox:latest test_container sh

ctr: failed to create shim task: Others("failed to handler message create container\n\nCaused by:\n    0: create\n    1: do handle device\n    2: failed to create deviec\n    3: failed to create device\n    4: unsupported driver type "): unknown

```

Debug to see if device type is something other than BlockDevice and enable for CH in runtime-rs.

**Comment by Apokleos** [comment]
Hi @cmaf,  Maybe, the driver setting is not correct. what's block_config.driver_option ?

**Comment by cmaf** [comment]
@Apokleos I think it should be `virtio-blk-pci` but right now it showing up as empty, I'm trying to figure out why.

**Comment by Apokleos** [comment]
The block_config.driver_option comes from the configuration.toml, and the block_device_driver in configuration is first translated into `blockdev_info.block_device_driver`. When block volume created, the driver_option is set with `block_device_driver`. 
Maybe, first of all, ensure the  [block_driver](https://github.com/kata-containers/kata-containers/blob/b365bef570f1512d5166ce0870f3c9620f69971d/src/runtime-rs/crates/resource/src/volume/block_volume.rs#L45) is correct.

**Comment by Apokleos** [comment]
> @Apokleos I think it should be `virtio-blk-pci` but right now it showing up as empty, I'm trying to figure out why.
Hi, It's indeed a bug, and @Tim-0731-Hzt will repair it.
