### ISSUE TITLE
e2e: [sig-node] Probing container should be restarted with a GRPC liveness probe

### ISSUE THREAD

**Issue by ldoktor** [kata-containers/kata-containers#7565]
# Description of problem

The e2e test `[sig-node] Probing container should be restarted with a GRPC liveness probe [NodeConformance] [Suite:openshift/conformance/parallel]` is failing with `{  fail [k8s.io/kubernetes@v1.26.1/test/e2e/framework/pod/pod_client.go:99]: Aug  7 10:00:56.547: Error creating Pod: Pod "test-grpc-9a42f811-558f-4b0f-b14a-228dc9654b98" is invalid: spec.containers[0].livenessProbe: Required value: must specify a handler type
Ginkgo exit error 1: exit with code 1}` when using kata-containers (ocp 4.14): https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40790/rehearse-40790-periodic-ci-kata-containers-kata-containers-main-next-e2e-tests/1688473839253590016

Works well when not using kata-containers (tested manually).

# Expected result

Test should PASS

# Actual result

Test FAILs

# Further information

Steps to reproduce (when we leave-out the "deploy kata-containers" step the test is PASSing):

```bash
# Configure "kubeconfig"

# Deploy kata-containers and webhook
cd kata/kata-containers/tests/.ci/openshift-ci
./test.sh
KATA_RUNTIME=kata-qemu .cluster/deploy_webhook.sh

# Disable security
oc adm policy add-scc-to-group privileged system:authenticated system:serviceaccounts
oc adm policy add-scc-to-group anyuid system:authenticated system:serviceaccounts
oc label --overwrite ns default pod-security.kubernetes.io/enforce=privileged pod-security.kubernetes.io/warn=baseline pod-security.kubernetes.io/audit=baseline

# Run e2e
cd openshift/origin
echo '"[sig-node] Probing container should be restarted with a GRPC liveness probe [NodeConformance] [Suite:openshift/conformance/parallel]"' | ./openshift-tests run --provider azure -f -
```

Some of the other liveness tests are already disabled in CI: https://github.com/kata-containers/kata-containers/issues/2464 but this issue seems a bit different.

**Comment by arc9693** [comment]
I would like to take this up.
