### ISSUE TITLE
failed to create shim task: Unknown device type vfio-gk: unknown 

### ISSUE THREAD

**Issue by 291723286** [kata-containers/kata-containers#7612]
When creating a guest os for gpu pass-through. Failed to create a kata container. when create kata containers using the default guest os is normal. The pass-through gpu device is right displayed in the container. Are there any base packages that are not included in rootfs-builder/ubuntu/docker.in ? please help .build in docker for guest os img

**Comment by 291723286** [comment]
resolve

**Comment by liricky** [comment]
> resolve

Hello, I met the same problem when I was starting a kata container with containerd.

**Comment by dingzl8018** [comment]
> resolve

**Comment by dingzl8018** [comment]
hi [291723286](https://github.com/291723286) , I also met the same issue, how did u resolve it ?

**Comment by liricky** [comment]
> hi [291723286](https://github.com/291723286) , I also met the same issue, how did u resolve it ?

@dingzl8018 I ran into this problem when installing with kata-deploy, and when I build from source, this error disappeared.  If you find anything special, I will be really delighted to know.
