### ISSUE TITLE
Agent Policy should be supported on s390x, powerpc64

### ISSUE THREAD

**Issue by danmihai1** [kata-containers/kata-containers#7616]
**Which feature do you think can be improved?**

The new Agent Policy from https://github.com/kata-containers/kata-containers/issues/7573

**How can it be improved?**

Add support for s390x, powerpc64. 

**Additional Information**

N/A

**Before raising this enhancement request**

Have you looked at the [limitations document](https://github.com/kata-containers/kata-containers/blob/main/docs/Limitations.md)?
Yes

**Comment by Amulyam24** [comment]
Hi @BbolroC , was able to successfully build opa binary, Thanks for the instructions!
```
# file _release/0.55.0/opa_linux_ppc64le_static
_release/0.55.0/opa_linux_ppc64le_static: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, with debug_info, not stripped
```
Next step would be to make changes for building it.

Also, they have workflows to publish the binaries for amd, not sure how open they are to supporting other architectures. I have seen previous PRs for arm & [ppc64le support](https://github.com/open-policy-agent/opa/pull/5360) were closed.

**Comment by BbolroC** [comment]
FYI: for a native build:

```
$ git clone -b v0.55.0 https://github.com/open-policy-agent/opa.git && cd opa
$ export WASM_ENABLED=0
$ export DOCKER_RUNNING=0
$ make ci-go-ci-build-linux-static
```

**Comment by BbolroC** [comment]
I will raise a PR for this. Thanks.

**Comment by zvonkok** [comment]
@Amulyam24  @danmihai1  Arm64 support was added in `22 and is published https://github.com/open-policy-agent/opa/releases/download/v0.55.0/opa_linux_arm64_static but only "static" builds. Can we add `aarch64` support as well? I can do some tests on my side to verify.

**Comment by zvonkok** [comment]
Looks like only an update to the `versions.yaml` would be needed and how those versions are deduced in the build scripts.
