### ISSUE TITLE
runtime: Unused `SharedVersions` field in the `VhostUserDevice` struct

### ISSUE THREAD

**Issue by gkurz** [kata-containers/kata-containers#7720]
```
[main]kata-containers$ git grep -C 1 SharedVersions
src/runtime/pkg/govmm/qemu/qemu.go-     QueueSize      uint32 //size of virtqueues
src/runtime/pkg/govmm/qemu/qemu.go:     SharedVersions bool   //enable virtio-fs shared version metadata
src/runtime/pkg/govmm/qemu/qemu.go-     VhostUserType  DeviceDriver
--
src/runtime/pkg/govmm/qemu/qemu.go-     }
src/runtime/pkg/govmm/qemu/qemu.go:     if vhostuserDev.SharedVersions {
src/runtime/pkg/govmm/qemu/qemu.go-             deviceParams = append(deviceParams, "versiontable=/dev/shm/fuse_shared_versions")
```

1. this would add a `versiontable` property that isn't supported by upstream QEMU
2. this is dead code since `virtcontainers` isn't setting `SharedVersions` to `true`

This should be just dropped.

**Comment by JadeFlute0127** [comment]
This looks like a good starting project, please allow me to try fixing it

**Comment by gkurz** [comment]
> This looks like a good starting project, please allow me to try fixing it

Hi @JadeFlute0127 !

You are welcomed to contribute. Please have a look at the [contributing guidelines](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md) and open a PR.

Cheers,

--
Greg

**Comment by JadeFlute0127** [comment]
> > This looks like a good starting project, please allow me to try fixing it
> 
> Hi @JadeFlute0127 !
> 
> You are welcomed to contribute. Please have a look at the [contributing guidelines](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md) and open a PR.
> 
> Cheers,
> 
> -- Greg

thanks a lot, my pleasure

**Comment by kalil-pelissier** [comment]
Hi @gkurz :wave:!
If this issue is still up to date I will be happy to take a look at it.

**Comment by gkurz** [comment]
> Hi @gkurz 👋! If this issue is still up to date I will be happy to take a look at it.

Bonjour @kalil-pelissier, I haven't rechecked but if the issue still stands, feel free to tackle it.
