### ISSUE TITLE
Sometimes Travis CI failed randomly

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#782]
Not 100%, but sometimes.

From yesterday Travis fails for randomly by two reasons:

```
---- mount::tests::test_init_rootfs stdout ----
thread 'mount::tests::test_init_rootfs' panicked at 'Should pass. Got: Err(No such file or directory (os error 2))', rustjail/src/mount.rs:982:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
```

From: https://api.travis-ci.org/v3/job/729299183/log.txt

Or

```
=== RUN   TestNewConsole
    TestNewConsole: console_test.go:28: 
        	Error Trace:	console_test.go:28
        	Error:      	Received unexpected error:
        	            	open /dev/ptmx: permission denied
        	Test:       	TestNewConsole
        	Messages:   	failed to create a new console: open /dev/ptmx: permission denied
--- FAIL: TestNewConsole (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xec75c2]

```
From: https://api.travis-ci.org/v3/job/729310337/log.txt

**Comment by devimc** [comment]
@liubin in the logs that you mention I see that the `test_init_rootfs` is passing

**Comment by liubin** [comment]
Sorry @devimc I pasted a miss URL, two are both logs for `console_test`.  I can't find it again from my browser history now. I will add the new log if the same error occurs.

**Comment by liubin** [comment]
https://github.com/kata-containers/kata-containers/pull/811 may be fix this issue

**Comment by bergwolf** [comment]
Turns out that #811 didn't fix it. Let's track it here and let #811 do its own work on fix the static checkers.
