### ISSUE TITLE
rust agent cannot work with firecracker

### ISSUE THREAD

**Issue by yyyeerbo** [kata-containers/kata-containers#79]
From log, we can see rust agent listen successfully. But it receives nothing afterwards. Not sure fc forwarding problem or grpc problem

**Comment by yyyeerbo** [comment]
[fc-kernel.log](https://github.com/kata-containers/kata-containers/files/3823297/fc-kernel.log)

**Comment by yyyeerbo** [comment]
After some debug, this issue probably is bug in grpc.
socat + nc-vsock works fine
socat + go agent works fine
socat + rust agent does not work. 
After CONNECT 1024\n is send to xxxxx.hvsock unix domain socket, socat receive some byte from rust agent. but rust agent receives nothing.. It look like when CONNECT 1024\n, vmm -> kernel -> grpc, grpc internals doesn't handle it correctly and then returns something. possibly
@teawater  will continue debugging grpc

**Comment by bergwolf** [comment]
This have been fixed. Please reopen it if seeing it again.
