### ISSUE TITLE
runtime-rs: ch: Implement device removal

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#7945]
Implement device removal handling for the runtime-rs Cloud Hypervisor driver.

**Comment by jodh-intel** [comment]
Hi @amshinde and @cmaf - any updates on this one?

**Comment by amshinde** [comment]
As seen here:https://github.com/kata-containers/kata-containers/blob/0f80dc636c3a4df6eb5cc3034e5702c87c17778e/src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md?plain=1#L101, the only device removal api supported is `VmRemoveDevicePut` which is removal of vfio devices. We already support that. 
Removal of block and other devices is not supported with clh api as it is strictly not required. I think we can mark this as done.

**Comment by amshinde** [comment]
@cmaf @jodh-intel I am closing this one. 
@cmaf If you feel there is any work left to do on this, please feel free to reopen.
