### ISSUE TITLE
CI: Artifacts for GHA only retained for 3 days

### ISSUE THREAD

**Issue by gkurz** [kata-containers/kata-containers#8000]
The new GHA-based CI builds all the artifacts, cache them and then proceeds to the running the actual tests. This is fine except that the artifact are only retained for a short period (~3 days at the present time) and not automatically regenerated.
This causes  `Error: Unable to find any artifacts for the associated workflow`  failures when tests are run again afterwards.
Another problem is that only maintainers are allowed to manually run GHA, which is required to regenerate the artifacts.

This issue is a placeholder for potential improvements.

**Comment by fidencio** [comment]
Fow whoever wants to work on this: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#configuring-a-custom-artifact-retention-period

Our limit is 90 days, I think we could explicitly set it to 15 days.
