### ISSUE TITLE
Building agent-ctl alters git managed files in Kata2

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#801]
# Description of problem

When building the `agent-ctl` tool from source:

```
$ cd tools/agent-ctl
$ cargo build
$ git status
```

# Expected result

No checked-in files should be altered by a build.

# Actual result

```
$ git status
On branch 2.0-dev
Your branch is up to date with 'origin/2.0-dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Cargo.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

# Further information

I'm not sure what the right solution here is, because I'm not really sure what is triggering cargo to update the lockfile.  I think we probably want to just update once and check in the result, but I'm not certain.

**Comment by liubin** [comment]
Close via #884
