### ISSUE TITLE
ci: crio: Test readonly volume for pods is failing

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#8034]
```
not ok 1 Test readonly volume for pods
# (from function `setup' in test file k8s-file-volume.bats, line 17)
#   `tmp_file=$(exec_host mktemp /tmp/file-volume-test-foo.XXXXX)' failed with status 2
# /home/runner/actions-runner/_work/kata-containers/kata-containers/tests/integration/kubernetes/tests_common.sh: line 51: return: chroot:: numeric argument required
# Error from server (NotFound): pods "test-file-volume" not found
#
# /home/runner/actions-runner/_work/kata-containers/kata-containers/tests/integration/kubernetes/tests_common.sh: line 51: return: chroot:: numeric argument required
```

From the Kata Containers logs:
```
chroot: cannot change root directory to '/host': Operation not permitted
```

I wonder if this is related to a stricter set of caps that CRI-O uses, as we haven´t  seen this one failing on containerd.

**Comment by gkurz** [comment]
> ```
> not ok 1 Test readonly volume for pods
> # (from function `setup' in test file k8s-file-volume.bats, line 17)
> #   `tmp_file=$(exec_host mktemp /tmp/file-volume-test-foo.XXXXX)' failed with status 2

This is `exec_host()` or `mktemp` failing.

> ```
> # /home/runner/actions-runner/_work/kata-containers/kata-containers/tests/integration/kubernetes/tests_common.sh: line 51: return: chroot:: numeric argument required
> ```

This looks like a bug in `exec_host()`...

```
# Runs a command in the host filesystem.
exec_host() {
        node="$(kubectl get node -o name)"
        # `kubectl debug` always returns 0, so we hack it to return the right exit code.
        command="$@"
        command+='; echo -en \\n$?'
        output="$(kubectl debug -qit "${node}" --image=alpine:latest -- chroot /host bash -c "${command}")"
        kubectl get pods -o name | grep node-debugger | xargs kubectl delete > /dev/null
        exit_code="$(echo "${output}" | tail -1)"
```
It seems that `${command}` didn't even run otherwise we'd get a numerical status here.
/me curious to see the actual output of `kubectl debug`
```
        echo "$(echo "${output}" | head -n -1)"
        return ${exit_code}
}
```
> ```
> # Error from server (NotFound): pods "test-file-volume" not found
> #
> # /home/runner/actions-runner/_work/kata-containers/kata-containers/tests/integration/kubernetes/tests_common.sh: line 51: return: chroot:: numeric argument required
>```
> 
> From the Kata Containers logs:
> 
> ```
> chroot: cannot change root directory to '/host': Operation not permitted
> ```

This error comes from https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-debug/debug.sh#L10 , meaning that Kata Container logs could not even be collected... but since the first error happens during `setup()`, I'm not even sure that the test did run at all actually.

> I wonder if this is related to a stricter set of caps that CRI-O uses, as we haven´t seen this one failing on containerd.

Maybe... @littlejawa might know better.
