### ISSUE TITLE
ARM CI fail on k8s-oom test

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#809]
k8s-oom.bat is a new test case. it can't pass on ARM  for now. I will raise a PR to skip it on ARM first, as this may block some PR.

> ok 1 Setting sysctl
1..1
not ok 1 Test OOM events for pods
(in test file k8s-oom.bats, line 30)
 `kubectl wait --for=condition=Ready pod "$pod_name"' failed
INFO: k8s configured to use runtimeclass
pod/pod-oom created
error: timed out waiting for the condition on pods/pod-oom
pod "pod-oom" deleted
Failed at 84: bats "${K8S_TEST_ENTRY}"

@jodh-intel  @GabyCT @liubin

**Comment by jodh-intel** [comment]
Hi @jongwu - can you give details here as to why it cannot work on ARM currently?

**Comment by jongwu** [comment]
@jodh-intel  yeah, I have not figured out why it can't pass on ARM, so I need skip it first then find the root cause.

**Comment by jodh-intel** [comment]
Any update on this @jongwu ?

**Comment by jongwu** [comment]
just close it for now.
