### ISSUE TITLE
clh: code generated by openapi-generator is wrong 

### ISSUE THREAD

**Issue by devimc** [kata-containers/kata-containers#810]
According to the openapi.yaml file, the type for the EPC sections size must be a `uint64`

https://github.com/kata-containers/kata-containers/blob/740c45ac615dd0147abc19c76260bd7fc6a5b8d9/src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml#L1155-L1162

but in the generated code, the type is an `int32`

https://github.com/kata-containers/kata-containers/blob/740c45ac615dd0147abc19c76260bd7fc6a5b8d9/src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_sgx_epc_config.go#L12-L15

**Comment by jodh-intel** [comment]
Blocked on new release of clh that includes https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1760.

**Comment by likebreath** [comment]
This was being fixed in commit: https://github.com/kata-containers/kata-containers/commit/ea1cb37b5969b4f83e4ff814912816d666025a12#diff-b4d62d9713213d6e8e44957a67629fdd138e4a0c230cd6373ee85827443213c5.
