### ISSUE TITLE
CC: Basic pull image on guest

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8103]
This is the first issue in a series to get the pull image functionality over from the `CCv0` branch. In order to make the porting as easy as possible, I'm proposing that we break it down into small functions and we can iterate and build upon. The scope of this is therefore a basic image pull on guest of an unencrypted, unsigned image, in a public registry, with no pre-caching if the pause image.

Initially I/we'd hoped to be able to cherry-pick over commits from `CCv0`, but given how much iteration there has been we're going to need to copy over chunks of the code and tests, improving as we go. Ideally we'll add `co-authored` tags to reflect the original authors though.

## Things to note/include with this work
- We need to add the dependency of the image-rs crate into the kata-agent as this has the logic that does the pull. Given that it's quite a large amount of code and dependencies to drag in I think we might want to consider having a new kata-agent feature for this e.g. `guest_pull` (or something better).
- We shouldn't need to include anything related to the attestation-agent, confidential-data-hub or api-server-rest though as I don't think this is any requirement for secrets/resources for this pull
- In order to build this we need a dependency on `clang` to build the agent, so we might need to update some of the builds something like https://github.com/kata-containers/kata-containers/commit/32d347aa25b7630cc3865c64ec1bcb1faa48a761 for this (though the static-checks have changed a lot since then)
- We will need to pull some of https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/image_rpc.rs, but I don't think we need `get_security_config`, ` pull_image`,`cid_from_request`, `unpack_pause_image` or the imageClient config setting.
- I think we will need the logic related to `HTTP_PROXY` and `NO_PROXY` (https://github.com/kata-containers/kata-containers/pull/3957) in order to do the pull on thinks that run behind the firewall? *See questions*
- We'll need code relating to the image pull on guest with nydus snapshotter from https://github.com/kata-containers/kata-containers/pull/7676/commits which might also build on some changes in https://github.com/kata-containers/kata-containers/pull/7688, so we might need some help from Chengyu to unpick which bits are needed when just doing pull on guest
- Do we need to make device type optional changes from https://github.com/kata-containers/kata-containers/commit/deee3cf4a243e2db5ef9cce5c42d4a77cef6892a *See questions*
- We need to bring over/rewrite a new test case like `Test can pull an unencrypted image inside the guest without signature config` for [Kubernetes](https://github.com/kata-containers/tests/blob/CCv0/integration/kubernetes/confidential/agent_image.bats) and [containerd](https://github.com/kata-containers/tests/blob/CCv0/integration/containerd/confidential/agent_image.bats) test jobs - probably as a new test file. This will need us to port over a bunch of the nydus-snapshotter install and config, which I think it mostly in https://github.com/kata-containers/tests/pull/5775
- There is no TEE specific code, so this should be able to run on a non-TEE and all the TEEs, but there is a question of how we package these changes in kata-deploy to enable them

## Questions
- How do we decided whether to build the kata-agent with the `guest_pull` feature, should it be default? If not, how we choose how to package these new changes in kata-deploy? What about the crictl testing?
- Do we still need `http_proxy` and `no_proxy`? Is it related to the pull image that runs on the TDX box behind the Intel firewall and needed for GHA K8s tests on tdx? @arronwy @fidencio 
- Do we need to make device type optional with this: https://github.com/kata-containers/kata-containers/commit/deee3cf4a243e2db5ef9cce5c42d4a77cef6892a, or could we spin that out separately? @arronwy 
- Do we need a new GHA 'job' for each of the TEEs to run this code given that it requires nydus-snapshotter set-up?
- Can we check the host filesystem on the AKS nodes to check that the image hasn't been pulled on the host? Assuming not then we can only test the host side wasn't pulled on other platforms, or with crictl

## Acceptance Criteria

For each supported platform:

_**Scenario: Image pull on guest works on Kubernetes**_
**Given** I have a version of kata deployed on Kubernetes with a guest image that has an agent with `guest_pull` feature enabled and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml)
**When** I try and create a pod from a public container (e.g. `quay.io/prometheus/busybox:latest`)
**Then** The pod is successfully created

_**Scenario: Image pull on guest works with crictl**_
**Given** I have a version of kata installed with a guest that has an agent with `guest_pull` feature enabled and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml)
**When** I try and create a pod from a public container (e.g. `quay.io/prometheus/busybox:latest`)
**Then** The pod is successfully created
  **And** when I check the host filesystem with:
```
local pod_id=$(crictl pods --name "$sandbox_name" -q)
	rootfs=($(find /run/kata-containers/shared/sandboxes/${pod_id}/shared \
		-name rootfs))
```
then I can see that no rootfs were created on the host.

**Comment by ChengyuZhu6** [comment]
>We'll need code relating to the image pull on guest with nydus snapshotter from https://github.com/kata-containers/kata-containers/pull/7676/commits which might also build on some changes in https://github.com/kata-containers/kata-containers/pull/7688, so we might need some help from Chengyu to unpick which bits are needed when just doing pull on guest 
Absolutely, I'd be glad to help to refactor related code.

**Comment by stevenhorsman** [comment]
With some of the challenges and issues that we've see landing this in 0.8 I think that having some mixed runtime workloads as part of this test might be interesting - e.g. create a runc nginx pod, then one that is offloaded with nydus and ensure that the offload still works.

@huoqifeng might have some other suggestions too and then we can update the acceptance criteria to add some more scenarios once people are happy

**Comment by huoqifeng** [comment]
Thanks @stevenhorsman collectedall stuff in a single ticket, based on the experience/problems, I think we need add some unit test cases as following matrix which refers to same workload image:

			runc     tee-pod-without-annotation       tee-pod-without-annotation      another-tee-pod-with-annotation
									x
						x			x
						x			x					x
			  x			x			x					x

**Comment by ChengyuZhu6** [comment]
https://github.com/kata-containers/kata-containers/issues/8504

**Comment by ChengyuZhu6** [comment]
@stevenhorsman Should we support pulling the pause image on the guest? For `basic pull image on the guest` task, there is no pause image stored in the rootfs. This would cause a failure if we just pull the container image on the guest. I have submitted a PR (https://github.com/containerd/containerd/pull/9419) to the containerd repo to support pulling the pause image on the guest. Do you think this makes sense?

**Comment by stevenhorsman** [comment]
Hey Chengyu, I probably missed something important, but my intention when laying out the issues was that for this issue we'd just pull pause on the guest like a normal container image.

Then the follow on issue https://github.com/kata-containers/kata-containers/issues/8104 is where we re-introduce the ability to cache the pause image on the guest so we then add the special case to use that rather than pull it.

In the absence of containerd fixing the pause annotation, if we merge the two together and add pause image caching, does that help, or is the probably that when nydus tries to have the image name to pass through to the create container request in the agent we have no way to know that it was pause?

**Comment by ChengyuZhu6** [comment]
>In the absence of containerd fixing the pause annotation, if we merge the two together and add pause image caching, does that help

Yes, it would help to fix the issue in CoCo.

**Comment by stevenhorsman** [comment]
> Yes, it would help to fix the issue in CoCo.

Okay I think the best path is to merge these two issues then especially as the pause image caching is a performance/security improvement and doesn't impact the user experience, or test cases? Sorry for any inconvenience in splitting them.

**Comment by ChengyuZhu6** [comment]
>or is the probably that when nydus tries to have the image name to pass through to the create container request in the agent we have no way to know that it was pause?

The snapshotter can identify whether an image is for sandbox or for container, but it faces a limitation in getting the pause image name when the image is for sandbox. This is because the pause image name is not included in the annotations that are passed from containerd.

**Comment by ChengyuZhu6** [comment]
> Okay I think the best path is to merge these two issues then especially as the pause image caching is a performance/security improvement and doesn't impact the user experience, or test cases? Sorry for any inconvenience in splitting them.
Thanks, I agree with it.

**Comment by stevenhorsman** [comment]
> The snapshotter can identify whether an image is for sandbox or for container, but it faces a limitation in getting the pause image name when the image is for sandbox. This is because the pause image name is not included in the annotations that are passed from containerd.

Okay, so as long as we are happy with including the same version of pause image each time (and I guess we should bump it to 3.9 if that is the still the latest), then pre-building it into the guest image and having the kata-agent use that like `CCv0` sounds do-able. Thanks for the extra info :)

**Comment by wainersm** [comment]
> 
>     * In order to build this we need a dependency on `clang` to build the agent, so we might need to update some of the builds something like [32d347a](https://github.com/kata-containers/kata-containers/commit/32d347aa25b7630cc3865c64ec1bcb1faa48a761) for this (though the static-checks have changed a lot since then)
> 

@stevenhorsman could you please expand a little bit on this `clang` thing? https://github.com/kata-containers/kata-containers/pull/8484 didn't change (or I didn't notice) the build scripts to install clang.

**Comment by ChengyuZhu6** [comment]
> > ```
> > * In order to build this we need a dependency on `clang` to build the agent, so we might need to update some of the builds something like [32d347a](https://github.com/kata-containers/kata-containers/commit/32d347aa25b7630cc3865c64ec1bcb1faa48a761) for this (though the static-checks have changed a lot since then)
> > ```
> 
> @stevenhorsman could you please expand a little bit on this `clang` thing? #8484 didn't change (or I didn't notice) the build scripts to install clang.

I apologize. This is my responsibility. I overlooked this task.

**Comment by ChengyuZhu6** [comment]
I have add the dependency of `clang` (https://github.com/kata-containers/kata-containers/pull/8484/commits/8044c47f2689377dbab0dab9a47f0d9f91c34656) , which the rootfs is built successfully in my local machine by the command ` script -fec 'sudo -E USE_DOCKER=true GUEST_PULL=yes ./rootfs.sh "${distro}"'`
