### ISSUE TITLE
CC: Add cosign signature verification to image pull on guest

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8120]
This feature builds upon the initial basic image pull work in https://github.com/kata-containers/kata-containers/issues/8103 as one of the possible next steps to extend it to support more of the current `CCv0` feature set.

The scope of this is to add the ability to pull an container image on the guest and following the rules in a provided policy (using a provided public gpg key) we have validate the signature of the image with the cosign signing scheme, if required to ensure it hasn't been modified before we run an pod from it.

Initially I/we hoped to be able to cherry-pick over commits from `CCv0`, but given how much iteration there has been we're going to need to copy over chunks of the code and tests, improving as we go. Ideally we'll add `co-authored` tags to reflect the original authors though.

## Things to note/include with this work
>**Note**: Depending on whether encrypted image support has been implemented first there is potentially a few things that might have already been completed from the list

- With this feature we'll build on the guest-components integration already done and add signature specifics like:
- The signatures part of [`get_security_config` in image_rpc.rs](https://github.com/kata-containers/kata-containers/blob/1ad87faaf4d3068569d99c270df640e41465c410/src/agent/src/image_rpc.rs#L154-L160), though it should probably be refactored out of that method
- The addition in agent config.rs of `agent.image_policy_file`, (via https://github.com/kata-containers/kata-containers/commit/03d83914041fc8dc2bd7815414a619d94cbaf82c)
- Add addition of `agent.enable_signature_verification` config from https://github.com/kata-containers/kata-containers/pull/5552

- New tests
  - There are five potential new test cases I'd suggest, that are detailed in the acceptance criteria (some of which could be covered by unit tests). The code for this code be based on the existing `CCv0` tests for [crictl](https://github.com/kata-containers/tests/blob/6cf430642335c010014b5d9355a861328c4213ed/integration/containerd/confidential/agent_image.bats#L90-L109) and [kubernetes](https://github.com/kata-containers/tests/blob/6cf430642335c010014b5d9355a861328c4213ed/integration/kubernetes/confidential/agent_image.bats#L96-L111) and [lib functions](https://github.com/kata-containers/tests/blob/6cf430642335c010014b5d9355a861328c4213ed/integration/confidential/lib.sh#L288-L309), but we want to work to make them easier to apply to different KBCs/TEE by extracting out the KBC/TEE logic into library functions, so the test cases are cleaner, similar to the approach done in https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-confidential.bats rather than a pure cherry-pick
  - We need to set-up the sample KBS resources: based on #8870
  - We also want to automatically create and sign (if applicable) the test images that we are using as part of a workflow like we do with the unencrypted test image: https://github.com/kata-containers/kata-containers/tree/main/tests/integration/kubernetes/runtimeclass_workloads/confidential in order to control this ourselves and not rely on manual creation in our pipelines
    > **Note:** we need to specify different test images for each of the different arches as the digest will be different for each, so we can't use a multi-arch manifest here (but we can still create it in a multi-arch way

## Questions
- In `CCv0` we decided to make `agent.enable_signature_verification` default to true for security reasons and therefore had to set `agent.enable_signature_verification=false` as a default in the configuration.toml (see https://github.com/kata-containers/kata-containers/pull/5552). When merging into main I think we want to have a discussion if this configuration should still be the default in `main` and what configuration.toml/runtime classes we'll have specifically for CC cases (which related back to a kata-deploy piece)

## Acceptance Criteria

For each supported platform (different TEEs and kubernetes/crictl):

For all scenarios the common context is:
> **Note:** this assumes that `agent.enable_signature_verification` defaults to true

**Given** I have a version of kata deployed with a guest image that has an agent with guest_pull feature enabled and the attestation-agent installed, as well as the and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml) and the kata configuration and doesn't have the setting `agent.enable_signature_verification=false` (unless stated)

**Scenario:** Regression: Create a pod from an unsigned image, on an `insecureAcceptAnything` registry works
**Given** A public unsigned container image *i* from registry *r* and a KBS resources configured to pass through a policy file of
```
{
    "default": [{"type": "insecureAcceptAnything"}]
}
```
e.g. for the offline_fs_kbc it would have a `/etc/aa-offline_fs_kbc-resources.json` file containing:
```
{
  "default/security-policy/test": "ewogICAgImRlZmF1bHQiOiBbeyJ0eXBlIjogImluc2VjdXJlQWNjZXB0QW55dGhpbmcifV0KfQ==",
}
```
is present in the guest image
**When** I try and create a pod from *i*
**Then** The pod is successfully created and runs

**Scenario:** Create a pod from an unsigned image, on a 'restricted registry' is rejected
**Given** A public unsigned container image *i* from registry *r* and a KBS resources, or agent config configured to read a policy file like:
```
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "<r>": [
                {
                    "type": "sigstoreSigned",
                    "keyPath": "kbs:///default/cosign-public-key/test"
                }
            ]
        }
    }
}
```

**When** I try and create a pod from *i*
**Then** The pod is not created an we get an appropriate error message in the logs e.g. `Validate image failed`

**Scenario:** Create a pod from a signed image, on a 'restricted registry' is successful
**Given** A public signed container image *s* signed with a key *k* from registry *r* and a KBS resources or agent config configured to read a policy file like:
```
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "<r>": [
                {
                    "type": "sigstoreSigned",
                     "keyPath": "kbs:///default/cosign-public-key/test"
                }
            ]
        }
    }
}
```
**And** the public gpg key is provide in the resource like:
```
"default/cosign-public-key/test": "<base64 encoding of k>"
```
**When** I try and create a pod from *i*
**Then** The pod is successfully created and runs

**Scenario:** Create a pod from a signed image, on a 'restricted registry', but with the wrong key is rejected
**Given** A public signed container image *s* signed with a key *k* and a different key *w* from registry *r* and a KBS resources or agent config configured to read a policy file like:
```
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "<r>": [
                {
                    "type": "sigstoreSigned",
                    "keyPath": "kbs:///default/cosign-public-key/test"
                }
            ]
        }
    }
}
```
**And** the public gpg key is provide in the resource like:
```
"default/cosign-public-key/test": "<base64 encoding of w>"
```
**When** I try and create a pod from *i*
**Then** The pod is not created an we get an appropriate error message in the logs e.g. `Validate image failed`

**Scenario:** Create a pod from an unsigned image, on a 'restricted registry' works if `enable_signature_verfication` is false
**Given** The kata configuration and has the setting `agent.enable_signature_verification=false` and a public unsigned container image *i* from registry *r* and a KBS resources configured or agent config configured to read a policy file like:
```
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "<r>": [
                {
                    "type": "sigstoreSigned",
                    "keyPath": "kbs:///default/cosign-public-key/test"
                }
            ]
        }
    }
}
```
**When** I try and create a pod from *i*
**Then** The signature check is not enforced, so the pod is created successfully

**Comment by ariel-adam** [comment]
@stevenhorsman to who should this issue be assigned to?

**Comment by ariel-adam** [comment]
Also question regarding what should the priority be :-) ?

**Comment by stevenhorsman** [comment]
> @stevenhorsman to who should this issue be assigned to?

This is blocked, so doesn't make sense to assign to anyone

**Comment by ariel-adam** [comment]
Tagged as status blocked

**Comment by ariel-adam** [comment]
@fitzthum can you check with James if someone from his team can take this?

**Comment by fitzthum** [comment]
> @fitzthum can you check with James if someone from his team can take this?

Sure, @magowan can you check with Steve on this?

**Comment by Xynnn007** [comment]
@ariel-adam @fitzthum I can help with `kata-agent` and `image-rs` side code, while I am not familiar with test things.

**Comment by Xynnn007** [comment]
@ariel-adam plz assign this to me.
