### ISSUE TITLE
CC: Support pulling images on guest from private registries

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8122]
This feature builds upon the initial basic image pull work in https://github.com/kata-containers/kata-containers/issues/8103 as one of the possible next steps to extend it to support more of the current `CCv0` feature set.

The scope of this is to add the ability to pull a container image on the guest from an private credential using authentication information passed to the guest in a 'secure' way.

Initially I/we'd hoped to be able to cherry-pick over commits from `CCv0`, but given how much iteration there has been we're going to need to copy over chunks of the code and tests, improving as we go. Ideally we'll add `co-authored` tags to reflect the original authors though.

## Things to note/include with this work
- Add the [code in image_rpc.rs](https://github.com/kata-containers/kata-containers/blob/1ad87faaf4d3068569d99c270df640e41465c410/src/agent/src/image_rpc.rs#L144-L151) that enables credentials checking by the image client
- Add the `agent.image_registry_auth` part of https://github.com/kata-containers/kata-containers/pull/6707/files to enable the option of using image credentials without the need for a KBS. 
  > **Note:** we don't have a good way to edit the rootfs image and test this out in kata-containers, so will probably need to rely on other consumers of this feature, like peer-pods to test this (which has some existing tests from `CCv0`-based days https://github.com/confidential-containers/cloud-api-adaptor/blob/86e0f6d1da7b13c6a292948cfcc670c35f32b7cd/src/cloud-api-adaptor/test/e2e/common_suite.go#L235-L281 that we can re-use)
- New tests
  - There are a few new test cases I'd suggest, that are detailed in the acceptance criteria. The code for this code be based on the existing `CCv0` tests for [Kubernetes](https://github.com/stevenhorsman/tests/blob/31ea93fed12338f746b3c67642ef082f43471d38/integration/kubernetes/confidential/agent_image.bats#L185-L220), and [crictl](https://github.com/stevenhorsman/tests/blob/31ea93fed12338f746b3c67642ef082f43471d38/integration/containerd/confidential/agent_image.bats#L121-L139) but we want to work to make them easier to apply to different KBCs/TEE by extracting out the KBC/TEE logic into library functions, so the test cases are cleaner, similar to the approach done in https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-confidential.bats rather than a pure cherry-pick
  - These tests also need to provide credentials to the nydus-snapshotter which is documented [here](https://github.com/containerd/nydus-snapshotter/blob/main/docs/configure_nydus.md#dockerconfig-based-authentication), but we hit challenges with in https://github.com/kata-containers/tests/pull/5775, so might need another look
  -  We need to set-up the sample_KBS resources based on the approach in #8870

## Acceptance Criteria

For each supported platform (different TEEs):

_**Scenario**: Creating a container from an authenticated image, with correct credentials via KBC works_
**Given** An authenticated container registry *quay.io/kata-containers/confidential-containers-auth*
  **And** a version of kata deployed with a guest image that has an agent with `guest_pull` feature enabled and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml)
  **And** a KBS set up to have the correct auth.json for registry *quay.io/kata-containers/confidential-containers-auth* embedded in the `"Credential"` section of `its resources file`
**When** I create a pod from the container image *quay.io/kata-containers/confidential-containers-auth:test*
**Then** The pull image works and the pod can start

_**Scenario**: Creating a container from an authenticated image, with incorrect credentials via KBC fails_
**Given**  An authenticated container registry *quay.io/kata-containers/confidential-containers-auth*
  **And** a version of kata deployed with a guest image that has an agent with `guest_pull` feature enabled and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml)  
  **And** An installed kata CC with the sample_kbs set up to have the auth.json for registry *quay.io/kata-containers/confidential-containers-auth* embedded in the `"Credential"` resource, but with a dummy user name and password
**When** I create a pod from the container image *quay.io/kata-containers/confidential-containers-auth:test*
**Then** The pull image fails with a message that reflects that the authorisation failed

_**Scenario**: Creating a container from an authenticated image, with no credentials fails_
**Given**  An authenticated container registry *quay.io/kata-containers/confidential-containers-auth*
   **And** a version of kata deployed with a guest image that has an agent with `guest_pull` feature enabled and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml)
  **And** An installed kata CC with no credentials section
**When** I create a pod from the container image *quay.io/kata-containers/confidential-containers-auth:test*
**Then** The pull image fails with a message that reflects that the authorisation failed

_**Scenario**: Regression tests: Creating a container from a public image, with no credentials works_
**Given** A public container registry *quay.io/prometheus*
   **And** a version of kata deployed with a guest image that has an agent with `guest_pull` feature enabled and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml)
  **And** An installed kata CC with no credentials section
**When** I create a pod from the container image in *quay.io/prometheus/busybox:latest*
**Then** The pull image works and the pod can start

**Comment by ariel-adam** [comment]
@stevenhorsman to who should this issue be assigned to and what should be the priority?

**Comment by stevenhorsman** [comment]
> @stevenhorsman to who should this issue be assigned to and what should be the priority?

This is blocked, so I don't think it makes sense to assign it to anyone yet

**Comment by ariel-adam** [comment]
Tagged as status blocked.

**Comment by ariel-adam** [comment]
@littlejawa could you take a look at this :-)?

**Comment by mkulke** [comment]
https://github.com/confidential-containers/guest-components/issues/568
