### ISSUE TITLE
CC: Trusted storage on guest

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8142]
When pulling and unpacking, or just decrypting an encrypted container image inside the guest we use tmpfs (in /run/kata-containers/) by default, so that when running in a TEE this data is encrypted and therefore not accessible to the untrusted host. There are limitations with this - encrypted memory is typically small and valuable, so with this feature we can use a side car to instead create a block volume on the host that we can use dm-crypt and dm-verity to protect as a place to store downloaded container images, or data storage. See https://github.com/confidential-containers/confidential-containers/issues/123 for more information

## Things to note/include with this work
I'm not an expert here, but I think the work provided is mostly cherry-picks (checking for updates) of the following commits:
- Add cryptsetup support in Guest kernel and rootfs https://github.com/kata-containers/kata-containers/pull/4762/commits/edf3cba463faebbec86aa87ac4ffd4c30558d665
- Add data-integrity agent config option: https://github.com/kata-containers/kata-containers/pull/4885/commits/b4c4ec66d067edcc42c5560a85728dd5d39ebeff
- Add trusted storage script in the rootfs and enable it in the agent, if configured https://github.com/kata-containers/kata-containers/pull/4885/commits/7e369534c8781b114c5d5e7a8e839f60f6d02c70
- Optimise trusted storage: https://github.com/kata-containers/kata-containers/commit/4906228701b0a71ef8d2e941ce7cca2b8748ad40
- I think we also might have a dependency on https://github.com/kata-containers/kata-containers/issues/8104 to ensure the security & optimisation of the pause image.
- Do we bring across (and update) some of the documentation for this in https://github.com/confidential-containers/confidential-containers/blob/main/guides/ephemeral_storage.md
- One of the things missing in `CCv0` is some test cases for this, so I think we need to add them as part of this issue

## Questions
- How do we decided whether to include the init trusted storage script in rootfs? Is there any harm in always including it as it's only used if `agent.data-integrity` is set in the kernel parameters?
- What are some good test cases for this - Is there anyway to connect to the guest without going through debug console to see that a pod is using the encrypted block storage?

## Acceptance Criteria

For each supported platform:

_**Scenario: Image pull on guest works on Kubernetes**_
**Given** I have a version of kata deployed on Kubernetes with a guest image that has an agent with `guest_pull` feature enabled and nydus-snapshotter installed and configured for [guest-pulling](https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/config-coco-guest-pulling.toml)
**And** `agent.data-integrity` is enabled
**And** I have a compliant CSI driver installed
**When** I try and create a pod from a public container (e.g. `quay.io/prometheus/busybox:latest`) with a sidecar trusted-store & PVC like the example in https://github.com/confidential-containers/confidential-containers/blob/main/guides/ephemeral_storage.md
**Then** The pod is successfully created and I can validate from the host that the mounted storage is encrypted

**Comment by stevenhorsman** [comment]
@arronwy - I think you are the SME for this, so please feel free to update my description and edit/add tests cases. Thanks!

**Comment by fitzthum** [comment]
As I understand it the trusted storage plan has morphed a bit since it was first proposed. Originally we talked about using an ephemeral block device as a way to alleviate memory pressure. Now that we are introducing host pulling, I'm not sure that is significant anymore.

More recently we have talked about trusted storage being implemented via the CDH as a way to support advanced workloads. As I understand it this is not related to storing the container image, but more to mounting protected volumes inside of a container.

I think the commits listed above are a mix of commits supporting trusted storage with CDH and some of the underpinnings for nydus, such as dm-verity support. Trusted storage with CDH is not currently implemented in v0.8.0. I'm not sure if it is targeted for v0.9.0 or later. Here is one of the oustanding PRs https://github.com/confidential-containers/guest-components/pull/345

Btw what is the `agent.data-integrity` flag you mention?

**Comment by stevenhorsman** [comment]
`agent.data-integrity` is the agent config that is used in https://github.com/kata-containers/kata-containers/commit/7e369534c8781b114c5d5e7a8e839f60f6d02c70#diff-f87c1c212bba3abd0b07bafe69d5b01ad00dfe2c01bed585e2a75fcbb6442b89 to run the init trusted storage script

**Comment by fitzthum** [comment]
Ok, so is this issue just about the ephemeral storage stuff described [here](https://github.com/confidential-containers/confidential-containers/blob/main/guides/ephemeral_storage.md). @arronwy is that something we are planning to port to main? I'm not sure how relevant it is given that we have nydus support. Maybe people pulling in the guest (not on peer pods) might still want to use it.

**Comment by ariel-adam** [comment]
@fitzthum @stevenhorsman going back to this issue.
Is this something we still need and if so, who's the owner and priority?
