### ISSUE TITLE
CC: SNP specific features

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8178]
As part of the merge from CCv0 to main, most of the basic TEE platforms support has already been merged, but there might be some work outstanding for SNP if it's still needed including:
- https://github.com/kata-containers/kata-containers/commit/9ef28e3e5eade644aba3f5cdb70b790ec1205b08 which enables policy for SNP

**Comment by fitzthum** [comment]
See https://github.com/kata-containers/kata-containers/issues/6576. I think there is relatively little needed for SNP support. We may need a few tweaks to get the tests to work.
