### ISSUE TITLE
CC: Add the ability to create arbitrary files in the guest image, before the workload starts

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8182]
This is a generalisation of #8180. That focused on setting the content of two files `/etc/aa-offline_fs_kbc-keys.json` and `/etc/aa-offline_fs_kbc-resources.json`, but some of the tests needs generic files set in order to test them correctly e.g.
- RHSS tests need the signature claim files to be created on the guest image
- RHSS and cosign tests without using the KBS need to set an image policy that `agent.image_policy` points at
- credentials-auth want to set and auth.json file that `agent.image_registry_auth` references

As such we'd like a mechanism to create arbitary files in the guest image, before the workload that depends on them is created.

As with #8180, in `CCv0` this is currently done in most of the tests using the [`cp_to_guest_img`](https://github.com/kata-containers/tests/blob/6cf430642335c010014b5d9355a861328c4213ed/lib/common.bash#L295), util function, but it has the same issues as there, so we'd again want to consider the policy approach, but might need to design it more carefully as we aren't going to be as restricted in where we write files, so we'll probably want to have some guards to ensure that we can't overwrite particularly things, or potentially just provide allow-lists of directories that can be written inside.

**Comment by Xynnn007** [comment]
Nice topic! We are talking about bringing a design to inject any configurations that will be covered by RA into a pod during launch from k8s yaml without modifying kernel cmdline and guest image. Hopefully we can give a demo and speech a near weekly meeting.

**Comment by danmihai1** [comment]
@stevenhorsman @Xynnn007 I think we should encourage the features consuming these JSON file to retrieve the same data using an API, that:

1. Reads that data from the Policy - as in the https://github.com/kata-containers/kata-containers/pull/8261 example. 
2. Optionally, if the JSON file is present, could read that data from the JSON file. 

But, if we'll really need the Kata Agent to create JSON files from Policy, that should take approximately 10 lines of code - we can work on that together if you want.

**Comment by ariel-adam** [comment]
@stevenhorsman who should this issue be assigned to and what priority?

**Comment by stevenhorsman** [comment]
I think we should be able to use the sample kbc CC_KBS approach, so I think we can kick this out of 0.9 and potentially close it once verified
