### ISSUE TITLE
Do not use 'go get' for retrieving assets; use git, wget, curl, etc. instead

### ISSUE THREAD

**Issue by umarcor** [kata-containers/kata-containers#823]
# Description of problem

- `go get` is NOT for retrieving assets, but for adding Go (build) dependencies.
- git, wget, curl, etc. might be used for retrieving assets.
- In this project, `go get` is used incorrectly for retrieving assets.
- Enabling go modules is broken because the testing infrastructure relies on `go get` downloading assets to specific locations. See https://github.com/kata-containers/kata-containers/blob/2.0-dev/ci/lib.sh#L17.
- Travis CI is passing because go modules are NOT being used.
- Some maintainers seem to think that go modules are properly supported just because `go.mod` files were added to the repo.

> https://github.com/kata-containers/runtime/pull/1911#issuecomment-597547275
> @bergwolf:
> We should not use the **new** `go get` to download code or binary inside a go module directory, -- it would fetch the code and add it to your `go.mod` dependency. `git clone` is your friend ;)

# Expected result

Running Travis CI with go modules enabled should be successful.

# Actual result

- https://github.com/umarcor/kata-containers/commit/1cc0749b03dbb7da6dcdb93725228acd8b00262c
- https://travis-ci.com/github/umarcor/kata-containers/jobs/392554689

Please, see https://github.com/kata-containers/runtime/pull/1420#issuecomment-700777378.

# Further information

- kata-containers/runtime#1420
- kata-containers/runtime#1331
- kata-containers/runtime#1338
- kata-containers/kata-containers#42
- kata-containers/runtime#1911

**Comment by jodh-intel** [comment]
If anyone wants to do this, step 1 is to `grep -r "go get"` and change each occurrence to use `curl -sLO $URL` instead (no `wget` please).

**Comment by ariel-adam** [comment]
We will leave this as a parent issue not assigned to anyone specific.

**Comment by umarcor** [comment]
@jodh-intel, last time I had a look at this, the problem was not replacing `go get` with `curl`|`wget`|`git`. That is rather easy, since it is a mechanical replacement. The actual problem is that all the scripts rely on assets being installed in some specific location in the GOPATH. That location changes when go modules are enabled; so the scripts cannot find them. Installing assets into the GOPATH without using go is likely to produce more headaches than help solve the issue. Please, see the detailed explanation in https://github.com/kata-containers/runtime/pull/1420#issue-264351427 about the problems derived from just changing from go get to curl.

Therefore, three things need to be modified at the same time: how are assets retrieved, where are assets downloaded to, how do scripts find assets (sometimes hardcoded). I could and can "fix" the two first points, but the latter requires an expertise/knowledge about this project's testing infrastructure as a whole. As a result, I believe that modifying this needs to be guided by someone with a good understanding of the organisation and the overall testing architecture.

**Comment by liubin** [comment]
This should be closed via https://github.com/kata-containers/tests/pull/5224
