### ISSUE TITLE
ARM CI should be offline as qemu patch for arm64 under obs-packaging has gone.

### ISSUE THREAD

**Issue by jongwu** [kata-containers/kata-containers#828]
The patch of qemu for arm64 under obs-packaging has gone due the removal of the whole directory of obs-packaging, then ARM CI will not work correctly in the following days. So let ARM CI be offline until we address that issue.

Could you help take ARM CI offline @jodh-intel @bergwolf , thanks.

**Comment by jodh-intel** [comment]
@GabyCT, @jcvenegas - is this something you have access to?

**Comment by ariel-adam** [comment]
Closing this issue since it seems to be working.
Please reopen the issue if needed.
