### ISSUE TITLE
runtime-rs: Update PCI path information for VFIO and virtio-blk devices

### ISSUE THREAD

**Issue by amshinde** [kata-containers/kata-containers#8283]
While implementing change to hotplug VFIO and virtio-block devices for cloud-hypervisor, it was observed that although these devices are added to the hypervisor sucessfully , these are not detected by the agent within the VM. This is because the PCI Path information for these devices is not provided correctly to the agent by runtime-rs.

**Comment by jodh-intel** [comment]
Related: #7218, #7489.
