### ISSUE TITLE
CCv0: Set v0.8.0 tags for image-rs, AA and td-shim

### ISSUE THREAD

**Issue by portersrc** [kata-containers/kata-containers#8352]
The release candidates have now been tagged with v0.8.0 for image-rs, AA, and td-shim.
We need to update the versions.yaml and Cargo.toml in the CCv0 branch of kata
to point to these.

**Comment by stevenhorsman** [comment]
Closed with https://github.com/kata-containers/kata-containers/pull/8353 being merged
