### ISSUE TITLE
Put all the CI distros as required in kata 2.0

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#840]
Currently in kata 2.0 we have issues in Debian and CentOS as they are failing https://github.com/kata-containers/tests/issues/2910. From what I can see is that PRs are being merged without running all the complete distros so it is hard to track which PR introduces a regression. If we are going to have a CI for different distros, I believe that we should be running them not just running ubuntu or the "required" distros and merging the PRs. Are we still going to support different distros or just we will support ubuntu? In case that we are going to support different distros then I will suggest to mark all of them as a required.
/cc @amshinde @bergwolf @chavafg

**Comment by GabyCT** [comment]
In case that we do not want to run all the distros, I believe that the best is to drop that CI (it is a waste of time looking PRs that introduce regressions).

**Comment by cpmeadors** [comment]
If Ubuntu is the reference distro, then only run that and commit to fixing all CI failures before the PR is merged/approved and set that as the expectation.  Dropping CI altogether doesn't seem right.  If you have tests that you trust and they are passing, why not just run those.  That still adds value by reducing risk.  The other distros can be added when they add value.

If the problem with running other distros as required checks is that there are too many failures, I could help with taking a look at a distro run and seeing how to make it more useful .  I am particularly interested in RHEL.  Let me know if there are other ways to help.

**Comment by jodh-intel** [comment]
@GabyCT - I agree that we need to either make all distros "required", or just stop running them (nobody is suggesting we remove *all* CI's of course :-). Thanks for the offer of help @cpmeadors. In fact, this suggests an idea to me...

Ubuntu is arguably our "main" CI distro so I think we can look after that one. But it might be a good idea to create a set of "champions" / owners for every (other) CI distro. That would allow distro-specific failures to be analysed in parallel. Debian is a problem in that we don't have any representation in the Kata project afaik. However, I'm sure we could find champions for CentOS/RHEL/Fedora and SUSE. And if we don't have a "distro champion", we consider dropping that distro from the CI.

wdyt folks?

/cc @ariel-adam, @amshinde, @chavafg, @gnawux, @bergwolf?

**Comment by jodh-intel** [comment]
Related:

- https://github.com/kata-containers/kata-containers/issues/198
- https://github.com/kata-containers/ci/issues/15
- https://github.com/kata-containers/ci/issues/16

**Comment by GabyCT** [comment]
Closing this issue as all the CI's are now required in kata 2.0
