### ISSUE TITLE
consider making the "pull container image" ttrpc request more consistent with the other Agent ttrpc requests

### ISSUE THREAD

**Issue by danmihai1** [kata-containers/kata-containers#8489]
**Which feature do you think can be improved?**

Container image pull from the Guest.

**How can it be improved?**

Container image pull was implemented in the CCv0 branch in image_rpc.rs - separate from the regular rpc.rs, using separate data structures, etc. I think that moving this functionality into rpc.rs and making it consistent with the other ttrpc requests would be better. For example, if we don't make these consistent, then image_rpc.rs would need separate code for enforcing the Agent Policy.

**Additional Information**

Cc: @ChengyuZhu6 @fidencio @stevenhorsman 

**Before raising this enhancement request**

Yes

**Comment by jiangliu** [comment]
Once we get rid of forked containerd, there should be no need for the image_rpc anymore.

**Comment by ChengyuZhu6** [comment]
@danmihai1 When the guest pulls the image , there seems to be no necessity to process `PullImageRequest` through policy since the request won't be sent to the agent when using vanilla containerd. Consequently, I believe that the image's RPC service becomes unnecessary.

**Comment by fitzthum** [comment]
Can we close this?
