### ISSUE TITLE
GHA: old workflows still referred as required when they are updated with a different name

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#8527]
**Which feature do you think can be improved?**

As part of the CI migration to GHA, #8485 is to newly add the `static-checks` workflows for `s390x` on top of `x86_64`. This leads to an update on the existing workflow name like: (e.g.

- From  `build-checks (agent, make check)`
- To `Static checks / build-checks (agent, make check, ubuntu-20.04)`
)

It was expected that the old one is renamed, but the old one still appears together with the new one in the checks status keeping its status as `required`, which is never triggered by any events. This prevents the PR from being merged.

There are 2 solutions for this:

- [1st] When the PR is mergerd, to encourage other PRs open at the time of changing the settings to rebase themselves onto the main branch 
- [2nd] To mark the old ones as `non-required` and keep the changed settings for sometime (around a week) while letting other PRs get merged, and get the `non-required` checks back to `required` again 

The 1st approach incurs unnecessary maintenance overheads while the 2nd one could have chance to get a PR which does not pass the static check merged.

Thinking that we will have a similar PR for `aarch64` and `ppc64le`, we have to make the same efforts three times for the 1st approach while just one-week careful review is required for the 2nd one when the PRs for three architectures are ready.

This issue is raised for the collaboration of @BbolroC, @jongwu and @Amulyam24 for the 2nd approach.

When the PR for `aarch64` and `ppc64le` is ready, I would be grateful to leave a comment here. Thanks.

Relevant Slack conversation: https://katacontainers.slack.com/archives/C879ACQ00/p1700814859695369

**Comment by jongwu** [comment]
Hi @BbolroC -, thanks for your effort for this.

Sorry for that I'm not very clear with your second solusion. What should I do to catch up it? Is there an example?

**Comment by BbolroC** [comment]
> Hi @BbolroC -, thanks for your effort for this.
> 
> Sorry for that I'm not very clear with your second solusion. What should I do to catch up it? Is there an example?

The detailed explanation has been delivered via Slack.

What this issue wants you and @Amulyam24 to do is to post a link for your PR regarding the static checks migration for aarch64 and ppc64le when it is ready. Then the community will merge 3 PRs at the same time and go with the 2nd approach. Thanks!

**Comment by BbolroC** [comment]
I am closing this because https://github.com/kata-containers/kata-containers/pull/8485 has been merged.
