### ISSUE TITLE
Network endpoints (TAP device) not configured in sandbox namespace when using docker

### ISSUE THREAD

**Issue by zvonegit** [kata-containers/kata-containers#8541]
[kata-logs_3011.log](https://github.com/kata-containers/kata-containers/files/13516537/kata-logs_3011.log)

# Description of problem

We are using kata-containers (v3.2.0) with Docker and we are facing issues related to network. Our orchestrator is doing the following (orchestrator is communicating with Docker via API).

1. Create a sandbox (pause) container with NetworkMode set to "none" (we build our own network configuration); The runtime for the container when triggering docker is set to `"Runtime": "io.containerd.kata.v2",`. (containerd-shim-kata-v2 is in the `$path`).

2. Configure network for the sandbox:
    a. Obtain network namespace of the sandbox container (using PID of the container) (/proc/{pid}/ns/net).
    b. Create `veth` pair.
    c. Move one end of the `veth` pair into sandbox namespace (from step a.).
    d. Assign IP to interface moved to sandbox namespace and bring the interface up.
    e. Bring up the other `veth` interface in host network namespace.
    f. Create bridge interface in host net ns.
    g. Assign IP to bridge interface.
    h. Bring the bridge up.
    i. Connect host `veth` interface to bridge.
    j. Add route to network in host net ns.
    
3. Create containers with NetworkMode `container:<sandboxContainerId>` (shared NS with sandbox).

4. Start containers.

We would expect that we would be able to connect to the containers, but the network connectivity is not working. We know that kata-containers should do what is explained here: [Networking](https://github.com/kata-containers/kata-containers/blob/main/docs/design/architecture/networking.md). However, this is not the case, TAP is not configured.

After analysing kata-containers code we know that when we trigger _create sandbox_, network interfaces are not yet create and kata-containers will not see them. We can confirm this with log output as scanning of endpoints gives an empty array (see penultimate line):

```sh
Nov 30 15:50:45 net-ec-worker-1 containerd[25011]: time="2023-11-30T15:50:45.688054497Z" level=info msg="Stop logging QEMU (qemuPid=36855)" name=containerd-shim-v2 pid=36838 sandbox=254d6591c7676f0e5473a1b8cca95e21c1d77ec58170cb99d6779101191367e2 source=virtcontainers/hypervisor subsystem=qemu
Nov 30 15:50:45 net-ec-worker-1 kata[38844]: time="2023-11-30T15:50:45.712286258Z" level=info msg="scanner return error: read unix @->/run/vc/vm/417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994/qmp.sock: use of closed network connection" name=containerd-shim-v2 pid=38844 sandbox=417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994 source=virtcontainers/hypervisor subsystem=qmp
Nov 30 15:50:45 net-ec-worker-1 containerd[25011]: time="2023-11-30T15:50:45.712286258Z" level=info msg="scanner return error: read unix @->/run/vc/vm/417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994/qmp.sock: use of closed network connection" name=containerd-shim-v2 pid=38844 sandbox=417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994 source=virtcontainers/hypervisor subsystem=qmp
Nov 30 15:50:45 net-ec-worker-1 containerd[25011]: time="2023-11-30T15:50:45.713125445Z" level=info msg="stopping monitor" sandbox=913d576f3de7120efd83ab14630d4b0dbcdc5ec5637dfd728ee9688b6de16ca2 source=virtcontainers subsystem=virtcontainers/monitor
Nov 30 15:50:45 net-ec-worker-1 containerd[25011]: time="2023-11-30T15:50:45.713218462Z" level=info msg="Cleanup agent" name=containerd-shim-v2 path=/run/kata-containers/shared/sandboxes/913d576f3de7120efd83ab14630d4b0dbcdc5ec5637dfd728ee9688b6de16ca2/shared pid=38534 sandbox=913d576f3de7120efd83ab14630d4b0dbcdc5ec5637dfd728ee9688b6de16ca2 source=virtcontainers subsystem=fs_share
Nov 30 15:50:45 net-ec-worker-1 containerd[25011]: time="2023-11-30T15:50:45.713507794Z" level=info msg="sandbox 417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994 hypervisor pid is 38856" name=containerd-shim-v2 pid=38844 sandbox=417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994 source=virtcontainers subsystem=sandbox
Nov 30 15:50:45 net-ec-worker-1 containerd[25011]: time="2023-11-30T15:50:45.713876541Z" level=info msg="endpoints found after scan" endpoints="[]" name=containerd-shim-v2 pid=38844 sandbox=417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994 source=virtcontainers subsystem=network
Nov 30 15:50:45 net-ec-worker-1 containerd[25011]: time="2023-11-30T15:50:45.713924420Z" level=info msg="VM started" name=containerd-shim-v2 pid=38844 sandbox=417b4242df4e8716db9885fd4a3d0bec02d3b22d36862e3a2eb317fdbade8994 source=virtcontainers subsystem=sandbox
```

As we configure network after step one is completed, kata-containers does not perform the configuration of TAP device for our `veth` interface. The configuration of TAP is not triggered after the step two either.

# Expected result

Expected result is to have TAP interface configured by kata-containers inside the network namespace of the sandbox and containers accessible from the host.  

# Actual result

No TAP interface inside the sandbox network namespace.

Output of `ip netns exec cnitest-4ad3c724-10e4-b1e7-57a0-7dae130a1ae0 ip a` for one of the namespaces:

```sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
611: ceth25955@if612: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 5e:27:1c:a6:9b:76 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.52.1/22 scope global ceth25955
       valid_lft forever preferred_lft forever
    inet6 fe80::5c27:1cff:fea6:9b76/64 scope link 
       valid_lft forever preferred_lft forever
```

# Further information

Docker version: 24.0.6
kata-containers version: 3.2.0
containerd version: 1.6.6

Configuration of kata-containers:

```sh
[Kernel]
  Path = "/opt/kata/share/kata-containers/vmlinux-6.1.38-114"
  Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none"

[Meta]
  Version = "1.0.26"

[Image]
  Path = "/opt/kata/share/kata-containers/kata-ubuntu-latest.image"

[Initrd]
  Path = ""

[Hypervisor]
  MachineType = "q35"
  Version = "QEMU emulator version 7.2.0 (kata-static)\nCopyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers"
  Path = "/opt/kata/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-fs"
  VirtioFSDaemon = "/opt/kata/libexec/virtiofsd"
  SocketPath = ""
  Msize9p = 8192
  MemorySlots = 10
  HotPlugVFIO = "no-port"
  ColdPlugVFIO = "no-port"
  Debug = false

[Runtime]
  Path = "/opt/kata/bin/kata-runtime"
  GuestSeLinuxLabel = ""
  Debug = false
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  SandboxCgroupOnly = true
  [Runtime.Config]
    Path = "/etc/kata-containers/configuration.toml"
  [Runtime.Version]
    OCI = "1.0.2-dev"
    [Runtime.Version.Version]
      Semver = "3.2.0"
      Commit = "45687e3251604ccc71b595d37f14253c4584cd5f"
      Major = 3
      Minor = 2
      Patch = 0

[Host]
  Kernel = "5.15.0-89-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "22.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz"
    CPUs = 4
  [Host.Memory]
    Total = 16373256
    Free = 9351000
    Available = 12089272

[Agent]
  Debug = false
  Trace = false
```

What have we tried so far:

1. Build our own CNI plugin and configured _containerd_ to use it. Perhaps, the runtime would then trigger CNI plugin to configure the interfaces and the interfaces would be present in the network namespace before kata is triggered (we are not sure whe kata-containers is actually triggered)? This did not work. We assume setting NetworkMode to `none` makes docker to not propagate request to configure network to the runtime?

2. We tried to use OCI hooks as well (createRuntime). As we are not able to set those with Docker we tried with [oci-add-hooks](https://github.com/awslabs/oci-add-hooks). This should modify the bundle json and merge hooks configuration from our json to 
bundle passed to runtime. Thes hook should then be triggered before VM is started. We were not successful with that either.

3. After speaking with your team, we also tried with the following two patches: [Fix network attach](https://github.com/kata-containers/kata-containers/commit/3b9e6e7ee43eb805c54be472abfc1395fe14ba40) and [Fix network hotplug](https://github.com/kata-containers/kata-containers/commit/97845c93d8cd619fa75aa4ca679a63cfef0cc3f5). We merged those two patches into 3.2.0 and did our own build. The results are the same.

4. We are now trying to configure network before step 1. and pass network namespace through Docker, but at this point we are not sure it is possible.

Can we try something else? What do you propose?

**Comment by jodh-intel** [comment]
Hi @zvonegit - Thanks for reporting. Please could you [enable full debug](https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#enable-full-debug), re-run and ideally attach a full log to this issue so we can get some more detail on the issue.

**Comment by amshinde** [comment]
Docker's default networking ([CNM](https://github.com/moby/libnetwork/blob/master/docs/design.md)) should work with Kata. Is the reason you dont want to use that due to having your own orchestrator?

I havent tried your actual steps, but the reason kata-containers does not perform the configuration of TAP device at the end of step 1) -4) is that Kata scans the network at the time of sandbox creation. Network is a shared resource common to all containers in a pod and Kata expects all the network interfaces to be present when the network namespace path is provided to it.
So in short, all the veths pairs need to be present in the netns before it is handed over to the pause container.

We had a networking monitoring process running in the past that would look for any changes in the network namespace, this was removed as docker support was tempororily dropped. This process was to support `docker attach` cli methods. 
We have a PR in progress that adds it back, it could be used in your case as a workaround: https://github.com/kata-containers/kata-containers/pull/7648

> 1. Build our own CNI plugin and configured _containerd_ to use it.

Using containerd standalone with CNI is currently broken: https://github.com/kata-containers/kata-containers/issues/2580
There is a fix submitted to containerd, but has not been merged it. We will try to have that merged soon.

If I understand correctly that you do not want to use CNM, and instead use CNI, you can take a look at [nerdctl](https://github.com/kata-containers/kata-containers/blob/207a7fef900f16c1eac101fd5579a530c6795137/tests/integration/nerdctl/gha-run.sh#L70). It makes use of containerd and CNI networks and could work in your case.

Lastly, would like to understand your use case better and what you are trying to achieve, so that we can help you better.

**Comment by zvonegit** [comment]
Solved by switching to docker networks.

**Comment by SelvamArul** [comment]
@zvonegit Could you please elaborate on how you solved this. I am actually using docker networks but TAP endpoints are not configured correctly by Kata.
