### ISSUE TITLE
CI: Make URL checker use a list of user agents

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#8553]
See discussion on https://github.com/kata-containers/kata-containers/pull/6826, namely https://github.com/kata-containers/kata-containers/pull/6826#issuecomment-1836427181.

**Comment by amshinde** [comment]
@jodh-intel  Are you taking a look at this one? Till this is implemented, can we consider adding 403 to the http_statuses to ignore in order to unblock PR 6826?
