### ISSUE TITLE
CI testing failing on [serial(chdir)]

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#856]
# Description of problem

Comment from @jodh-intel indicates a Travis CI failure https://github.com/kata-containers/kata-containers/pull/795#pullrequestreview-501793775

```
error: cannot find attribute `serial` in this scope
   --> rustjail/src/mount.rs:971:7
    |
971 |     #[serial(chdir)]
    |       ^^^^^^
```

I did not change that code. It was introduced in commit 64b4f69847ac69d39fd7ac416983e30d3cce936b by @bergwolf 

# Expected result

CI passes

# Actual result

Travis CI error message.

```
error: cannot find attribute `serial` in this scope
   --> rustjail/src/mount.rs:971:7
    |
971 |     #[serial(chdir)]
    |       ^^^^^^
```

# Further information

This was introduced in Rust "relatively recently": https://github.com/rust-lang/rust/pull/42684. Is it possible that some of our Travis CI runners have a very old version of Rust?

**Comment by c3d** [comment]
Blocks #795 for now

**Comment by jodh-intel** [comment]
The problem of this not being detected before might be due to #769? /cc @liubin.

**Comment by c3d** [comment]
> The problem of this not being detected before might be due to #769? /cc @liubin.

This is marked as closed, not merged. I see no review, and while there is a `/test` comment, I see no CI job run either. Yet it's in the source code? Was it pushed directly?

**Comment by c3d** [comment]
> > The problem of this not being detected before might be due to #769? /cc @liubin.
> 
> This is marked as closed, not merged. I see no review, and while there is a `/test` comment, I see no CI job run either. Yet it's in the source code? Was it pushed directly?

So the actual PR is #780, #769 was dropped for some reason and has no reference to #780. I added it.,

**Comment by c3d** [comment]
One thing I don't understand is why we have the error.

```
$ rustc --version
rustc 1.44.1 (c7087fe00 2020-06-17)
```

I was thinking this was a problem with some older version of Rust not recognizing `#[serial]` annotations. But that one seems quite recent.

**Comment by c3d** [comment]
Checked locally, I have the same failure mode with `make check`, but not on `2.0-dev`, so it looks like it is a problem with the code changes in #795. Bisecting.

**Comment by jodh-intel** [comment]
Thanks @c3d.

**Comment by c3d** [comment]
OK, bisecting is made more complicated by having regrouped the commits. It turns out that some imports were removed _after_ doing some other changes. In order to reduce the number of commits, I had regrouped things by topics, and moved "removing imports" first. Can't do that before cleaning up the rest. Need to reorganize the branch if I want every step to compile.

**Comment by c3d** [comment]
Found it. The problem was indeed in a change in #795 

I had removed that, which is necessary for using `#[serial]`:

```
#[macro_use]
#[cfg(test)]
extern crate serial_test;
```

Closing.
