### ISSUE TITLE
Tracking issue for moving the govmm repository into the Kata Containers organisation

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#858]
Now that the [`govmm`](https://github.com/intel/govmm) package only has a single "user" (the Kata Containers `virtcontainers` package), it makes sense to move it into the Kata Containers GitHub organisation.

See https://github.com/intel/govmm/issues/141 for further details.

/cc @kata-containers/architecture-committee, @kata-containers/runtime.

**Comment by jodh-intel** [comment]
Can we get a few acks here before we actually do the transfer folks?

**Comment by jodh-intel** [comment]
The "fix up" work we should do after the transfer is complete is to re-vendor the 1.x and 2.x runtimes:

- 1.x: https://github.com/kata-containers/runtime/blob/master/Gopkg.toml
- 2.x: https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/go.mod

**Comment by amshinde** [comment]
+1 from me 
cc @bergwolf @egernst

**Comment by fidencio** [comment]
+1 from me as well.

**Comment by devimc** [comment]
lgtm - thanks @jodh-intel

**Comment by c3d** [comment]
Ack

**Comment by jodh-intel** [comment]
The transfer is now complete - govmm is now part of Kata Containers.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/govmm/issues/147

**Comment by jodh-intel** [comment]
Closing as job done ;)
