### ISSUE TITLE
clh: virtiofsd: vfio: VFIO test us failing

### ISSUE THREAD

**Issue by devimc** [kata-containers/kata-containers#862]
Looks like virtiofs is crashing when a VFIO device is hotplugged - I can work around this issue by disabling DAX in the configuration file

```
ct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Unexpected poll revents 11
Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Stopping queue 0 thread
Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000003] fv_queue_thread: kill event on queue 0 - quitting
Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Stopping queue 1 thread
Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000016] fv_queue_thread: kill event on queue 1 - quitting
Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Exit
Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] fv_panic: libvhost-user: Error while writing: Broken pipe
```

cc @likebreath

**Comment by likebreath** [comment]
Thanks for reporting this issue and the work-around.  

@jcvenegas Given your extended experience on virtiofsd, do you have any inputs? What's our plan for the `DAX` option?

**Comment by likebreath** [comment]
The PR to disable DAX option for virtio-fs is pending in kata-runtime (https://github.com/kata-containers/runtime/pull/2997), and will be forward ported to kata 2.0. I am assuming that would bring our VFIO CI on CLH back in kata 2.0, right? @devimc

**Comment by devimc** [comment]
@likebreath you are right

**Comment by jcvenegas** [comment]
@likebreath @likebreath I will send the 2.0 Port to by tomorrow

**Comment by hejianet** [comment]
> 
> 
> Looks like virtiofs is crashing when a VFIO device is hotplugged - I can work around this issue by disabling DAX in the configuration file
> 
> ```
> ct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Unexpected poll revents 11
> Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Stopping queue 0 thread
> Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000003] fv_queue_thread: kill event on queue 0 - quitting
> Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Stopping queue 1 thread
> Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000016] fv_queue_thread: kill event on queue 1 - quitting
> Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] virtio_loop: Exit
> Oct 05 20:15:53 test virtiofsd[30057]: [ID: 00000001] fv_panic: libvhost-user: Error while writing: Broken pipe
> ```
@devimc  Hi，does this crashing also happened with qemu vfio hotplugging?
And in this case, what is the vfio device? disk/NIC ? thanks for the details.
I tried to reproduce it on arm64 with qemu (no Kata image/container rootfs involved) but failed to reproduce.
I started the virtiofsd and mount a fs in the qemu guest with dax mode. And then hot-adding a nvme disk. After that, everything
seems to be ok. Am I missing anything?

**Comment by hejianet** [comment]
Besides, I recomended to use the latest qemu+guest kernel. E.g. the cache size property has been dropped in main line qemu:
https://www.qemu.org/docs/master/interop/virtiofsd.html#examples

**Comment by devimc** [comment]
@hejianet this error is reproducible hot-adding a virtio nic into qemu + virtiofs with dax enabled, for more details see https://github.com/kata-containers/tests/blob/2.0-dev/integration/kubernetes/vfio.sh
