### ISSUE TITLE
Add StratoVirt to hypervisors page

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#8645]
Now that #7796 has landed, the hypervisors page needs updating to include it:

- https://github.com/kata-containers/kata-containers/blob/main/docs/hypervisors.md

@WenyuanLau - Is this something you could look at?

**Comment by WenyuanLau** [comment]
@jodh-intel - Yes, I will handle that!

BTW, are there other docs I need to update? I hope that I wouldn't miss something. :-)
