### ISSUE TITLE
kata-deploy: tomlq breaks containerd config

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8678]
In https://github.com/kata-containers/kata-containers/pull/8639 a change was made to use `tomlq` to update the containerd config.toml, but in the operator (https://github.com/confidential-containers/operator/issues/305) we've found that this changes breaks the payload. I've been able to isolate the reason for this - and tomql is converting a float to an int, which breaks the containerd parsing. The cut down reproduce of this issue can be seen:
```bash
$ containerd config default > config.toml
$ cp config.toml config.toml.bak
$ tomlq -i -t '.debug.level = "debug"' config.toml
$ diff -w config.toml config.toml.bak
18c18
< level = "debug"
---
>   level = ""
36a37
>
98a100,101
>       [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
>
163c166
< sampling_ratio = 1
---
>     sampling_ratio = 1.0
223a227
>
```
showing that sample_ratio is switched from `1.0` to `1`.

After this change and restarting container we see the error:
```
containerd: (204, 1): Can't convert 1(int64) to float64
```

There is still an outstanding question of how this passes in the kata CI?

We have a few options:
1. Horrible option - create an issue in the tomlq project add some post processing to convert the sampling_ratio back to a float with sed. I don't think this is viable as the point of using tomlq was to allow us to be less brittle in case of other containerd configs that we haven't seen and this just moves that problem along
2. Try and find another toml tool that works better and switch it in place of tomlq. I think Fabiano tried multiple options and found issues with them
3. Write out own program to do the editting - Magnus has suggested toml-edit: https://github.com/confidential-containers/operator/issues/304 might help for rust
4. Back out the PR and use sed

I think that 4 is the solution we need to do now as this close to the holidays for part of the community I don't want to leave kata-deploy broken and I think 2 and 3 might take more time to resolve. I also would like to understand why the CI didn't catch this before we re-introduce changes.

**Comment by stevenhorsman** [comment]
Ok, one mystery down - I ran the kata-deploy test locally:
```
DOCKER_REGISTRY=" quay.io"
export DOCKER_REGISTRY="quay.io"
export DOCKER_REPO="kata-containers/kata-deploy-ci"
export DOCKER_TAG="kata-containers-latest"
bash tests/functional/kata-deploy/gha-run.sh run-tests
```
and they passed:
```
[run-kata-deploy-tests.sh:21] INFO: Run tests
kata-deploy.bats
 ✓ Test runtimeclasses are being properly created

1 test, 0 failures
```
The reason being that they just check that the runtimeclass was created properly, which it was:
```
# kubectl get runtimeclasses
NAME        HANDLER     AGE
kata        kata-qemu   13m
kata-qemu   kata-qemu   13m
```
It doesn't run any workload, which would demonstrate that containerd wasn't happy:
```
# journalctl -u containerd.service | tail -5
Dec 15 04:06:46 sh-operator-main1.fyre.ibm.com containerd[1405807]: time="2023-12-15T04:06:46.776495868-08:00" level=info msg="loading plugin \"io.containerd.internal.v1.tracing\"..." type=io.containerd.internal.v1
Dec 15 04:06:46 sh-operator-main1.fyre.ibm.com containerd[1405807]: containerd: (172, 1): Can't convert 1(int64) to float64
Dec 15 04:06:46 sh-operator-main1.fyre.ibm.com systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 04:06:46 sh-operator-main1.fyre.ibm.com systemd[1]: containerd.service: Failed with result 'exit-code'.
Dec 15 04:06:46 sh-operator-main1.fyre.ibm.com systemd[1]: Failed to start containerd container runtime.
```

**Comment by BbolroC** [comment]
Thanks for the investigation. Just let me know if you need my help for this matter.

**Comment by stevenhorsman** [comment]
I've created a really simple containerd status test case: https://github.com/kata-containers/kata-containers/pull/8679 as I want to ensure I can get the kata tests failing before trying to fix this problem.

**Comment by stevenhorsman** [comment]
Re-opening as I think we still want a longer term solution here, which might involved fixing tomlq and re-introducing it.
