### ISSUE TITLE
runtime-rs: optimize `increase_attach_count` function

### ISSUE THREAD

**Issue by studychao** [kata-containers/kata-containers#8738]
When the device already has attach point larger than 1, if it more suitable to directly return Err instead of return `true`. 
Also, there is no comment here to describe what `true` or `false` mean in this function.

**Comment by studychao** [comment]
also, when there are multiple containers in the pod, there may be case that attach point larger than 2, we should not return `Err` in that case when we are doing `attach` ops.

**Comment by Apokleos** [comment]
Thx @studychao, the PR to do bugfix is coming!
cc @Tim-0731-Hzt
