### ISSUE TITLE
mounts: Too many mount points in k8s high-density deployment with Kata go runtime

### ISSUE THREAD

**Issue by fadecoder** [kata-containers/kata-containers#8758]
Recently, we notice one problem when deploying Kata Containers go runtime through k8s. When we deploy over 400 Pods on one node, the number of mount points on the system will exceed 10,000, no matter what VMM(qemu, clh, stratovirt) we use. 

A large number of mount points will cause the `systemd` process in the `host` to be very busy (100% CPU load), executing system calls such as `open`/`read` the mounts, due to some kind of container health check mechanism. The high load of the `systemd` process will cause the deployment of more Pods to become extremely slow, making it difficult to meet the requirements for fast and high-density deployment.

Inspired by rust runtime, we add the mount namespace isolation to go runtime, and it can prevent the `systemd` process from seeing more mounts, thereby reducing the burden on the `systemd`, making it faster to deploy more Pods.

Considering the runtime-rs VMMs are under heavy developments, adding such isolation is still useful for many user-cases.

**Comment by WenyuanLau** [comment]
Thanks! @fadecoder

**Comment by DeciderWill** [comment]
thanks @fadecoder this has been affecting us for a while 🎉
