### ISSUE TITLE
Firecracker runtime pod doesnt start on kubernetes 1.27.0

### ISSUE THREAD

**Issue by jonasz-lasut** [kata-containers/kata-containers#8764]
1. Run the `kata-collect-data.sh` script, which is installed as part of Kata Containers
   or `kata-containers.collect-data`, which is installed as part of the Kata Containers
   snapcraft package.

Uploaded as a file - comment was too long
[collect.md](https://github.com/kata-containers/kata-containers/files/13820698/collect.md)

# Description of problem

I've followed the steps located in https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/README.md -> kubectl apply RBAC, apply kata-deploy, apply runtime classes and test pods

Firecracker pod doesn't start with FailedCreatePodSandboxError
` Warning  FailedCreatePodSandBox  36s (x102 over 23m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: failed to mount "/run/kata-containers/shared/containers/e451326df87ad20cbe9f2c6827d34ea0571690810f676d4df81be6445a7a25f8/rootfs" to "/run/kata-containers/e451326df87ad20cbe9f2c6827d34ea0571690810f676d4df81be6445a7a25f8/rootfs", with error: ENOENT: No such file or directory: unknown`

# Expected result

Pod should start with firecracker runtime class

# Actual result

Pod fails to start with FailedCreatePodSandboxError

**Comment by jonasz-lasut** [comment]
Solves by adding snapshotter = devmapper for firecracker, it should be stated in the documentation though

**Comment by LijieZhang1998** [comment]
Hi @jonasz-lasut  where did you add `snapshotter = devmapper`?

**Comment by jonasz-lasut** [comment]
Hi @LijieZhang1998 you need to add those lines in /etc/containerd/config.yoml
Below you can find the part with klata-fc config with the added line

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc]
&nbsp;&nbsp;runtime_type = "io.containerd.kata-fc.v2"
&nbsp;&nbsp;**snapshotter = "devmapper"**
&nbsp;&nbsp;privileged_without_host_devices = true
&nbsp;&nbsp;pod_annotations = ["io.katacontainers.*"]
&nbsp;&nbsp;[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc.options]
&nbsp;&nbsp;&nbsp;&nbsp;ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-fc.toml"

You also need to create a devmapper snapshotter configuration in that file and a create a thin pool.
Basic snapshotter config looks like this, you can place somewhere above runtimes in /etc/containerd/config.toml

[plugins."io.containerd.snapshotter.v1.devmapper"]
&nbsp;&nbsp;pool_name = "thinpool name"
&nbsp;&nbsp;base_image_size = "size in GB"
&nbsp;&nbsp;root_path = "path to data directory"

Creating thin pool device is described in the kernel documentation at https://www.kernel.org/doc/Documentation/device-mapper/thin-provisioning.txt

**Comment by LijieZhang1998** [comment]
Hi @jonasz-lasut, I followed the kernel doc you mentioned to create thin pool device. I got this error
```
device-mapper: reload ioctl on pool (253:0) failed: No such device
Command failed.
```
when I ran the command `sudo dmsetup create pool --table '0 20971520 thin-pool $metadata_dev $data_dev $data_block_size $low_water_mark'`. The `$metadata_dev` and `$data_dev` has been created without error using `dd` command. Do you have any idea? Sorry I'm pretty new to this area. 

Thanks!

**Comment by aki263** [comment]
I am getting same error but even adding snapshotter = devmapper is not helping

```
Events:
  Type     Reason                  Age    From               Message
  ----     ------                  ----   ----               -------
  Normal   Scheduled               7m40s  default-scheduler  Successfully assigned default/kata-fc-pod-2 to node-1.maas
  Warning  FailedCreatePodSandBox  7m39s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: failed to mount /run/kata-containers/shared/containers/1061cb6425896a0a9047fb6ef55fbd4d6182d16bdc297be71a3dbbabc63175b3/rootfs to /run/kata-containers/1061cb6425896a0a9047fb6ef55fbd4d6182d16bdc297be71a3dbbabc63175b3/rootfs, with error: ENOENT: No such file or directory

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>: unknown
  Warning  FailedCreatePodSandBox  7m25s  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: failed to mount /run/kata-containers/shared/containers/a5356dde428686d089e1df257d7cad686111f8a191a19360a1a29d3892863757/rootfs to /run/kata-containers/a5356dde428686d089e1df257d7cad686111f8a191a19360a1a29d3892863757/rootfs, with error: ENOENT: No such file or directory
```

```
root@node-1:~# cat /etc/containerd/config.toml
version = 2

[metrics]
address = "127.0.0.1:1338"

[plugins."io.containerd.snapshotter.v1.devmapper"]
pool_name = "devpool"
root_path = "/var/lib/containerd/devmapper"
base_image_size = "10GB"
discard_blocks = true

[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "registry.k8s.io/pause:3.9"
snapshotter = "devmapper"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc]
runtime_type = "io.containerd.kata-fc.v2"
runtime_path = "/opt/kata/bin/containerd-shim-kata-v2"
privileged_without_host_devices = true
snapshotter = "devmapper"
pod_annotations = ["io.katacontainers.*"]

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc.options]
ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-fc.toml"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu]
runtime_type = "io.containerd.kata-qemu.v2"
runtime_path = "/opt/kata/bin/containerd-shim-kata-v2"
privileged_without_host_devices = true
pod_annotations = ["io.katacontainers.*"]

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu.options]
ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-qemu.toml"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
endpoint = ["https://registry-1.docker.io"]

[debug]
level = "debug"
```

```
root@node-1:~# ctr plugins ls |grep devmapper
WARN[0000] DEPRECATION: The `mirrors` property of `[plugins."io.containerd.grpc.v1.cri".registry]` is deprecated since containerd v1.5 and will be removed in containerd v2.0. Use `config_path` instead.
io.containerd.snapshotter.v1          devmapper                linux/amd64    ok
```
