### ISSUE TITLE
CCv0: some typo for building shell

### ISSUE THREAD

**Issue by blossomin** [kata-containers/kata-containers#8823]
# Get your issue reviewed faster

This line [in kata_deploy_binaries.sh](https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L335) has a typo. It should be **version_checker**.

**Comment by stevenhorsman** [comment]
`CCv0` hasn't been maintained for around a year now and this code didn't get ported to `main`, so I think we can close it, thanks for raising though @blossomin!
