### ISSUE TITLE
CI: run-runk failing intermittently on the `test ps command` checker

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#8975]
I've noticed intermittent failures on run-runk job, often you run a 2nd time and the test pass.

It is in the `test ps command` that sometimes return 2 instead of the expected 3 lines:
```
[runk-tests.sh:78] INFO: ctr pull'd: docker.io/library/busybox:latest
start container with runk
exec process in a container
test ps command
ps output:
PID     INFO
3795    -
ps output lines: 2
[runk-tests.sh:48] ERROR: unexpected ps command output
```

Examples of fails in https://github.com/kata-containers/kata-containers/actions/runs/7726958090/job/21065554095?pr=8953 and https://github.com/kata-containers/kata-containers/actions/runs/7714184548/job/21028062099?pr=8964

**Comment by danmihai1** [comment]
I noticed these failures too, every once in a while. Also, when the test passes, the ps output looks unusual for me - e.g.,

ps output:
PID     INFO
9913    -
9982    **&ProcessDetails{ExecID:id1,XXX_unrecognized:[],}**

**Comment by wainersm** [comment]
Hi @ManaSugi @liubin , can this indicate a bug on runk? Anyway, I convert the current suite of tests from pure shell script to bats and disabled that specific test.

**Comment by ManaSugi** [comment]
@wainersm thanks for the report.
I think this is not a bug on runk, but the script. The ps test should wait for the `sh` process executed by `ctr exec` to actually start running. Inserting `sleep 1`  or a retry mechanism before running `ctr ps` helps the script always pass.

```
sudo ctr t exec --detach --exec-id id1 ${CONTAINER_ID} sh
// sleep or retry mechanism will be required to pass the test all the time.
ps_out="$(sudo ctr t ps ${CONTAINER_ID})" || die "ps command failed"
```

**Comment by wainersm** [comment]
> @wainersm thanks for the report. I think this is not a bug on runk, but the script. The ps test should wait for the `sh` process executed by `ctr exec` to actually start running. Inserting `sleep 1` or a retry mechanism before running `ctr ps` helps the script always pass.
> 
> ```
> sudo ctr t exec --detach --exec-id id1 ${CONTAINER_ID} sh
> // sleep or retry mechanism will be required to pass the test all the time.
> ps_out="$(sudo ctr t ps ${CONTAINER_ID})" || die "ps command failed"
> ```

@ManaSugi alright. I will add that sleep on the script. thanks!
