### ISSUE TITLE
Supporting gollvm, for Kata containers

### ISSUE THREAD

**Issue by advancedwebdeveloper** [kata-containers/kata-containers#899]
Hi.
@devimc sent me here - so I am firing an issue.

I am interested to contribute into supporting [gollvm](https://go.googlesource.com/gollvm/) project.
I think I was able to compile all the Golang code, for both Kata containers and [Firecracker's Go SDK](https://github.com/firecracker-microvm/firecracker-go-sdk) project.

I am proposing to check how this alternative LLVM oriented compiler, for Golang, could be of help.

Ivan

**Comment by jcvenegas** [comment]
Hi @advancedwebdeveloper , thanks for open this issue. Supporting could mean a few steps here.

- Build  identify if all kata componets build 
- Scripts have scripts to allow other folks can build it
- CI jobs ensure that kata keeps working over the time.
  CI and support could be dependent on how stable gollvm. If support stability is ensured this could be a metric to consider add it, if is not consider stable this may cause some issues in kata maintenance. 

Finally I think  @kata-containers/architecture-committee may want to take a look to see priorities on adoption.

**Comment by advancedwebdeveloper** [comment]
You can try to build & run Kata containers, using gollvm, yourself.

https://github.com/advancedwebdeveloper/clang_test_cpu_features/blob/main/.github/workflows/llvm.yml
https://github.com/advancedwebdeveloper/clang_test_cpu_features/actions
.
The above pipeline shows how to build - and you can perform installation, which would allow to use (excluding main-go, which your are currently using). I was able to build it within a VM - but compiling inside Docker containers should be possible, too.
Since virt. capabilities are interfaced into userspace via a syscall - you should be able to boot a "clean" bare metal machines, with some Linux distro, and run pre-compiled Kata containers (via gollvm/llvm-goc).

**Comment by jodh-intel** [comment]
Hi @advancedwebdeveloper - I hope you don't mind but we've assigned this issue to you ;) Are you still interested in working on this? If not, feel free to close the issue. If it's going to be a huge amount of work (and I suspect it is), you should know that we would need to think extremely carefully before switching compiler, but we are always willing to consider new tech ;)

**Comment by advancedwebdeveloper** [comment]
You did not explain how do you arrange testing of hosts, with UEFI

**Comment by fidencio** [comment]
As this issue has not been active for a quite long time, I'm closing the issue.

@advancedwebdeveloper, please, feel free to re-open it in case you have the interest to work on this.  Mind that this will come with the commitment to setup and maintain a CI to ensure we don't regress on this front.
