### ISSUE TITLE
`kata-runtime exec` error message isn't correct

### ISSUE THREAD

**Issue by WeiZhang555** [kata-containers/kata-containers#8999]
# Description of problem

Following instructions from https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#simple-debug-console-setup 

I'm trying to connect to debug console of one VM with modified rootfs, it reports:

```
#kata-runtime exec c649a44d3ff5fb8513c6b6814fe078f9232f1762374ca56a48e2a015c5d2029c
Get "http://shim/agent-url": dial unix /run/kata/c649a44d3ff5fb8513c6b6814fe078f9232f1762374ca56a48e2a015c5d2029c/shim-monitor.sock: connect: no such file or directory
```

/run/kata directory doesn't exist at all, even though I switch the rootfs to correct one and successfully exec into the VM.

After some search, I found that the `shim-monitor.sock` resides in 
```
#find /run/ -name shim-monitor.sock
/run/vc/sbs/64f59bdbb91b1ad892e1d3988ebc570dd03d42361812c550bb2263313833a929/shim-monitor.sock
```

The correct dir should be `/run/vc/sbs/`

# Expected result

The error message should be 
```
#kata-runtime exec c649a44d3ff5fb8513c6b6814fe078f9232f1762374ca56a48e2a015c5d2029c
Get "http://shim/agent-url": dial unix /run/vc/sbs/c649a44d3ff5fb8513c6b6814fe078f9232f1762374ca56a48e2a015c5d2029c/shim-monitor.sock: connect: no such file or directory
```

**Comment by Apokleos** [comment]
related issue [#6622](https://github.com/kata-containers/kata-containers/issues/6622), [#6148](https://github.com/kata-containers/kata-containers/issues/6148)
