### ISSUE TITLE
Remove '$' prefix from commands in Kata Containers documentation

### ISSUE THREAD

**Issue by mhmohona** [kata-containers/kata-containers#9107]
**Description of problem:**
I've noticed that in the documentation for Kata Containers, all commands are prefixed with a '$' sign. This makes it inconvenient for users who want to directly copy and paste the commands into their terminal, as they have to manually remove the '$' sign each time. This small inconvenience can lead to errors, especially for new users who might not be familiar with command line interfaces.

**Expected result:**
I expect that commands in the documentation should not have a '$' sign prefix, so users can directly copy and paste them without any additional editing.

**Actual result:**
Currently, all commands in the documentation are prefixed with a '$' sign, which adds an unnecessary step for users who want to use the commands directly.

**Further information:**
Removing the '$' sign from commands in the documentation will improve the user experience and make it easier for users to follow the instructions accurately. 

**Kata Containers survey:**
Please consider taking the survey to help us improve Kata Containers: [Kata Containers User Survey](https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey)

**Comment by justxuewei** [comment]
A line with the prefix of `$` implies that it is a command instead of an output. IMHO, I don't think it is a good idea to remove them. For example, the first line is a command, and the rest is an output.

```
$ ls /
bin  boot  cdrom  dev  etc  home  lib  lib64  libx32  lost+found  media  mnt  opt  proc  root  run  sbin  snap	srv  swapfile  sys  tmp  usr  var
```

**Comment by zvonkok** [comment]
`$` also implies running the command as a user and not as root `#`; removing it increases entropy.
