### ISSUE TITLE
io.containerd.kata.v2 use cloud-hypervisor？

### ISSUE THREAD

**Issue by wenjunGU** [kata-containers/kata-containers#9168]
kata-runtime version 3.2.0-rc0，This version uses qemu by default。I tried to use containerd-shim-kata-v2 under runtime-rs to replace it, but I got the following error:
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: ttrpc: closed: unknown

请问我需要怎么做才能设置kata-runtime使用cloud-hypervisor？Thank you very much！！

**Comment by Apokleos** [comment]
Hi @wenjunGU Cloud you please ask questions in English ? The Kata community is a global community of developers. Using English will allow more developers to understand your questions. Thx.

Anyway. You can do it following the doc [containerd-kata.md](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/containerd-kata.md) if you're using containerd engine and kata 3.x.

**Comment by wenjunGU** [comment]
@Apokleos Excuse me，I have solved the problem, thank you for your help
