### ISSUE TITLE
how to login kata guest

### ISSUE THREAD

**Issue by magnate3** [kata-containers/kata-containers#918]
I have started the kata container, but 
virt list is empty ，and how to login kata guest vm

root@ubuntu:/etc/docker# virsh list
 Id    Name                           State
----------------------------------------------------

/usr/share/kata-containers/binary/qemu-system-aarch64 -name sandbox-299c206776b33924c49eabd0c6fb0da56c5a241749b513b2315edb14acc0ef11 -uuid 7e699a93-d791-448f-a916-87ec19258f8f -machine virt,usb=off,accel=kvm,gic-version=host,nvdimm -cpu host,pmu=off -qmp unix:/run/vc/vm/299c206776b33924c49eabd0c6fb0da56c5a241749b513b2315edb14acc0ef11/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=257176M -device pcie-pci-bridge,bus=pcie.0,id=pcie-bridge-0,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/299c206776b33924c49eabd0c6fb0da56c5a241749b513b2315edb14acc0ef11/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/binary/kata-containers.img,size=184549376 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/299c206776b33924c49eabd0c6fb0da56c5a241749b513b2315edb14acc0ef11/kata.sock,server,nowait -device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/299c206776b33924c49eabd0c6fb0da56c5a241749b513b2315edb14acc0ef11/shared,security_model=none -netdev tap,id=network-0,vhost=on,vhostfds=3,fds=4 -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:03,disable-modern=false,mq=on,vectors=4,romfile= -rtc base=utc,driftfix=slew,clock=host -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic --no-reboot -daemonize -kernel /usr/share/kata-containers/binary/vmlinuz-5.4.34-88 -append console=hvc0 console=hvc1 iommu.passthrough=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=64 agent.use_vsock=false systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none agent.log=debug agent.log=debug -pidfile /run/vc/vm/299c206776b33924c49eabd0c6fb0da56c5a241749b513b2315edb14acc0ef11/pid -D /run/vc/vm/299c206776b33924c49eabd0c6fb0da56c5a241749b513b2315edb14acc0ef11/qemu.log -smp 1,cores=1,threads=1,sockets=64,maxcpus=64

**Comment by liubin** [comment]
Hi @magnate3 , you can check https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/Developer-Guide.md#set-up-a-debug-console at first, hope this will be helpful.

**Comment by jodh-intel** [comment]
@magnate3 - any update? Did you try the developer guide?

**Comment by fidencio** [comment]
@magnate3, I'm closing the issue for now due to its inactivity for more than one year. Please, feel free to re-open it, or even open a new issue, in case you feel it's needed.
