### ISSUE TITLE
there is no output when I use  socat "stdin,raw,echo=0,escape=0x11" "unix-connect:${console}"  

### ISSUE THREAD

**Issue by magnate3** [kata-containers/kata-containers#921]
root@ubuntu:~# id=$(sudo docker ps -q --no-trunc)
root@ubuntu:~# console="/var/run/vc/vm/${id}/console.sock"
root@ubuntu:~# echo $console
/var/run/vc/vm/4491cde0777ac6886102e4315558dd8acbf23d56c89f5ef72c217a0057280a41/console.sock
root@ubuntu:~# socat "stdin,raw,echo=0,escape=0x11" "unix-connect:${console}"

**Comment by liubin** [comment]
@magnate3 This repo is only for Kata containers 2.0, and not supports docker. If you are using a 1.x version of Kata containers, you can read [this](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#set-up-a-debug-console). If steel get new errors, you can create issue in https://github.com/kata-containers/runtime

**Comment by magnate3** [comment]
firstly,I have succed to connect kata container with socat when I not using k8s and containerd, but when I create kata container with k8s and I fail to  to connect kata container with socat.
lsof -n -p  not find console.sock

**Comment by jodh-intel** [comment]
@magnate3 - is this still a problem? If yes, please provide the output of `kata-collect-data.sh` as requested on the issue template.

**Comment by cmaf** [comment]
@magnate3 Since this issue is over a year old and we didn't receive more information I'm closing it, but please reopen or create a new issue if you are having problems.
