### ISSUE TITLE
Update upgrading document

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#928]
We need to rework the upgrading doc:

- https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/Upgrading.md

It's difficult to know at this point how much detail to specify and also exactly how to document "upgrading from Kata 1.x to 2.0" given that:

- There are various ways of installing Kata.
- We don't know the approach distributions will take

  *Presumably* they'll just allow an upgrade from 1.x packages to 2.0 (and disallow downgrades maybe?). But some distros might decide to create a new set of `kata-containers2` packages or similar? I guess what we can say is the usual mantra:

> We recommend you used distro-packaged version of Kata Containers. Please refer to your distribution for details on upgrading from Kata 1.x to 2.0.

We can also:

- Remove all the bits in that doc about runV and Clear Containers imho.
- Add a link to what will soon be the "legacy" documenation repo (https://github.com/kata-containers/documentation).

Related: https://github.com/kata-containers/kata-containers/issues/539

**Comment by bergwolf** [comment]
Good point, @jodh-intel! I think we have to situations:
1. upgrade from distro-packaged Kata Containers 1.x
2. upgrade from the official static package Kata Containers 1.x

For the former one, we can ask users to follow distro guides on how to upgrade.
For the latter one, it is like upgrading from 1.x to 1.(x+1). Users just need to install Kata Containers 2.x and everything works like before.

**Comment by jodh-intel** [comment]
@bergwolf - agreed. I'll work on this today...
