### ISSUE TITLE
When installing Kata Container in Ubuntu, it raised: gpg: 找不到有效的 OpenPGP 数据。

### ISSUE THREAD

**Issue by zibinpan** [kata-containers/kata-containers#9399]
When following the [doc ](https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md)to install Kata Container in Ubuntu, it raised: gpg: 找不到有效的 OpenPGP 数据。

**Comment by stevenhorsman** [comment]
This documentation is for the Kata 1.x release which is very old and the repo has been archived for multiple years. Please try using more recent docs: https://github.com/kata-containers/kata-containers/blob/main/docs/install/README.md Thanks!
