### ISSUE TITLE
Kata for SEV-SNP

### ISSUE THREAD

**Issue by yuxi191231** [kata-containers/kata-containers#9442]
Hello, I see that kata3.1 and 3.2 versions support sev-snp now, but when I install and run according to the documents, I have encountered the following problems, may I ask whether there is still a problem in the current code or my configuration is wrong
![微信图片_20240409133323](https://github.com/kata-containers/kata-containers/assets/127105680/2a34f998-9208-473c-b0d8-15a1515727e8)

And I would like to ask if there is any documentation on how specifically kata supports sev/snp, such as its specific architecture implementation, thank you very much

**Comment by Apokleos** [comment]
@yuxi191231 Could you please give us more detailed info about the kata and host ENV you're using?

**Comment by yuxi191231** [comment]
> @yuxi191231 Could you please give us more detailed info about the kata and host ENV you're using?

I am using kata stable-3.2 and my host kernel is 6.5.0-rc2-snp-host-ec25de0e7141 on ubuntu 22.04 TLS. 
Here`s some kata log.

`4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.023169561+08:00" level=info msg="loaded configuration" file=/etc/kata-containers/configuration.toml format=TOML name=containerd-shim-v2 pid=2765242 sandbox=b1 source=katautils
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.023478059+08:00" level=info msg="IOMMUPlatform is disabled by default." name=containerd-shim-v2 pid=2765242 sandbox=b1 source=katautils
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.023535321+08:00" level=debug default-kernel-parameters= name=containerd-shim-v2 pid=2765242 sandbox=b1 source=katautils
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.024808606+08:00" level=debug msg="container rootfs: /run/containerd/io.containerd.runtime.v2.task/default/b1/rootfs" source=virtcontainers subsystem=oci
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.024846487+08:00" level=info msg="shm-size detected: 67108864" source=virtcontainers subsystem=oci
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.026869464+08:00" level=info msg="create netns" name=containerd-shim-v2 netns=/var/run/netns/cnitest-be62dbc2-5ee6-7bcb-9ebb-0319a0dcacfe pid=2765242 sandbox=b1 source=katautils
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.026968476+08:00" level=warning msg="Could not add /dev/mshv to the devices cgroup" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=cgroups
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.03071094+08:00" level=debug msg="restore sandbox failed" error="open /run/vc/sbs/b1/persist.json: no such file or directory" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=sandbox
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.030747331+08:00" level=warning msg="Confidential guests do not support hotplugging of vCPUs. Setting DefaultMaxVCPUs to NumVCPUs (1)" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.030914256+08:00" level=info msg="Enabling SNP guest protection" kernel-params="[{tsc reliable} {no_timer_check } {rcupdate.rcu_expedited 1} {i8042.direct 1} {i8042.dumbkbd 1} {i8042.nopnp 1} {i8042.noaux 1} {noreplace-smp } {reboot k} {cryptomgr.notests } {net.ifnames 0} {pci lastbus=0}]" kernel-params-debug="[{debug }]" kernel-params-non-debug="[{quiet }]" machine="{microvm  accel=kvm,kernel_irqchip=split}" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemuAmd64
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.030987698+08:00" level=debug msg="Creating bridges" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.031008409+08:00" level=debug msg="Creating UUID" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.031118772+08:00" level=debug msg="Disable nesting environment checks" inside-vm=false name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.031248795+08:00" level=info msg="Set selinux=0 to kernel params because SELinux on the guest is disabled" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.031862893+08:00" level=info msg="adding volume" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu volume-type=virtio-9p
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.032265924+08:00" level=info msg="endpoints found after scan" endpoints="[]" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=network
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.032302405+08:00" level=debug msg="Endpoints added" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=network
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.066063845+08:00" level=info msg="Starting VM" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=sandbox
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.066110676+08:00" level=error msg="Could not read qemu pid file" error="open /run/vc/vm/b1/pid: no such file or directory" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.066187598+08:00" level=debug default-kernel-parameters="tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k cryptomgr.notests net.ifnames=0 pci=lastbus=0 console=hvc0 console=hvc1 debug" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.06625111+08:00" level=info msg="created vm path" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu vm path=/run/vc/vm/b1
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.067000391+08:00" level=info msg="Adding extra file [0xc00006e758 0xc00006e540]" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qmp
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.067052182+08:00" level=info msg="launching /home/zhaoyang/qemu/build/qemu-system-x86_64 with: [-name sandbox-b1 -uuid b7a3ebee-039f-4407-b994-fdbe052ab4eb -machine microvm,accel=kvm,kernel_irqchip=split,confidential-guest-support=snp -cpu EPYC-v4,pmu=off -qmp unix:fd=3,server=on,wait=off -m 2048M,slots=10,maxmem=64920M -device virtio-serial-device,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/b1/console.sock,server=on,wait=off -device virtio-scsi-device,id=scsi0 -object sev-snp-guest,id=snp,cbitpos=51,reduced-phys-bits=1 -drive if=pflash,format=raw,readonly=on,file=/home/zhaoyang/kata-containers/tools/packaging/static-build/ovmf/opt/kata/share/ovmf/AMDSEV.fd -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-device,rng=rng0 -device vhost-vsock-device,vhostfd=4,id=vsock-29951875,guest-cid=29951875 -device virtio-9p-device,fsdev=extra-9p-kataShared,mount_tag=kataShared -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/b1/shared,security_model=none,multidevs=remap -rtc base=utc,driftfix=slew,clock=host -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic --no-reboot -object memory-backend-ram,id=dimm1,size=2048M -machine memory-backend=dimm1 -kernel /usr/share/kata-containers/vmlinuz-5.19.2-114-snp -initrd /usr/share/kata-containers/kata-containers-initrd-2024-04-11-15:23:52.602655872+0800-15e85b8ce -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k cryptomgr.notests net.ifnames=0 pci=lastbus=0 console=hvc0 console=hvc1 debug panic=1 nr_cpus=1 selinux=0 scsi_mod.scan=none agent.log=debug agent.log=debug initcall_debug -pidfile /run/vc/vm/b1/pid -smp 1,cores=1,threads=1,sockets=1,maxcpus=1]" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qmp
4月 12 14:29:41 public-Super-Server kata[2765242]: time="2024-04-12T14:29:41.08025403+08:00" level=info msg="Start logging QEMU (qemuPid=2765251)" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.003524615+08:00" level=info msg="QMP details" name=containerd-shim-v2 pid=2765242 qmp-Capabilities=oob qmp-major-version=6 qmp-micro-version=50 qmp-minor-version=1 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.015483789+08:00" level=error msg="qemu-system-x86_64: ../hw/i386/pc_sysfw_ovmf.c:131: pc_system_ovmf_table_find: Assertion `ovmf_flash_parsed' failed." name=containerd-shim-v2 pid=2765242 qemuPid=2765251 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.093793771+08:00" level=info msg="scanner return error: read unix @->/run/vc/vm/b1/qmp.sock: read: connection reset by peer" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qmp
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.094640535+08:00" level=error msg="Failed to negotiate QMP Capabilities" error="exitting QMP loop, command cancelled" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.133685363+08:00" level=info msg="Stopping Sandbox" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.13395677+08:00" level=warning msg="Unable to connect to unix socket (/run/vc/vm/b1/qmp.sock): dial unix /run/vc/vm/b1/qmp.sock: connect: no such file or directory" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qmp
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.134006252+08:00" level=error msg="Failed to connect to QEMU instance" error="dial unix /run/vc/vm/b1/qmp.sock: connect: no such file or directory" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.134070233+08:00" level=warning msg="failed to resolve vm path" dir=/run/vc/vm/b1 error="lstat /run/vc/vm/b1: no such file or directory" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.134112215+08:00" level=info msg="Cleanup vm path" dir=/run/vc/vm/b1 link= name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.134162376+08:00" level=debug msg="Endpoints removed" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=network
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.134192327+08:00" level=info msg="Network namespace \"/var/run/netns/cnitest-be62dbc2-5ee6-7bcb-9ebb-0319a0dcacfe\" deleted" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=network
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.135509944+08:00" level=debug msg="Deleting sandbox &{%!s(*cgroups.cgroup=&{0x564f96ef9860 [0xc000166340 0xc0005646c0 0xc0005646d0 0xc000564720 0xc000564730 0xc000564780 0xc000564790 0xc0005647a0 0xc0005647b0 0xc0000120f0 0xc000166360 0xc0005647f0 0xc000564870 0xc0000a2bd0] {0 0} <nil>}) /vc %!s(*specs.LinuxCPU=<nil>) [{%!s(bool=true) c %!s(*int64=0xc0000a25a8) %!s(*int64=0xc0000a25b0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a25d8) %!s(*int64=0xc0000a25e0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2608) %!s(*int64=0xc0000a2610) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2638) %!s(*int64=0xc0000a2640) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2668) %!s(*int64=0xc0000a2670) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2698) %!s(*int64=0xc0000a26a0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a26c8) %!s(*int64=0xc0000a26d0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a26f8) %!s(*int64=0xc0000a2700) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2a58) %!s(*int64=0xc0000a2a60) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2a88) %!s(*int64=0xc0000a2a90) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2b78) %!s(*int64=0xc0000a2b80) rwm} {%!s(bool=true) c %!s(*int64=0xc000015428) %!s(*int64=0xc000015440) m} {%!s(bool=true) b %!s(*int64=0xc000015428) %!s(*int64=0xc000015440) m} {%!s(bool=true) c %!s(*int64=0xc000015448) %!s(*int64=0xc000015440) rwm} {%!s(bool=true) c %!s(*int64=0xc0000154c0) %!s(*int64=0xc0000154c8) rwm}] {%!s(int32=0) %!s(uint32=0)}} resource controler" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=sandbox
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.293829526+08:00" level=info msg="Stop logging QEMU (qemuPid=2765251)" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers/hypervisor subsystem=qemu
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.305228793+08:00" level=error msg="failed to cleanup the &{%!s(*cgroups.cgroup=&{0x564f96ef9860 [0xc000166340 0xc0005646c0 0xc0005646d0 0xc000564720 0xc000564730 0xc000564780 0xc000564790 0xc0005647a0 0xc0005647b0 0xc0000120f0 0xc000166360 0xc0005647f0 0xc000564870 0xc0000a2bd0] {0 0} <nil>}) /vc %!s(*specs.LinuxCPU=<nil>) [{%!s(bool=true) c %!s(*int64=0xc0000a25a8) %!s(*int64=0xc0000a25b0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a25d8) %!s(*int64=0xc0000a25e0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2608) %!s(*int64=0xc0000a2610) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2638) %!s(*int64=0xc0000a2640) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2668) %!s(*int64=0xc0000a2670) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2698) %!s(*int64=0xc0000a26a0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a26c8) %!s(*int64=0xc0000a26d0) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a26f8) %!s(*int64=0xc0000a2700) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2a58) %!s(*int64=0xc0000a2a60) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2a88) %!s(*int64=0xc0000a2a90) rwm} {%!s(bool=true) c %!s(*int64=0xc0000a2b78) %!s(*int64=0xc0000a2b80) rwm} {%!s(bool=true) c %!s(*int64=0xc000015428) %!s(*int64=0xc000015440) m} {%!s(bool=true) b %!s(*int64=0xc000015428) %!s(*int64=0xc000015440) m} {%!s(bool=true) c %!s(*int64=0xc000015448) %!s(*int64=0xc000015440) rwm} {%!s(bool=true) c %!s(*int64=0xc0000154c0) %!s(*int64=0xc0000154c8) rwm}] {%!s(int32=0) %!s(uint32=0)}} resource controllers" error="cgroups: unable to remove paths /sys/fs/cgroup/systemd/kata_overhead/b1" name=containerd-shim-v2 pid=2765242 sandbox=b1 source=virtcontainers subsystem=sandbox
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.305498781+08:00" level=info msg="Cleanup agent" name=containerd-shim-v2 path=/run/kata-containers/shared/sandboxes/b1/shared pid=2765242 sandbox=b1 source=virtcontainers subsystem=fs_share
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.306813957+08:00" level=warning msg="failed to cleanup network" error="failed to get netns /var/run/netns/cnitest-be62dbc2-5ee6-7bcb-9ebb-0319a0dcacfe: failed to Statfs \"/var/run/netns/cnitest-be62dbc2-5ee6-7bcb-9ebb-0319a0dcacfe\": no such file or directory" id=/var/run/netns/cnitest-be62dbc2-5ee6-7bcb-9ebb-0319a0dcacfe name=containerd-shim-v2 pid=2765242 sandbox=b1 source=katautils
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.306888619+08:00" level=debug msg="Create() end" container=b1 name=containerd-shim-v2 pid=2765242 sandbox=b1 source=containerd-kata-shim-v2
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.309952995+08:00" level=debug msg="Delete() start" container=b1 name=containerd-shim-v2 pid=2765242 sandbox=b1 source=containerd-kata-shim-v2
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.310049318+08:00" level=debug msg="Delete() end" container=b1 name=containerd-shim-v2 pid=2765242 sandbox=b1 source=containerd-kata-shim-v2
4月 12 14:29:44 public-Super-Server kata[2765242]: time="2024-04-12T14:29:44.310344506+08:00" level=debug msg="Shutdown() start" container=b1 name=containerd-shim-v2 pid=2765242 sandbox=b1 source=containerd-kata-shim-v2
`

**Comment by peng-yq** [comment]
> Hello, I see that kata3.1 and 3.2 versions support sev-snp now, but when I install and run according to the documents, I have encountered the following problems, may I ask whether there is still a problem in the current code or my configuration is wrong ![微信图片_20240409133323](https://private-user-images.githubusercontent.com/127105680/320732003-2a34f998-9208-473c-b0d8-15a1515727e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjkzNDQsIm5iZiI6MTcyNzE2OTA0NCwicGF0aCI6Ii8xMjcxMDU2ODAvMzIwNzMyMDAzLTJhMzRmOTk4LTkyMDgtNDczYy1iMGQ4LTE1YTE1MTU3MjdlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwOTEwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGM4ZjE0NjQ3MzNmMWMwYWY1MDExMDRkYzJkNjI4ZTY1YTRlYWI0NTU0NGU0M2IyNWViMDcyNTEyOTA0Mzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GueJLZIdSrngQfUJFoCZmEVmfQboJUrtz0yzZdMfPGQ)
> 
> And I would like to ask if there is any documentation on how specifically kata supports sev/snp, such as its specific architecture implementation, thank you very much

How did you solve this problem? I would also like to ask what document did you refer to when running confidential containers in AMD SEV? Any answer is appreciated.
