### ISSUE TITLE
CC: run on-TEE jobs configured with CRI-O

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#9474]
@bpradipt asked if we could have a CI job to run the non-TEE CoCo tests with CRI-O for the sake of CoCo's 0.9.0 release.

After a brief chat (see https://cloud-native.slack.com/archives/C06UCUCG744) we agreed on creating a new job, using k0s and the default ubuntu based guest image, configured with CRI-O.

Cc @bpradipt @stevenhorsman @ldoktor @fidencio

**Comment by bpradipt** [comment]
@wainersm afaik 1.29 has all the coco pieces. The crio runtimeclass config does need a config option `runtime_pull_image = true`  to allow in-guest image pull. Example
```
[crio.runtime.runtimes.kata-cc-snp]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_root = "/run/vc"
runtime_type = "vm"
privileged_without_host_devices = true
runtime_config_path = "/usr/share/defaults/kata-containers/configuration-qemu-snp.toml"
runtime_pull_image = true
```

However the best person to confirm is @littlejawa

**Comment by littlejawa** [comment]
@wainersm @bpradipt  - yes, the 1.29 version should be good. The changes we need are in cri-o 1.28 and higher.

And the `runtime_pull_image` flag is the only other change needed.

**Comment by wainersm** [comment]
> @wainersm @bpradipt - yes, the 1.29 version should be good. The changes we need are in cri-o 1.28 and higher.
> 
> And the `runtime_pull_image` flag is the only other change needed.

Thanks @littlejawa ! 

@fidencio help needed... I was looking at kata-deploy.sh to see how it handles CRI-O. It doesn't set that ^^^^ `runtime_pull_image` property in cri-o conf, indeed CoCo for CRI-O was never tested upstream to the best of my knowledge. Could you confirm (or not) that? Just in case I am missing something...

So, I thought in having a new environment variable for kata-deploy called `PULL_TYPE`. In case of `runtime==CRIO` and `PULL_TYPE==guest-pull` then kata-deploy adds the `runtime_pull_image` property to crio's config. I will need to change the gha.sh script for CI as well as the CoCo's operator for peer pods. Is this the correct way to add that support?
