### ISSUE TITLE
Update maintenance statement in upgrading doc

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#956]
PR #941 got merged before we'd finalised the wording for the maintenance statement / warning (my fault - I should have added a `dnm` label):

- https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/Upgrading.md#maintenance-warning

We need to decide if the current wording is reasonable given that maintaining *each* stable branches has an associated cost to the community.

/cc @kata-containers/architecture-committee.

**Comment by cmaf** [comment]
@jodh-intel can we close this issue or does the wording need a (different) update?

**Comment by stevenhorsman** [comment]
This doc has been re-work as we are no longer maintaining stable branches, so I believe this issue can be closed
