### ISSUE TITLE
kata-monitor: should support all configured kata shims

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#957]
Currently the kata-monitor will look @ shims with name kata-v2. ie: `io.containerd.kata.v2`

We support a few common configurations for Kata, including:
```
io.containerd.kata.v2
io.containerd.kata-qemu.v2
io.containerd.kata-clh.v2
```

We should for these types of sandboxes as well.

**Comment by egernst** [comment]
@liubin  WDYT?

**Comment by liubin** [comment]
The fast and simple way is to use a regex like `io.containerd.kata*` ?

**Comment by egernst** [comment]
Yeah, that looks good to me. I can try to test this tomorrow, unless you beat me to it! :)
