### ISSUE TITLE
docs: kata-monitor has a couple of errors

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#958]
When running through kata-monitor docs for running prometheus I noticed:
1) we should just write the example PortNumber. ie: https://github.com/kata-containers/kata-containers/blame/2.0-dev/docs/how-to/how-to-set-prometheus-in-k8s.md#L47
2) The kata-monitor daemonset refers to an image that doesn't exist. Can we create this image on the katadocker page on docker hub? Can we add the example Dockerfile for this?
3) For applying the grafana, I believe the port used is incorrect here: should be 30000? https://github.com/kata-containers/kata-containers/blame/2.0-dev/docs/how-to/how-to-set-prometheus-in-k8s.md#L99

**Comment by fidencio** [comment]
@egernst, is this still an issue? @fgiudici, @liubin, what's the status of the documentation nowadays?

**Comment by fgiudici** [comment]
I think this can be closed:
seems to me we are fine with both Prometheus and Grafana port numbers.
For the daemonset image... well, I think we lost it in the migration to quay.io, but we have a dedicated issue for that:
https://github.com/kata-containers/kata-containers/issues/2421

I would close this one.

**Comment by fidencio** [comment]
Thanks for confirming @fgiudici!

@egernst, I'm closing this one now.  Feel free to re-open it though in case you feel the need to do so.
