### ISSUE TITLE
virtio-9p: 9pfs does not honor open file handles on unlinked files

### ISSUE THREAD

**Issue by l8huang** [kata-containers/kata-containers#9700]
When running iperf in kata-container with config `shared_fs = "virtio-9p"`, the iperf3 server reports error:
```
iperf3: error - unable to create a new stream: No such file or directory
```

In the guest VM, strace shows that  error happened when iperf3 ftruncate the tmp file after unlink it:
```
openat(AT_FDCWD, "/tmp/iperf3.HzTTUh", O_RDWR|O_CREAT|O_EXCL, 0600) = 11
unlink("/tmp/iperf3.HzTTUh")            = 0
ftruncate(11, 131072)                   = -1 ENOENT (No such file or directory)
 ```

This is a known QEMU bug:
9pfs does not honor open file handles on unlinked files(https://bugs.launchpad.net/qemu/+bug/1336794)

**Comment by Apokleos** [comment]
Hi @l8huang is virtio-9p necessary? IMO, virtiofs may be more popular in Kata now.

**Comment by l8huang** [comment]
9p is still supported, this issue can be use to reveal the known bug.

**Comment by Apokleos** [comment]
Yeah, I saw you post about the issue on slack just now. And I find a [related issue](https://github.com/kata-containers/kata-containers/issues/9611). 
Possible mismatch between kernel version and virtiofs version I think.

**Comment by zvonkok** [comment]
This is a known bug, you should try to use `shared_fs=none` and setup containerd `devmapper`

**Comment by l8huang** [comment]
ref: https://github.com/kata-containers/kata-containers/pull/7001/files#r1447185512
