### ISSUE TITLE
runtime: Add support for directly attachable network

### ISSUE THREAD

**Issue by justxuewei** [kata-containers/kata-containers#9758]
The runtime-rs has already implemented a directly attachable network by https://github.com/kata-containers/kata-containers/pull/7383 to fix https://github.com/kata-containers/kata-containers/issues/1922. It could be ported to the runtime for customizing container networks.

**Comment by l8huang** [comment]
please assign it to me

**Comment by l8huang** [comment]
@justxuewei @lifupan  could you please review https://github.com/kata-containers/kata-containers/pull/9868?

**Comment by l8huang** [comment]
Considering VFIO network device need a driver to be claimed in guest VM, should I raise a PR(like https://github.com/kata-containers/kata-containers/pull/6595) to add a pre-built kernel which includes the netdev driver(e.g. https://github.com/kata-containers/kata-containers/pull/9620) into kata-deploy image? I'm not sure if there are concerns regarding the size of the kata-deploy image.

CC @zvonkok
