### ISSUE TITLE
Align Kata OCI Spec with Latest Runtime-Spec using oci-spec-rs

### ISSUE THREAD

**Issue by Apokleos** [kata-containers/kata-containers#9766]
**Which feature do you think can be improved?**

The Rust implementation of [the Kata OCI Spec](https://github.com/kata-containers/kata-containers/blob/main/src/libs/oci/src/lib.rs) is dedicated to kata containers based on the [ the OCI runtime spec](https://github.com/opencontainers/runtime-spec). However, open source project [oci-spec-rs](https://github.com/containers/oci-spec-rs) is another implementation of the OCI specification, and it adheres more closely to the standard compared to the Kata OCI Spec.

To maintain alignment with the OCI-Spec and ensure adherence to the evolving container standards, we propose transitioning the Kata OCI Spec implementation to utilize another open-source project 

**How can it be improved?**

We propose integrating oci-spec-rs into our Kata OCI Spec implementation to ensure compatibility and simplify maintenance.

**Comment by Apokleos** [comment]
cc @lifupan @bergwolf @zvonkok @fidencio

**Comment by zvonkok** [comment]
+1 for this. Tag me on the PR for review.
