### ISSUE TITLE
runtime:  the func countFiles() does not work as expected

### ISSUE THREAD

**Issue by gaohuatao-1** [kata-containers/kata-containers#9780]
# Description of problem
I find a bug when I test func countFiles(path string, limit int) (numFiles int, err error) (link:https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/mount.go#L369). The func countFiles can not satisfy

When the number of regular files in the subfolder of **path** exceeds the **limit**, this function does not return -1, but  it only subtracts one from the number of files counted.
I set the path as "/root/gaohuatao/config-volume". The files within the path is as below.  The number of regular files under config-volume/ght/ dir is 10  and the limit is 8, but countFiles did not return the expected value -1.

![image](https://github.com/kata-containers/kata-containers/assets/22569211/00d7555a-812d-4327-8418-fa587ec15367)

# Expected result
If the total number of files observed under the **path** is greater than the limit, the func countFiles should break and return -1.
The path should not be watchable.

# Actual result
When the total number of files observed is greater than the limit,  the func countFiles returns a wrong value. 
In the scene shown above, the path with 15 files that exceeds the limit is still watchable bind and this is not as expected.

# Further information
The same problem exists in runtime-rs.

**Comment by Apokleos** [comment]
Hi @gaohuatao-1 do you have addressed this problem ? If fine, welcome the PR!

**Comment by gaohuatao-1** [comment]
> Hi @gaohuatao-1 do you have addressed this problem ? If fine, welcome the PR!

Yes, PTAL.
