### ISSUE TITLE
set_sandbox_storage() returns wrong result

### ISSUE THREAD

**Issue by jiangliu** [kata-containers/kata-containers#98]
# Description of problem

    Function set_sandbox_storage() is designed to return true when the
    reference count drops from 1 to 0. But current implementation always
    return true no matter the reference count is, which may cause removing
    an in use mountpoint.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by lifupan** [comment]
Since the issue has been fixed, close this issue.
