### ISSUE TITLE
Let  `kata-monitor` support CRI-O

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#980]
Now `kata-monitor` only support containerd.

**Comment by ariel-adam** [comment]
@liubin what do we use kata-monitor for :-)? 
@fidencio do you think we need to add it?

**Comment by fidencio** [comment]
@ariel-adam, thanks for bringing this to my attention.

This is something that I have as part of my backlog and I will be working on it as soon as we finish the whole (and not exactlt related) task about CRI stats vs cAdvisor metrics on CRI-O.

I've assigned this one to myself.

**Comment by ariel-adam** [comment]
Cool, thanks :-)

**Comment by fgiudici** [comment]
Yep, we can close this, thanks @liubin (missing the super-powers to close it myself) !

**Comment by fgiudici** [comment]
Implementation is done: PR https://github.com/kata-containers/kata-containers/pull/2233
Still missing documentation update
