### ISSUE TITLE
runtime-rs: container start fails under cri-o

### ISSUE THREAD

**Issue by pmores** [kata-containers/kata-containers#9847]
When cri-o tries to launch a runtime-rs pod it fails with
```
ERROR: containerd-shim-kata-v2 failed: shim start

Caused by:
   0: do start
   1: failed to get bundle path
   2: No such file or directory (os error 2): connect: invalid argument
```
This happens when the shim is launched with the "start" argument and `container_type` is `ContainerType::PodContainer` in [`ShimExecutor::do_start()`](https://github.com/kata-containers/kata-containers/blob/824287d64a9f030c7d796b34e330aba341a3feca/src/runtime-rs/crates/shim/src/shim_start.rs#L35).  [`ShimExecutor::get_shim_info_from_sandbox()`](https://github.com/kata-containers/kata-containers/blob/824287d64a9f030c7d796b34e330aba341a3feca/src/runtime-rs/crates/shim/src/shim_start.rs#L109) is then called which tries to derive the path to the sandbox bundle from the container bundle the shim is currently running in.

This fails since the bundle directory structure is different between containerd and cri-o (containerd stores the bundles in `<container_root>/<sandbox_id>` and `<container_root>/<container_id>` while cri-o in `<container_root>/<sandbox_id>/userdata` and `<container_root>/<container_id>/userdata`, respectively).

Having discussed this with @littlejawa we believe that the shim shouldn't try to access the sandbox bundle in the first place while starting a container.  For a smoke test, I've removed the offending code locally and have been running with it for a bit, having observed no ill effects so far.

Do you folks agree that this is the right solution?  Admittedly I'm not clear what the reason for the current shim behaviour was in the first place so I might be missing something.

**Comment by gkurz** [comment]
@pmores Please create a PR with your proposed change. It will be easier to discuss there.
