### ISSUE TITLE
CI: fix `kata-containers-ci-on-push / run-k8s-tests-on-aks / run-k8s-tests (cbl-mariner, *)` jobs 

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#9855]
The following jobs have failed at least 5 out of last 10 executions on the nightly CI (see https://github.com/kata-containers/kata-containers/issues/9506#issuecomment-2168522061).

 * kata-containers-ci-on-push / run-k8s-tests-on-aks / run-k8s-tests (cbl-mariner, clh, small, oci-distribution): (10) fail=7 skips=0
 * kata-containers-ci-on-push / run-k8s-tests-on-aks / run-k8s-tests (cbl-mariner, clh, small, containerd): (10) fail=7 skips=0

**Comment by wainersm** [comment]
Hi @danmihai1 !

I would normally be disabling these jobs but I know your team has actively monitored and fixed cbl-mariner jobs. So I will touch on them, unless you want me to do so.

**Comment by danmihai1** [comment]
> Hi @danmihai1 !
> 
> I would normally be disabling these jobs but I know your team has actively monitored and fixed cbl-mariner jobs. So I will touch on them, unless you want me to do so.

@wainersm I believe these are fixed now. We had two recent PR collisions with the new yq command line format, but they were fixed with:

- https://github.com/kata-containers/kata-containers/pull/9844
- https://github.com/kata-containers/kata-containers/pull/9809

**Comment by wainersm** [comment]
> > Hi @danmihai1 !
> > I would normally be disabling these jobs but I know your team has actively monitored and fixed cbl-mariner jobs. So I will touch on them, unless you want me to do so.
> 
> @wainersm I believe these are fixed now. We had two recent PR collisions with the new yq command line format, but they were fixed with:
> 
>     * [tests: fix yq command line in k8s-policy-pvc #9844](https://github.com/kata-containers/kata-containers/pull/9844)
> 
>     * [tests: k8s: use newer yq command line format #9809](https://github.com/kata-containers/kata-containers/pull/9809)

Great! So I will close this issue and we can check again next week.
