### ISSUE TITLE
Upgrade the default qemu version from 7.2.0 to 7.2.12 / 8 / 9

### ISSUE THREAD

**Issue by avizack18** [kata-containers/kata-containers#9858]
Is it possible to upgarde the default qemu version from 7.2.0 to the latest 7.2.12 and maybe support qemu 8 and 9 versions?

**Comment by fitzthum** [comment]
See https://github.com/kata-containers/kata-containers/pull/9149

**Comment by gkurz** [comment]
Fixed by #9149
