### ISSUE TITLE
whern intergrating k8s,  fail to connect  kata vm with socat 

### ISSUE THREAD

**Issue by magnate3** [kata-containers/kata-containers#989]
there is no output when I use socat "stdin,raw,echo=0,escape=0x11" "unix-connect:${console}"

firstly,I have succed to connect kata container with socat when I not using k8s and containerd, but when I create kata container with k8s and I fail to to connect kata container with socat.

executing the cmd :  lsof -n -p "pid of qemu vm "  and not find console.sock

**Comment by jodh-intel** [comment]
@magnate3 - please provide the output of `kata-collect-data.sh` as requested on the issue template.

**Comment by cmaf** [comment]
Hi @magnate3, due to inactivity I'm closing this issue. Please do reopen if you are experiencing the issue.
