### ISSUE TITLE
virtio-fs is not working on arm

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#990]
ARM CI failed on vsock connection:

> /home/jenkins/workspace/kata-containers-2.0-tests-ubuntu-ARM-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:72
E1017 15:59:09.796113   19365 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create containerd task: Failed to check if grpc server is working: rpc error: code = DeadlineExceeded desc = timed out connecting to vsock 2569143870:1024: unknown
Oct 17 15:59:09.799: INFO: Unexpected error occurred: rpc error: code = Unknown desc = failed to create containerd task: Failed to check if grpc server is working: rpc error: code = DeadlineExceeded desc = timed out connecting to vsock 2569143870:1024: unknown

Guest kernel was built with vsock support:
```
  CC      net/vmw_vsock/af_vsock.o
  CC      drivers/cpuidle/governor.o
  CC      net/vmw_vsock/af_vsock_tap.o
```

And qemu was built with vsock support as well:
```
vhost-crypto support yes
vhost-scsi support yes
vhost-vsock support yes
vhost-user support yes
vhost-user-fs support yes
```

It seems that qemu failed to connect to virtiofsd.
> time="2020-10-17T15:58:53.624585624Z" level=info msg="New client" pid=19785 sandbox=58d5c100620c34e32fdb19793f623ece2d47a9198c24a657eb6315e7a07a1eb3 source=virtcontainers subsystem=kata_agent url="vsock://915552965:1024"
time="2020-10-17T15:58:53.657701869Z" level=info msg="virtiofsd quits" pid=19772 sandbox=12d11ac68ca8489be634071838cd201443a9b6cf9496e31c6a06b29c20ae42ad source=virtcontainers subsystem=qemu
time="2020-10-17T15:58:53.658670898Z" level=info msg="Stopping Sandbox" pid=19772 sandbox=12d11ac68ca8489be634071838cd201443a9b6cf9496e31c6a06b29c20ae42ad source=virtcontainers subsystem=qemu
time="2020-10-17T15:58:53.659844802Z" level=debug msg="qemu-system-aarch64: warning: global kvm-pit.lost_tick_policy has invalid class name" pid=19772 sandbox=12d11ac68ca8489be634071838cd201443a9b6cf9496e31c6a06b29c20ae42ad source=virtcontainers subsystem=qemu
time="2020-10-17T15:58:53.660330997Z" level=debug msg="qemu-system-aarch64: Failed to read from slave." pid=19772 sandbox=12d11ac68ca8489be634071838cd201443a9b6cf9496e31c6a06b29c20ae42ad source=virtcontainers subsystem=qemu

**Comment by Jakob-Naucke** [comment]
Chiming in due to similar issues on s390x.
I have the same features supported in the guest kernel and QEMU (using commit # `8c1c0792`, the PR commit that features the `vhost-user-fs-ccw` device. That commit of QEMU also works with Kata on x86_64.)
Logs look similar with `virtiofsd quits` immediately after `New client`.
/cc @huoqifeng since you seemed interested in this as per kata-containers/runtime#2939

**Comment by Jakob-Naucke** [comment]
@bergwolf do you have an idea about how this could be investigated?

**Comment by Jakob-Naucke** [comment]
No, my issues on s390x were due to memory backends not being added because DIMM is not supported, see https://github.com/kata-containers/govmm/pull/161

**Comment by jongwu** [comment]
virtio-fs works on arm, thus, it seems this issue can be closed.
