### ISSUE TITLE
`grpc.GetOOMEventRequest` generate too many errors

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#991]
If pod starting failed, or in the shutdown progress(after agent is marked as dead), there will be too many logs:

```
Oct 19 02:57:51 master kata[5897]: time="2020-10-19T02:57:51.647599915Z" level=warning
msg="failed to get OOM event from sandbox" 
error="read vsock host(2):58864318->vm(3237919778):1024: connection reset by peer" 
pid=5897 sandbox=98da9d8884b0ffd0fdf3ed2737047803a2f311b154d4fc799a3d75093493b6e1 source=containerd-kata-shim-v2
```

Except:

After agent dead, should not try the `grpc.GetOOMEventRequest` any more.

**Comment by liubin** [comment]
https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/runtime/containerd-shim-v2/wait.go#L152

Maybe we should need a mechanism to  know if agent is dead.

**Comment by jodh-intel** [comment]
> Maybe we should need a mechanism to know if agent is dead.

@liubin - I agree. You've just reminded me... I saw some unexpected behaviour when I was playing with `agent-ctl` for https://github.com/kata-containers/kata-containers/pull/965. If the agent isn't running, the client (`agent-ctl`) will get an immediate error of course. However, if `agent-ctl` connects to the agent and the agent then panics, the `agent-ctl` client just hangs forever, even if I specify `--timeout 1s`. I haven't had a chance to look into this yet but it's not ideal behaviour.

I guess "a" solution might be to make a new API call (`Check` call using the health API service) but I haven't tested that.

**Comment by liubin** [comment]
And got :
```
Nov 09 14:24:04 ubuntu1804-azure49af40 kata[32451]: time="2020-11-09T14:24:04.883949687Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=32451 sandbox=39e713a0d02e6c3709c66ef29560700f0a1134d6ac699a2687d9fe8f811da8d5 source=containerd-kata-shim-v2
```
In http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/437/

**Comment by liubin** [comment]
Some strange logs from http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/442/ :

cloudHypervisor is stopped, and then "failed to get OOM event from sandbox", and "mark agent dead", no noisy logs found.

```
Nov 10 05:59:40 ubuntu1804-azureb9a7c0 kata[8823]: time="2020-11-10T05:59:40.448904962Z" level=info msg="Stopping Cloud Hypervisor" PID=8834 pid=8823 sandbox=ce6f66781970931d70c2ce67a34d049d9dc6309c0789bbf790e141e1973169e6 source=virtcontainers subsystem=cloudHypervisor
Nov 10 05:59:40 ubuntu1804-azureb9a7c0 kata[8823]: time="2020-11-10T05:59:40.508502817Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=8823 sandbox=ce6f66781970931d70c2ce67a34d049d9dc6309c0789bbf790e141e1973169e6 source=containerd-kata-shim-v2
Nov 10 05:59:40 ubuntu1804-azureb9a7c0 kata[8823]: time="2020-11-10T05:59:40.721444034Z" level=info msg="mark agent dead" pid=8823 sandbox=ce6f66781970931d70c2ce67a34d049d9dc6309c0789bbf790e141e1973169e6 source=virtcontainers subsystem=kata_agent

Nov 10 05:59:40 ubuntu1804-azureb9a7c0 kata[8823]: time="2020-11-10T05:59:40.721552941Z" level=info msg="mark agent dead" pid=8823 sandbox=ce6f66781970931d70c2ce67a34d049d9dc6309c0789bbf790e141e1973169e6 source=virtcontainers subsystem=kata_agent
```
